PARAMETERS AA
SELECT IZBOR
IF EOF()
   GO BOTTOM
ENDIF
GOTO AA
*TPNAZIV=ALLTRIM(PNAZIV)
PUBLIC TGKREDNI
TGKREDNI=ALLTRIM(SIFPROD)
CLOSE ALL TABLES
KNAL='NAL'+TGKREDNI
DO FORM AANALI
AAIZBORNAL.release
KEYBOARD '{ENTER}'
