PARAMETERS AA
SELECT IZBOR
IF EOF()
   GO BOTTOM
ENDIF
GOTO AA
TPNAZIV=ALLTRIM(PNAZIV)
PUBLIC TBLREDNI,TBLKONTO
TBLREDNI=ALLTRIM(SIFPROD)
TBLKONTO=KONTO
CLOSE ALL TABLES
TOBJEKAT='B'
KBL='BL'+TBLREDNI
DO FORM AABLI
AAIZBORBL.release
KEYBOARD '{ENTER}'
