PUSH KEY CLEAR
IF RECCOUNT()<10
   SELECT IZBOR
   APPEND BLANK
   REPLACE SIFPROD WITH str(recno(),2,0)
   REPLACE PNAZIV WITH 'GLAVNA KNJIGA '+SIFPROD  
   SELECT izbor
   DO FORM AAIZBORNALK
   CLOSE ALL TABLES
   DO DBdata03
   DO dbdata04
   USE AANAL IN 0 ALIAS IZBOR
ENDIF
POP KEY   
AAIZBORNALTAB.GRD0.SETFOCUS
AAIZBORNALTAB.REFRESH
