PARAMETERS AA
SELECT IZBOR
IF EOF()
   GO BOTTOM
ENDIF
GOTO AA
TPNAZIV=ALLTRIM(PNAZIV)
PUBLIC TBLREDNI,TBLKONTO
TBLREDNI=ALLTRIM(SIFPROD)
TBLKONTO=KONTO
TOBJEKAT='KA'
PUBLIC TKAREDNI
TKAREDNI=ALLTRIM(SIFPROD)
CLOSE ALL TABLES
KKAMATE='KAMATE'+TKAREDNI
KKAKOEF='KAKOEF'+TKAREDNI
KKASTOP='KASTOP'+TKAREDNI
DO FORM AAKAI
AAIZBORKA.release
KEYBOARD '{ENTER}'
