PARAMETERS MI,MSIFPROD,MPNAZIV,MPRIKAZ
   MSIFPROD=SIFPROD
   MPNAZIV=PNAZIV
   IF PRIKAZ<>'N'.AND.MI=1
      AAIZBORNAL.CMD1.VISIBLE=.T.
      AAIZBORNAL.CMD1.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=2
      AAIZBORNAL.CMD2.VISIBLE=.T.
      AAIZBORNAL.CMD2.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=3
      AAIZBORNAL.CMD3.VISIBLE=.T.
      AAIZBORNAL.CMD3.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=4
      AAIZBORNAL.CMD4.VISIBLE=.T.
      AAIZBORNAL.CMD4.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=5
      AAIZBORNAL.CMD5.VISIBLE=.T.
      AAIZBORNAL.CMD5.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=6
      AAIZBORNAL.CMD6.VISIBLE=.T.
      AAIZBORNAL.CMD6.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=7
      AAIZBORNAL.CMD7.VISIBLE=.T.
      AAIZBORNAL.CMD7.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=8
      AAIZBORNAL.CMD8.VISIBLE=.T.
      AAIZBORNAL.CMD8.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=9
      AAIZBORNAL.CMD9.VISIBLE=.T.
      AAIZBORNAL.CMD9.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=10
      AAIZBORNAL.CMD10.VISIBLE=.T.
      AAIZBORNAL.CMD10.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   
