PARAMETERS MI,MSIFPROD,MPNAZIV,MKONTO,MPRIKAZ
   MSIFPROD=SIFPROD
   MPNAZIV=PNAZIV
   MKONTO=KONTO
   IF PRIKAZ<>'N'.AND.MI=1
      AAIZBORPR.CMD1.VISIBLE=.T.
      AAIZBORPR.CMD1.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=2
      AAIZBORPR.CMD2.VISIBLE=.T.
      AAIZBORPR.CMD2.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=3
      AAIZBORPR.CMD3.VISIBLE=.T.
      AAIZBORPR.CMD3.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=4
      AAIZBORPR.CMD4.VISIBLE=.T.
      AAIZBORPR.CMD4.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=5
      AAIZBORPR.CMD5.VISIBLE=.T.
      AAIZBORPR.CMD5.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=6
      AAIZBORPR.CMD6.VISIBLE=.T.
      AAIZBORPR.CMD6.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=7
      AAIZBORPR.CMD7.VISIBLE=.T.
      AAIZBORPR.CMD7.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=8
      AAIZBORPR.CMD8.VISIBLE=.T.
      AAIZBORPR.CMD8.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=9
      AAIZBORPR.CMD9.VISIBLE=.T.
      AAIZBORPR.CMD9.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=10
      AAIZBORPR.CMD10.VISIBLE=.T.
      AAIZBORPR.CMD10.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=11
      AAIZBORPR.CMD11.VISIBLE=.T.
      AAIZBORPR.CMD11.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=12
      AAIZBORPR.CMD12.VISIBLE=.T.
      AAIZBORPR.CMD12.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=13
      AAIZBORPR.CMD13.VISIBLE=.T.
      AAIZBORPR.CMD13.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=14
      AAIZBORPR.CMD14.VISIBLE=.T.
      AAIZBORPR.CMD14.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=15
      AAIZBORPR.CMD15.VISIBLE=.T.
      AAIZBORPR.CMD15.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=16
      AAIZBORPR.CMD16.VISIBLE=.T.
      AAIZBORPR.CMD16.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=17
      AAIZBORPR.CMD17.VISIBLE=.T.
      AAIZBORPR.CMD17.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=18
      AAIZBORPR.CMD18.VISIBLE=.T.
      AAIZBORPR.CMD18.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=19
      AAIZBORPR.CMD19.VISIBLE=.T.
      AAIZBORPR.CMD19.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=20
      AAIZBORPR.CMD20.VISIBLE=.T.
      AAIZBORPR.CMD20.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=21
      AAIZBORPR.CMD21.VISIBLE=.T.
      AAIZBORPR.CMD21.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=22
      AAIZBORPR.CMD22.VISIBLE=.T.
      AAIZBORPR.CMD22.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=23
      AAIZBORPR.CMD23.VISIBLE=.T.
      AAIZBORPR.CMD23.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=24
      AAIZBORPR.CMD24.VISIBLE=.T.
      AAIZBORPR.CMD24.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=25
      AAIZBORPR.CMD25.VISIBLE=.T.
      AAIZBORPR.CMD25.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
