PARAMETERS MI,MSIFPROD,MPNAZIV,MPRIKAZ
   MSIFPROD=SIFPROD
   MPNAZIV=PNAZIV
   IF PRIKAZ<>'N'.AND.MI=1
      AAIZBORKA.CMD1.VISIBLE=.T.
      AAIZBORKA.CMD1.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=2
      AAIZBORKA.CMD2.VISIBLE=.T.
      AAIZBORKA.CMD2.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=3
      AAIZBORKA.CMD3.VISIBLE=.T.
      AAIZBORKA.CMD3.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=4
      AAIZBORKA.CMD4.VISIBLE=.T.
      AAIZBORKA.CMD4.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=5
      AAIZBORKA.CMD5.VISIBLE=.T.
      AAIZBORKA.CMD5.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=6
      AAIZBORKA.CMD6.VISIBLE=.T.
      AAIZBORKA.CMD6.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=7
      AAIZBORKA.CMD7.VISIBLE=.T.
      AAIZBORKA.CMD7.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=8
      AAIZBORKA.CMD8.VISIBLE=.T.
      AAIZBORKA.CMD8.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=9
      AAIZBORKA.CMD9.VISIBLE=.T.
      AAIZBORKA.CMD9.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=10
      AAIZBORKA.CMD10.VISIBLE=.T.
      AAIZBORKA.CMD10.CAPTION=MSIFPROD+'-'+MPNAZIV
   ENDIF 
   
