PUSH KEY CLEAR
IF RECCOUNT()<99
   APPEND BLANK
   REPLACE SIFPROD WITH str(recno(),2,0)
   replace pordn WITH 'D'
   replace PRENCEN WITH 'D'
   replace NABCENA WITH 'N'
   replace PRACENJE WITH 'D'
   replace UNKOL WITH 'N'
   replace TNIVEL WITH 'N'
   replace AZURIRAJ WITH 'N'
   replace KORIGUJMC WITH 'N'
   replace MCMARZA WITH 'N'
   replace PROMKOL WITH 'D'
   replace PRIKAZ WITH 'D'
   replace VERIFIKAC WITH 'N'
   replace KUKALKP WITH 'N'
   replace KEUKALKP WITH 'N'
   replace FLAGER WITH 'D'
   replace FTPUTNIK WITH 'N'
   IF AMIZBOR='TV'
      REPLACE DOK WITH 'V'+ALLTRIM(SIFPROD)
      REPLACE KONTO WITH '1320      '
      REPLACE KONTOU WITH '6120      '
      REPLACE KONTOPAZ WITH '1320     '
      REPLACE KONTOK WITH '8800      '
   ELSE
      REPLACE DOK WITH 'M'+ALLTRIM(SIFPROD)
      REPLACE KONTO WITH '1340      '
      REPLACE KONTOU WITH '6120      '
      REPLACE KONTOPAZ WITH '1340     '
      REPLACE KONTOK WITH '8800      '
   ENDIF   
   IF AMIZBOR='TV'
      REPLACE PNAZIV WITH 'MAGACIN '+SIFPROD  
      DO DODAJVRNAL WITH 'TV','V',ALLTRIM(SIFPROD)
      SELECT IZBOR
      SCATTER NAME POLJA
      USE TRGPAR IN 0
      SELECT TRGPAR
      APPEND BLANK
      GATHER NAME POLJA
           REPLACE PKGK WITH 'D'
            REPLACE PKAN WITH 'D'
            REPLACE PKTM WITH 'D'
            REPLACE PKKP WITH 'D'
            REPLACE PKPDV WITH 'D'
            REPLACE PNGK WITH 'D'
            REPLACE PNTM WITH 'D'
            REPLACE PNKP WITH 'D'
            REPLACE PFGK WITH 'D'
            REPLACE PFAN WITH 'D'
            REPLACE PFTM WITH 'D'
            REPLACE PFKP WITH 'D'
            REPLACE PFPDV WITH 'D'
            REPLACE PFKPO WITH 'D'           
      USE
      SELECT IZBOR
   ELSE
      REPLACE PNAZIV WITH 'PRODAVNICA '+SIFPROD  
      DO DODAJVRNAL WITH 'TM','M',ALLTRIM(SIFPROD)
      SELECT IZBOR
      SCATTER NAME POLJA
      USE TRGPAR IN 0
      SELECT TRGPAR
      APPEND BLANK
      GATHER NAME POLJA
           REPLACE PKGK WITH 'D'
            REPLACE PKAN WITH 'D'
            REPLACE PKTM WITH 'D'
            REPLACE PKKP WITH 'D'
            REPLACE PKPDV WITH 'D'
            REPLACE PNGK WITH 'D'
            REPLACE PNTM WITH 'D'
            REPLACE PNKP WITH 'D'
            REPLACE PFGK WITH 'D'
            REPLACE PFAN WITH 'D'
            REPLACE PFTM WITH 'D'
            REPLACE PFKP WITH 'D'
            REPLACE PFPDV WITH 'D'
            REPLACE PFKPO WITH 'D'           
            USE
      SELECT IZBOR
   ENDIF  
   SELECT IZBOR
   GO BOTTOM 
   
   AAIZBORTVTAB.GRD0.REFRESH
   DO FORM AAIZBORTVK
   *--------NAPRAVI PROVERU   
   CLOSE ALL TABLES
   IF AMIZBOR='TV'   
      DO DBdata03
      DO dbdata04
      DO nalppunidefk
      USE AATV IN 0 ALIAS IZBOR
      GO TOP   
   ELSE
      DO DBdata03
      DO dbdata04
      DO nalppunidefk
      USE AATM IN 0 ALIAS IZBOR
      GO TOP   
   ENDIF
   *---------KRAJ PROVERE
   SELECT IZBOR
ENDIF
POP KEY   
AAIZBORTVTAB.GRD0.SETFOCUS
AAIZBORTVTAB.REFRESH
