PUSH KEY CLEAR
SELECT izbor
IF RECCOUNT()<10
   APPEND BLANK
   REPLACE SIFPROD WITH str(recno(),2,0)
   REPLACE PNAZIV WITH 'KAMATE '+SIFPROD  
   SELECT izbor
   DO FORM AAIZBORKAK
   CLOSE ALL TABLES
   DO DBdata03
   DO DBdata04
   USE AAKA IN 0 ALIAS IZBOR
   GO TOP
ENDIF
POP KEY   
AAIZBORKATAB.GRD0.SETFOCUS
AAIZBORKATAB.REFRESH
