PUSH KEY CLEAR
SELECT izbor
IF RECCOUNT()<99
APPEND BLANK
REPLACE SIFPROD WITH str(recno(),2,0)
REPLACE PNAZIV WITH 'ANALITIKA '+SIFPROD  
   SELECT izbor
   DO FORM AAIZBORANK
   CLOSE ALL TABLES
   DO dbdata03
   DO dbdata04
   DO nalppunidefk
   USE AAAN IN 0 ALIAS IZBOR
   GO TOP
ENDIF
POP KEY   
AAIZBORANTAB.GRD0.SETFOCUS
AAIZBORANTAB.REFRESH
