PUSH KEY CLEAR
IF RECCOUNT()<100
APPEND BLANK
REPLACE SIFPROD WITH str(recno(),2,0)
REPLACE PNAZIV WITH 'BLAGAJNA '+SIFPROD  
   SELECT izbor
   DO FORM AAIZBORBLK
   CLOSE ALL TABLES
   DO DBdata03
   DO dbdata04
   USE AABL IN 0 ALIAS IZBOR
   GO TOP
ENDIF
POP KEY   
AAIZBORBLTAB.GRD0.SETFOCUS
AAIZBORBLTAB.REFRESH
