PARAMETERS MI,MSIFPROD,MPNAZIV,MKONTO,MPRIKAZ
   MSIFPROD=SIFPROD
   MPNAZIV=PNAZIV
   MKONTO=KONTO
   IF PRIKAZ<>'N'.AND.MI=1
      AAIZBORBL.STRANA0.STR1.CMD1.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR1.CMD1.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=2
      AAIZBORBL.STRANA0.STR1.CMD2.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR1.CMD2.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=3
      AAIZBORBL.STRANA0.STR1.CMD3.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR1.CMD3.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=4
      AAIZBORBL.STRANA0.STR1.CMD4.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR1.CMD4.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=5
      AAIZBORBL.STRANA0.STR1.CMD5.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR1.CMD5.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=6
      AAIZBORBL.STRANA0.STR1.CMD6.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR1.CMD6.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=7
      AAIZBORBL.STRANA0.STR1.CMD7.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR1.CMD7.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=8
      AAIZBORBL.STRANA0.STR1.CMD8.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR1.CMD8.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=9
      AAIZBORBL.STRANA0.STR1.CMD9.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR1.CMD9.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=10
      AAIZBORBL.STRANA0.STR1.CMD10.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR1.CMD10.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=11
      AAIZBORBL.STRANA0.STR1.CMD11.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR1.CMD11.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=12
      AAIZBORBL.STRANA0.STR1.CMD12.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR1.CMD12.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=13
      AAIZBORBL.STRANA0.STR1.CMD13.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR1.CMD13.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=14
      AAIZBORBL.STRANA0.STR1.CMD14.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR1.CMD14.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=15
      AAIZBORBL.STRANA0.STR1.CMD15.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR1.CMD15.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=16
      AAIZBORBL.STRANA0.STR1.CMD16.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR1.CMD16.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=17
      AAIZBORBL.STRANA0.STR1.CMD17.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR1.CMD17.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=18
      AAIZBORBL.STRANA0.STR1.CMD18.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR1.CMD18.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=19
      AAIZBORBL.STRANA0.STR1.CMD19.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR1.CMD19.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=20
      AAIZBORBL.STRANA0.STR1.CMD20.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR1.CMD20.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=21
      AAIZBORBL.STRANA0.STR1.CMD21.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR1.CMD21.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=22
      AAIZBORBL.STRANA0.STR1.CMD22.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR1.CMD22.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=23
      AAIZBORBL.STRANA0.STR1.CMD23.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR1.CMD23.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=24
      AAIZBORBL.STRANA0.STR1.CMD24.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR1.CMD24.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=25
      AAIZBORBL.STRANA0.STR1.CMD25.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR1.CMD25.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
   
   IF PRIKAZ<>'N'.AND.MI=26
      AAIZBORBL.STRANA0.STR2.CMD26.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR2.CMD26.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 

   IF PRIKAZ<>'N'.AND.MI=27
      AAIZBORBL.STRANA0.STR2.CMD27.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR2.CMD27.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=28
      AAIZBORBL.STRANA0.STR2.CMD28.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR2.CMD28.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=29
      AAIZBORBL.STRANA0.STR2.CMD29.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR2.CMD29.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=30
      AAIZBORBL.STRANA0.STR2.CMD30.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR2.CMD30.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=31
      AAIZBORBL.STRANA0.STR2.CMD31.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR2.CMD31.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=32
      AAIZBORBL.STRANA0.STR2.CMD32.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR2.CMD32.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=33
      AAIZBORBL.STRANA0.STR2.CMD33.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR2.CMD33.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=34
      AAIZBORBL.STRANA0.STR2.CMD34.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR2.CMD34.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=35
      AAIZBORBL.STRANA0.STR2.CMD35.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR2.CMD35.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=36
      AAIZBORBL.STRANA0.STR2.CMD36.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR2.CMD36.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=37
      AAIZBORBL.STRANA0.STR2.CMD37.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR2.CMD37.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=38
      AAIZBORBL.STRANA0.STR2.CMD38.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR2.CMD38.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=39
      AAIZBORBL.STRANA0.STR2.CMD39.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR2.CMD39.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=40
      AAIZBORBL.STRANA0.STR2.CMD40.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR2.CMD40.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 

   IF PRIKAZ<>'N'.AND.MI=41
      AAIZBORBL.STRANA0.STR2.CMD41.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR2.CMD41.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 

   IF PRIKAZ<>'N'.AND.MI=42
      AAIZBORBL.STRANA0.STR2.CMD42.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR2.CMD42.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 

   IF PRIKAZ<>'N'.AND.MI=43
      AAIZBORBL.STRANA0.STR2.CMD43.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR2.CMD43.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 

   IF PRIKAZ<>'N'.AND.MI=44
      AAIZBORBL.STRANA0.STR2.CMD44.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR2.CMD44.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 

   IF PRIKAZ<>'N'.AND.MI=45
      AAIZBORBL.STRANA0.STR2.CMD45.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR2.CMD45.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 

   IF PRIKAZ<>'N'.AND.MI=46
      AAIZBORBL.STRANA0.STR2.CMD46.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR2.CMD46.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 

   IF PRIKAZ<>'N'.AND.MI=47
      AAIZBORBL.STRANA0.STR2.CMD47.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR2.CMD47.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 

   IF PRIKAZ<>'N'.AND.MI=48
      AAIZBORBL.STRANA0.STR2.CMD48.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR2.CMD48.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=49
      AAIZBORBL.STRANA0.STR2.CMD49.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR2.CMD49.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
   IF PRIKAZ<>'N'.AND.MI=50
      AAIZBORBL.STRANA0.STR2.CMD50.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR2.CMD50.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 

  IF PRIKAZ<>'N'.AND.MI=51
      AAIZBORBL.STRANA0.STR3.CMD51.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR3.CMD51.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=52
      AAIZBORBL.STRANA0.STR3.CMD52.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR3.CMD52.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=53
      AAIZBORBL.STRANA0.STR3.CMD53.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR3.CMD53.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=54
      AAIZBORBL.STRANA0.STR3.CMD54.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR3.CMD54.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=55
      AAIZBORBL.STRANA0.STR3.CMD55.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR3.CMD55.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=56
      AAIZBORBL.STRANA0.STR3.CMD56.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR3.CMD56.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=57
      AAIZBORBL.STRANA0.STR3.CMD57.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR3.CMD57.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=58
      AAIZBORBL.STRANA0.STR3.CMD58.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR3.CMD58.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=59
      AAIZBORBL.STRANA0.STR3.CMD59.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR3.CMD59.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=60
      AAIZBORBL.STRANA0.STR3.CMD60.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR3.CMD60.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=61
      AAIZBORBL.STRANA0.STR3.CMD61.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR3.CMD61.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=62
      AAIZBORBL.STRANA0.STR3.CMD62.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR3.CMD62.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=63
      AAIZBORBL.STRANA0.STR3.CMD63.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR3.CMD63.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=64
      AAIZBORBL.STRANA0.STR3.CMD64.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR3.CMD64.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=65
      AAIZBORBL.STRANA0.STR3.CMD65.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR3.CMD65.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=66
      AAIZBORBL.STRANA0.STR3.CMD66.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR3.CMD66.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=67
      AAIZBORBL.STRANA0.STR3.CMD67.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR3.CMD67.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=68
      AAIZBORBL.STRANA0.STR3.CMD68.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR3.CMD68.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=69
      AAIZBORBL.STRANA0.STR3.CMD69.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR3.CMD69.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=70
      AAIZBORBL.STRANA0.STR3.CMD70.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR3.CMD70.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=71
      AAIZBORBL.STRANA0.STR3.CMD71.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR3.CMD71.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=72
      AAIZBORBL.STRANA0.STR3.CMD72.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR3.CMD72.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=73
      AAIZBORBL.STRANA0.STR3.CMD73.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR3.CMD73.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=74
      AAIZBORBL.STRANA0.STR3.CMD74.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR3.CMD74.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=75
      AAIZBORBL.STRANA0.STR3.CMD75.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR3.CMD75.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=76
      AAIZBORBL.STRANA0.STR4.CMD76.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR4.CMD76.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=77
      AAIZBORBL.STRANA0.STR4.CMD77.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR4.CMD77.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=78
      AAIZBORBL.STRANA0.STR4.CMD78.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR4.CMD78.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=79
      AAIZBORBL.STRANA0.STR4.CMD79.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR4.CMD79.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=80
      AAIZBORBL.STRANA0.STR4.CMD80.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR4.CMD80.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=81
      AAIZBORBL.STRANA0.STR4.CMD81.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR4.CMD81.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=82
      AAIZBORBL.STRANA0.STR4.CMD82.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR4.CMD82.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=83
      AAIZBORBL.STRANA0.STR4.CMD83.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR4.CMD83.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=84
      AAIZBORBL.STRANA0.STR4.CMD84.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR4.CMD84.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=85
      AAIZBORBL.STRANA0.STR4.CMD85.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR4.CMD85.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=86
      AAIZBORBL.STRANA0.STR4.CMD86.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR4.CMD86.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=87
      AAIZBORBL.STRANA0.STR4.CMD87.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR4.CMD87.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=88
      AAIZBORBL.STRANA0.STR4.CMD88.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR4.CMD88.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=89
      AAIZBORBL.STRANA0.STR4.CMD89.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR4.CMD89.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=90
      AAIZBORBL.STRANA0.STR4.CMD90.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR4.CMD90.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=91
      AAIZBORBL.STRANA0.STR4.CMD91.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR4.CMD91.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=92
      AAIZBORBL.STRANA0.STR4.CMD92.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR4.CMD92.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=93
      AAIZBORBL.STRANA0.STR4.CMD93.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR4.CMD93.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=94
      AAIZBORBL.STRANA0.STR4.CMD94.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR4.CMD94.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=95
      AAIZBORBL.STRANA0.STR4.CMD95.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR4.CMD95.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=96
      AAIZBORBL.STRANA0.STR4.CMD96.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR4.CMD96.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=97
      AAIZBORBL.STRANA0.STR4.CMD97.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR4.CMD97.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=98
      AAIZBORBL.STRANA0.STR4.CMD98.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR4.CMD98.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
  IF PRIKAZ<>'N'.AND.MI=99
      AAIZBORBL.STRANA0.STR4.CMD99.VISIBLE=.T.
      AAIZBORBL.STRANA0.STR4.CMD99.CAPTION=MSIFPROD+'-'+MKONTO+'-'+MPNAZIV
   ENDIF 
