PUSH KEY CLEAR
   APPEND BLANK
   AAPLAN.GRD0.REFRESH
   REPLACE SIFPROD WITH str(recno(),2,0)
   *--------NAPRAVI PROVERU   
   USE PROVERAI IN 0 
   SELECT PROVERAI
   replACE TDBgk WITH '0'
   mtdbgk=tdbgk
   USE
   *---------KRAJ PROVERE
   SELECT aaplan   
POP KEY
AAplan.GRD0.SETFOCUS
AAPLAN.REFRESH
