PUSH KEY CLEAR
SET EXACT ON
IF LEN(M2REDNI)=1
   MDOK=ALLTRIM(M2OBJ+M2REDNI)+' '
ELSE
   MDOK=ALLTRIM(M2OBJ+M2REDNI)
ENDIF
MGLKONTO=M2KONTO
MGLKONTOK=M2KONTOK
KKNALIZV=MDATA01+'\NALIZV'+OPERATER+'.DBF'
KKNALIZVX=MDATA01+'\NALIZV'+OPERATER+'.CDX'
KNALIZV=MDATA01+'\NALIZV'+OPERATER
KNALIZVX=MDATA01+'\NALIZV'+OPERATER
DO IDEL WITH (KKNALIZV)
DO IDEL WITH (KKNALIZVX)
DO IBAZE WITH KNALIZV,'NALIZV'
DO IIND WITH KNALIZV,'KONTO+DTOS(DATDOK)','BRNAL','DTOS(DATDOK)',;
             'KONTO+SIFRA+DTOS(DATDOK)','SIFRA+DTOS(DATDOK)','SIFRA+BRRAC+DTOS(DATDOK)'

USE &KNALIZV IN 0 ALIAS NALIZV EXCLUSIVE 

   DO idel WITH (kkockax)   
   DO idel WITH (kkockax2)   
   DO idel WITH (kkockax3)   
   DO idel WITH (kkockax4)   
   DO idel WITH (kkockax5)   
   
SELECT NALIZV   
COPY STRUCTURE TO &KKOCKA   
COPY STRUCTURE TO &KKOCKA3   
   
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
   
IF M2OBJ='V'

KKAL='KAL'+M2REDNI
KKALG='KALG'+M2REDNI
KFAK='FAK'+M2REDNI
KFAKG='FAKG'+M2REDNI
KTVNIV='TVNIV'+M2REDNI
USE AATV IN 0
SELECT AATV
GOTO VAL(M2REDNI)
IF SIFARNIK<>'  '
  KROB='ROB'+ALLTRIM(M2REDNI)
ELSE
   KROB='ROB'
ENDIF

IF TFPOSSIF='D'.and.TNEZAJEDNO<>'D'

   KROB='ROBV'+TTVREDNI
ENDIF


ELSE

SKKALP='TMKAL'+M2REDNI
KKAL='TMKAL'+M2REDNI
KKALG='TMKALG'+M2REDNI
KFAK='TMFAK'+M2REDNI
KFAKG='TMFAKG'+M2REDNI
KTVNIV='TMNIV'+M2REDNI

USE AATM IN 0 ALIAS AATV
SELECT AATV
GOTO VAL(M2REDNI)

IF SIFARNIK<>'  '
  KROB='MROB'+ALLTRIM(M2REDNI)
ELSE
   KROB='ROB'
ENDIF

   if tfpossif='D'.AND.TNEZAJEDNO<>'D'

   KROB='ROBM'+TTVREDNI
ENDIF


ENDIF
SELECT AATV
USE
USE &krob IN 0 ALIAS rob ORDER 1

*------------KALKULACIJE---------------
USE &KKALG IN 0 ALIAS KALG 
USE &KKAL IN 0 ALIAS KAL ORDER 1

SELECT KAL
SET RELATION TO RSIF INTO ROB ADDITIVE

SELECT KALG
GO TOP
DO WHILE.NOT.EOF()
   MBRKAL=BRKAL
   MFVRSTA=FVRSTA
   mdatdok=datdok
   AATVISERVIS031.LBLKAL.CAPTION=' KALKULACIJE '+MBRKAL+' '+DTOC(DATDOK)
   IF DATDOK>TDAT0
   
   SELECT KALPRN 
   SEEK MFVRSTA
   IF FOUND()
      MSEMA=SEMA
   ELSE
      MSEMA=SPACE(4) 
   ENDIF
   SELECT KSEMA 
   SEEK MSEMA
   IF FOUND()
      MKONTO=K_MAG
      MKONTOS=K_MAG2
      MKONTOK=K_MAG3
      MKONTOU=K_USLUGE
   ELSE
      MKONTO=SPACE(10)      
      MKONTOS=SPACE(10)      
      MKONTOK=SPACE(10)
      MKONTOU=SPACE(10)                        
   ENDIF
   SELECT KALG
   MBRNAL=BRNAL
   MDATDOK=DATDOK
   SELECT KAL
   SEEK MBRKAL
   IF FOUND()
      MMALVRED=0
      MMALVREDS=0
      MMALVREDK=0            
      DO WHILE.NOT.EOF()
         IF BRKAL<>MBRKAL
            EXIT
         ENDIF
            MRVRSTA=ROB.VRSTA
            DO CASE 
            CASE MRVRSTA='S'
               IF M2OBJ='V'
                  MMALVREDS=MMALVREDS+VELVRED
               ELSE
                  MMALVREDS=MMALVREDS+MALVRED
               ENDIF
            CASE MRVRSTA='K'
               IF M2OBJ='V'
                  MMALVREDK=MMALVREDK+VELVRED
               ELSE
                  MMALVREDK=MMALVREDK+MALVRED
               ENDIF
            OTHERWISE
               IF M2OBJ='V'
                  MMALVRED=MMALVRED+VELVRED
               ELSE
                  MMALVRED=MMALVRED+MALVRED
               ENDIF
            ENDCASE
         SKIP
      ENDDO   
      IF MMALVRED<>0
         SELECT KOCKA
         APPEND BLANK
         REPLACE BRNAL WITH MBRNAL
         REPLACE DOK WITH MDOK
         REPLACE DUG WITH MMALVRED
         REPLACE KONTO WITH MKONTO
         REPLACE K3 WITH 'KAL'
         REPLACE BRKAL WITH MBRKAL
         replace datdok WITH mdatdok
      ENDIF
      IF MMALVREDK<>0
         SELECT KOCKA
         APPEND BLANK
         REPLACE BRNAL WITH MBRNAL
         REPLACE DOK WITH MDOK
         REPLACE DUG WITH MMALVREDK
         REPLACE KONTO WITH MKONTOK
         REPLACE K3 WITH 'KAL'
         REPLACE BRKAL WITH MBRKAL
         replace datdok WITH mdatdok
      ENDIF
      IF MMALVREDS<>0
         SELECT KOCKA
         APPEND BLANK
         REPLACE BRNAL WITH MBRNAL
         REPLACE DOK WITH MDOK
         REPLACE DUG WITH MMALVREDS
         REPLACE KONTO WITH MKONTOS
         REPLACE K3 WITH 'KAL'
         REPLACE BRKAL WITH MBRKAL
         replace datdok WITH mdatdok
      ENDIF


   ENDIF     
   ENDIF
   SELECT KALG
   SKIP
ENDDO   
SELECT KAL
SET RELATION TO
USE
SELECT KALG
USE

*--------NIVELACIJE-------------------

USE &KTVNIV IN 0 ALIAS NIV
SELECT NIV
SET ORDER TO 3

TOTAL ON BRNAL TO &KKOCKA2 FIELDS SIZNOS,VELVRED,MALVRED
USE
USE &KKOCKA2 IN 0 ALIAS KOCKA2 EXCLU
SELECT KOCKA2
GO TOP

DO WHILE.NOT.EOF()
   MBRNAL=BRNAL
   MBRKAL=BRKAL
   mdatdok=datdok
   MMALVRED=0
   MMALVREDS=0
   MMALVREDK=0
   MRVRSTA=ROB.VRSTA
   DO CASE 
   CASE MRVRSTA='S'  
      IF M2OBJ='V'
         MMALVREDS=VELVRED-SIZNOS
      ELSE
         MMALVREDS=MALVRED-SIZNOS
      ENDIF
   CASE MRVRSTA='K'
      IF M2OBJ='V'
         MMALVREDK=VELVRED-SIZNOS
      ELSE
         MMALVREDK=MALVRED-SIZNOS
      ENDIF
   OTHERWISE
      IF M2OBJ='V'
         MMALVRED=VELVRED-SIZNOS
      ELSE
         MMALVRED=MALVRED-SIZNOS
      ENDIF
   ENDCASE

 MSEMA=SEMA
   SELECT KSEMA 
   SEEK MSEMA
   IF FOUND()
      MKONTO=K_MAG
      MKONTOS=K_MAG2
      MKONTOK=K_MAG3
   ELSE
      MKONTO=SPACE(10)      
      MKONTOS=SPACE(10)      
      MKONTOK=SPACE(10)                  
   ENDIF
   IF MMALVRED<>0
      SELECT KOCKA
      APPEND BLANK
      REPLACE BRNAL WITH MBRNAL
      REPLACE DOK WITH MDOK
      REPLACE DUG WITH MMALVRED
      REPLACE KONTO WITH MKONTO
      REPLACE K3 WITH 'NIV'
      replace datdok WITH mdatdok
      REPLACE BRKAL WITH MBRKAL
   ENDIF
   IF MMALVREDK<>0
      SELECT KOCKA
      APPEND BLANK
      REPLACE BRNAL WITH MBRNAL
      REPLACE DOK WITH MDOK
      REPLACE DUG WITH MMALVREDK
      REPLACE KONTO WITH MKONTOK
      REPLACE K3 WITH 'NIV'
      replace datdok WITH mdatdok
      REPLACE BRKAL WITH MBRKAL
   ENDIF

   IF MMALVREDS<>0
      SELECT KOCKA
      APPEND BLANK
      REPLACE BRNAL WITH MBRNAL
      REPLACE DOK WITH MDOK
      REPLACE DUG WITH MMALVREDS
      REPLACE KONTO WITH MKONTOS
      REPLACE K3 WITH 'NIV'
      replace datdok WITH mdatdok
      REPLACE BRKAL WITH MBRKAL
   ENDIF


   SELECT KOCKA2
   AATVISERVIS031.LBLKAL.CAPTION=' NIVELACIJE '+MBRNAL+' '+DTOC(MDATDOK)
   
   SKIP
ENDDO   
SELECT KOCKA2
USE
*------------------FAKTURE----------------------
IF MIMAFAK='D'
USE &KFAKG IN 0 ALIAS FAKG 
USE &KFAK IN 0 ALIAS FAK ORDER 1
SELECT FAK
SET RELATION TO RSIF INTO ROB ADDITIVE

SELECT FAKG
GO TOP
DO WHILE.NOT.EOF()
   MBRKAL=BRKAL
   MFVRSTA=FVRSTA
   mdatdok=datdok
   SELECT FAKPRN 
   SEEK MFVRSTA
   IF FOUND()
      MSEMA=SEMA
   ELSE
      MSEMA=SPACE(4) 
   ENDIF
   SELECT KSEMA 
   SEEK MSEMA
   IF FOUND()
      MKONTO=K_MAG
      MKONTOS=K_MAG2
      MKONTOK=K_MAG3
      MKONTOU=K_USLUGE
   ELSE
      MKONTO=SPACE(10)      
      MKONTOS=SPACE(10)      
      MKONTOK=SPACE(10)                  
      MKONTOU=SPACE(10)                  
   ENDIF
   SELECT FAKG
   MBRNAL=BRNAL
   MDATDOK=DATDOK
   SELECT FAK
   SEEK MBRKAL

   IF FOUND()
      MMALVRED=0
      MMALVREDS=0
      MMALVREDK=0
      MMALVREDU=0      
      DO WHILE.NOT.EOF()
         IF BRKAL<>MBRKAL
            EXIT
         ENDIF
         MRVRSTA=ROB.VRSTA
         DO CASE 
            CASE MRVRSTA='S'  
               IF M2OBJ='V'
                  MMALVREDS=MMALVREDS+VELVRED
               ELSE
                  MMALVREDS=MMALVREDS+MALVRED
               ENDIF
            CASE MRVRSTA='K'
               IF M2OBJ='V'
                  MMALVREDK=MMALVREDK+VELVRED
               ELSE
                  MMALVREDK=MMALVREDK+MALVRED
               ENDIF
            CASE MRVRSTA='U'
                IF M2OBJ='V'
                  MMALVREDU=MMALVREDU+VELVRED
               ELSE
                  MMALVREDU=MMALVREDU+MALVRED
               ENDIF
            OTHERWISE
               IF M2OBJ='V'
                  MMALVRED=MMALVRED+VELVRED
               ELSE
                  MMALVRED=MMALVRED+MALVRED
               ENDIF
         ENDCASE
         SKIP
      ENDDO   
      IF MMALVRED<>0
         SELECT KOCKA
         APPEND BLANK
         REPLACE BRNAL WITH MBRNAL
         REPLACE DOK WITH MDOK
         REPLACE POT WITH MMALVRED
         REPLACE KONTO WITH MKONTO
         REPLACE K3 WITH 'FAK'
         replace datdok WITH mdatdok
         replace brkal WITH mbrkal
      ENDIF
      IF MMALVREDK<>0
         SELECT KOCKA
         APPEND BLANK
         REPLACE BRNAL WITH MBRNAL
         REPLACE DOK WITH MDOK
         REPLACE POT WITH MMALVREDK
         REPLACE KONTO WITH MKONTOK
         REPLACE K3 WITH 'FAK'
         replace datdok WITH mdatdok
         replace brkal WITH mbrkal
      ENDIF
      IF MMALVREDS<>0
         SELECT KOCKA
         APPEND BLANK
         REPLACE BRNAL WITH MBRNAL
         REPLACE DOK WITH MDOK
         REPLACE POT WITH MMALVREDS
         REPLACE KONTO WITH MKONTOS
         REPLACE K3 WITH 'FAK'
         replace datdok WITH mdatdok
         replace brkal WITH mbrkal
      ENDIF
      IF MMALVREDU<>0
         SELECT KOCKA
         APPEND BLANK
         REPLACE BRNAL WITH MBRNAL
         REPLACE DOK WITH MDOK
         REPLACE POT WITH MMALVREDU
         REPLACE KONTO WITH MKONTOU
         REPLACE K3 WITH 'FAK'
         replace datdok WITH mdatdok
         replace brkal WITH mbrkal
      ENDIF


   ENDIF     
   SELECT FAKG   
   AATVISERVIS031.LBLKAL.CAPTION=' FAKTURE '+MBRKAL+' '+DTOC(DATDOK)
   SKIP
ENDDO   
SELECT FAK
SET RELATION TO
USE
SELECT FAKG
USE
ENDIF
SELECT ROB
USE
*----------------GLAVNA KNJIGA--------------------
USE NAL IN 0
SELECT NAL
COPY TO &KKOCKA4 FOR DOK=MDOK.AND.GKONTO<>SPACE(10).AND.AUTOMNAL<>' '
USE
USE &KKOCKA4 IN 0 ALIAS KOCKA4 EXCLU
SELECT KOCKA4
INDEX ON BRNAL+KONTO  TAG BRNAL
SET ORDER TO 1
SELECT KOCKA
GO TOP
DO WHILE.NOT.EOF()
   M3KONTO=KONTO
   MBRNAL=BRNAL+KONTO
   mdatdok=datdok
   SELECT KOCKA4
   SEEK MBRNAL
   IF FOUND()
      MDUG=0
      MPOT=0
      DO WHILE.NOT.EOF()
         IF BRNAL+KONTO<>MBRNAL 
            EXIT
         ENDIF   
         IF KONTO=M3KONTO
            MDUG=MDUG+DUG
            MPOT=MPOT+POT
         ENDIF
         REPLACE KONTO WITH '9999999999'
         SKIP
      ENDDO      
      SELECT KOCKA
      REPLACE UDUG WITH MDUG
      REPLACE UPOT WITH MPOT
   ENDIF 
   SELECT KOCKA
   AATVISERVIS031.LBLKAL.CAPTION=' GLAVNA KNJIGA '+MBRNAL+' '+DTOC(MDATDOK)
   SKIP
ENDDO
SELECT KOCKA4
DELETE ALL FOR KONTO='9999999999'
PACK
IF RECCOUNT()>0
   GO TOP
   DO WHILE.NOT.EOF()
      MKONTO=KONTO
      MBRNAL=BRNAL
      MUDUG=DUG
      MUPOT=POT
      MDATDOK=DATDOK
      SELECT KOCKA
      APPEND BLANK
      REPLACE BRNAL WITH MBRNAL
      REPLACE UDUG WITH MUDUG
      REPLACE UPOT WITH MUPOT
      REPLACE DATDOK WITH MDATDOK
      REPLACE KONTO WITH MKONTO
      SELECT KOCKA4
      AATVISERVIS031.LBLKAL.CAPTION=' IZRACUNAVANJE SALDA '+MBRNAL+' '+DTOC(MDATDOK)
      SKIP
   ENDDO   
ENDIF      
SELECT KOCKA4
USE
SELECT KOCKA
GO TOP
DO WHILE.NOT.EOF()
   REPLACE SALDO WITH DUG-POT
   REPLACE USALDO WITH UDUG-UPOT
   REPLACE DSALDO WITH SALDO-USALDO
   SKIP
ENDDO   

GO TOP
   SELECT KOCKA
   GO TOP
   DO WHILE.NOT.EOF()
      MKONTO=KONTO
      MK3=K3
      MSALDO=SALDO
      MUSALDO=USALDO
      MDSALDO=DSALDO
      MDATDOK=DATDOK
      MDOK=DOK
      MBRNAL=BRNAL
      MBRKAL=BRKAL
      SELECT SVESLAG
      APPEND BLANK
      REPLACE KONTO WITH MKONTO
      REPLACE VRSTA WITH MK3
      REPLACE ROBNO WITH MSALDO
      REPLACE GKNJIGA WITH MUSALDO
      REPLACE RAZLIKA WITH MDSALDO
      REPLACE BRNAL WITH MBRNAL
      REPLACE DOK WITH MDOK
      REPLACE DATDOK WITH MDATDOK
      REPLACE SIFARNIK WITH T2SIFARNIK
      REPLACE BRKAL WITH MBRKAL
      SELECT KOCKA
      AATVISERVIS031.LBLKAL.CAPTION=' PUNJENJE GLAVNE BAZE '+MBRNAL+' '+DTOC(MDATDOK)
      SKIP
   ENDDO   
SELECT NALIZV
USE
SELECT KOCKA
USE
SELECT SVESLAG
SET EXACT OFF
POP KEY