PUSH KEY CLEAR
SET EXACT ON
IF LEN(M2REDNI)=1
   MDOK=ALLTRIM(M2OBJ+M2REDNI)+' '
ELSE
   MDOK=ALLTRIM(M2OBJ+M2REDNI)
ENDIF
MGLKONTO=M2KONTO
MGLKONTOK=M2KONTOK
KKNALIZV=MDATA01+'\NALIZV'+OPERATER+'.DBF'
KKNALIZVX=MDATA01+'\NALIZV'+OPERATER+'.CDX'
KNALIZV=MDATA01+'\NALIZV'+OPERATER
KNALIZVX=MDATA01+'\NALIZV'+OPERATER
DO IDEL WITH (KKNALIZV)
DO IDEL WITH (KKNALIZVX)
DO IBAZE WITH KNALIZV,'NALIZV'
DO IIND WITH KNALIZV,'KONTO+DTOS(DATDOK)','BRNAL','DTOS(DATDOK)',;
             'KONTO+SIFRA+DTOS(DATDOK)','SIFRA+DTOS(DATDOK)','SIFRA+BRRAC+DTOS(DATDOK)'

USE &KNALIZV IN 0 ALIAS NALIZV EXCLUSIVE 

   DO idel WITH (kkockax)   
   DO idel WITH (kkockax2)   
   DO idel WITH (kkockax3)   
   DO idel WITH (kkockax4)   
   DO idel WITH (kkockax5)   
   DO idel WITH (kkockax6)   

   
SELECT NALIZV   
COPY STRUCTURE TO &KKOCKA   
COPY STRUCTURE TO &KKOCKA3   
   
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
   
IF M2OBJ='V'

KKAL='KAL'+M2REDNI
KKALG='KALG'+M2REDNI
KFAK='FAK'+M2REDNI
KFAKG='FAKG'+M2REDNI
KTVNIV='TVNIV'+M2REDNI
KTM='TVTM'+M2REDNI
IF TSIFARNIK<>'  '
  KROB='ROB'+ALLTRIM(TSIFARNIK)
ELSE
   KROB='ROB.DBF'
ENDIF

   if tfpossif='D'.AND.TNEZAJEDNO<>'D'

   KROB='ROBV'+M2REDNI
ENDIF

ELSE

SKKALP='TMKAL'+M2REDNI
KKAL='TMKAL'+M2REDNI
KKALG='TMKALG'+M2REDNI
KFAK='TMFAK'+M2REDNI
KFAKG='TMFAKG'+M2REDNI
KTVNIV='TMNIV'+M2REDNI
KTM='TM'+M2REDNI

IF TSIFARNIK<>'  '
  KROB='MROB'+ALLTRIM(TSIFARNIK)
ELSE
   KROB='ROB'
ENDIF

   if tfpossif='D'.AND.TNEZAJEDNO<>'D'

   KROB='ROBM'+M2REDNI
ENDIF


ENDIF


USE &krob IN 0 ALIAS rob ORDER 1

*------------KALKULACIJE---------------
USE &KKALG IN 0 ALIAS KALG 
USE &KKAL IN 0 ALIAS KAL ORDER 1

SELECT KAL
SET RELATION TO RSIF INTO ROB ADDITIVE

SELECT KALG
GO TOP
DO WHILE.NOT.EOF()
   MBRKAL=BRKAL
   MFVRSTA=FVRSTA
   mdatdok=datdok
   AATVISERVIS081.LBLKAL.CAPTION=' KALKULACIJE '+MBRKAL+' '+DTOC(DATDOK)
   SELECT KALPRN 
   SEEK MFVRSTA
   IF FOUND()
      MSEMA=SEMA
   ELSE
      MSEMA=SPACE(4) 
   ENDIF
   SELECT KSEMA 
   SEEK MSEMA
   IF FOUND()
      MKONTO=K_MAG
   ELSE
      MKONTO=SPACE(10)      
   ENDIF
   SELECT KALG
   MBRNAL=BRNAL
   MDATDOK=DATDOK
   SELECT KAL
   SEEK MBRKAL
   IF FOUND()
      MMALVRED=0
      DO WHILE.NOT.EOF()
         IF BRKAL<>MBRKAL
            EXIT
         ENDIF
            IF ROB.VRSTA<>'K'  
               IF M2OBJ='V'
                  MMALVRED=MMALVRED+VELVRED
               ELSE
                  MMALVRED=MMALVRED+MALVRED
               ENDIF
            ENDIF
         SKIP
      ENDDO   
      IF MMALVRED<>0
         SELECT KOCKA
         APPEND BLANK
         REPLACE BRNAL WITH MBRNAL
         REPLACE DOK WITH MDOK
         REPLACE DUG WITH MMALVRED
         REPLACE KONTO WITH MKONTO
         REPLACE K3 WITH 'KAL'
         REPLACE BRKAL WITH MBRKAL
         replace datdok WITH mdatdok
      ENDIF
   ENDIF     
   SELECT KALG
   SKIP
ENDDO   
SELECT KAL
SET RELATION TO
USE
SELECT KALG
USE

*--------NIVELACIJE-------------------

USE &KTVNIV IN 0 ALIAS NIV
SELECT NIV
SET ORDER TO 3

TOTAL ON BRNAL TO &KKOCKA2 FIELDS SIZNOS,VELVRED,MALVRED
USE
USE &KKOCKA2 IN 0 ALIAS KOCKA2 EXCLU
SELECT KOCKA2
GO TOP

DO WHILE.NOT.EOF()
   MBRNAL=BRNAL
   MBRKAL=BRKAL
   mdatdok=datdok
   MMALVRED=0
      IF ROB.VRSTA<>'K'
         IF M2OBJ='V'
            MMALVRED=VELVRED-SIZNOS
         ELSE
            MMALVRED=MALVRED-SIZNOS
         ENDIF
      ENDIF   
   MSEMA=SEMA
   SELECT KSEMA 
   SEEK MSEMA
   IF FOUND()
      MKONTO=K_MAG
   ELSE
      MKONTO=SPACE(10)      
   ENDIF
   IF MMALVRED<>0
      SELECT KOCKA
      APPEND BLANK
      REPLACE BRNAL WITH MBRNAL
      REPLACE DOK WITH MDOK
      REPLACE BRNAL WITH MBRNAL   
      REPLACE DUG WITH MMALVRED
      REPLACE KONTO WITH MKONTO
      REPLACE K3 WITH 'NIV'
      replace datdok WITH mdatdok
      REPLACE BRKAL WITH MBRKAL
   ENDIF
   SELECT KOCKA2
   AATVISERVIS081.LBLKAL.CAPTION=' NIVELACIJE '+MBRNAL+' '+DTOC(MDATDOK)
   
   SKIP
ENDDO   
SELECT KOCKA2
USE

IF M2OBJ='V'

*------------RACUNI---------------
USE &KFAKG IN 0 ALIAS FAKG 
USE &KFAK IN 0 ALIAS FAK ORDER 1

SELECT FAK
SET RELATION TO RSIF INTO ROB ADDITIVE

SELECT FAKG
GO TOP
DO WHILE.NOT.EOF()
   MBRKAL=BRKAL
   MFVRSTA=FVRSTA
   mdatdok=datdok
   AATVISERVIS081.LBLKAL.CAPTION=' RACUNI '+MBRKAL+' '+DTOC(DATDOK)
   SELECT FAKPRN 
   SEEK MFVRSTA
   IF FOUND()
      MSEMA=SEMA
   ELSE
      MSEMA=SPACE(4) 
   ENDIF
   SELECT KSEMA 
   SEEK MSEMA
   IF FOUND()
      MKONTO=K_MAG
   ELSE
      MKONTO=SPACE(10)      
   ENDIF
   SELECT FAKG
   MBRNAL=BRNAL
   MDATDOK=DATDOK
   SELECT FAK
   SEEK MBRKAL
   IF FOUND()
      MMALVRED=0
      DO WHILE.NOT.EOF()
         IF BRKAL<>MBRKAL
            EXIT
         ENDIF
            IF ROB.VRSTA<>'K'  
               IF M2OBJ='V'
                  MMALVRED=MMALVRED+VELVRED+POREZ-RABAT-RABAT2
               ELSE
                  MMALVRED=MMALVRED+MALVRED
               ENDIF
            ENDIF
         SKIP
      ENDDO   
      IF MMALVRED<>0
         SELECT KOCKA
         APPEND BLANK
         REPLACE BRNAL WITH MBRNAL
         REPLACE DOK WITH MDOK
         REPLACE DUG WITH MMALVRED
         REPLACE KONTO WITH MKONTO
         REPLACE K3 WITH 'FAK'
         REPLACE BRKAL WITH MBRKAL
         replace datdok WITH mdatdok
      ENDIF
   ENDIF     
   SELECT FAKG
   SKIP
ENDDO   
SELECT FAK
SET RELATION TO
USE
SELECT FAKG
USE
ENDIF
*----------------KEPU--------------------

USE &KTM IN 0 ALIAS TM
SELECT TM
COPY TO &KKOCKA4 FOR UKNAB<>0.AND.VREDPROD=0.AND.AUTOMNAL<>' '
USE
USE &KKOCKA4 IN 0 ALIAS KOCKA4 EXCLU
SELECT KOCKA4
INDEX ON BRNAL  TAG BRNAL
SET ORDER TO 1
SELECT KOCKA
GO TOP
DO WHILE.NOT.EOF()
   MBRNAL=BRNAL
   mdatdok=datdok
   SELECT KOCKA4
   SEEK MBRNAL
   IF FOUND()
      MDUG=0
      MPOT=0
      DO WHILE.NOT.EOF()
         IF BRNAL<>MBRNAL 
            EXIT
         ENDIF   
         MDUG=MDUG+UKNAB
         REPLACE KONTO WITH '9999999999'
         SKIP
      ENDDO      
      SELECT KOCKA
      REPLACE UDUG WITH MDUG
      REPLACE UPOT WITH MPOT
   ENDIF 
   SELECT KOCKA
   AATVISERVIS081.LBLKAL.CAPTION=' KEPU '+MBRNAL+' '+DTOC(MDATDOK)
   SKIP
ENDDO
SELECT KOCKA4
DELETE ALL FOR KONTO='9999999999'
PACK
IF RECCOUNT()>0
   SELECT KOCKA4
   GO TOP
   DO WHILE.NOT.EOF()
      MBRNAL=BRNAL
      MUDUG=UKNAB
      MDATDOK=DATDOK
      SELECT KOCKA
      APPEND BLANK
      REPLACE UDUG WITH MUDUG
      REPLACE DATDOK WITH MDATDOK
      REPLACE BRNAL WITH MBRNAL
      REPLACE DOK WITH MDOK

      SELECT KOCKA4
      AATVISERVIS081.LBLKAL.CAPTION=' IZRACUNAVANJE SALDA '+MBRNAL+' '+DTOC(MDATDOK)
      SKIP
   ENDDO   
ENDIF      
SELECT KOCKA4
USE
SELECT KOCKA
GO TOP
DO WHILE.NOT.EOF()
   REPLACE SALDO WITH DUG-POT
   REPLACE USALDO WITH UDUG-UPOT
   REPLACE DSALDO WITH SALDO-USALDO
   SKIP
ENDDO   
GO TOP
IF M2OBJ<>'V'
   SELECT KOCKA
   GO TOP
   DO WHILE.NOT.EOF()
      MK3=K3
      MSALDO=SALDO
      MUSALDO=USALDO
      MDSALDO=DSALDO
      MDATDOK=DATDOK
      MDOK=DOK
      MBRNAL=BRNAL
      MBRKAL=BRKAL
      SELECT SVESLAG
      APPEND BLANK
      REPLACE VRSTA WITH MK3
      REPLACE ROBNO WITH MSALDO
      REPLACE GKNJIGA WITH MUSALDO
      REPLACE RAZLIKA WITH MDSALDO
      REPLACE BRNAL WITH MBRNAL
      REPLACE DOK WITH MDOK
      REPLACE DATDOK WITH MDATDOK
      REPLACE SIFARNIK WITH T2SIFARNIK
      REPLACE BRKAL WITH MBRKAL
      SELECT KOCKA
      AATVISERVIS081.LBLKAL.CAPTION=' PUNJENJE GLAVNE BAZE '+MBRNAL+' '+DTOC(MDATDOK)
      SKIP
   ENDDO   
ENDIF
SELECT SVESLAG
*----------------KEPU--------------------
IF M2OBJ='V'
DO idel WITH (kkockax4)   
USE &KTM IN 0 ALIAS TM

SELECT TM
COPY TO &KKOCKA4 FOR VREDPROD<>0.AND.AUTOMNAL<>' '
USE
USE &KKOCKA4 IN 0 ALIAS KOCKA4 EXCLU
SELECT KOCKA4
INDEX ON BRNAL  TAG BRNAL
SET ORDER TO 1
SELECT KOCKA
GO TOP
DO WHILE.NOT.EOF()
   MBRNAL=BRNAL
   mdatdok=datdok
   SELECT KOCKA4
   SEEK MBRNAL
   IF FOUND()
      MDUG=0
      MPOT=0
      DO WHILE.NOT.EOF()
         IF BRNAL<>MBRNAL 
            EXIT
         ENDIF   
         MDUG=MDUG+VREDPROD
         REPLACE KONTO WITH '9999999999'
         SKIP
      ENDDO      
      SELECT KOCKA
      REPLACE UDUG WITH MDUG
      REPLACE UPOT WITH MPOT
   ENDIF 
   SELECT KOCKA
   AATVISERVIS081.LBLKAL.CAPTION=' KEPU '+MBRNAL+' '+DTOC(MDATDOK)
   SKIP
ENDDO
SELECT KOCKA


SELECT KOCKA4
DELETE ALL FOR KONTO='9999999999'
PACK

IF RECCOUNT()>0
   SELECT KOCKA4
   GO TOP
   DO WHILE.NOT.EOF()
      MBRNAL=BRNAL
      MUDUG=VREDPROD
      MDATDOK=DATDOK
      MBRKAL=BRKAL
      SELECT KOCKA
      APPEND BLANK
      REPLACE UDUG WITH MUDUG
      REPLACE DATDOK WITH MDATDOK
      REPLACE BRNAL WITH MBRNAL
      REPLACE BRKAL WITH MBRKAL
      REPLACE DOK WITH MDOK
      SELECT KOCKA4
      AATVISERVIS081.LBLKAL.CAPTION=' IZRACUNAVANJE SALDA '+MBRNAL+' '+DTOC(MDATDOK)
      SKIP
   ENDDO   
ENDIF      
SELECT KOCKA4
USE
SELECT KOCKA
GO TOP
DO WHILE.NOT.EOF()
   REPLACE SALDO WITH DUG-POT
   REPLACE USALDO WITH UDUG-UPOT
   REPLACE DSALDO WITH SALDO-USALDO
   SKIP
ENDDO   

GO TOP
   SELECT KOCKA
   GO TOP
   DO WHILE.NOT.EOF()
      MK3=K3
      MSALDO=SALDO
      MUSALDO=USALDO
      MDSALDO=DSALDO
      MDATDOK=DATDOK
      MDOK=DOK
      MBRNAL=BRNAL
      MBRKAL=BRKAL
      SELECT SVESLAG
      APPEND BLANK
      REPLACE VRSTA WITH MK3
      REPLACE ROBNO WITH MSALDO
      REPLACE GKNJIGA WITH MUSALDO
      REPLACE RAZLIKA WITH MDSALDO
      REPLACE BRNAL WITH MBRNAL
      REPLACE DOK WITH MDOK
      REPLACE DATDOK WITH MDATDOK
      REPLACE SIFARNIK WITH T2SIFARNIK
      REPLACE BRKAL WITH MBRKAL
      SELECT KOCKA
      AATVISERVIS081.LBLKAL.CAPTION=' PUNJENJE GLAVNE BAZE '+MBRNAL+' '+DTOC(MDATDOK)
      SKIP
   ENDDO   
ENDIF

   
SELECT ROB
USE   
SELECT NALIZV
USE
SELECT KOCKA
USE
SELECT SVESLAG
SET EXACT OFF
POP KEY