PARAMETERS MIMAKAL,MIMAFAK

PUSH KEY CLEAR
SET EXACT ON
IF LEN(M2REDNI)=1
   MDOK=ALLTRIM(M2OBJ+M2REDNI)+' '
ELSE
   MDOK=ALLTRIM(M2OBJ+M2REDNI)
ENDIF
KKNALIZV=MDATA01+'\NALIZV'+OPERATER+'.DBF'
KKNALIZVX=MDATA01+'\NALIZV'+OPERATER+'.CDX'
KNALIZV=MDATA01+'\NALIZV'+OPERATER
KNALIZVX=MDATA01+'\NALIZV'+OPERATER
DO IDEL WITH (KKNALIZV)
DO IDEL WITH (KKNALIZVX)
DO IBAZE WITH KNALIZV,'NALIZV'
DO IIND WITH KNALIZV,'KONTO+DTOS(DATDOK)','BRNAL','DTOS(DATDOK)',;
             'KONTO+SIFRA+DTOS(DATDOK)','SIFRA+DTOS(DATDOK)','SIFRA+BRRAC+DTOS(DATDOK)'

USE &KNALIZV IN 0 ALIAS NALIZV EXCLUSIVE 

   DO idel WITH (kkockax)   
   DO idel WITH (kkockax2)   
   DO idel WITH (kkockax3)   
   DO idel WITH (kkockax4)   
   DO idel WITH (kkockax5)   
   
SELECT NALIZV   
COPY STRUCTURE TO &KKOCKA   
COPY STRUCTURE TO &KKOCKA3   
   
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
   
IF M2OBJ='V'

KKAL='KAL'+M2REDNI
KKALG='KALG'+M2REDNI
KFAK='FAK'+M2REDNI
KFAKG='FAKG'+M2REDNI


ELSE

SKKALP='TMKAL'+M2REDNI
KKAL='TMKAL'+M2REDNI
KKALG='TMKALG'+M2REDNI
KFAK='TMFAK'+M2REDNI
KFAKG='TMFAKG'+M2REDNI



ENDIF


IF MIMAKAL='D'
*------------KALKULACIJE---------------
USE &KKALG IN 0 ALIAS KALG 
USE &KKAL IN 0 ALIAS KAL ORDER 1


SELECT KALG
GO TOP
DO WHILE.NOT.EOF()
   MBRKAL=BRKAL
   MFVRSTA=FVRSTA
   mdatdok=datdok
   mprenos=prenos
   MBRNAL=BRNAL
   MDATDOK=DATDOK
   AATVISERVIS071.LBLKAL.CAPTION=' KALKULACIJE '+MBRKAL+' '+DTOC(DATDOK)
   IF mprenos=' '.and.interna=' '
      SELECT KAL
      SEEK MBRKAL
      IF FOUND()
         M270=0
         M271=0
         M274=0
         M275=0
         M278=0
         DO WHILE.NOT.EOF()
            IF BRKAL<>MBRKAL
               EXIT
            ENDIF
            IF procpor=VAL(TOSTOPA)
               m270=m270+placpor+placpord+placporz
               m274=m274+placporu+placporc
            ENDIF
            IF procpor=VAL(TNSTOPA)
               m271=m271+placpor+placpord+placporz
               m275=m275+placporu+placporc
            ENDIF
            IF poljproc<>0
               m278=m278+poljdin
            ENDIF
            SKIP
         ENDDO   
         IF M270<>0
            SELECT KOCKA
            APPEND BLANK
            REPLACE BRNAL WITH MBRNAL
            REPLACE DOK WITH MDOK
            REPLACE DUG WITH M270
            REPLACE K3 WITH 'KAL'
            REPLACE BRKAL WITH MBRKAL
            replace datdok WITH mdatdok
            replace konto WITH '270'
         endif   
         IF M271<>0
            SELECT KOCKA
            APPEND BLANK
            REPLACE BRNAL WITH MBRNAL
            REPLACE DOK WITH MDOK
            REPLACE DUG WITH M271
            REPLACE K3 WITH 'KAL'
            REPLACE BRKAL WITH MBRKAL
            replace datdok WITH mdatdok
            replace konto WITH '271'
         endif   
         IF M274<>0
            SELECT KOCKA
            APPEND BLANK
            REPLACE BRNAL WITH MBRNAL
            REPLACE DOK WITH MDOK
            REPLACE DUG WITH M274
            REPLACE K3 WITH 'KAL'
            REPLACE BRKAL WITH MBRKAL
            replace datdok WITH mdatdok
            replace konto WITH '274'
         endif   
         IF M275<>0
            SELECT KOCKA
            APPEND BLANK
            REPLACE BRNAL WITH MBRNAL
            REPLACE DOK WITH MDOK
            REPLACE DUG WITH M275
            REPLACE K3 WITH 'KAL'
            REPLACE BRKAL WITH MBRKAL
            replace datdok WITH mdatdok
            replace konto WITH '275'
         endif   
         IF M278<>0
            SELECT KOCKA
            APPEND BLANK
            REPLACE BRNAL WITH MBRNAL
            REPLACE DOK WITH MDOK
            REPLACE DUG WITH M278
            REPLACE K3 WITH 'KAL'
            REPLACE BRKAL WITH MBRKAL
            replace datdok WITH mdatdok
            replace konto WITH '278'
         endif   
         
      ENDIF
   ENDIF     
   SELECT KALG
   SKIP
ENDDO   
SELECT KAL
SET RELATION TO
USE
SELECT KALG
USE

ENDIF
IF MIMAFAK='D'
*------------RACUNI---------------
USE &KFAKG IN 0 ALIAS FAKG 
USE &KFAK IN 0 ALIAS FAK ORDER 1

SELECT FAKG
GO TOP
DO WHILE.NOT.EOF()
   MBRKAL=BRKAL
   mdatdok=datdok
   mprenos=prenos
   MBRNAL=BRNAL
   MDATDOK=DATDOK
   AATVISERVIS071.LBLKAL.CAPTION=' RACUNI '+MBRKAL+' '+DTOC(DATDOK)
   IF mprenos=' '.and.interna=' '
      SELECT FAK
      SEEK MBRKAL
      IF FOUND()
         M470=0
         m471=0
         DO WHILE.NOT.EOF()
            IF BRKAL<>MBRKAL
               EXIT
            ENDIF
            IF procpor=VAL(TOSTOPA)
               m470=m470+porez
            ENDIF
            IF procpor=VAL(TNSTOPA)
               m471=m471+porez
            ENDIF
            SKIP
         ENDDO   
         IF M470<>0
            SELECT KOCKA
            APPEND BLANK
            REPLACE BRNAL WITH MBRNAL
            REPLACE DOK WITH MDOK
            REPLACE DUG WITH M470
            REPLACE K3 WITH 'FAK'
            REPLACE BRKAL WITH MBRKAL
            replace datdok WITH mdatdok
            replace konto WITH '470'
         endif   
         IF M471<>0
            SELECT KOCKA
            APPEND BLANK
            REPLACE BRNAL WITH MBRNAL
            REPLACE DOK WITH MDOK
            REPLACE DUG WITH M471
            REPLACE K3 WITH 'FAK'
            REPLACE BRKAL WITH MBRKAL
            replace datdok WITH mdatdok
            replace konto WITH '471'
         endif   
      ENDIF
   ENDIF     
   SELECT FAKG
   SKIP
ENDDO   
SELECT FAK
SET RELATION TO
USE
SELECT FAKG
USE
ENDIF
*---------------GLAVNA KNJIGA--------------------
USE NAL IN 0

SELECT NAL
COPY TO &KKOCKA4 FOR DOK=MDOK.AND.(DUG<>0.AND.(SUBSTR(KONTO,1,2)='27').or.(POT<>0.AND.substr(konto,1,2)='47'))
USE
USE &KKOCKA4 IN 0 ALIAS KOCKA4 EXCLU
SELECT KOCKA4
DELETE ALL FOR SUBSTR(konto,1,3)='279'
DELETE ALL FOR SUBSTR(konto,1,3)='479'
PACK
REPLACE ALL POT WITH -POT FOR SUBSTR(KONTO,1,1)='4'
INDEX ON BRNAL+SUBSTR(KONTO,1,3)  TAG BRNAL
SET ORDER TO 1
SELECT KOCKA
GO TOP
DO WHILE.NOT.EOF()
   M3KONTO=SUBSTR(konto,1,3)
   MBRNAL=BRNAL
   mdatdok=datdok
   SELECT KOCKA4
   SEEK MBRNAL+M3KONTO
   IF FOUND()
      MDUG=0
      MPOT=0
      DO WHILE.NOT.EOF()
         IF BRNAL+SUBSTR(KONTO,1,3)<>MBRNAL+M3KONTO
            EXIT
         ENDIF   
         IF SUBSTR(konto,1,3)=m3KONTO
            MDUG=MDUG+DUG
            MPOT=MPOT+POT
         ENDIF
         REPLACE KONTO WITH '9999999999'
         SKIP
      ENDDO      
      SELECT KOCKA
      REPLACE UDUG WITH MDUG
      REPLACE UPOT WITH MPOT
   ENDIF 
   SELECT KOCKA
   AATVISERVIS071.LBLKAL.CAPTION=' GLAVNA KNJIGA '+MBRNAL+' '+DTOC(MDATDOK)
   SKIP
ENDDO
SELECT KOCKA4
DELETE ALL FOR KONTO='9999999999'
PACK

IF RECCOUNT()>0
   DO IDEL WITH (KKOCKAX5)
   COPY TO &KKOCKA5 
   USE &KKOCKA5 IN 0 ALIAS KOCKA5 EXCLU
   SELECT KOCKA5
   GO TOP
   DO WHILE.NOT.EOF()
      MKONTO=KONTO
      MBRNAL=BRNAL
      MUDUG=DUG
      MUPOT=POT
      MDATDOK=DATDOK
      SELECT KOCKA
      APPEND BLANK
      REPLACE BRNAL WITH MBRNAL
      REPLACE UDUG WITH MUDUG
      REPLACE UPOT WITH MUPOT
      REPLACE DATDOK WITH MDATDOK
      REPLACE KONTO WITH MKONTO
      SELECT KOCKA5
      AATVISERVIS071.LBLKAL.CAPTION=' IZRACUNAVANJE SALDA '+MBRNAL+' '+DTOC(MDATDOK)
      SKIP
   ENDDO   
   SELECT KOCKA5
   USE
ENDIF      
SELECT KOCKA4
USE
SELECT KOCKA
GO TOP
DO WHILE.NOT.EOF()
   REPLACE SALDO WITH DUG-POT
   REPLACE USALDO WITH UDUG-UPOT
   REPLACE DSALDO WITH SALDO-USALDO
   SKIP
ENDDO   

GO TOP
   SELECT KOCKA
   GO TOP
   DO WHILE.NOT.EOF()
      MKONTO=KONTO
      MK3=K3
      MSALDO=SALDO
      MUSALDO=USALDO
      MDSALDO=DSALDO
      MDATDOK=DATDOK
      MDOK=DOK
      MBRNAL=BRNAL
      MBRKAL=BRKAL
      SELECT SVESLAG
      APPEND BLANK
      REPLACE KONTO WITH MKONTO
      REPLACE VRSTA WITH MK3
      REPLACE ROBNO WITH MSALDO
      REPLACE GKNJIGA WITH MUSALDO
      REPLACE RAZLIKA WITH MDSALDO
      REPLACE BRNAL WITH MBRNAL
      REPLACE DOK WITH MDOK
      REPLACE DATDOK WITH MDATDOK
      REPLACE SIFARNIK WITH T2SIFARNIK
      REPLACE BRKAL WITH MBRKAL
      SELECT KOCKA
      AATVISERVIS071.LBLKAL.CAPTION=' PUNJENJE GLAVNE BAZE '+MBRNAL+' '+DTOC(MDATDOK)
      SKIP
   ENDDO   
SELECT NALIZV
USE
SELECT KOCKA
USE
SELECT SVESLAG
SET EXACT OFF
POP KEY