PUSH KEY CLEAR
IF PPASAN=1
   SELECT AN0
   APPEND BLANK
   REPLACE SIFRA WITH STR(RECNO(),5,0)
   replace pib2 WITH sifra
   AN0.GRD0.SETFOCUS
   DO FORM AN0K2
   AN0.GRD0.SETFOCUS
   AN0.REFRESH
ELSE
   PUBLIC PPORUKA
   PPORUKA=' NEMATE PRAVO DODAVANJA NOVIH PARTNERA '
   DO PORUKA 
ENDIF
POP KEY