PUSH KEY CLEAR
IF PPASAN=1
   SELECT AN0
   APPEND BLANK
   REPLACE FLSIFRA WITH '99999'
   REPLACE JMBG WITH '9999999999999'
   replace PIB2 WITH FLSIFRA
   REPLACE DATUM WITH DATE()
   AN0fizli.GRD0.SETFOCUS
   DO FORM AN0fizliK2
   AN0fizli.GRD0.SETFOCUS
   AN0fizli.REFRESH
ELSE
   PUBLIC PPORUKA
   PPORUKA=' NEMATE PRAVO DODAVANJA NOVIH FIZICKIH LICA '
   DO PORUKA 
ENDIF
POP KEY