PUSH KEY CLEAR
IF PPASAN=1
   SELECT AN0
   DO FORM AN0FIZLIK2
   AN0FIZLI.GRD0.SETFOCUS 
 
ELSE
   PUBLIC PPORUKA
   PPORUKA=' NEMATE PRAVO PROMENE PODATAKA FIZICKIH LICA '
   DO PORUKA 
ENDIF
POP KEY