PUSH KEY CLEAR
SELECT AN0MI
SET ORDER TO 
GO BOTTOM
APPEND BLANK
GO BOTTOM
AN0MI.GRD0.SetFocus
AN0MI.GRD0.REFRESH
REPLACE MISIFRA WITH STR(RECNO(),5,0)
DO FORM AN0MIKART
GO BOTTOM
AN0MI.GRD0.SetFocus
AN0MI.GRD0.REFRESH
AN0MI.REFRESH  
POP KEY