PARAMETERS AGR
MGRUPA=GRUPA1
PUSH KEY CLEAR
IF AGR=0
   *REPORT FORM AN0PREGDUG0 PREVIEW FOR (STARIDUG<>0.OR.MESECNO<>0).AND.(GRUPA1=MGRUPA)
   mfile='AN0PREGDUG0'
   uslov="(STARIDUG<>0.OR.MESECNO<>0).AND.(GRUPA1=MGRUPA)" 
   DO printer_bullzip WITH mdata02,mfile,uslov
   
ELSE
   *REPORT FORM AN0PREGDUG0 PREVIEW FOR STARIDUG<>0.OR.MESECNO<>0
   mfile='AN0PREGDUG0'
   uslov="STARIDUG<>0.OR.MESECNO<>0" 
   DO printer_bullzip WITH mdata02,mfile,uslov
ENDIF

POP KEY
