PUSH KEY CLEAR
SET EXACT OFF
DO IDEL WITH (KKOCKAX)
DO IDEL WITH (KKOCKAX2)
MDAT0=ANALOTV.TXTDAT0.VALUE
MDAT1=ANALOTV.TXTDAT1.VALUE
public iosdat1
iosdat1=mdat1
MGRUPAK=ANALOTV.TXTGRUPAK.VALUE
MGRUPA1=ANALOTV.TXTGRUPA1.VALUE
MGRUPA2=ANALOTV.TXTGRUPA2.VALUE
MGRUPA3=ANALOTV.TXTGRUPA3.VALUE


KANAL='ANAL'+TANREDNI

USE FIRMA IN 0

   USE &KANAL IN 0 ALIAS anal
   SELECT anal
   USE

MDOK=ANALOTV.TXTDOK.VALUE
MMP=ANALOTV.TXTMP.VALUE
MMTR=ANALOTV.TXTMTR.VALUE




*use &kANALK IN 0 EXCLU ALIAS ANALK
*SELECT analk
*DELETE ALL
*PACK
*SET ORDER TO

IF TSIFARNIK<>'  '
  KAN0='AN0'+ALLTRIM(TSIFARNIK)
ELSE
   KAN0='AN0'
ENDIF

   USE &KAN0 IN 0 ALIAS an0
   SELECT an0
   USE

 *  USE &KAN0 IN 0 ORDER 1 ALIAS AN0

SELECT ANAL.SIFRA,DATDOK,VALUTA,BRRAC,DUG,POT,DEVDUG,DEVPOT,DEVSALDO,SALDO,BRNAL,AN0.NAZIV,AN0.POSTA,AN0.MESTO,AN0.ULICA,AN0.ULBROJ,AN0.PIB,AN0.ZIRORAC,RREC,AN0.DOK,an0.republika FROM &KANAL AS ANAL;
   INNER JOIN &KAN0 AS AN0 ;
      ON ANAL.SIFRA = AN0.SIFRA ;
   INTO TABLE &KKOCKA;
   WHERE;
   (an0.GRUPA1=MGRUPA1.OR.MGRUPA1=SPACE(3));
   .AND.(an0.GRUPA2=MGRUPA2.OR.MGRUPA2=SPACE(3));
   .AND.(an0.GRUPA3=MGRUPA3.OR.MGRUPA3=SPACE(3));
   .AND.(AN0.DOK=MDOK.OR.MDOK=SPACE(3));
   .AND.(DATDOK>=MDAT0.AND.DATDOK<=MDAT1);
   .AND.(MP=MMP.OR.MMP=SPACE(2));
   .AND.(ANAL.GRUPA=MGRUPAK.OR.MGRUPAK=SPACE(3));
   .AND.(ZATVAR=' ')
   USE

*SELECT analk
USE &KKOCKA IN 0 ALIAS ANALK EXCLU
*APPEND FROM &KKOCKA
*SET RELATION TO SIFRA INTO an0 ADDITIVE
SELECT ANALK
INDEX ON SIFRA+BRRAC TAG SIFRA
INDEX ON NAZIV TAG NAZIV
INDEX ON NAZIV+SIFRA+DTOS(datdok) TAG NAZSIF
INDEX ON SIFRA+DTOs(datdok) TAG SIFRAdat
SET ORDER TO 1
TOTAL ON SIFRA+BRRAC TO &KKOCKA2
ZAP
APPEND FROM &KKOCKA2
REPLACE ALL SALDO WITH DUG-POT
GO TOP
DO FORM ANALOTV1


CLOSE ALL TABLES
POP KEY
ANALOTV.RELEASE