PUSH KEY CLEAR
  IF PPASAN=1
  AN.CMDBRISI.SETFOCUS
  CLOSE ALL TABLES
  USE &KANAL EXCLU IN 0 ALIAS ANAL

  SELECT ANAL
  DELETE ALL FOR DUG=0.AND.POT=0.AND.DEVDUG=0.AND.DEVPOT=0
  PACK
  AN.RELEASE
  ELSE
  PUBLIC PPORUKA
  PPORUKA=' NEMATE PRAVO BRISANJA PRAZNIH POLJA U ANALITICI '
  DO PORUKA 

  ENDIF
  POP KEY