PUSH KEY CLEAR
SET EXACT OFF
MDAT0=analopomene.TXTDAT0.VALUE
MDAT1=analopomene.TXTDAT1.VALUE
public iosdat1
iosdat1=mdat1
MGRUPAK=analopomene.TXTGRUPAK.VALUE
MGRUPA1=analopomene.TXTGRUPA1.VALUE
MGRUPA2=analopomene.TXTGRUPA2.VALUE
MGRUPA3=analopomene.TXTGRUPA3.VALUE


KANAL='ANAL'+TANREDNI

USE FIRMA IN 0

USE &KANAL IN 0 ALIAS anal
SELECT anal
GO TOP

MDOK=analopomene.TXTDOK.VALUE
MMP=analopomene.TXTMP.VALUE
MMTR=analopomene.TXTMTR.VALUE

use &kANALK IN 0 EXCLU ALIAS ANALK
SELECT analk
DELETE ALL
PACK
SET ORDER TO

IF TSIFARNIK<>'  '
  KAN0='AN0'+ALLTRIM(TSIFARNIK)
ELSE
   KAN0='AN0'
ENDIF
   
USE &KAN0 IN 0 ORDER 1 ALIAS AN0
SELECT anal
SET RELATION TO SIFRA INTO an0 additive
SET ORDER TO 6
GO TOP
do while.not.eof()
   MSIFRA=SIFRA
   analopomene.LBLFIRMA.CAPTION=SIFRA+' '+AN0.NAZIV 
   if an0.GRUPA1=MGRUPA1.OR.MGRUPA1=SPACE(3)
      if an0.GRUPA2=MGRUPA2.OR.MGRUPA2=SPACE(3)                  
         if an0.GRUPA3=MGRUPA3.OR.MGRUPA3=SPACE(3)
            if Anal.DOK=MDOK.OR.MDOK=SPACE(3)
               if valuta>=MDAT0.AND.valuta<=MDAT1
                  if MP=MMP.OR.MMP=SPACE(2)
                     if GRUPA=MGRUPAK.OR.MGRUPAK=SPACE(3)
                        IF ZATVAR=' '
                           MNAZIV=AN0.NAZIV
                           MPOSTA=AN0.POSTA
                           MMESTO=AN0.MESTO
                           MULICA=AN0.ULICA
                           MULBROJ=AN0.ULBROJ
                           MZIRORAC=AN0.ZIRORAC
                           MTEL=AN0.TELEFON
                           MFAX=AN0.FAX
                           SCATTER NAME POLJA
                           SELECT analk
                           APPEND BLANK
                           GATHER NAME POLJA
                           REPLACE NAZIV WITH MNAZIV
                           REPLACE POSTA WITH MPOSTA
                           REPLACE MESTO WITH MMESTO
                           REPLACE ULICA WITH MULICA
                           REPLACE ULBROJ WITH MULBROJ
                           REPLACE ZIRORAC WITH MZIRORAC
                           REPLACE TELEFON WITH MTEL
                           REPLACE FAX WITH MFAX
                           SELECT anal
                        ENDIF
                     endif   
                  endif        
               endif
            endif
         ENDIF
      ENDIF         
   endif
   skip
enddo          
go top
SELECT anal
SET RELATION TO
USE 
SELECT analk
   DO IDEL WITH (Kkockax)
   DO IDEL WITH (Kkockax2)
   DO IDEL WITH (Kkockax3)

*--------AKO JE DUGOVNI SALDO----------
IF TDP='D'

COPY TO &KKOCKA FOR DUG<>0
COPY TO &KKOCKA2 FOR POT<>0

USE &KKOCKA2 IN 0 ALIAS KOCKA2 EXCLU
SELECT KOCKA2
INDEX ON SIFRA+BRRAC TAG SIFRAC
TOTAL ON SIFRA+BRRAC TO &KKOCKA3 FIELDS POT
DELETE ALL
PACK
APPEND FROM &KKOCKA3
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
SELECT KOCKA
GO TOP
DO WHILE.NOT.EOF()
   MSIFRAC=SIFRA+BRRAC
   SELECT KOCKA2 
   SEEK MSIFRAC
   IF FOUND()
      MPOT=POT
   ELSE
      MPOT=0
   ENDIF
   SELECT KOCKA 
   REPLACE POT WITH MPOT       
   SKIP
ENDDO   
SELECT KOCKA
USE
SELECT ANALK
DELETE ALL
PACK
APPEND FROM &KKOCKA
GO TOP
DO WHILE.NOT.EOF()
   REPLACE SALDO WITH DUG-POT
   SKIP
ENDDO


ELSE

*--------AKO JE DUGOVNI SALDO----------

COPY TO &KKOCKA FOR POT<>0
COPY TO &KKOCKA2 FOR DUG<>0

USE &KKOCKA2 IN 0 ALIAS KOCKA2 EXCLU
SELECT KOCKA2
INDEX ON SIFRA+BRRAC TAG SIFRAC
TOTAL ON SIFRA+BRRAC TO &KKOCKA3 FIELDS DUG
DELETE ALL
PACK
APPEND FROM &KKOCKA3
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
SELECT KOCKA
GO TOP
DO WHILE.NOT.EOF()
   MSIFRAC=SIFRA+BRRAC
   SELECT KOCKA2 
   SEEK MSIFRAC
   IF FOUND()
      MDUG=DUG
   ELSE
      MDUG=0
   ENDIF
   SELECT KOCKA 
   REPLACE DUG WITH MDUG       
   SKIP
ENDDO   
SELECT KOCKA
USE
SELECT ANALK
DELETE ALL
PACK
APPEND FROM &KKOCKA
GO TOP
DO WHILE.NOT.EOF()
   REPLACE SALDO WITH POT-DUG
   SKIP
ENDDO

ENDIF
GO TOP      
SET RELATION TO SIFRA INTO an0 ADDITIVE

DO FORM ANALOPOMENE1

SELECT analk
USE
SELECT an0
USE
CLOSE ALL TABLES
POP KEY
ANALOPOMENE.RELEASE
