PUSH KEY CLEAR
SET EXACT ON
SELECT ANALP
SET ORDER TO 3
DO IDEL WITH (KKOCKAX)
DO IDEL WITH (KKOCKAX2)
IF TDP='D'
COPY TO &KKOCKA FOR DUG<>0
ELSE
COPY TO &KKOCKA FOR POT<>0
ENDIF
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
SELECT KOCKA

REPLACE ALL DDUG WITH 1
INDEX ON SIFRA+BRRAC TAG SR
SET ORDER TO 1
TOTAL ON SIFRA+BRRAC FIELDS DDUG TO &KKOCKA2
ZAP
SELECT KOCKA
SET ORDER TO 
ZAP
USE &KKOCKA2 IN 0 ALIAS KOCKA2 EXCLU
SELECT KOCKA2
DELETE ALL FOR DDUG=1
PACK
GO TOP
DO WHILE.NOT.EOF()
   MSIFRAC=SIFRA+BRRAC
   SELECT ANALP
   SEEK MSIFRAC
   IF FOUND()
      MIMA=0
      DO WHILE.NOT.EOF()
         IF SIFRA+BRRAC<>MSIFRAC
            EXIT
         ENDIF
         IF TDP='D'
            IF DUG<>0
               SCATTER NAME POLJA
               MIMA=1
            ELSE
               MIMA=0
            ENDIF
         ELSE
            IF POT<>0
               SCATTER NAME POLJA
               MIMA=1
            ELSE
               MIMA=0   
            ENDIF
         ENDIF      
         IF MIMA=1
            SELECT KOCKA
            APPEND BLANK
            GATHER NAME POLJA
         ENDIF
         SELECT ANALP
         SKIP
      ENDDO      
   ENDIF
   SELECT KOCKA2
   SKIP
ENDDO   
SELECT KOCKA2
USE
SELECT KOCKA
SET RELATION TO SIFRA INTO AN0 ADDITIVE
GO TOP
SET CENTURY OFF
*REPORT FORM ANALIZVPROVDUPRAC PREVIEW
      mfile='ANALIZVPROVDUPRAC'
      uslov=""
      DO printer_bullzip WITH mdata02,mfile,uslov

SET CENTURY ON
SELECT KOCKA
SET RELATION TO
USE
SELECT ANALP
SET ORDER TO 
SET EXACT OFF
POP KEY
