SELECT ANALK
PUSH KEY CLEAR
SET CENTURY OFF
   PUBLIC ADOSPELO
   ADOSPELO=0
   *REPORT FORM ANALK02 preview
   mfile='ANALK02'
   uslov=""
   DO printer_bullzip WITH mdata02,mfile,uslov
   
SET CENTURY ON
POP KEY 
