PUSH KEY CLEAR
MSTANJE=ANALUPL.TXTSTANJE.VALUE
IF TDP='D'
PUSH KEY CLEAR
   IF MSTANJE>0
      IF MSTANJE>=DUG
         REPLACE POT WITH DUG
      ELSE
         REPLACE POT WITH MSTANJE
      ENDIF
   ENDIF
   ANALUPL.GRD0.REFRESH
   ANALUPL.GRD0.SETFOCUS
   POP KEY
   ANALUPL.REFRESH         
ELSE   
PUSH KEY CLEAR
   IF MSTANJE>0
      IF MSTANJE>=POT
         REPLACE DUG WITH POT
      ELSE
         REPLACE DUG WITH MSTANJE
      ENDIF
   ENDIF
   ANALUPL.GRD0.REFRESH
   ANALUPL.GRD0.SETFOCUS
   POP KEY
   ANALUPL.REFRESH         
ENDIF   
POP KEY