PUSH KEY CLEAR
SELECT ANALK
   DO IDEL WITH (Kkockax)
   DO IDEL WITH (Kkockax2)
   DO IDEL WITH (Kkockax3)
SET ORDER TO 3

COPY TO &KKOCKA
USE &KKOCKA IN 0 ALIAS KOCKA EXCLUSIVE
SELECT KOCKA
INDEX ON BRRAC TAG BRRAC
SET ORDER TO 1
GO TOP
MSALDO=0
DO WHILE.NOT.EOF()
   MBRRAC=BRRAC
   MSALDO=MSALDO+DUG-POT
   REPLACE SALDO WITH MSALDO
   SKIP
   IF BRRAC<>MBRRAC
      MSALDO=0
      MBRRAC=BRRAC
      SKIP-1
   ELSE
      SKIP-1
   ENDIF   
   SKIP
ENDDO   
SET RELATION TO sifra INTO an0 additive
PUSH KEY CLEAR
   *REPORT FORM ANALK03RAC preview
   mfile='ANALK03RAC'
   uslov=""
   DO printer_bullzip WITH mdata02,mfile,uslov
   
POP KEY 
SELECT KOCKA
SET RELATION TO 
USE
SELECT ANALK
POP KEY
