PUSH KEY CLEAR
SET CENTURY OFF
SET EXACT OFF
SELECT AN0
MSIFRA=SIFRA
MDUG=0
MPOT=0
SELECT ANALKA
ZAP
SELECT ANALP
SET ORDER TO 2
SEEK MSIFRA
IF FOUND()
   DO WHILE.NOT.EOF()
      IF SIFRA<>MSIFRA
         EXIT
      ENDIF
      IF DUG<>0.OR.POT<>0.OR.DEVDUG<>0.OR.DEVPOT<>0
         SCATTER NAME LL
         MRREC=RECNO()
         MZATVAR=ZATVAR
         IF MA2ODAKLE=1
            IF MZATVAR=' '
               SELECT ANALKA
               APPEND BLANK
               GATHER NAME LL 
               MDUG=MDUG+DUG
               MPOT=MPOT+POT
               REPLACE RREC WITH MRREC     
               SELECT ANALP
            ENDIF
         ELSE
            SELECT ANALKA
            APPEND BLANK
            GATHER NAME LL 
            MDUG=MDUG+DUG
            MPOT=MPOT+POT
            REPLACE RREC WITH MRREC     
            SELECT ANALP
         ENDIF      
      ENDIF
      SELECT ANALP
      SKIP
   ENDDO     
ENDIF    
ANALKPREG.TXTDUG.Value=MDUG
ANALKPREG.TXTPOT.Value=MPOT
ANALKPREG.TXTSALDO.Value=MDUG-MPOT
ANALKPREG.GRD1.REFRESH   
SELECT ANALP
SEEK MSIFRA
SELECT AN0
ANALKPREG.GRD0.REFRESH   
ANALKPREG.GRD0.SETFOCUS
ANALKPREG.Refresh 
POP KEY
  
