PUSH KEY CLEAR
DO IDEL WITH (KKOCKAX)
SELECT ANALK
SORT ON DUG TO &KKOCKA DESCEND
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
SELECT KOCKA
SET RELATION TO SIFRA INTO AN0 ADDITIVE
*REPORT FORM ANALKSORTDUG preview
   mfile='ANALKSORTDUG'
   uslov=""
   DO printer_bullzip WITH mdata02,mfile,uslov

SELECT KOCKA
USE
SELECT ANALK
POP KEY 
