PUSH KEY CLEAR
SELECT ANALK
   DO IDEL WITH (Kkockax)
   DO IDEL WITH (Kkockax2)
   DO IDEL WITH (Kkockax3)


COPY TO &KKOCKA
USE &KKOCKA IN 0 ALIAS KOCKA EXCLUSIVE
SELECT KOCKA
INDEX ON DTOS(valuta) TAG VALUTA
SET ORDER TO 1
TOTAL ON DTOS(VALUTA) TO &KKOCKA2 FIELDS DUG,POT,DEVDUG,DEVPOT
DELETE ALL
PACK
APPEND FROM &KKOCKA2
GO TOP
MSALDO=0
MDEVSALDO=0
DO WHILE.NOT.EOF()
   MSALDO=MSALDO+DUG-POT
   REPLACE SALDO WITH MSALDO
   MDEVSALDO=MDEVSALDO+DEVDUG-DEVPOT
   REPLACE DEVSALDO WITH MDEVSALDO
   SKIP
ENDDO   
GO TOP
SET RELATION TO sifra INTO an0 additive
PUSH KEY CLEAR

   *REPORT FORM ANALK03V preview
   mfile='ANALK03V'
   uslov=""
   DO printer_bullzip WITH mdata02,mfile,uslov
   
POP KEY 
SELECT KOCKA
SET RELATION TO 
USE
SELECT ANALK
POP KEY
