PUSH KEY CLEAR
SELECT ANALK
   DO IDEL WITH (Kkockax)
   DO IDEL WITH (Kkockax2)
   DO IDEL WITH (Kkockax3)


COPY TO &KKOCKA
USE &KKOCKA IN 0 ALIAS KOCKA EXCLUSIVE
SELECT KOCKA
INDEX ON DATDOK TAG DATDOK
SET ORDER TO 1
IF TDP='D'
   COPY TO &KKOCKA2 FOR POT<>0
   DELETE ALL FOR POT<>0
   PACK
   
ELSE
   COPY TO &KKOCKA2 FOR DUG<>0
   DELETE ALL FOR DUG<>0
   PACK
ENDIF      
USE &KKOCKA2 IN 0 ALIAS KOCKA2 EXCLU
SELECT KOCKA2
INDEX ON BRNAL TAG BRNAL
TOTAL ON BRNAL TO &KKOCKA3 FIELDS DUG,POT,DEVDUG,DEVPOT
DELETE ALL
PACK
APPEND FROM &KKOCKA3
USE
SELECT KOCKA
APPEND FROM &KKOCKA2
GO TOP
MSALDO=0
MSALDOD=0
DO WHILE.NOT.EOF()
   MSALDO=MSALDO+DUG-POT
   REPLACE SALDO WITH MSALDO
   MSALDOD=MSALDOD+DEVDUG-DEVPOT
   REPLACE DEVSALDO WITH MSALDOD
   SKIP
ENDDO
GO TOP   
SET RELATION TO sifra INTO an0 additive
PUSH KEY CLEAR

   *REPORT FORM ANALK03U preview

   mfile='ANALK03U'
   uslov=""
   DO printer_bullzip WITH mdata02,mfile,uslov

   
POP KEY 
SELECT KOCKA
SET RELATION TO 
USE
SELECT ANALK
POP KEY