PUSH KEY CLEAR
DO IDEL WITH (KKOCKAX)
SELECT ANALK
SORT ON POT TO &KKOCKA DESCEND
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
SELECT KOCKA
SET RELATION TO SIFRA INTO AN0 ADDITIVE
*REPORT FORM ANALKSORTPOT preview
   mfile='ANALKSORTPOT'
   uslov=""
   DO printer_bullzip WITH mdata02,mfile,uslov

SELECT KOCKA
USE
SELECT ANALK
POP KEY 
