PUSH KEY CLEAR
IF PPASAN=1
   SET ORDER TO 
   IF RECCOUNT()>0
      MOPIS=OPIS
      MBRNAL=BRNAL
      MDATDOK=DATDOK
      MVALUTA=VALUTA
      MKONTO=KONTO
      MDOG=DOK
      APPEND BLANK
      REPLACE KONTO WITH MKONTO
      REPLACE OPIS WITH MOPIS
      REPLACE BRNAL WITH MBRNAL
      REPLACE DATDOK WITH MDATDOK
      REPLACE VALUTA WITH MVALUTA
      REPLACE OPER WITH OPERATER
      REPLACE DATUM WITH DATE()
      REPLACE VREME WITH TIME()   
      AN.GRD0.SETFOCUS
      replace konto with tkonto
      AN.REFRESH
   ELSE
      APPEND BLANK
      REPLACE DATDOK WITH DATE()
      replace konto with tkonto
   ENDIF
   AN.GRD0.COLUMN1.SETFOCUS
   AN.REFRESH  
ELSE
   PUBLIC PPORUKA
   PPORUKA=' NEMATE PRAVO DODAVANJA POLJA U ANALITICI '
   DO PORUKA 
ENDIF
POP KEY