PARAMETERS AODAKLE
PUSH KEY CLEAR
DO FORM ANALK WITH AODAKLE
SET ORDER TO
SET EXACT ON
DO CASE TANAL
CASE tanal='ANP'
   ANP.REFRESH
CASE tanal='ANI'
   ANIZV.REFRESH
CASE tanal='ANA'
   AN.REFRESH
CASE tanal='APL'
   ANPL0.REFRESH 
CASE tanal='ANAP'
   SELECT AN0
   SET ORDER TO 2
   ANALKPREG.GRD0.RECORDSOURCE='AN0'
   ANALKPREG.GRD0.COLUMN2.SETFOCUS
   ANALKPREG.REFRESH
ENDCASE
SET EXACT OFF
POP KEY