SET ORDER TO 2
MSIFRA=SIFRA
MBRNAL=BRNAL
PUSH KEY CLEAR
*REPORT FORM ANODOB0 PREVIEW FOR Msifra=sifra.AND.BRNAL=MBRNAL

   mfile='ANODOB0'
   uslov="Msifra=sifra.AND.BRNAL=MBRNAL"
   DO printer_bullzip WITH mdata02,mfile,uslov


POP KEY