PUSH KEY CLEAR
   APPEND BLANK
   REPLACE REDBR WITH STR(RECNO(),2,0)
   REPLACE DAT0 WITH DATE()
   REPLACE DAT1 WITH DATE()
   SELECT ANODOB00
   ANODOB00.GRD0.COLUMN1.SETFOCUS
   ANODOB00.REFRESH  
POP KEY