IF PPASAN=1
   CLOSE ALL TABLES
   PUSH KEY CLEAR
   IF TANAL='ANP'
      USE &KANALP EXCLU IN 0 ALIAS ANAL
      
   ELSE
      USE &KANAL EXCLU ALIAS ANAL IN 0
   ENDIF
   SELECT ANAL
   DELETE ALL FOR DUG=0.AND.POT=0
   PACK
   POP KEY
   ANP.RELEASE
ENDIF  
