PUSH KEY CLEAR
SELECT ANALP
SET RELATION TO
DO FORM FAN0
SET EXact ON
DO CASE TANAL
CASE TANAL='ANI'
   ANIZV.GRD0.SETFOCUS
   POP KEY
   ANIZV.REFRESH
CASE TANAL='INV'
   INVEST.GRD0.SETFOCUS
   POP KEY
   INVEST.REFRESH
CASE TANAL='INP'
   INVESTP.GRD0.SETFOCUS
   POP KEY
   INVESTP.REFRESH
OTHERWISE
   AN.GRD0.SETFOCUS
   POP KEY
   AN.REFRESH
ENDCASE
SET EXact OFF