PUSH KEY CLEAR
SET RELATION TO
DO FORM FAN0
SELECT AN0
MSIFRA=SIFRA
SELECT NALP
IF SIFRA=SPACE(5)
   REPLACE SIFRA WITH MSIFRA
ENDIF   
SET RELATION TO KONTO INTO KONTO ADDITIVE
SET RELATION TO MP INTO MESTA ADDITIVE
SET RELATION TO MTR INTO MTR ADDITIVE
SET RELATION TO SIFRA INTO AN0 ADDITIVE
NALPEP.GRD0.SETFOCUS
NALPEP.REFRESH
POP KEY
