IF PPASAN=1
   PUSH KEY CLEAR 
   SELECT ANALP
   USE
   IF TANAL='ANP'
       USE &KANALP EXCLU IN 0 ALIAS ANALP
   ELSE
       USE &KANAL EXCLU ALIAS ANALP IN 0
   ENDIF
   SELECT ANALP
   DELETE ALL FOR DUG=0.AND.POT=0
   PACK
   SET RELATION TO MP INTO MESTA ADDITIVE
   SET RELATION TO MTR INTO MTR ADDITIVE
   SET RELATION TO SIFRA INTO AN0 ADDITIVE
   SELECT ANALP
   POP KEY
   ANP.RELEASE
ENDIF  
