DO IDEL WITH (KKOCKAX)
DO IDEL WITH (KKOCKAX2)
USE ROB IN 0 
SELECT ROB
COPY TO &KKOCKA
USE &KKOCKA IN 0 ALIAS KOCKA EXCLUSIVE
SELECT KOCKA
INDEX ON GRUPA TAG GRUPA
SET ORDER TO 1
TOTAL ON GRUPA TO &KKOCKA2 FOR GRUPA<>'   '
USE
SELECT ROB
USE
SELECT ANPUTG0
USE
USE ANPUTG0 IN 0 EXCLUSIVE 

SELECT ANPUTG0
SET ORDER TO 
DELETE ALL
PACK
APPEND FROM &KKOCKA2

ANPUTGRU.GRD0.SETFOCUS
ANPUTGRU.REFRESH

