PUSH KEY CLEAR
SELECT ANPUTG0
APPEND BLANK
   *--------NAPRAVI PROVERU   
   USE PROVERAI IN 0 
   SELECT PROVERAI
   replACE TDBan WITH '0'   
   mtdban=tdban
   USE
   SELECT ANputg0

ANPUTGRU.GRD0.SETFOCUS
ANPUTGRU.REFRESH  
POP KEY