PUSH KEY CLEAR
SET EXACT OFF
SET ORDER TO 4
IF ARHIVA=' '
   MBRNAL=BRNAL
   SEEK MBRNAL
   DO WHILE.NOT.EOF()
      IF BRNAL<>MBRNAL
         EXIT
      ENDIF
      REPLACE ARHIVA WITH '*'   
      SKIP
   ENDDO   
   SEEK MBRNAL
ELSE
   MBRNAL=BRNAL
   SEEK MBRNAL
   DO WHILE.NOT.EOF()
      IF BRNAL<>MBRNAL
         EXIT
      ENDIF
      REPLACE ARHIVA WITH ' '   
      SKIP
   ENDDO   
   SEEK MBRNAL
ENDIF
SET ORDER TO
AN.GRD0.SETFOCUS
POP KEY
AN.REFRESH