PUSH KEY CLEAR
MBRKAL=BRKAL
SET ORDER TO 1
   LOCATE FOR BRKAL=MBRKAL


*REPORT FORM ASNAL08 FOR BRKAL=MBRKAL PREVIEW 
   mfile='ASNAL08'
   uslov="BRKAL=MBRKAL"
   DO printer_bullzip WITH mdata02,mfile,uslov

SELECT ASNAL
   LOCATE FOR BRKAL=MBRKAL

SET ORDER TO 
POP KEY
