PUSH KEY CLEAR
IF RECCOUNT()>0
   IF ASNALG.ARHIVA=' '
      *---AKO NIJE ARHIVIRANA-----
      MBRKAL=BRKAL
      MDATDOK=DATDOK
      APPEND BLANK
      REPLACE BRKAL WITH MBRKAL 
      REPLACE DATDOK WITH MDATDOK
      ASNAL.GRD0.SETFOCUS
      ASNAL.REFRESH
   ELSE
      *------AKO JE KALKULACIJA  ARHIVIRANA
      SELECT ASNAL
      SET ORDER TO 1 
      GO BOTTOM
      MBRKAL=BRKAL
      MNLEN=LEN(ALLTRIM(STR(VAL(ALLTRIM(MBRKAL))+1,6,0)))
      MNBRKAL=REPLI('0',6-MNLEN)+ALLTRIM(STR(VAL(ALLTRIM(MBRKAL))+1,6,0))
      SET ORDER TO 1
            LOCATE FOR BRKAL=MNBRKAL

      IF.NOT.FOUND()
         APPEND BLANK
         REPLACE BRKAL WITH MNBRKAL 
         ASNAL.GRD0.SETFOCUS
         ASNAL.GRD0.REFRESH
         ASNAL.REFRESH
      ENDIF
      SELECT ASNALG
            LOCATE FOR BRKAL=MNBRKAL

      IF.NOT.FOUND()
         APPEND BLANK
         REPLACE BRKAL WITH MNBRKAL
      ENDIF      
      DO FORM ASNALZAG
      SELECT ASNAL
            LOCATE FOR BRKAL=MNBRKAL

      REPLACE DATDOK WITH ASNALG.DATDOK    
      SET ORDER TO 
   ENDIF 
ELSE
   *--------AKO PRVA STAVKA NE POSTOJI---------
   APPEND BLANK
   MNBRKAL='000001'
   REPLACE BRKAL WITH MNBRKAL 
   *------IDEMO U ZAGLAVLJE
   IF .NOT.FOUND()
      SELECT ASNAL
      SET RELATION TO
      SELECT ASNALG
            LOCATE FOR BRKAL=MNBRKAL

      IF.NOT.FOUND()
         APPEND BLANK
         REPLACE BRKAL WITH MNBRKAL
      ENDIF     
      DO FORM ASNALZAG
      SELECT ASNAL
      SET RELATION TO BRKAL INTO ASNALG ADDITIVE
      SET RELATION TO RSIF INTO ROB ADDITIVE
      REPLACE DATDOK WITH ASNALG.DATDOK
   ENDIF   
ENDIF    

POP KEY
SELECT ASNAL
SET ORDER TO
ASNAL.GRD0.COLUMN2.SETFOCUS
ASNAL.REFRESH  
