PUSH KEY CLEAR
MBRKAL=BRKAL
SET ORDER TO 1
   LOCATE FOR BRKAL=MBRKAL
*REPORT FORM ASNAL01MAT FOR BRKAL=MBRKAL.AND.(ROB.VRSTA='N') preview
   mfile='ASNAL01MAT'
   uslov="BRKAL=MBRKAL.AND.(ROB.VRSTA='N')"
   DO printer_bullzip WITH mdata02,mfile,uslov

SELECT ASNAL
LOCATE FOR BRKAL=MBRKAL
SET ORDER TO 
POP KEY
