PUSH KEY CLEAR
MBRKAL=BRKAL
SELECT ASNAL
SET RELATION TO
SELECT ASNALG
   LOCATE FOR BRKAL=MBRKAL

IF FOUND()
   IF ARHIVA=' '
      REPLACE ARHIVA WITH '*'
   ELSE
      REPLACE ARHIVA WITH ' '  
   ENDIF       
ENDIF
SELECT ASNAL
SET ORDER TO 1
   LOCATE FOR BRKAL=MBRKAL

SET ORDER TO 
SET RELATION TO BRKAL INTO ASNALG  ADDITIVE
SET RELATION TO RSIF INTO ROB ADDITIVE
ASNAL.GRD0.Refresh
ASNAL.GRD0.SETFOCUS
POP KEY
ASNAL.Refresh 

