PUSH KEY CLEAR
MBRKAL=BRKAL
SET ORDER TO 1
   LOCATE FOR BRKAL=MBRKAL
*REPORT FORM ASNAL01 FOR BRKAL=MBRKAL.AND.(ROB.VRSTA='U') preview
   mfile='ASNAL01'
   uslov="BRKAL=MBRKAL.AND.(ROB.VRSTA='U')"
   DO printer_bullzip WITH mdata02,mfile,uslov

SELECT ASNAL
LOCATE FOR BRKAL=MBRKAL
SET ORDER TO 
POP KEY
