PUSH KEY CLEAR
      SELECT ASNAL
      MBRKAL=BRKAL
      SET RELATION TO
      SELECT ASNALG
      DO FORM ASNALZAG
      SELECT ASNAL
      SET RELATION TO BRKAL INTO ASNALG ADDITIVE
      SET RELATION TO RSIF INTO ROB ADDITIVE
      SET RELATION TO sifneisp INTO asneisp ADDITIVE      
      SET ORDER TO 1
         LOCATE FOR BRKAL=MBRKAL

      IF FOUND()
         DO WHILE.NOT.EOF()
            IF BRKAL<>MBRKAL
               EXIT
            ENDIF   
            REPLACE DATDOK WITH ASNALG.DATDOK
            SKIP
         ENDDO
            LOCATE FOR BRKAL=MBRKAL

      ENDIF
      SET ORDER TO 
      ASNAL.GRD0.SETFOCUS
POP KEY      
      ASNAL.REFRESH      