PUSH KEY CLEAR
IF ASNALG.ARHIVA=' '
   MSBRKAL=BRKAL
   USE &KFAK ALIAS FAK IN 0 ORDER 1
      SET ORDER TO 1
   USE &KFAKG IN 0 ALIAS FAKG ORDER 1
   SELECT FAK
   GO BOTTOM
   MNBRKAL='      '
   MNOVI=VAL(BRKAL)+1
   DO WHILE.T.
      MLEN=LEN(ALLTRIM(STR(MNOVI)))
      MNBRKAL=REPLI('0',6-MLEN)+ALLTRIM(STR(MNOVI))
            LOCATE FOR BRKAL=MNBRKAL

      IF FOUND()
         MNOVI=MNOVI+1
         LOOP
      ELSE
         EXIT
      ENDIF
   ENDDO
   SELECT ASNAL
   SET ORDER TO 1
   MMODEL=ASNALG.MODEL
   MREGBR=ASNALG.REGBR
   SET RELATION TO
   SELECT FAK
   SET RELATION TO BRKAL INTO FAKG ADDITIVE 
   SET RELATION  TO RSIF INTO ROB ADDITIVE
   SELECT ASNAL
   SET RELATION TO BRKAL INTO ASNALG ADDITIVE
   SEEK MSBRKAL
   IF FOUND()
      MSIFRA=ASNALG.SIFRA
      MDATDOK=ASNALG.DATDOK
      DO WHILE.NOT.EOF()
         IF BRKAL<>MSBRKAL
            EXIT
         ENDIF
         MBRRAC=MSBRKAL
         MRSIF=RSIF
         MKOL=KOL
         MMALCENA=MALCENA
         MMALVRED=MALVRED
         SELECT ROB
         SEEK MRSIF
         MPROCPOR=ROB.PROCPOR
         MTARIFA=ROB.TARIFA
         MVELCENA=ROB.VELCENA
*         MMALCENA=ROB.MALCENA
         MVRSTA=ROB.VRSTA
         MCENA=ROB.ZADNABM
         SELECT ASNAL
         MSIFRA=ASNALG.SIFRA
         SELECT FAK
         IF MKOL<>0
            APPEND BLANK 
            REPLACE BRKAL WITH MNBRKAL
            REPLACE RSIF WITH MRSIF
            REPLACE KOLI WITH MKOL
            REPLACE CENA WITH MCENA
            REPLACE VELCENA WITH MVELCENA
            REPLACE MALCENA WITH MMALCENA
            REPLACE IZNI WITH KOLI*CENA
            REPLACE MALVRED WITH KOLI*MALCENA
            REPLACE POREZ WITH ROUND(MALVRED*PROCPOR/(100+PROCPOR),2)
            REPLACE VELVRED WITH MALVRED-POREZ
            REPLACE VELCENA WITH ROUND(VELVRED/KOLI,3)
            REPLACE MARZA WITH VELVRED-IZNI
            IF IZNI<>0
               REPLACE MARPROC WITH ROUND(MARZA*100/IZNI,6)
            ELSE
               REPLACE MARPROC WITH 0
            ENDIF
         ENDIF
         SELECT ASNAL
         SKIP
      ENDDO
   ENDIF   
   SELECT FAKG
         LOCATE FOR BRKAL=MNBRKAL

   IF.NOT.FOUND()
      APPEND BLANK
      REPLACE BRKAL WITH MNBRKAL
      REPLACE BRRAC WITH MSBRKAL
      REPLACE SIFRA WITH MSIFRA
      REPLACE DATDOK WITH MDATDOK
      REPLACE OTPDAT WITH MDATDOK
      REPLACE FVRSTA WITH '  1'
      REPLACE OPDV WITH '*'
      REPLACE NAPOMENAG WITH 'MODEL '+MMODEL+' REG.BR.'+MREGBR
   ENDIF
   SELECT FAK
   USE
   SELECT FAKG
   USE
   SELECT ASNAL
   SET RELATION TO
   SEEK MSBRKAL
   SET ORDER TO
   SET RELATION TO BRKAL INTO ASNALG ADDITIVE
   SET RELATION TO RSIF INTO ROB ADDITIVE
ENDIF
ASNAL.GRD0.SETFOCUS
POP KEY
ASNAL.REFRESH