PUSH KEY CLEAR
SELECT ASNEISP
SET ORDER TO 
GO BOTTOM
APPEND BLANK
GO BOTTOM
ASNEISP.GRD0.SetFocus
ASNEISP.GRD0.REFRESH
REPLACE SIFNEISP WITH STR(RECNO(),5,0)
DO FORM ASNEISPKART
ASNEISP.GRD0.SetFocus
ASNEISP.GRD0.REFRESH
ASNEISP.REFRESH  
POP KEY