PUSH KEY CLEAR
SELECT asnal
SET RELATION to
SELECT asneisp
DO FORM ASNEISP
SELECT asneisp
MSIFNEISP=sifneisp
IF asnal.grd0.readonly=.f.
   SELECT asnal
   replace sifneisp WITH msifneisp
ENDIF
SELECT ASNAL
SET RELATION TO BRKAL INTO ASNALG ADDITIVE
SET RELATION TO RSIF INTO ROB ADDITIVE
SET RELATION TO sifneisp INTO asneisp ADDITIVE      
ASNAL.GRD0.REFRESH
POP KEY