PUSH KEY CLEAR
SELECT ASVOZILA
SET ORDER TO 
GO BOTTOM
APPEND BLANK
GO BOTTOM
ASVOZILA.GRD0.SetFocus
ASVOZILA.GRD0.REFRESH
REPLACE SIFRAVOZ WITH STR(RECNO(),5,0)
DO FORM ASVOZILAKART
ASVOZILA.GRD0.SetFocus
ASVOZILA.GRD0.REFRESH
ASVOZILA.REFRESH  
POP KEY