PUSH KEY CLEAR
MDNEV=DNEV
SET ORDER TO 4
GO TOP
MPSTANJE=0
MDUG=0
MPOT=0
MPDATDOK=DATE()
DO WHILE.NOT.EOF()
   IF DNEV<MDNEV
      MPSTANJE=MPSTANJE+DEVDUG-DEVPOT
      MPDATDOK=DATDOK
   ELSE
      IF DNEV=MDNEV
         MDUG=MDUG+DEVDUG
         MPOT=MPOT+DEVPOT 
      ENDIF
   ENDIF
   SKIP
ENDDO
SEEK MDNEV       
PUBLIC PSTANJE,PDUG,PPOT

PSTANJE=MPSTANJE
PDUG=MDUG
PPOT=MPOT
PDATDOK=MPDATDOK   
mdnev=dnev

   *REPORT FORM BLDNEVDEV FOR DNEV=MDNEV PREVIEW
   mfile='BLDNEVDEV'
   uslov="DNEV=MDNEV"
   DO printer_bullzip WITH mdata02,mfile,uslov
   
   
SET ORDER TO
POP KEY
