PUSH KEY CLEAR
MDNEV=DNEV
SET ORDER TO 4
GO TOP
MPSTANJE=0
MDUG=0
MPOT=0
MPDUG=0
mppot=0
MPDATDOK=DATE()
DO WHILE.NOT.EOF()
   DO CASE
   CASE DNEV<MDNEV
      MPSTANJE=MPSTANJE+DUG-POT
      MPDATDOK=DATDOK
      MPDUG=MPDUG+DUG
      MPPOT=MPPOT+POT
   CASE DNEV=MDNEV
      MDUG=MDUG+DUG
      MPOT=MPOT+POT 
   ENDCASE
   SKIP
ENDDO
SEEK MDNEV       
PUBLIC PSTANJE,PDUG,PPOT,APDUG,APPOT

PSTANJE=MPSTANJE
PDUG=MDUG
PPOT=MPOT
PDATDOK=MPDATDOK   
APDUG=MPDUG
APPOT=MPPOT
mdnev=dnev

*REPORT FORM BLDNEV FOR DNEV=MDNEV PREVIEW

   mfile='BLDNEV'
   uslov="DNEV=MDNEV"
   DO printer_bullzip WITH mdata02,mfile,uslov


SET ORDER TO
POP KEY