PUSH KEY CLEAR
IF RECCOUNT()>0
   PUSH KEY CLEAR
   MDNEV=DNEV
   MNALU=NALU
   MNALI=NALI
   MOPIS=OPIS
   MBRNAL=BRNAL
   MDATDOK=DATDOK
   MKONTO=KONTO
   APPEND BLANK
   REPLACE DNEV WITH MDNEV
   REPLACE NALU WITH MNALU
   REPLACE NALI WITH MNALI
   REPLACE KONTO WITH MKONTO
   REPLACE OPIS WITH MOPIS
   REPLACE BRNAL WITH MBRNAL
   REPLACE DATDOK WITH MDATDOK
   REPLACE OPER WITH OPERATER
   REPLACE DATUM WITH DATE()
   REPLACE VREME WITH TIME()   
   BLP.GRD0.SETFOCUS
   POP KEY
   BLP.REFRESH
ELSE
   PUSH KEY CLEAR
*   APPEND BLANK
   DO FORM NALBROJ
   SELECT BLP
   SET RELATION TO
   SET RELATION TO BRNAL INTO NALBROJ  ADDITIVE
   SET RELATION TO KONTO INTO KONTo ADDITIVE
   SET RELATION TO MP INTO MESTA ADDITIVE
   SET RELATION TO MTR INTO MTR ADDITIVE
   SET RELATION TO SIFRA INTO AN0 ADDITIVE
   POP KEY
ENDIF
BLP.GRD0.COLUMN1.SETFOCUS
POP KEY
BLP.REFRESH  
