PUSH KEY CLEAR
MDNEV=DNEV
SET ORDER TO 1

*REPORT FORM BLKONTO PREVIEW FOR DNEV=MDNEV

   mfile='BLKONTO'
   uslov="DNEV=MDNEV"
   DO printer_bullzip WITH mdata02,mfile,uslov


SET ORDER TO
GO BOTTOM
POP KEY