PUSH KEY CLEAR
MDATDOK=DATDOK
MBRNAL=BRNAL
BLP.CMDGRADJANI.SETFOCUS
IF TBLKONTO='0000000001'
   IF DUG=0
      DO FORM BLPTSUPL WITH 1,MDATDOK,MBRNAL
   ENDIF   
ENDIF
IF TBLKONTO='0000000002'
   IF DUG=0
      DO FORM BLPPKUPL WITH 1,MDATDOK,MBRNAL
   ENDIF   
ENDIF


POP KEY