PARAMETERS m3pib
PUSH KEY CLEAR
MDUG=0
MPOT=0
MA3PIB=SUBSTR(M3PIB,1,10)
SELECT TSUPL
SEEK MA3PIB
SELECT TSUPL
SEEK MA3PIB
IF FOUND()
   DO WHILE.NOT.EOF()
      IF PIB<>MA3PIB
         EXIT
      ENDIF
      MDUG=MDUG+DUG   
      MPOT=MPOT+POT
      REPLACE SALDO WITH MDUG-MPOT
      SKIP
   ENDDO   
ENDIF   
SELECT BLP
BLPPKUPL.TXTZADUZ.VALUE=MDUG
BLPPKUPL.TXTUPLACENO.VALUE=MPOT
BLPPKUPL.TXTSALDO.VALUE=MDUG-MPOT
*BLPTSUPL.REFRESH
POP KEY
