PUSH KEY CLEAR
mpib=BLPPKUPL.txtpib.value
IF mpib=SPACE(13)
SELECT BLP
SELECT TS
   SET ORDER TO 1
   DO FORM BLPTSA
   SELECT TS
   MPIB=PIB
   MIME=IME_PREZ
   MADRESA=ULICA
   MOPIS='KOMUNALNE USLUGE '
   SELECT BLP
   REPLACE PIB WITH MPIB
   REPLACE IME WITH MIME
   REPLACE ADRESA WITH MADRESA
   REPLACE OPIS WITH MOPIS         
   BLPPKUPL.TXTPib.Value=mpib
   BLPPKUPL.TXTIME.Value=MIME
   BLPPKUPL.TXTADRESA.Value=MADRESA
   BLPPKUPL.TXTOPIS.Value=MOPIS
   BLPPKUPL.REFRESH
   BLPPKUPL.TXTPIB.SETFOCUS
endif   
BLPPKUPL.REFRESH
BLPPKUPL.TXTPIB.SETFOCUS
POP KEY