PUSH KEY CLEAR
MPIB=PIB
BLPPKA.CMDF7.SETFOCUS
SELECT TSUPL
SEEK MPIB
IF FOUND()
   MDUG=0
   MPOT=0
   DO WHILE.NOT.EOF()
      IF PIB<>MPIB
         EXIT
      ENDIF
      MDUG=MDUG+DUG   
      MPOT=MPOT+POT
      REPLACE SALDO WITH MDUG-MPOT
      SKIP
   ENDDO   
ENDIF   
SEEK MPIB
*REPORT FORM BLPTSUPL0 PREVIEW FOR PIB=MPIB

   mfile='BLPTSUPL0'
   uslov="PIB=MPIB"
   DO printer_bullzip WITH mdata02,mfile,uslov


SEEK MPIB
SELECT TS
BLPPKA.GRD0.SetFocus 
BLPPKA.refresh
POP KEY