PUSH KEY CLEAR
MPIB=SUBSTR(AAPIB,1,10)
*BLPTSA.CMDF7.SETFOCUS
SELECT TSUPL
SET ORDER TO 1
SEEK MPIB
IF FOUND()
   MDUG=0
   MPOT=0
   DO WHILE.NOT.EOF()
      IF PIB<>MPIB
         EXIT
      ENDIF
      MDUG=MDUG+DUG   
      MPOT=MPOT+POT
      REPLACE SALDO WITH MDUG-MPOT
      SKIP
   ENDDO   
ENDIF   
SEEK MPIB
*REPORT FORM BLPPKUPL0 PREVIEW FOR PIB=MPIB

   mfile='BLPPKUPL0'
   uslov="PIB=MPIB"
   DO printer_bullzip WITH mdata02,mfile,uslov


SEEK MPIB
SELECT TS
*BLPTSA.GRD0.SetFocus 
*BLPTSA.refresh
SELECT BLP
POP KEY