PARAMETERS ASIFRA
PUSH KEY CLEAR
SELECT BLP
MDNEV=DNEV
MSIFRA=SIFRA
SET ORDER TO 1
IF ASIFRA=0
   *REPORT FORM BLKONTO PREVIEW FOR DNEV=MDNEV
   mfile='BLKONTO'
   uslov="DNEV=MDNEV"
   DO printer_bullzip WITH mdata02,mfile,uslov
   
ELSE
   *REPORT FORM BLKONTO PREVIEW FOR SIFRA=MSIFRA
   mfile='BLKONTO'
   uslov="SIFRA=MSIFRA"
   DO printer_bullzip WITH mdata02,mfile,uslov

ENDIF   
SET ORDER TO
GO BOTTOM
POP KEY