PUSH KEY CLEAR
mpib=blptsupl.txtpib.value
IF mpib=SPACE(13)
SELECT BLP
SELECT TS
   SET ORDER TO 1
   DO FORM BLPTSA
   SELECT TS
   MPIB=PIB
   MIME=IME
   MPREZ=PREZ
   MADRESA=ULICA
   MOPIS='KOMUNALNE USLUGE '
   SELECT BLP
   REPLACE PIB WITH MPIB
   REPLACE IME WITH MIME+' '+MPREZ
   REPLACE ADRESA WITH MADRESA
   REPLACE OPIS WITH MOPIS         
   BLPTSUPL.TXTPib.Value=mpib
   BLPTSUPL.TXTIME.Value=MIME+' '+MPREZ
   BLPTSUPL.TXTADRESA.Value=MADRESA
   BLPTSUPL.TXTOPIS.Value=MOPIS
   BLPTSUPL.REFRESH
   BLPTSUPL.TXTPIB.SETFOCUS
endif   
BLPTSUPL.REFRESH
BLPTSUPL.TXTPIB.SETFOCUS
POP KEY