PUSH KEY CLEAR
BLPTSA.COMMAND20.SETFOCUS
SELECT TS
MGRUPA=ALLTRIM(GRUPA)
mpib=pib
MBRNAL=BRNAL
*SELECT TSobrac
*MBROBRAC=BROBRAC
*MBRNAL='O'+REPLICATE('0',2-LEN(ALLTRIM(STR(MBROBRAC,2,0))))+ALLTRIM(STR(MBROBRAC,2,0))
DO IDEL WITH (KKOCKAX)
IF MAKOJIV=1
   USE TSUPLD IN 0 
ELSE
   USE TSUPLDS IN 0 ALIAS TSUPLD
ENDIF
SELECT TSupld
SET ORDER TO 1
COPY STRUCTURE TO &KKOCKA
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
SELECT TSUPLD
SET ORDER TO 1
SEEK Mpib
IF FOUND()
   DO while.not.eof()
      IF Pib<>mpib
         EXIT
      endif   
      IF brnal=MBRNAL
         SCATTER NAME POLJA
         SELECT KOCKA
         APPEND BLANK
         GATHER NAME POLJA
      ENDIF
      SKIP      
   ENDDO
endif
PUBLIC AKOJE
AKOJE=MAKOJIV
USE TSRACTXT IN 0
USE TSRACTX2 IN 0
SELECT KOCKA
   IF MAKOJIV=1
      *REPORT FORM BLPTSRACSVE PREVIEW
   mfile='BLPTSRACSVE'
   uslov=""
   DO printer_bullzip WITH mdata02,mfile,uslov
      
   ELSE
      *REPORT FORM BLPTSRACSVES PREVIEW
   mfile='BLPTSRACSVES'
   uslov=""
   DO printer_bullzip WITH mdata02,mfile,uslov
      
   ENDIF
SELECT TSUPLD
USE
SELECT KOCKA
USE
SELECT TSractxt
USE
SELECT TSractx2
USE
SELECT TS
POP KEY