SELECT VP
MPIB=PIB
MGRUPA=GRUPA
MIME_PREZ=IME_PREZ
MPREZ=AN00.PREZ
MIME=AN00.IME
*SET STEP ON 
*-----------TABELA OBRACUNA------------
select VPOBRAC
MCENOVNIK=CENOVNIK
MBROBRAC=BROBRAC
*------TABELA CENA
select VPCENE
SET ORDER TO 1
SEEK MCENOVNIK
mpstanje=pstanje
mzstanje=zstanje
APOC='ST'+ALLTRIM(STR(MPSTANJE,2,0))
AKRAJ='ST'+ALLTRIM(STR(MZSTANJE,2,0))
MMES=MZSTANJE-MPSTANJE
mEdatum=datum
mEvaluta=valuta
mdatOD2=DTOS(datod)
mdatDO2=DTOS(datdo)
mdatOD=datod
mdatDO=datdo
mcvoda=cvoda
mcdvoda=cdvoda
mckanal=ckanal
mcdkanal=cdkanal
MCSMECE=CSMECE
MCCIS=CCIS
MCgre=CGRE
MRABPROC=RABPROC
MPROCvoda=PROCvoda
mprockan=PROCkan
MPROCsme=PROCsme
MPROCgre=PROCgre
mproccis=proccIS
mprocakont=procakont
MBRNAL='O'+ALLTRIM(STR(MBROBRAC,2,0))+MGRUPA
MPRDUG=0

IF mcenovnik2=' '
   mcvoda=cvoda
   mckanal=ckanal
   MCSMECE=CSMECE
   MCgre=CGRE
ENDIF

IF mcenovnik2='U'
   mcvoda=cvodau
   mckanal=ckanalu
   MCSMECE=CSMECEu
   MCgre=CGREu
ENDIF

IF mcenovnik2='P'
   mcvoda=cvodap
   mckanal=ckanalp
   MCSMECE=CSMECEp
   MCgre=CGREp
ENDIF

IF mcenovnik2='R'
   mcvoda=cvodap
   mckanal=ckanalp
   MCSMECE=CSMECE60
   MCgre=CGREp
ENDIF

IF mcenovnik2='T'
   mcvoda=cvodap
   mckanal=ckanalp
   MCSMECE=CSMECE60p
   MCgre=CGRE
ENDIF

IF mcenovnik2='K'
   mcvoda=cvodap
   mckanal=ckanalp
   MCSMECE=CSMECEk
   MCgre=CGREp
ENDIF


SELECT VP
IF POPUST<>' '
   IMARABAT=1
ELSE
   IMARABAT=0
ENDIF   
SELECT VP
mdinost1=dinost1
mdinost2=dinost2
MPOST1=POST1
MPOST2=POST2
MNAZOST1=NAZOST1
MNAZOST2=NAZOST2
mprocost1=procost1
mprocost2=procost2
*-----------OBRACUN KAMATE---------------
   select VPUPL
   set order to 
   SELECT VP
   USE VPKAM IN 0 EXCLU
   SELECT VPKAM
   ZAP
   DO VPKAM WITH MPIB,MDATOD,MDATDO
   SELECT VPKAM
*--------PRENOS KAMATE------------------
   SET ORDER TO 1
   MKAMATA=0
   SELECT VPKAM
   SET ORDER TO 1
   SEEK MPIB
   IF FOUND()
      MKAMATA=0
      DO WHILE.NOT.EOF()
         IF PIB<>MPIB
            EXIT
         ENDIF
         IF DATPOC>=MDATOD.AND.DATPOC<=MDATDO
            mKAMATA=mKAMATA+KAMATA
         ENDIF   
         SKIP
      ENDDO
   ENDIF
   *DO VPPRENKAM WITH MPIB,MDATOD,MDATDO
   SELECT VPKAM
   USE
   SELECT VP  
   REPLACE DATUM WITH MEDATUM
   REPLACE VALUTA WITH MEVALUTA
   REPLACE MES WITH MMES
   IF MKAMATA>0
      REPLACE KAMATA WITH MKAMATA
   ELSE
      REPLACE KAMATA WITH 0
   ENDIF
*--------OBRACUN PAUSAL------------------
   IF PAUSAL<>'D'
      REPLACE POT WITH &AKRAJ-&APOC
      MPOT=POT
   ELSE
      REPLACE POT WITH MMES*MESPAUSAL
      MPOT=POT
   ENDIF
   IF POT<0
      REPLACE POT WITH 0
      MPOT=POT
   ENDIF   
   REPLACE POC WITH &APOC
   REPLACE KRAJ WITH &AKRAJ
   *REPLACE UKPOT WITH KRAJ-POC
   REPLACE UKPOT WITH MPOT
   REPLACE VODA WITH 0
*   REPLACE CENOVNIK WITH MCENOVNIK
*------------OBRACUN ZA VODU------------------   
   IF POT>0
      IF PVODA='D'
         REPLACE VODA WITH POT*MCVODA*(100-POPPROC)/100
         REPLACE DOPV WITH POT*MCDVODA*(100-POPPROC)/100    
      ELSE
         REPLACE VODA WITH 0
         REPLACE DOPV WITH 0
      ENDIF
*------------OBRACUN ZA KANALIZACIJU
      IF PKANAL='D'
         REPLACE KAN WITH POT*MCKANAL*(100-POPKAN)/100
         REPLACE DOPK WITH POT*MCDKANAL*(100-POPKAN)/100    
      ELSE
         REPLACE KAN WITH 0
         REPLACE DOPK WITH 0   
      ENDIF
   ELSE
      REPLACE VODA WITH 0
      REPLACE DOPV WITH 0
      REPLACE KAN WITH 0
      REPLACE DOPK WITH 0   
   ENDIF
*------------OBRACUN ZA CISCENJE
IF PCIS='D'
   REPLACE CISCENJE WITH MCCIS*(100-POPCIS)/100
ELSE
   REPLACE CISCENJE WITH 0
ENDIF
*------------OBRACUN ZA SMECE
IF PSMECE='D'
   REPLACE SMECE WITH POV*MCSMECE*(100-POPSME)/100
ELSE
   REPLACE SMECE WITH 0
ENDIF
*------------OBRACUN ZA GREJANJE
IF PGRE='D'
   REPLACE GREJANJE WITH POV*MCGRE*(100-POPGRE)/100
ELSE
   REPLACE GREJANJE WITH 0
ENDIF

*----------PRETRAZIVANJE UPLATA zbog rabata--------  
   MRABATDUG=0
   SELECT VPUPL
   SET ORDER TO 1
   SEEK MPIB
   if found()
      do while.not.eof()
         if PIB<>mPIB
            exit
         ENDIF
         IF brnal<>mbrnal
*            SET STEP on
            IF datum<=mdatdo
               mrabatdug=mrabatdug+dug-pot
            endif
         endif   
        skip
     enddo      
   ELSE
      mrabatdug=0   
   endif
IF mrabatdug<=0
   imarabat=1
ELSE
   imarabat=0
endif
*-------UKUPNI PODACI------------------   
SELECT vp
   REPLACE MESECI WITH MMES      
   IF IMARABAT=1
      MRABOSNOV=VODA+DOPV+KAN+DOPK+SMECE+CISCENJE+GREJANJE+DINOST1+DINOST2
   ELSE
      MRABOSNOV=0
   ENDIF      
   *MMAKSPOT=MMES*15
   *IF POT<=MMAKSPOT
   IF MRABOSNOV>0
      MRABAT=ROUND(MRABOSNOV*MRABPROC/100,2)
   ELSE
      MRABAT=0
   ENDIF
   *ELSE
   *   MRABAT=0
   *ENDIF
   REPLACE RABAT WITH MRABAT
   *-----OBRACUN POREZA-------------------------------
   
   MUKUPNO=VODA+DOPV+KAN+DOPK+SMECE+CISCENJE+GREJANJE+DINOST1+DINOST2
   MUKUPNO2=VODA+DOPV+KAN+DOPK+SMECE+GREJANJE   
   REPLACE UKUPNO WITH MUKUPNO   
   
   IF POPSOC>0.AND.(MUKUPNO-mRABAT)>0
      MSOC=ROUND((MUKUPNO-RABAT)*POPSOC/100,2)
   ELSE
      MSOC=0
   ENDIF
   REPLACE SOC WITH MSOC
   
   *------porez     
   REPLACE PROCvoda WITH MPROCVODA
   REPLACE PROCKAN WITH MPROCKAN
   REPLACE PROCSME WITH MPROCSME
   REPLACE PROCGRE WITH MPROCGRE
   REPLACE PROCCIS WITH MPROCCIS
   MPOREZ20=0
   MPOREZ10=0
   MOSN20=0
   MOSN10=0
   MOSN0=0
   
   IF voda>0
      MPORVODA=ROUND(VODA*PROCVODA/100,2)
      DO CASE PROCVODA
      case PROCVODA=VAL(TOSTOPA)
         MPOREZ20=MPOREZ20+MPORVODA
         MOSN20=MOSN20+VODA
      case PROCVODA=VAL(TNSTOPA)
         MPOREZ10=MPOREZ10+MPORVODA
         MOSN10=MOSN10+VODA
      OTHERWISE
         mosn0=MOSN0+voda          
      ENDcase
   ELSE
      MPORVODA=0
   ENDIF
   IF KAN>0
      MPORKAN=ROUND(KAN*PROCKAN/100,2)
      DO CASE PROCKAN
      case PROCKAN=VAL(TOSTOPA)
         MPOREZ20=MPOREZ20+MPORKAN
         MOSN20=MOSN20+KAN
      case PROCKAN=VAL(TNSTOPA)
         MPOREZ10=MPOREZ10+MPORKAN
         MOSN10=MOSN10+KAN
      OTHERWISE
         mosn0=MOSN0+KAN         
      ENDcase
   ELSE
      MPORKAN=0
   ENDIF
   IF SMECE>0
      MPORSME=ROUND(SMECE*PROCSME/100,2)
      DO CASE PROCSME
      case PROCSME=VAL(TOSTOPA)
         MPOREZ20=MPOREZ20+MPORSME
         MOSN20=MOSN20+SMECE
      case PROCSME=VAL(TNSTOPA)
         MPOREZ10=MPOREZ10+MPORSME
         MOSN10=MOSN10+SMECE
      OTHERWISE
         mosn0=MOSN0+SMECE    
      ENDcase
   ELSE
      MPORSME=0
   ENDIF
   IF GREJANJE>0
      MPORGRE=ROUND(GREJANJE*PROCGRE/100,2)
      DO CASE PROCGRE
      case PROCGRE=VAL(TOSTOPA)
         MPOREZ20=MPOREZ20+MPORGRE
         MOSN20=MOSN20+GREJANJE
      case PROCGRE=VAL(TNSTOPA)
         MPOREZ10=MPOREZ10+MPORGRE
         MOSN10=MOSN10+GREJANJE
      OTHERWISE
         mosn0=MOSN0+GREJANJE
      ENDcase
   ELSE
      MPORGRE=0
   ENDIF
   IF CISCENJE<>0
      MPORCIS=ROUND(CISCENJE*PROCCIS/100,2)
      DO CASE PROCCIS
      case PROCCIS=VAL(TOSTOPA)
         MPOREZ20=MPOREZ20+MPORCIS
         MOSN20=MOSN20+CISCENJE
      case PROCCIS=VAL(TNSTOPA)
         MPOREZ10=MPOREZ10+MPORCIS
         MOSN10=MOSN10+CISCENJE
      OTHERWISE
         mosn0=MOSN0+CISCENJE
      ENDcase
      
   ELSE
      MPORCIS=0
   ENDIF
   
   IF DINOST1<>0
      MPOROST1=ROUND((DINOST1)*PROCOST1/100,2)
      DO CASE PROCOST1
      case PROCOST1=VAL(TOSTOPA)
         MPOREZ20=MPOREZ20+MPOROST1
         MOSN20=MOSN20+DINOST1
      case PROCOST1=VAL(TNSTOPA)
         MPOREZ10=MPOREZ10+MPOROST1
         MOSN10=MOSN10+DINOST1
      OTHERWISE
         mosn0=MOSN0+DINOST1
      ENDcase

   ELSE
      MPOROST1=0
   ENDIF
   IF DINOST2<>0
      MPOROST2=ROUND((DINOST2)*PROCOST2/100,2)
      DO CASE PROCOST2
      case PROCOST2=VAL(TOSTOPA)
         MPOREZ20=MPOREZ20+MPOROST2
         MOSN20=MOSN20+DINOST2
      case PROCOST2=VAL(TNSTOPA)
         MPOREZ10=MPOREZ10+MPOROST2
         MOSN10=MOSN10+DINOST2
      OTHERWISE
         mosn0=MOSN0+DINOST2
      ENDcase
   ELSE
      MPOROST2=0
   ENDIF
   REPLACE PORVODA WITH MPORVODA
   REPLACE PORKAN WITH MPORKAN
   REPLACE PORSME WITH MPORSME
   REPLACE PORGRE WITH MPORGRE
   REPLACE PORCIS WITH MPORCIS
   REPLACE POROST1 WITH MPOROST1
   REPLACE POROST2 WITH MPOROST2  
   
   REPLACE POREZ20 WITH MPOREZ20
   REPLACE POREZ10 WITH MPOREZ10   
   REPLACE OSNOV20 WITH MOSN20   
   REPLACE OSNOV10 WITH MOSN10   
   REPLACE OSNOV0 WITH MOSN0      
   replace porezuk WITH mporez20+mporez10
   replace osnovuk WITH osnov20+osnov10+osnov0

   REPLACE SVEGA WITH UKUPNO-SOC-RABAT+PORVODA+PORKAN+PORSME+PORGRE+PORCIS+POROST1+POROST2

   MOSNOV=MUKUPNO-MSOC-mrabat+MPORVODA+MPORKAN+MPORSME+MPORGRE+MPORCIS+MPOROST1+MPOROST2

   IF MOSNOV>0.AND.MMES>0   
      REPLACE AKONT WITH ROUND( (100+MPROCAKONT)*MOSNOV/MMES/100,0)
   ELSE
      REPLACE AKONT WITH 0
   ENDIF   
   REPLACE BRNAL WITH MBRNAL
   MPR2DUG=0
   MUPLAC=0
   mispr=0
   MSPORAZUM=0
   MOSTALO=0

   SELECT VPUPL
   SET ORDER TO 1
   SEEK MPIB
*----------PRETRAZIVANJE UPLATA ZA OSTALIM PODACIMA--------  
   if found()
      do while.not.eof()
         if PIB<>mPIB
            exit
         endif
         if DTOS(datum)<DTOS(mdatod)
            mpr2dug=mpr2dug+dug-pot
         endif    
         if DTOS(datum)>=DTOS(mdatod).and.DTOS(datum)<=DTOS(mdatdo)
            IF GRUPA='SPO'.OR.GRUPA='STA'.OR.GRUPA='STO'.OR.GRUPA='SPP'
               MSPORAZUM=MSPORAZUM+DUG
            ENDIF      
            IF GRUPA='ISP'.OR.GRUPA='KOD'
               MOSTALO=MOSTALO+DUG
            ENDIF      
         ENDIF
         if DTOS(datum)>=DTOS(mdatod).and.DTOS(datum)<=DTOS(mdatdo)
           mUPLAC=MUPLAC+POT
           mdATUM=datum 
        endif
        skip
     enddo      
  endif
*----------POPUNJAVANJE GLAVNE TABELE----------
   SELECT VP
   REPLACE DUG WITH MPR2DUG
   REPLACE UPLAC WITH MUPLAC
   REPLACE OSTALO WITH MOSTALO+msporazum
   *REPLACE SPORAZUM WITH MSPORAZUM
*   REPLACE SVEGA WITH UKUPNO+OSTALO+SPORAZUM-UPLAC+DUG+POREZ+KAMATA-MSOC
*   REPLACE ZADUZENJE WITH UKUPNO+POREZ-SOC 
*   REPLACE SOC WITH -MSOC
   SET CENTURY OFF
   MGODINA=SUBSTR(DTOC(medatum),7,2)
   mbrrac=ALLTRIM(pib)+ALLTRIM(STR(MBROBRAC,2,0))+mgodina
   REPLACE BRRAC WITH MBRRAC
   M1=VAL(mbrrac)
   M2=(M1*100/97)-INT(M1*100/97)
   M3=ROUND(97*M2,0)
   M4=98-M3
   IF M4<=9
      M4='0'+STR(M4,1,0)
   ELSE
      M4=STR(M4,2,0)
   ENDIF      
   REPLACE model WITH +M4+'-'+ALLTRIM(mbrrac)
   SET CENTURY on
   SELECT VPUPLD
   SET ORDER TO 1
   SET EXACT OFF
   GO TOP
   DO WHILE.T.
      LOCATE FOR pib=mpib.and.brnal=mbrnal
      IF FOUND()
         SET ORDER TO 
         REPLACE PIB WITH SPACE(13)
         REPLACE BRNAL WITH SPACE(6)
         REPLACE BRRAC WITH ''
         REPLACE GRUPA WITH ''
         REPLACE CENOVNIK WITH 0
         REPLACE PSTanje WITH 0
         REPLACE ZSTANJE WITH 0
         REPLACE MESEC WITH 0
         REPLACE DATUM WITH CTOD('')
         REPLACE VALUTA WITH CTOD('')
         REPLACE DATOD WITH CTOD('')
         REPLACE DATDO WITH CTOD('')
         REPLACE CVODA WITH 0
         REPLACE CDVODA WITH 0
         REPLACE CKANAL WITH 0
         REPLACE CSMECE WITH 0
         REPLACE CDKANAL WITH 0
         REPLACE CCIS WITH 0
         REPLACE CGRE WITH 0         
         REPLACE VODA WITH 0
         REPLACE DOPV WITH 0
         REPLACE KAN WITH 0
         REPLACE SMECE WITH 0     
         replace pov WITH 0    
         REPLACE CISCENJE WITH 0                  
         REPLACE GREJANJE WITH 0     
         REPLACE DOPK WITH 0
         REPLACE UKUPNO WITH 0
         REPLACE OSTALO WITH 0
         REPLACE SPORAZUM WITH 0
         REPLACE SOC WITH 0
         REPLACE KAMATA WITH 0
         REPLACE OSNOV WITH 0
         REPLACE POC WITH 0
         REPLACE KRAJ WITH 0
         REPLACE POT WITH 0
         REPLACE RABAT WITH 0
         REPLACE DUG WITH 0
         REPLACE SALDO WITH 0
         REPLACE SVEGA WITH 0
         REPLACE PROCVODA WITH 0
         REPLACE PROCKAN WITH 0
         REPLACE PROCSME WITH 0
         REPLACE PROCGRE WITH 0
         REPLACE PROCCIS WITH 0
         REPLACE PROCOST1 WITH 0
         REPLACE PROCOST2 WITH 0         
         REPLACE PORVODA WITH 0         
         REPLACE PORKAN WITH 0         
         REPLACE PORSME WITH 0         
         REPLACE PORGRE WITH 0         
         REPLACE PORCIS WITH 0
         REPLACE POROST1 WITH 0
         REPLACE POROST2 WITH 0
         LOOP 
      ELSE
         EXIT
      ENDIF
   ENDDO   
   SET ORDER TO 
   SELECT VP
   MGRUPA=GRUPA
   MDATUM=DATUM
   MVALUTA=VALUTA
   MPAUSAL=PAUSAL
   MMESPAUSAL=MESPAUSAL
   MVODA=VODA
   MDOPV=DOPV
   MKAN=KAN
   MSMECE=SMECE
   MCISCENJE=CISCENJE
   MGREJANJE=GREJANJE
   MDOPK=DOPK
   MUKUPNO=UKUPNO
   MOSTALO=OSTALO
   *msporazum=sPORAzum
   mdug=dug
   MSVEGA=SVEGA
   MUPLAC=UPLAC
   MSOC=SOC
   MKAMATA=KAMATA
   MBRRAC=BRRAC
   MMODEL=MODEL
   MRABAT=RABAT
   MPOC=POC
   MKRAJ=KRAJ
   MPOT=POT
   MPVODA=PVODA
   MPKANAL=PKANAL
   MSLEP=SLEP
   MPOPPROC=POPPROC
   MPOPKAN=POPKAN
   MPOPSOC=POPSOC
   MPOPSME=POPSME
   MPOPCIS=POPCIS
   MPOPGRE=POPGRE
   MBRSTAN=BRSTAN
   MUKSTAN=UKSTAN
   MDOMAC=DOMAC
   MKS=KS
   MKSSIFRA=KSSIFRA
   MVRSTA=VRSTA
   MSIFUL=SIFUL
   MULICA=ULICA
   MULBROJ=ULBROJ
   MBROJ=BROJ
   MIME_PREZ=IME_PREZ
   MAPREZ=AN00.PREZ
   MAIME=AN00.IME
   MAOTAC=AN00.OTAC
   MAPOSTA0=AN00.POSTA0
   MAMESTO0=AN00.MESTO0
   MASIFUL0=AN00.SIFUL0
   MAULICA0=AN00.ULICA0
   MAULBROJ0=AN00.ULBROJ0
   MASTAN0=AN00.STAN0
   MPOSTA=POSTA
   MULICA=ULICA
   MMESTO=MESTO
   MAPIB=AN00.PIB
   MAMATICNI0=AN00.MATICNI0
   MAMATICNI1=AN00.MATICNI1
   MRABAT=RABAT   
   mdatcit=datcit
   mpov=pov
   MPROCVODA=PROCVODA
   MPROCKAN=PROCKAN
   MPROCSME=PROCSME
   MPROCGRE=PROCGRE
   MPROCIS=PROCCIS
   MPROCOST1=PROCOST1   
   MPROCOST2=PROCOST2      
   MPORCIS=PORCIS
   MPOROST1=POROST1
   MPOROST2=POROST2
   MPOREZ20=POREZ20
   MPOREZ10=POREZ10   
   MOSNOV20=OSNOV20   
   MOSNOV10=OSNOV10   
   MOSNOV0=OSNOV0      
   mporezuk=porezuk
   mosnovuk=osnovuk
   SELECT VPUPLD
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE GRUPA WITH MGRUPA
   REPLACE CENOVNIK WITH MCENOVNIK
   REPLACE PSTanje WITH MPSTANJE
   REPLACE ZSTANJE WITH MZSTANJE
   REPLACE MESEC WITH MMES
   REPLACE DATUM WITH  MDATUM
   REPLACE VALUTA WITH MVALUTA
   REPLACE DATOD WITH MDATOD
   REPLACE DATDO WITH MDATDO
   REPLACE CVODA WITH MCVODA
   REPLACE CDVODA WITH MCDVODA
   REPLACE CKANAL WITH MCKANAL
   REPLACE CDKANAL WITH MCDKANAL
   REPLACE CSMECE WITH MCSMECE
   REPLACE CCIS WITH MCCIS   
   REPLACE CGRE WITH MCGRE
   REPLACE VODA WITH MVODA
   REPLACE DOPV WITH MDOPV
   REPLACE KAN WITH MKAN
   REPLACE DOPK WITH MDOPK
   REPLACE SMECE WITH MSMECE
   REPLACE CISCENJE WITH MCISCENJE
   REPLACE GREJANJE WITH MGREJANJE
   REPLACE UKUPNO WITH MUKUPNO
   REPLACE OSTALO WITH MOSTALO
   REPLACE DUG WITH MDUG
   REPLACE UPLAC WITH MUPLAC
   REPLACE SOC WITH MSOC
   REPLACE KAMATA WITH MKAMATA
   REPLACE SVEGA WITH MSVEGA
   REPLACE SALDO WITH SVEGA+DUG-UPLAC+KAMATA+ostalo
   REPLACE BRRAC WITH MBRRAC
   REPLACE MODEL WITH MMODEL
   REPLACE BRNAL WITH MBRNAL
   REPLACE OSNOV WITH MOSNOV
   REPLACE POC WITH MPOC
   REPLACE KRAJ WITH MKRAJ
   REPLACE POT WITH MPOT
   REPLACE UKPOT WITH MPOT
   REPLACE PVODA WITH MPVODA
   REPLACE PKANAL WITH MPKANAL
   REPLACE SLEP WITH  MSLEP
   REPLACE POPPROC WITH  MPOPPROC
   REPLACE POPKAN WITH  MPOPKAN
   REPLACE POPSME WITH  MPOPSME
   REPLACE POPCIS WITH  MPOPCIS
   REPLACE POPGRE WITH  MPOPGRE
   REPLACE POPSOC WITH  MPOPSOC   
   REPLACE BRSTAN WITH MBRSTAN
   REPLACE UKSTAN WITH MUKSTAN
   REPLACE DOMAC WITH MDOMAC
   REPLACE KS WITH MKS
   REPLACE KSSIFRA WITH MKSSIFRA
   REPLACE VRSTA WITH MVRSTA
   REPLACE SIFUL WITH MSIFUL
   REPLACE ULICA WITH MULICA
   REPLACE ULBROJ WITH MULBROJ
   REPLACE BROJ WITH MBROJ
   REPLACE IME_PREZ WITH MIME_PREZ
   REPLACE APREZ WITH MAPREZ
   REPLACE AIME WITH MAIME
   REPLACE AOTAC WITH MAOTAC
   REPLACE APOSTA0 WITH MAPOSTA0
   REPLACE AMESTO0 WITH MAMESTO0
   REPLACE ASIFUL0 WITH MASIFUL0
   REPLACE AULICA0 WITH MAULICA0
   REPLACE AULBROJ0 WITH MAULBROJ0
   REPLACE ASTAN0 WITH MASTAN0
   REPLACE APIB WITH MAPIB
   REPLACE AMATICNI0 WITH MAMATICNI0
   REPLACE AMATICNI1 WITH MAMATICNI1
   REPLACE RABAT WITH MRABAT
   replace datcit WITH mdatcit
   REPLACE POSTA WITH MPOSTA
   REPLACE MESTO WITH MMESTO
   REPLACE ULICA WITH MULICA
   replace pov WITH mpov
   REPLACE DINOST1 WITH MDINOST1
   REPLACE DINOST2 WITH MDINOST2
   REPLACE NAZOST1 WITH MNAZOST1
   REPLACE NAZOST2 WITH MNAZOST2
   REPLACE PROCVODA WITH MPROCVODA
   REPLACE PROCKAN WITH MPROCKAN
   REPLACE PROCSME WITH MPROCSME
   REPLACE PROCGRE WITH MPROCGRE
   REPLACE PROCCIS WITH MPROCCIS
   REPLACE PROCOST1 WITH MPROCOST1
   REPLACE PROCOST2 WITH MPROCOST2
   replace porvoda WITH mporvoda
   replace porkan WITH mporkan
   replace porsme WITH mporsme
   replace porgre WITH mporgre
   REPLACE PORCIS WITH MPORCIS
   REPLACE POROST1 WITH MPOROST1
   REPLACE POROST2 WITH MPOROST2
   replace porez20 WITH mporez20
   replace porez10 WITH mporez10
   replace osnov20 WITH mosnov20
   replace osnov10 WITH mosnov10
   replace osnov0 WITH mosnov0
   replace porezuk WITH mporezuk
   replace osnovuk WITH mosnovuk 

*   REPLACE SVEGA WITH MSVEGA
   MDDUG=VODA+DOPV+KAN+DOPK+smece+ciscenje+grejanje+PORVODA+PORKAN+PORSME+PORGRE+PORCIS+POROST1+POROST2-SOC-RABAT+KAMATA+DINOST1+DINOST2
   MKAMATA=KAMATA
   SELECT VP


