PROCEDURE BOATAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       BOA.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE BOUPLTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       BOUPL.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE BOUPLDTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       BOUPLD.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE BOUPLDFTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       BOUPLDF.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC


PROCEDURE BOPODTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       BOPOD.RELEASE
ENDPROC

PROCEDURE BOFirmeTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       BOFIRME.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE BOFIRMEPODTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       BOFIRMEPOD.RELEASE
ENDPROC


PROCEDURE BO0TAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   BO0.RELEASE
ENDPROC


PROCEDURE BOSUD0TAST
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   BOSUD0.RELEASE
ENDPROC

PROCEDURE BOSUDTAST
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   BOSUD.RELEASE
ENDPROC

PROCEDURE BOSUD0DODRACTAST
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   BOSUD0DODRAC.RELEASE
ENDPROC

PROCEDURE BOANALIZVOTAST
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   BOANALIZVO.RELEASE
ENDPROC


PROCEDURE VT0TAST
   ON KEY LABEL F1    DO HELPN WITH 'VT0'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VT0.RELEASE
   ON KEY LABEL F2        ! /N CALC.EXE
ENDPROC


PROCEDURE BOKAKOEFTAST
   ON KEY LABEL F1    DO HELPN WITH 'VPKAKOEF'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       BOKAKOEF.RELEASE
   ON KEY LABEL F2        ! /N CALC.EXE
ENDPROC

PROCEDURE VKKAKOEFTAST
   ON KEY LABEL F1    DO HELPN WITH 'VKKAKOEF'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VKKAKOEF.RELEASE
   ON KEY LABEL F2        ! /N CALC.EXE
ENDPROC

PROCEDURE BOFAN0TAST

ON KEY LABEL F1    DO HELPN WITH 'FAN0'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       FAN0.RELEASE
ON KEY LABEL +         DO FAN0DOD
on key label INS       DO FAN0DOD
ON KEY LABEL F3        DO FAN0DEONAZ
ON KEY LABEL ALT+F3        DO FAN0TEKRAC
ON KEY LABEL F4        DO FAN0TRAZI
ON KEY LABEL F5        DO FAN0GR5TRAZI
ON KEY LABEL F6        DO FAN0TRAZIF6
ON KEY LABEL F7        DO FAN0KARTF7
ON KEY LABEL F8        DO FAN0ZIROTRAZI
ON KEY LABEL CTRL+F12  DO OTVFAN0
ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC

ENDPROC


PROCEDURE HELPNTAST
   ON KEY LABEL ESC       HELPN.RELEASE
   ON KEY LABEL F1    ON KEY
   ON KEY LABEL CTRL+F12  HELPN.GRD0.READONLY=.F.
ENDPROC

PROCEDURE NCALCTAST
ON KEY LABEL F1    DO HELPN WITH 'NCALC'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL INS       DO NCALCDOD
ON KEY LABEL F7        DO NCALCF7
ON KEY LABEL F8        DO NCALCF8
ON KEY LABEL ESC       NCALC.RELEASE
ENDPROC

PROCEDURE PORUKADANETAST
   ON KEY LABEL F1    DO HELPN WITH 'PORUKADANE'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PORUKADANE.RELEASE
ENDPROC

PROCEDURE AN0K2TAST
ON KEY LABEL F1    DO HELPN WITH 'AN0K2'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       AN0K2.RELEASE
ENDPROC

PROCEDURE fan0dEONAZTAST
   ON KEY LABEL F1    DO HELPN WITH 'FAN0DEONAZ'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       fan0DEONAZ.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE PORUKATAST
   ON KEY LABEL F1    DO HELPN WITH 'PORUKA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PORUKA.RELEASE
ENDPROC


PROCEDURE BOfan0TEKRACTAST
   ON KEY LABEL F1    DO HELPN WITH 'FAN0TEKRAC'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       fan0TEKRAC.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC


PROCEDURE BOIZVESTAJITAST
   ON KEY LABEL F1    DO HELPN WITH 'VPIZVESTAJI'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       BOIZVESTAJI.RELEASE
ENDPROC


PROCEDURE BOSERVISTAST
   ON KEY LABEL F1    DO HELPN WITH 'VPSERVIS'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       BOSERVIS.RELEASE
ENDPROC

PROCEDURE BODATCITTAST
   ON KEY LABEL F1    DO HELPN WITH 'VPDATCIT'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       BODATCIT.RELEASE
ENDPROC

PROCEDURE BOEKSPRIJEMPOTTAST
   ON KEY LABEL F1    DO HELPN WITH 'VPEKPRIJEMPOT'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       BOEKSPRIJEMPOT.RELEASE
ENDPROC

PROCEDURE BOSTANJEAKONTTAST
   ON KEY LABEL F1    DO HELPN WITH 'VPSTANJEAKONT'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       BOSTANJEAKONT.RELEASE
ENDPROC

PROCEDURE BOSTANJEAKONTFTAST
   ON KEY LABEL F1    DO HELPN WITH 'VPSTANJEAKONTF'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       BOSTANJEAKONTF.RELEASE
ENDPROC

PROCEDURE BOSPORAZTAST
   ON KEY LABEL F1    DO HELPN WITH 'VPSPORAZ'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       BOSPORAZ.RELEASE
ENDPROC

PROCEDURE BOSPORAZpodTAST
   ON KEY LABEL F1    DO HELPN WITH 'VPSPORAZPOD'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       BOSPORAZPOD.RELEASE
ENDPROC

PROCEDURE BOSPORAZKARTTAST
   ON KEY LABEL F1    DO HELPN WITH 'VPSPORAZKART'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       BOSPORAZKART.RELEASE
ENDPROC


PROCEDURE BOAPOTROSNJATAST
   ON KEY LABEL F1    DO HELPN WITH 'VPAPOTROSNJA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       BOAPOTROSNJA.RELEASE
ENDPROC

PROCEDURE BO0TAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       BO0.RELEASE
ENDPROC

PROCEDURE BOuplttAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       BOuplt.RELEASE
ENDPROC

PROCEDURE BOSERVISFIRMETAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       BOSERVISFIRME.RELEASE
ENDPROC

PROCEDURE BOSERVISTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       BOSERVIS.RELEASE
ENDPROC
