CLOSE ALL TABLES
USE firma IN 0 
SELECT firma
mfpumpe=fpumpe
IF Mfpumpe<>'1'
*----------TECIC LEVAC 
   SET DEFAULT TO &MDATA01BP
   DO BPBAZE
   DO FORM BP00
ELSE
*---------PETROL SOFT------
   SET DEFAULT TO &MDATA01BP
   DO BPBAZEPS
   DO FORM BP00PS
endif

CLOSE ALL TABLES
SET DEFAULT TO &MDATA02

