PUSH KEY CLEAR
SELECT BPDIN
SET ORDER TO 
IF RECCOUNT()>0
   GO BOTTOM
   MREDNI=REDNI
ELSE
   MREDNI=0
ENDIF
APPEND BLANK
GO BOTTOM
REPLACE REDNI WITH MREDNI+1
BPDIN.GRD0.COLUMN1.SetFocus
*BPDIN.REFRESH
POP KEY