PUSH KEY CLEAR
SELECT BPI
BP.COMMAND5.SETFOCUS
IF RECCOUNT()>0
   MDATDOK=DATDOK
   MREDNI=REDNI
ELSE
   MDATDOK=CTOD('')
   MREDNI=0
ENDIF
APPEND BLANK
REPLACE DATDOK WITH MDATDOK
REPLACE REDNI WITH MREDNI
BP.GRD0.COLUMN1.SetFocus 
POP KEY
