PROCEDURE BP00TAST
   ON KEY LABEL F1    DO HELPN WITH 'BP00'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       BP00.RELEASE
ENDPROC

PROCEDURE BPPRODTAST
   ON KEY LABEL F1    DO HELPN WITH 'BPPROD'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       BPPROD.RELEASE
ENDPROC

PROCEDURE BPPROMETTAST
   ON KEY LABEL F1    DO HELPN WITH 'BPPROMET'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       BPPROMET.RELEASE
ENDPROC

PROCEDURE BPKALTAST
   ON KEY LABEL F1    DO HELPN WITH 'BPKAL'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       BPKAL.RELEASE
ENDPROC

PROCEDURE BPKALUZMITAST
   ON KEY LABEL F1    DO HELPN WITH 'BPKALUZMI'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       BPKALUZMI.RELEASE
ENDPROC

PROCEDURE BPNIVTAST
   ON KEY LABEL F1    DO HELPN WITH 'BPNIV'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       BPNIV.RELEASE
ENDPROC

PROCEDURE BPNIVUZMITAST
   ON KEY LABEL F1    DO HELPN WITH 'BPNIVUZMI'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       BPNIVUZMI.RELEASE
ENDPROC


PROCEDURE BPFAKTAST
   ON KEY LABEL F1    DO HELPN WITH 'BPFAK'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       BPFAK.RELEASE
ENDPROC


PROCEDURE BPFAKUZMITAST
   ON KEY LABEL F1    DO HELPN WITH 'BPFAKUZMI'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       BPFAKUZMI.RELEASE
ENDPROC

PROCEDURE Bp00mTAST
   ON KEY LABEL F1    DO HELPN WITH 'BP00m'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       BP00M.RELEASE
ENDPROC

PROCEDURE BPPRODMTAST
   ON KEY LABEL F1    DO HELPN WITH 'BPPRODM'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       BPPRODM.RELEASE
ENDPROC


PROCEDURE BPFAKMTAST
   ON KEY LABEL F1    DO HELPN WITH 'BPFAKM'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       BPFAKM.RELEASE
ENDPROC

PROCEDURE BPFAKUZMIMTAST
   ON KEY LABEL F1    DO HELPN WITH 'BPFAKUZMIM'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       BPFAKUZMIM.RELEASE
ENDPROC

