PUSH KEY CLEAR
IF RECCOUNT()>0
   MBRSPEC=BRSPEC
   MDATDOK=DATDOK
   MSIFRA=SIFRA
   MPARTIJA=PARTIJA
ENDIF
APPEND BLANK
GOTO RECCOUNT()
CEKOVI.GRD0.REFRESH
IF RECCOUNT()>1
  REPLACE BRSPEC WITH MBRSPEC
  REPLACE DATDOK WITH MDATDOK
  REPLACE SIFRA WITH MSIFRA
  REPLACE PARTIJA WITH MPARTIJA
ELSE
  REPLACE BRSPEC WITH 1
  REPLACE DATDOK WITH DATE()
ENDIF     
CEKOVI.GRD0.SETFOCUS
POP KEY
CEKOVI.REFRESH




