   PARAMETERS AGDE
   PUSH KEY CLEAR

   MBRSPEC=BRSPEC
   IF AGDE=1
      *REPORT FORM CEKSPEC0  PREVIEW FOR BRSPEC=MBRSPEC
   mfile='CEKSPEC0'
   uslov="BRSPEC=MBRSPEC"
   DO printer_bullzip WITH mdata02,mfile,uslov
      
      
   ELSE
      REPORT FORM CEKSPEC0  TO PRINTER PROMPT FOR BRSPEC=MBRSPEC

   ENDIF
   POP KEY