PUSH KEY CLEAR

DO IBAZE WITH 'CLHCRNAL'
DO IIND WITH 'CLHCRNAL','DTOC(DATDOK)','RNAL','RSIF','RNAL+grupa'

DO IBAZE WITH 'CLHCIZV'
DO IIND WITH 'CLHCIZV','BRKAL','rnal','DTOC(DATDOK)','SMENA','DTOC(DATDOK)+SMENA'

DO IBAZE WITH 'CLHCPAK'
DO IIND WITH 'CLHCPAK','SIFPAK','NAZPAK'

DO IBAZE WITH 'CLHCIDK'
DO IIND WITH 'CLHCIDK','BRKAL','RNAL'

CLOSE ALL TABLES
POP KEY