PUSH KEY CLEAR
SELECT DELLOKAC
SET ORDER TO 
GO BOTTOM
APPEND BLANK
GO BOTTOM
DELLOKAC.GRD0.SetFocus
DELLOKAC.GRD0.REFRESH
REPLACE SIFLOKAC WITH STR(RECNO(),3,0)
DO FORM DELLOKACKART
DELLOKAC.GRD0.SetFocus
DELLOKAC.GRD0.REFRESH
DELLOKAC.REFRESH  
POP KEY