PUSH KEY CLEAR
SELECT DELORGAN
SET ORDER TO 
GO BOTTOM
APPEND BLANK
GO BOTTOM
DELORGAN.GRD0.SetFocus
DELORGAN.GRD0.REFRESH
REPLACE SIFORGAN WITH STR(RECNO(),3,0)
DO FORM DELORGANKART
DELORGAN.GRD0.SetFocus
DELORGAN.GRD0.REFRESH
DELORGAN.REFRESH  
POP KEY