PUSH KEY CLEAR
SELECT DELOV
SET ORDER TO 
GO BOTTOM
IF RECCOUNT()>0
   replace arhiva WITH '*'
   MPUTANJA=PUTANJA
ELSE
   MPUTANJA='C:\DELOVOD'
ENDIF
APPEND BLANK
GO BOTTOM
REPLACE BROJ WITH STR(RECNO(),5,0)
REPLACE PUTANJA WITH MPUTANJA
REPLACE IMEFAJLA WITH ALLTRIM(BROJ)+'.TXT'
replace oper WITH OPERATER
replace datPRI WITH DATE()
replace daTDOK  WITH DATE()
REPLACE DATUM WITH DATE()
replace VALUTA WITH DATE()
replace vreme WITH TIME()
GO BOTTOM
DELOV.GRD0.SETFOCUS
   
   DO FORM DELOVKART
   
DELOV.GRD0.SETFOCUS
POP KEY
