PUSH KEY CLEAR
SELECT DELPRIM
SET ORDER TO 
GO BOTTOM
APPEND BLANK
GO BOTTOM
DELPRIM.GRD0.SetFocus
DELPRIM.GRD0.REFRESH
REPLACE SIFPRIM WITH STR(RECNO(),4,0)
DO FORM DELPRIMKART
DELPRIM.GRD0.SetFocus
DELPRIM.GRD0.REFRESH
DELPRIM.REFRESH  
POP KEY