PUSH KEY CLEAR
SELECT DELSTAT
SET ORDER TO 
GO BOTTOM
IF RECCOUNT()<10
   APPEND BLANK
   GO BOTTOM
   DELSTAT.GRD0.SetFocus
   DELSTAT.GRD0.REFRESH
   REPLACE SIFSTATUS WITH STR(RECNO(),1,0)
   DO FORM DELSTATKART
ENDIF
DELSTAT.GRD0.SetFocus
DELSTAT.GRD0.REFRESH
DELSTAT.REFRESH  
POP KEY