PUSH KEY CLEAR
SELECT DELVRSTA
SET ORDER TO 
GO BOTTOM
APPEND BLANK
GO BOTTOM
DELVRSTA.GRD0.SetFocus
DELVRSTA.GRD0.REFRESH
REPLACE VRSTA WITH STR(RECNO(),3,0)
DO FORM DELVRSTAKART
DELVRSTA.GRD0.SetFocus
DELVRSTA.GRD0.REFRESH
DELVRSTA.REFRESH  
POP KEY