PUSH KEY CLEAR
IF RECCOUNT()>0
   MBRRAC=BRRAC
   MSIFRA=SIFRA
   MDATDOK=DATDOK
   
ELSE
   MBRRAC='NEMA'
   MSIFRA=''
   MDATDOK=DATE()
ENDIF      
APPEND BLANK
REPLACE BRRAC WITH MBRRAC
REPLACE SIFRA WITH MSIFRA
REPLACE DATDOK WITH MDATDOK
DKREDITI.GRD0.SETFOCUS
POP KEY
DKREDITI.REFRESH