PARAMETERS VVRNAL,M0OBJ,M0RED
PUSH KEY CLEAR
USE &KNALVRSTA IN 0 ALIAS NALVRSTA
SELECT NALVRSTA

IF VVRNAL='TV'
   APPEND BLANK
   REPLACE VRNAL WITH STR(RECNO(),3,0)
   REPLACE NAZIV WITH 'KALKULACIJE VP '+M0RED
   REPLACE DOK WITH M0OBJ+M0RED
   REPLACE MP WITH 'PN'
   REPLACE OBL WITH 'K'
   REPLACE NALDOK WITH '*'
   REPLACE ZNAKOVI WITH 2
   REPLACE POCSIF WITH ALLTRIM(M0OBJ)+ALLTRIM(M0RED) 
   REPLACE NAUTO WITH '*'
   
   APPEND BLANK
   REPLACE VRNAL WITH STR(RECNO(),3,0)
   REPLACE NAZIV WITH 'RACUNI VP '+M0RED
   REPLACE DOK WITH M0OBJ+M0RED
   REPLACE MP WITH 'PN'
   REPLACE OBL WITH 'R'
   REPLACE NALDOK WITH '*'
   REPLACE ZNAKOVI WITH 2
   REPLACE POCSIF WITH 'F'+ALLTRIM(M0RED) 
   REPLACE NAUTO WITH '*'
   
   APPEND BLANK
   REPLACE VRNAL WITH STR(RECNO(),3,0)
   REPLACE NAZIV WITH 'NIVELACIJE VP '+M0RED
   REPLACE DOK WITH M0OBJ+M0RED
   REPLACE MP WITH 'PN'
   REPLACE OBL WITH 'N'
   REPLACE NALDOK WITH '*'
   REPLACE ZNAKOVI WITH 2
   REPLACE POCSIF WITH 'N'+ALLTRIM(M0RED) 
   REPLACE NAUTO WITH '*'
ELSE
   APPEND BLANK
   REPLACE VRNAL WITH STR(RECNO(),3,0)
   REPLACE NAZIV WITH 'KALKULACIJE MP '+M0RED
   REPLACE DOK WITH M0OBJ+M0RED
   REPLACE MP WITH 'PN'
   REPLACE OBL WITH 'K'
   REPLACE NALDOK WITH '*'
   REPLACE ZNAKOVI WITH 2
   REPLACE POCSIF WITH ALLTRIM(M0OBJ)+ALLTRIM(M0RED) 
   REPLACE NAUTO WITH '*'

   APPEND BLANK
   REPLACE VRNAL WITH STR(RECNO(),3,0)
   REPLACE NAZIV WITH 'RACUNI MP '+M0RED
   REPLACE DOK WITH M0OBJ+M0RED
   REPLACE MP WITH 'PN'
   REPLACE OBL WITH 'R'
   REPLACE NALDOK WITH '*'
   REPLACE ZNAKOVI WITH 2
   REPLACE POCSIF WITH 'R'+ALLTRIM(M0RED) 
   REPLACE NAUTO WITH '*'
   
   
   APPEND BLANK
   REPLACE VRNAL WITH STR(RECNO(),3,0)
   REPLACE NAZIV WITH 'NIVELACIJE MP '+M0RED
   REPLACE DOK WITH M0OBJ+M0RED
   REPLACE MP WITH 'PN'
   REPLACE OBL WITH 'N'
   REPLACE NALDOK WITH '*'
   REPLACE ZNAKOVI WITH 2
   REPLACE POCSIF WITH 'L'+ALLTRIM(M0RED) 
   REPLACE NAUTO WITH '*'
ENDIF   
SELECT NALVRSTA
USE
POP KEY