  
   IF LEN(ALLTRIM(K_ULAZ))>0
       REPLACE K_ULAZ WITH ALLTRIM(K_ULAZ)+'00'
   ENDIF   
   IF LEN(ALLTRIM(K_ULAZ2))>0
       REPLACE K_ULAZ2 WITH ALLTRIM(K_ULAZ2)+'00'
   ENDIF   
   IF LEN(ALLTRIM(K_ULAZ2))>0
       REPLACE K_ULAZ2 WITH ALLTRIM(K_ULAZ2)+'00'
   ENDIF   
   IF LEN(ALLTRIM(K_ZAV))>0
       REPLACE K_ZAV WITH ALLTRIM(K_ZAV)+'00'
   ENDIF   
   IF LEN(ALLTRIM(K_POR))>0
       REPLACE K_POR WITH ALLTRIM(K_POR)+'00'   
    ENDIF   
   IF LEN(ALLTRIM(K_MAR))>0
       REPLACE K_MAR WITH ALLTRIM(K_MAR)+'00'
   ENDIF   
   IF LEN(ALLTRIM(K_MAR2))>0
       REPLACE K_MAR2 WITH ALLTRIM(K_MAR2)+'00'
   ENDIF   
   IF LEN(ALLTRIM(K_MAR3))>0
       REPLACE K_MAR3 WITH ALLTRIM(K_MAR3)+'00'
   ENDIF   
   IF LEN(ALLTRIM(K_PLAC))>0
       REPLACE K_PLAC WITH ALLTRIM(K_PLAC)+'00'
   ENDIF   
   IF LEN(ALLTRIM(K_PLAC8))>0
       REPLACE K_PLAC8 WITH ALLTRIM(K_PLAC8)+'00'
   ENDIF   
   IF LEN(ALLTRIM(K_PLAC5))>0
       REPLACE K_PLAC5 WITH ALLTRIM(K_PLAC5)+'00'
   ENDIF   
   IF LEN(ALLTRIM(K_MAG))>0
       REPLACE K_MAG WITH ALLTRIM(K_MAG)+'00'
   ENDIF   
   IF LEN(ALLTRIM(K_MAG2))>0
       REPLACE K_MAG2 WITH ALLTRIM(K_MAG2)+'00'
   ENDIF   
   IF LEN(ALLTRIM(K_MAG3))>0
       REPLACE K_MAG3 WITH ALLTRIM(K_MAG3)+'00'
   ENDIF   
   IF LEN(ALLTRIM(K_FAK))>0
       REPLACE K_FAK WITH ALLTRIM(K_FAK)+'00'
   ENDIF   
   IF LEN(ALLTRIM(K_PRIH))>0
       REPLACE K_PRIH WITH ALLTRIM(K_PRIH)+'00'
   ENDIF   
   IF LEN(ALLTRIM(K_PRIH2))>0
       REPLACE K_PRIH2 WITH ALLTRIM(K_PRIH2)+'00'
   ENDIF   
   IF LEN(ALLTRIM(K_PRIH3))>0
       REPLACE K_PRIH3 WITH ALLTRIM(K_PRIH3)+'00'
   ENDIF   
   IF LEN(ALLTRIM(K_RABAT))>0
       REPLACE K_RABAT WITH ALLTRIM(K_RABAT)+'00'
   ENDIF   
   IF LEN(ALLTRIM(K_RABAT2))>0
       REPLACE K_RABAT2 WITH ALLTRIM(K_RABAT2)+'00'
   ENDIF   
   IF LEN(ALLTRIM(K_RABAT3))>0
       REPLACE K_RABAT3 WITH ALLTRIM(K_RABAT3)+'00'
   ENDIF   
   IF LEN(ALLTRIM(K_RASH))>0
       REPLACE K_RASH WITH ALLTRIM(K_RASH)+'00'
   ENDIF   
   IF LEN(ALLTRIM(K_RASH2))>0
       REPLACE K_RASH2 WITH ALLTRIM(K_RASH2)+'00'
   ENDIF   
   IF LEN(ALLTRIM(K_RASH3))>0
       REPLACE K_RASH3 WITH ALLTRIM(K_RASH3)+'00'
   ENDIF   

   IF LEN(ALLTRIM(K_OBPOR))>0
       REPLACE K_OBPOR WITH ALLTRIM(K_OBPOR)+'00'
   ENDIF   
   IF LEN(ALLTRIM(K_OBPOR8))>0
       REPLACE K_OBPOR8 WITH ALLTRIM(K_OBPOR8)+'00'
   ENDIF   
   IF LEN(ALLTRIM(K_RMAR))>0
       REPLACE K_RMAR WITH ALLTRIM(K_RMAR)+'00'
   ENDIF   
   IF LEN(ALLTRIM(K_RMAR2))>0
       REPLACE K_RMAR2 WITH ALLTRIM(K_RMAR2)+'00'
   ENDIF   
   IF LEN(ALLTRIM(K_RMAR3))>0
       REPLACE K_RMAR3 WITH ALLTRIM(K_RMAR3)+'00'
   ENDIF   
   IF LEN(ALLTRIM(K_RPOR))>0
       REPLACE K_RPOR WITH ALLTRIM(K_RPOR)+'00'
   ENDIF   
   IF LEN(ALLTRIM(K_USLUGE))>0
       REPLACE K_USLUGE WITH ALLTRIM(K_USLUGE)+'00'
   ENDIF   
   IF LEN(ALLTRIM(K_RAVNAJ))>0
       REPLACE K_RAVNAJ WITH ALLTRIM(K_RAVNAJ)+'00'
   ENDIF   

   IF LEN(ALLTRIM(K9_PRDUG))>0
       REPLACE K9_PRDUG WITH ALLTRIM(K9_PRDUG)+'00'
   ENDIF   
   IF LEN(ALLTRIM(K9_PRPOT))>0
       REPLACE K9_PRPOT WITH ALLTRIM(K9_PRPOT)+'00'
   ENDIF   

   IF LEN(ALLTRIM(K9_TRDUG))>0
       REPLACE K9_TRDUG WITH ALLTRIM(K9_TRDUG)+'00'
   ENDIF   
   IF LEN(ALLTRIM(K9_TRPOT))>0
       REPLACE K9_TRPOT WITH ALLTRIM(K9_TRPOT)+'00'
   ENDIF   

   IF LEN(ALLTRIM(K9_GPDUG))>0
       REPLACE K9_GPDUG WITH ALLTRIM(K9_GPDUG)+'00'
   ENDIF   
   IF LEN(ALLTRIM(K9_GPPOT))>0
       REPLACE K9_GPPOT WITH ALLTRIM(K9_GPPOT)+'00'
   ENDIF   

   IF LEN(ALLTRIM(K9_GTDUG))>0
       REPLACE K9_GTDUG WITH ALLTRIM(K9_GTDUG)+'00'
   ENDIF   
   IF LEN(ALLTRIM(K9_GTPOT))>0
       REPLACE K9_GTPOT WITH ALLTRIM(K9_GTPOT)+'00'
   ENDIF   
