   PARAMETERS A1,A2,A3,A4,A5,A6,A7,A8,A9
   PUSH KEY CLEAR
   APPEND BLANK
      REPLACE VPDV WITH A1
      REPLACE KOND1 WITH A2
      REPLACE KOND2 WITH A3
      REPLACE KONP1 WITH A4
      REPLACE KONP2 WITH A5
      REPLACE OPIS WITH  A6
      REPLACE GRUPA WITH A7
      REPLACE PPDV WITH A8
      REPLACE OPDV WITH A9
      POP KEY