PUSH KEY CLEAR
   DO IDEL WITH (Kkockax)
   DO IDEL WITH (Kkockax2)

COPY TO &kkocka 
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
SELECT KOCKA
GO TOP
INDEX on grupa TAG grupa
SET ORDER TO 1
TOTAL ON grupa FIELDS IZNOS,MARZA,PLACPOR,RABAT,VELVRED,MALVRED,TRDOB,POREZ,USLUGE FOR PRENOS=' '  TO &KKOCKA2
ZAP
APPEND FROM &kkocka2
GO TOP
DO WHILE.NOT.EOF()
   IF TOBJEKAT='V'
      REPLACE NABVRED WITH VELVRED-RABAT+USLUGE
   ELSE
      REPLACE NABVRED WITH MALVRED-RABAT+USLUGE
   ENDIF
   REPLACE MARZA WITH MARZA-RABAT
   SKIP
ENDDO   
GO TOP
MNABVRED=0
MMARZA=0
DO WHILE.NOT.EOF()
   MNABVRED=MNABVRED+NABVRED
   MMARZA=MMARZA+MARZA
   SKIP
ENDDO   
GO TOP
SORT ON MARZA TO &KKOCKA2 DESCEND
DELETE ALL
PACK
APPEND FROM &KKOCKA2
SET ORDER TO 
GO TOP
DO WHILE.NOT.EOF()
   IF MNABVRED<>0
      MPROMET=ROUND(NABVRED*100/MNABVRED,2)
      REPLACE IZNOS WITH MPROMET
   ENDIF
   IF MMARZA<>0
      MPROMET=ROUND(MARZA*100/MMARZA,2)
      REPLACE RABAT WITH MPROMET
   ENDIF
   SKIP
ENDDO
SELECT kocka
USE robgru IN 0 ORDER 1
SET RELATION TO grupa INTO robgru additive
GO TOP 
PUSH KEY CLEAR
*REPORT FORM FAKIZVAN01Og2  PREVIEW 

   mfile='FAKIZVAN01OG2'
   uslov=""
   DO printer_bullzip WITH mdata02,mfile,uslov


POP KEY
SELECT KOCKA
USE
SELECT robgru
use
SELECT KALI
POP KEY