PUSH KEY CLEAR
   DO IDEL WITH (Kkockax)
   DO IDEL WITH (Kkockax2)
SET EXACT ON
SET ORDER TO 2
COPY TO &KKOCKA
USE &KKOCKA IN 0 ALIAS KOCKA EXCLUSIVE
SELECT KOCKA
GO TOP
DO WHILE.NOT.EOF()
   IF ALLTRIM(TARIFA)=TOSTOPA
      REPLACE PDV18 WITH POREZ
   ENDIF   
   IF ALLTRIM(TARIFA)=TNSTOPA
      REPLACE PDV8 WITH POREZ
   ENDIF   
   SKIP
ENDDO   
INDEX ON NAZIV TAG NAZIV
SET ORDER TO 1
TOTAL ON NAZIV FIELDS IZNOS,MARZA,PLACPOR,RABAT,RABAT2,VELVRED,MALVRED,TRDOB,POREZ,PDV18,PDV8 FOR PRENOS=' '  TO &KKOCKA2
DELETE ALL
PACK

APPEND FROM &KKOCKA2
USE
DO IDEL WITH (Kkockax2)
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
SELECT KOCKA
GO TOP
DO WHILE.NOT.EOF()
   IF TOBJEKAT='V'
      REPLACE NABVRED WITH VELVRED-RABAT-RABAT2
   ELSE
      REPLACE NABVRED WITH MALVRED-RABAT-RABAT2
   ENDIF
   SKIP
ENDDO   
GO TOP
SET ORDER TO 
SORT ON NABVRED TO &KKOCKA2 DESCEND
DELETE ALL
PACK

APPEND FROM &KKOCKA2
GO TOP
MNABVRED=0
MMARZA=0
DO WHILE.NOT.EOF()
   MNABVRED=MNABVRED+NABVRED
   MMARZA=MMARZA+MARZA
   MOSTOPA=VAL(TOSTOPA)
   MNSTOPA=VAL(TNSTOPA)   
   REPLACE OSN18 WITH ROUND(PDV18*100/MOSTOPA,3)
   REPLACE OSN8 WITH ROUND(PDV8*100/MNSTOPA,3)
   SKIP
ENDDO   
*GO TOP
*DO WHILE.NOT.EOF()
*   IF MNABVRED<>0
*      MPROMET=ROUND(NABVRED*100/MNABVRED,2)
*      REPLACE IZNOS WITH MPROMET
*   ENDIF
*   IF MMARZA<>0
*      MPROMET=ROUND(MARZA*100/MMARZA,2)
*      REPLACE RABAT WITH MPROMET
*   ENDIF
*   SKIP
*ENDDO
GO TOP 

PUSH KEY CLEAR
*REPORT FORM FAKIZVAN01G  PREVIEW 

   mfile='FAKIZVAN01G'
   uslov=""
   DO printer_bullzip WITH mdata02,mfile,uslov

POP KEY
SELECT KOCKA
USE
SELECT KALI
POP KEY