PUSH KEY CLEAR
   DO IDEL WITH (Kkockax)
   DO IDEL WITH (Kkockax2)

SET ORDER TO 2
TOTAL ON NAZIV FIELDS IZNOS,MARZA,PLACPOR,RABAT,VELVRED,MALVRED,TRDOB,POREZ,USLUGE FOR PRENOS=' '  TO &KKOCKA
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
SELECT KOCKA
GO TOP
DO WHILE.NOT.EOF()
   IF TOBJEKAT='V'
      REPLACE NABVRED WITH VELVRED-RABAT+USLUGE
   ELSE
      REPLACE NABVRED WITH MALVRED-RABAT+USLUGE
   ENDIF
   SKIP
ENDDO   
GO TOP
SET ORDER TO 
SORT ON NABVRED TO &KKOCKA2 DESCEND
DELETE ALL
PACK

APPEND FROM &KKOCKA2
GO TOP
MNABVRED=0
MMARZA=0
DO WHILE.NOT.EOF()
   MNABVRED=MNABVRED+NABVRED
   MMARZA=MMARZA+MARZA
   SKIP
ENDDO   
GO TOP
DO WHILE.NOT.EOF()
   IF MNABVRED<>0
      MPROMET=ROUND(NABVRED*100/MNABVRED,2)
      REPLACE IZNOS WITH MPROMET
   ENDIF
   IF MMARZA<>0
      MPROMET=ROUND(MARZA*100/MMARZA,2)
      REPLACE RABAT WITH MPROMET
   ENDIF
   SKIP
ENDDO
GO TOP 
PUSH KEY CLEAR

*REPORT FORM FAKIZVAN01O  PREVIEW 

   mfile='FAKIZVAN01O'
   uslov=""
   DO printer_bullzip WITH mdata02,mfile,uslov


POP KEY
SELECT KOCKA
USE
SELECT KALI
POP KEY