PUSH KEY CLEAR
   DO IDEL WITH (Kkockax)
   DO IDEL WITH (Kkockax2)
SELECT KALI
COPY TO &KKOCKA 
USE &KKOCKA IN 0 ALIAS KOCKA EXCLUSIVE
SELECT KOCKA
INDEX ON SIFRA+RSIF TAG SIFRSIF
INDEX ON SIFRA TAG SIFRA
SET ORDER TO 1
TOTAL ON SIFRA+RSIF FIELDS KOLI,VELVRED TO &KKOCKA2
DELETE ALL
PACK

APPEND FROM &KKOCKA2
SET RELATION TO SIFRA INTO AN0 ADDITIVE
SET RELATION TO RSIF INTO ROB ADDITIVE
REPLACE ALL DATDOK WITH ADAT1
COPY TO PROMET FIELDS SIFRA,AN0.NAZIV,AN0.PIB,AN0.ULICA,AN0.MESTO,RSIF,ROB.NAZ,KOLI,VELVRED,DATDOK TYPE XLS
SELECT KOCKA
USE
SELECT KALI
POP KEY