PUSH KEY CLEAR
   DO IDEL WITH (Kkockax)
   DO IDEL WITH (Kkockax2)
SELECT KALI
COPY TO &KKOCKA 
USE &KKOCKA IN 0 ALIAS KOCKA EXCLUSIVE
SELECT KOCKA
INDEX ON SIFRA+RSIF TAG SIFRSIF
INDEX ON SIFRA TAG SIFRA
SET ORDER TO 1
TOTAL ON SIFRA+RSIF FIELDS KOLI,VELVRED TO &KKOCKA2
DELETE ALL
PACK
APPEND FROM &KKOCKA2
SET RELATION TO SIFRA INTO AN0 ADDITIVE
SET RELATION TO RSIF INTO ROB ADDITIVE
PUSH KEY CLEAR
*REPORT FORM FAKIZVAN01GR  PREVIEW 

   mfile='FAKIZVAN01GR'
   uslov=""
   DO printer_bullzip WITH mdata02,mfile,uslov


POP KEY
SELECT KOCKA
USE
SELECT KALI
POP KEY