PUSH KEY CLEAR
FAK.GRD0.COLUMN6.SETFOCUS
IF TNET=1
IF RECCOUNT()>0
   *---AKO KALKULACIJA POSTOJI
   IF FAKG.ARHIVA=' '
      *---AKO NIJE ARHIVIRANA-----
      SELECT FAK
      MBRKAL=BRKAL
      MDATDOK=DATDOK
      APPEND BLANK
      REPLACE BRKAL WITH MBRKAL 
      REPLACE DATDOK WITH MDATDOK
      FAK.GRD0.SETFOCUS
      FAK.REFRESH
   ELSE
      *------AKO JE KALKULACIJA  ARHIVIRANA
      SELECT FAK
      SET RELATION TO
      SET ORDER TO 1 
      GO BOTTOM
      MBRKAL=BRKAL
      MNLEN=LEN(ALLTRIM(STR(VAL(ALLTRIM(MBRKAL))+1,6,0)))
      MNBRKAL=REPLI('0',6-MNLEN)+ALLTRIM(STR(VAL(ALLTRIM(MBRKAL))+1,6,0))
      SET ORDER TO 1
            LOCATE FOR BRKAL=MNBRKAL

      IF.NOT.FOUND()
         APPEND BLANK
         REPLACE BRKAL WITH MNBRKAL 
         FAK.GRD0.SETFOCUS
         FAK.GRD0.REFRESH
         FAK.REFRESH
      ENDIF
      SELECT FAKG
*            LOCATE FOR BRKAL=MNBRKAL

      LOCATE FOR BRKAL=MNBRKAL
      IF.NOT.FOUND()
         APPEND BLANK
         REPLACE BRKAL WITH MNBRKAL
      ENDIF      
      DO FORM FAKZAGG
      SELECT FAK
            LOCATE FOR BRKAL=MNBRKAL

      SET RELATION TO BRKAL INTO FAKG ADDITIVE
      SET RELATION TO RSIF INTO ROB ADDITIVE
      REPLACE DATDOK WITH FAKG.DATDOK    
      SET ORDER TO 
   ENDIF 
ELSE
   *--------AKO PRVA STAVKA NE POSTOJI---------
   APPEND BLANK
   MNBRKAL='000001'
   REPLACE BRKAL WITH MNBRKAL 
   *------IDEMO U ZAGLAVLJE
   IF .NOT.FOUND()
      SELECT FAK
      SET RELATION TO
      SELECT FAKG
*            LOCATE FOR BRKAL=MNBRKAL

      LOCATE FOR BRKAL=MNBRKAL
      IF.NOT.FOUND()
         APPEND BLANK
         REPLACE BRKAL WITH MNBRKAL
      ENDIF     
      DO FORM FAKZAGG
      SELECT FAK
      SET RELATION TO BRKAL INTO FAKG ADDITIVE
      SET RELATION TO RSIF INTO ROB ADDITIVE
      REPLACE DATDOK WITH FAKG.DATDOK
   ENDIF   
ENDIF    
ELSE
*-----AKO SE RADI KOD ULAZA===========

   IF RECCOUNT()>0
      *---AKO KALKULACIJA POSTOJI
      IF FAKG.ARHIVA=' '
        *---AKO NIJE ARHIVIRANA-----
         MBRKAL=BRKAL
         MDATDOK=DATDOK
         APPEND BLANK
         REPLACE BRKAL WITH MBRKAL 
         REPLACE DATDOK WITH MDATDOK
         FAK.GRD0.SETFOCUS
         FAK.REFRESH
      ENDIF
   ELSE
      PUBLIC PPORUKA
      PPORUKA=' OTVORITE NOVU FAKTURU '
      DO FORM PORUKA

   ENDIF
ENDIF


SELECT FAK
SET ORDER TO
FAK.GRD0.COLUMN3.SETFOCUS
POP KEY
FAK.REFRESH  
