PUSH KEY CLEAR
DO IDEL WITH (KKOCKax)
DO IDEL WITH (KKOCKax2)
SELECT KALI
SET ORDER TO 6
TOTAL ON RNAL TO &KKOCKA
USE &KKOCKA IN 0 EXCLU ALIAS KOCKA
SELECT KOCKA
GO TOP
   *REPORT FORM FAKIZV20RN PREVIEW

   mfile='FAKIZV20RN'
   uslov=""
   DO printer_bullzip WITH mdata02,mfile,uslov
   
   
SELECT KOCKA
USE
SELECT KALI
POP KEY
