PUSH KEY CLEAR
   SET ORDER TO 5
   GO TOP
DO IDEL WITH (KKOCKAX)
DO IDEL WITH (KKOCKAX2)
TOTAL ON TARIFA TO &KKOCKA
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
SELECT KOCKA
   *REPORT FORM FAKIZV3TAR PREVIEW

   mfile='FAKIZV3TAR'
   uslov=""
   DO printer_bullzip WITH mdata02,mfile,uslov

   
   SELECT KOCKA
   USE
   SELECT KALI
POP KEY