PUSH KEY CLEAR
   DO IDEL WITH (Kkockax)

SET ORDER TO 2
TOTAL ON NAZIV FIELDS izni,IZNOS,MARZA,RABAT,VELVRED,MALVRED,POREZ,USLUGE,PORUSL   TO &KKOCKA
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
SELECT KOCKA
GO TOP
COPY TO fak_saldo_kupaca TYPE xls
PUSH KEY CLEAR

*REPORT FORM FAKIZV2F10  PREVIEW 
   mfile='FAKIZV2F10'
   uslov=""
   DO printer_bullzip WITH mdata02,mfile,uslov

POP KEY
SELECT KOCKA
USE
SELECT KALI
POP KEY
