PUSH KEY CLEAR
   DO IDEL WITH (KKOCKAX)
SET ORDER TO 3
TOTAL ON FVRSTA FIELDS IZNI,MARZA,RABAT,RABAT2,VELVRED,MALVRED,POREZ   TO &KKOCKA
use &kFAKprn in 0 order 1 alias FAKprn 
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
SELECT KOCKA
GO TOP
DO WHILE.NOT.EOF()
   MFVRSTA=FVRSTA
   SELECT FAKPRN
   LOCATE FOR FVRSTA=MFVRSTA
   IF FOUND()
      MFNAZ=FNAZ
   ELSE
      MFNAZ='*****NEMA****'   
   ENDIF
   SELECT KOCKA
   REPLACE NAZIV WITH MFNAZ   
   SKIP
ENDDO   
GO TOP
PUSH KEY CLEAR
*REPORT FORM FAKIZV3D  PREVIEW 

   mfile='FAKIZV3D'
   uslov=""
   DO printer_bullzip WITH mdata02,mfile,uslov


POP KEY
SELECT KOCKA
USE
SELECT FAKPRN
USE
SELECT KALI
POP KEY