PUSH KEY CLEAR
   DO IDEL WITH (KKOCKAX)
   DO IDEL WITH (KKOCKAX2)
SET ORDER TO 3
COPY TO &KKOCKA
USE &KKOCKA IN 0 ALIAS KOCKA EXCLUSIVE
SELECT KOCKA
INDEX ON VRSTA TAG VRSTA
SET ORDER TO 1
TOTAL ON FVRSTA FIELDS IZNI,MARZA,RABAT,RABAT2,VELVRED,MALVRED,POREZ   TO &KKOCKA2
SELECT KOCKA
ZAP
APPEND FROM &KKOCKA2
GO TOP
PUSH KEY CLEAR
*REPORT FORM FAKIZV3DVRSTA  PREVIEW 

   mfile='FAKIZV3DVRSTA'
   uslov=""
   DO printer_bullzip WITH mdata02,mfile,uslov


POP KEY
SELECT KOCKA
USE
SELECT KALI
POP KEY