PUSH KEY CLEAR
   DO IDEL WITH (Kkockax)
   DO IDEL WITH (Kkockax2)
   SET RELATION TO
   SET ORDER TO 1
   TOTAL ON BRKAL FIELDS izni,IZNOS,MARZA,RABAT,VELVRED,POREZ,MALVRED TO &KKOCKA
   USE &KKOCKA IN 0 ALIAS KOCKA EXCLUSIVE
   SELECT KOCKA
   INDEX ON PUTNIK TAG PUTNIK
   SET ORDER TO 1
   TOTAL ON PUTNIK TO &KKOCKA2 
   DELETE ALL
   PACK
   APPEND FROM &KKOCKA2
   SET ORDER TO 
   SET RELATION TO SIFRA INTO AN0 ADDITIVE
   GO TOP   
   REPLACE ALL IZNOS WITH IZNI
   *REPORT FORM FAKIZV2PUTNIK PREVIEW
   mfile='FAKIZV2PUTNIK'
   uslov=""
   DO printer_bullzip WITH mdata02,mfile,uslov
   
   
   SELECT KOCKA
   USE
   SELECT KALI
POP KEY   
