PUSH KEY CLEAR
   DO IDEL WITH (KKOCKAX)
   DO IDEL WITH (KKOCKAX2)

SET ORDER TO 3
COPY TO &KKOCKA
USE &KKOCKA IN 0 ALIAS KOCKA EXCLUSIVE
SELECT KOCKA
INDEX ON BRKAL+PUTNIK TAG BRKAL
INDEX ON PUTNIK TAG PUTNIK
SET ORDER TO 1
TOTAL ON BRKAL+PUTNIK FIELDS IZNI,MARZA,RABAT,RABAT2,VELVRED,MALVRED,POREZ,PUTNIK   TO &KKOCKA2
ZAP
APPEND FROM &KKOCKA2
REPLACE ALL DDUG WITH 1
SET ORDER TO 2
TOTAL ON PUTNIK FIELDS IZNI,MARZA,RABAT,RABAT2,VELVRED,MALVRED,POREZ,DDUG   TO &KKOCKA2
ZAP
APPEND FROM &KKOCKA2
use PUTNICI in 0 order 1 alias PUTNICI
SELECT KOCKA
REPLACE ALL IZNOS WITH ROUND((VELVRED-RABAT)/DDUG,2)
REPLACE ALL KARTICA WITH ROUND((MARZA-RABAT)/DDUG,2)
GO TOP
DO WHILE.NOT.EOF()
   MPUTNIK=PUTNIK
   SELECT PUTNICI
   LOCATE FOR PUTNIK=MPUTNIK
   IF FOUND()
      MFNAZ=IME
   ELSE
      MFNAZ='*****NEMA****'   
   ENDIF
   SELECT KOCKA
   REPLACE NAZIV WITH MFNAZ   
   SKIP
ENDDO   
GO TOP
PUSH KEY CLEAR
*REPORT FORM FAKIZV3DPROSEK  PREVIEW 

   mfile='FAKIZV3DPROSEK'
   uslov=""
   DO printer_bullzip WITH mdata02,mfile,uslov


POP KEY
SELECT putnici
use
SELECT KOCKA
USE
SELECT KALI
POP KEY