PUSH KEY CLEAR
SELECT FAK
IF FAKG.ARHIVA=' '
MBRKAL=BRKAL
SET ORDER TO 1
   LOCATE FOR BRKAL=MBRKAL

SELECT FAKG
MREC=RECCOUNT()
MIME=REPLI('0',5-LEN(ALLTRIM(STR(MREC,5,0))))+ALLTRIM(STR(MREC,5,0))
SELECT FAK
MMIME=MIME+'.BON'
SET CENTURY ON
MDANAS=SUBSTR(DTOC(DATE()),1,2)+SUBSTR(DTOC(DATE()),4,2)+SUBSTR(DTOC(DATE()),7,4)
MVREME=SUBSTR(TIME(),1,2)+SUBSTR(TIME(),4,2)+SUBSTR(TIME(),7,2)
SET CENTURY OFF
ANLOPER='01'
MM='100'+MDANAS+MVREME+MIME+ANLOPER
MMLEN=LEN(ALLTRIM(MM))
bobi=FCREATE(MMIME)
FPUTS(bobi,MM)
MMALVRED=0
DO WHILE.NOT.EOF()
   IF BRKAL<>MBRKAL
      EXIT
   ENDIF   
   MRSIF=RSIF
   MKOLI=TRAN(KOLI,'99999.999')
   MMkoli=SUBSTR(MKOLI,1,5)+SUBSTR(MKOLI,7,3)
   M1LEN=LEN(ALLTRIM(MMKOLI))
   IF M1LEN<8
      MMKOLI=REPLI('0',8-M1LEN)+ALLTRIM(MMKOLI)
   ENDIF
   MMALCENA=TRAN(MALCENA,'999999.99')
   MMMALCENA=SUBSTR(MMALCENA,1,6)+SUBSTR(MMALCENA,8,2)
   M1LEN=LEN(ALLTRIM(MMMALCENA))
   IF M1LEN<8
      MMMALCENA=REPLI('0',8-M1LEN)+ALLTRIM(MMMALCENA)
   ENDIF
   MJED='01'
   MSTORN='00'
   MNAZ=SUBSTR(ROB.NAZ,1,30)
   MRSIF=ALLTRIM(RSIF)
   MLENRSIF=LEN(MRSIF)
   MBARKOD=REPLI('0',13-MLENRSIF)+MRSIF
   IF ALLTRIM(TARIFA)=TOSTOPA
      MPG='03'
      ELSE
      MPG='04'
   ENDIF
   MM='200'+MNAZ+MMMALCENA+MMKOLI+'00'+MBARKOD+MPG
   MMLEN=LEN(ALLTRIM(MM))
   FPUTS(bobi,MM)
   MMALVRED=MMALVRED+MALVRED
   SKIP
ENDDO
   LOCATE FOR BRKAL=MBRKAL

SELECT KASAPL
M2GOTOVINA=KES
M2CEK=CEK
M2KARTICA=KARTICA
MGOT=TRAN(M2GOTOVINA,'999999.99')
MCEK=TRAN(M2CEK,'999999.99')
MKARTICA=TRAN(M2KARTICA,'999999.99')

IF M2GOTOVINA<>0
   MMGOT=SUBSTR(MGOT,1,6)+SUBSTR(MGOT,8,2)
   M1LEN=LEN(ALLTRIM(MMGOT))
   IF M1LEN<8
      MMGOT=REPLI('0',8-M1LEN)+ALLTRIM(MMGOT)
   ENDIF
   MM='300'+MMGOT+'00'
   MMLEN=LEN(ALLTRIM(MM))
   FPUTS(bobi,MM,MMLEN)
ENDIF   

IF M2CEK<>0
   MMGOT=SUBSTR(MCEK,1,6)+SUBSTR(MCEK,8,2)
   M1LEN=LEN(ALLTRIM(MMGOT))
   IF M1LEN<8
      MMGOT=REPLI('0',8-M1LEN)+ALLTRIM(MMGOT)
   ENDIF
   MM='300'+MMGOT+'01'
   MMLEN=LEN(ALLTRIM(MM))
   FPUTS(bobi,MM,MMLEN)
ENDIF   

IF M2KARTICA<>0
   MMGOT=SUBSTR(MKARTICA,1,6)+SUBSTR(MKARTICA,8,2)
   M1LEN=LEN(ALLTRIM(MMGOT))
   IF M1LEN<8
      MMGOT=REPLI('0',8-M1LEN)+ALLTRIM(MMGOT)
   ENDIF
   MM='300'+MMGOT+'02'
   MMLEN=LEN(ALLTRIM(MM))
   FPUTS(bobi,MM,MMLEN)
ENDIF   

FCLOSE(bobi)
MFSALJI='C:\IPOS\BON'
COPY FILE &MMIME TO &MFSALJI
DELETE FILE (MMIME)
SELECT FAK
ENDIF
POP KEY