PUSH KEY CLEAR
SELECT FAKLICA
SET ORDER TO 
GO BOTTOM
APPEND BLANK
GO BOTTOM
FAKLICA.GRD0.SetFocus
FAKLICA.GRD0.REFRESH
REPLACE OLSIFRA WITH STR(RECNO(),2,0)
DO FORM FAKLICAKART
GO BOTTOM
FAKLICA.GRD0.SetFocus
FAKLICA.GRD0.REFRESH
FAKLICA.REFRESH  
POP KEY