PUSH KEY CLEAR
*SET STEP ON
FAKNOVA.GRD0.RECORDSOURCE=''
SELECT magg
GO BOTTOM
MBRKAL=BRKAL
MMREC=RECCOUNT()
*use
MNLEN=LEN(ALLTRIM(STR(VAL(ALLTRIM(MBRKAL))+1,6,0)))
MNBRKAL=REPLI('0',6-MNLEN)+ALLTRIM(STR(VAL(ALLTRIM(MBRKAL))+1,6,0))
SELECT MAGg
LOCATE FOR BRKAL=MNBRKAL
IF.NOT.FOUND()
   APPEND BLANK
   REPLACE BRKAL WITH MNBRKAL
   REPLACE OPER WITH AAOPER
ENDIF
SELECT MAGG
SCATTER NAME POLJA
SELECT fakG
APPEND BLANK
GATHER NAME POLJA
SELECT MAGG
FAKNOVA.GRD0.RECORDSOURCE='MAGG'
faknova.GRD0.COLUMN1.CONTROLSOURCE='BRKAL'
FAKNOVA.GRD0.SETFOCUS
FAKNOVA.REFRESH
POP KEY
