PUSH KEY CLEAR
SELECT FAK
REPLACE KOLI WITH 0
REPLACE CENA WITH 0
REPLACE IZNI WITH 0
REPLACE VELCENA WITH 0
REPLACE VELVRED WITH 0
REPLACE MARPROC WITH 0
REPLACE MARZA WITH 0
REPLACE RABPROC WITH 0
REPLACE RABAT WITH 0
REPLACE RABPROC2 WITH 0
REPLACE RABAT2 WITH 0
REPLACE ZAOKRUZ WITH 0
REPLACE AKCCENA WITH 0
REPLACE AKCVRED WITH 0
REPLACE TARIFA WITH ' '
REPLACE PROCPOR WITH 0
REPLACE POREZ WITH 0
REPLACE MALCENA WITH 0
REPLACE MALVRED WITH 0
POP KEY
