PUSH KEY CLEAR
FAK.CMDFAKNALGOT.SETFOCUS
*FAK.GRD0.COLUMN1.SETFOCUS
MIME='FAK'
CLOSE ALL TABLES
FAK.RELEASE
PUBLIC TKOJI
TKOJI='NALGK'
TANAL='NALAP'
TGKREDNI='1'
*DO FORM NALP WITH 'NALAP'
DO FORM NALP
POP KEY
KEYBOARD '{ENTER}' 
