PUSH KEY CLEAR
SELECT FAKG
mnbrkal=brkal
IF ARHIVA=' '
   IF ALLTRIM(OPER)=AAOPER.OR.TREBOV='*'
   SELECT FAK
   SET RELATION TO
   SELECT FAKG
*         LOCATE FOR BRKAL=MNBRKAL

   LOCATE FOR BRKAL=MNBRKAL
   IF.NOT.FOUND()
      APPEND BLANK
      REPLACE BRKAL WITH MNBRKAL
      REPLACE OPER WITH AAOPER
   ENDIF      
   DO FORM FAKZAG
   SELECT FAK
   APPEND BLANK
   REPLACE BRKAL WITH MNBRKAL
   SET ORDER TO 1
         LOCATE FOR BRKAL=MNBRKAL

   SET RELATION TO BRKAL INTO FAKG ADDITIVE
   SET RELATION TO RSIF INTO ROB ADDITIVE
   REPLACE DATDOK WITH FAKG.DATDOK    
   SET ORDER TO 
   GO BOTTOM
   FAKNOVA.RELEASE
   FAK.grd0.setfocus
   FAK.refresh
   ELSE
      PUBLIC PPORUKA
      PPORUKA=' RACUN '+MNBRKAL+' JE OTVORIO DRUGI OPERATER-OTVORITE NOVI '
      DO FORM PORUKA
      FAKNOVA.GRD0.RECORDSOURCE='FAKG'
      FAKNOVA.GRD0.COLUMN1.CONTROLSOURCE='BRKAL'
      FAKNOVA.GRD0.COLUMN1.SETFOCUS
      FAKNOVA.GRD0.REFRESH
      FAKNOVA.REFRESH
   ENDIF
ELSE
   PUBLIC PPORUKA
   PPORUKA=' RACUN '+MNBRKAL+' JE PROKNJIZEN  OTVORITE NOVI '
   DO FORM PORUKA
   SELECT FAKG
   FAKNOVA.GRD0.RECORDSOURCE='FAKG'
   FAKNOVA.GRD0.COLUMN1.CONTROLSOURCE='BRKAL'
   FAKNOVA.GRD0.COLUMN1.SETFOCUS
   FAKNOVA.GRD0.REFRESH
   FAKNOVA.REFRESH
ENDIF
POP KEY
