PUSH KEY CLEAR
FAK.GRD0.COLUMN4.SETFOCUS
IF FAKG.ARHIVA='*'
   IF FAKG.ARHIVA2=' '
      SELECT FAKG
      REPLACE ARHIVA WITH ' '
   ELSE
      SELECT FAKG
      IF PPASNIVO=1
         REPLACE ARHIVA WITH ' '
      ENDIF   
   ENDIF
   SELECT FAK
ELSE
   SELECT FAKG
   REPLACE ARHIVA WITH '*'
   SELECT FAK
ENDIF
POP KEY