PUSH KEY CLEAR
IF fakG.ARHIVA=' '
   mbrkal=brkal
   SELECT FAK
   SET ORDER TO 1
      LOCATE FOR BRKAL=MBRKAL

   IF FOUND()
      MDATNAB=DATDOK
      DO WHILE.NOT.EOF()
         IF BRKAL<>MBRKAL
            EXIT
         ENDIF 
         REPLACE DEVCENA WITH VELCENA
         REPLACE DEVVRED WITH ROUND(KOLI*DEVCENA,3)
         SKIP
      ENDDO   
   endif   
      LOCATE FOR BRKAL=MBRKAL

   SET ORDER TO 
ENDIF
FAK.GRD0.SETFOCUS
POP KEY
FAK.REFRESH
