PUSH KEY CLEAR
   FAK.GRD0.COLUMN3.SETFOCUS
   MBRKAL=BRKAL
   IF FAKG.ARHIVA=' '
      SELECT FAK
      SET RELATION TO
      SELECT FAKG
      DO FORM FAKPROMENINAL
      MDATDOK=DATDOK
      SELECT FAK
      SET RELATION TO BRKAL INTO FAKG ADDITIVE
      SET RELATION TO RSIF INTO ROB ADDITIVE
      SET ORDER TO 1
      LOCATE FOR BRKAL=MBRKAL

      SET ORDER TO   
   ENDIF
POP KEY