PUSH KEY CLEAR
FAK.GRD0.COLUMN1.SETFOCUS
DO FORM FAKPREG
select FAkprn
SET RELATION TO 
set relation to fpsifra into fakpodn additive
SELECT FAKG
SET RELATION TO
SET RELATION TO SIFRA INTO AN0 ADDITIVE
SET RELATION TO FVRSTA INTO FAKPRN ADDITIVE
IF TNET=2
SELECT FAKS
SET RELATION TO 
SET RELATION TO BRKAL INTO FAKG  ADDITIVE
SET RELATION TO RSIF INTO ROB ADDITIVE
ENDIF
SELECT FAK
SET RELATION TO 
SET RELATION TO BRKAL INTO FAKG  ADDITIVE
SET RELATION TO RSIF INTO ROB ADDITIVE
POP KEY
