PUSH KEY CLEAR
PUBLIC AFTFAKT,AFTIZDAO,AFTDIREKTOR,AFTPRIMIO,AFFAKT,AFIZDAO,AFDIREKTOR,AFPRIMIO,afdev
AFFAKT=FAKPRN.FFAKT
AFIZDAO=FAKPRN.FIZDAO
AFDIREKTOR=FAKPRN.FDIREKTOR
AFPRIMIO=FAKPRN.FPRIMIO
afdev=FAKPRN.dev
IF FAKPRN.FFAKT=1
AFTFAKT=FAKPRN.FTFAKT
ELSE
AFTFAKT=SPACE(25)
ENDIF
IF FAKPRN.FIZDAO=1
   AFTIZDAO=FAKPRN.FTIZDAO
ELSE
   AFTIZDAO=SPACE(20)
ENDIF   
IF FAKPRN.FDIREKTOR=1
   AFTDIREKTOR=FAKPRN.FTDIREKTOR
ELSE
   AFTDIREKTOR=SPACE(20)
ENDIF   

IF FAKPRN.FPRIMIO=1
   AFTPRIMIO=FAKPRN.FTPRIMIO
ELSE
   AFTPRIMIO=SPACE(20)
ENDIF   
POP KEY