PARAMETERS KAKO
PUSH KEY CLEAR
IF FAKG.ARHIVA=' '
   IF FAKG.PRENOS<>' '
      FAK.GRD0.COLUMN4.SETFOCUS
      MBRKAL=BRKAL
      DO FORM FAKPRENN WITH MBRKAL,KAKO
   ELSE
      DO PORUKAU WITH ' DOKUMENT NIJE PRENOSNI ILI INTERNI '
   ENDIF       
ENDIF   
FAKPREN0.RELEASE
FAK.REFRESH
POP KEY