PUSH KEY CLEAR
FAK.GRD0.COLUMN6.SETFOCUS
MSIFRA=FAKG.SIFRA
MDAT0=TDAT0
MDAT1=TDAT1
KANALK=MDATA01+'\'+'ANALK'+OPERATER+'.DBF'                  
KANALKX=MDATA01+'\'+'ANALK'+OPERATER+'.CDX'         
USE AAAN IN 0 
SELECT AAAN
MREC=RECCOUNT()
USE
USE &KANALK ALIAS ANALK EXCLU IN 0
SELECT ANALK
DELETE ALL
PACK

GO TOP
FOR I=1 TO MREC
   MI=ALLTRIM(STR(I,2,0))
   KANAL='ANAL'+MI
   USE &KANAL IN 0 ALIAS ANAL ORDER 2
   SELECT ANAL
   SEEK MSIFRA
   IF FOUND()
      DO WHILE.NOT.EOF()
         IF SIFRA<>MSIFRA
            EXIT
         ENDIF
         IF datdok>=mdat0.and.datdok<=mdat1
            IF DUG<>0.OR.POT<>0
               SCATTER NAME POLJA
               SELECT ANALK
               APPEND BLANK
               GATHER NAME POLJA
               SELECT ANAL
            ENDIF
         endif
         SKIP
      ENDDO   
   ENDIF                   
   SELECT ANAL
   USE         
NEXT
SELECT ANALK
GO TOP

   DO IDEL WITH (Kkockax)
   DO IDEL WITH (Kkockax2)
   DO IDEL WITH (Kkockax3)

SORT ON KONTO,DATDOK TO &KKOCKA
USE 
USE &KKOCKA IN 0  ALIAS ANALKk EXCLUSIVE
SELECT ANALKk
INDEX ON KONTO+DTOS(DATDOK) TAG KONDAT
SET ORDER TO 1



COPY TO &KKOCKA2
USE &KKOCKA2 IN 0 ALIAS KOCKA2 EXCLU
SELECT KOCKA2
INDEX ON BRRAC TAG BRRAC
TOTAL ON BRRAC TO &KKOCKA3 FIELDS DUG,POT
DELETE ALL
PACK

APPEND FROM &KKOCKA3
DELETE ALL FOR DUG=POT
GO TOP
MODUG=0
MOPOT=0
DO WHILE.NOT.EOF()
   IF VALUTA<=DATE()
      MODUG=MODUG+DUG
      MOPOT=MOPOT+POT
   ENDIF
   SKIP
ENDDO   
USE
PUBLIC ADOSPELO
ADOSPELO=MODUG-MOPOT

SELECT ANALKk
GO TOP 
SELECT AN0
SET ORDER TO 1
SELECT ANALKk
SET RELATION TO SIFRA INTO AN0
DO FORM ANZBIRK2
SELECT ANALKk
SET RELATION TO
USE
SELECT FAK
POP KEY