PUSH KEY CLEAR
   SELECT FAKPRN
   SET ORDER TO 
   APPEND BLANK
   GO BOTTOM
   REPLACE FVRSTA WITH STR(RECCOUNT(),3,0)
   FAKPRN.GRD0.REFRESH  
   DO FAKPRNKART
   FAKPRN.GRD0.REFRESH
   FAKPRN.GRD0.COLUMN2.SETFOCUS
   FAKPRN.GRD0.COLUMN2.SETFOCUS
   FAKPRN.REFRESH  
POP KEY
   
