PUSH KEY CLEAR
SELECT FAK
SET ORDER TO 1
MBRKAL=BRKAL
MRABK=AN0.RABK
*MVALDAN=AN0.VALDAN
*SELECT FAKG
*      LOCATE FOR BRKAL=MBRKAL

*IF FOUND()
*   REPLACE VALUTA WITH DATDOK+MVALDAN
*ENDIF   
SELECT FAK
LOCATE FOR BRKAL=MBRKAL
IF FOUND()
   DO WHILE.NOT.EOF()
      IF BRKAL<>MBRKAL
         EXIT
      ENDIF   
      REPLACE RABPROC WITH MRABK
      DO FAKRAC
      SKIP
   ENDDO
ENDIF
      LOCATE FOR BRKAL=MBRKAL
SET ORDER TO       
FAKSERV.RELEASE

POP KEY   