PUSH KEY CLEAR
PUBLIC MREDREC,MREDZAD
SELECT FAK
MREDREC=RECNO()
MREDZAD=RECCOUNT()
FAK.CMDFAKROBA.SETFOCUS
MBRKAL=BRKAL
TGLAVNISR=0
DO FORM ROBA
SELECT FAK
SET ORDER TO 1
   LOCATE FOR BRKAL=MBRKAL
IF FOUND()
   DO WHILE.NOT.EOF()
      IF BRKAL<>MBRKAL
         EXIT
      ENDIF
      DO FAKRAC   
      SKIP
   ENDDO   
ENDIF
SET ORDER TO 
GOTO MREDREC
*FAK.GRD0.SETFOCUS
FAK.GRD0.COLUMN4.SETFOCUS
*FAK.GRD0.REFRESH
POP KEY
