PUSH KEY CLEAR
*FAK.GRD0.COLUMN4.SETFOCUS
IF FAKG.ARHIVA=' '
   MBRKAL=BRKAL
   SET ORDER TO 1
   LOCATE FOR BRKAL=MBRKAL
   IF FOUND()
      DO WHILE.NOT.EOF()
         IF BRKAL<>MBRKAL
            EXIT
         ENDIF   
         REPLACE RABPROC WITH ROB.RAB4
         REPLACE RABAT WITH ROUND(VELVRED*RABPROC/100,2)
         DO FAKRAC
         SELECT FAK
         SKIP
      ENDDO   
   ENDIF
   LOCATE FOR BRKAL=MBRKAL
   SET ORDER TO 
ENDIF   
FAKSERV.RELEASE

POP KEY
