PUSH KEY CLEAR
USE ROBPR IN 0 ORDER 1
SELECT FAK
SET ORDER TO 1
MBRKAL=BRKAL
MRABK=AN0.RABK
MVALDAN=AN0.VALDAN
MBRPROFILA=AN0.BRPROFILA
IF MBRPROFILA>0.AND.MBRPROFILA<=10
   SELECT FAKG
         LOCATE FOR BRKAL=MBRKAL
   IF FOUND()
      IF MVALDAN<>0
         REPLACE VALUTA WITH DATDOK+MVALDAN
      ENDIF
   ENDIF   
   SELECT FAK
   LOCATE FOR BRKAL=MBRKAL
   IF FOUND()
      DO WHILE.NOT.EOF()
         IF BRKAL<>MBRKAL
            EXIT
         ENDIF   
         MPROFIL=ROB.PROFIL
         SELECT ROBPR
         SEEK MPROFIL
         IF FOUND()
            MRAB='RAB'+ALLTRIM(STR(MBRPROFILA,2,0))
            MMRAB=&MRAB
            SELECT FAK   
            REPLACE RABPROC WITH MMRAB
            DO FAKRAC
         ELSE
            SELECT FAK
         ENDIF
         SKIP
      ENDDO
   ENDIF
ENDIF
SELECT ROBPR
USE
SELECT FAK
LOCATE FOR BRKAL=MBRKAL
SET ORDER TO       
FAKSERV.RELEASE
POP KEY   
