PUSH KEY CLEAR
SELECT FAK
SET ORDER TO 1
MBRKAL=BRKAL
SELECT FAK
LOCATE FOR BRKAL=MBRKAL

IF FOUND()
   DO WHILE.NOT.EOF()
      IF BRKAL<>MBRKAL
         EXIT
      ENDIF   
      MAKCIJARAB=ROB.AKCIJARAB
      REPLACE RABPROC2 WITH MAKCIJARAB
      DO FAKRAC
      SELECT FAK
      SKIP
   ENDDO
ENDIF
SELECT FAK
      LOCATE FOR BRKAL=MBRKAL

SET ORDER TO       
FAKSERV.RELEASE
POP KEY   