PUBLIC acslovima
PUSH KEY CLEAR

USE &KPDVKON IN 0 ALIAS PDVKON
DO IDEL WITH (KKOCKAX)

SELECT PDVKON   
COPY STRUCTURE TO &KKOCKA
USE
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
SELECT KOCKA
APPEND BLANK
SELECT FAK
MBRKAL=BRKAL
set order to 1
LOCATE FOR BRKAL=MBRKAL
IF FOUND()
   AAVANS=FAKG.AVANS
   AOSN18=FAKG.AVANS18
   AOSN8=FAKG.AVANS8
   APDV18=FAKG.AVANSP18
   APDV8=FAKG.AVANSP8
   amfakvred=0
   AMALVRED=0
   DO while.not.eof()
      IF brkal<>mbrkal
         EXIT
      endif   
      AMALVRED=AMALVRED+MALVRED
      MVELVRED=VELVRED
      MRABAT=RABAT+RABAT2
      MPOREZ=POREZ
      mprocpor=procpor
      SELECT KOCKA
      IF MPROCPOR=VAL(TOSTOPA)
         IF mporez<>0
         REPLACE OSN18 WITH OSN18+MVELVRED-MRABAT
         REPLACE PDV18 WITH PDV18+MPOREZ
         endif
      ENDIF
      IF MPROCPOR=VAL(TNSTOPA)
         IF mporez<>0
         REPLACE OSN8 WITH OSN8+MVELVRED-MRABAT
         REPLACE PDV8 WITH PDV8+MPOREZ
         endif
      ENDIF
      
      SELECT FAK
      IF ROB.TRANSPAK>0
          replace paket WITH ROUND(koli/ROB.TRANSPAK,2)
      endif             
      amfakvred=amfakvred+velvred+porez-rabat+ZAOKRUZ-RABAT2
      SKIP
   enddo   
   PUBLIC acslovima
   SET PROCEDURE TO slovima
   acslovima=brojuslova(amfakvred)
   SET PROCEDURE TO 
ELSE
   acslovima='nema'   
ENDIF
LOCATE FOR BRKAL=MBRKAL
DO FAKPRNPUBLIC
*SET REPORTBEHAVIOR 80
LOCATE FOR BRKAL=MBRKAL

INKEY(1)

   REPORT FORM FAK02o FOR BRKAL=MBRKAL NOWAIT TO PRINTER NODIALOG noconsole
SELECT KOCKA
USE
SELECT FAK
POP KEY
