PARAMETERS ASTAMPA
PUBLIC acslovima
PUSH KEY CLEAR
USE &KPDVKON IN 0 ALIAS PDVKON
DO IDEL WITH (KKOCKAX)
DO IDEL WITH (KKOCKAX2)

SELECT PDVKON   
COPY STRUCTURE TO &KKOCKA
USE
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
SELECT KOCKA
APPEND BLANK
SELECT FAKG
COPY STRUCTURE TO &KKOCKA2
USE &KKOCKA2 IN 0 ALIAS KOCKA2
SELECT KOCKA2
APPEND BLANK
SELECT FAKG
FOR I=1 TO 18
   MPR='PR'+ALLTRIM(STR(I,2,0))
   MMPR=&MPR 
   MPV='PV'+ALLTRIM(STR(I,2,0))
   MMPV=&MPV
   MPRDIN='PRDIN'+ALLTRIM(STR(I,2,0))
   MMPRDIN=&MPRDIN
   MBRRAC=ALLTRIM(BRRAC)
   MBRAC='BRAC'+ALLTRIM(STR(I,2,0))
   MDAN=ALLTRIM(STR(MMPV-DATDOK,3,0))
   IF MMPRDIN<>0
      SELECT KOCKA2
      REPLACE &MPRDIN WITH MMPRDIN
      REPLACE &MPV WITH MMPV
      REPLACE &MBRAC WITH ALLTRIM(MBRRAC)+'-'+MDAN
      SELECT FAKG
   ENDIF   
NEXT
SELECT KOCKA2


SELECT FAK

MBRKAL=BRKAL
set order to 1
LOCATE FOR BRKAL=MBRKAL

IF FOUND()
   amfakvred=0
   DO while.not.eof()
      IF brkal<>mbrkal
         EXIT
      endif   
      MVELVRED=VELVRED
         MRABAT=RABAT
         MPOREZ=POREZ
         mprocpor=procpor
      
      
      
      SELECT KOCKA
      IF MPROCPOR=VAL(TOSTOPA)
         IF mporez<>0
         REPLACE OSN18 WITH OSN18+MVELVRED-MRABAT
         REPLACE PDV18 WITH PDV18+MPOREZ
         endif
      ENDIF
      IF MPROCPOR=VAL(TNSTOPA)
         IF mporez<>0
         REPLACE OSN8 WITH OSN8+MVELVRED-MRABAT
         REPLACE PDV8 WITH PDV8+MPOREZ
         endif
      ENDIF
      
      SELECT FAK
            
      amfakvred=amfakvred+velvred+porez-rabat+ZAOKRUZ
    
      SKIP
   enddo   
   PUBLIC acslovima
   SET PROCEDURE TO slovima
   acslovima=brojuslova(amfakvred)
   SET PROCEDURE TO 
ELSE
   acslovima='nema'   
ENDIF
LOCATE FOR BRKAL=MBRKAL
DO FAKPRNPUBLIC
*SET REPORTBEHAVIOR 80

select fakg
ambrkred=brkred
IF FLSIFRA<>SPACE(5)
   MFLSIFRA=FLSIFRA
   USE AN0FIZLI IN 0 ORDER 1
   SELECT AN0FIZLI
   SEEK MFLSIFRA
   IF FOUND()
      AMFLSIFRA=FLSIFRA
      AMIMEPREZ=IME_PREZ
      AMJMBG=JMBG
      AMMESTO=MESTO
      AMULICA=ULICA
   ELSE
      AMFLSIFRA=' NEMA'
      AMIMEPREZ='NEMA'
      AMJMBG='NEMA'
      AMMESTO='NEMA'
      AMULICA='NEMA'
   ENDIF
   USE 
ELSE
   AMFLSIFRA=' NEMA'
   AMIMEPREZ='NEMA'
   AMJMBG='NEMA'
   AMMESTO='NEMA'
   AMULICA='NEMA'
ENDIF
SELECT FAK
   IF ASTAMPA='EKR'
      *REPORT FORM FAK01MPKRED FOR BRKAL=MBRKAL PREVIEW 
      mfile='FAK01MPKRED'
      uslov="BRKAL=MBRKAL"
      DO printer_bullzip WITH mdata02,mfile,uslov
      
   ELSE
      REPORT FORM FAK01MPKRED FOR BRKAL=MBRKAL TO PRINTER
   ENDIF
      
SELECT KOCKA2
USE
SELECT KOCKA
USE
SELECT FAK
POP KEY
