PARAMETERS ASTAMPA
PUBLIC acslovima
PUSH KEY CLEAR
USE &KPDVKON IN 0 ALIAS PDVKON
DO IDEL WITH (KKOCKAX)
DO IDEL WITH (KKOCKAX2)
DO IDEL WITH (KKOCKAX3)

SELECT PDVKON   
COPY STRUCTURE TO &KKOCKA
USE
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
SELECT KOCKA
APPEND BLANK

SELECT FAK

MBRKAL=BRKAL
set order to 1
LOCATE FOR BRKAL=MBRKAL

IF FOUND()
   amfakvred=0
   DO while.not.eof()
      IF brkal<>mbrkal
         EXIT
      endif   
      MVELVRED=VELVRED
         MRABAT=RABAT
         MPOREZ=POREZ
         mprocpor=procpor
      
      
      
      SELECT KOCKA
      IF MPROCPOR=VAL(TOSTOPA)
         IF mporez<>0
         REPLACE OSN18 WITH OSN18+MVELVRED-MRABAT
         REPLACE PDV18 WITH PDV18+MPOREZ
         endif
      ENDIF
      IF MPROCPOR=VAL(TNSTOPA)
         IF mporez<>0
         REPLACE OSN8 WITH OSN8+MVELVRED-MRABAT
         REPLACE PDV8 WITH PDV8+MPOREZ
         endif
      ENDIF
      
      SELECT FAK
            
      amfakvred=amfakvred+velvred+porez-rabat+ZAOKRUZ
    
      SKIP
   enddo   
   PUBLIC acslovima
   SET PROCEDURE TO slovima
   acslovima=brojuslova(amfakvred)
   SET PROCEDURE TO 
ELSE
   acslovima='nema'   
ENDIF
   LOCATE FOR BRKAL=MBRKAL

DO FAKPRNPUBLIC
*SET REPORTBEHAVIOR 80
SELECT FAK
COPY STRUCTURE TO &KKOCKA2
USE &KKOCKA2 IN 0 ALIAS KOCKA2 EXCLU
SELECT KOCKA2
INDEX ON BRKAL TAG BRKAL
SET ORDER TO 1
SELECT FAK
LOCATE FOR BRKAL=MBRKAL
DO WHILE.NOT.EOF()
   IF BRKAL<>MBRKAL
      EXIT
   ENDIF
   SCATTER NAME POLJA
   SELECT KOCKA2
   APPEND BLANK
   GATHER NAME POLJA
   SELECT FAK
   SKIP
ENDDO      
SELECT KOCKA2
SET ORDER TO 1
TOTAL ON BRKAL TO &KKOCKA3 FIELDS VELVRED,POREZ,RABAT 
DELETE ALL
PACK

APPEND FROM &KKOCKA3
GO TOP
SET RELATION TO BRKAL INTO FAKG
GO TOP
*REPORT FORM FAK01SVEUJ PREVIEW 
      mfile='FAK01SVEUJ'
      uslov="BRKAL=MBRKAL"
      DO printer_bullzip WITH mdata02,mfile,uslov

SELECT KOCKA2
USE
SELECT KOCKA
USE
SELECT FAK
   LOCATE FOR BRKAL=MBRKAL

POP KEY
