PUSH KEY CLEAR
SELECT fak
MTOVARNI=FAKG.TOVARNI
DO IDEL WITH (KKOCKAX)
SELECT FAK
SET RELATION TO
SET ORDER TO 1
COPY STRUCTURE TO &KKOCKA
USE &KKOCKA IN 0 ALIAS KOCKA exclu
SELECT FAKG
*SET RELATION TO
SET ORDER TO 7
SEEK MTOVARNI
IF FOUND()   
   DO WHILE.NOT.EOF()
      IF TOVARNI<>MTOVARNI
         EXIT
      ENDIF   
      MBRKAL=BRKAL
      SELECT FAK
      LOCATE FOR BRKAL=MBRKAL

      IF FOUND()
         DO WHILE.NOT.EOF()
            IF BRKAL<>MBRKAL
               EXIT
            ENDIF
            SCATTER NAME POLJA
            SELECT KOCKA
            APPEND BLANK
            GATHER NAME POLJA
            SELECT FAK   
            SKIP
         ENDDO   
      ENDIF
      SELECT FAKG
      SKIP
   ENDDO   
   SELECT FAKG 
   SET ORDER TO 1
   SELECT KOCKA
   INDEX on rsif TAG rsif
   SET ORDER TO 1
   TOTAL ON rsif FIELDS koli,PAKET,BRUTO,NETO TO &kkocka2
   DELETE ALL
PACK

   APPEND FROM &kkocka2
   GO top

   SET RELATION TO BRKAL INTO FAKG ADDITIVE
   SET RELATION TO RSIF INTO ROB ADDITIVE

   *REPORT FORM FAK25 PREVIEW 
      mfile='FAK25'
      uslov=""
      DO printer_bullzip WITH mdata02,mfile,uslov
   
 
   SELECT KOCKA
   USE
   SELECT FAKG
ENDIF
SELECT FAKG
SET ORDER TO 1
SELECT FAK
SET ORDER TO 
SELECT FAK
SET RELATION TO BRKAL INTO FAKG  ADDITIVE
SET RELATION TO RSIF INTO ROB ADDITIVE
POP KEY
