PUSH KEY CLEAR

DO IDEL WITH (KKOCKAX)


USE &KFAKVAL IN 0 ALIAS FAKVAL EXCLU ORDER 1
SELECT FAKVAL
IF USED()
   DELETE ALL
PACK

ENDIF

SELECT FAK
SET ORDER TO 1
 
LOCATE FOR BRKAL=MBRKAL

IF FOUND()
   DO WHILE.NOT.EOF()
      IF BRKAL<>MBRKAL
         EXIT
      ENDIF
      IF koli<>0.or.vtxt<>' '
      MVALDAN=VALDAN
      MBRRAC=ALLTRIM(FAKG.MODEL)+'-'+ALLTRIM(VALDAN)
      MDATDOK=FAKG.DATDOK
      MIZNOS=VELVRED+POREZ-RABAT
      MVALUTA=MDATDOK+VAL(ALLTRIM(MVALDAN))
      MRSIF=RSIF
      MSIFRA=FAKG.SIFRA
      MZIRORACZ=AN0.ZIRORAC
      SELECT FAKVAL
      APPEND BLANK
      REPLACE BRKAL WITH MBRKAL
      REPLACE VALDAN WITH MVALDAN
      REPLACE BRRAC WITH MBRRAC
      REPLACE VALUTA WITH MVALUTA
      REPLACE IZNOS WITH MIZNOS
      REPLACE RSIF WITH MRSIF
      REPLACE ZIRORACZ WITH MZIRORACZ
      REPLACE SIFRA WITH MSIFRA
      endif
      SELECT FAK
      SKIP
   ENDDO
ENDIF         

SELECT FAK         
SET RELATION TO
SELECT FAKG
SET RELATION TO
SELECT FAKVAL

TOTAL ON VALDAN FIELDS IZNOS TO &KKOCKA
DELETE ALL
PACK
APPEND FROM &KKOCKA
GO TOP

SET RELATION TO BRKAL INTO FAKG  ADDITIVE
SET RELATION TO RSIF INTO ROB ADDITIVE
SET RELATION TO SIFRA INTO AN0 ADDITIVE

PUSH KEY CLEAR
   *REPORT FORM FAKOVLASCENJE  PREVIEW 
      mfile='FAKOVLASCENJE'
      uslov=""
      DO printer_bullzip WITH mdata02,mfile,uslov
   
POP KEY 
USE

SELECT FAKG
SET RELATION TO SIFRA INTO AN0 ADDITIVE
SET RELATION TO FVRSTA INTO FAKPRN ADDITIVE

SELECT FAK
LOCATE FOR BRKAL=MBRKAL

SET ORDER TO 
SET RELATION TO BRKAL INTO FAKG  ADDITIVE
SET RELATION TO RSIF INTO ROB ADDITIVE
POP KEY