PARAMETERS ASTAMPA
PUBLIC acslovima
PUSH KEY CLEAR
*USE &KPDVKON IN 0 ALIAS PDVKON
DO IDEL WITH (KKOCKAX)

SELECT FAK
COPY STRUCTURE TO &KKOCKA
SET RELATION TO
*USE
*ALTER TABLE &KkOCKA ADD COLUMN GRUPA c(3)
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
SELECT KOCKA
APPEND BLANK

SELECT FAK

MBRKAL=BRKAL
set order to 1
LOCATE FOR BRKAL=MBRKAL
IF FOUND()
   amfakvred=0
   DO while.not.eof()
      SELECT FAK
      SCATTER NAME POLJA
      *amfakvred=amfakvred+velvred+porez-rabat+ZAOKRUZ
      SELECT KOCKA
      APPEND BLANK
      GATHER NAME POLJA
      SELECT FAK
      SKIP
   enddo   
   *PUBLIC acslovima
   *SET PROCEDURE TO slovima
   *acslovima=brojuslova(amfakvred)
   *SET PROCEDURE TO 
*ELSE
*   acslovima='nema'   
ENDIF
*LOCATE FOR BRKAL=MBRKAL
*DO FAKPRNPUBLIC
*SET REPORTBEHAVIOR 80
SELECT FAK
SET RELATION TO
SELECT KOCKA
INDEX ON GRUPA TAG GRUPA
SET ORDER TO 1
SET RELATION TO BRKAL INTO FAKG ADDITIVE
SET RELATION TO RSIF INTO ROB ADDITIVE
REPLACE ALL GRUPA WITH ROB.VRSTA

*REPORT FORM FAKSTAMPAUTOSERVIS FOR BRKAL=MBRKAL PREVIEW 
      mfile='FAKSTAMPAUTOservis'
      uslov="BRKAL=MBRKAL"
      DO printer_bullzip WITH mdata02,mfile,uslov


SELECT KOCKA
SET RELATION to
USE
select fak
LOCATE FOR BRKAL=MBRKAL
*set relation to brkal into fakg  additive
*set relation to rsif into rob additive
POP KEY
