PARAMETERS MPOC,MKRAJ
PUSH KEY CLEAR
FAK.GRD0.COLUMN4.SETFOCUS
DO IDEL WITH (KKOCKAX4)

SELECT FAK
SET ORDER TO 1
SELECT FAKG
COPY TO &KKOCKA4 FOR VAL(BRKAL)>=MPOC.AND.VAL(BRKAL)<=MKRAJ 
USE &KKOCKA4 IN 0 ALIAS KOCKA4 EXCLU
SELECT KOCKA4
GO TOP
DO WHILE.NOT.EOF()
   MBRKAL=BRKAL
   SELECT FAK
   SET ORDER TO 1
   LOCATE FOR BRKAL=MBRKAL
   SET ORDER TO 
   DO FAKSTAMPF11ODDO
   INKEY(1)
   SELECT KOCKA4
   SKIP
ENDDO   
SELECT KOCKA4
USE
SELECT FAK
GO BOTTOM
POP KEY