PUSH KEY CLEAR
SELECT FAK
MRNAL=FAKG.RNAL
MKOLG=0
DO IDEL WITH (KKOCKAX)
USE PRONALN IN 0 ORDER 1
SELECT PRONALN
SEEK MRNAL
IF FOUND()
   DO WHILE.NOT.EOF()
      IF RNAL<>MRNAL
         EXIT
      ENDIF   
      MKOLG=MKOLG+KOL
      SKIP
   ENDDO   
ELSE
   MKOLG=0
ENDIF      

SELECT FAK
COPY TO &KKOCKA FOR FAKG.RNAL=MRNAL
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
SELECT KOCKA
INDEX ON BRKAL TAG BRKAL
SET ORDER TO 1
GO TOP
MIZNI=0
MVELVRED=0
DO WHILE.NOT.EOF()
   MIZNI=MIZNI+IZNI
   MVELVRED=MVELVRED+VELVRED
   SKIP
ENDDO   
GO TOP
SET RELATION TO BRKAL INTO FAKG ADDITIVE
SET RELATION TO RSIF INTO ROB ADDITIVE
GO TOP
IF MKOLG<>0
   MCENAK=ROUND(MIZNI/MKOLG,3)
   MPRODCENA=ROUND(MVELVRED/MKOLG,3)   
ELSE
   MCENAK=0
   MPRODCENA=0
ENDIF
PUBLIC AMCENAK,AMPRODCENA,AKOL
AMCENAK=MCENAK
AMPRODCENA=MPRODCENA
AKOL=MKOLG
*REPORT FORM FAK19  PREVIEW 
      mfile='FAK19'
      uslov=""
      DO printer_bullzip WITH mdata02,mfile,uslov

SELECT pronaln
use
SELECT KOCKA
SET RELATION TO
USE
SELECT FAK
POP KEY