PARAMETERS ASTAMPA
PUBLIC acslovima
PUSH KEY CLEAR
USE &KPDVKON IN 0 ALIAS PDVKON
DO IDEL WITH (KKOCKAX)

SELECT PDVKON   
COPY STRUCTURE TO &KKOCKA
USE
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
SELECT KOCKA
APPEND BLANK

SELECT FAK

MBRKAL=BRKAL
set order to 1
SEEK mbrkal
IF FOUND()
   amfakvred=0
   DO while.not.eof()
      IF brkal<>mbrkal
         EXIT
      endif   
      MVELVRED=VELVRED
         MRABAT=RABAT
         MPOREZ=POREZ
         mprocpor=procpor
      
      
      
      SELECT KOCKA
      IF MPROCPOR=18
         IF mporez<>0
         REPLACE OSN18 WITH OSN18+MVELVRED-MRABAT
         REPLACE PDV18 WITH PDV18+MPOREZ
         endif
      ENDIF
      IF MPROCPOR=8
         IF mporez<>0
         REPLACE OSN8 WITH OSN8+MVELVRED-MRABAT
         REPLACE PDV8 WITH PDV8+MPOREZ
         endif
      ENDIF
      
      SELECT FAK
            
      amfakvred=amfakvred+velvred+porez-rabat+ZAOKRUZ
    
      SKIP
   enddo   
   PUBLIC acslovima
   SET PROCEDURE TO slovima
   acslovima=brojuslova(amfakvred)
   SET PROCEDURE TO 
ELSE
   acslovima='nema'   
ENDIF
seek mbrkal
DO FAKPRNPUBLIC
SET REPORTBEHAVIOR 80

   IF ASTAMPA='EKR'
      REPORT FORM FAK01BEZCENE FOR BRKAL=MBRKAL.AND.(KOLI<>0.OR.VTXT<>' ') PREVIEW 
   ELSE
      REPORT FORM FAK01BEZCENE FOR BRKAL=MBRKAL.AND.(KOLI<>0.OR.VTXT<>' ') TO PRINTER
   ENDIF
*_REPORTOUTPUT='JOZA'
*      REPORT FORM FAK01 FOR BRKAL=MBRKAL OBJECT TYPE 0
*      REPORT FORM FAK01 FOR BRKAL=MBRKAL OBJECT TYPE 1
*      REPORT FORM FAK01 FOR BRKAL=MBRKAL OBJECT TYPE 2
*      REPORT FORM FAK01 FOR BRKAL=MBRKAL OBJECT TYPE 3
*      REPORT FORM FAK01 FOR BRKAL=MBRKAL OBJECT TYPE 4
*      REPORT FORM FAK01 FOR BRKAL=MBRKAL OBJECT TYPE 3 TO FILE 'C:\JOZA1.JPG'
*      REPORT FORM FAK01 FOR BRKAL=MBRKAL OBJECT TYPE 4 TO FILE 'C:\JOZA2.JPG'
      

SELECT KOCKA
USE
SELECT FAK
POP KEY
