PARAMETERS ASTAMPA
PUSH KEY CLEAR
DO FAKPRNPUBLIC
*SET REPORTBEHAVIOR 80
DO IDEL WITH (KKOCKAX)
SELECT FAK
MBRKAL=BRKAL
COPY TO &KKOCKA FOR BRKAL=MBRKAL
USE &KKOCKA IN 0 ALIAS KOCKA EXCLUSIVE
SELECT KOCKA
INDEX ON NAZ TAG NAZ
SET RELATION TO RSIF INTO ROB ADDITIVE
REPLACE ALL NAZ WITH ROB.GRUPA
TOTAL ON NAZ TO &KKOCKA2 FIELDS VELVRED,RABAT,POREZ
ZAP
APPEND FROM &KKOCKA2
SET RELATION TO BRKAL INTO FAKG ADDITIVE
GO TOP
   IF ASTAMPA='EKR'
      *REPORT FORM FAK01GR PREVIEW 
      mfile='FAK01gr'
      uslov=""
      DO printer_bullzip WITH mdata02,mfile,uslov
      
      
   ELSE
      REPORT FORM FAK01GR TO PRINTER
   ENDIF
SELECT KOCKA   
SET RELATION TO 
USE
SELECT FAK
POP KEY
