PUSH KEY CLEAR
MBRKAL=BRKAL
SELECT FAK
SET ORDER TO 1
LOCATE FOR BRKAL=MBRKAL

SET ORDER TO 
PUBLIC acslovima
IF FILE(KKOCKAX)
   DELETE FILE (KKOCKAX)
ENDIF   
SELECT FAK
SET RELATION TO
COPY STRUCTURE TO &KKOCKA
USE &KKOCKA IN 0 ALIAS KOCKA EXCLUSIVE
SELECT KOCKA
INDEX ON RREDNI TAG REDNI
SET ORDER TO 
SELECT FAK
MBRKAL=BRKAL
set order to 1
LOCATE FOR BRKAL=MBRKAL
IF FOUND()
   amfakvred=0
   ABRRAC=FAKG.BRRAC
   DO while.not.eof()
      IF brkal<>mbrkal
         EXIT
      endif   
      MMALVRED=MALVRED
      MMALCENA=MALCENA
      amfakvred=amfakvred+MALvred
      SCATTER NAME POLJA
      SELECT KOCKA
      APPEND BLANK
      GATHER NAME POLJA
      REPLACE RREDNI WITH '1'
      APPEND BLANK
      GATHER NAME POLJA
      REPLACE RREDNI WITH '2'
      SELECT FAK
      SKIP
   enddo   
ENDIF
SELECT FAK
LOCATE FOR BRKAL=MBRKAL
SELECT KOCKA
SET ORDER TO 1
GO TOP
SET RELATION TO BRKAL INTO FAKG ADDITIVE
SET RELATION TO RSIF INTO ROB ADDITIVE
GO TOP
*REPORT FORM FAK33 PREVIEW
      mfile='FAK33'
      uslov=""
      DO printer_bullzip WITH mdata02,mfile,uslov

SELECT KOCKA
USE
SELECT FAK
SET RELATION TO BRKAL INTO FAKG  ADDITIVE
SET RELATION TO RSIF INTO ROB ADDITIVE
sELECT FAK
SET ORDER TO 1
LOCATE FOR BRKAL=MBRKAL
SET ORDER TO 
POP KEY
