PARAMETERS AGDE,ANUMFAK
PUSH KEY CLEAR
IF AGDE=1
   FAK.COMMAND13.SETFOCUS
ENDIF
SELECT FAK
MBRKAL=BRKAL
manumfak=anumfak
DO CASE MANUMFAK
CASE ANUMFAK=1
   DO FAKSTAMPDIR WITH AGDE,1
CASE ANUMFAK=0
   DO FAKSTAMP0 WITH 'STA',1
CASE ANUMFAK=2
   DO FAKSTAMPDIRA WITH AGDE,1
CASE ANUMFAK=3
   DO FAKSTAMPDIRB WITH AGDE,1
CASE ANUMFAK=4
   DO FAKSTAMP0 WITH 'STA',54
CASE ANUMFAK=5
   DO FAKSTAMPDIR WITH AGDE,5
CASE ANUMFAK=6
   DO FAKSTAMPDIRB WITH AGDE,2
CASE ANUMFAK=7
   DO FAKSTAMPDIRA WITH AGDE,2
CASE ANUMFAK=8
   DO FAKSTAMPDIRB2r WITH AGDE,1
endcase
SELECT FAK
IF AGDE=1
   SET ORDER TO 1
   LOCATE FOR BRKAL=MBRKAL
   SET ORDER TO 
   FAK.GRD0.COLUMN6.SETFOCUS
ENDIF
POP KEY