PUSH KEY CLEAR

DO IDEL WITH (KKOCKAX)


USE &KFAKVAL IN 0 ALIAS FAKVAL EXCLU ORDER 1
SELECT FAKVAL
IF USED()
   DELETE ALL
PACK

ENDIF

SELECT FAK
SET ORDER TO 1
 
LOCATE FOR BRKAL=MBRKAL

IF FOUND()
   DO WHILE.NOT.EOF()
      IF BRKAL<>MBRKAL
         EXIT
      ENDIF
      IF koli<>0.or.vtxt<>' '
      MVALDAN=VALDAN
      MBRRAC=FAKG.BRRAC
      MDATDOK=FAKG.DATDOK
      MIZNOS=VELVRED+POREZ-RABAT
      MVALUTA=MDATDOK+VAL(ALLTRIM(MVALDAN))
      MRSIF=RSIF
      MSIFRA=FAKG.SIFRA
      MZIRORACZ=AN0.ZIRORAC
      SELECT FAKVAL
      APPEND BLANK
      REPLACE BRKAL WITH MBRKAL
      REPLACE VALDAN WITH MVALDAN
      REPLACE BRRAC WITH MBRRAC
      REPLACE VALUTA WITH MVALUTA
      REPLACE IZNOS WITH MIZNOS
      REPLACE RSIF WITH MRSIF
      REPLACE ZIRORACZ WITH MZIRORACZ
*      REPLACE SIFRA WITH MSIFRA
      endif
      SELECT FAK
      SKIP
   ENDDO
ENDIF         

SELECT FAK         
SET RELATION TO

SELECT FAKVAL

TOTAL ON VALDAN FIELDS IZNOS TO &KKOCKA
IF USED()
DELETE ALL
PACK

ENDIF
APPEND FROM &KKOCKA
GO TOP

SET RELATION TO BRKAL INTO FAKG  ADDITIVE
SET RELATION TO RSIF INTO ROB ADDITIVE
MLEN=LEN(ALLTRIM(FIRMA.FIME)+' '+ALLTRIM(FIRMA.FMES))
MNAZRAC=REPLICATE(' ',50-MLEN)+ALLTRIM(FIRMA.FIME)+' '+ALLTRIM(FIRMA.FMES)+' PIB '+FIRMA.FPOR

MLEN=LEN(ALLTRIM(AN0.NAZIV)+' '+ALLTRIM(AN0.MESTO))
MNAZRACZ=REPLICATE(' ',50-MLEN)+ALLTRIM(AN0.NAZIV)+' '+ALLTRIM(AN0.MESTO)+' PIB '+AN0.PIB

USE &KFAKVIR IN 0 ALIAS VIRM EXCLU
SELECT VIRM
IF USED()
DELETE ALL
PACK

ENDIF
SELECT FAKVAL
GO TOP
DO WHILE.NOT.EOF()   
   MSTAMPA='*'
   MZIRORAC=FIRMA.FZIRO
   MZIRORACZ=ZIRORACZ
   MDUG=IZNOS
   MSIF1='221'
   MSVRHA='UPLATA RAÈUNA'
   M0BRRAC=REPLICATE('0',6-LEN(ALLTRIM(SUBSTR(BRKAL,1,6))))+ALLTRIM(BRKAL)
   MMSIFRA=REPLICATE('0',5-LEN(ALLTRIM(SUBSTR(MSIFRA,1,5))))+ALLTRIM(MSIFRA)
   MBRRAC=ALLTRIM(M0BRRAC)+'-'+MMSIFRA+'-'+ALLTRIM(VALDAN)
   AMODEL=ALLTRIM(M0BRRAC)+MMSIFRA+ALLTRIM(VALDAN)
   MDATVAL=VALUTA
   M1=VAL(AMODEL)
   M2=(M1*100/97)-INT(M1*100/97)
   M3=ROUND(97*M2,0)
   M4=98-M3
   IF M4<=9
      M4='0'+STR(M4,1,0)
   ELSE
      M4=STR(M4,2,0)
   ENDIF      
   MPOZIVO=M4+'-'+ALLTRIM(AMODEL)
   SELECT VIRM
   APPEND BLANK
   REPLACE STAMPA WITH MSTAMPA
   REPLACE ZIRORAC WITH MZIRORAC
   REPLACE ZIRORACZ WITH MZIRORACZ
   REPLACE DUG WITH MDUG
   REPLACE SIF1 WITH MSIF1
   REPLACE NAZRAC WITH MNAZRAC
   REPLACE SVRHA WITH MSVRHA
   REPLACE NAZRACZ WITH MNAZRACZ
   REPLACE MODELO WITH '97'
   REPLACE POZIVO WITH MPOZIVO
   REPLACE DATVAL WITH MDATVAL
   REPLACE VALUTA WITH 'RSD'
   SELECT FAKVAL
   SKIP
ENDDO   

USE

SELECT VIRM
PUSH KEY CLEAR
   *REPORT FORM FAKVIR  PREVIEW 
      mfile='FAKVIR'
      uslov=""
      DO printer_bullzip WITH mdata02,mfile,uslov
   
   POP KEY 
SELECT VIRM
USE
SELECT FAK
LOCATE FOR BRKAL=MBRKAL

SET ORDER TO 
SET RELATION TO BRKAL INTO FAKG  ADDITIVE
SET RELATION TO RSIF INTO ROB ADDITIVE
POP KEY