PUSH KEY CLEAR
FAK.GRD0.COLUMN6.SETFOCUS
MBRKAL=BRKAL
SET ORDER TO 1
LOCATE FOR BRKAL=MBRKAL
*REPORT FORM FAKSVE1 PREVIEW FOR BRKAL=MBRKAL
      mfile='FAKSVE1'
      uslov="BRKAL=MBRKAL"
      DO printer_bullzip WITH mdata02,mfile,uslov

SELECT FAK
SET ORDER TO 1
LOCATE FOR BRKAL=MBRKAL

SET ORDER TO 
POP KEY