PARAMETERS AAPRN
PUBLIC acslovima
PUSH KEY CLEAR
MBRKAL=BRKAL
set order to 1
LOCATE FOR BRKAL=MBRKAL
replace fakg.datumi WITH DATE()
replace fakg.vremei WITH time()
SET ORDER TO 3
IF AAPRN=0
   *REPORT FORM FAK01OTBEZ FOR BRKAL=MBRKAL.AND.KOLI<>0 PREVIEW 
      mfile='FAK01OTBEZ'
      uslov="BRKAL=MBRKAL.AND.(KOLI<>0.OR.VTXT<>' ')"
      DO printer_bullzip WITH mdata02,mfile,uslov
   
   
ELSE   
   REPORT FORM FAK01OTBEZ FOR BRKAL=MBRKAL.AND.KOLI<>0 TO PRINTER PROMPT
ENDIF   
POP KEY
