PARAMETERS ASTAMPA
PUBLIC acslovima
PUSH KEY CLEAR
select fakg
IF FLSIFRA<>SPACE(5)
   MFLSIFRA=FLSIFRA
   USE AN0FIZLI IN 0 ORDER 1
   SELECT AN0FIZLI
   SEEK MFLSIFRA
   IF FOUND()
      AMFLSIFRA=FLSIFRA
      AMIMEPREZ=IME_PREZ
      AMJMBG=JMBG
      AMMESTO=MESTO
      AMULICA=ULICA
   ELSE
      AMFLSIFRA=' NEMA'
      AMIMEPREZ='NEMA'
      AMJMBG='NEMA'
      AMMESTO='NEMA'
      AMULICA='NEMA'
   ENDIF
   USE   
ENDIF
SELECT fak
      *REPORT FORM FAKDOSTAVAFL FOR BRKAL=MBRKAL PREVIEW 
      mfile='FAKDOSTAVAFL'
      uslov="BRKAL=MBRKAL"
      DO printer_bullzip WITH mdata02,mfile,uslov
      
SELECT FAK
POP KEY
