SELECT FAK
SET ORDER TO 1
MBRKAL=BRKAL
LOCATE FOR BRKAL=MBRKAL

*REPORT FORM FAK01BL FOR BRKAL=MBRKAL PREVIEW 
      mfile='FAK01BL'
      uslov="BRKAL=MBRKAL"
      DO printer_bullzip WITH mdata02,mfile,uslov

SELECT FAK
