PUSH KEY CLEAR
SELECT FAK
MRNAL=FAKG.RNAL
*SET ORDER TO 1
DO IDEL WITH (KKOCKAX)

SELECT FAK
COPY TO &KKOCKA FOR FAKG.RNAL=MRNAL
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
SELECT KOCKA
INDEX ON BRKAL TAG BRKAL
SET ORDER TO 1
SET RELATION TO BRKAL INTO FAKG ADDITIVE
SET RELATION TO RSIF INTO ROB ADDITIVE
GO TOP
   *REPORT FORM FAK20  PREVIEW 
      mfile='FAK20'
      uslov=""
      DO printer_bullzip WITH mdata02,mfile,uslov
   
SELECT KOCKA
SET RELATION TO
USE
SELECT FAK
POP KEY