PUSH KEY CLEAR
IF TNET=2
SELECT FAK
MBRKAL=BRKAL
MAKNJI=0
IF FAKG.BRNAL<>SPACE(6)
   *--------KOPIRANJE U TREBOVANJE--------------
   SELECT FAK
   SET RELATION TO
   DO IDEL WITH (KKOCKAX)
   KFAKT='FAKT'
   KFAKTG='FAKTG'
   USE &KFAKT IN 0 ALIAS FAKT
   SELECT FAKT
   COPY STRUCTURE TO &KKOCKA
   USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
   SELECT KOCKA
   INDEX ON Magacin TAG magacin
   SET ORDER TO 1   
   USE &KFAKTG IN 0 ALIAS FAKTG
   SELECT FAK
   SET ORDER TO 1
   LOCATE FOR BRKAL=MBRKAL

   IF FOUND()
      DO WHILE.NOT.EOF()
         IF BRKAL<>MBRKAL
            EXIT
         ENDIF
         SCATTER NAME POLJA
         SELECT kocka
         APPEND BLANK
         GATHER NAME POLJA
         REPLACE IZDATO WITH KOLI
         SELECT FAK
         SKIP
      ENDDO   
   ENDIF
   
   SELECT FAKG
   SET ORDER TO 1
   LOCATE FOR BRKAL=MBRKAL
   IF FOUND()
      REPLACE TREBOV WITH '*'
      SCATTER NAME POLJA
      SELECT FAKTG
      APPEND BLANK
      GATHER NAME POLJA
   ENDIF
   
   SELECT KOCKA
   GO TOP
   DO WHILE.NOT.EOF()
      SCATTER NAME POLJA
      SELECT FAKT
      APPEND BLANK
      GATHER NAME POLJA
      SELECT KOCKA
      SKIP
   ENDDO   
   
   SELECT KOCKA
   USE
   
   SELECT FAKT   
   USE
   
   SELECT FAKTG
   USE
   
   SELECT FAK
   DELETE ALL FOR BRKAL=MBRKAL
   PACK
   SELECT FAKG
   SET ORDER TO 1
LOCATE FOR BRKAL=MBRKAL
   SELECT FAK    
   *--------KRAJ KOPIRANJA U TREBOVANJE---------
   FAK.release
ELSE
   PUBLIC PPORUKA
   PPORUKA=' RAÈUN '+mBRKAL+' NEMA BROJA NALOGA '
   DO PORUKA
   SELECT FAK
ENDIF
ENDIF
POP KEY