m2brkal=brkal
KFAKT='FAKT'
KFAKTG='FAKTG'

DO IDEL WITH (KKOCKAX)
DO IDEL WITH (KKOCKAX2)

USE &KFAKTG IN 0 ALIAS FAKTG ORDER 1
SELECT FAKTG
COPY STRUCTURE TO &KKOCKA
USE &KKOCKA IN 0 ALIAS KOCKA EXCLUSIVE
USE &KFAKT IN 0 ALIAS FAKT ORDER 1
SELECT FAKT
COPY STRUCTURE TO &KKOCKA2
USE &KKOCKA2 IN 0 ALIAS KOCKA2 EXCLUSIVE
SELECT FAKTG
SEEK M2BRKAL
IF FOUND()
   SELECT FAKTG
   SCATTER NAME POLJA
   SELECT KOCKA    
   APPEND BLANK
   GATHER NAME POLJA
   REPLACE BRKAL WITH MBRKAL
   SELECT FAKTG
   REPLACE BRKAL WITH '999999'
   SELECT FAKT
   SEEK M2BRKAL
   IF FOUND()
      DO WHILE.NOT.EOF()
         IF BRKAL=M2BRKAL
            SCATTER NAME POLJA
            SELECT KOCKA2
            APPEND BLANK
            GATHER NAME POLJA
            REPLACE BRKAL WITH MBRKAL
            SELECT FAKT
            REPLACE BRKAL WITH '999999'
            SEEK M2BRKAL
            IF FOUND()
               LOOP
            ELSE
               EXIT
            ENDIF      
         ELSE
            EXIT
         ENDIF
         SKIP
      ENDDO   
   ENDIF
   SELECT KOCKA
   USE
   SELECT KOCKA2
   USE    
   SELECT FAK
   APPEND FROM &KKOCKA2
   SELECT FAKG
   APPEND FROM &KKOCKA
   replace fvrsta WITH '  1'
ELSE
   SELECT KOCKA
   USE
   SELECT KOCKA2
   USE
ENDIF
SELECT FAKT
USE
SELECT FAKTG
USE
SELECT FAK
FAKT02.RELEASE