PUSH KEY CLEAR
SELECT FAK
IF FAKG.ARHIVA=' '
   MBRKAL=BRKAL
   SELECT FAK
   SET ORDER TO 1
   LOCATE FOR BRKAL=MBRKAL

   IF FOUND()
      DO WHILE.NOT.EOF()
         IF BRKAL<>MBRKAL
            EXIT
         ENDIF
         MKOLI=KOLI
         IF TOBJEKAT='V'
            REPLACE CENA WITH ROB.PROSCENV 
            REPLACE VELCENA WITH ROB.VELCENA  
         ELSE
            REPLACE CENA WITH ROB.PROSCENM
            REPLACE MALCENA WITH ROB.MALCENA  
         ENDIF
  *       REPLACE ROB.KOL WITH ROB.KOL-MKOLI
         SELECT FAK
         DO FAKRAC
         SKIP
      ENDDO   
   ENDIF   
LOCATE FOR BRKAL=MBRKAL
   SET ORDER TO
   FAKSERV.RELEASE
   FAk.GRD0.SETFOCUS
   FAK.GRD0.REFRESH
ENDIF   
POP KEY
