PUSH KEY CLEAR
SET EXACT OFF
DO IDEL WITH (KKOCKAX)
DO IDEL WITH (KKOCKAX2)
SELECT FAK
MDATDOK=DATDOK
MAREC=RECNO()
COPY TO &KKOCKA FOR DATDOK=MDATDOK
USE &KKOCKA IN 0 ALIAS KOCKA EXCLUSIVE
SELECT KOCKA
INDEX ON BRKAL TAG BRKAL
SET ORDER TO 1
TOTAL ON BRKAL TO &KKOCKA2
DELETE ALL
PACK

APPEND FROM &KKOCKA2

GO TOP
DO WHILE.NOT.EOF()
   MBRKAL=BRKAL
   SELECT FAK
   SET ORDER TO 1
   LOCATE FOR BRKAL=MBRKAL

   IF FOUND()
      DO WHILE.NOT.EOF()
         IF BRKAL<>MBRKAL
            EXIT
         ENDIF
         *-----------------------------------------
         MRSIF=RSIF
         MKOL=0
         MKOLI=0
         MNABVREDU=0
         MNABVREDI=0
         MREC=RECNO()
         SELECT KAL
         SET ORDER TO 2
         SEEK MRSIF
         DO WHILE.NOT.EOF()
            IF RSIF<>MRSIF
               EXIT
            ENDIF
            IF DATDOK<=MDATDOK
               MKOL=MKOL+KOL
               MNABVREDU=MNABVREDU+NABVRED
            ENDIF
            SELECT KAL
            SKIP
         ENDDO   
         
         SELECT FAK
         SET ORDER TO 2
         SEEK MRSIF
         DO WHILE.NOT.EOF()
            IF RSIF<>MRSIF
               EXIT
            ENDIF
            IF DATDOK<=MDATDOK
               IF RECNO()<MREC
                  MKOLI=MKOLI+KOLI
                  MNABVREDI=MNABVREDI+IZNI
               ENDIF
            ENDIF      
            SKIP
         ENDDO   
         SELECT FAK
         SET ORDER TO 1
         GOTO MREC
         MSTANJE=MKOL-MKOLI
         MNABVRED=MNABVREDU-MNABVREDI
         IF MSTANJE<>0
            MNABCENA=ROUND(MNABVRED/MSTANJE,3)
         ELSE
            MNABCENA=1
         ENDIF
         REPLACE CENA WITH MNABCENA
         REPLACE IZNI WITH KOLI*MNABCENA
         DO FAKRAC
         GOTO MREC
         SKIP
      ENDDO
   ENDIF 
   SELECT KOCKA
   SKIP
ENDDO        
SELECT KOCKA
USE
SELECT FAK
GOTO MAREC
SET ORDER TO 
FAKSERV.RELEASE
FAk.GRD0.SETFOCUS
FAK.GRD0.REFRESH
POP KEY