PUSH KEY CLEAR
FAK.GRD0.COLUMN6.SETFOCUS
FAK.CMDFAKZBIR.SETFOCUS
MBRKAL=BRKAL
SELECT FAK
SET ORDER TO 
MBRKAL=BRKAL
SELECT FAK
SET ORDER TO 1
LOCATE FOR BRKAL=MBRKAL

IF FOUND()
   DO WHILE.NOT.EOF()
      IF BRKAL<>MBRKAL
         EXIT
      ENDIF
      DO FAKRAC   
      SKIP
   ENDDO   
ENDIF
LOCATE FOR BRKAL=MBRKAL
SET ORDER TO 
*REPORT FORM FAKZBIR0 PREVIEW FOR BRKAL=MBRKAL
      mfile='FAKZBIR0'
      uslov="BRKAL=MBRKAL"
      DO printer_bullzip WITH mdata02,mfile,uslov

SET ORDER TO 1
LOCATE FOR BRKAL=MBRKAL
SET ORDER TO 
FAK.GRD0.COLUMN6.SETFOCUS
POP KEY