PUSH KEY CLEAR
FAK.GRD0.COLUMN6.SETFOCUS
SELECT FAK
MMFF=FAKG.ARHIVA
IF FAKG.ARHIVA<>'*' 
   MBRKAL=BRKAL
   SET RELATION TO
   SELECT FAKG
   LOCATE FOR BRKAL=MBRKAL
   IF.NOT.FOUND()
      APPEND BLANK
      REPLACE BRKAL WITH MBRKAL
   ENDIF      
   DO FORM FAKZAGDOD
   SELECT FAK
   REPLACE DATDOK WITH FAKG.DATDOK    
   SET RELATION TO BRKAL INTO FAKG ADDITIVE
   SET RELATION TO RSIF INTO ROB ADDITIVE
   SELECT FAK
   SET ORDER TO 1
   LOCATE FOR BRKAL=MBRKAL
   SET ORDER TO 
ENDIF
FAK.GRD0.COLUMN3.SETFOCUS
POP KEY
FAK.REFRESH  
