PUSH KEY CLEAR
FAK.GRD0.COLUMN6.SETFOCUS
MREC=RECNO()
*REPORT FORM FAKZARADA0 PREVIEW FOR RECNO()=MREC
      mfile='FAKZARADA0'
      uslov="RECNO()=MREC"
      DO printer_bullzip WITH mdata02,mfile,uslov

SELECT FAK
POP KEY