PUSH KEY CLEAR
FAK.GRD0.COLUMN6.SETFOCUS
MBRKAL=BRKAL
USE &KFAZB IN 0 ALIAS KALZBIR EXCLUSIVE
SELECT KALZBIR
DELETE ALL
PACK


SELECT FAK
SET ORDER TO 1
LOCATE FOR BRKAL=MBRKAL

IF FOUND()
   MIZNI=0
   MRABAT=0
   MRABAT2=0
   MMARZA=0
   MVELVRED18=0
   MVELVRED8=0
   MPOREZ18=0
   MPOREZ8=0
   MMALVRED18=0
   MMALVRED8=0
   MFVRSTA=FAKG.FVRSTA
   MSIFRA=FAKG.SIFRA
   MBRRAC=FAKG.BRRAC
   MDATDOK=FAK.DATDOK
   MVALUTA=FAKG.VALUTA
   MPR1=FAKG.PR1
   MPV1=FAKG.PV1
   MPRDIN1=FAKG.PRDIN1
   MPR2=FAKG.PR2
   MPV2=FAKG.PV2
   MPRDIN2=FAKG.PRDIN2
   MPR3=FAKG.PR3
   MPV3=FAKG.PV3
   MPRDIN3=FAKG.PRDIN3
   MPR4=FAKG.PR4
   MPV4=FAKG.PV4
   MPRDIN4=FAKG.PRDIN4
   MPR5=FAKG.PR5
   MPV5=FAKG.PV5
   MPRDIN5=FAKG.PRDIN5
   MPR6=FAKG.PR6
   MPV6=FAKG.PV6
   MPRDIN6=FAKG.PRDIN6
   MPR7=FAKG.PR7
   MPV7=FAKG.PV7
   MPRDIN7=FAKG.PRDIN7
   MPR8=FAKG.PR8
   MPV8=FAKG.PV8
   MPRDIN8=FAKG.PRDIN8
   MPR9=FAKG.PR9
   MPV9=FAKG.PV9
   MPRDIN9=FAKG.PRDIN9
   MPR10=FAKG.PR10
   MPV10=FAKG.PV10
   MPRDIN10=FAKG.PRDIN10
   MPR11=FAKG.PR11
   MPV11=FAKG.PV11
   MPRDIN11=FAKG.PRDIN11
   MPR12=FAKG.PR12
   MPV12=FAKG.PV12
   MPRDIN12=FAKG.PRDIN12
   MRNAL=FAKG.RNAL
   MPBRKAL=FAKG.PBRKAL
   MPDOK=FAKG.PDOK
   MINTERNA=FAKG.INTERNA
   MPRENOS=FAKG.PRENOS
   MVPDV=FAKG.VPDV
   MoPDV=FAKG.oPDV
   MDEV=FAKG.DEV
   MDEVKURS=FAKG.DEVKURS
   MDEVIZNA=FAKG.DEVIZNA
   MNAZIV=AN0.NAZIV
   MOTPBR=FAKG.OTPBR
   MOTPDAT=FAKG.OTPDAT
   MPORBR=FAKG.PORBR
   MPORDAT=FAKG.PORDAT
   MNAPOMENAG=FAKG.NAPOMENAG
   MNAPOMENAD=FAKG.NAPOMENAD
   MPUTNIK=FAKG.PUTNIK
   MTOVARNI=FAKG.TOVARNI
   MNACIN=FAKG.NACIN
   MOTPREMA=FAKG.OTPREMA
   MVOZILO=FAKG.VOZILO
   MVOZAC=FAKG.VOZAC
   MCMR=FAKG.CMR
   MKASA=FAKG.KASA
   MKES=FAKG.KES
   MKARTICA=FAKG.KARTICA
   MCEK=FAKG.CEK
   MVIRMAN=FAKG.VIRMAN
   MAVANS=FAKG.AVANS
   MAVBRRAC=FAKG.AVBRRAC
   MAVDATDOK=FAKG.AVDATDOK
   MAVANS18=FAKG.AVANS18
   MAVANS8=FAKG.AVANS8
   MAVANSP18=FAKG.AVANSP18
   MAVANSP8=FAKG.AVANSP8
   MRELACOD=FAKG.RELACOD
   MRELACDO=FAKG.RELACDO
   MMODEL=FAKG.MODEL
   MOPDV=FAKG.OPDV
   MIDKARTICE=FAKG.IDKARTICE
   MMTR=FAKG.MTR
   





   DO WHILE.NOT.EOF()
      IF BRKAL<>MBRKAL
         EXIT
      ENDIF
      IF PROCPOR=VAL(TOSTOPA)
         MVELVRED18=MVELVRED18+VELVRED
         MMALVRED18=MMALVRED18+MALVRED
         MPOREZ18=MPOREZ18+POREZ
      ENDIF
      IF PROCPOR=VAL(TNSTOPA) 
         MVELVRED8=MVELVRED8+VELVRED
         MMALVRED8=MMALVRED8+MALVRED
         MPOREZ8=MPOREZ8+POREZ
      ENDIF
      MIZNi=MIZNi+IZNI
      MRABAT=MRABAT+RABAT
      MRABAT2=MRABAT2+RABAT2
      MMARZA=MMARZA+MARZA
      SKIP
   ENDDO   
ENDIF
SELECT FAK
LOCATE FOR BRKAL=MBRKAL
SELECT KALZBIR
APPEND BLANK
REPLACE BRKAL WITH MBRKAL
REPLACE IZNI WITH MIZNI
REPLACE RABAT WITH MRABAT
REPLACE RABAT2 WITH MRABAT2
REPLACE MARZA WITH MMARZA
REPLACE VELVRED18 WITH MVELVRED18
REPLACE VELVRED8 WITH MVELVRED8
REPLACE VELVRED WITH MVELVRED18+MVELVRED8
REPLACE POREZ18 WITH MPOREZ18
REPLACE POREZ8 WITH MPOREZ8
REPLACE POREZ WITH MPOREZ18+MPOREZ8
REPLACE MALVRED18 WITH MMALVRED18
REPLACE MALVRED8 WITH MMALVRED8
REPLACE MALVRED WITH MMALVRED18+MMALVRED8
REPLACE FVRSTA WITH MFVRSTA
REPLACE SIFRA WITH MSIFRA
REPLACE BRRAC WITH MBRRAC
REPLACE DATDOK WITH MDATDOK
REPLACE VALUTA WITH MVALUTA
REPLACE PR1 WITH MPR1
REPLACE PV1 WITH MPV1
REPLACE PRDIN1 WITH MPRDIN1
REPLACE PR1 WITH MPR1
REPLACE PV2 WITH MPV2
REPLACE PRDIN2 WITH MPRDIN2
REPLACE PR1 WITH MPR1
REPLACE PV3 WITH MPV3
REPLACE PRDIN3 WITH MPRDIN3
REPLACE PR1 WITH MPR1
REPLACE PV4 WITH MPV4
REPLACE PRDIN4 WITH MPRDIN4
REPLACE PR1 WITH MPR1
REPLACE PV5 WITH MPV5
REPLACE PRDIN5 WITH MPRDIN5
REPLACE PR1 WITH MPR1
REPLACE PV6 WITH MPV6
REPLACE PRDIN6 WITH MPRDIN6
REPLACE PR1 WITH MPR1
REPLACE PV7 WITH MPV7
REPLACE PRDIN7 WITH MPRDIN7
REPLACE PR1 WITH MPR1
REPLACE PV8 WITH MPV8
REPLACE PRDIN8 WITH MPRDIN8
REPLACE PR1 WITH MPR1
REPLACE PV9 WITH MPV9
REPLACE PRDIN9 WITH MPRDIN9
REPLACE PR1 WITH MPR1
REPLACE PV10 WITH MPV10
REPLACE PRDIN10 WITH MPRDIN10
REPLACE PR1 WITH MPR1
REPLACE PV11 WITH MPV11
REPLACE PRDIN11 WITH MPRDIN11
REPLACE PR1 WITH MPR1
REPLACE PV12 WITH MPV12
REPLACE PRDIN12 WITH MPRDIN12
REPLACE NAZIV WITH MNAZIV
REPLACE OTPBR WITH MOTPBR
REPLACE OTPDAT WITH MOTPDAT
REPLACE PORBR WITH MPORBR
REPLACE PORDAT WITH MPORDAT
REPLACE NAPOMENAG WITH MNAPOMENAG
REPLACE NAPOMENAD WITH MNAPOMENAD
REPLACE MODEL     WITH MMODEL
REPLACE PUTNIK WITH MPUTNIK
REPLACE TOVARNI WITH MTOVARNI
REPLACE NACIN WITH MNACIN
REPLACE OTPREMA WITH MOTPREMA
REPLACE VOZILO WITH MVOZILO
REPLACE VOZAC WITH MVOZAC
REPLACE CMR WITH MCMR
REPLACE KASA WITH MKASA
REPLACE KES WITH MKES
REPLACE KARTICA WITH MKARTICA
REPLACE CEK WITH MCEK
REPLACE VIRMAN WITH MVIRMAN
REPLACE AVANS WITH MAVANS
REPLACE AVBRRAC WITH MAVBRRAC
REPLACE AVDATDOK WITH MAVDATDOK
REPLACE AVANS18 WITH MAVANS18
REPLACE AVANS8 WITH MAVANS8
REPLACE AVANSP18 WITH MAVANSP18
REPLACE AVANSP8 WITH MAVANSP8
REPLACE RELACOD WITH MRELACOD
REPLACE RELACDO WITH MRELACDO
REPLACE MODEL WITH MMODEL
REPLACE OPDV WITH MOPDV
REPLACE IDKARTICE WITH MIDKARTICE
REPLACE MTR WITH MMTR


*SELECT FAK
*SET RELATION to
*USE
SELECT KALZBIR
GO top

*REPORT FORM FAKZBIR01 PREVIEW FOR BRKAL=MBRKAL 
      mfile='FAKZBIR01'
      uslov="BRKAL=MBRKAL"
      DO printer_bullzip WITH mdata02,mfile,uslov


SELECT KALZBIR
USE
*CLOSE ALL 
*FAK.RELEASE
*SET PROCEDURE TO TASTERI2
*   DO FAKTAST
*SET PROCEDURE TO
*
*DO FORM FAK WITH MBRKAL
SELECT FAK
POP KEY