PUSH KEY CLEAR
IF PPASAN=1
      SET ORDER TO 
      GO BOTTOM
      APPEND BLANK
      GO BOTTOM
      FAN0.REFRESH
      MSIFRA=STR(RECNO(),5,0)
      REPLACE SIFRA WITH MSIFRA
   MMCOUNT=0
   DO FORM AN0K2
   FAN0.GRD0A.RECORDSOURCE='AN0'
   FAN0.GRD0A.COLUMN2.SETFOCUS
   FAN0.REFRESH
ELSE
   PUBLIC PPORUKA
   PPORUKA=' NEMATE PRAVO DODAVANJA NOVIH PARTNERA '
   DO PORUKA 
ENDIF
POP KEY
