PUSH KEY CLEAR
IF PPASAN=1
   SELECT AN0
      SET ORDER TO 
      GO BOTTOM
      APPEND BLANK
      GO BOTTOM
      FAN02.GRD0A.REFRESH
      MSIFRA=STR(RECNO(),5,0)
      REPLACE SIFRA WITH MSIFRA
   MMCOUNT=0
   SELECT an0
   SET ORDER TO 
   GO bottom
   DO FORM AN0K2
   SELECT AN0
   SET ORDER TO 2
   FAN02.GRD0A.RECORDSOURCE='AN0'
   FAN02.GRD0A.COLUMN2.SETFOCUS
   FAN02.REFRESH
ELSE
   PUBLIC PPORUKA
   PPORUKA=' NEMATE PRAVO DODAVANJA NOVIH PARTNERA '
   DO PORUKA 
ENDIF
POP KEY


