PARAMETERS MPODATAK,MIMETABELE
mmpodatak = MPODATAK 
*SET STEP ON 
CLOSE TABLES ALL 
USE FINDTAB IN 0 EXCLUSIVE
SELECT FINDTAB
ZAP
USE
ON ERROR
USE FTABELE IN 0 exclu ALIAS tabele
SELECT TABELE
ZAP
IF MIMETABELE=SPACE(8)
  GTABELE = ADIR(ETABELE, '*.DBF') 
   FOR I = 1 TO GTABELE
      MPOLJE=ETABELE(I,1)
      SELECT TABELE
      APPEND BLANK
      REPLACE IMETAB WITH ALLTRIM(MPOLJE)
   ENDFOR
ELSE
   APPEND BLANK
   REPLACE IMETAB WITH ALLTRIM(MIMETABELE)+'.DBF'
ENDIF
GO TOP
DO WHILE.NOT.EOF()
   MIME=IMETAB
   MAT=AT('.',MIME)
   msime=SUBSTR(MIME,1,MAT-1)
   REPLACE IMETAB WITH msime
   IF MsIME='FTABELE'.OR.MsIME='FINDTAB'
      DELETE
   ENDIF
   SKIP
ENDDO
PACK
MREC=RECCOUNT()
GO TOP
DO WHILE.NOT.EOF()
   MIME=IMETAB
   USE (MIME) ALIAS TABELA IN 0
   SELECT TABELA
   brojpolja= afields(niz)
   mm0=''
   FOR I= 1 TO BROJPOLJA
      mm0=NIZ(I,1)	
      mm1=NIZ(I,2)	      
		FINDTAB.LBL1.CAPTION=MIME+' '+TRANSFORM(RECCOUNT()-RECNO(),'999999999')+'/'+TRANSFORM(RECCOUNT(),'999999999')+'/'+TRANSFORM(RECNO(),'999999999')+' '+MM0
		IF MM1 = "C" THEN 
			mcMD = [LOCATE FOR '] + ALLTRIM(UPPER(mmpodatak)) + [' $ UPPER(] + NIZ(I,1) + [)]
			EXECSCRIPT(mcmd)
			IF FOUND() THEN 
			    MREC=RECNO()
			    MM0A=&MM0
		        USE FINDTAB IN 0
			    SELECT FINDTAB
			    APPEND BLANK
			    REPLACE IME WITH MIME
			    REPLACE REDNIBROJ WITH MREC
			    REPLACE POLJE WITH MM0
			    REPLACE PODATAK WITH MM0A
			    USE
			    SELECT TABELA
			ENDIF 
		ENDIF 		
	next 
	SELECT TABELA
	USE
	SELECT TABELE
	SKIP
ENDDO	
SELECT TABELE
USE
