SELECT KOMANDE
KOMANDE.GRD0.SETFOCUS
GO TOP
MBROJ=0
DO WHILE.NOT.EOF()
   IF ZNAK<>' '
      MBROJ=MBROJ+1
   ENDIF      
   SKIP
ENDDO   
GO TOP
DIMENSION JOZA[MBROJ] 
BROJAC=0
DO WHILE.NOT.EOF()
   IF ZNAK<>' '
      BROJAC=BROJAC+1
      MCMD=ALLTRIM(KOMANDA)
      JOZA[BROJAC]=MCMD
   ENDIF
   SELECT KOMANDE
   SKIP
ENDDO   
FOR I=1 TO BROJAC
   MCMD=JOZA[I]
   EXECSCRIPT(MCMD)
NEXT
FTPPRENOS.RELEASE
KEYBOARD '{ENTER}'

