PUSH KEY CLEAR
IF MADODAJ=1
   GO BOTTOM
   IF FIRMA<>SPACE(30)
      APPEND BLANK
      REPLACE PSIFRA WITH RECNO()
      REPLACE SLIKE WITH '01'
      REPLACE fsnimi WITH '1'
      GLAVNA2.GRD0.SETFOCUS
   ENDIF
ELSE
   DO PORUKAU WITH ' RADITE U SERVISNOM REŽIMU-NE MOŽETE DODAVATI FIRME '
ENDIF
GLAVNA2.GRD0.REFRESH
POP KEY
GLAVNA2.REFRESH
