PUSH KEY CLEAR
IF OPERATER<>'1'
   PUBLIC PPORUKA
   PPORUKA=' NEMATE PRAVO PRISTUPA LOZINKAMA JER NISTE SUPERVIZOR '
   DO PORUKA 
ELSE
   CLOSE ALL TABLES
   PUSH KEY CLEAR
   DO FORM LOZINKES
   POP KEY
ENDIF
POP KEY