*SAVE SCREEN TO EKR
MH=mHELP
*@ 1,10 CLEAR TO 12,70
*@ 1,10 TO 12,70
define window POMOC FROM 1,10 TO 30,120 TITLE ' POMOC ZA AKTIVAN PROZOR '+MHELP STYLE 'B' PANEL
activate window pomoc
SET EXACT ON
DO CASE MH
CASE MH='GLAVNA'
@ 2,11 SAY ' GLAVNI MENI APLIKACIJE '
CASE MH='GLAVNA1'
@ 2,11 SAY ' UNOS SIFRE IDENTIFIKACIJA KORISNIKA '
CASE MH='GLAVNA2'
@ 2,11 SAY ' IZBOR FIRME - MESTA RADA '
@ 4,11 SAY ' +   DODAVANJE NOVE FIRME '
@ 5,11 SAY ' F7  KARTICA FIRME        '
@ 6,11 SAY ' F10 ULAZAK U FIRMU       '

CASE MH='GLAVNA3'
@ 2,11 SAY ' IZBOR GLAVNIH POSLOVA '

CASE MH='GLAVNA4'
@ 2,11 SAY ' IZBOR POSLOVA U FINANSIJAMA '

CASE MH='NALP'
@  2,11 SAY ' GLAVNA KNJIGA - IZRADA NALOGA'
@  4,11 say '       +  DODAVANJE '
@  5,11 SAY '       F4 KONTNI PLAN '
@  6,11 SAY '       F5 KNJIZENJE NALOGA '
@  7,11 SAY '       F6 ZATVARANJE NALOGA UKRSTENIM ZBIROM '
@  8,11 SAY '       F8 PREGLED NALOGA'
@  9,11 SAY '       F10 PRELAZAK U ANALITIKU AKO POSTOJI KONTO ANALITIKE '
@ 10,11 SAY ' Shift+F1  TABELA MESTA-GRADOVA  '
@ 11,11 SAY ' Shift+F2  TABELA MESTA TROSKOVA '
@ 12,11 SAY ' Shift+F10 BRISANJE PRAZNINA     '


CASE MH='NAL'
@  2,11 SAY ' DNEVNIK GLAVNE KNJIGE '
@  4,11 SAY '       F4 KONTNI PLAN '
@  5,11 SAY '       F5 TRAZENJE KONTA '
@  6,11 SAY '       F6 PREGLED KONTA '
@  7,11 SAY '       F7 TRAZENJE NALOGA '
@  8,11 SAY '       F8 PREGLED NALOGA'
@  9,11 SAY ' Shift+F1  TABELA MESTA-GRADOVA  '
@ 10,11 SAY ' Shift+F2  TABELA MESTA TROSKOVA '
@ 11,11 SAY ' Shift+F10 BRISANJE PRAZNINA     '
@ 12,11 SAY '   Alt+F1  IZVESTAJI             '
@ 13,11 SAY '   Alt+F2  RAZNE OPERACIJE       '


CASE MH='BLP'.OR.MH='BL'
@  2,11 SAY ' IZRADA DNEVNIKA BLAGAJNE'
@  4,11 say '       +  DODAVANJE '
@  5,11 SAY '       F4 KONTNI PLAN '
@  6,11 SAY '       F5 KNJIZENJE DNEVNIKA '
@  7,11 SAY '       F6 NALOG '
@  8,11 SAY '       F7 PRIZNANICA'
@  9,11 SAY '       F8 DNEVNIK   '
@ 10,11 SAY ' Shift+F1  TABELA MESTA-GRADOVA  '
@ 11,11 SAY ' Shift+F2  TABELA MESTA TROSKOVA '
@ 12,11 SAY ' Shift+F10 BRISANJE PRAZNINA     '




CASE MH='NALBROJ'
@  2,11 SAY ' ODREDJIVANJE BROJA NALOGA ZA KNJIZENJE '
@  4,11 SAY '       +  DODAVANJE NOVOG NALOGA '
@  5,11 SAY '       F7 KARTICA NALOGA         '

CASE MH='KONTO'.OR.MH='KONTO2'
@  2,11 SAY ' KONTNI PLAN '
@  4,11 SAY '       +  DODAVANJE NOVOG KONTA '
@  5,11 SAY '       F7 KARTICA KONTA         '


CASE MH='AN0'


@ 2,11 SAY ' GLAVNI SIFARNIK ANALITIKE '

@  4,11 SAY '       F6  TRAZENJE          '
@  5,11 SAY '       F10 ZBIRNA KARTICA    '
@  6,11 SAY '    Alt+F1 IZVESTAJI         '


CASE MH='ANP'


@ 2,11 SAY ' ANALITIKA-KNJIZENJE '


@  4,11 SAY '       F4  POSLOVNI PARTNERI '
@  5,11 SAY '       F5  KNJIZENJE  '
@  6,11 SAY '       F6  TRAZENJE SIFRE    '
@  7,11 SAY '       F7  KARTICA           '
@  8,11 SAY '       F9  UPLATE            '
@  9,11 SAY ' Shift+F1  MESTA-GRADOVI     '
@ 10,11 SAY ' Shift+F2  MESTA TROSKOVA    '
@ 11,11 SAY ' Shift+F3  DEVIZNI KURS      '
@ 12,11 SAY ' Shift+F10 BRISANJE PRAZNINA '




CASE MH='AN'


@ 2,11 SAY ' ANALITIKA-EVIDENCIJA '


@  4,11 SAY '       F4  POSLOVNI PARTNERI '
@  5,11 SAY '       F5             '
@  6,11 SAY '       F6  TRAZENJE SIFRE    '
@  7,11 SAY '       F7  KARTICA           '
@  8,11 SAY '       F9  UPLATE            '
@  9,11 SAY ' Shift+F1  MESTA-GRADOVI     '
@ 10,11 SAY ' Shift+F2  MESTA TROSKOVA    '
@ 11,11 SAY ' Shift+F3  DEVIZNI KURS      '
@ 12,11 SAY ' Shift+F10 BRISANJE PRAZNINA '
@ 13,11 SAY '   Alt+F1  IZVESTAJI         '

CASE MH='ANALK'
   @  2,11 SAY ' ANALITIKA-KARTICA PARTNERA '
   @  4,11 SAY '       F10 STAMPA SIROKO    '
   @  5,11 SAY '       F9  STAMPA USPRAVNO  '
   @  6,11 SAY '       F8  STAMPA DEVIZNO   '
   @  7,11 SAY '       F6  PROMENA REDOSLEDA'
   @  8,11 SAY '       ALT+F10 STAMPA SIROKO NEZATVORENO   '
   @  9,11 SAY '       ALT+F9  STAMPA USPRAVNO NEZATVORENO  '
   @ 10,11 SAY '       ALT+F8  STAMPA DEVIZNO  NEZATVORENO  '
   

CASE MH='ANALKSVE'
   @ 2,11 SAY ' ANALITIKA-SVE KARTICE PARTNERA '
   @ 4,11 SAY '       F9  STAMPA PO STRANAMA   '
   @ 5,11 SAY '       F10 STAMPA ZBIJENO       '

CASE MH='KASTOPE'
@  2,11 SAY ' KAMATNE STOPE '
@  4,11 say '       +  DODAVANJE '
@  5,11 SAY '       F10 KOEFICIJENTI        '
@  6,11 SAY ' Shift+F10 BRISANJE PRAZNINA   '

CASE MH='KAKOEF'
@  2,11 SAY ' KAMATNI KOEFICIJENTI '
@  4,11 say '       +  DODAVANJE      '
@  5,11 SAY '       F10 KOEFICIJENTI  '


CASE MH='KAMATE'
@  2,11 SAY ' EVIDENCIJA KAMATA            '
@  4,11 say '       F5  PRELAZAK U OBRACUN '
@  5,11 SAY '       F10 KAMATNI LIST       '

CASE MH='KAMOBRAC'
@  2,11 SAY ' EVIDENCIJA KAMATA            '
@  4,11 say '       F5  OBRACUN KAMATE     '



CASE MH='USL'

@ 2,11 SAY ' USLUGE '

@  4,11 SAY '       F3  KARTICA PARTNERA  '
@  5,11 SAY '       F4  SIFARNIK USLUGA   '
@  6,11 SAY '       F5  KNJIZENJE         '
@  7,11 SAY '       F6  TRAZENJE RAZNO    '
@  8,11 SAY '       F7  ZBIR RACUNA       '
@  9,11 SAY '       F9  ZAGLAVLJE         '
@ 10,11 SAY ' Shift+F1  MESTA-GRADOVI     '
@ 11,11 SAY ' Shift+F2  MESTA TROSKOVA    '
@ 12,11 SAY ' Shift+F3  DEVIZNI KURS      '
@ 13,11 SAY ' Shift+F10 BRISANJE PRAZNINA '


CASE MH='AANAL'.OR.MH='AAAN'.OR.MH='AABL'.OR.MH='AATV'.OR.MH='AATM'.OR.MH='AAKA'.OR.MH='AAUS'


@ 2,11 SAY ' IZBOR MESTA RADA '


@  4,11 SAY '       F7  OPSTA KARTA         '
@  5,11 SAY '       F10 IZBOR GLAVNE KNJIGE '


CASE MH='ROBA0'


@ 2,11 SAY ' ROBA - GLAVNI SIFARNIK '


@  4,11 SAY '       F4  TRAZI NAZIV           '
@  5,11 SAY '       F6  TRAZI SIFRU           '
@  6,11 SAY '       F7  OPSTA KARTICA         '

@  7,11 SAY '       F8  KARTICA ROBE          '
@  8,11 SAY '   Alt+F1  IZVESTAJI RAZNO       '
@  9,11 SAY '   Alt+F2  ODJAVA KONSIGNACIJE   '
@ 10,11 SAY '   Alt+F3  SREDJIVANJE ROBE      '
@ 11,11 SAY '   Alt+F4  ETIKETE               '
@ 12,11 SAY '   Alt+F5  POPISNA LISTA         '
@ 13,11 SAY '   Alt+F6  CENOVNIK              '
@ 14,11 SAY '   Alt+F7                        '
@ 15,11 SAY '   Alt+F8  PROMENA STOPE POREZA  '
@ 16,11 SAY '   Alt+F9  KOPRIRANJE ROBE       '
@ 17,11 SAY '   Alt+F10 PRENOS CENA U SIFARNIK'
@ 18,11 SAY '   CTRL+F1 NIVEELACIJA            '


CASE MH='KAL'.OR.MH='FAK'


@ 2,11 SAY ' KALKULACIJE - FAKTURE '

@  4,11 SAY '       F2  NOVI DOKUMENT     '
@  5,11 SAY '       F3  KARTICA PARTNERA  '
@  6,11 SAY '       F4  SIFARNIK ROBE     '
@  7,11 SAY '       F5  KNJIZENJE         '
@  8,11 SAY '       F6  TRAZENJE RAZNO    '
@  9,11 SAY '       F7  ZBIR              '
@ 10,11 SAY '       F8  KARTICA ROBE      '
@ 11,11 SAY '       F9  ZAGLAVLJE         '
@ 12,11 SAY '       F10 STAMPA            '

@ 13,11 SAY ' Shift+F1  MARZA               '
@ 14,11 SAY ' Shift+F2  RABAT               '
IF MH='KAL'
   @ 15,11 SAY ' Shift+F3  ZAVISNI TROSKOVI    '
   @ 16,11 SAY ' Shift+F4  TROSKOVI DOBAVLJACA '
ELSE
   @ 15,11 SAY ' Shift+F3  POREZ   '
   @ 16,11 SAY ' Shift+F4  MANIPULATIVNI TROSKOVI '
ENDIF
@ 17,11 SAY '   Alt+F1  IZVESTAJI           '
@ 18,11 SAY '   Alt+F2  PREGLEDI            '
@ 19,11 SAY '   Alt+F3  SERVIS              '
@ 20,11 SAY '   Alt+F4  PRENOS              '
@ 21,11 SAY '   Alt+F5  JEDNA STAVKA        '


CASE MH='NIV'


@ 2,11 SAY ' NIVELACIJE '


@  4,11 SAY '       F4  SIFARNIK ROBE     '
@  5,11 SAY '       F5  KNJIZENJE         '
@  6,11 SAY '       F6  TRAZENJE RAZNO    '
@  7,11 SAY '       F7  ZBIR              '
@  8,11 SAY '       F8  KARTICA ROBE      '
@  9,11 SAY '       F9  ZAGLAVLJE         '
@ 10,11 SAY '       F10 STAMPA            '

@ 11,11 SAY ' Shift+F1  MARZA               '

@ 12,11 SAY '   Alt+F1  IZVESTAJI           '
@ 13,11 SAY '   Alt+F3  SERVIS              '
@ 14,11 SAY '   Alt+F5  JEDNA STAVKA        '


CASE MH='FAN0'

@  2,11 SAY ' POSLOVNI PARTNERI '
@  4,11 SAY '       F4  TRAZENJE IMENA    '
@  5,11 SAY '       F6  TRAZENJE SIFRE    '
@  6,11 SAY '       F7  KARTICA           '

CASE MH='TM'

@  2,11 SAY ' KNJIGA PROMETA - TRGOVACKA KNJIGA '
@  4,11 SAY '       F7  ZBIR              '
@  5,11 SAY '       F10 PREGLED           '
@  6,11 SAY ' SHIFT+F10 BRISANJE PRAZNINA '


CASE MH='PP'

@  2,11 SAY ' KNJIGA POREZA NA PROMET '
@  4,11 SAY '       F7  ZBIR              '
@  4,11 SAY '       F8  SALDO PO TARIFAMA '
@  5,11 SAY '       F10 PREGLED           '
@  6,11 SAY ' SHIFT+F10 BRISANJE PRAZNINA '

CASE MH='TMP'

@  2,11 SAY ' KNJIGA PRIHODA I RASHODA '
@  4,11 SAY '       F7  ZBIR              '
@  4,11 SAY '       F8  JEDNA STAVKA      '
@  5,11 SAY '       F10 PREGLED           '
@  6,11 SAY ' SHIFT+F10 BRISANJE PRAZNINA '

CASE MH='ROBA'


@ 2,11 SAY ' SIFARNIK ROBE  '

@  7,11 SAY '       F4  TRAZENJE          '
@  8,11 SAY '       F7  OPSTA KARTA ROBE  '
@  9,11 SAY '       F10 IZBOR ROBE        '
@ 10,11 SAY '       F12 PRELAZAK U TABELU   '



CASE MH='FAKAR'


@ 2,11 SAY ' SIFARNIK PROIZVODA  '

@  7,11 SAY '       F4  TRAZENJE          '
@  8,11 SAY '       F7  OPSTA KARTA PROIZVODA  '
@  9,11 SAY '       F10 IZBOR PROIZVODA        '

CASE MH='ROBVRST'


@ 2,11 SAY ' SIFARNIK VRSTA ROBE '

@  7,11 SAY '       F4  TRAZENJE          '
@  8,11 SAY '       F7  OPSTA KARTA VRSTA ROBE  '
@  9,11 SAY '       F10 IZBOR VRSTA ROBE        '

CASE MH='ROBPROI'


@ 2,11 SAY ' SIFARNIK PROIAVODJACA '

@  7,11 SAY '       F4  TRAZENJE          '
@  8,11 SAY '       F7  OPSTA KARTA PROIZVODJACA'
@  9,11 SAY '       F10 IZBOR PROIZVODJACA      '



CASE MH='KALIZV2'


@ 2,11 SAY ' IZVESTAJI PO KALKULACIJAMA  '

@  8,11 SAY '       F7  ZBIR              '
@  9,11 SAY '       F8  SALDO KALKULACIJA '
@ 10,11 SAY '       F9  SALDO NALOGA      '


CASE MH='LD'


@ 2,11 SAY ' OBRACUN ZARADA '


@  4,11 SAY '       F4  TRAZI IME         '
@  5,11 SAY '       F5  TRAZI KOLONU      '
@  6,11 SAY '       F6  TRAZI SIFRU       '
@  7,11 SAY '       F7  KARTICA           '
@  8,11 SAY '       F8  POPUNI KOLONU     '
@  9,11 SAY '       F9  DOTACIJA          '
@ 10,11 SAY '       F10 OBRACUN           '
@ 11,11 SAY ' Shift+F1  AKONTACIJA        '
@ 12,11 SAY ' Shift+F2  PRENOS KREDITA    '
@ 13,11 SAY ' Shift+F3  JEDAN LISTIC      '
@ 14,11 SAY ' Shift+F4  SVI LISTICI       '


CASE MH='LDVIRM'


@ 2,11 SAY ' VIRMANI ZA PLATE '

@  4,11 SAY '       F2  POPUNJAVANJE VIRMANA        '
@  5,11 SAY '       F3  UNOS DATUMA I SVRHE DOZNAKE '
@  6,11 SAY '       F8  TRAKA                       '
@  7,11 SAY '       F9  STAMPA JEDNOG VIRMANA       '
@  8,11 SAY '       F10 STAMPA SVIH VIRMANA         '


CASE MH='US0'


@ 2,11 SAY ' SIFARNIK USLUGA  '

@  7,11 SAY '       F4  TRAZENJE          '
@  8,11 SAY '       F7  OPSTA KARTA USLUGA  '
@  9,11 SAY '       F10 IZBOR USLUGE        '
@ 10,11 SAY '       F12 PRELAZAK U TABELU   '

CASE MH='CEKOVI'


@ 2,11 SAY ' CEKOVI GRADJANA'

@  3,11 SAY '       +   DODAVANJE         '
@  4,11 SAY '       F4  POSLOVNI PARTNERI '
@  5,11 SAY '       F9  STAMPA            '

OTHERWISE
@ 2,11 SAY ' NIJE OBEZBEDJENA POMOC '
ENDCASE
INKEY(0)
release window pomoc
SET EXACT OFF
*RESTORE SCREEN FROM EKR
