PUSH KEY CLEAR
PUBLIC MREDREC
SELECT HEPON
MREDREC=RECNO()
HEPON.GRD0.COLUMN5.SETFOCUS
MBRKAL=BRKAL
DO FORM ROBA
SELECT HEPON
SET ORDER TO 1
LOCATE FOR BRKAL=MBRKAL

SET ORDER TO 
GOTO MREDREC
HEPON.GRD0.SETFOCUS
HEPON.GRD0.REFRESH
POP KEY
