PUSH KEY CLEAR
HEPON.GRD0.COLUMN1.SETFOCUS
IF RECCOUNT()>0
   *---AKO KALKULACIJA POSTOJI
   IF HEPONG.ARHIVA=' '
      *---AKO NIJE ARHIVIRANA-----
      MBRKAL=BRKAL
      *MDATDOK=DATDOK
      APPEND BLANK
      REPLACE BRKAL WITH MBRKAL 
      *REPLACE DATDOK WITH MDATDOK
      HEPON.GRD0.SETFOCUS
      HEPON.REFRESH
   ELSE
      *------AKO JE KALKULACIJA  ARHIVIRANA
      SELECT HEPON
      SET RELATION TO
      SET ORDER TO 1 
      GO BOTTOM
      MBRKAL=BRKAL
      MNLEN=LEN(ALLTRIM(STR(VAL(ALLTRIM(MBRKAL))+1,6,0)))
      MNBRKAL=REPLI('0',6-MNLEN)+ALLTRIM(STR(VAL(ALLTRIM(MBRKAL))+1,6,0))
      SET ORDER TO 1
            LOCATE FOR BRKAL=MNBRKAL

      IF.NOT.FOUND()
         APPEND BLANK
         REPLACE BRKAL WITH MNBRKAL 
         HEPON.GRD0.SETFOCUS
         HEPON.GRD0.REFRESH
         HEPON.REFRESH
      ENDIF
      SELECT HEPONG
            LOCATE FOR BRKAL=MNBRKAL

      IF.NOT.FOUND()
         APPEND BLANK
         REPLACE BRKAL WITH MNBRKAL
      ENDIF      
      DO FORM HEPONZAG
      SELECT HEPON
            LOCATE FOR BRKAL=MNBRKAL

      SET RELATION TO BRKAL INTO HEPONG ADDITIVE
      SET RELATION TO RSIF INTO ROB ADDITIVE
*      REPLACE DATDOK WITH FAKG.DATDOK    
      SET ORDER TO 
   ENDIF 
ELSE
   *--------AKO PRVA STAVKA NE POSTOJI---------
   APPEND BLANK
   MNBRKAL='000001'
   REPLACE BRKAL WITH MNBRKAL 
   *------IDEMO U ZAGLAVLJE
   IF .NOT.FOUND()
      SELECT HEPON
      SET RELATION TO
      SELECT HEPONG
            LOCATE FOR BRKAL=MNBRKAL

      IF.NOT.FOUND()
         APPEND BLANK
         REPLACE BRKAL WITH MNBRKAL
      ENDIF     
      DO FORM HEPONZAG
      SELECT HEPON
      SET RELATION TO BRKAL INTO HEPONG ADDITIVE
      SET RELATION TO RSIF INTO ROB ADDITIVE
   *   REPLACE DATDOK WITH FAKG.DATDOK
   ENDIF   
ENDIF    

SELECT HEPON
SET ORDER TO
HEPON.GRD0.COLUMN3.SETFOCUS
POP KEY
HEPON.REFRESH  
