PROCEDURE IIND
   PARAMETERS AIND,AP1,AP2,AP3,AP4,AP5,AP6,AP7,AP8,AP9,AP10,AP11
   PUSH KEY CLEAR
   ON ERROR
   PRIVATE EMMAP
   
*   SET STEP ON 
   SET EXACT ON
   MPARAM=PARAMETERS()
   MMAP1=AP1
   MMAP2=AP2
   MMAP3=AP3
   MMAP4=AP4
   MMAP5=AP5
   MMAP6=AP6
   MMAP7=AP7
   MMAP8=AP8
   MMAP9=AP9
   MMAP10=AP10
   MIMA=AIND+'.CDX'
   MAIND=AIND+'.DBF'
   IF FILE(MAIND)
   IF !FILE(MIMA)
      USE &AIND IN 0 ALIAS IND  exclu
     
      SELECT IND

      FOR AI=1 TO MPARAM-1
         EMAP='MMAP'+ALLTRIM(STR(AI,2,0))
         EMMAP=&EMAP

         IF EMMAP<>''
            INDEX ON &EMMAP TAG &EMAP ADDITIVE
         ELSE
            AI=11
         ENDIF
      NEXT
      USE
   ENDIF
   ENDIF
   SET EXACT OFF
   POP KEY
   ON ERROR DO GRESKE WITH ;
   ERROR( ), MESSAGE( ), MESSAGE(1), PROGRAM( ), LINENO( )   
ENDPROC
