PUSH KEY CLEAR
IF PPASOS=1
   SELECT AN0
   APPEND BLANK
   REPLACE OSIFRA WITH STR(RECNO(),4,0)
   INVEST0.GRD0.SETFOCUS
   DO INVEST0KART
   INVEST0.GRD0.SETFOCUS   
   INVEST0.REFRESH
ELSE
   PUBLIC PPORUKA
   PPORUKA=' NEMATE PRAVO DODAVANJA NOVIH INVESTICIJA '
   DO PORUKA 
ENDIF
POP KEY