PUSH KEY CLEAR
   SET ORDER TO 
   IF RECCOUNT()>0
      MBRNAL=BRNAL
      MDATDOK=DATDOK
      MVALUTA=VALUTA
      APPEND BLANK
      REPLACE BRNAL WITH MBRNAL
      REPLACE DATDOK WITH MDATDOK
      REPLACE VALUTA WITH MVALUTA
      REPLACE OPER WITH OPERATER
      REPLACE DATUM WITH DATE()
      REPLACE VREME WITH TIME()   
      invest.GRD0.SETFOCUS
      invest.REFRESH
   ELSE
      APPEND BLANK
      REPLACE DATDOK WITH DATE()
   ENDIF
   invest.GRD0.COLUMN1.SETFOCUS
   invest.REFRESH  
POP KEY