SELECT VP
MPIB=PIB
MGRUPA=GRUPA
*MPREZ=PREZ
*MIME=IME
MIME_prez=ime_prez
*SET STEP ON 
*-----------TABELA OBRACUNA------------
select VPOBRAC
MCENOVNIK=CENOVNIK
MBROBRAC=BROBRAC
*SET STEP ON 
*------TABELA CENA
select VPCENE
SET ORDER TO 1
SEEK MCENOVNIK
mpstanje=pstanje
mzstanje=zstanje
APOC='ST'+ALLTRIM(STR(MPSTANJE,2,0))
AKRAJ='ST'+ALLTRIM(STR(MZSTANJE,2,0))
MMES=MZSTANJE-MPSTANJE
mEdatum=datum
mEvaluta=valuta
mdatOD2=DTOS(datod)
mdatDO2=DTOS(datdo)
mdatOD=datod
mdatDO=datdo
mcvoda=cvoda
mcDOPV=CDOPV
mckanal=ckanal
mcdOPK=cdOPK
MRABPROC=RABPROC
MPAUSALDO=PAUSALDO
MPAUSALkan=PAUSALKAN
MPAUSALCENA=PAUSALCENA
mprocakont=procakont
MBRNAL='PLO'+ALLTRIM(STR(MBROBRAC,2,0))+MGRUPA
MPRDUG=0
mcvoda=cvoda
mcDOPV=CDOPV
mckanal=ckanal
mcdOPK=cdOPK
MCSMECE=CSMECE
MCodrz=Codrz
MPPOVODA=PPOVODA
MPPOKANAL=PPOKANAL
MPPOSMECE=PPOSMECE
MPPOodrz=PPOODRZ

SELECT VP
IF POPUST<>' '
   IMARABAT=1
ELSE
   IMARABAT=0
ENDIF   
SELECT VP

*---------POCETNI POODACI
   SELECT VP  
   REPLACE DATDOK WITH MEDATUM
   REPLACE DATUM WITH MEDATUM
   REPLACE VALUTA WITH MEVALUTA
   REPLACE BRNAL WITH MBRNAL
   REPLACE MES WITH MMES
*--------OBRACUN PAUSAL------------------

   IF PAUSAL=' '
      REPLACE POT WITH &AKRAJ-&APOC
      MPOT=POT
   ELSE
      REPLACE POT WITH MMES*MESPAUSAL
      MPOT=POT
   ENDIF
   IF POT<0
      REPLACE POT WITH 0
      MPOT=POT
   ENDIF   
   REPLACE POC WITH &APOC
   REPLACE KRAJ WITH &AKRAJ
   REPLACE UKPOT WITH MPOT
   REPLACE VODA WITH 0
   REPLACE CENOVNIK WITH MCENOVNIK

*------------OBRACUN ZA VODU------------------   
*      IF PVODA<>' '
*         IF POPVODA<>0
*            MSOCVODA=ROUND(POT*MCVODA,2)
*         ELSE
*            MSOCVODA=0
*         ENDIF
*         REPLACE VODA WITH ROUND(POT*MCVODA,2)
*         REPLACE DOPV WITH ROUND(POT*MCDOPV,2)
*         REPLACE PORVODA WITH ROUND(MPPOVODA*VODA/100,2)
*      ELSE
 *        MSOCVODA=0
         REPLACE VODA WITH 0
         REPLACE DOPV WITH 0
         REPLACE PORVODA WITH 0
         MPORVODA8=0
         MPORVODA18=0
         MOSNVODA0=0
         MOSNVODA8=0
         MOSNVODA18=0
 *     ENDIF
   REPLACE KANAL WITH 0
   REPLACE DOPK WITH 0   
   REPLACE PORKANAL WITH 0

*------------OBRACUN ZA KANALIZACIJU
      IF PKANAL<>' '
         REPLACE KANAL WITH ROUND(MMES*MCKANAL,2)
         REPLACE DOPK WITH ROUND(KANAL*MCDOPK/100,2)
         REPLACE PORKANAL WITH ROUND(MPPOKANAL*KANAL/100,2)
      ENDIF
*------------OBRACUN ZA KANALIZACIJU
      IF PVODA<>' '
         REPLACE KANAL WITH ROUND(MMES*Mpausalkan,2)
         REPLACE DOPK WITH ROUND(KANAL*MCDOPK/100,2)
         REPLACE PORKANAL WITH ROUND(MPPOKANAL*KANAL/100,2)
      ENDIF
*------------OBRACUN ZA SMECE
IF PSMECE<>' '
  * IF POPSMECE<>0
  *    MSOCSMECE=ROUND(POV*MCSMECE*MMES,2)
  * ELSE
  * MSOCSMECE=0
  * MSOCSMECEP=0
  * ENDIF
   IF POV<=MPAUSALDO
      MPAUSALDIN=ROUND(MPAUSALCENA*MMES,2)
      MSMECE=0
   ELSE   
      MPAUSALDIN=0
      MSMECE=ROUND((POV)*MCSMECE*MMES,2)
   ENDIF
   REPLACE PAUSALDIN WITH  MPAUSALDIN
   REPLACE SMECE WITH  MSMECE      
   REPLACE PORSMECE WITH ROUND(MPPOSMECE*(SMECE+PAUSALDIN)/100,2)
ELSE
   REPLACE SMECE WITH 0
   REPLACE PAUSALDIN WITH 0
   REPLACE PORSMECE WITH 0
   MPAUSALDIN=0
ENDIF

*------------OBRACUN ZA  ODRZAVANJE
IF PSMECE<>' '
   REPLACE ODRZ WITH ROUND(CODRZ*MMES,2)
   REPLACE PORODRZ WITH ROUND(MPPOODRZ*ODRZ/100,2)
ELSE
   REPLACE odrz WITH 0
   REPLACE PORODRZ WITH 0
ENDIF

*---------RASPODELA PORESKIH STOPA I OSNOVICA-----------------
MPORVODA8=0
MPORVODA18=0
MOSNVODA0=0
MOSNVODA8=0
MOSNVODA18=0
MPORKANAL8=0
MPORKANAL18=0
MOSNKANAL0=0
MOSNKANAL8=0
MOSNKANAL18=0
MPORSMECE8=0
MOSNSMECE8=0
MPORSMECE18=0
MOSNSMECE18=0
MOSNSMECE0=0
MPORodrz8=0
MOSNodrz8=0
MPORodrz18=0
MOSNodrz18=0
MOSNodrz0=0

IF MPPOVODA<>0
   IF MPPOVODA=VAL(TNSTOPA)
      MPORVODA8=PORVODA
      MOSNVODA8=VODA
      MOSNVODA0=DOPV
   ENDIF
   IF MPPOVODA=VAL(TOSTOPA)
      MPORVODA18=PORVODA
      MOSNVODA18=VODA
      MOSNVODA0=DOPV
   ENDIF      
ELSE
   MOSNVODA0=VODA+DOPV
ENDIF

IF MPPOKANAL<>0
   IF MPPOKANAL=VAL(TNSTOPA)
      MPORKANAL8=PORKANAL
      MOSNKANAL8=KANAL
      MOSNKANAL0=DOPK
   ENDIF
   IF MPPOKANAL=VAL(TOSTOPA)
      MPORKANAL18=PORKANAL
      MOSNKANAL18=KANAL
      MOSNKANAL0=DOPK
   ENDIF      
ELSE
   MOSNKANAL0=KANAL+DOPK
ENDIF
   
   
IF MPPOSMECE<>0
   IF MPPOSMECE=VAL(TNSTOPA)
      MPORSMECE8=PORSMECE
      MOSNSMECE8=SMECE+PAUSALDIN
   ENDIF
   IF MPPOSMECE=VAL(TOSTOPA)
      MPORSMECE18=PORSMECE
      MOSNSMECE18=SMECE+PAUSALDIN
   ENDIF      
ELSE
   MOSNSMECE0=SMECE
ENDIF

IF MPPOodrz<>0
   IF MPPOodrz=VAL(TNSTOPA)
      MPORodrz8=PORODRZ
      MOSNodrz8=ODRZ
   ENDIF
   IF MPPOodrz=VAL(TOSTOPA)
      MPORodrz18=PORODRZ
      MOSNodrz18=ODRZ
   ENDIF
ELSE
   MOSNodrz0=ODRZ
ENDIF   


MPOR8=MPORVODA8+MPORKANAL8+MPORSMECE8+MPORodrz8
MOSN8=MOSNVODA8+MOSNKANAL8+MOSNSMECE8+MOSNodrz8
MPOR18=MPORVODA18+MPORKANAL18+MPORSMECE18+MPORodrz18
MOSN18=MOSNVODA18+MOSNKANAL18+MOSNSMECE18+MOSNodrz18
MOSN0=MOSNVODA0+MOSNKANAL0+MOSNSMECE0+MOSNodrz0

REPLACE OSN0 WITH MOSN0
REPLACE OSN8 WITH MOSN8
REPLACE OSN18 WITH MOSN18
REPLACE POR8 WITH MPOR8
REPLACE POR18 WITH MPOR18
*REPLACE SOC WITH -(MSOCVODA+MSOCKANAL+MSOCSMECE)
*-------OBRACUN RABATA-----------------   
   REPLACE MESECI WITH MMES      
   IF IMARABAT=1
      MRABOSNOV=VODA+DOPV+KANAL+DOPK+SMECE+PAUSALDIN
   ELSE
      MRABOSNOV=0
   ENDIF      
   IF MRABOSNOV>0
      MRABAT=ROUND(MRABOSNOV*MRABPROC/100,2)
   ELSE
      MRABAT=0
   ENDIF
   REPLACE RABAT WITH MRABAT
*----KRAJ RABATA------------------------

*----OBRACUN UKUPNO---------------------
   MUKUPNO=VODA+DOPV+KANAL+DOPK+SMECE+ODRZ+PAUSALDIN
   REPLACE POREZ WITH PORVODA+PORKANAL+PORSMECE+porodrz
   REPLACE UKUPNO WITH MUKUPNO+POREZ
   REPLACE SVEGA WITH UKUPNO-RABAT
*----------POPUNJAVANJE GLAVNE TABELE----------
   SELECT vp
   MSALDO=SVEGA
   IF MSALDO>INT(MSALDO)
      MZAOKRUZ=MSALDO-INT(MSALDO)
   ELSE
      MZAOKRUZ=-(MSALDO-INT(MSALDO))
   ENDIF 
   REPLACE ZAOKRUZ WITH -MZAOKRUZ
   REPLACE SALDO WITH MSALDO-MZAOKRUZ
   SET CENTURY OFF
   mbrrac=REPLICATE('0',2-LEN(ALLTRIM(STR(MBROBRAC,2,0))))+ALLTRIM(STR(MBROBRAC,2,0))+SUBSTR(DTOC(MDATDO),7,2)+ALLTRIM(pib)
   SET CENTURY ON
   REPLACE BRRAC WITH MBRRAC
   REPLACE BRNAL WITH MBRNAL
   M1=VAL(mbrrac)
   M2=(M1*100/97)-INT(M1*100/97)
   M3=ROUND(97*M2,0)
   M4=98-M3
   IF M4<=9
      M4='0'+STR(M4,1,0)
   ELSE
      M4=STR(M4,2,0)
   ENDIF      
   REPLACE model WITH +M4+'-'+ALLTRIM(mbrrac)
   
   SELECT vpUPLD
   SET ORDER TO 5
   SET EXACT OFF
   GO TOP
   DO WHILE.T.
      SEEK MBRRAC
      IF FOUND()
         REPLACE PIB WITH SPACE(13)
         REPLACE BRNAL WITH SPACE(6)
         REPLACE BRRAC WITH ''
         REPLACE GRUPA WITH ''
         REPLACE CENOVNIK WITH 0
         REPLACE DATUM WITH CTOD('')
         REPLACE VALUTA WITH CTOD('')
         REPLACE DATOD WITH CTOD('')
         REPLACE DATDO WITH CTOD('')
         REPLACE CVODA WITH 0
         REPLACE CDOPV WITH 0
         REPLACE CKANAL WITH 0
         REPLACE CDOPK WITH 0
         REPLACE CSMECE WITH 0
         REPLACE CODRZ WITH 0
         REPLACE PAUSALDO WITH 0
         REPLACE PAUSALCENA WITH 0
         REPLACE PAUSALkan WITH 0

         REPLACE PPOVODA WITH 0
         REPLACE PPOKANAL WITH 0
         REPLACE PPOSMECE WITH 0
         REPLACE PPOodrz WITH 0
         
         REPLACE POREZ WITH 0
         REPLACE PORVODA WITH 0
         REPLACE PORKANAL WITH 0
         REPLACE PORSMECE WITH 0
         REPLACE PORodrz WITH 0

         REPLACE VODA WITH 0
         REPLACE DOPV WITH 0
         REPLACE KANAL WITH 0
         REPLACE DOPK WITH 0
         REPLACE SMECE WITH 0
         REPLACE ODRZ WITH 0
         
         REPLACE UKUPNO WITH 0
         REPLACE OSTALO WITH 0
         REPLACE SPORAZUM WITH 0
         REPLACE KAMATA WITH 0
         REPLACE POREZ WITH 0
         REPLACE POC WITH 0
         REPLACE KRAJ WITH 0
         REPLACE POT WITH 0
         REPLACE RABAT WITH 0
         REPLACE DUG WITH 0
         REPLACE SALDO WITH 0
         REPLACE ZAOKRUZ WITH 0
         REPLACE SVEGA WITH 0
         REPLACE OSN0 WITH 0
         REPLACE OSN8 WITH 0
         REPLACE OSN18 WITH 0
         REPLACE POR8 WITH 0
         REPLACE POR18 WITH 0
         LOOP 
      ELSE
         EXIT
      ENDIF
   ENDDO   
  
   SELECT vp
   MGRUPA=GRUPA
   MDATDOK=DATDOK
   MVALUTA=VALUTA
   MPAUSAL=PAUSAL
   MMESPAUSAL=MESPAUSAL
   MMES=MES
   MVODA=VODA
   MDOPV=DOPV
   MKANAL=KANAL
   MDOPK=DOPK
   MSMECE=SMECE
   MODRZ=ODRZ
      
   MPORVODA =PORVODA
   MPORKANAL=PORKANAL
   MPORSMECE=PORSMECE
   MPORODrz=PORODRZ

   MUKUPNO=UKUPNO
   MOSTALO=OSTALO
   MZAOKRUZ=ZAOKRUZ
   
   mdug=dug
   MSVEGA=SVEGA
   MUPLAC=UPLAC
   MPOREZ=POREZ
   MSOC=SOC
   MKAMATA=KAMATA
   MBRRAC=BRRAC
   MMODEL=MODEL
   MRABAT=RABAT
   MPOC=POC
   MKRAJ=KRAJ
   MPOT=POT
   MPVODA=PVODA
   MPKANAL=PKANAL
   MPSMECE=PSMECE
   MpODRZ=PODRZ
   MPOV =POV

   MPOPVODA=POPVODA
   MPOPKAN=POPKAN
   MPOPSMECE=POPSMECE
   MBRSTAN=BRSTAN
   MUKSTAN=UKSTAN
   MDOMAC=DOMAC
   MKS=KS
   MKSSIFRA=KSSIFRA
   MVRSTA=VRSTA
   MULICA=ULICA
*   MIME_PREZ=ALLTRIM(PREZ)+' '+IME
   MRABAT=RABAT   
   mdatcit=datcit
   *-------CENE-----------------
   REPLACE Cvoda WITH Mcvoda
   REPLACE cDOPV WITH MCDOPV
   REPLACE ckanal WITH Mckanal
   REPLACE cdOPK WITH McdOPK
   REPLACE CSMECE WITH MCSMECE
   REPLACE CODRZ WITH MCODRZ 
   REPLACE PAUSALDO WITH MPAUSALDO
   REPLACE PAUSALCENA WITH MPAUSALCENA
   REPLACE PAUSALDIN WITH MPAUSALDIN   
   replace pausalkan WITH mpausalkan
   *--------STOPE POREZA-------
   REPLACE PPOVODA WITH MPPOVODA
   REPLACE PPOKANAL WITH MPPOKANAL
   REPLACE PPOSMECE WITH MPPOSMECE
   REPLACE PPOodrz WITH MPPOodrz
   *----------POREZ------------
   REPLACE PORVODA  WITH MPORVODA
   REPLACE PORKANAL WITH MPORKANAL
   REPLACE PORSMECE WITH MPORSMECE
   REPLACE PORodrz WITH MPORodrz
   REPLACE DATOD WITH MDATOD
   REPLACE DATDO WITH MDATDO
   
   REPLACE OSN0 WITH MOSN0
   REPLACE OSN8 WITH MOSN8
   REPLACE OSN18 WITH MOSN18
   REPLACE POR8 WITH MPOR8
   REPLACE POR18 WITH MPOR18
   REPLACE POSTA WITH AN0.POSTA
   REPLACE MESTO WITH AN0.MESTO
   REPLACE ULICA0 WITH AN0.ULICA
   REPLACE ULBROJ0 WITH AN0.ULBROJ
   REPLACE MES WITH MMES
   SCATTER NAME POLJA
*---------DODAVANJE POLJA-----------
   SELECT VPUPLD
   APPEND BLANK
   GATHER NAME POLJA
   SELECT VP
