PROCEDURE JBATAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       JBA.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE AKOMUN00TAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   AKOMUN00.RELEASE
ENDPROC
 
PROCEDURE VKAKOEFTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL ESC       VKAKOEF.RELEASE
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL F10       DO KAKOEFKOEF 
ENDPROC
 
PROCEDURE JBUPLTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       JBUPL.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE JBUPLDTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       JBUPLD.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE JBUPLDFTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       JBUPLDF.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC


PROCEDURE JBPODTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       JBPOD.RELEASE
ENDPROC

PROCEDURE JBAFTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       JBAF.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE JBPODFTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       JBPODF.RELEASE
ENDPROC


PROCEDURE JB0TAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   JB0.RELEASE
ENDPROC


PROCEDURE JBSUD0TAST
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   JBSUD0.RELEASE
ENDPROC

PROCEDURE JBSUDTAST
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   JBSUD.RELEASE
ENDPROC

PROCEDURE JBSUD0DODRACTAST
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   JBSUD0DODRAC.RELEASE
ENDPROC

PROCEDURE JBANALIZVOTAST
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   JBANALIZVO.RELEASE
ENDPROC


PROCEDURE VT0TAST
   ON KEY LABEL F1    DO HELPN WITH 'VT0'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VT0.RELEASE
   ON KEY LABEL F2        ! /N CALC.EXE
ENDPROC


PROCEDURE JBKAKOEFTAST
   ON KEY LABEL F1    DO HELPN WITH 'JBKAKOEF'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JBKAKOEF.RELEASE
   ON KEY LABEL F2        ! /N CALC.EXE
ENDPROC

PROCEDURE VKKAKOEFTAST
   ON KEY LABEL F1    DO HELPN WITH 'VKKAKOEF'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VKKAKOEF.RELEASE
   ON KEY LABEL F2        ! /N CALC.EXE
ENDPROC

PROCEDURE JBFAN0TAST

ON KEY LABEL F1    DO HELPN WITH 'FAN0'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       FAN0.RELEASE
ON KEY LABEL +         DO FAN0DOD
on key label INS       DO FAN0DOD
ON KEY LABEL F3        DO FAN0DEONAZ
ON KEY LABEL ALT+F3        DO FAN0TEKRAC
ON KEY LABEL F4        DO FAN0TRAZI
ON KEY LABEL F5        DO FAN0GR5TRAZI
ON KEY LABEL F6        DO FAN0TRAZIF6
ON KEY LABEL F7        DO FAN0KARTF7
ON KEY LABEL F8        DO FAN0ZIROTRAZI
ON KEY LABEL CTRL+F12  DO OTVFAN0
ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC

ENDPROC


PROCEDURE HELPNTAST
   ON KEY LABEL ESC       HELPN.RELEASE
   ON KEY LABEL F1    ON KEY
   ON KEY LABEL CTRL+F12  HELPN.GRD0.READONLY=.F.
ENDPROC

PROCEDURE NCALCTAST
ON KEY LABEL F1    DO HELPN WITH 'NCALC'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL INS       DO NCALCDOD
ON KEY LABEL F7        DO NCALCF7
ON KEY LABEL F8        DO NCALCF8
ON KEY LABEL ESC       NCALC.RELEASE
ENDPROC

PROCEDURE PORUKADANETAST
   ON KEY LABEL F1    DO HELPN WITH 'PORUKADANE'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PORUKADANE.RELEASE
ENDPROC

PROCEDURE AN0K2TAST
ON KEY LABEL F1    DO HELPN WITH 'AN0K2'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       AN0K2.RELEASE
ENDPROC

PROCEDURE fan0dEONAZTAST
   ON KEY LABEL F1    DO HELPN WITH 'FAN0DEONAZ'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       fan0DEONAZ.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE PORUKATAST
   ON KEY LABEL F1    DO HELPN WITH 'PORUKA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PORUKA.RELEASE
ENDPROC


PROCEDURE JBfan0TEKRACTAST
   ON KEY LABEL F1    DO HELPN WITH 'FAN0TEKRAC'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       fan0TEKRAC.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC


PROCEDURE JBIZVESTAJITAST
   ON KEY LABEL F1    DO HELPN WITH 'JBIZVESTAJI'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JBIZVESTAJI.RELEASE
ENDPROC


PROCEDURE JBSERVISTAST
   ON KEY LABEL F1    DO HELPN WITH 'JBSERVIS'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JBSERVIS.RELEASE
ENDPROC

PROCEDURE JBDATCITTAST
   ON KEY LABEL F1    DO HELPN WITH 'JBDATCIT'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JBDATCIT.RELEASE
ENDPROC

PROCEDURE JBEKSPRIJEMPOTTAST
   ON KEY LABEL F1    DO HELPN WITH 'JBEKPRIJEMPOT'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JBEKSPRIJEMPOT.RELEASE
ENDPROC

PROCEDURE JBSTANJEAKONTTAST
   ON KEY LABEL F1    DO HELPN WITH 'JBSTANJEAKONT'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JBSTANJEAKONT.RELEASE
ENDPROC

PROCEDURE JBSTANJEAKONTFTAST
   ON KEY LABEL F1    DO HELPN WITH 'JBSTANJEAKONTF'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JBSTANJEAKONTF.RELEASE
ENDPROC

PROCEDURE JBSPORAZTAST
   ON KEY LABEL F1    DO HELPN WITH 'JBSPORAZ'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JBSPORAZ.RELEASE
ENDPROC

PROCEDURE JBSPORAZpodTAST
   ON KEY LABEL F1    DO HELPN WITH 'JBSPORAZPOD'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JBSPORAZPOD.RELEASE
ENDPROC

PROCEDURE JBAPOTROSNJATAST
   ON KEY LABEL F1    DO HELPN WITH 'JBAPOTROSNJA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JBAPOTROSNJA.RELEASE
ENDPROC

PROCEDURE JBAN00TAST
   ON KEY LABEL F1    DO HELPN WITH 'JBAN00'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JBAN00.RELEASE
ENDPROC

PROCEDURE JBAN00KARTTAST
   ON KEY LABEL F1    DO HELPN WITH 'JBAN00KART'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JBAN00KART.RELEASE
ENDPROC

PROCEDURE JBCENETAST
   ON KEY LABEL F1    DO HELPN WITH 'JBCENE'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JBCENE.RELEASE
ENDPROC

PROCEDURE JBOBRAC0TAST
   ON KEY LABEL F1    DO HELPN WITH 'JBOBRAC0'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JBOBRAC0.RELEASE
ENDPROC

PROCEDURE JBOBRAC01TAST
   ON KEY LABEL F1    DO HELPN WITH 'JBOBRAC01'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JBOBRAC01.RELEASE
ENDPROC

PROCEDURE JBUNOSPOTTAST
   ON KEY LABEL F1    DO HELPN WITH 'JBUNOSPOT'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JBUNOSPOT.RELEASE
ENDPROC

PROCEDURE JBAFTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       JBAF.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE JBCENEfTAST
   ON KEY LABEL F1    DO HELPN WITH 'JBCENEf'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JBCENEf.RELEASE
ENDPROC

PROCEDURE JBOBRACfTAST
   ON KEY LABEL F1    DO HELPN WITH 'JBOBRACf'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JBOBRACf.RELEASE
ENDPROC

PROCEDURE JBOBRAC01fTAST
   ON KEY LABEL F1    DO HELPN WITH 'JBOBRAC01f'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JBOBRAC01f.RELEASE
ENDPROC

PROCEDURE JBIZVESTAJIFTAST
   ON KEY LABEL F1    DO HELPN WITH 'JBIZVESTAJIF'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JBIZVESTAJIF.RELEASE
ENDPROC

PROCEDURE JBSPIS3TAST
   ON KEY LABEL F1    DO HELPN WITH 'JBSPIS3'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JBSPIS3.RELEASE
ENDPROC

PROCEDURE JBSPIS3FTAST
   ON KEY LABEL F1    DO HELPN WITH 'JBSPIS3F'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JBSPIS3F.RELEASE
ENDPROC