SELECT VP
MPIB=PIB
MGRUPA=GRUPA
MIME_PREZ=IME_PREZ
MPREZ=AN00.PREZ
MIME=AN00.IME
*SET STEP ON 
*-----------TABELA OBRACUNA------------
select VPOBRAC
MCENOVNIK=CENOVNIK
MBROBRAC=BROBRAC
*------TABELA CENA
select VPCENE
SET ORDER TO 1
SEEK MCENOVNIK
mpstanje=pstanje
mzstanje=zstanje
APOC='ST'+ALLTRIM(STR(MPSTANJE,2,0))
AKRAJ='ST'+ALLTRIM(STR(MZSTANJE,2,0))
MMES=MZSTANJE-MPSTANJE
mEdatum=datum
mEvaluta=valuta
mdatOD2=DTOS(datod)
mdatDO2=DTOS(datdo)
mdatOD=datod
mdatDO=datdo
mcvoda=cvoda
mcdvoda=cdvoda
mckanal=ckanal
mcdkanal=cdkanal
MCSMECE=CSMECE
MCGRO=CGRO
MRABPROC=RABPROC
MPROCvoda=PROCvoda
mprockan=PROCkan
MPROCsme=PROCsme
mprocGRO=procGRO
mprocakont=procakont
MBRNAL='O'+ALLTRIM(STR(MBROBRAC,2,0))+MGRUPA
MPRDUG=0
SELECT VP
IF POPUST<>' '
   IMARABAT=1
ELSE
   IMARABAT=0
ENDIF   
SELECT VP
mdinost1=dinost1
mdinost2=dinost2
MPOST1=POST1
MPOST2=POST2
MNAZOST1=NAZOST1
MNAZOST2=NAZOST2
mprocost1=procost1
mprocost2=procost2
mporost1=0
mporost2=0
MKAMATA=0
*-----------OBRACUN KAMATE---------------
   select VPUPL
   set order to 
   SELECT VP
   USE VPKAM IN 0 EXCLU
   SELECT VPKAM
   ZAP
   DO VPKAM WITH MPIB,MDATOD,MDATDO
   SELECT VPKAM
*--------PRENOS KAMATE------------------
   SET ORDER TO 1
   MKAMATA=0
   SELECT VPKAM
   SET ORDER TO 1
   SEEK MPIB
   IF FOUND()
      MKAMATA=0
      DO WHILE.NOT.EOF()
         IF PIB<>MPIB
            EXIT
         ENDIF
         IF DATPOC>=MDATOD.AND.DATPOC<=MDATDO
            mKAMATA=mKAMATA+KAMATA
         ENDIF   
         SKIP
      ENDDO
   ENDIF
   *DO VPPRENKAM WITH MPIB,MDATOD,MDATDO
   SELECT VPKAM
   USE
   SELECT VP  
   REPLACE DATUM WITH MEDATUM
   REPLACE VALUTA WITH MEVALUTA
   REPLACE MES WITH MMES
   IF MKAMATA>0
      REPLACE KAMATA WITH MKAMATA
   ELSE
      REPLACE KAMATA WITH 0
   ENDIF
*--------OBRACUN PAUSAL------------------
   IF PAUSAL<>'D'
      REPLACE POT WITH &AKRAJ-&APOC
      MPOT=POT
   ELSE
      REPLACE POT WITH MMES*MESPAUSAL
      MPOT=POT
   ENDIF
   IF POT<0
      REPLACE POT WITH 0
      MPOT=POT
   ENDIF   
   REPLACE POC WITH &APOC
   REPLACE KRAJ WITH &AKRAJ
   *REPLACE UKPOT WITH KRAJ-POC
   REPLACE UKPOT WITH MPOT
   REPLACE VODA WITH 0
*   REPLACE CENOVNIK WITH MCENOVNIK
*------------OBRACUN ZA VODU------------------   
   IF POT>0
      IF PVODA='D'
         REPLACE VODA WITH POT*MCVODA*(100-POPVODA)/100
         REPLACE DOPV WITH POT*MCDVODA*(100-POPVODA)/100    
      ELSE
         REPLACE VODA WITH 0
         REPLACE DOPV WITH 0
      ENDIF
*------------OBRACUN ZA KANALIZACIJU
      IF PKANAL='D'
         REPLACE KAN WITH POT*MCKANAL*(100-POPKAN)/100
         REPLACE DOPK WITH POT*MCDKANAL*(100-POPKAN)/100    
      ELSE
         REPLACE KAN WITH 0
         REPLACE DOPK WITH 0   
      ENDIF
   ELSE
      REPLACE VODA WITH 0
      REPLACE DOPV WITH 0
      REPLACE KAN WITH 0
      REPLACE DOPK WITH 0   
   ENDIF
*------------OBRACUN ZA GROCENJE
IF PGRO='D'
   REPLACE GRO WITH MCGRO*(100-POPGRO)/100
ELSE
   REPLACE GRO WITH 0
ENDIF
*------------OBRACUN ZA SMECE
IF PSMECE='D'
   REPLACE SMECE WITH POV*MCSMECE*(100-POPSME)/100
ELSE
   REPLACE SMECE WITH 0
ENDIF
*----------PRETRAZIVANJE UPLATA zbog rabata--------  
   MRABATDUG=0
   SELECT VPUPL
   SET ORDER TO 1
   SEEK MPIB
   if found()
      do while.not.eof()
         if PIB<>mPIB
            exit
         ENDIF
         IF brnal<>mbrnal
*            SET STEP on
            IF datum<=mdatdo
               mrabatdug=mrabatdug+dug-pot
            endif
         endif   
        skip
     enddo      
   ELSE
      mrabatdug=0   
   endif
IF mrabatdug<=0
   imarabat=1
ELSE
   imarabat=0
endif
*-------UKUPNI PODACI------------------   
SELECT vp
   REPLACE MESECI WITH MMES      
   IF IMARABAT=1
      MRABOSNOV=VODA+DOPV+KAN+DOPK+SMECE+GRO+DINOST1+DINOST2
   ELSE
      MRABOSNOV=0
   ENDIF      
   *MMAKSPOT=MMES*15
   *IF POT<=MMAKSPOT
   IF MRABOSNOV>0
      MRABAT=ROUND(MRABOSNOV*MRABPROC/100,2)
   ELSE
      MRABAT=0
   ENDIF
   *ELSE
   *   MRABAT=0
   *ENDIF
   REPLACE RABAT WITH MRABAT
   *-----OBRACUN POREZA-------------------------------
   
   MUKUPNO=VODA+DOPV+KAN+DOPK+SMECE+GRO+DINOST1+DINOST2
   MUKUPNO2=VODA+DOPV+KAN+DOPK+SMECE   
   REPLACE UKUPNO WITH MUKUPNO   
   
   IF POPSOC>0.AND.(MUKUPNO-mRABAT)>0
      MSOC=ROUND((MUKUPNO-RABAT)*POPSOC/100,2)
   ELSE
      MSOC=0
   ENDIF
   REPLACE SOC WITH MSOC
   
   *------porez     
   REPLACE PROCvoda WITH MPROCVODA
   REPLACE PROCKAN WITH MPROCKAN
   REPLACE PROCSME WITH MPROCSME
   REPLACE PROCGRO WITH MPROCGRO
   MPOREZ20=0
   MPOREZ10=0
   MOSN20=0
   MOSN10=0
   MOSN0=0
   mosn0=dopv+dopk
   IF voda>0
      MPORVODA=ROUND(VODA*PROCVODA/100,2)
      DO CASE PROCVODA
      case PROCVODA=VAL(TOSTOPA)
         MPOREZ20=MPOREZ20+MPORVODA
         MOSN20=MOSN20+VODA
      case PROCVODA=VAL(TNSTOPA)
         MPOREZ10=MPOREZ10+MPORVODA
         MOSN10=MOSN10+VODA
      OTHERWISE
         mosn0=MOSN0+voda          
      ENDcase
   ELSE
      MPORVODA=0
   ENDIF
   IF KAN>0
      MPORKAN=ROUND(KAN*PROCKAN/100,2)
      DO CASE PROCKAN
      case PROCKAN=VAL(TOSTOPA)
         MPOREZ20=MPOREZ20+MPORKAN
         MOSN20=MOSN20+KAN
      case PROCKAN=VAL(TNSTOPA)
         MPOREZ10=MPOREZ10+MPORKAN
         MOSN10=MOSN10+KAN
      OTHERWISE
         mosn0=MOSN0+KAN         
      ENDcase
   ELSE
      MPORKAN=0
   ENDIF
   IF SMECE>0
      MPORSME=ROUND(SMECE*PROCSME/100,2)
      DO CASE PROCSME
      case PROCSME=VAL(TOSTOPA)
         MPOREZ20=MPOREZ20+MPORSME
         MOSN20=MOSN20+SMECE
      case PROCSME=VAL(TNSTOPA)
         MPOREZ10=MPOREZ10+MPORSME
         MOSN10=MOSN10+SMECE
      OTHERWISE
         mosn0=MOSN0+SMECE    
      ENDcase
   ELSE
      MPORSME=0
   ENDIF
   IF GRO<>0
      MPORGRO=ROUND(GRO*PROCGRO/100,2)
      DO CASE PROCGRO
      case PROCGRO=VAL(TOSTOPA)
         MPOREZ20=MPOREZ20+MPORGRO
         MOSN20=MOSN20+GRO
      case PROCGRO=VAL(TNSTOPA)
         MPOREZ10=MPOREZ10+MPORGRO
         MOSN10=MOSN10+GRO
      OTHERWISE
         mosn0=MOSN0+GRO
      ENDcase
      
   ELSE
      MPORGRO=0
   ENDIF
   
   IF DINOST1<>0
      MPOROST1=ROUND((DINOST1)*PROCOST1/100,2)
      DO CASE PROCOST1
      case PROCOST1=VAL(TOSTOPA)
         MPOREZ20=MPOREZ20+MPOROST1
         MOSN20=MOSN20+DINOST1
      case PROCOST1=VAL(TNSTOPA)
         MPOREZ10=MPOREZ10+MPOROST1
         MOSN10=MOSN10+DINOST1
      OTHERWISE
         mosn0=MOSN0+DINOST1
      ENDcase

   ELSE
      MPOROST1=0
   ENDIF
   IF DINOST2<>0
      MPOROST2=ROUND((DINOST2)*PROCOST2/100,2)
      DO CASE PROCOST2
      case PROCOST2=VAL(TOSTOPA)
         MPOREZ20=MPOREZ20+MPOROST2
         MOSN20=MOSN20+DINOST2
      case PROCOST2=VAL(TNSTOPA)
         MPOREZ10=MPOREZ10+MPOROST2
         MOSN10=MOSN10+DINOST2
      OTHERWISE
         mosn0=MOSN0+DINOST2
      ENDcase
   ELSE
      MPOROST2=0
   ENDIF
   REPLACE PORVODA WITH MPORVODA
   REPLACE PORKAN WITH MPORKAN
   REPLACE PORSME WITH MPORSME
   REPLACE PORGRO WITH MPORGRO
   REPLACE POROST1 WITH MPOROST1
   REPLACE POROST2 WITH MPOROST2  
   
   REPLACE POREZ20 WITH MPOREZ20
   REPLACE POREZ10 WITH MPOREZ10   
   REPLACE OSNOV20 WITH MOSN20   
   REPLACE OSNOV10 WITH MOSN10   
   REPLACE OSNOV0 WITH MOSN0      
   replace porezuk WITH mporez20+mporez10
   replace osnovuk WITH osnov20+osnov10+osnov0

   REPLACE SVEGA WITH UKUPNO-SOC-RABAT+PORVODA+PORKAN+PORSME+PORGRO+POROST1+POROST2

   MOSNOV=MUKUPNO-MSOC-mrabat+MPORVODA+MPORKAN+MPORSME+MPORGRO+MPOROST1+MPOROST2

   IF MOSNOV>0.AND.MMES>0   
      REPLACE AKONT WITH ROUND( (100+MPROCAKONT)*MOSNOV/MMES/100,0)
   ELSE
      REPLACE AKONT WITH 0
   ENDIF   
   REPLACE BRNAL WITH MBRNAL
   MPR2DUG=0
   MUPLAC=0
   mispr=0
   MSPORAZUM=0
   MOSTALO=0

   SELECT VPUPL
   SET ORDER TO 1
   SEEK MPIB
*----------PRETRAZIVANJE UPLATA ZA OSTALIM PODACIMA--------  
   if found()
      do while.not.eof()
         if PIB<>mPIB
            exit
         endif
         if DTOS(datum)<DTOS(mdatod)
            mpr2dug=mpr2dug+dug-pot
         endif    
         if DTOS(datum)>=DTOS(mdatod).and.DTOS(datum)<=DTOS(mdatdo)
            IF GRUPA='SPO'.OR.GRUPA='STA'.OR.GRUPA='STO'.OR.GRUPA='SPP'
               MSPORAZUM=MSPORAZUM+DUG
            ENDIF      
            IF GRUPA='ISP'.OR.GRUPA='KOD'
               MOSTALO=MOSTALO+DUG
            ENDIF      
         ENDIF
         if DTOS(datum)>=DTOS(mdatod).and.DTOS(datum)<=DTOS(mdatdo)
           mUPLAC=MUPLAC+POT
           mdATUM=datum 
        endif
        skip
     enddo      
  endif
*----------POPUNJAVANJE GLAVNE TABELE----------
   SELECT VP
   REPLACE DUG WITH MPR2DUG
   REPLACE UPLAC WITH MUPLAC
   REPLACE OSTALO WITH MOSTALO+msporazum
   *REPLACE SPORAZUM WITH MSPORAZUM
*   REPLACE SVEGA WITH UKUPNO+OSTALO+SPORAZUM-UPLAC+DUG+POREZ+KAMATA-MSOC
*   REPLACE ZADUZENJE WITH UKUPNO+POREZ-SOC 
*   REPLACE SOC WITH -MSOC
   SET CENTURY OFF
   MGODINA=SUBSTR(DTOC(medatum),7,2)
   mbrrac=ALLTRIM(pib)+ALLTRIM(STR(MBROBRAC,2,0))+mgodina
   REPLACE BRRAC WITH MBRRAC
   mbrrac2=SUBSTR(mbrrac,1,2)+ALLTRIM(SUBSTR(mbrrac,4,25))
   M1=VAL(mbrrac2)
   M2=(M1*100/97)-INT(M1*100/97)
   M3=ROUND(97*M2,0)
   M4=98-M3
   IF M4<=9
      M4='0'+STR(M4,1,0)
   ELSE
      M4=STR(M4,2,0)
   ENDIF      
   REPLACE model WITH +M4+'-'+ALLTRIM(mbrrac2)
   SET CENTURY on
   SELECT VPUPLD
   SET ORDER TO 1
   SET EXACT OFF
   GO TOP
   DO WHILE.T.
      LOCATE FOR pib=mpib.and.brnal=mbrnal
      IF FOUND()
         SET ORDER TO 
         REPLACE PIB WITH SPACE(13)
         REPLACE BRNAL WITH SPACE(6)
         REPLACE BRRAC WITH ''
         REPLACE GRUPA WITH ''
         REPLACE CENOVNIK WITH 0
         REPLACE PSTanje WITH 0
         REPLACE ZSTANJE WITH 0
         REPLACE MESEC WITH 0
         REPLACE DATUM WITH CTOD('')
         REPLACE VALUTA WITH CTOD('')
         REPLACE DATOD WITH CTOD('')
         REPLACE DATDO WITH CTOD('')
         REPLACE CVODA WITH 0
         REPLACE CDVODA WITH 0
         REPLACE CKANAL WITH 0
         REPLACE CSMECE WITH 0
         REPLACE CDKANAL WITH 0
         REPLACE CGRO WITH 0
         REPLACE VODA WITH 0
         REPLACE DOPV WITH 0
         REPLACE KAN WITH 0
         REPLACE SMECE WITH 0     
         replace pov WITH 0    
         REPLACE GRO WITH 0                  
         REPLACE DOPK WITH 0
         REPLACE UKUPNO WITH 0
         REPLACE OSTALO WITH 0
         REPLACE SOC WITH 0
         REPLACE KAMATA WITH 0
         REPLACE OSNOV WITH 0
         REPLACE POC WITH 0
         REPLACE KRAJ WITH 0
         REPLACE POT WITH 0
         REPLACE RABAT WITH 0
         REPLACE DUG WITH 0
         REPLACE SALDO WITH 0
         REPLACE SVEGA WITH 0
         REPLACE PROCVODA WITH 0
         REPLACE PROCKAN WITH 0
         REPLACE PROCSME WITH 0
         REPLACE PROCGRO WITH 0
         REPLACE PROCOST1 WITH 0
         REPLACE PROCOST2 WITH 0         
         REPLACE PORVODA WITH 0         
         REPLACE PORKAN WITH 0         
         REPLACE PORSME WITH 0         
         REPLACE PORGRO WITH 0
         REPLACE POROST1 WITH 0
         REPLACE POROST2 WITH 0
         LOOP 
      ELSE
         EXIT
      ENDIF
   ENDDO   
   SET ORDER TO 
   SELECT VP
   MGRUPA=GRUPA
   MDATUM=DATUM
   MVALUTA=VALUTA
   MPAUSAL=PAUSAL
   MMESPAUSAL=MESPAUSAL
   MVODA=VODA
   MDOPV=DOPV
   MKAN=KAN
   MSMECE=SMECE
   MGRO=GRO
   MDOPK=DOPK
   MUKUPNO=UKUPNO
   MOSTALO=OSTALO
   *msporazum=sPORAzum
   mdug=dug
   MSVEGA=SVEGA
   MUPLAC=UPLAC
   MSOC=SOC
   MKAMATA=KAMATA
   MBRRAC=BRRAC
   MMODEL=MODEL
   MRABAT=RABAT
   MPOC=POC
   MKRAJ=KRAJ
   MPOT=POT
   MPVODA=PVODA
   MPKANAL=PKANAL
   MPOPVODA=POPVODA
   MPOPKAN=POPKAN
   MPOPSOC=POPSOC
   MPOPSME=POPSME
   MPOPGRO=POPGRO
   MBRSTAN=BRSTAN
   MUKSTAN=UKSTAN
   MDOMAC=DOMAC
   MKS=KS
   MKSSIFRA=KSSIFRA
   MVRSTA=VRSTA
   MSIFUL=SIFUL
   MULICA=ULICA
   MULBROJ=ULBROJ
   MBROJ=BROJ
   MIME_PREZ=IME_PREZ
   MPOSTA=POSTA
   MULICA=ULICA
   MMESTO=MESTO
   MRABAT=RABAT   
   mdatcit=datcit
   mpov=pov
   MPROCVODA=PROCVODA
   MPROCKAN=PROCKAN
   MPROCSME=PROCSME
   MPROGRO=PROCGRO
   MPROCOST1=PROCOST1   
   MPROCOST2=PROCOST2      
   MPORGRO=PORGRO
   MPOROST1=POROST1
   MPOROST2=POROST2
   MPOREZ20=POREZ20
   MPOREZ10=POREZ10   
   MOSNOV20=OSNOV20   
   MOSNOV10=OSNOV10   
   MOSNOV0=OSNOV0      
   mporezuk=porezuk
   mosnovuk=osnovuk
   SELECT VPUPLD
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE GRUPA WITH MGRUPA
   REPLACE CENOVNIK WITH MCENOVNIK
   REPLACE PSTanje WITH MPSTANJE
   REPLACE ZSTANJE WITH MZSTANJE
   REPLACE MESEC WITH MMES
   REPLACE DATUM WITH  MDATUM
   REPLACE VALUTA WITH MVALUTA
   REPLACE DATOD WITH MDATOD
   REPLACE DATDO WITH MDATDO
   REPLACE CVODA WITH MCVODA
   REPLACE CDVODA WITH MCDVODA
   REPLACE CKANAL WITH MCKANAL
   REPLACE CDKANAL WITH MCDKANAL
   REPLACE CSMECE WITH MCSMECE
   REPLACE CGRO WITH MCGRO   
   REPLACE VODA WITH MVODA
   REPLACE DOPV WITH MDOPV
   REPLACE KAN WITH MKAN
   REPLACE DOPK WITH MDOPK
   REPLACE SMECE WITH MSMECE
   REPLACE GRO WITH MGRO
   REPLACE UKUPNO WITH MUKUPNO
   REPLACE OSTALO WITH MOSTALO
   REPLACE DUG WITH MDUG
   REPLACE UPLAC WITH MUPLAC
   REPLACE SOC WITH MSOC
   REPLACE KAMATA WITH MKAMATA
   REPLACE SVEGA WITH MSVEGA
   REPLACE SALDO WITH SVEGA+DUG-UPLAC+KAMATA+ostalo
   REPLACE BRRAC WITH MBRRAC
   REPLACE MODEL WITH MMODEL
   REPLACE BRNAL WITH MBRNAL
   REPLACE OSNOV WITH MOSNOV
   REPLACE POC WITH MPOC
   REPLACE KRAJ WITH MKRAJ
   REPLACE POT WITH MPOT
   REPLACE UKPOT WITH MPOT
   REPLACE PVODA WITH MPVODA
   REPLACE PKANAL WITH MPKANAL
   REPLACE POPVODA WITH  MPOPVODA
   REPLACE POPKAN WITH  MPOPKAN
   REPLACE POPSME WITH  MPOPSME
   REPLACE POPGRO WITH  MPOPGRO
   REPLACE POPSOC WITH  MPOPSOC   
   REPLACE BRSTAN WITH MBRSTAN
   REPLACE UKSTAN WITH MUKSTAN
   REPLACE DOMAC WITH MDOMAC
   REPLACE KS WITH MKS
   REPLACE KSSIFRA WITH MKSSIFRA
   REPLACE VRSTA WITH MVRSTA
   REPLACE SIFUL WITH MSIFUL
   REPLACE ULICA WITH MULICA
   REPLACE ULBROJ WITH MULBROJ
   REPLACE BROJ WITH MBROJ
   REPLACE IME_PREZ WITH MIME_PREZ
   REPLACE RABAT WITH MRABAT
   replace datcit WITH mdatcit
   REPLACE POSTA WITH MPOSTA
   REPLACE MESTO WITH MMESTO
   REPLACE ULICA WITH MULICA
   replace pov WITH mpov
   REPLACE DINOST1 WITH MDINOST1
   REPLACE DINOST2 WITH MDINOST2
   REPLACE NAZOST1 WITH MNAZOST1
   REPLACE NAZOST2 WITH MNAZOST2
   REPLACE PROCVODA WITH MPROCVODA
   REPLACE PROCKAN WITH MPROCKAN
   REPLACE PROCSME WITH MPROCSME
   REPLACE PROCGRO WITH MPROCGRO
   REPLACE PROCOST1 WITH MPROCOST1
   REPLACE PROCOST2 WITH MPROCOST2
   replace porvoda WITH mporvoda
   replace porkan WITH mporkan
   replace porsme WITH mporsme
   REPLACE PORGRO WITH MPORGRO
   REPLACE POROST1 WITH MPOROST1
   REPLACE POROST2 WITH MPOROST2
   replace porez20 WITH mporez20
   replace porez10 WITH mporez10
   replace osnov20 WITH mosnov20
   replace osnov10 WITH mosnov10
   replace osnov0 WITH mosnov0
   replace porezuk WITH mporezuk
   replace osnovuk WITH mosnovuk 

*   REPLACE SVEGA WITH MSVEGA
   MDDUG=VODA+DOPV+KAN+DOPK+smece+GRO+PORVODA+PORKAN+PORSME+PORGRO+POROST1+POROST2-SOC-RABAT+KAMATA+DINOST1+DINOST2
   MKAMATA=KAMATA
   SELECT VPUPL
   SET ORDER TO 1
   SEEK Mpib
   IF FOUND()
       DO WHILE.NOT.EOF()
          IF pib<>Mpib
             EXIT
          ENDIF
          IF brnal=mbrnal
          IF DUG<>0
             REPLACE DUG WITH 0
             REPLACE BRRAC WITH ''
          ENDIf    
          endif
          SKIP
       ENDDO
   ENDIF    
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE GRUPA WITH MGRUPA
   REPLACE DUG WITH MDDUG-Mkamata
   REPLACE DATUM WITH MDATUM
   REPLACE VALUTA WITH MVALUTA
   REPLACE BRRAC WITH MBRRAC
   REPLACE BRNAL WITH MBRNAL
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE GRUPA WITH MGRUPA
   REPLACE DUG WITH Mkamata
   REPLACE DATUM WITH MDATUM
   REPLACE VALUTA WITH MVALUTA
   REPLACE BRRAC WITH 'K-'+MBRRAC
   REPLACE BRNAL WITH MBRNAL
   SET ORDER TO 
   SELECT VP