PROCEDURE JCATAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       JCA.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE JCUPLTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       JCUPL.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE JCUPLDTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       JCUPLD.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE JCUPLDFTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       JCUPLDF.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC


PROCEDURE JCPODTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       JCPOD.RELEASE
ENDPROC

PROCEDURE JCFirmeTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       JCFIRME.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE JCFIRMEPODTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       JCFIRMEPOD.RELEASE
ENDPROC


PROCEDURE JC0TAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   JC0.RELEASE
ENDPROC


PROCEDURE JCSUD0TAST
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   JCSUD0.RELEASE
ENDPROC

PROCEDURE JCSUDTAST
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   JCSUD.RELEASE
ENDPROC

PROCEDURE JCSUD0DODRACTAST
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   JCSUD0DODRAC.RELEASE
ENDPROC

PROCEDURE JCANALIZVOTAST
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   JCANALIZVO.RELEASE
ENDPROC


PROCEDURE VT0TAST
   ON KEY LABEL F1    DO HELPN WITH 'VT0'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VT0.RELEASE
   ON KEY LABEL F2        ! /N CALC.EXE
ENDPROC


PROCEDURE JCKAKOEFTAST
   ON KEY LABEL F1    DO HELPN WITH 'VPKAKOEF'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JCKAKOEF.RELEASE
   ON KEY LABEL F2        ! /N CALC.EXE
ENDPROC

PROCEDURE VKKAKOEFTAST
   ON KEY LABEL F1    DO HELPN WITH 'VKKAKOEF'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VKKAKOEF.RELEASE
   ON KEY LABEL F2        ! /N CALC.EXE
ENDPROC

PROCEDURE JCFAN0TAST

ON KEY LABEL F1    DO HELPN WITH 'FAN0'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       FAN0.RELEASE
ON KEY LABEL +         DO FAN0DOD
on key label INS       DO FAN0DOD
ON KEY LABEL F3        DO FAN0DEONAZ
ON KEY LABEL ALT+F3        DO FAN0TEKRAC
ON KEY LABEL F4        DO FAN0TRAZI
ON KEY LABEL F5        DO FAN0GR5TRAZI
ON KEY LABEL F6        DO FAN0TRAZIF6
ON KEY LABEL F7        DO FAN0KARTF7
ON KEY LABEL F8        DO FAN0ZIROTRAZI
ON KEY LABEL CTRL+F12  DO OTVFAN0
ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC

ENDPROC


PROCEDURE HELPNTAST
   ON KEY LABEL ESC       HELPN.RELEASE
   ON KEY LABEL F1    ON KEY
   ON KEY LABEL CTRL+F12  HELPN.GRD0.READONLY=.F.
ENDPROC

PROCEDURE NCALCTAST
ON KEY LABEL F1    DO HELPN WITH 'NCALC'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL INS       DO NCALCDOD
ON KEY LABEL F7        DO NCALCF7
ON KEY LABEL F8        DO NCALCF8
ON KEY LABEL ESC       NCALC.RELEASE
ENDPROC

PROCEDURE PORUKADANETAST
   ON KEY LABEL F1    DO HELPN WITH 'PORUKADANE'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PORUKADANE.RELEASE
ENDPROC

PROCEDURE AN0K2TAST
ON KEY LABEL F1    DO HELPN WITH 'AN0K2'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       AN0K2.RELEASE
ENDPROC

PROCEDURE fan0dEONAZTAST
   ON KEY LABEL F1    DO HELPN WITH 'FAN0DEONAZ'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       fan0DEONAZ.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE PORUKATAST
   ON KEY LABEL F1    DO HELPN WITH 'PORUKA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PORUKA.RELEASE
ENDPROC


PROCEDURE JCfan0TEKRACTAST
   ON KEY LABEL F1    DO HELPN WITH 'FAN0TEKRAC'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       fan0TEKRAC.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC


PROCEDURE JCIZVESTAJITAST
   ON KEY LABEL F1    DO HELPN WITH 'VPIZVESTAJI'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JCIZVESTAJI.RELEASE
ENDPROC


PROCEDURE JCSERVISTAST
   ON KEY LABEL F1    DO HELPN WITH 'VPSERVIS'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JCSERVIS.RELEASE
ENDPROC

PROCEDURE JCDATCITTAST
   ON KEY LABEL F1    DO HELPN WITH 'VPDATCIT'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JCDATCIT.RELEASE
ENDPROC

PROCEDURE JCEKSPRIJEMPOTTAST
   ON KEY LABEL F1    DO HELPN WITH 'VPEKPRIJEMPOT'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JCEKSPRIJEMPOT.RELEASE
ENDPROC

PROCEDURE JCSTANJEAKONTTAST
   ON KEY LABEL F1    DO HELPN WITH 'VPSTANJEAKONT'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JCSTANJEAKONT.RELEASE
ENDPROC

PROCEDURE JCSTANJEAKONTFTAST
   ON KEY LABEL F1    DO HELPN WITH 'VPSTANJEAKONTF'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JCSTANJEAKONTF.RELEASE
ENDPROC

PROCEDURE JCSPORAZTAST
   ON KEY LABEL F1    DO HELPN WITH 'VPSPORAZ'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JCSPORAZ.RELEASE
ENDPROC

PROCEDURE JCSPORAZpodTAST
   ON KEY LABEL F1    DO HELPN WITH 'VPSPORAZPOD'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JCSPORAZPOD.RELEASE
ENDPROC

PROCEDURE JCSPORAZKARTTAST
   ON KEY LABEL F1    DO HELPN WITH 'VPSPORAZKART'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JCSPORAZKART.RELEASE
ENDPROC


PROCEDURE JCAPOTROSNJATAST
   ON KEY LABEL F1    DO HELPN WITH 'VPAPOTROSNJA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JCAPOTROSNJA.RELEASE
ENDPROC

PROCEDURE JC0TAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       JC0.RELEASE
ENDPROC

PROCEDURE JCuplttAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       JCuplt.RELEASE
ENDPROC

PROCEDURE JCSERVISFIRMETAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       JCSERVISFIRME.RELEASE
ENDPROC

PROCEDURE JCSERVISTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       JCSERVIS.RELEASE
ENDPROC
