SELECT VP
MPIB=PIB
*-----------TABELA OBRACUNA------------
select VPOBRAC
MCENOVNIK=CENOVNIK
MBROBRAC=BROBRAC
MGRUPA=GRUPA
ABRNAL='O'+ALLTRIM(STR(MBROBRAC,2,0))+MGRUPA      
*------TABELA CENA
select VPCENE
SET ORDER TO 1
SEEK MCENOVNIK
mpstanje=pstanje
mzstanje=zstanje
MMES=MZSTANJE-MPSTANJE
MMESEC=MESEC
mEdatum=datum
mEvaluta=valuta
mdatOD=datod
mdatDO=datdo
mCSMECE=CSMECE
mCSMECEN=CSMECEN
mprocakont=procakont
MCEKO=CEKO
MPROCPOR=PROCPOR
mpposmece=pposmece
mpposmecen=pposmecen

*------OBRACUN ZA SMECE==============================

DECLARE MCS[27],MNCS[27]
FOR I=1 TO 27
   MMCS='CS'+ALLTRIM(STR(I,2,0))
   MCS[I]=&MMCS
   MMNCS='NCS'+ALLTRIM(STR(I,2,0))
   MNCS[I]=&MMNCS
NEXT
DECLARE MCSN[7]
FOR I=21 TO 27
   MMCSN='CSN'+ALLTRIM(STR(I,2,0))
   MCSN[I-20]=&MMCSN
NEXT
SELECT VP
MSMECE=0
MSMECEN=0
MEKODINAR=0
IF PSMECE<>' '
   MCEN=CENOVNIK
   IF MCEN=0
      REPLACE SMECE WITH MCSMECE*POV
      REPLACE SMECEN WITH MCSMECEN*POVNE
   ELSE
      IF CENOVNIK>0.AND.CENOVNIK<=20
         MCENA=MCS[CENOVNIK]
         REPLACE SMECE WITH MCENA
         REPLACE SMECEN WITH 0
      ELSE
         REPLACE SMECE WITH 0 
         REPLACE SMECEN WITH 0      
      ENDIF
      IF CENOVNIK>=21.AND.CENOVNIK<=27
         MCENA=MCS[CENOVNIK]
         MNCENA=MCSN[CENOVNIK-20]
         REPLACE SMECE WITH MCENA*POV
         REPLACE SMECEN WITH MNCENA*POVNE
      ENDIF      
   ENDIF
   IF MCEKO<>0
      REPLACE EKODINAR WITH MCEKO
   ELSE
      REPLACE EKODINAR WITH 0
   ENDIF   
   
   IF MPposmece<>0
      REPLACE PORsmece WITH ROUND(SMECE*Mpposmece/100,2)
   ELSE
      REPLACE porsmece WITH 0
   ENDIF   
   IF MPposmecen<>0
      REPLACE PORsmecen WITH ROUND(SMECEN*Mpposmecen/100,2)
   ELSE
      REPLACE PORsmecen WITH 0
   ENDIF   
   replace porez WITH porsmece+porsmecen

ELSE
   REPLACE SMECE WITH 0 
   REPLACE SMECEN WITH 0      
   REPLACE EKODINAR WITH 0
   REPLACE POREZ WITH 0
   replace porsmece WITH 0
   replace porsmecen WITH 0
ENDIF
REPLACE DUG WITH SMECE+SMECEN+EKODINAR+POREZ
REPLACE SVEGA WITH SMECE+SMECEN+EKODINAR+POREZ
MLENO=LEN(ALLTRIM(PIB2))
MPIB2=REPLICATE('0',5-MLENO)+ALLTRIM(PIB2)
MMESO1=LEN(ALLTRIM(STR(MMESEC,2,0)))
MMESO2=REPLICATE('0',2-MMESO1)+ALLTRIM(STR(MMESEC,2,0))
MGOD=SUBSTR(STR(YEAR(MEDATUM),4,2),3,2)
MBRRAC=ALLTRIM(PIB)+'-'+MMESO2+'-'+MGOD
MPOZIVO=ALLTRIM(PIB)+MMESO2+MGOD
REPLACE BRRAC WITH MBRRAC
replace datum WITH medatum
replace valuta WITH mevaluta
M1=VAL(MPOZIVO)
M2=(M1*100/97)-INT(M1*100/97)
M3=ROUND(97*M2,0)
M4=98-M3
IF M4<=9
   M4='0'+STR(M4,1,0)
ELSE
   M4=STR(M4,2,0)
ENDIF      
REPLACE POZIVO WITH M4+'-'+MBRRAC

*---------RASPODELA PORESKIH STOPA I OSNOVICA-----------------
MPORSMECE8=0
MOSNSMECE8=0
MPORSMECE18=0
MOSNSMECE18=0
MOSNSMECE0=0
MPORSMECEN8=0
MOSNSMECEN8=0
MPORSMECEN18=0
MOSNSMECEN18=0
MOSNSMECE0N=0

IF MPPOSMECE<>0
   IF MPPOSMECE=VAL(TNSTOPA)
      MPORSMECE8=PORSMECE
      MOSNSMECE8=SMECE
   ENDIF
   IF MPPOSMECE=VAL(TOSTOPA)
      MPORSMECE18=PORSMECE
      MOSNSMECE18=SMECE
   ENDIF      
ELSE
   MOSNSMECE0=SMECE
ENDIF
IF MPPOSMECEN<>0
   IF MPPOSMECEN=VAL(TNSTOPA)
      MPORSMECEN8=PORSMECEN
      MOSNSMECEN8=SMECEN
   ENDIF
   IF MPPOSMECEN=VAL(TOSTOPA)
      MPORSMECEN18=PORSMECEN
      MOSNSMECEN18=SMECEN
   ENDIF      

ELSE
   MOSNSMECE0N=SMECEN
ENDIF

MPOR8=MPORSMECE8+MPORsmecen8
MOSN8=MOSNSMECE8+MOSNsmecen8
MPOR18=MPORSMECE18+MPORsmecen18
MOSN18=MOSNSMECE18+MOSNsmecen18
MOSN0=MOSNSMECE0+MOSNSMECE0N

REPLACE OSN0 WITH MOSN0
REPLACE OSN8 WITH MOSN8
REPLACE OSN18 WITH MOSN18
REPLACE POR8 WITH MPOR8
REPLACE POR18 WITH MPOR18

MSALDO=SVEGA

*IF MSALDO>INT(MSALDO)
*   MZAOKRUZ=MSALDO-INT(MSALDO)
*ELSE
*   MZAOKRUZ=-(MSALDO-INT(MSALDO))
*ENDIF 
*REPLACE ZAOKRUZ WITH -MZAOKRUZ
replace zaokruz WITH 0
REPLACE SALDO WITH MSALDO
REPLACE MESECI WITH MMES
replace pposmece WITH mpposmece
replace pposmecen WITH mpposmecen
replace porsmece WITH mporsmece8+MPORSMECE18
replace porsmecen WITH mporsmecen8+MPORSMECEN18
*-------kraj rabata-----------------------
SELECT VP
