PARAMETERS MPIB,MDAT0,MDAT1
SELECT JPKAM
SET ORDER TO 1
COPY STRU TO VTK2

USE JPKAKOEF IN 0 ORDER 1 ALIAS KAKOEF
SELECT KAKOEF
SELECT JPUPL
SET ORDER TO 1 
COPY STRU TO VTU2
USE VTU2 EXCLU IN 0
SELECT VTU2
INDEX ON DATUM TAG DATUM
set order to 1
*-------TRAZI SE PIB U SIFARNIKU----------
SELECT JP
   USE VTK2 EXCLU IN 0
   SELECT VTK2
   DELETE ALL
PACK

   SELECT KAKOEF
   GO TOP
   seek DTOS(mdat0)
   *------PROLAZ KROZ BAZU KOEFICIJENATA---------
   DO WHILE.NOT.EOF()
      IF DATUM>=MDAT0.AND.DATUM<=MDAT1
         MMSTOPA=STOPA
         MMPERIOD=PERIOD
         MMDATUM=DATUM
         mkoef=koef 
         SELECT VTK2
         APPEND BLANK
         REPLACE STOPA WITH MMSTOPA
         REPLACE DATPOC WITH MMDATUM
         REPLACE DATUM WITH MMDATUM
         REPLACE PERIOD WITH MMPERIOD
         REPLACE PIB WITH MPIB           
         replace koef with mkoef
         SELECT KAKOEF
      ENDIF
      SKIP
   ENDDO
   SELECT VTK2
   GO TOP
   *--------PROLAZIMO KROZ BAZU UPLATA 
   SELECT JPUPL
   SEEK MPIB
   *------PROLAZ KROZ EVIDENCIJU I PUNJENJE BAZE UPLATE2 SA PODACIMA
   DO WHILE.NOT.EOF()
      IF PIB<>MPIB
         EXIT
      ENDIF
      IF DATUM<MDAT0
         MDUG=DUG
         MPOT=POT
         MDATUM=VALUTA 
         MVALUTA=VALUTA
         SELECT VTU2
         APPEND BLANK
         REPLACE DATUM WITH MDAT0
         IF MVALUTA<MDAT0
            replace valuta with mdat0
            REPLACE DATUM WITH MDAt0           
         ELSE
            REPLACE VALUTA WITH MVALUTA
            replace datum with mvaluta
         ENDIF
         REPLACE DUG WITH MDUG
         REPLACE POT WITH MPOT
         REPLACE PIB WITH MPIB
         SELECT JPUPL
      ENDIF
      IF DATUM>=MDAT0.AND.DATUM<=MDAT1
         MDUG=DUG
         MPOT=POT
         MDATUM=VALUTA
         SELECT VTU2
         APPEND BLANK
         REPLACE DATUM WITH MDATUM
         REPLACE DUG WITH MDUG
         REPLACE POT WITH MPOT
         REPLACE PIB WITH MPIB
         SELECT JPUPL
      ENDIF
      SKIP
   ENDDO
   SELECT VTU2
   TOTAL ON DATUM FIELDS DUG,POT TO VTU3
   *---------SPOJENI DATUMI U BAZI KAMATE3---------
   USE VTU3 EXCLU IN 0
   SELECT VTU3
   INDEX ON DATUM Tag VTU3
   SET ORDER TO tag VTU3
   *-------VRACAMO SE U TABELU KOEFICIJENATA
   SELECT VTK2
   SET RELATION TO DATUM INTO VTU3 additive
   GO TOP
   MSOSNOVICA=0
   DO WHILE.NOT.EOF()
      IF VTU3->DATUM=DATUM
         REPLACE DUG WITH VTU3->DUG
         REPLACE POT WITH VTU3->POT
      ENDIF
      SKIP
   ENDDO
   SET RELATION TO
   SELECT VTU2
DELETE ALL
PACK

   SELECT VTU3
DELETE ALL
PACK

   USE
   *------OPET IDEMO U BAZU KOEFICIJENATA
   SELECT VTK2
   SET ORDER TO
   GO TOP
   DO WHILE.NOT.EOF()
      MSTOPA=STOPA
      MPERIOD=PERIOD
      MDUG=DUG
      MPOT=POT
      RRR=RECNO()
      IF DUG<>0.OR.POT<>0
         REPLACE VAZI WITH '*'
      ENDIF
      if recno()<reccount()
         GOTO RRR+1
         IF .NOT.(STOPA=MSTOPA.AND.PERIOD=MPERIOD)
            REPLACE VAZI WITH '*'
         ENDIF
         goto rrr  
      endif
      SKIP
   ENDDO
   DELETE ALL FOR VAZI=' '
   PACK
   GO TOP
   DO WHILE.NOT.EOF()
      SKIP
      MDATPOC=DATPOC
      MDUG=DUG
      MPOT=POT
      SKIP -1
      IF MDUG<>0.OR.MPOT<>0
         REPLACE DATKRA WITH MDATPOC
         IF DUG<>0.OR.POT<>0
            REPLACE DATPOC WITH DATPOC
         ELSE
            REPLACE DATPOC WITH DATPOC-1
         ENDIF
      ELSE
         IF DUG=0.AND.POT=0
            REPLACE DATPOC WITH DATPOC-1
         ENDIF
            REPLACE DATKRA WITH MDATPOC-1
      ENDIF
      SKIP
   ENDDO
   GO bottom
   REPLACE DATKRA WITH MDAT1
   MSOSNOVICA=0
   GO TOP
   DO WHILE.NOT.EOF()
      IF DATPOC<>CTOD('').AND.DATKRA<>CTOD('')
         IF RECNO()>1
            REPLACE DANA WITH DATKRA-DATPOC-1
         ELSE
            REPLACE DANA WITH DATKRA-DATPOC-1
         ENDIF
      ENDIF
      IF PERIOD<>0
         MKOEF=ROUND(((((100+STOPA)/100)**(DANA/PERIOD)))-1,8)
         REPLACE KOEF WITH MKOEF
      ENDIF
      REPLACE OSNOVICA WITH SOSNOVICA+DUG-POT
      REPLACE KAMATA WITH ROUND(OSNOVICA*(KOEF),2)
      RRR=RECNO()
      MSOSNOVICA=OSNOVICA+KAMATA
      if recno()<reccount() 
         GOTO RRR+1
         REPLACE SOSNOVICA WITH MSOSNOVICA
         GOTO RRR
      endif
      SKIP
   ENDDO
   DELETE ALL FOR OSNOVICA=0
   PACK
   DO WHILE.NOT.EOF()
      IF DATPOC<>CTOD('').AND.DATKRA<>CTOD('')
         REPLACE DANA WITH DATKRA-DATPOC
      ENDIF
      IF PERIOD<>0
         MKOEF=ROUND(((((100+STOPA)/100)**(DANA/PERIOD)))-1,8)
         REPLACE KOEF WITH MKOEF
      ENDIF
      REPLACE OSNOVICA WITH SOSNOVICA+DUG-POT
      REPLACE KAMATA WITH ROUND(OSNOVICA*(KOEF),2)
      RRR=RECNO()
      MSOSNOVICA=OSNOVICA+KAMATA
      if recno()<reccount()
         GOTO RRR+1
         REPLACE SOSNOVICA WITH MSOSNOVICA
         GOTO RRR
      endif
      SKIP
   ENDDO
   GO TOP
   SELECT VTK2
   SET RELATION TO
   *----------PRELAZIMO U KAMATE--------
   SELECT JPKAM
   GO BOTTOM
   IF RECCOUNT()=0
      MRBR='   1'
   ELSE
      MMRBR=STR(VAL(RBR)+1,5,0)
      MRBRLEN=LEN(ALLTRIM(MMRBR))
      MRBR=SUBSTR('    ',1,4-MRBRLEN)+ALLTRIM(MMRBR)
   ENDIF
   SELECT VTK2
   REPLACE ALL PIB WITH MPIB
   REPLACE ALL RBR WITH MRBR
   USE
   SELECT JPKAM
   APPEND FROM VTK2
SELECT KAKOEF
USE
SELECT VTU2
USE
SELECT JPKAM
GO BOTTOM
