SELECT VP
MPIB=PIB
mclanova=clanova
MKANTABROJ=0
IF SERKANTA1<>SPACE(20)
   MKANTABROJ=1
ENDIF
IF SERKANTA2<>SPACE(20)
   MKANTABROJ=MKANTABROJ+1
ENDIF
IF SERKANTA3<>SPACE(20)
   MKANTABROJ=MKANTABROJ+1
ENDIF
REPLACE KANTABROJ WITH MKANTABROJ
   
*-----------TABELA OBRACUNA------------
select VPOBRAC
MCENOVNIK=CENOVNIK
MBROBRAC=BROBRAC
MGRUPA=GRUPA
ABRNAL='O'+ALLTRIM(STR(MBROBRAC,2,0))+MGRUPA      

*------TABELA CENA

select VPCENE
SET ORDER TO 1
SEEK MCENOVNIK

mpstanje=pstanje
mzstanje=zstanje
MCEKO=CEKO
MPROCPOR=PROCPOR
MMES=MZSTANJE-MPSTANJE

mEdatum=datum
mEvaluta=valuta
mdatOD=datod
mdatDO=datdo
MDATUOD=DATUOD
MDATUDO=DATUDO

mCSMECE=CSMECE
mCSMECEn=CSMECEn
mprocakont=procakont
MMESEC=MESEC
MCKANTA1=CKANTA1
MCKANTA2=CKANTA2
MCKANTA3=CKANTA3
MCCLAN1=CCLAN1
MCCLAN2=CCLAN2
select VPUPL
set order to 1
select VP
SET ORDER TO 1
SEEK MPIB
IF FOUND()
   REPLACE ODUG WITH 0
   REPLACE OPOT WITH 0
   REPLACE OSALDO WITH 0
   REPLACE RABAT WITH 0
   REPLACE KAMATA WITH 0
   REPLACE OSTALO WITH 0
   REPLACE SVEGA WITH 0
   select VPUPL
   seek MPIB
   if found()
      do while.not.eof()
         if PIB<>MPIB
            exit
         endif   
         *---BRISANJE NALOGA
         IF BRNAL=ABRNAL
            REPLACE DUG WITH 0
            REPLACE GRUPA WITH ' '
            REPLACE BRNAL WITH ' ' 
         ENDIF   
         skip
      enddo 
      SELECT VP
   ENDIF
ENDIF
*-----------OBRACUN KAMATE---------------
select VPUPL
set order to 
SELECT VP
USE VPKAM IN 0 EXCLU
SELECT VPKAM
ZAP
DO VPKAM WITH MPIB,MDATOD,MDATDO
SELECT VPKAM
*--------PRENOS KAMATE------------------
SET ORDER TO 1
DO VPPRENKAM WITH MPIB,MDATOD,MDATDO
SELECT VPKAM
USE
*------POPUNJAVANJE OSTALIH PODATAKA-----

SELECT VP
set procedure to
SELECT VP
REPLACE MESECI WITH MMES      

REPLACE SMECE WITH 0
*------------OBRACUN -----------------   
REPLACE SMECEN WITH 0
REPLACE EKODINAR WITH 0
replace KANTADIN WITH 0
replace smecec1 WITH 0
replace smecec2 WITH 0      

IF PSMECE='C'
      msmece1=0
      msmece2=0
      IF clanova<=4
         msmece1=ROUND(MCclan1*MMES*CLANOVA,2)
      ENDIF
      IF clanova>4
         msmece1=ROUND(MCclan1*MMES*4,2)
         msmece2=ROUND(MCclan2*MMES*(clanova-4),2)
      ENDIF
      replace smecec1 WITH msmece1
      replace smecec2 WITH msmece2      
      REPLACE EKODINAR WITH MCEKO
else

IF MKANTABROJ=0
   IF PSMECE<>' '
      REPLACE SMECE WITH POV*MCSMECE*MMES
      REPLACE SMECEN WITH POVNE*MCSMECEN*MMES
      REPLACE EKODINAR WITH MCEKO
      replace smecec1 WITH 0
      replace smecec2 WITH 0      
   ENDIF
ELSE
   DO CASE mkantabroj
   case MKANTABROJ=1
      REPLACE KANTADIN WITH MCKANTA1*MMES
      MCKANTA2=0
      mckanta3=0
   CASE mkantabroj=2
      REPLACE KANTADIN WITH (MCKANTA1+MCKANTA2)*MMES
      mckanta3=0
   CASE mkantabroj=3
      REPLACE KANTADIN WITH (MCKANTA1+MCKANTA2+mckanta3)*MMES
   ENDCASE
   replace smecec1 WITH 0
   replace smecec2 WITH 0
   
ENDIF   

ENDIF

MSMECE=SMECE
MSMECEN=SMECEN
MEKODINAR=EKODINAR
MKANTADIN=KANTADIN
MUKUPNO=SMECE+SMECEN+EKODINAR+KANTADIN+SMECEC1+SMECEC2
msmecec1=smecec1  
msmecec2=smecec2
MSOC=ROUND(MUKUPNO*POPSOC/100,2)

REPLACE SOC WITH -MSOC   

   IF MPROCPOR<>0
      REPLACE POREZ WITH ROUND((SMECE+SMECEN+EKODINAR+SOC+KANTADIN+SMECEC1+SMECEC2)*MPROCPOR/100,2)
   ELSE
      REPLACE POREZ WITH 0
   ENDIF
MPOREZ=POREZ

REPLACE UKUPNO WITH SMECE+SMECEN+SOC+EKODINAR+POREZ+KANTADIN+SMECEC1+SMECEC2
   
REPLACE AKONT WITH (100+MPROCAKONT)*(UKUPNO)/MMES/100

SELECT VPUPL
SEEK MPIB

MPRDUG=0
MUPLAC=0
MUPLACPER=0
mOST=0
*----------PRETRAZIVANJE UPLATA ZA OSTALIM PODACIMA--------  
if found()
   do while.not.eof()
      if PIB<>mPIB
         exit
      endif
      if datum<mdatod
         mprdug=mprdug+dug-pot
      endif    
      if datum>=mdatod.and.datum<=mdatdo
         IF !(GRUPA='SME'.OR.GRUPA='SC1'.OR.GRUPA='SC2'.OR.GRUPA='SOC'.OR.GRUPA='RAB'.OR.GRUPA='KAM'.OR.GRUPA='SMN'.OR.GRUPA='EKO'.OR.GRUPA='POR'.OR.GRUPA='KNT')
            MOST=MOST+DUG
         ENDIF      
      ENDIF
      if datum>=mdatod.and.datum<=mdatdo
         mUPLAC=MUPLAC+POT
         mdATUM=datum 
      endif
      if datum>=mdatUod.and.datum<=mdatUdo
         mUPLACPER=MUPLACPER+POT
         mdATUM=datum 
      endif
      
      skip
   enddo      
endif
*----------POPUNJAVANJE GLAVNE TABELE----------
SELECT VP
REPLACE UPLAC WITH MUPLAC
REPLACE DUG WITH MPRDUG
REPLACE OSTALO WITH MOST
REPLACE SOC WITH -MSOC
mbrrac=grupa+SUBSTR(STR(YEAR(medatum),4,0),3,2)+ALLTRIM(pib)+ALLTRIM(STR(MBROBRAC,2,0))
REPLACE BRRAC WITH MBRRAC
M1=VAL(mbrrac)
M2=(M1*100/97)-INT(M1*100/97)
M3=ROUND(97*M2,0)
M4=98-M3
IF M4<=9
   M4='0'+STR(M4,1,0)
ELSE
   M4=STR(M4,2,0)
ENDIF      
REPLACE model WITH +M4+'-'+ALLTRIM(mbrrac)
*----------POPUNJAVANJE TABELE UPLATA----------
SELECT VPUPL   
IF MSMECE<>0
   SELECT VPUPL 
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE DUG WITH MSMECE+MKANTADIN
   REPLACE DATUM WITH MEDATUM
   REPLACE VALUTA WITH MEVALUTA
   REPLACE GRUPA WITH 'SME'
   replace opis WITH ' SMECE IZGRADJENA'+GRUPA
   REPLACE BRRAC WITH MBRRAC+'-SME'
   REPLACE BRNAL WITH ABRNAL      
ENDIF
IF MSMECEc1<>0
   SELECT VPUPL 
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE DUG WITH MSMECEC1
   REPLACE DATUM WITH MEDATUM
   REPLACE VALUTA WITH MEVALUTA
   REPLACE GRUPA WITH 'SC1'
   replace opis WITH ' SMECE CLANOVA <=4'+GRUPA
   REPLACE BRRAC WITH MBRRAC+'-SC1'
   REPLACE BRNAL WITH ABRNAL      
ENDIF
IF MSMECEc2<>0
   SELECT VPUPL 
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE DUG WITH MSMECEC2
   REPLACE DATUM WITH MEDATUM
   REPLACE VALUTA WITH MEVALUTA
   REPLACE GRUPA WITH 'SC2'
   replace opis WITH ' SMECE CLANOVA >4'+GRUPA
   REPLACE BRRAC WITH MBRRAC+'-SC2'
   REPLACE BRNAL WITH ABRNAL      
ENDIF

IF MKANTADIN<>0
   SELECT VPUPL 
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE DUG WITH MKANTADIN
   REPLACE DATUM WITH MEDATUM
   REPLACE VALUTA WITH MEVALUTA
   REPLACE GRUPA WITH 'KNT'
   replace opis WITH ' KANTE '+GRUPA
   REPLACE BRRAC WITH MBRRAC+'-KNT'
   REPLACE BRNAL WITH ABRNAL      
ENDIF

IF MSMECEN<>0
   SELECT VPUPL 
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE DUG WITH MSMECEN  
   REPLACE DATUM WITH MEDATUM
   REPLACE VALUTA WITH MEVALUTA
   REPLACE GRUPA WITH 'SMN'
   replace opis WITH ' SMECE NEIZGRADJENA '+GRUPA
   REPLACE BRRAC WITH MBRRAC+'-SMN'   
   REPLACE BRNAL WITH ABRNAL      
ENDIF

IF MEKODINAR<>0
   SELECT VPUPL 
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE DUG WITH MEKODINAR
   REPLACE DATUM WITH MEDATUM
   REPLACE VALUTA WITH MEVALUTA
   REPLACE GRUPA WITH 'EKO'
   replace opis WITH ' EKOLOSKI DINAR '+GRUPA
   REPLACE BRRAC WITH MBRRAC+'-EKO'   
   REPLACE BRNAL WITH ABRNAL      
ENDIF

IF MPOREZ<>0
   SELECT VPUPL 
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE DUG WITH MPOREZ
   REPLACE DATUM WITH MEDATUM
   REPLACE VALUTA WITH MEVALUTA
   REPLACE GRUPA WITH 'POR'
   replace opis WITH ' POREZ PDV '+GRUPA
   REPLACE BRRAC WITH MBRRAC+'-POR'   
   REPLACE BRNAL WITH ABRNAL      
ENDIF


IF MSOC<>0
   SELECT VPUPL 
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE DUG WITH -MSOC
   REPLACE DATUM WITH MEDATUM
   REPLACE VALUTA WITH MEVALUTA
   REPLACE GRUPA WITH 'SOC'
   replace opis WITH ' POPUST SOC '+GRUPA
   REPLACE BRRAC WITH MBRRAC+'-SOC'   
   REPLACE BRNAL WITH ABRNAL
   SELECT VP
ENDIF
*----------sada radimo rabat-----------
MRABPROC=0
select VPUPL
set order to 1
select VP
SET ORDER TO 1
SEEK MPIB
IF FOUND()
   select VPUPL
   seek MPIB
   if found()
      mdug=0
      mpot=0
      MPRDUG=0
      MRUKUPNO=0
      do while.not.eof()
         if PIB<>MPIB
            exit
         endif   
         if datum<mdatOD
            mprdug=mprdug+dug-pot
         endif   
         if (datum>=mdatOD.AND.datum<=mdatDO)
            mdug=mdug+dug
            mpot=mpot+pot
         ELSE
            MRUKUPNO=MRUKUPNO+DUG-POT
         ENDIF
         skip
      enddo 
      SELECT VP
      REPLACE ODUG WITH MDUG
      REPLACE OPOT WITH MPOT
      REPLACE OSALDO WITH mprdug+MDUG-MPOT  
      IF OSALDO<=0.and.(mukupno-MRUKUPNO)>0
         MRABAT=MRABPROC*ABS(mukupno-MRUKUPNO)/100
         REPLACE RABAT WITH -MRABAT
         SELECT VPUPL
         IF MRABAT>0
            APPEND BLANK
            REPLACE PIB WITH MPIB
            REPLACE DUG WITH -MRABAT
            REPLACE BRNAL WITH ABRNAL
            REPLACE OPIS WITH 'RABAT '+DTOC(MDATDO)
            REPLACE BRRAC WITH MBRRAC+'-RAB'            
            REPLACE GRUPA WITH 'RAB'
            replace datum with mdatDO
            replace valuta with mdatDO
         ENDIF
      ELSE
         MRABAT=0
      ENDIF   
      SELECT VP
      REPLACE RABAT WITH MRABAT
   endif
ENDIF
select VPUPL
set order to 
*-------kraj rabata-----------------------
SELECT VP
REPLACE SVEGA WITH UKUPNO+DUG-UPLAC+KAMATA+rabat+OSTALO+SOC+POREZ+EKODINAR
*MBRRAC=ALLTRIM(SIFRA)+'-'+ALLTRIM(PIB)+'-'+ALLTRIM(STR(MMESEC,2,0))+'-04'
REPLACE BRRAC WITH MBRRAC
