SELECT JP
MPIB=PIB
MKSSIFRA=KSSIFRA
DO IDEL WITH (KKOCKAX)
SELECT JP
COPY TO &KKOCKA FOR KS='*'
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
*-----------TABELA OBRACUNA------------
select JPOBRAC
MCENOVNIK=CENOVNIK
MBROBRAC=BROBRAC
*------TABELA CENA
select JPCENE
SET ORDER TO 1
SEEK MCENOVNIK
mpstanje=pstanje
mzstanje=zstanje
APOC='ST'+ALLTRIM(STR(MPSTANJE,2,0))
AKRAJ='ST'+ALLTRIM(STR(MZSTANJE,2,0))
MMES=MZSTANJE-MPSTANJE
mEdatum=datum
mEvaluta=valuta
mdatOD2=DTOS(datod)
mdatDO2=DTOS(datdo)
mdatOD=datod
mdatDO=datdo
MBRNAL='O'+REPLICATE('0',2-LEN(ALLTRIM(STR(MBROBRAC,2,0))))+ALLTRIM(STR(MBROBRAC,2,0))
SELECT KOCKA
GO TOP
DO WHILE.NOT.EOF()
   MKSSIFRA=PIB
   MPOT=&AKRAJ-&APOC
   MST0=ST0
   MST1=ST1
   MST2=ST2
   MST3=ST3
   MST4=ST4
   MST5=ST5
   MST6=ST6
   MST7=ST7
   MST8=ST8
   MST9=ST9
   MST10=ST10
   MST11=ST11
   MST12=ST12
   SELECT JP
   SET ORDER TO 4
   SEEK MKSSIFRA
   IF FOUND()
      MUKSTAN=0
      DO WHILE.NOT.EOF()
         IF KSSIFRA<>MKSSIFRA
            EXIT
         ENDIF
         MUKSTAN=MUKSTAN+BRSTAN   
         REPLACE POT WITH MPOT
         REPLACE ST0 WITH MST0
         REPLACE ST1 WITH MST1
         REPLACE ST2 WITH MST2
         REPLACE ST3 WITH MST3
         REPLACE ST4 WITH MST4
         REPLACE ST5 WITH MST5
         REPLACE ST6 WITH MST6
         REPLACE ST7 WITH MST7
         REPLACE ST8 WITH MST8
         REPLACE ST9 WITH MST9
         REPLACE ST10 WITH MST10
         REPLACE ST11 WITH MST11
         REPLACE ST12 WITH MST12
         SKIP
      ENDDO   
      SEEK MKSSIFRA
      IF FOUND()
         DO WHILE.NOT.EOF()
            IF KSSIFRA<>MKSSIFRA
               EXIT
            ENDIF
            REPLACE UKSTAN WITH MUKSTAN
            IF UKSTAN<>0
               REPLACE POJP WITH ROUND(MPOT*BRSTAN/UKSTAN,2)
            ELSE
               REPLACE POJP WITH 0
            ENDIF
            REPLACE DATDOK WITH MEDATUM
            REPLACE VALUTA WITH MEVALUTA
            REPLACE DATOD WITH MDATOD
            REPLACE DATDO WITH MDATDO
            REPLACE BRNAL WITH MBRNAL
            REPLACE UKPOT WITH MPOT
            REPLACE CENOVNIK WITH MCENOVNIK
            JPOBRAC02.LBLIME.Caption=PIB+' '+ALLTRIM(PREZ)+' '+ALLTRIM(IME)+' '+GRUPA+' '+ULICA+' '+ULBROJ            
            SKIP
         ENDDO   
      ENDIF   
   ENDIF
   SELECT KOCKA
   SKIP
ENDDO
*------------------PRENOS INVESTICIONOG ODRZAVANJA
SELECT KOCKA
USE
SELECT JP
MPIB=PIB
MKSSIFRA=KSSIFRA2
DO IDEL WITH (KKOCKAX)
SELECT JP
COPY TO &KKOCKA FOR KS='*'
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
*-----------TABELA OBRACUNA------------
SELECT KOCKA
GO TOP
DO WHILE.NOT.EOF()
   MKSSIFRA=PIB
   mcinvodRZ=cinvodRZ
   MCENAGZ=CENA_GZ
   MLIFT=LIFT
   SELECT JP
   SET ORDER TO 7
   SEEK MKSSIFRA
   IF FOUND()
      BROJAC=0
      DO WHILE.NOT.EOF()
         IF KSSIFRA2<>MKSSIFRA
            EXIT
         ENDIF
         IF KTGPOT='1'
         BROJAC=BROJAC+1
         ENDIF
         REPLACE CINVODRZ WITH MCINVODRZ
         REPLACE CENA_GZ WITH MCENAGZ
         SKIP
      ENDDO  
      IF MLIFT<>0
         IF BROJAC<>0
            SELECT JP
            SET ORDER TO 7
            SEEK MKSSIFRA
            IF FOUND()
               DO WHILE.NOT.EOF()
                  IF KSSIFRA2<>MKSSIFRA
                     EXIT
                  ENDIF
                  REPLACE LIFT WITH ROUND(MLIFT/BROJAC,2)
                  SKIP
               ENDDO  
            ENDIF 
         ENDIF      
      ENDIF
   ENDIF
   SELECT KOCKA
   SKIP
ENDDO       
SELECT KOCKA
USE      
SELECT JP
