SELECT TS
MPIB=PIB
MGRUPA=GRUPA
MNAZIV=NAZIV
MPODNAZ=PODNAZ
*-----------TABELA OBRACUNA------------
select TSOBRAC
MCENOVNIK=CENOVNIK
MBROBRAC=BROBRAC
*------TABELA CENA
select TSCENE
SET ORDER TO 1
SEEK MCENOVNIK
mpstanje=pstanje
mzstanje=zstanje
APOC='ST'+ALLTRIM(STR(MPSTANJE,2,0))
AKRAJ='ST'+ALLTRIM(STR(MZSTANJE,2,0))
MMES=MZSTANJE-MPSTANJE
mEdatum=datum
mEvaluta=valuta
mdatOD2=DTOS(datod)
mdatDO2=DTOS(datdo)
mdatOD=datod
mdatDO=datdo
mcvoda=cvoda
mcDOPV=CDOPV
mckanal=ckanal
mcdOPK=cdOPK
MRABPROC=RABPROC
mprocakont=procakont
MBRNAL='O'+REPLICATE('0',2-LEN(ALLTRIM(STR(MBROBRAC,2,0))))+ALLTRIM(STR(MBROBRAC,2,0))
MPRDUG=0
MCSMECE=CSMECE
MCCISCENJE=CCISCENJE  
MCINVODRZ=CINVODRZ 
MCGRADJZEM=CGRADJZEM
MCOSTALO1=COSTALO1
MCOSTALO2=COSTALO2
MCOSTALO3=COSTALO3
MTOSTALO1=TOSTALO1
MTOSTALO2=TOSTALO2
MTOSTALO3=TOSTALO3

MPPOVODA=PPOVODA
MPPOKANAL=PPOKANAL
MPPOSMECE=PPOSMECE
MPPOGRADJ=PPOGRADJ
MPPOCISCE=PPOCISCE
MPPOINVOD=PPOINVOD
MPPOOSTA1=PPOOSTA1
MPPOOSTA2=PPOOSTA2
MPPOOSTA3=PPOOSTA3

SELECT TS
*---------POCETNI POODACI
   SELECT TS  
   REPLACE DATDOK WITH MEDATUM
   REPLACE VALUTA WITH MEVALUTA
   REPLACE BRNAL WITH MBRNAL
   REPLACE MES WITH MMES
*--------OBRACUN PAUSAL------------------
   IF PAUSAL=' '
      REPLACE POT WITH &AKRAJ-&APOC
      MPOT=POT
   ELSE
      REPLACE POT WITH MMES*MESPAUSAL
      MPOT=POT
   ENDIF
   IF POT<0
      REPLACE POT WITH 0
      MPOT=POT
   ENDIF   
   REPLACE POC WITH &APOC
   REPLACE KRAJ WITH &AKRAJ
   REPLACE UKPOT WITH MPOT
   REPLACE VODA WITH 0
   REPLACE CENOVNIK WITH MCENOVNIK

*------------OBRACUN ZA VODU------------------   
   IF POT>0
      IF PVODA<>' '
         REPLACE VODA WITH POT*MCVODA*(100-POPVODA)/100
         REPLACE DOPV WITH POT*MCDOPV*(100-POPVODA)/100    
         REPLACE PORVODA WITH ROUND(MPPOVODA*VODA/100,2)
      ELSE
         REPLACE VODA WITH 0
         REPLACE DOPV WITH 0
         REPLACE PORVODA WITH 0
      ENDIF
*------------OBRACUN ZA KANALIZACIJU
      IF PKANAL<>' '
         REPLACE KANAL WITH POT*MCKANAL*(100-POPKANAL)/100
         REPLACE DOPK WITH POT*MCDOPK*(100-POPKANAL)/100    
         REPLACE PORKANAL WITH ROUND(MPPOKANAL*KANAL/100,2)
         
      ELSE
         REPLACE KANAL WITH 0
         REPLACE DOPK WITH 0   
         REPLACE PORKANAL WITH 0
      ENDIF
   ELSE
      REPLACE VODA WITH 0
      REPLACE DOPV WITH 0
      REPLACE KANAL WITH 0
      REPLACE DOPK WITH 0   
      REPLACE PORVODA WITH 0
      REPLACE PORKANAL WITH 0
   ENDIF
*------------OBRACUN ZA SMECE
IF PSMECE<>' '
   REPLACE SMECE WITH ROUND(POVOBJ*MCSMECE*MMES*(100-POPSMECE)/100,2)
   REPLACE PORSMECE WITH ROUND(MPPOSMECE*SMECE/100,2)
ELSE
   REPLACE SMECE WITH 0
   REPLACE PORSMECE WITH 0
ENDIF

*------------OBRACUN ZA GRADJEVINSKO ZEMLJISTE
IF PGRADJZEM<>' '
   REPLACE GRADJZEM WITH ROUND(CGRADJZEM*MMES*(100-POPGRADJ)/100,2)
   REPLACE PORGRADJ WITH ROUND(MPPOGRADJ*GRADJZEM/100,2)
ELSE
   REPLACE GRADJZEM WITH 0
   REPLACE PORGRADJ WITH 0
ENDIF
 
*------------OBRACUN ZA CISCENJE ZAJEDNICKIH PROSTORIJA
IF PCISCENJE<>' '
   REPLACE CISCENJE WITH ROUND(MCCISCENJE*MMES*(100-POPCISCE)/100,2)
   REPLACE PORCISCE WITH ROUND(MPPOCISCE*CISCENJE/100,2)
ELSE
   REPLACE CISCENJE WITH 0
   REPLACE PORCISCE WITH 0
ENDIF
   
*------------OBRACUN ZA INVESTICIONO ODRZAVANJE
IF PINVODRZ<>' '
   REPLACE INVODRZ WITH ROUND(MCINVODRZ*MMES*(100-POPINVOD)/100,2)
   REPLACE PORINVOD WITH ROUND(MPPOINVOD*INVODRZ/100,2)
ELSE
   REPLACE INVODRZ WITH 0
   REPLACE PORINVOD WITH 0
ENDIF

*------------OBRACUN ZA OSTALO
IF POSTALO1<>' '
   REPLACE OSTALO1 WITH ROUND(MCOSTALO1*MMES*(100-POPOSTA1)/100,2)
   REPLACE POROSTA1 WITH ROUND(MPPOOSTA1*OSTALO1/100,2)
   REPLACE TOSTALO1 WITH MTOSTALO1
ELSE
   REPLACE OSTALO1 WITH 0
   REPLACE POROSTA1 WITH 0
   REPLACE TOSTALO1 WITH ''
ENDIF

IF POSTALO2<>' '
   REPLACE OSTALO2 WITH ROUND(MCOSTALO2*MMES*(100-POPOSTA2)/100,2)
   REPLACE POROSTA2 WITH ROUND(MPPOOSTA2*OSTALO2/100,2)
   REPLACE TOSTALO2 WITH MTOSTALO2
ELSE
   REPLACE OSTALO2 WITH 0
   REPLACE POROSTA2 WITH 0
   REPLACE TOSTALO2 WITH ''
ENDIF

IF POSTALO3<>' '
   REPLACE OSTALO3 WITH ROUND(MCOSTALO3*MMES*(100-POPOSTA3)/100,2)
   REPLACE POROSTA3 WITH ROUND(MPPOOSTA3*OSTALO3/100,2)
   REPLACE TOSTALO3 WITH MTOSTALO3
ELSE
   REPLACE OSTALO3 WITH 0
   REPLACE POROSTA3 WITH 0
   REPLACE TOSTALO3 WITH ''
ENDIF
*----OBRACUN UKUPNO---------------------
   MUKUPNO=VODA+DOPV+KANAL+DOPK+SMECE+GRADJZEM+CISCENJE+INVODRZ+OSTALO1+OSTALO2+OSTALO3
   REPLACE UKUPNO WITH MUKUPNO   
   REPLACE POREZ WITH PORVODA+PORKANAL+PORSMECE+PORGRADJ+PORCISCE+PORINVOD+POROSTA1+POROSTA2+POROSTA3
   REPLACE SVEGA WITH UKUPNO-RABAT+POREZ

   mispr=0


*---------RASPODELA PORESKIH STOPA I OSNOVICA-----------------
MPORVODA8=0
MPORVODA18=0
MOSNVODA0=0
MOSNVODA8=0
MOSNVODA18=0
MPORKANAL8=0
MPORKANAL18=0
MOSNKANAL0=0
MOSNKANAL8=0
MOSNKANAL18=0
MPORSMECE8=0
MOSNSMECE8=0
MPORSMECE18=0
MOSNSMECE18=0
MOSNSMECE0=0
MPORGRADJ8=0
MOSNGRADJ8=0
MPORGRADJ18=0
MOSNGRADJ18=0
MOSNGRADJ0=0
MPORCISCE8=0
MOSNCISCE8=0
MPORCISCE18=0
MOSNCISCE18=0
MOSNCISCE0=0
MPORINVOD8=0
MOSNINVOD8=0
MPORINVOD18=0
MOSNINVOD18=0
MOSNINVOD0=0
MPPOOSTA18=0
MPOROSTA18=0
MOSNOSTA18=0
MPPOOSTA118=0
MPOROSTA118=0
MOSNOSTA118=0
MOSNOSTA10=0
MPPOOSTA28=0
MPOROSTA28=0
MOSNOSTA28=0
MPPOOSTA218=0
MPOROSTA218=0
MOSNOSTA218=0
MOSNOSTA20=0
MPPOOSTA38=0
MPOROSTA38=0
MOSNOSTA38=0
MPPOOSTA318=0
MPOROSTA318=0
MOSNOSTA318=0
MOSNOSTA30=0

IF MPPOVODA<>0
   IF MPPOVODA=8
      MPORVODA8=PORVODA
      MOSNVODA8=VODA
      MOSNVODA0=DOPV
   ENDIF
   IF MPPOVODA=18
      MPORVODA18=PORVODA
      MOSNVODA18=VODA
      MOSNVODA0=DOPV
   ENDIF      
ELSE
   MOSNVODA0=VODA+DOPV
ENDIF

IF MPPOKANAL<>0
   IF MPPOKANAL=8
      MPORKANALA8=PORKANAL
      MOSNKANAL8=KANAL
      MOSNKANAL0=DOPK
   ENDIF
   IF MPPOKANAL=18
      MPORKANAL18=PORKANAL
      MOSNKANAL18=KANAL
      MOSNKANAL0=DOPK
   ENDIF      
ELSE
   MOSNKANAL0=KANAL+DOPK
ENDIF
   
   
IF MPPOSMECE<>0
   IF MPPOSMECE=8
      MPORSMECE8=PORSMECE
      MOSNSMECE8=SMECE
   ENDIF
   IF MPPOSMECE=18
      MPORSMECE18=PORSMECE
      MOSNSMECE18=SMECE
   ENDIF      
ELSE
   MOSNSMECE0=SMECE
ENDIF

IF MPPOGRADJ<>0
   IF MPPOGRADJ=8
      MPORGRADJ8=PORGRADJ
      MOSNGRADJ8=GRADJZEM
   ENDIF
   IF MPPOGRADJ=18
      MPORGRADJ18=PORGRADJ
      MOSNGRADJ18=GRADJZEM
   ENDIF
ELSE
   MOSNGRADJ0=GRADJZEM
ENDIF

IF MPPOCISCE<>0
   IF MPPOCISCE=8
      MPORCISCE8=PORCISCE
      MOSNCISCE8=CISCENJE
   ENDIF
   IF MPPOCISCE=18
      MPORCISCE18=PORCISCE
      MOSNCISCE18=CISCENJE
   ENDIF
ELSE
   MOSNCISCE0=CISCENJE
ENDIF   

IF MPPOINVOD<>0
   IF MPPOINVOD=8
      MPORINVOD8=PORINVOD
      MOSNINVOD8=INVODRZ
   ENDIF
   IF MPPOINVOD=18
      MPORINVOD18=PORINVOD
      MOSNINVOD18=INVODRZ
   ENDIF
ELSE
   MOSNINVOD0=INVODRZ
ENDIF   

IF MPPOOSTA1<>0
   IF MPPOOSTA18=8
      MPOROSTA18=POROSTA1
      MOSNOSTA18=OSTALO1
   ENDIF
   IF MPPOOSTA118=18
      MPOROSTA118=POROSTA1
      MOSNOSTA118=OSTALO1
   ENDIF
ELSE
   MOSNOSTA10=0
ENDIF   

IF MPPOOSTA2<>0
   IF MPPOOSTA28=8
      MPOROSTA28=POROSTA2
      MOSNOSTA28=OSTALO2
   ENDIF
   IF MPPOOSTA218=18
      MPOROSTA218=POROSTA2
      MOSNOSTA218=OSTALO2
   ENDIF
ELSE
   MOSNOSTA20=0
ENDIF   

IF MPPOOSTA3<>0
   IF MPPOOSTA38=8
      MPOROSTA38=POROSTA3
      MOSNOSTA38=OSTALO3
   ENDIF
   IF MPPOOSTA318=18
      MPOROSTA318=POROSTA3
      MOSNOSTA318=OSTALO3
   ENDIF
ELSE
   MOSNOSTA30=0
ENDIF   

MPOR8=MPORVODA8+MPORKANAL8+MPORSMECE8+MPORGRADJ8+MPORCISCE8+MPORINVOD8+MPOROSTA18+MPOROSTA28+MPOROSTA38
MOSN8=MOSNVODA8+MOSNKANAL8+MOSNSMECE8+MOSNGRADJ8+MOSNCISCE8+MOSNINVOD8+MOSNOSTA18+MOSNOSTA28+MOSNOSTA38
MPOR18=MPORVODA18+MPORKANAL18+MPORSMECE18+MPORGRADJ18+MPORCISCE18+MPORINVOD18+MPOROSTA118+MPOROSTA218+MPOROSTA318
MOSN18=MOSNVODA18+MOSNKANAL18+MOSNSMECE18+MOSNGRADJ18+MOSNCISCE18+MOSNINVOD18+MOSNOSTA118+MOSNOSTA218+MOSNOSTA318
MOSN0=MOSNVODA0+MOSNKANAL0+MOSNSMECE0+MOSNGRADJ0+MOSNCISCE0+MOSNINVOD0+MOSNOSTA10+MOSNOSTA20+MOSNOSTA30

REPLACE OSN0 WITH MOSN0
REPLACE OSN8 WITH MOSN8
REPLACE OSN18 WITH MOSN18
REPLACE POR8 WITH MPOR8
REPLACE POR18 WITH MPOR18

*----------POPUNJAVANJE GLAVNE TABELE----------
   SELECT TS
   MSALDO=SVEGA
   REPLACE SALDO WITH MSALDO
   SET CENTURY OFF
   mbrrac=REPLICATE('0',2-LEN(ALLTRIM(STR(MBROBRAC,2,0))))+ALLTRIM(STR(MBROBRAC,2,0))+SUBSTR(DTOC(MDATDO),7,2)+ALLTRIM(pib)
   SET CENTURY ON
   REPLACE BRRAC WITH MBRRAC
   M1=VAL(mbrrac)
   M2=(M1*100/97)-INT(M1*100/97)
   M3=ROUND(97*M2,0)
   M4=98-M3
   IF M4<=9
      M4='0'+STR(M4,1,0)
   ELSE
      M4=STR(M4,2,0)
   ENDIF      
   REPLACE model WITH +M4+'-'+ALLTRIM(mbrrac)
   
   SELECT TSUPLD
   SET ORDER TO 5
   SET EXACT OFF
   GO TOP
   DO WHILE.T.
      SEEK MBRRAC
      IF FOUND()
         REPLACE PIB WITH SPACE(13)
         REPLACE BRNAL WITH SPACE(6)
         REPLACE BRRAC WITH ''
         REPLACE GRUPA WITH ''
         REPLACE CENOVNIK WITH 0
         REPLACE DATDOK WITH CTOD('')
         REPLACE VALUTA WITH CTOD('')
         REPLACE DATOD WITH CTOD('')
         REPLACE DATDO WITH CTOD('')
         REPLACE CVODA WITH 0
         REPLACE CDOPV WITH 0
         REPLACE CKANAL WITH 0
         REPLACE CDOPK WITH 0
         REPLACE CSMECE WITH 0
         REPLACE CGRADJZEM WITH 0
         REPLACE CCISCENJE WITH 0
         REPLACE CINVODRZ WITH 0

         REPLACE COSTALO1 WITH 0
         REPLACE COSTALO2 WITH 0
         REPLACE COSTALO3 WITH 0

         REPLACE PPOVODA WITH 0
         REPLACE PPOKANAL WITH 0
         REPLACE PPOSMECE WITH 0
         REPLACE PPOGRADJ WITH 0
         REPLACE PPOCISCE WITH 0
         REPLACE PPOINVOD WITH 0
         
         REPLACE PPOOSTA1 WITH 0
         REPLACE PPOOSTA2 WITH 0
         REPLACE PPOOSTA3 WITH 0
         REPLACE POROSTA1 WITH 0
         REPLACE POROSTA2 WITH 0
         REPLACE POROSTA3 WITH 0

         REPLACE POREZ WITH 0
         REPLACE PORVODA WITH 0
         REPLACE PORKANAL WITH 0
         REPLACE PORSMECE WITH 0
         REPLACE PORGRADJ WITH 0
         REPLACE PORCISCE WITH 0
         REPLACE PORINVOD WITH 0

         REPLACE VODA WITH 0
         REPLACE DOPV WITH 0
         REPLACE KANAL WITH 0
         REPLACE DOPK WITH 0
         REPLACE SMECE WITH 0
         REPLACE CISCENJE WITH 0
         REPLACE GRADJZEM WITH 0
         REPLACE INVODRZ WITH 0
         REPLACE OSTALO1 WITH 0
         REPLACE OSTALO2 WITH 0
         REPLACE OSTALO3 WITH 0
         
         REPLACE UKUPNO WITH 0
         REPLACE OSTALO WITH 0
         REPLACE POREZ WITH 0
         REPLACE POC WITH 0
         REPLACE KRAJ WITH 0
         REPLACE POT WITH 0
         REPLACE SALDO WITH 0
         REPLACE SVEGA WITH 0
         REPLACE OSN0 WITH 0
         REPLACE OSN8 WITH 0
         REPLACE OSN18 WITH 0
         REPLACE POR8 WITH 0
         REPLACE POR18 WITH 0
         LOOP 
      ELSE
         EXIT
      ENDIF
   ENDDO   
  
   SELECT TS
   MGRUPA=GRUPA
   MDATDOK=DATDOK
   MVALUTA=VALUTA
   MPAUSAL=PAUSAL
   MMESPAUSAL=MESPAUSAL

   MVODA=VODA
   MDOPV=DOPV
   MKANAL=KANAL
   MDOPK=DOPK
   MSMECE=SMECE
   MCISCENJE=CISCENJE
   MGRADJZEM=GRADJZEM
   MINVODRZ=INVODRZ
   MOSTALO1=OSTALO1
   MOSTALO2=OSTALO2
   MOSTALO3=OSTALO3
      
   MPORVODA =PORVODA
   MPORKANAL=PORKANAL
   MPORSMECE=PORSMECE
   MPORGRADJ=PORGRADJ
   MPORCISCE=PORCISCE
   MPORINVOD=PORINVOD
   MPOROSTA1=POROSTA1
   MPOROSTA2=POROSTA2
   MPOROSTA3=POROSTA3

   MUKUPNO=UKUPNO
   MOSTALO=OSTALO
   MSVEGA=SVEGA
   MPOREZ=POREZ
   MBRRAC=BRRAC
   MMODEL=MODEL
   MPOC=POC
   MKRAJ=KRAJ
   MPOT=POT
   MPVODA=PVODA
   MPKANAL=PKANAL
   MPSMECE=PSMECE
   MPGRADJZEM=PGRADJZEM 
   MPCISCENJE=PCISCENJE
   MPINVODRZ=PINVODRZ
   MPOSTALO1=POSTALO1
   MPOSTALO2=POSTALO2
   MPOSTALO3=POSTALO3
   MPOVOBJ =POVOBJ

   MPOPVODA=POPVODA
   MPOPKANAL=POPKANAL
   MPOPSMECE=POPSMECE
   MVRSTA=VRSTA
   MULICA=ULICA
   MNAZIV=ALLTRIM(NAZIV)
   MPODNAZ=ALLTRIM(PODNAZ)
   mdatcit=datcit
   *-------CENE-----------------
   REPLACE Cvoda WITH Mcvoda
   REPLACE cDOPV WITH MCDOPV
   REPLACE ckanal WITH Mckanal
   REPLACE cdOPK WITH McdOPK
   REPLACE CSMECE WITH MCSMECE
   REPLACE CGRADJZEM WITH MCGRADJZEM 
   REPLACE CCISCENJE WITH MCCISCENJE  
   REPLACE CINVODRZ WITH MCINVODRZ 
   REPLACE COSTALO1 WITH MCOSTALO1
   REPLACE COSTALO2 WITH MCOSTALO2
   REPLACE COSTALO3 WITH MCOSTALO3
   *--------STOPE POREZA-------
   REPLACE PPOVODA WITH MPPOVODA
   REPLACE PPOKANAL WITH MPPOKANAL
   REPLACE PPOSMECE WITH MPPOSMECE
   REPLACE PPOGRADJ WITH MPPOGRADJ
   REPLACE PPOCISCE WITH MPPOCISCE
   REPLACE PPOINVOD WITH MPPOINVOD
   REPLACE PPOOSTA1 WITH MPPOOSTA1
   REPLACE PPOOSTA2 WITH MPPOOSTA2
   REPLACE PPOOSTA3 WITH MPPOOSTA3
   *----------POREZ------------
   REPLACE PORVODA  WITH MPORVODA
   REPLACE PORKANAL WITH MPORKANAL
   REPLACE PORSMECE WITH MPORSMECE
   REPLACE PORGRADJ WITH MPORGRADJ
   REPLACE PORCISCE WITH MPORCISCE
   REPLACE PORINVOD WITH MPORINVOD
   REPLACE POROSTA1 WITH MPOROSTA1
   REPLACE POROSTA2 WITH MPOROSTA2
   REPLACE POROSTA3 WITH MPOROSTA3
   REPLACE DATOD WITH MDATOD
   REPLACE DATDO WITH MDATDO
   
   SCATTER NAME POLJA
   SELECT TSUPLD
   APPEND BLANK
   GATHER NAME POLJA
   SELECT TS
