PROCEDURE JP0TAST
   ON KEY LABEL F1    DO HELPN WITH 'JP0'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   JP0.RELEASE
ENDPROC


PROCEDURE JPATAST
   ON KEY LABEL F1    DO HELPN WITH 'JPA'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       JPA.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE JP00TAST
   ON KEY LABEL F1    DO HELPN WITH 'JP00'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   JP00.RELEASE
ENDPROC
 
PROCEDURE JPOBRAC0TAST
   ON KEY LABEL F1    DO HELPN WITH 'JPOBRAC0'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   JPOBRAC0.RELEASE
ENDPROC
 


PROCEDURE JPAKART0TAST
   ON KEY LABEL F1    DO HELPN WITH 'JPAKART0'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   JPAKART0.RELEASE
ENDPROC


PROCEDURE JPCENETAST
   ON KEY LABEL F1    DO HELPN WITH 'JPCENE'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   JPCENE.RELEASE
ENDPROC

PROCEDURE JPUNOSPOTTAST
   ON KEY LABEL F1    DO HELPN WITH 'JPUNOSPOT'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL F6    DO JPUNPF6   
   ON KEY LABEL ESC   JPUNOSPOT.RELEASE
ENDPROC



PROCEDURE JPKAKOEFTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL ESC       JPKAKOEF.RELEASE
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL F10       DO KAKOEFKOEF 
ENDPROC


PROCEDURE JPUPLDTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       JPUPLD.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC


PROCEDURE JPPOTROSNJATAST
   ON KEY LABEL F1    DO HELPN WITH 'JPPOTROSNJA'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   JPPOTROSNJA.RELEASE
ENDPROC


PROCEDURE JPRACTXTTAST
   ON KEY LABEL F1    DO HELPN WITH 'JPRACTXT'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   JPRACTXT.RELEASE
ENDPROC


PROCEDURE JPRACTX2TAST
   ON KEY LABEL F1    DO HELPN WITH 'JPRACTX2'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   JPRACTX2.RELEASE
ENDPROC

PROCEDURE JPSPISTAST
   ON KEY LABEL F1    DO HELPN WITH 'JPSPIS'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   JPSPIS.RELEASE
ENDPROC

PROCEDURE JPSPISSOCTAST
   ON KEY LABEL F1    DO HELPN WITH 'JPSPISSOC'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   JPSPISSOC.RELEASE
ENDPROC

PROCEDURE JPSPISVLATAST
   ON KEY LABEL F1    DO HELPN WITH 'JPSPISVLA'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   JPSPISVLA.RELEASE
ENDPROC


PROCEDURE JPSPISDUGTAST
   ON KEY LABEL F1    DO HELPN WITH 'JPSPISDUG'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   JPSPISDUG.RELEASE
ENDPROC

PROCEDURE JPFTAST
   ON KEY LABEL F1    DO HELPN WITH 'JPF'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       JPF.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC


PROCEDURE JPFKART0TAST
   ON KEY LABEL F1    DO HELPN WITH 'JPFKART0'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   JPFKART0.RELEASE
ENDPROC

PROCEDURE JPFPOTROSNJATAST
   ON KEY LABEL F1    DO HELPN WITH 'JPFPOTROSNJA'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   JPFPOTROSNJA.RELEASE
ENDPROC

PROCEDURE JPFUNOSPOTTAST
   ON KEY LABEL F1    DO HELPN WITH 'JPFUNOSPOT'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL F6    DO JPUNPF6   
   ON KEY LABEL ESC   JPFUNOSPOT.RELEASE
ENDPROC

PROCEDURE JPVLA0TAST
   ON KEY LABEL F1    DO HELPN WITH 'JPVLA0'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   JPVLA0.RELEASE
ENDPROC

PROCEDURE JPPREGPOTTAST
   ON KEY LABEL F1    DO HELPN WITH 'JPPREGPOT'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   JPPREGPOT.RELEASE
ENDPROC




PROCEDURE JPSPISSALDOKSTAST
   ON KEY LABEL F1    DO HELPN WITH 'JPSPISSALDOKS'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   JPSPISSALDOKS.RELEASE
ENDPROC

PROCEDURE JPSPISOCITTAST
   ON KEY LABEL F1    DO HELPN WITH 'JPSPISOCIT'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   JPSPISOCIT.RELEASE
ENDPROC

PROCEDURE JPSPISNEGATTAST
   ON KEY LABEL F1    DO HELPN WITH 'JPSPISNEGAT'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   JPSPISNEGAT.RELEASE
ENDPROC

PROCEDURE JPUPLPREUZMINALTAST
   ON KEY LABEL F1    DO HELPN WITH 'JPUPLPREUZMINAL'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   JPUPLPREUZMINAL.RELEASE
ENDPROC

PROCEDURE JPANALIZVOTAST
   ON KEY LABEL F1    DO HELPN WITH 'JPANALIZVO'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JPANALIZVO.RELEASE
ENDPROC

PROCEDURE JPPODTAST
   ON KEY LABEL F1    DO HELPN WITH 'JPPOD'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JPPOD.RELEASE
ENDPROC

PROCEDURE JPUPLTAST
   ON KEY LABEL F1    DO HELPN WITH 'JPUPL'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JPUPL.RELEASE
ENDPROC

PROCEDURE JPULICETAST
   ON KEY LABEL F1    DO HELPN WITH 'JPULICE'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JPULICE.RELEASE
ENDPROC

PROCEDURE JPOBRACTAST
   ON KEY LABEL F1    DO HELPN WITH 'JPOBRAC'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JPOBRAC.RELEASE
ENDPROC

PROCEDURE JPGRUPATAST
   ON KEY LABEL F1    DO HELPN WITH 'JPGRUPA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JPGRUPA.RELEASE
ENDPROC

PROCEDURE JPSPISULTAST
   ON KEY LABEL F1    DO HELPN WITH 'JPSPISUL'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JPSPISUL.RELEASE
ENDPROC

PROCEDURE JPSPISULETAST
   ON KEY LABEL F1    DO HELPN WITH 'JPSPISULE'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JPSPISULE.RELEASE
ENDPROC

PROCEDURE JPSALDOTAST
   ON KEY LABEL F1    DO HELPN WITH 'JPSALDO'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JPSALDO.RELEASE
ENDPROC

PROCEDURE JPSOCTAST
   ON KEY LABEL F1    DO HELPN WITH 'JPSOC'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JPSOC.RELEASE
ENDPROC

PROCEDURE JPSALULTAST
   ON KEY LABEL F1    DO HELPN WITH 'JPSALUL'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JPSALUL.RELEASE
ENDPROC


PROCEDURE JPGRUPAKTAST
   ON KEY LABEL F1    DO HELPN WITH 'JPGRUPAK'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JPGRUPAK.RELEASE
ENDPROC


PROCEDURE JPNALSALTAST
   ON KEY LABEL F1    DO HELPN WITH 'JPNALSAL'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JPNALSAL.RELEASE
ENDPROC

PROCEDURE JPFTXTTAST
   ON KEY LABEL F1    DO HELPN WITH 'JPFTXT'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JPFTXT.RELEASE
ENDPROC

PROCEDURE JPFPODTAST
   ON KEY LABEL F1    DO HELPN WITH 'JPFPOD'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JPFPOD.RELEASE
ENDPROC


PROCEDURE JPFOBRACTAST
   ON KEY LABEL F1    DO HELPN WITH 'JPFOBRAC'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       JPFOBRAC.RELEASE
ENDPROC

