IF FILE(KKOCKAX)
   DELETE FILE &KKOCKAX
ENDIF
SELECT VPUPL  
SET ORDER TO 4
TOTAL ON GRUPA TO &KKOCKA FIELDS DUG,POT FOR DATUM>=ADAT0.AND.DATUM<=ADAT1
USE &KKOCKA IN 0 ALIAS KOCKA
SELECT VPGRUPAK
SET ORDER TO 1
SELECT KOCKA
SET RELATION TO GRUPA INTO VPGRUPAK ADDITIVE
*GVPUPGRSAL=MREPORTI+'VPUPGRSAL'
*EXTERNAL REPORT (GVPUPGRSAL)
REPORT FORM JPUPGRSAL FOR BRKAL=MBRKAL PREVIEW
SELECT KOCKA
SET RELATION TO 
USE
SELECT VPGRUPAK
SET ORDER TO 
SELECT VPUPL
SET ORDER TO 


