MBRKAL=BRKAL
PUSH KEY CLEAR
SELECT kal
LOCATE FOR BRKAL=MBRKAL

   *REPORT FORM KAL3NNDNEVNIPOVB FOR BRKAL=MBRKAL PREVIEW 
      mfile='KAL3NNDNEVNIPOVB'
      uslov="BRKAL=MBRKAL"
      DO printer_bullzip WITH mdata02,mfile,uslov
   
   SELECT kal

LOCATE FOR BRKAL=MBRKAL
   SET ORDER TO 
  POP KEY