MBRKAL=BRKAL
PUSH KEY CLEAR
SELECT KAL
MBRKAL=BRKAL
set order to 1
LOCATE FOR BRKAL=MBRKAL

*REPORT FORM KAL3NNDNEVNIB FOR BRKAL=MBRKAL PREVIEW 
      mfile='KAL3NNDNEVNIB'
      uslov="BRKAL=MBRKAL"
      DO printer_bullzip WITH mdata02,mfile,uslov

SELECT kal
LOCATE FOR BRKAL=MBRKAL
SET ORDER TO 
POP KEY