PUSH KEY CLEAR
   DO IDEL WITH (KKOCKAX)
   DO IDEL WITH (KKOCKAX2)


SET ORDER TO 2
TOTAL ON NAZIV FIELDS IZNOS,MARZA,PLACPOR,RABAT,VELVRED,MALVRED,TRDOB,POREZ FOR PRENOS=' '  TO &KKOCKA
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
SELECT KOCKA
GO TOP
DO WHILE.NOT.EOF()
   REPLACE NABVRED WITH IZNOS-RABAT+PLACPOR+TRDOB
   SKIP
ENDDO   
GO TOP
SET ORDER TO 
SORT ON NABVRED TO &KKOCKA2 DESCEND
DELETE ALL
PACK

APPEND FROM &KKOCKA2
GO TOP
MMALVRED=0
MMARZA=0
DO WHILE.NOT.EOF()
   MMALVRED=MMALVRED+NABVRED
   MMARZA=MMARZA+MARZA
   SKIP
ENDDO   
GO TOP
DO WHILE.NOT.EOF()
   IF MMALVRED<>0
      MPROMET=ROUND(nabVRED*100/MMALVRED,2)
      REPLACE IZNOS WITH MPROMET
   ENDIF
   IF MMARZA<>0
      MPROMET=ROUND(MARZA*100/MMARZA,2)
      REPLACE RABAT WITH MPROMET
   ENDIF
   SKIP
ENDDO
GO TOP   
PUSH KEY CLEAR

*REPORT FORM KALIZVAN01  PREVIEW 
      mfile='KALIZVAN01'
      uslov=""
      DO printer_bullzip WITH mdata02,mfile,uslov

POP KEY
SELECT KOCKA
USE
SELECT KALI
POP KEY