PUSH KEY CLEAR
IF TNET=1
   SELECT KAL
   SET RELATION TO
   USE
   USE &KKAL IN 0 EXCLU ALIAS KAL
   SELECT KAL
   DELETE ALL FOR KOL=0
   PACK
   USE
ELSE
   SELECT KAL
   SET RELATION TO
   USE
   USE &KKALP IN 0 EXCLU ALIAS KAL
   SELECT KAL
   DELETE ALL FOR KOL=0
   PACK
   USE
ENDIF
KALSERV.RELEASE
POP KEY