IF TFPOSSIF='D'.AND.TNEZAJEDNO<>'D'
   USE ROB IN 0 ALIAS ROB0
   SELECT KAL
   SET ORDER TO 
   DO WHILE.NOT.EOF()
      MRSIF=RSIF
      SELECT ROB
      LOCATE FOR RSIF=MRSIF
      IF.NOT.FOUND()
         SELECT ROB0
         LOCATE FOR RSIF=MRSIF
         IF FOUND()
            SCATTER NAME POLJA
            SELECT ROB
            APPEND BLANK
            GATHER NAME POLJA
            SELECT ROB
         ENDIF   
      ENDIF      
      SELECT KAL
      SKIP
   ENDDO   
   SELECT ROB0
   USE
   SELECT KAL
   GO TOP
   SET ORDER TO 
   KAL.GRD0.SETFOCUS
ENDIF   
