PUSH KEY CLEAR
   DO IDEL WITH (KKOCKAX)

SET ORDER TO 2
TOTAL ON NAZIV FIELDS IZNOS,MARZA,PLACPOR,PLACPORU,PLACPORZ,PLACPORD,PLACPORC,RABAT,VELVRED,MALVRED,TRDOB,POREZ,POLJDIN   TO &KKOCKA
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
SELECT KOCKA
GO TOP
DO WHILE.NOT.EOF()
   REPLACE NABVRED WITH IZNOS-RABAT+PLACPOR+PLACPORU+PLACPORZ+PLACPORD+PLACPORC+trdob+POLJDIN
   SKIP
ENDDO   
GO TOP
PUSH KEY CLEAR

*REPORT FORM KALIZV2F10 PREVIEW 
      mfile='KALIZV2F10'
      uslov=""
      DO printer_bullzip WITH mdata02,mfile,uslov

POP KEY
SELECT KOCKA
USE
SELECT KALI
POP KEY