PARAMETERS AGDE
PUSH KEY CLEAR
SET ORDER TO 1
IF AGDE=0
*REPORT FORM KALIZV20DNEV  PREVIEW 
      mfile='KALIZV20DNEV'
      uslov=""
      DO printer_bullzip WITH mdata02,mfile,uslov

ELSE
REPORT FORM KALIZV20DNEV  TO PRINTER PROMPT
ENDIF
POP KEY
