PUSH KEY CLEAR
SELECT KAL
IF KALG.ARHIVA=' '
MBRKAL=BRKAL
SET ORDER TO 1
LOCATE FOR BRKAL=MBRKAL
IF FOUND()
   DO WHILE.NOT.EOF()
      IF BRKAL<>MBRKAL
         EXIT
      ENDIF
      REPLACE CENA WITH ROUND(CENA*100/(100+PROCPOR),2)
      SKIP
   ENDDO   
ENDIF
LOCATE FOR BRKAL=MBRKAL

SET ORDER TO 
ENDIF
KAL.GRD0.SETFOCUS
KAL.GRD0.REFRESH
POP KEY