PUSH KEY CLEAR
   DO IDEL WITH (KKOCKAX)
SELECT KALI   
SET ORDER TO 4
TOTAL ON FVRSTA FIELDS IZNOS,MARZA,PLACPOR,PLACPORU,PLACPORZ,PLACPORD,PLACPORC,RABAT,VELVRED,MALVRED,TRDOB,POREZ,POLJDIN   TO &KKOCKA
use &kkalprn in 0 order 1 alias kalprn 

USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
SELECT KOCKA
GO TOP
DO WHILE.NOT.EOF()
   REPLACE NABVRED WITH IZNOS-RABAT+PLACPOR+PLACPORU+PLACPORZ+PLACPORD+PLACPORC+trdob+POLJDIN
   MFVRSTA=FVRSTA
   SELECT KALPRN
   LOCATE FOR FVRSTA=MFVRSTA
   IF FOUND()
      MFNAZ=FNAZ
   ELSE
      MFNAZ='*****NEMA****'   
   ENDIF
   SELECT KOCKA
   REPLACE NAZIV WITH MFNAZ   
   SKIP
ENDDO   
GO TOP
PUSH KEY CLEAR
*REPORT FORM KALIZV2F10D  PREVIEW 
      mfile='KALIZV2F10D'
      uslov=""
      DO printer_bullzip WITH mdata02,mfile,uslov

POP KEY
SELECT KOCKA
USE
SELECT KALPRN
USE
SELECT KALI
POP KEY