PUSH KEY CLEAR
   DO IDEL WITH (KKOCKAX)
   DO IDEL WITH (KKOCKAX2)   
SET ORDER TO 3
COPY TO &KKOCKA
USE &KKOCKA IN 0 ALIAS KOCKA EXCLUSIVE
SELECT KOCKA
INDEX ON TARIFA TAG PROCPOR
SET ORDER TO 1
TOTAL ON TARIFA FIELDS TARIFA,IZNOS,MARZA,PLACPOR,PLACPORU,PLACPORZ,PLACPORD,PLACPORC,RABAT,VELVRED,MALVRED,TRDOB,POREZ,POLJDIN   TO &KKOCKA2
SELECT KOCKA
ZAP
APPEND FROM &KKOCKA2
GO TOP
DO WHILE.NOT.EOF()
   REPLACE NABVRED WITH IZNOS-RABAT+PLACPOR+PLACPORU+PLACPORZ+PLACPORD+PLACPORC+trdob+POLJDIN
   SKIP
ENDDO   
GO TOP
PUSH KEY CLEAR

*REPORT FORM KALIZV2F10TAR  PREVIEW 
      mfile='KALIZV2F10TAR'
      uslov=""
      DO printer_bullzip WITH mdata02,mfile,uslov

POP KEY
SELECT KOCKA
USE
SELECT KALI
POP KEY