PUSH KEY CLEAR
DO IDEL WITH (KKOCKAX)
USE AAAN IN 0 
SELECT AAAN
MREC=RECCOUNT()
USE
SELECT KAL
SET RELATION TO
SELECT KALG
COPY TO &KKOCKA FOR PRENOS<>' '
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
SELECT KOCKA
*INDEX ON BRNAL TAG BRNAL
*SET ORDER TO 1

FOR I=1 TO MREC
   MANAL='ANAL'+ALLTRIM(STR(I,2,0))
   USE &MANAL IN 0 ALIAS ANAL ORDER 4
   SELECT KOCKA
   GO TOP
   DO WHILE.NOT.EOF()
      MBRNAL=BRNAL
      SELECT ANAL
      SEEK MBRNAL
      IF FOUND()
         DO WHILE.NOT.EOF()
            IF BRNAL<>MBRNAL
               EXIT
            ENDIF
            REPLACE DUG WITH 0
            REPLACE POT WITH 0
            REPLACE DEVDUG WITH 0
            REPLACE DEVPOT WITH 0
            SKIP
         ENDDO      
      ENDIF
      SELECT KOCKA
      SKIP
   ENDDO   
   SELECT ANAL
   USE
   SELECT KOCKA
NEXT   
SELECT KOCKA
USE
SELECT KAL
SET RELATION TO BRKAL INTO KALG  ADDITIVE
SET RELATION TO RSIF INTO ROB ADDITIVE
GO TOP
POP KEY