MBRKAL=BRKAL
PUSH KEY CLEAR
DO IDEL WITH (KKOCKAX)
USE KOMKIR IN 0 EXCLUSIVE
SELECT KOMKIR
ZAP
SELECT KAL
MDATDOK=DATDOK
SET ORDER TO 1
SELECT KALG
COPY TO &KKOCKA FOR DATDOK=MDATDOK.AND.(PRODAJA='P'.OR.PRODAJA='V')
*---------UNOSIMO TEKUCE STANJE---------
SELECT KOMKIR
APPEND FROM &KKOCKA
GO TOP
DO WHILE.NOT.EOF()
   MBRKAL=BRKAL
   MIZNOS=0
   MIZNOSU=0
   MKOL=0
   MVRSTAROBE=SPACE(25)
   MJED=SPACE(10)
   SELECT KAL
   SEEK MBRKAL
   IF FOUND()
      MVRSTAROBE=ROB.VRSTAROBE
      MJRED=ROB.JED
      DO WHILE.NOT.EOF()
         IF BRKAL<>MBRKAL
            EXIT
         ENDIF      
         MIZNOS=MIZNOS+IZNOS   
         MKOL=MKOL+KOL
         SKIP
      ENDDO   
   ENDIF
   SELECT KOMKIR
   REPLACE IZNOS WITH MIZNOS
   REPLACE KOL WITH MKOL
   REPLACE VRSTAROBE WITH MVRSTAROBE
   REPLACE JED WITH MJED
   REPLACE BRKAL WITH MBRKAL
   SKIP
ENDDO   

*--------TRAZI SE PRETHODNO STANJE-------------
SELECT KAL
SET ORDER TO 1
SET RELATION TO
SELECT KALG
SET RELATION TO
SET ORDER TO 4
SELECT KOMKIR
GO TOP
DO WHILE.NOT.EOF()
   MSIFRA=SIFRA
   MIZNOSPRE=0
   SELECT KALG
      SEEK MSIFRA
      IF FOUND()
         DO WHILE.NOT.EOF()
            IF SIFRA<>MSIFRA
               EXIT
            ENDIF
            IF DATDOK<MDATDOK
               MBRKAL=BRKAL
               SELECT KAL
               SEEK MBRKAL
               IF FOUND()
                  DO WHILE.NOT.EOF()
                     IF BRKAL<>MBRKAL
                        EXIT
                     ENDIF   
                     IF PRODAJA='V'
                        MIZNOSPRE=MIZNOSPRE+IZNOS
                     ENDIF
                     SKIP
                  ENDDO   
               ENDIF
            ENDIF
            SELECT KALG
            SKIP
         ENDDO      
      ENDIF
   SELECT KOMKIR
   REPLACE IZNOSPRE WITH MIZNOSPRE
   SKIP
ENDDO   
SELECT KALG
SET ORDER TO 1
SELECT KOMKIR
SET RELATION TO SIFRA INTO AN0 ADDITIVE
SET RELATION TO BRKAL INTO KALG  ADDITIVE
GO TOP
DO WHILE.NOT.EOF()
   REPLACE UKUPNO WITH IZNOS+IZNOSPRE
   SKIP
ENDDO   
GO TOP
*REPORT FORM KALKOMIS3  PREVIEW 
      mfile='KALKOMIS3'
      uslov=""
      DO printer_bullzip WITH mdata02,mfile,uslov

SELECT KOMKIR
USE
SELECT kal
LOCATE FOR BRKAL=MBRKAL
SELECT KALG
SET ORDER TO 1
SET RELATION TO SIFRA INTO AN0 ADDITIVE
SET RELATION TO FVRSTA INTO KALPRN ADDITIVE
SELECT kal
SET RELATION TO BRKAL INTO KALG  ADDITIVE
SET RELATION TO RSIF INTO ROB ADDITIVE

SET ORDER TO 
POP KEY