PUSH KEY CLEAR
*SET STEP ON
KALNOVA.GRD0.RECORDSOURCE=''
SELECT magg
GO BOTTOM
MBRKAL=BRKAL
MMREC=RECCOUNT()
*use
MNLEN=LEN(ALLTRIM(STR(VAL(ALLTRIM(MBRKAL))+1,6,0)))
MNBRKAL=REPLI('0',6-MNLEN)+ALLTRIM(STR(VAL(ALLTRIM(MBRKAL))+1,6,0))
SELECT MAGg
LOCATE FOR BRKAL=MNBRKAL
IF.NOT.FOUND()
   APPEND BLANK
   REPLACE BRKAL WITH MNBRKAL
   REPLACE OPER WITH AAOPER
ENDIF
SELECT MAGG
SCATTER NAME POLJA
SELECT KALG
APPEND BLANK
GATHER NAME POLJA
SELECT MAGG
KALNOVA.GRD0.RECORDSOURCE='MAGG'
KALNOVA.GRD0.SETFOCUS
KALNOVA.REFRESH
POP KEY
