PUSH KEY CLEAR

*KAL.GRD0.COLUMN6.SETFOCUS
KAL.CMDKALNALGOT.SETFOCUS
MIME='KAL'
CLOSE ALL TABLES
KAL.RELEASE
PUBLIC TKOJI
TKOJI='NALGK'
TANAL='NALAP'
TGKREDNI='1'
*DO FORM NALP WITH 'NALAP'
DO FORM NALP
KEYBOARD '{ENTER}' 
POP KEY
