PUSH KEY CLEAR
SELECT KALG
mnbrkal=brkal
IF ARHIVA=' '
   IF ALLTRIM(OPER)=AAOPER
   SELECT KAL
   SET RELATION TO
   SELECT KALG
         LOCATE FOR BRKAL=MNBRKAL

   IF.NOT.FOUND()
      APPEND BLANK
      REPLACE BRKAL WITH MNBRKAL
      REPLACE OPER WITH AAOPER
   ENDIF      
   DO FORM KALZAG
   SELECT KAL
   APPEND BLANK
   REPLACE BRKAL WITH MNBRKAL
   SET ORDER TO 1
         LOCATE FOR BRKAL=MNBRKAL

   SET RELATION TO BRKAL INTO KALG ADDITIVE
   SET RELATION TO RSIF INTO ROB ADDITIVE
   REPLACE DATDOK WITH KALG.DATDOK    
   SET ORDER TO 
   GO BOTTOM
   KALNOVA.RELEASE
   kal.grd0.setfocus
   kal.refresh
   ELSE
      PUBLIC PPORUKA
      PPORUKA=' KALKULACIJU '+MNBRKAL+' JE OTVORIO DRUGI OPERATER-OTVORITE NOVU '
      DO PORUKA
   ENDIF   
ELSE
   PUBLIC PPORUKA
   PPORUKA=' KALKULACIJA '+MNBRKAL+' JE PROKNJIZENA  OTVORITE NOVU '
   DO PORUKA
ENDIF
POP KEY