PUSH KEY CLEAR
SELECT KALG
GO BOTTOM
MBRKAL=BRKAL
MNLEN=LEN(ALLTRIM(STR(VAL(ALLTRIM(MBRKAL))+1,6,0)))
MNBRKAL=REPLI('0',6-MNLEN)+ALLTRIM(STR(VAL(ALLTRIM(MBRKAL))+1,6,0))
APPEND BLANK
REPLACE BRKAL WITH MNBRKAL
REPLACE OPER WITH AAOPER
KALNOVA.GRD0.SETFOCUS
POP KEY
KALNOVA.REFRESH