PUSH KEY CLEAR
SELECT KAL
REPLACE KOL WITH 0
REPLACE CENA WITH 0
REPLACE IZNOS WITH 0
REPLACE VELCENA WITH 0
REPLACE VELVRED WITH 0
REPLACE MARPROC WITH 0
REPLACE MARZA WITH 0
REPLACE RABPROC WITH 0
REPLACE RABAT WITH 0
REPLACE ZAVPROC WITH 0
REPLACE ZAVISNI WITH 0
REPLACE ZAVPROCN WITH 0
REPLACE ZAVISNIN WITH 0
REPLACE ZAVPROCC WITH 0
REPLACE ZAVISNIC WITH 0
REPLACE ZAVPRC2 WITH 0
REPLACE ZAVISC2 WITH 0
REPLACE ZAVPRC3 WITH 0
REPLACE ZAVISC3 WITH 0
REPLACE PORKPROC WITH 0
REPLACE PORKOREKC WITH 0
REPLACE TRJDOB WITH 0
REPLACE TRDOB WITH 0
REPLACE TRJDOBN WITH 0
REPLACE TRDOBN WITH 0
REPLACE ZAOKRUZ WITH 0
REPLACE NABCENA WITH 0
REPLACE NABVRED WITH 0
REPLACE TARIFA WITH ' '
REPLACE PROCPOR WITH 0
REPLACE POREZ WITH 0
REPLACE MALCENA WITH 0
REPLACE MALVRED WITH 0
REPLACE POLJPROC WITH 0
REPLACE POLJDIN WITH 0
REPLACE CARPROC WITH 0
REPLACE CARDIN WITH 0
REPLACE AKCCENA WITH 0
REPLACE AKCVRED WITH 0
REPLACE PLACPOR WITH 0
REPLACE PLACPORZ WITH 0
REPLACE PLACPORU WITH 0
REPLACE PLACPORC WITH 0
REPLACE PROCPORD WITH 0
REPLACE PLACPORD WITH 0
REPLACE MARZAKOR WITH 0
REPLACE DEVCENA WITH 0
REPLACE DEVVRED WITH 0
POP KEY
