PUSH KEY CLEAR
KAL.GRD0.COLUMN6.SETFOCUS
IF KALG.ARHIVA='*'
   IF KALG.ARHIVA2=' '
      SELECT KALG
      REPLACE ARHIVA WITH ' '
   ELSE
      SELECT KALG
      IF PPASNIVO=1
         REPLACE ARHIVA WITH ' '
      ENDIF   
   ENDIF
   SELECT KAL
ELSE
   SELECT KALG
   REPLACE ARHIVA WITH '*'
   SELECT KAL
ENDIF
POP KEY
