PUSH KEY CLEAR
   MBRKAL=BRKAL
   IF KALG.ARHIVA=' '
      SELECT KAL
      SET RELATION TO
      SELECT KALG
      DO FORM KALPROMENINAL
      MDATDOK=DATDOK
      SELECT KAL
      SET RELATION TO BRKAL INTO KALG ADDITIVE
      SET RELATION TO RSIF INTO ROB ADDITIVE
      SET ORDER TO 1
         LOCATE FOR BRKAL=MBRKAL

      SET ORDER TO   
   ENDIF
POP KEY