PUSH KEY CLEAR
   SET ORDER TO 
   APPEND BLANK
   REPLACE FVRSTA WITH STR(RECNO(),3,0)
   GO BOTTOM
   KALPRN.GRD0.REFRESH
   DO KALPRNKART
   KALPRN.GRD0.REFRESH
   KALPRN.GRD0.COLUMN2.SETFOCUS
POP KEY
KALPRN.REFRESH  
