PUSH KEY CLEAR
IF KALG.ARHIVA=' '
   MBRKAL=BRKAL
   SET ORDER TO 1
LOCATE FOR BRKAL=MBRKAL
   IF FOUND()
      DO WHILE.NOT.EOF()
         IF BRKAL<>MBRKAL
            EXIT
         ENDIF
         IF TOBJEKAT='M'
            REPLACE MALCENA WITH ROB.MALCENA
         ELSE
            REPLACE VELCENA WITH ROB.VELCENA
         ENDIF
         DO KALRAC    
         SKIP
      ENDDO   
   ENDIF
   LOCATE FOR BRKAL=MBRKAL

   SET ORDER TO  
ENDIF
POP KEY