PUSH KEY CLEAR
KAL.CMDKALPRENDEVCEN.SETFOCUS
IF KALG.ARHIVA=' '
   mbrkal=brkal
   SELECT kal
   SET ORDER TO 1
LOCATE FOR BRKAL=MBRKAL
   IF FOUND()
      MDATNAB=DATDOK
      DO WHILE.NOT.EOF()
         IF BRKAL<>MBRKAL
            EXIT
         ENDIF 
         REPLACE DEVCENA WITH CENA
         REPLACE DEVVRED WITH ROUND(KOL*DEVCENA,3)
         SKIP
      ENDDO   
   endif   
   LOCATE FOR BRKAL=MBRKAL

   SET ORDER TO 
ENDIF
KAL.GRD0.SETFOCUS
POP KEY
KAL.REFRESH
