PUSH KEY CLEAR
SELECT KAL
IF KOL=0
   DO KALNULE
ELSE
IF CENA=0
   IF TOBJEKAT='V'
      REPLACE CENA WITH roB.ZADNAB
   ELSE
      REPLACE CENA WITH roB.ZADNABM
   ENDIF
ENDIF            
*SET STEP ON  

IF VELCENA=0 
   REPLACE VELCENA WITH ROB.VELCENA
ENDIF

IF MALCENA=0
   REPLACE MALCENA WITH ROB.MALCENA
ENDIF   
      REPLACE IZNOS WITH KOL*CENA
      REPLACE VELVRED WITH KOL*VELCENA
      REPLACE TRDOB WITH KOL*TRJDOB   
      REPLACE MALVRED WITH KOL*MALCENA
      REPLACE AKCVRED WITH KOL*AKCCENA
   IF TOBJEKAT='M'
      IF KALG.OPDV<>' '
         REPLACE POREZ WITH ROUND(MALVRED*PROCPOR/(100+PROCPOR),2)
      ELSE
         REPLACE POREZ WITH 0
      ENDIF
      REPLACE VELVRED WITH MALVRED-POREZ
      IF KOL<>0
         REPLACE VELCENA WITH ROUND(VELVRED/KOL,2)
      ENDIF   

   ENDIF   
   IF RABPROC<>0.AND.IZNOS<>0
      REPLACE RABAT WITH ROUND(IZNOS*RABPROC/100,2)
   ELSE
      REPLACE RABAT WITH 0   
   ENDIF
   *-----------SVE VRSTE ZAVISNIH TROSKOVA----------------------
   IF ZAVPROCC=0
      REPLACE ZAVISNIC WITH 0
   ENDIF
   IF ZAVPROC=0
      REPLACE ZAVISNI WITH 0
   ENDIF
   IF ZAVPRC2=0
      REPLACE ZAVISC2 WITH 0
   ENDIF
   IF ZAVPRC2=0
      REPLACE ZAVISC2 WITH 0
   ENDIF
   IF ZAVISNIC<>0.AND.ZAVPROCC=0
      REPLACE ZAVPROCC WITH ROUND(ZAVISNIC*100/(IZNOS-RABAT),4)
   ENDIF
   IF ZAVPROCC<>0
      REPLACE ZAVISNIC WITH ROUND(ZAVPROCC*(IZNOS-RABAT)/100,2)
   ELSE
      REPLACE ZAVISNIC WITH 0
   ENDIF
   IF ZAVISC2<>0.AND.ZAVPRC2=0
      REPLACE ZAVPRC2 WITH ROUND(ZAVISC2*100/(IZNOS-RABAT),4)
   ENDIF
   IF ZAVPRC2<>0
      REPLACE ZAVISC2 WITH ROUND(ZAVPRC2*(IZNOS-RABAT)/100,2)
   ELSE
      REPLACE ZAVISC2 WITH 0
   ENDIF
   IF ZAVPRC3<>0
      REPLACE ZAVISC3 WITH ROUND(ZAVPRC3*(IZNOS-RABAT)/100,2)
   ELSE
      REPLACE ZAVISC3 WITH 0
   ENDIF
   IF ZAVISNI<>0.AND.ZAVPROC=0
      REPLACE ZAVPROC WITH ROUND(ZAVISNI*100/(IZNOS-RABAT),4)
   ENDIF
   IF ZAVPROC<>0
      REPLACE ZAVISNI WITH ROUND(ZAVPROC*(IZNOS-RABAT)/100,2)
   ELSE
      REPLACE ZAVISNI WITH 0
   ENDIF
   IF ZAVPROCN=0
      REPLACE ZAVISNIN WITH 0
   ENDIF
   IF ZAVISNIN<>0.AND.ZAVPROCN=0
      REPLACE ZAVPROCN WITH ROUND(ZAVISNIN*100/(IZNOS-RABAT),4)
   ENDIF
   IF ZAVPROCN<>0
      REPLACE ZAVISNIN WITH ROUND(ZAVPROCN*(IZNOS-RABAT)/100,2)
   ELSE
      REPLACE ZAVISNIN WITH 0
   ENDIF
   IF TRJDOB<>0
      REPLACE TRDOB WITH ROUND(TRJDOB*KOL,2)
   ENDIF
   IF TRJDOBN<>0
      REPLACE TRDOBN WITH ROUND(TRJDOBN*KOL,2)
   ENDIF
   IF ZAVPROC<>0.AND.IZNOS<>0
      REPLACE ZAVISNI WITH ROUND((IZNOS-RABAT+trdob)*ZAVPROC/100,2)
   ELSE
      REPLACE ZAVISNI WITH 0   
   ENDIF
   IF PORKPROC<>0
      REPLACE PORKOREKC WITH ROUND(PORKPROC*(IZNOS-RABAT)/100,2)
   ELSE
      REPLACE PORKOREKC WITH 0
   ENDIF


   *------------CARINA-------------------------------------

   IF CARPROC<>0
      REPLACE CARDIN WITH ROUND((IZNOS+ZAVISNIC)*CARPROC/100,3)
   ELSE
      REPLACE CARDIN WITH 0
   ENDIF
*   SET STEP ON 
   MNABAVNA=(IZNOS-RABAT+ZAVISNI+ZAVISNIN+ZAVISNIC+ZAVISC2+zavisc3+CARDIN+TRDOB+TRDOBN+ZAOKRUZ)

   REPLACE NABVRED WITH MNABAVNA
   
   IF TNABAVNA='D'
      IF KOL<>0.AND.VELCENA=0
         REPLACE VELCENA WITH ROUND(MNABAVNA/KOL,2)
         REPLACE VELVRED WITH ROUND(KOL*VELCENA,2)
      ENDIF
   ENDIF      
   
   IF NABVRED<>0.AND.KOL<>0
      REPLACE NABCENA WITH ROUND(NABVRED/KOL,3)
   ELSE
      REPLACE NABCENA WITH 0
   ENDIF      
   
   IF NABVRED<>0.AND.VELVRED<>0
      REPLACE MARZA WITH VELVRED-NABVRED-akcvred
      REPLACE MARPROC WITH ROUND(MARZA*100/NABVRED,5)
     
   ELSE
      REPLACE MARZA WITH 0
      REPLACE MARPROC WITH 0
   ENDIF
    
   IF KALG.OPDV<>' '
      REPLACE POREZ WITH ROUND(VELVRED*PROCPOR/100,2)
   ELSE
      REPLACE POREZ WITH 0
   ENDIF
   *------------PLACENI POREZ---------------------------
   *-------AKO NIJE CARINA------------------------------
*   IF CARDIN=0
   IF KALG.DEVIZNA=' ' 
      IF POLJPROC=0
         IF KALG.PPDV<>' '
            REPLACE PLACPOR WITH ROUND((IZNOS-RABAT+ZAVISNI)*PROCPOR/100,2)
         ELSE
            REPLACE PLACPOR WITH 0
         ENDIF
         REPLACE POLJDIN WITH 0
      ELSE
         REPLACE PLACPOR WITH 0
         REPLACE POLJDIN WITH ROUND((IZNOS-RABAT+ZAVISNI)*POLJPROC/100,2)
      ENDIF
      REPLACE PLACPORU WITH 0
   ELSE
      REPLACE PLACPOR WITH 0
      IF KALG.PPDV<>' '
         REPLACE PLACPORU WITH ROUND((IZNOS-RABAT+CARDIN+ZAVISNIC+ZAVISC3+PORKOREKC)*PROCPOR/100,2)
         REPLACE PLACPOR WITH 0
      ENDIF
   ENDIF
   REPLACE PLACPORD WITH ROUND(TRDOB*PROCPORD/100,2)
   *------------obracun preporucene mp cene------------------
   IF tobjekat='V'
      IF KOL<>0 
         REPLACE MARZAMP WITH ROUND(MARPROCMP*VELCENA/100,2)
         IF MALCENAMP=0
            REPLACE MALCENAMP WITH ROUND((VELCENA+MARZAMP)*(100+PROCPOR)/100,2)
         ENDIF
      ENDIF   
   ENDIF
   *-----------KRAJ PLACENOG POREZA---------------------------
   IF TOBJEKAT='V'
      REPLACE MALVRED WITH VELVRED+POREZ+AKCVRED
      IF KOL<>0
         REPLACE MALCENA WITH ROUND(MALVRED/KOL,2)
      endif
   ELSE
      REPLACE MALVRED WITH ROUND(KOL*MALCENA,2)
 
      *-------------AKO JE POSEBAN POREZ--------------------------
      IF PROCPOS<>0
         REPLACE PORPOS WITH ROUND(PROCPOS*MALVRED/(100+PROCPOR+PROCPOS),2)
         MNABAVNA=(IZNOS-RABAT+ZAVISNI+ZAVISNIN+ZAVISNIC+ZAVISC2+zavisc3+CARDIN+TRDOB+TRDOBN+ZAOKRUZ+PORPOS)
         REPLACE NABVRED WITH MNABAVNA
         IF NABVRED<>0.AND.KOL<>0
            REPLACE NABCENA WITH ROUND(NABVRED/KOL,3)
         ELSE
            REPLACE NABCENA WITH 0
         ENDIF
         IF NABVRED<>0.AND.VELVRED<>0
            REPLACE MARZA WITH MALVRED-POREZ-NABVRED-akcvred
            REPLACE MARPROC WITH ROUND(MARZA*100/NABVRED,5)
         ELSE
            REPLACE MARZA WITH 0
            REPLACE MARPROC WITH 0
         ENDIF
         IF KALG.OPDV<>' '
            REPLACE POREZ WITH ROUND((MALVRED-PORPOS)*PROCPOR/(100+PROCPOR),2)
         ELSE
            REPLACE POREZ WITH 0
         ENDIF
         REPLACE VELVRED WITH MALVRED-POREZ-PORPOS
         IF KOL<>0
            REPLACE VELCENA WITH ROUND(VELVRED/KOL,2)
         ENDIF   
      ELSE
         REPLACE PORPOS WITH 0
      ENDIF
      *---------KRAJ POSEBNOG POREZA------------------------
      REPLACE MARZA WITH MALVRED-POREZ-IZNOS+RABAT-ZAVISNI-ZAVISNIC-zavisc2-ZAVISC3-TRDOB-trdobn-zavisnin-akcvred-PORPOS-CARDIN
      REPLACE VELVRED WITH MALVRED-POREZ-akcvred
   ENDIF   
ENDIF   
POP KEY
