PUSH KEY CLEAR
KAL.CMDKALROBA.SETFOCUS
PUBLIC MREDREC,MREDZAD
SELECT KAL
MREDREC=RECNO()
MREDZAD=RECCOUNT()
MBRKAL=BRKAL
TGLAVNISR=0
DO FORM ROBA
SELECT KAL
SET ORDER TO 1
LOCATE FOR BRKAL=MBRKAL
SET ORDER TO 
GOTO MREDREC
KAL.GRD0.COLUMN4.SETFOCUS
POP KEY

*KAL.GRD0.REFRESH