PUSH KEY CLEAR
GO TOP

DO WHILE.NOT.EOF()
   KALSERV.LABEL3.CAPTION=BRKAL+' '+TRAN(RECCOUNT()-RECNO(),'99999999999')
*   THISFORM.REFRESH
   DO KALRAC
   SKIP
ENDDO   
   
MBRKAL=BRKAL
KALSERV.RELEASE
POP KEY