PUSH KEY CLEAR
SELECT KAL
MBRKAL=BRKAL
SET ORDER TO 1
LOCATE FOR BRKAL=MBRKAL
*REPORT FORM KALSVE1 PREVIEW FOR BRKAL=MBRKAL
      mfile='KALSVE1'
      uslov="BRKAL=MBRKAL"
      DO printer_bullzip WITH mdata02,mfile,uslov

SELECT KAL
SET ORDER TO 1
LOCATE FOR BRKAL=MBRKAL

SET ORDER TO 
POP KEY