PUSH KEY CLEAR
SELECT KAL
IF KALG.ARHIVA=' '
MBRKAL=BRKAL
SELECT KAL
SET ORDER TO 1
LOCATE FOR BRKAL=MBRKAL

IF FOUND()
   DO WHILE.NOT.EOF()
      IF BRKAL<>MBRKAL
         EXIT
      ENDIF
      IF TOBJEKAT='V'
         REPLACE CENA WITH ROB.PROSCENV   
      ELSE
         REPLACE CENA WITH ROB.PROSCENM
      ENDIF
      DO KALRAC
      SKIP
   ENDDO   
ENDIF   
LOCATE FOR BRKAL=MBRKAL

SET ORDER TO
ENDIF
POP KEY