PARAMETERS mdat0,mdat1,mfvrsta,mvrsta

DO IDEL WITH (KKOCKAX2)
DO IDEL WITH (KKOCKAX3)
DO IDEL WITH (KKOCKAX4)
SELECT KAL
SET ORDER TO 1
COPY TO &KKOCKA2 FOR DATDOK>=MDAT0.AND.DATDOK<=MDAT1.AND.(kalg.FVRSTA=MFVRSTA.OR.MFVRSTA=SPACE(3))
SET RELATION to
USE &kkocka2 IN 0 EXCLUSIVE ALIAS KOCKA2
SELECT kocka2
INDEX on brkal TAG brkal
TOTAL ON brkal TO &kkocka4
ZAP
APPEND FROM &kkocka4
SET RELATION TO BRKAL INTO KALG ADDITIVE
*---------------------virmani------------
USE VIRM IN 0 
SELECT VIRM
GO TOP
DO WHILE.NOT.EOF()
   REPLACE STAMPA WITH ' '
   REPLACE VRSTA WITH ' '
   SKIP
ENDDO
SELECT FIRMA
MNAZRACZ=ALLTRIM(FIME)+' '+ALLTRIM(FMES)
MFZIRO=FZIRO
SELECT KOCKA2
GO TOP
DO WHILE.NOT.EOF()
   MSIFRA=SIFRA
   MNAZIV=an0.NAZIV
   Mjmbg=ALLTRIM(an0.jmbg)+ALLTRIM(AN0.pib)
   POSTA=an0.POSTA
   MMESTO=an0.MESTO
   MZIRORAC=an0.ZIRORAC
   DO case
   case mvrsta='poljo'
      MDUG=POLJDIN
      MSVRHA='ISPLATA PDV ZA POLJOPRIVREDU'      
   CASE mvrsta='fakt'
      mdug=nabvred+poljdin+placpor
      MSVRHA='ISPLATA RACUNA'            
	  Mjmbg=ALLTRIM(KALG.BRRAC)      
   OTHERWISE
      mdug=nabvred
      MSVRHA='ISPLATA OTKUPA POLJOPRIVREDNIH PROIZVODA'            
   endcase
   SELECT VIRM
   IF MDUG<>0
      SELECT VIRM
      APPEND BLANK
      REPLACE STAMPA WITH '*'
      REPLACE ZIRORAC WITH MZIRORAC
      REPLACE NAZRAC WITH MNAZIV
      REPLACE NAZRACZ WITH MNAZRACZ
      REPLACE MESTO WITH MMESTO
      REPLACE SVRHA WITH MSVRHA
      replace pozivo WITH mjmbg
      REPLACE DUG WITH MDUG
      REPLACE VRSTA WITH '99'
      REPLACE BANKA WITH '1'
      REPLACE ZIRORACZ WITH MFZIRO
      REPLACE MODELO WITH '99'
      REPLACE SIF1 WITH '221'
      replace valuta WITH 'RSD'
   ENDIF
   SELECT KOCKA2
   SKIP
ENDDO   
SELECT VIRM
USE
*-------------kraj virmANA***************
SELECT kocka2
USE
SELECT KAL
SET ORDER TO 
select kal
set relation to brkal into kalg  additive
set relation to rsif into rob additive
