PUSH KEY CLEAR
SELECT KALZAV
MSIFRA=STR(VAL(ALLTRIM(SIFRA)),5,0)
SET RELATION TO
SELECT AN0
SEEK MSIFRA
SET ORDER TO 2
DO FORM FAN0
SELECT AN0
MSIFRA=SIFRA
MNAZIV=NAZIV
SET ORDER TO 1
SELECT KALZAV
IF SIFRA=SPACE(5)
   REPLACE SIFRA WITH MSIFRA
ENDIF
SET RELATION TO SIFRA INTO AN0 ADDITIVE
SET RELATION TO BRKAL INTO KALG ADDITIVE

KALZAVRAC.GRD0.SetFocus
POP KEY
KALZAVRAC.REFRESH

