PUSH KEY CLEAR
SELECT KAL
SET ORDER TO 1
KAL.CMDKALZBIR.SETFOCUS
*KAL.GRD0.COLUMN5.SETFOCUS
MBRKAL=BRKAL
*REPORT FORM KALZBIR0 PREVIEW FOR BRKAL=MBRKAL
      mfile='KALZBIR0'
      uslov="BRKAL=MBRKAL"
      DO printer_bullzip WITH mdata02,mfile,uslov

SELECT KAL
SET ORDER TO 1
LOCATE FOR BRKAL=MBRKAL

SET ORDER TO 
KAL.GRD0.SETFOCUS
POP KEY
