PUSH KEY CLEAR
MBRKAL=BRKAL

USE &KKAZB IN 0 ALIAS KALZBIR EXCLUSIVE
SELECT KALZBIR
DELETE ALL
PACK


SELECT KAL
SET ORDER TO 1
LOCATE FOR BRKAL=MBRKAL

IF FOUND()
   MIZNOS=0
   MRABAT=0
   MMARZA=0
   MVELVRED18=0
   MVELVRED8=0
   MZAVISNI=0
   MZAVISNIN=0
   MZAVISNIC=0
   MZAVISC2=0
   MZAVISC3=0
   MPORKOREKC=0
   MTRDOB=0
   MTRDOBN=0
   MZAOKRUZ=0
   MNABVRED=0
   MPOREZ18=0
   MPOREZ8=0
   MMALVRED18=0
   MMALVRED8=0
   MPOLJDIN=0
   MCARDIN=0
   MAKCVRED=0
   MPLACPOR18=0
   MPLACPOR8=0
   MPLACPORC18=0
   MPLACPORC8=0
   MPLACPORZ18=0
   MPLACPORZ8=0
   MPLACPORU18=0
   MPLACPORU8=0
   MPLACPORD18=0
   MPLACPORD8=0
   MFVRSTA=KALG.FVRSTA
   MSIFRA=KALG.SIFRA
   MBRRAC=KALG.BRRAC
   MDATDOK=KALG.DATDOK
   MVALUTA=KALG.VALUTA
   MDOKUM=KALG.DOKUM
   MPV1=KALG.PV1
   MPRDIN1=KALG.PRDIN1
   MPV2=KALG.PV2
   MPRDIN2=KALG.PRDIN2
   MPV3=KALG.PV3
   MPRDIN3=KALG.PRDIN3
   MPV4=KALG.PV4
   MPRDIN4=KALG.PRDIN4
   MPV5=KALG.PV5
   MPRDIN5=KALG.PRDIN5
   MPV6=KALG.PV6
   MPRDIN6=KALG.PRDIN6
   MPV7=KALG.PV7
   MPRDIN7=KALG.PRDIN7
   MPV8=KALG.PV8
   MPRDIN8=KALG.PRDIN8
   MPV9=KALG.PV9
   MPRDIN9=KALG.PRDIN9
   MPV10=KALG.PV10
   MPRDIN10=KALG.PRDIN10
   MPV11=KALG.PV11
   MPRDIN11=KALG.PRDIN11
   MPV12=KALG.PV12
   MPRDIN12=KALG.PRDIN12
   MRNAL=KALG.RNAL
   MPBRKAL=KALG.PBRKAL
   MPDOK=KALG.PDOK
   MNOBRKAL=KALG.NOBRKAL
   MINTERNA=KALG.INTERNA
   MPRENOS=KALG.PRENOS
   MVPDV=KALG.VPDV
   MDEV=KALG.DEV
   MDEVKURS=KALG.DEVKURS
   MDEVIZNA=KALG.DEVIZNA
   MNAZIV=AN0.NAZIV
   mfnaz=kalprn.fnaz
   DO WHILE.NOT.EOF()
      IF BRKAL<>MBRKAL
         EXIT
      ENDIF
      IF PROCPOR=VAL(TOSTOPA)
         MVELVRED18=MVELVRED18+VELVRED
         MMALVRED18=MMALVRED18+MALVRED
         MPLACPOR18=MPLACPOR18+PLACPOR
         MPLACPORC18=MPLACPORC18+PLACPORC
         MPLACPORZ18=MPLACPORZ18+PLACPORZ
         MPLACPORU18=MPLACPORU18+PLACPORU
         MPOREZ18=MPOREZ18+POREZ
      ENDIF
      IF PROCPOR=VAL(TNSTOPA)
         MVELVRED8=MVELVRED8+VELVRED
         MMALVRED8=MMALVRED8+MALVRED
         MPLACPOR8=MPLACPOR8+PLACPOR
         MPLACPORC8=MPLACPORC8+PLACPORC
         MPLACPORZ8=MPLACPORZ8+PLACPORZ
         MPLACPORU8=MPLACPORU8+PLACPORU
         MPOREZ8=MPOREZ8+POREZ
      ENDIF
      IF PROCPORd=VAL(TOSTOPA)
         MPLACPORD18=MPLACPORD18+PLACPORD
      ENDIF
      IF PROCPORd=VAL(TNSTOPA)
         MPLACPORD8=MPLACPORD8+PLACPORD
      ENDIF
      MIZNOS=MIZNOS+IZNOS
      MRABAT=MRABAT+RABAT
      MMARZA=MMARZA+MARZA
      MZAVISNI=MZAVISNI+ZAVISNI
      MZAVISNIN=MZAVISNIN+ZAVISNIN
      MZAVISNIC=MZAVISNIC+ZAVISNIC
      MZAVISC2=MZAVISC2+ZAVISC2
      MZAVISC3=MZAVISC3+ZAVISC3
      MPORKOREKC=MPORKOREKC+PORKOREKC
      MTRDOB=MTRDOB+TRDOB
      MTRDOBN=MTRDOBN+TRDOBN
      MZAOKRUZ=MZAOKRUZ+ZAOKRUZ
      MNABVRED=MNABVRED+NABVRED
      MPOLJDIN=MPOLJDIN+POLJDIN
      MCARDIN=MCARDIN+CARDIN
      MAKCVRED=MAKCVRED+AKCVRED
      SKIP
   ENDDO   
ENDIF
SELECT kal
LOCATE FOR BRKAL=MBRKAL

SELECT KALZBIR
APPEND BLANK
REPLACE BRKAL WITH MBRKAL
REPLACE IZNOS WITH MIZNOS
REPLACE RABAT WITH MRABAT
REPLACE MARZA WITH MMARZA
REPLACE VELVRED18 WITH MVELVRED18
REPLACE VELVRED8 WITH MVELVRED8
REPLACE VELVRED WITH MVELVRED18+MVELVRED8
REPLACE ZAVISNI WITH  MZAVISNI
REPLACE ZAVISNIN WITH MZAVISNIN
REPLACE ZAVISNIC WITH MZAVISNIC
REPLACE ZAVISC2 WITH MZAVISC2
REPLACE ZAVISC3 WITH MZAVISC3
REPLACE PORKOREKC WITH MPORKOREKC
REPLACE TRDOB WITH MTRDOB
REPLACE TRDOBN WITH MTRDOBN
REPLACE ZAOKRUZ WITH MZAOKRUZ
REPLACE NABVRED WITH MNABVRED
REPLACE POREZ18 WITH MPOREZ18
REPLACE POREZ8 WITH MPOREZ8
REPLACE POREZ WITH MPOREZ18+MPOREZ8
REPLACE MALVRED18 WITH MMALVRED18
REPLACE MALVRED8 WITH MMALVRED8
REPLACE MALVRED WITH MMALVRED18+MMALVRED8
REPLACE POLJDIN WITH MPOLJDIN
REPLACE CARDIN WITH MCARDIN
REPLACE AKCVRED WITH MAKCVRED
REPLACE PLACPOR18 WITH MPLACPOR18
REPLACE PLACPOR8 WITH MPLACPOR8
REPLACE PLACPOR WITH MPLACPOR18+MPLACPOR8
REPLACE PLACPORC18 WITH MPLACPORC18
REPLACE PLACPORC8 WITH MPLACPORC8
REPLACE PLACPORC WITH MPLACPORC18+MPLACPORC8
REPLACE PLACPORZ18 WITH MPLACPORZ18
REPLACE PLACPORZ8 WITH MPLACPORZ8
REPLACE PLACPORZ WITH MPLACPORZ18+MPLACPORZ8
REPLACE PLACPORU18 WITH MPLACPORU18
REPLACE PLACPORU8 WITH MPLACPORU8
REPLACE PLACPORU WITH MPLACPORU18+MPLACPORU8
REPLACE PLACPORD18 WITH MPLACPORD18
REPLACE PLACPORD8 WITH MPLACPORD8
REPLACE PLACPORD WITH MPLACPORD18+MPLACPORD8
REPLACE FVRSTA WITH MFVRSTA
REPLACE SIFRA WITH MSIFRA
REPLACE BRRAC WITH MBRRAC
REPLACE DATDOK WITH MDATDOK
REPLACE VALUTA WITH MVALUTA
REPLACE DOKUM WITH MDOKUM
REPLACE PV1 WITH MPV1
REPLACE PRDIN1 WITH MPRDIN1
REPLACE PV2 WITH MPV2
REPLACE PRDIN2 WITH MPRDIN2
REPLACE PV3 WITH MPV3
REPLACE PRDIN3 WITH MPRDIN3
REPLACE PV4 WITH MPV4
REPLACE PRDIN4 WITH MPRDIN4
REPLACE PV5 WITH MPV5
REPLACE PRDIN5 WITH MPRDIN5
REPLACE PV6 WITH MPV6
REPLACE PRDIN6 WITH MPRDIN6
REPLACE PV7 WITH MPV7
REPLACE PRDIN7 WITH MPRDIN7
REPLACE PV8 WITH MPV8
REPLACE PRDIN8 WITH MPRDIN8
REPLACE PV9 WITH MPV9
REPLACE PRDIN9 WITH MPRDIN9
REPLACE PV10 WITH MPV10
REPLACE PRDIN10 WITH MPRDIN10
REPLACE PV11 WITH MPV11
REPLACE PRDIN11 WITH MPRDIN11
REPLACE PV12 WITH MPV12
REPLACE PRDIN12 WITH MPRDIN12
REPLACE NAZIV WITH MNAZIV
replace fnaz WITH mfnaz
IF TOBJEKAT='V'
   KKALZAV='KALZAV'+TTVREDNI+'.DBF'
ELSE
   KKALZAV='KALZAM'+TTVREDNI+'.DBF'
ENDIF   

USE &KKALZAV IN 0 ALIAS KALZAV ORDER 1
SELECT kalg
SET RELATION to
SELECT KALZAV
SET RELATION TO SIFRA INTO AN0
LOCATE FOR BRKAL=MBRKAL

IF FOUND()
   DO WHILE.NOT.EOF()
      IF BRKAL<>MBRKAL
         EXIT
      ENDIF   
      MDATDOK=DATDOK
      MVALUTA=VALUTA
      MSIFRA=SIFRA
      MNAZIV=AN0.NAZIV
      MDUG=DUG
      MOCARINA=OCARINA
      MOPOREZ=OPOREZ
      MPOR18=POR18
      MPOR8=POR8
      MNEPOREZ=NEPOREZ
      MVRSTA=VRSTA
      MSEMA=SEMA
      SELECT KALZBIR
      APPEND BLANK
      REPLACE BRKAL WITH MBRKAL
      REPLACE DATDOK WITH MDATDOK
      REPLACE VALUTA WITH MVALUTA
      REPLACE SIFRA WITH MSIFRA
      REPLACE NAZIV WITH MNAZIV
      REPLACE DUG WITH MDUG
      REPLACE OCARINA WITH MOCARINA
      REPLACE OPOREZ WITH MOPOREZ
      REPLACE POR18 WITH MPOR18
      REPLACE POR8 WITH MPOR8
      REPLACE NEPOREZ WITH MNEPOREZ
      REPLACE VRSTA WITH MVRSTA
      REPLACE SEMA WITH MSEMA
      SELECT KALZAV
      SKIP
   ENDDO
ENDIF
SELECT kal
SET RELATION to
USE
SELECT KALZAV
SET RELATION TO
USE
SELECT KALZBIR
GO top
PUSH KEY CLEAR
*REPORT FORM KALZBIR01 PREVIEW FOR BRKAL=MBRKAL 
      mfile='KALZBIR01'
      uslov="BRKAL=MBRKAL"
      DO printer_bullzip WITH mdata02,mfile,uslov

POP KEY
SELECT KALZBIR
USE
CLOSE ALL 
POP KEY