PUSH KEY CLEAR
PDAT0=DAT0
PDAT1=DAT1
PREDNAL=ALLTRIM(REDNAL)
PSIFRA=STR(VAL(ALLTRIM(SIFRA)),5,0)
IF PSIFRA='    0'
   PSIFRA='     '
ENDIF
PKONTO=ALLTRIM(KONTO)
IF PSIFRA=SPACE(5)
   SELECT KAMATE
   SET RELATION TO
   SELECT AN0
   GO TOP
   DO WHILE.NOT.EOF()
      PSIFRA=SIFRA
      IF grupa1=kamgrupa.or.kamgrupa=SPACE(3)
         SET PROCEDURE TO KAMATE
            DO KAMOBRAC WITH PDAT0,PDAT1,PSIFRA,PKONTO,PREDNAL
         SET PROCEDURE TO
      endif
      SELECT AN0
      KAMOBRAC.LABELR.CAPTION=SIFRA+' '+NAZIV
      SKIP
   ENDDO
   SELECT KAMATE
   SET RELATION TO SIFRA INTO AN0
ELSE
   SET PROCEDURE TO KAMATE
      DO KAMOBRAC WITH PDAT0,PDAT1,PSIFRA,PKONTO,PREDNAL
   SET PROCEDURE TO
ENDIF   
POP KEY
KAMOBRAC.RELEASE