   IF MKAMARKA=1.OR.MKAMARKA=5
   SELECT KASA
   SET ORDER TO
   GO TOP
   IF MRADTREB=1
      DO RADTREB
   ENDIF
   SELECT KASA
   GO TOP
   IF RECCOUNT()>0
      MMALVRED=0
      DO WHILE.NOT.EOF()
         MMALVRED=MMALVRED+MALVRED
         SKIP
      ENDDO 
      IZNOSRAC=MMALVRED  
      GO TOP
      REPLACE GOTOVINA WITH IZNOSRAC
      DO KASAGALEBKNJ WITH IZNOSRAC,1
      CLOSE ALL TABLES
      TKOJI='H'
      IF mpozivloz=0
         KASA.Release
         KEYBOARD '{ENTER}' 
      ELSE
         KASA.RELEASE
         KASA0.Release
         KEYBOARD '{ENTER}' 
      endif
   ENDIF
   ELSE
      KASA.RELEASE
   ENDIF         
   
 