SELECT KASAKR
*MFLSIFRA=FLSIFRA
USE &KKASA IN 0 ALIAS KASA EXCLU 
SELECT kasa
SET ORDER TO
GO TOP
*REPLACE FLSIFRA WITH MFLSIFRA
MMALVRED=0
DO WHILE.NOT.EOF()
   IF NMALVRED=0
      MMALVRED=MMALVRED+MALVRED
      ELSE
      MMALVRED=MMALVRED+NMALVRED
   endif      
   SKIP
ENDDO 
IZNOSRAC=MMALVRED  
AMADATO=IZNOSRAC
USE
SELECT KASAKR
IF MMALVRED<>0
   DO FORM KASAKRKART
else 
   DO PORUKAU WITH ' NEMA STAVKI U KASI '
ENDIF