PARAMETERS AMDATO
SELECT KASA
ASACEKAJ=1
IF RECCOUNT()>0
   SELECT KASA
   GO TOP
   *----------PROMENA 24.10.2006.GODINE----------
   MMAL0=0
   MSIFRA=SIFRA
   DO WHILE.NOT.EOF()
      MMAL0=MMAL0+MALVRED-RABAT
      REPLACE SIFRA WITH MSIFRA
      SKIP
   ENDDO   
   GO TOP
   MPARE=MMAL0-CEK-KARTICA
   REPLACE GOTOVINA WITH MPARE
   
   MDANAS=DTOS(DATE())

   SET PATH TO &MKASADATA
   SET DEFAULT TO &MKASADATA
   IF !DIRECTORY(MDANAS)
      MKDIR (MDANAS)
   ENDIF

   MKASADAT2=MKASADATA+'\'+MDANAS
   SET path TO &MKASADAT2
   SET DEFAULT TO &MKASADAT2
   MVREME=SUBSTR(TIME(),1,2)+SUBSTR(TIME(),4,2)+SUBSTR(TIME(),7,2)
   COPY TO &MVREME 
   SET path TO &MDATA02
   SET DEFAULT TO &MDATA02


   SELECT KASA
   GO TOP
   *-----------NIVELACIJE-----22.11.2006.---------------
   MRAB0=0
   DO WHILE.NOT.EOF()
      MRAB0=MRAB0+RABAT
      SKIP
   ENDDO   
   GO TOP
   IF MRAB0<>0
      KTVNIVX='TMNIV'+TTVREDNI+'.DBF'
      USE &KTVNIV IN 0 ALIAS NIV ORDER 1
      SELECT NIV
      IF RECCOUNT()>0
         GO BOTTOM
         MBRKAL=BRKAL
         MNLEN=LEN(ALLTRIM(STR(VAL(ALLTRIM(SUBSTR(MBRKAL,2,5)))+1,5,0)))
         MNBRKAL='N'+REPLI('0',5-MNLEN)+ALLTRIM(STR(VAL(ALLTRIM(SUBSTR(MBRKAL,2,5)))+1,5,0))
      ELSE
         MNBRKAL='N00001'
      ENDIF      
      GO BOTTOM
      SELECT KASA
      DO WHILE.NOT.EOF()
         IF STORNO=' '.AND.KOLI<>0
            IF RABAT<>0
               MSIZNOS=MALVRED
               MMALVRED=MALVRED-RABAT
               MKOLI=KOLI
               MTARIFA=TARIFA
               MPROCPOR=PROCPOR
               MRSIF=RSIF
               SELECT NIV
               APPEND BLANK
               REPLACE BRKAL WITH MNBRKAL
               REPLACE RSIF WITH MRSIF
               REPLACE KOL WITH MKOLI
               REPLACE SIZNOS WITH MSIZNOS
               REPLACE MALVRED WITH MMALVRED
               REPLACE STARIFA WITH MTARIFA
               REPLACE TARIFA WITH MTARIFA
               REPLACE PROCPOR WITH MPROCPOR
               REPLACE SPROCPOR WITH MPROCPOR
               REPLACE SCENA WITH ROUND(SIZNOS/KOL,2)
               REPLACE MALCENA WITH  ROUND(MALVRED/KOL,2)
               REPLACE SPOREZ WITH ROUND(SIZNOS*SPROCPOR/(100+SPROCPOR),2)
               REPLACE POREZ WITH ROUND(MALVRED*PROCPOR/(100+PROCPOR),2)
               REPLACE MARZA WITH MALVRED-SIZNOS-POREZ-SPOREZ
               REPLACE RAZLPOR WITH POREZ-SPOREZ
               REPLACE DATDOK WITH DATE()
               REPLACE DATUM WITH DATE()
               REPLACE VREME WITH TIME()
               REPLACE SEMA WITH '   2'
               REPLACE BRNAL WITH 'L'+REPLI('0',5-MNLEN)+ALLTRIM(STR(VAL(ALLTRIM(SUBSTR(MNBRKAL,2,5)))+1,5,0))
               REPLACE MARZA WITH MALVRED
               REPLACE ARHIVA WITH '*'
               SELECT KASA
            ENDIF
         ENDIF
         SKIP
      ENDDO   
      SELECT NIV
      USE
   ENDIF   
   *----------PRAVIMO RACUNE
   USE KASAPAR IN 0
   SELECT KASAPAR
   USE
   SELECT KASA
   GO TOP
   *--------AKO SE PRAVE RACUNI----------------
      DO KASAPUNIFAK WITH 0
   
   ***********************************************************************
   *--------KNJIZENJE U FINANSIJE-----------------------------------------
   ***********************************************************************
   
   SELECT KASA
   DELETE ALL
PACK

ENDIF
