   PARAMETERS MMBAR,MBAR

   KASA.GRD0.COLUMN2.BACKCOLOR=RGB(0,255,0)
   SET ORDER TO 2
   KASA.grd0.COLUMN2.TEXT1.SETFOCUS
   IF MMBAR=0.OR.MMBAR=1
      IF KASA.TXTKOL.VALUE=0
         IF TRANSPAK=0
            MKOL=1
         ELSE
            MKOL=TRANSPAK
         ENDIF
      ELSE
         MKOL=KASA.TXTKOL.VALUE
      ENDIF      
   ELSE
      MKOL=VAL(SUBSTR(MBAR,8,2)+'.'+SUBSTR(MBAR,10,3))
   ENDIF  
   IF MKOL<>0.AND.(KOL<>0.OR.VRSTA='M'.OR.VRSTA='S').AND.MALCENA<>0.AND.(KOL>=MKOL.OR.VRSTA='M'.OR.VRSTA='S').OR.ADOZMINUS=1
      MRSIF=RSIF
      MNAZ=NAZ
      MMALCENA=MALCENA
      MTARIFA=TARIFA
      MPROCPOR=PROCPOR
      MJED=SUBSTR(JED,1,3)
      SELECT KASA
      *----AKO JE PRVA STAVKA KASE---------
      IF RECCOUNT()<1
         DO WHILE .T.
         MN2BRKAL=OPER 
*            MHEIGHT=KASA.GRD1.HEIGHT+1.29
*            IF MHEIGHT>34.13
*               MHEIGHT=34.13
*            ENDIF
*            KASA.GRD1.HEIGHT=MHEIGHT
            
         KASA.LBLPRAZNO.VISIBLE=.F.
         APPEND BLANK
         KASA.LBLBRSTAVKI.Caption=STR(RECCOUNT(),3,0)   
         REPLACE BRKAL WITH MN2BRKAL
         REPLACE KOLi WITH MKOL
         REPLACE RSIF WITH MRSIF
         REPLACE NAZ WITH MNAZ
         REPLACE TARIFA WITH MTARIFA
         REPLACE PROCPOR WITH MPROCPOR
         REPLACE MALCENA WITH MMALCENA
         REPLACE MALVRED WITH KOLi*MALCENA
         REPLACE JED WITH MJED
         REPLACE OPER WITH PPAS
            DO KASAMETADISP WITH SUBSTR(MNAZ,1,20),TRANSFORM(MMALCENA,'999999.99')
            IF RECCOUNT()>0
               EXIT
            ELSE
               loop
            ENDIF   
         ENDDO   
         KASA.GRD1.REFRESH
         *------AKO NIJE PRVA STAVKA------------   
      ELSE
         IF RECCOUNT()<=254
            GO BOTTOM
            MN2BRKAL=BRKAL   
            MMREC1=RECCOUNT()
            DO WHILE .T.  
               IF RSIF<>MRSIF.or.storno='S'
*            MHEIGHT=KASA.GRD1.HEIGHT+1.29
*            IF MHEIGHT>34.13
*               MHEIGHT=34.13
*            ENDIF
*            KASA.GRD1.HEIGHT=MHEIGHT

                  APPEND BLANK
                  KASA.LBLBRSTAVKI.Caption=STR(RECCOUNT(),3,0)   
                  REPLACE KOLi WITH MKOL
                  MNASAOROB=0
                  KASA.GRD1.REFRESH
               ELSE
                  REPLACE KOLI WITH KOLI+MKOL
                  MNASAOROB=1
               ENDIF
               REPLACE BRKAL WITH MN2BRKAL
               REPLACE RSIF WITH MRSIF
               REPLACE NAZ WITH MNAZ
               REPLACE TARIFA WITH MTARIFA
               REPLACE PROCPOR WITH MPROCPOR
               REPLACE MALCENA WITH MMALCENA
               REPLACE MALVRED WITH KOLi*MALCENA
               REPLACE JED WITH MJED
               REPLACE OPER WITH PPAS
               DO KASAMETADISP WITH SUBSTR(MNAZ,1,20),TRANSFORM(MMALCENA,'999999.99')
               IF RECCOUNT()>MMREC1.AND.MNASAOROB=0
                  EXIT
               ELSE
                  IF MNASAOROB=1
                     EXIT
                  ELSE
                     LOOP
                  ENDIF
               ENDIF
            ENDDO            
         ELSE
            DO PORUKAU WITH ' DOSTIGNUT JE MAKSIMALAN BROJ STAVKI U RAÈUNU '
            mkol=0
         ENDIF      
         SET BELL TO
      ENDIF
      SELECT KASA
      SET ORDER TO
      GO TOP
      MMALVRED=0
      DO WHILE.NOT.EOF()
         MMALVRED=MMALVRED+MALVRED-RABAT
         SKIP
      ENDDO   
*      KASA.LBLIZNOS.CAPTION=TRAN(MMALVRED,'999 999 999.99')
      KASA.LBLIZNOSR.CAPTION=TRAN(MMALVRED,'9999 999.99')
      KASA.LBLIZNOSRDEV.CAPTION=TRAN(MMALVRED/AMKURS,'9999 999.99')      
      KASA.GRD0.REFRESH
      KASA.GRD1.REFRESH
      SELECT ROB
      REPLACE KOL WITH kol-MKOL
   ELSE
      IF MKOL=0
         MPORUKA=' UNETA KOLIÈINA=0 '
         DO   PORUKAU WITH MPORUKA
      ENDIF

      IF MALCENA=0
         MPORUKA=' CENA=0  '
         DO   PORUKAU WITH MPORUKA
      ENDIF
      IF adozminus=0
         IF KOL=0.AND.(VRSTA<>'S'.OR.VRSTA<>'M')
            MPORUKA=' KOLIÈINA U TABELI =0  '
            DO  PORUKAU WITH MPORUKA
         ENDIF      
         IF KOL>MKOL.AND.(VRSTA<>'S'.OR.VRSTA<>'M')
            MPORUKA=' PREKORAÈENA KOLICINA ZA PRODAJU '
            DO   PORUKAU WITH MPORUKA
         ENDIF
      endif
   ENDIF

   KASA.LABEL1.CAPTION=RSIF+' '+NAZ+' '+JED+' '+TRAN(KOL,'999 999.999')+' '+TRAN(MALCENA,'999 999 999.99')
   KASA.TXTKOL.VALUE=0
   KASA.TXTTRAZI.VALUE=''
*   KASA.TXTTRAZI.SETFOCUS 
   