ON KEY LABEL F10 ON KEY
SELECT KASA
IF MRADNJA=1

IF RECCOUNT()>0
   KASA.LABEL3.Visible=.T.
   KASA.TXTDATO.Visible=.T.
   KASA.LABEL2.Visible= .T.
   KASA.LBLIZNOS.Visible=.T.
   KASA.SHAPE2.VISIBLE=.T.
   KASA.TXTDATO.SETFOCUS
ELSE
   KASA.release

endif  

ELSE

IF RECCOUNT()>0
   KAFANA.LABEL3.Visible= .T.
   KAFANA.TXTDATO.Visible=.T.
   KAFANA.TXTDATO.SETFOCUS
ELSE
   KAFANA.release
 
   
endif  

ENDIF