   SELECT KASA
   GO TOP
   MSIFRA=SIFRA
   USE FIRMA IN 0 ALIAS FIRMA
   SELECT FIRMA
   MFIME=FIRMA.FIME
   USE
   USE AN0 IN 0 ORDER 1

   SELECT AN0
   SEEK MSIFRA
   IF FOUND()
      MNAZIV=NAZIV
      MMESTO=MESTO
      MULICA=ULICA
      MULBROJ=ULBROJ
      MPIB=PIB
   ELSE
      MNAZIV=''
      MMESTO=''
      MULICA=''
      MULBROJ=''
      MPIB=''
   ENDIF      
   SELECT AN0
   USE
   SELECT KASA
   MMIME='TXT_0001.TXT'
   MMIME0='TXT_'+'0001'
   FIDAT=FCREATE(MMIME)
   MM='XXXX ZA STRANKU XXXXXXXXXXXXXXXX'
   FPUTS(fidat,MM)
   MM=ALLTRIM(MFIME)
   FPUTS(fidat,MM)
   SET CENTURY ON
   MDAY=ALLTRIM(TRANSFORM(DAY(DATE()),'99'))
   MMONTH=ALLTRIM(TRANSFORM(MONTH(DATE()),'99'))
   MYEAR=ALLTRIM(TRANSFORM(YEAR(DATE()),'9999'))
   MTIME=TIME()
   MM='PRIZNANICA-'+'/'+MTIME+'-'+MDAY+'-'+MMONTH+'-'+MYEAR
   SET CENTURY OFF
   FPUTS(fidat,MM)
   MM=MSIFRA+' '+ALLTRIM(MNAZIV)
   FPUTS(fidat,MM)
   MM=ALLTRIM(MMESTO)
   FPUTS(fidat,MM)
   MM=ALLTRIM(MULICA)+' '+ALLTRIM(MULBROJ)
   FPUTS(fidat,MM)
   MM='PIB'+MPIB
   FPUTS(fidat,MM)
   MM=''
   FPUTS(fidat,MM)
   MM=' ZA KUPCA - PREUZETA ROBA '
   FPUTS(fidat,MM)
   mm='XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
   FPUTS(fidat,MM)
   DDUG=0
   DO WHILE.NOT.EOF()
      MM=RSIF+' '+SUBSTR(NAZ,1,20)+'T-'+SUBSTR(TARIFA,1,2)
      FPUTS(fidat,MM)
      MM=TRANSFORM(KOLI,'999.999')+'x'+TRANSFORM(MALCENA,'99999.99')+'='+TRANSFORM(MALVRED,'999999.99')
      FPUTS(fidat,MM)
      DDUG=DDUG+MALVRED
      SKIP
   ENDDO   
   MM='------------------------------'
   FPUTS(fidat,MM)
   MM='    IZNOS RACUNA='+TRANSFORM(DDUG,'999999.99')
   FPUTS(fidat,MM)
   MM='XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
   FPUTS(fidat,MM)

   GO TOP
   MM='ZA KASIRA-'+MTIME+'-'+MDAY+'-'+MMONTH+'-'+MYEAR
   SET CENTURY OFF
   FPUTS(fidat,MM)
   MM=MSIFRA+' '+ALLTRIM(MNAZIV)
   FPUTS(fidat,MM)
   MM=ALLTRIM(MMESTO)
   FPUTS(fidat,MM)
   MM=ALLTRIM(MULICA)+' '+ALLTRIM(MULBROJ)
   FPUTS(fidat,MM)
   MM='PIB'+MPIB
   FPUTS(fidat,MM)
   MM=''
   FPUTS(fidat,MM)
   MM=' PREUZETA ROBA '
   FPUTS(fidat,MM)
   mm='******************************'
   FPUTS(fidat,MM)
   DDUG=0
   DO WHILE.NOT.EOF()
      MM=RSIF+' '+SUBSTR(NAZ,1,20)+'T-'+SUBSTR(TARIFA,1,2)
      FPUTS(fidat,MM)
      MM=TRANSFORM(KOLI,'999.999')+'x'+TRANSFORM(MALCENA,'99999.99')+'='+TRANSFORM(MALVRED,'999999.99')
      FPUTS(fidat,MM)
      DDUG=DDUG+MALVRED
      SKIP
   ENDDO   
   MM='------------------------------'
   FPUTS(fidat,MM)
   MM='    IZNOS RACUNA='+TRANSFORM(DDUG,'999999.99')
   FPUTS(fidat,MM)
   MM='*******************************'
   FPUTS(fidat,MM)
   FCLOSE(fidat)
   DO MFSALJI WITH MMIME,MMIME0,0
   SET CENTURY OFF
   SELECT KASA
   GO TOP
   
