PARAMETERS MADATO,MASACEKAJ
PUSH KEY CLEAR
   *-----------PUNJENJE ARTIKALA----------------------------------
   DO KASASTAMP WITH MADATO,MASACEKAJ
   DO KASASNIMAJ 
   SELECT KASA
   DELETE ALL
PACK

   SELECT ROB
POP KEY
