PARAMETERS MADATO,MASACEKAJ
PUSH KEY CLEAR
MPROVERAF=PROVERAF()
IF MPROVERAF=1
   *-----------PUNJENJE ARTIKALA----------------------------------
  IF AKONTRAKA=1 
     DO KASASTAMP WITH MADATO,MASACEKAJ
  ENDIF
   SELECT KASA
   GO TOP
   MGOTOVINA=GOTOVINA
   MCEK=CEK
   MKARTICA=KARTICA

   MMCEK=TRANSFORM(MCEK,'999999.99')
   MMKARTICA=TRANSFORM(MKARTICA,'999999.99')
   MMGOTOVINA=TRANSFORM(MGOTOVINA,'999999.99')

   MMIME='prod'+'00'+PPAS+'.ime'
   MMIME0='prod'+'00'+PPAS

  
   IF FILE(KKOCKAX)
      DELETE FILE &KKOCKAX
   ENDIF
   IF FILE(KKOCKAX2)
      DELETE FILE &KKOCKAX2
   ENDIF
   SELECT KASA
   GO TOP
   FIDAT=FCREATE(MMIME)
   MTARIFA='1'
   M2MALVRED=0
   DO WHILE.NOT.EOF()
         IF AOBVEZNIK=1
            DO CASE TARIFA
            CASE ALLTRIM(TARIFA)=TOSTOPA
               MTARIFA='3'
            CASE ALLTRIM(TARIFA)=TNSTOPA
               MTARIFA='4'
            OTHERWISE
               MTARIFA='1'
            ENDCASE
         ELSE
            MTARIFA='0'
         ENDIF
         mSIFRA=ALLTRIM(rsif)+REPLICATE(' ',16-LEN(ALLTRIM(rsif)))
         IF NMALCENA=0
            mmalcena=TRANSFORM(malcena,'999999.99')
            mcena   =TRANSFORM(malcena,'999999.99')
         ELSE
            mmalcena=TRANSFORM(Nmalcena,'999999.99')
            mcena   =TRANSFORM(Nmalcena,'999999.99')
         ENDIF
         MKOLLEN=LEN(ALLTRIM(STR(KOLI,10,3)))
         MKOLI=KOLI
         MKOLIC=''
         IF MKOLI>0
            MKOLIC=STR(MKOLI,10,3)
         ELSE    
            mmkollen=LEN(ALLTRIM(STR(ABS(MKOLI),9,3)))
            MKOLIC=REPLICATE(' ',9-mmkollen)+'-'+ALLTRIM(STR(ABS(MKOLI),9,3))
         ENDIF
         MNAZIV=naz+SPACE(2)
         MCMD='0'
         MM=MSIFRA+' '+MTARIFA+' '+MNAZIV+' '+MCENA+' '+mkolic
         FPUTS(fidat,MM)
         M2MALVRED=M2MALVRED+MALVRED-RABAT
      SKIP
   ENDDO
   SELECT kasa
   GO top
   IF MCEK<>0   
      mM='CHEK       '+mmcek
      FPUTS(fidat,MM)
   ENDIF   
   IF MGOTOVINA<>0   
      mM='CASH       '+mmgotovina
      FPUTS(fidat,MM)
   ENDIF   
   IF MKARTICA<>0   
      mM='CARD       '+mmkartica
      FPUTS(fidat,MM)
   ENDIF   
   FCLOSE(fidat)
   DO GP550SALJI WITH MMIME,MMIME0,1
   SELECT KASA
   GO top
   M3MALVRED=TRANSFORM(M2MALVRED,'999 999.99')
   MM2MALVRED=M2MALVRED
   MMADATO=MADATO
   iF MaDATO>M2MALVRED
      MKUSUR=MaDATO-M2MALVRED
   ELSE
      MKUSUR=0
   ENDIF
*   dO METADISP WITH 'IZNOS ' +M3MALVRED,'KUSUR '+TRANSFORM(MKUSUR,'999 999.99')
   DO KASASNIMAJ 
   SELECT KASA
   ZAP
   SELECT ROB
   POP KEY
ELSE
   POP key
   DO PORUKAU WITH 'ŠTAMPAC NIJE FISKALIZOVAN '
ENDIF
