PUSH KEY CLEAR
IF FAKG.KASA=' '
   *---KREIRAMO TABELE-----------
IF ! FILE('ART0.DBF')
   CREATE TABLE ART0(;
    SIFRA      C(05),;
    OZNAKA     C(13),;
    NAZIV      C(20),;
    JM         C(2),;
    CENA       N(10,2),;
    TARIFA     C(1);
    )
    USE
ENDIF    

IF ! FILE('RACUN0.DBF')
   CREATE TABLE RACUN0(;
    SIFRA      C(05),;
    OZNAKA     C(13),;
    KOLICINA   N(09,3),;
    STORNO     L(1);
    )
    USE
ENDIF    

IF ! FILE('NOVAC0.DBF')
   CREATE TABLE NOVAC0(;
    NACIN      C(1),;
    IZNOS      N(10,2);
    )
    USE
ENDIF    


   SELECT FAK
   MBRKAL=BRKAL
   SET ORDER TO 1
   
   DO IDEL WITH (KKOCKAX)
   DO IDEL WITH (KKOCKAX2)
   USE ART0 IN 0 EXCLUSIVE
   SELECT ART0
   ZAP
   USE RACUN0 IN 0 EXCLUSIVE
   SELECT RACUN0
   ZAP
  
   USE NOVAC0 IN 0 EXCLUSIVE
   SELECT NOVAC0
   ZAP
   SELECT FAK
   COPY STRUCTURE TO &KKOCKA
   USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
   SELECT KOCKA
   MMALVREDZ=0
   SELECT FAK
   LOCATE FOR BRKAL=MBRKAL

   IF FOUND()
      DO WHILE.NOT.EOF()
         IF BRKAL<>MBRKAL
            EXIT
         ENDIF
         MVELVRED=VELVRED-RABAT
         IF TOBJEKAT='V'
            MMALVRED=ROUND(MVELVRED*(100+PROCPOR)/100,2)
            MMALCENA=ROUND(MMALVRED/KOLI,2)
            MCENA=MVELVRED
         ELSE
            MMALVRED=MALVRED
            MMALCENA=MALCENA
            MCENA=VELCENA
         ENDIF
*         MSIFRA=RSIF
*         MOZNAKA=ROB.BARKOD
         MOZNAKA=REPLICATE('0',5-LEN(ALLTRIM(RSIF)))+ALLTRIM(RSIF)
         MNAZIV=ROB.NAZ
         MJM='K '
*         MCENA=MMALCENA
         DO CASE TARIFA
         CASE ALLTRIM(TARIFA)=TOSTOPA
            MTARIFA='3'
         CASE ALLTRIM(TARIFA)=TNSTOPA
            MTARIFA='4'
         OTHERWISE
            MTARIFA='1'
         ENDCASE
         MKOLICINA=KOLI         
         SELECT ART0         
         IF MKOLICINA<>0
            SELECT ART0
            APPEND BLANK
    *        REPLACE SIFRA WITH MSIFRA
            REPLACE OZNAKA WITH MOZNAKA
            REPLACE NAZIV WITH MNAZIV
            REPLACE JM WITH MJM
            REPLACE CENA WITH MCENA
            REPLACE TARIFA WITH MTARIFA
            SELECT RACUN0
            APPEND BLANK
    *        REPLACE SIFRA WITH MSIFRA
            REPLACE OZNAKA WITH MOZNAKA
            REPLACE KOLICINA WITH MKOLICINA
            MMALVREDZ=MMALVREDZ+MMALVRED
         ENDIF
         SELECT FAK
         SKIP
      ENDDO      
   ENDIF
   SELECT KASAPL
   MNAZIN=0
   MKES=KES
   MCEK=CEK
   MKARTICA=KARTICA
   IF MKES<>0
      MNACIN='0'
      SELECT NOVAC0
      APPEND BLANK
      REPLACE NACIN WITH MNACIN
      REPLACE IZNOS WITH MKES
   ENDIF
   IF MCEK<>0
      MNACIN='1'
      SELECT NOVAC0
      APPEND BLANK
      REPLACE NACIN WITH MNACIN
      REPLACE IZNOS WITH MCEK
   ENDIF

   IF MKARTICA<>0
      MNACIN='2'
      SELECT NOVAC0
      APPEND BLANK
      REPLACE NACIN WITH MNACIN
      REPLACE IZNOS WITH MKARTICA
   ENDIF
   SELECT NOVAC0
   USE
   SELECT ART0
   USE
   SELECT RACUN0 
   USE
  
   DO KASAEPSONSALJI 

   SELECT KOCKA
   USE
   SELECT FAK
   LOCATE FOR BRKAL=MBRKAL

   SET ORDER TO 
   REPLACE FAKG.KASA WITH '*'
ENDIF   
   POP KEY