PUSH KEY CLEAR
SELECT KASAPL
MGOTOVINA=KES
MCEK=CEK
MKARTICA=KARTICA
MDATO=DATO
IF mdato<mgotovina
   mdato=mgotovina
endif   

SELECT FAK
IF FAKG.KASA=' '
   SELECT FAK
   MBRKAL=BRKAL
   SET ORDER TO 1
   DO IDEL WITH (KKOCKAX)
   DO IDEL WITH (KKOCKAX2)
   SELECT FAK
   COPY STRUCTURE TO &KKOCKA
   USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
   SELECT KOCKA
   MMALVRED=0
   SELECT FAK
   LOCATE FOR BRKAL=MBRKAL
   IF FOUND()
      DO WHILE.NOT.EOF()
         IF BRKAL<>MBRKAL
            EXIT
         ENDIF
         SCATTER NAME POLJA
         MVELVRED=VELVRED
         IF KOLI>0
            SELECT KOCKA
            APPEND BLANK
            GATHER NAME POLJA
            IF TOBJEKAT='V'
               REPLACE MALVRED WITH ROUND(MVELVRED*(100+PROCPOR)/100,2)
               REPLACE MALCENA WITH ROUND(MALVRED/KOLI,2)
            ENDIF
            REPLACE NAZ WITH ROB.NAZ
            MMALVRED=MMALVRED+MALVRED
         ENDIF
         SELECT FAK
         SKIP
      ENDDO      
   ENDIF
   *MGOTOVINA=MMALVRED
   *MCEK=0
   *MKARTICA=0
   MMIME='dat'+'0000'+PPAS+'.txt'
   MMIME0='dat'+'0000'+PPAS
   SELECT KOCKA
   INDEX ON RSIF TAG RSIF
   SET ORDER TO 1
   TOTAL ON RSIF TO &KKOCKA2 FIELDS RSIF
   ZAP
   APPEND FROM &KKOCKA2
   GO TOP
   SELECT ROB
   SET ORDER TO 1
   SELECT KOCKA
   SET RELATION TO RSIF INTO ROB ADDITIVE 
   SET EXACT OFF 
   SET CENTURY ON
   FIDAT=FCREATE(MMIME)
   DO WHILE.NOT.EOF()
      IF KOLI>0
*         IF AOBVEZNIK=1
            DO CASE TARIFA
            CASE ALLTRIM(TARIFA)=TOSTOPA
               MTARIFA='03'
            CASE ALLTRIM(TARIFA)=TNSTOPA
               MTARIFA='04'
            OTHERWISE
               MTARIFA='01'
            ENDCASE
 *        ELSE
 *           MTARIFA='00'
 *        ENDIF
         MSIFRA=ALLTRIM(rsif)+REPLICATE(' ',20-LEN(ALLTRIM(RSIF)))
         MNAZIV=ROB.NAZ+SPACE(10)
         MCENA=STR(malcena,10,2)
         MCMD='0'
         MM=MSIFRA+MTARIFA+MCENA+MNAZIV+MCMD
         FPUTS(fidat,MM)
      ENDIF
      SKIP
   ENDDO
   GO top
   FCLOSE(fidat)
   SELECT KOCKA
   SET RELATION TO
   USE
   DO INTEGRASALJIkasa WITH MMIME,MMIME0,1
   SELECT FAK
   SEEK MBRKAL
*------------POSLALI SMO ARTIKLE U STAMPAC---------------
   MMRAC='rac'+'0000'+PPAS+'.txt'
   MMRAC0='rac'+'0000'+PPAS
   FIDAT=FCREATE(MMRAC)
   M2MALVRED=0
   DO WHILE.NOT.EOF()
      IF BRKAL<>MBRKAL
         EXIT
      ENDIF    
      MSIFRA=ALLTRIM(rsif)+REPLICATE(' ',20-LEN(ALLTRIM(RSIF)))
      MCENA=STR(malcena,10,2)
      MKOLIC=STR(KOLI,10,3)
      MSTAVKA='S'
      mM=MSIFRA+MKOLIC+Mcena+MSTAVKA
      FPUTS(fidat,MM)
      SELECT FAK
      M2MALVRED=M2MALVRED+MALVRED-RABAT
      SKIP
   ENDDO
   MAGOTOVINA=TRANSFORM(MGOTOVINA,'9999999.99')
   MACEK=TRANSFORM(MCEK,'9999999.99')
   MAKARTICA=TRANSFORM(MKARTICA,'9999999.99')
   IF MGOTOVINA<>0
      mM=SPACE(30)+mAgotovina+'G'
      FPUTS(fidat,MM)
   ENDIF
   IF MCEK<>0
      mM=SPACE(30)+MACEK+'C'
      FPUTS(fidat,MM)
   ENDIF
   IF MKARTICA<>0
      mM=SPACE(30)+MAKARTICA+'K'
      FPUTS(fidat,MM)
   ENDIF
   FCLOSE(fidat)
   DO INTEGRASALJIKASA WITH MMRAC,MMRAC0,1
   SELECT FAK
   SEEK MBRKAL
ENDIF
POP KEY