SELECT ROB
*IF KOL<=0
*   MPORUKAU=' KOLIÈINA NIJE POZITIVNA '
*   DO PORUKAU WITH MPORUKAU
*   KASA.GRD0.SETFOCUS
*ELSE
   DO FORM KASAPLUS
   IF AGLBARKOD=0
      KASA.GRD0.SETFOCUS
   ELSE
      KASA.TXTTRAZI.SETFOCUS
   ENDIF
 *ENDIF