PUSH KEY CLEAR
SELECT FAK
SET RELATION TO
DO IDEL WITH (KKOCKAX)
SET ORDER TO 1
TOTAL ON BRKAL TO &KKOCKA
USE &KKOCKA IN 0 ALIAS KOCKA EXCLUSIVE
SELECT KOCKA
SET RELATION TO BRKAL INTO FAKG  ADDITIVE
SET RELATION TO RSIF INTO ROB ADDITIVE
*REPORT FORM KASAREV03rabat PREVIEW 
   mfile='KASAREV03RABAT'
   uslov=""
   DO printer_bullzip WITH mdata02,mfile,uslov

SELECT KOCKA
USE
SELECT FAK
SET RELATION TO BRKAL INTO FAKG  ADDITIVE
SET RELATION TO RSIF INTO ROB ADDITIVE

POP KEY