PUSH KEY CLEAR
MSIFRA=FAKG.SIFRA
*REPORT FORM KASAREV02rabat PREVIEW FOR FAKG.SIFRA=MSIFRA
   mfile='KASAREV02RABAT'
   uslov="FAKG.SIFRA=MSIFRA"
   DO printer_bullzip WITH mdata02,mfile,uslov

POP KEY