IF mradnja=1
   SELECT KASA
   MREC=RECCOUNT()
   SELECT ROB
   IF MREC>0
      SELECT KASA
      KASA.CMDSTORNO.VISIBLE=.T.
      KASA.COMMAND25.VISIBLE=.T.
      KASA.GRD1.COLUMN2.SETFOCUS
   ENDIF   
ELSE
   IF GLAVNAS<>1
      SELECT KASA
      MREC=RECCOUNT()
      SELECT ROB
      IF MREC>0
         SELECT KASA
         KAfana.CMDSTORNO.VISIBLE=.T.
         KAfana.GRD1.COLUMN2.SETFOCUS
      ENDIF   
   endif
Endif
