IF mradnja=1
   SELECT KASA
   KASA.GRD1.BackColor=RGB(255,255,128)
   KASA.TXTRSIF.value=''
   KASA.TXTRSIF.SETFOCUS

ELSE
   SELECT KASA
   KAfana.GRD1.BackColor=RGB(255,255,128)
   KAfana.TXTRSIF.value=''
   KAfana.TXTRSIF.SETFOCUS
endif