DO FORM KASAAF5naz
MRABDEC=0
SELECT KASA
GO top
MMALVRED=0
DO WHILE.NOT.EOF()
   IF STORNO=' '
      IF KOLI<>0
         IF MALVRED<>0
            IF RABPROC<>0
               REPLACE RABAT WITH ROUND(MALVRED*RABPROC/100,2)
               REPLACE NMALVRED WITH MALVRED-RABAT
               REPLACE NMALCENA WITH ROUND(NMALVRED/KOLI,MRABDEC) 
               REPLACE NMALVRED WITH NMALCENA*KOLI
            ELSE
               REPLACE RABAT WITH 0
               REPLACE NMALCENA WITH 0
               REPLACE NMALVRED WITH 0
            ENDIF
         ENDIF
      ENDIF
   ENDIF
   MMALVRED=MMALVRED+MALVRED-RABAT
   SKIP
ENDDO   
GO TOP
KASA.LBLIZNOSR.CAPTION=TRAN(MMALVRED,'9999 999.99')
        KASA.LBLIZNOSRDEV.CAPTION=TRAN(MMALVRED/AMKURS,'9999 999.99')

SELECT rob
   
