PARAMETERS MADATO,MASACEKAJ
PUSH KEY CLEAR
*--------------FISKALNA KASA KOLIBRI
   SELECT KASA
   GO TOP
   MGOTOVINA=GOTOVINA
   MCEK=CEK
   MKARTICA=KARTICA
   SET EXACT OFF 
   SET CENTURY ON
   mrec=1000
   *-------odredjujemo broj-------------
   USE KASABROJ IN 0
    SELECT KASABROJ
    GO BOTTOM
    IF RECCOUNT()>0
       MZADNJIbr=VAL(BRKAl)
    ELSE
       mzadnjibr=0
    endif
    APPEND BLANK
    IF RECCOUNT()>1
       MNOVI=ALLTRIM(STR(mzadnjibr+1,6,0))
       MLEN=LEN(MNOVI)
       MN2=REPLICATE('0',6-MLEN)+MNOVI  
       MN2BRKAL=MN2
    ELSE
       MN2BRKAL='000001'
    ENDIF   
    REPLACE BRKAL WITH MN2BRKAL
    MREC=RECCOUNT()
    USE   
    MIME=REPLI('0',5-LEN(ALLTRIM(STR(MREC,5,0))))+ALLTRIM(STR(MREC,5,0))
    *-------formiran je naziv datoteke
    SELECT KASA
    GO TOP
    MAMAL=0
    MMIME=MIME+'.BON'
    *----------FORMIRAMO PRVI RED DATOTEKE
    MDANAS=SUBSTR(DTOC(DATE()),1,2)+SUBSTR(DTOC(DATE()),4,2)+SUBSTR(DTOC(DATE()),7,4)
    MVREME=SUBSTR(TIME(),1,2)+SUBSTR(TIME(),4,2)+SUBSTR(TIME(),7,2)
    MM='100'+MDANAS+MVREME+MIME+'01'
    *---KREIRAMO DATOTEKU------------
    bobi=FCREATE(MMIME)
    FPUTS(bobi,MM)
    DO WHILE.NOT.EOF()
      MRSIF=RSIF
      M2KOLI=KOLI
      MKOLI=TRAN(KOLI,'99999.999')
      MMKOLI=SUBSTR(MKOLI,1,5)+SUBSTR(MKOLI,7,3)
      M1LEN=LEN(ALLTRIM(MMKOLI))
      IF M1LEN<8
         MMKOLI=REPLI('0',8-M1LEN)+ALLTRIM(MMKOLI)
      ENDIF
      MMALCENA=TRAN(MALCENA,'999999.99')
      MMMALCENA=SUBSTR(MMALCENA,1,6)+SUBSTR(MMALCENA,8,2)
      M1LEN=LEN(ALLTRIM(MMMALCENA))
      IF M1LEN<8
         MMMALCENA=REPLI('0',8-M1LEN)+ALLTRIM(MMMALCENA)
      ENDIF
      MSTORN=STORNIRAN
      IF MSTORN='  '
         MSTORN='00'
      ENDIF
      MNAZ=SUBSTR(NAZ,1,30)
      MRSIF=ALLTRIM(RSIF)
      MLENRSIF=LEN(MRSIF)
      MBARKOD=REPLI('0',13-MLENRSIF)+MRSIF
      DO CASE TARIFA
      CASE TARIFA='      '
         MPG='01'
      CASE ALLTRIM(TARIFA)=TOSTOPA
         MPG='03'
      OTHERWISE
         MPG='04'
      ENDCASE
      iF tobveznik='N'
         MPG='00'
      ENDIF   
      IF M2KOLI<>0
         MM='200'+MNAZ+MMMALCENA+MMKOLI+MSTORN+MBARKOD+MPG
         FPUTS(bobi,MM)
         MAMAL=MAMAL+MALVRED
      ENDIF   
      SKIP
   ENDDO 
   GO TOP
      MGOTOVINA=TRAN(GOTOVINA,'999999.99')
      MKARTICA =TRAN(KARTICA ,'999999.99')
      MCEK     =TRAN(CEK     ,'999999.99')
      IF KARTICA<>0
         MGOT=TRAN(KARTICA,'999999.99')
         MMGOT=SUBSTR(MGOT,1,6)+SUBSTR(MGOT,8,2)
         M1LEN=LEN(ALLTRIM(MMGOT))
         IF M1LEN<8
            MMGOT=REPLI('0',8-M1LEN)+ALLTRIM(MMGOT)
         ENDIF
         MM='300'+MMGOT+'02'
         FPUTS(bobi,MM)
      ENDIF
      IF CEK    <>0
         MGOT=TRAN(CEK,'999999.99')
         MMGOT=SUBSTR(MGOT,1,6)+SUBSTR(MGOT,8,2)
         M1LEN=LEN(ALLTRIM(MMGOT))
         IF M1LEN<8
           MMGOT=REPLI('0',8-M1LEN)+ALLTRIM(MMGOT)
         ENDIF
         MM='300'+MMGOT+'01'
         FPUTS(bobi,MM)
      ENDIF
      IF GOTOVINA<>0
         MGOT=TRAN(GOTOVINA,'999999.99')
         MMGOT=SUBSTR(MGOT,1,6)+SUBSTR(MGOT,8,2)
         M1LEN=LEN(ALLTRIM(MMGOT))
         IF M1LEN<8
            MMGOT=REPLI('0',8-M1LEN)+ALLTRIM(MMGOT)
         ENDIF
         MM='300'+MMGOT+'00'
         FPUTS(bobi,MM)
      ENDIF
   FCLOSE(bobi)
   *------PRENOS PODATAKA U ODGOVARAJUCU PUTANJU
   MPUTANJA='C:\IPOS\BON'
*   SET PATH TO &MPUTANJA
*   SET DEFAULT TO &MPUTANJA
  
   COPY FILE &MMIME TO &MPUTANJA
   DELETE FILE (MMIME)
   SELECT KASA
   GO TOP
   DO KASASNIMAJ 
   SELECT KASA
   ZAP
   SELECT ROB
   POP KEY
