PARAMETERS MADATO,MASACEKAJ
PUSH KEY CLEAR
   IF AKONTRAKA=1.OR.AKONTRAKA=2
   *-----------PUNJENJE ARTIKALA----------------------------------
   SELECT KASA
   GO TOP
   MGOTOVINA=GOTOVINA
   MCEK=CEK
   MKARTICA=KARTICA

   IF FILE(KKOCKAX)
      DELETE FILE &KKOCKAX
   ENDIF
   IF FILE(KKOCKAX2)
      DELETE FILE &KKOCKAX2
   ENDIF
   SELECT KASA
   COPY TO &KKOCKA
   USE FIRMA IN 0
   USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
   SET EXACT ON
   SELECT KOCKA
   INDEX ON RSIF TAG RSIF
   SET ORDER TO 1
   TOTAL ON RSIF TO &KKOCKA2 FIELDS RSIF,KOLI
   DELETE ALL
   PACK

   APPEND FROM &KKOCKA2
   DELETE ALL FOR KOLI=0
   PACK
   GO TOP
   SET EXACT OFF 
   SET CENTURY ON
   *SET STEP ON 
   IF AKONTRAKA<>2
      IF MKAMARKA<>8
         REPORT FORM KASAkafanarac TO print
      ELSE
         REPORT FORM KASAMALIPRN TO print
      ENDIF
   ELSE
      REPORT FORM KASAMALIPRN TO print
   ENDIF   
   SELECT KOCKA
   USE
   SELECT FIRMA
   USE
   SELECT KASA
   GO TOP
   ENDIF
POP KEY   