PUSH KEY CLEAR
DO FORM KASAFAKZBIRNIS
SELECT fak
SET ORDER TO 
SET RELATION to
SELECT FAKG
SET ORDER TO 1
SET RELATION to
SET RELATION TO sifra INTO AN0  ADDITIVE

SELECT FAK
SET RELATION TO BRKAL INTO FAKG  ADDITIVE
SET RELATION TO RSIF INTO ROB ADDITIVE

POP KEY
