PUSH KEY CLEAR
SELECT KASAKR
SET ORDER TO 
GO BOTTOM
IF RECCOUNT()<1.OR.ARHIVA<>' '
MFLSIFRA=FLSIFRA
USE &KKASA IN 0 ALIAS KASA EXCLU 
SELECT kasa
SET ORDER TO
GO TOP
REPLACE FLSIFRA WITH MFLSIFRA
MMALVRED=0
DO WHILE.NOT.EOF()
   IF NMALVRED=0
      MMALVRED=MMALVRED+MALVRED
      ELSE
      MMALVRED=MMALVRED+NMALVRED
      endif      
      SKIP
   ENDDO 
   IZNOSRAC=MMALVRED  
   AMADATO=IZNOSRAC
USE
IF MMALVRED<>0

SELECT KASAKR
IF RECCOUNT()>0
   SET ORDER TO 
   GO BOTTOM
  * IF ARHIVA<>' '
      APPEND BLANK
      GO BOTTOM
      MOREDNI=TTVREDNI
      MLEN=LEN(MOREDNI)
      MREDNI=RECNO()
      MLENREDNI=LEN(ALLTRIM(STR(MREDNI,5,0)))
      MSLEDECI=ALLTRIM(STR(MREDNI,5,0))
      REPLACE BRKRED WITH MOREDNI+REPLICATE('0',6-MLEN-MLENREDNI)+MSLEDECI
      REPLACE DOK WITH TOBJEKAT+TTVREDNI
      REPLACE DATDOK WITH DATE()
      replace malvred WITH mmalvred
      KASAKR.GRD0.SETFOCUS
      KASAKR.REFRESH
  * ENDIF  
ELSE
      APPEND BLANK
      GO BOTTOM
      MOREDNI=TTVREDNI
      MLEN=LEN(MOREDNI)
      MREDNI=RECNO()
      MLENREDNI=LEN(ALLTRIM(STR(MREDNI,5,0)))
      MSLEDECI=ALLTRIM(STR(MREDNI,5,0))
      REPLACE BRKRED WITH MOREDNI+REPLICATE('0',6-MLEN-MLENREDNI)+MSLEDECI
      REPLACE DOK WITH TOBJEKAT+TTVREDNI
      replace datdok WITH DATE()
      replace malvred WITH mmalvred
   KASAKR.GRD0.SETFOCUS
   KASAKR.REFRESH
ENDIF
DO KASAKRKART
ELSE
DO PORUKAU WITH ' NEMA STAVKI U KASI '
ENDIF
ENDIF
SELECT KASAKR
POP KEY