SELECT KASAKR
MSADA=SADA
MDINSADA=DINSADA
MRATA=RATA
MDANA=DANA
MDATDOK=DATDOK
*SELECT KASA
*GO TOP
*MMALVRED=0
*DO WHILE.NOT.EOF()
*   MMALVRED=MMALVRED+MALVRED-RABAT
*   SKIP
*ENDDO   
*SELECT KASAKR
*REPLACE MALVRED WITH MMALVRED
MMALVRED=MALVRED
IF MRATA>0
   MRATA1=ROUND(MMALVRED/RATA,0)
ELSE
   MRATA1=0
ENDIF
IF KAMPROC>0
   MKAMATA=ROUND(KAMPROC*MALVRED/100,0)
   REPLACE KAMATA WITH MKAMATA
ELSE
   REPLACE KAMATA WITH 0
ENDIF
REPLACE UKUPNO WITH MALVRED+KAMATA
MUKUPNO=UKUPNO
IF MSADA='D'
   IF dinsada=0
      mdinsada=mrata1
      REPLACE DINSADA WITH mdinsada
      REPLACE PRDIN1 WITH MDINSADA
   ELSE
      mdinsada=dinsada  
      REPLACE DINSADA WITH mdinsada
      REPLACE PRDIN1 WITH MDINSADA
   endif
   MKREDIT=MMALVRED-MDINSADA
   J=mrata-1
   REPLACE KREDIT WITH MKREDIT
   IF MRATA-1>0
      MRATA1=ROUND(MKREDIT/(MRATA-1),0)
   ELSE
      MRATA1=0
   ENDIF   
ELSE
   MKREDIT=MMALVRED
   REPLACE KREDIT WITH MKREDIT
   replace dinsada WITH 0
   J=mrata
ENDIF

MPRI=DATE()
MDANA=0
*SET STEP ON 
FOR I=1 TO 12 
 IF I<=MRATA 
   IF MSADA='D'
      IF I>1
         MDANA=MDANA+DANA
         MMPRI='PR'+ALLTRIM(STR(I,2,0))
         MMPRDIN='PRDIN'+ALLTRIM(STR(I,2,0))
         MMPV='PV'+ALLTRIM(STR(I,2,0))
         MPRI=MDANA
         REPLACE &MMPRI WITH MPRI
         REPLACE &MMPRDIN WITH MRATA1
         REPLACE &MMPV WITH MDATDOK+MDANA
      ELSE
         REPLACE PR1 WITH 0
         REPLACE PRDIN1 WITH MDINSADA
         REPLACE PV1 WITH MDATDOK
      ENDIF   
   ELSE
      MDANA=MDANA+DANA
      MMPRI='PR'+ALLTRIM(STR(I,2,0))
      MMPRDIN='PRDIN'+ALLTRIM(STR(I,2,0))
      MMPV='PV'+ALLTRIM(STR(I,2,0))
      MPRI=MDANA
      REPLACE &MMPRI WITH MPRI
      REPLACE &MMPRDIN WITH MRATA1
      REPLACE &MMPV WITH MDATDOK+MDANA
   ENDIF   
 ELSE
   MMPRI='PR'+ALLTRIM(STR(I,2,0))
   MMPRDIN='PRDIN'+ALLTRIM(STR(I,2,0))
   MMPV='PV'+ALLTRIM(STR(I,2,0))
   MPRI=0
   REPLACE &MMPRI WITH 0
   REPLACE &MMPRDIN WITH 0
   REPLACE &MMPV WITH CTOD('')
 ENDIF  
NEXT

PUSH KEY CLEAR
SELECT KASAKR
MSVEGA=PRDIN1+PRDIN2+PRDIN3+PRDIN4+PRDIN5+PRDIN6+PRDIN7+PRDIN8+PRDIN9+PRDIN10+PRDIN11+PRDIN12
MRAZLIKA=MMALVRED-MSVEGA
IF MRAZLIKA<>0
   REPLACE PRDIN1 WITH PRDIN1+MRAZLIKA
   IF MSADA='D'
      REPLACE DINSADA WITH PRDIN1
      MKREDIT=MMALVRED-MDINSADA
   REPLACE KREDIT WITH MKREDIT
   ENDIF   
ENDIF
MSVEGA=PRDIN1+PRDIN2+PRDIN3+PRDIN4+PRDIN5+PRDIN6+PRDIN7+PRDIN8+PRDIN9+PRDIN10+PRDIN11+PRDIN12
MRAZLIKA=MMALVRED-MSVEGA
kasakrkart.txtnaplata.value=KAMATA+dinsada
KASAKRKART.ReFRESH
POP KEY

