PARAMETERS MADATO,MASACEKAJ
PUSH KEY CLEAR
*--------------FISKALNI STAMPAC EI PARTNER
   SELECT KASA
   GO TOP
   MGOTOVINA=GOTOVINA
   MCEK=CEK
   MKARTICA=KARTICA
   SET EXACT OFF 
   SET CENTURY ON
   mrec=1000
   *-------odredjujemo broj-------------
    USE KASABROJ IN 0
    SELECT KASABROJ
    GO BOTTOM
    IF RECCOUNT()>0
       MZADNJIbr=VAL(BRKAl)
    ELSE
       mzadnjibr=0
    ENDIF
   * SET STEP ON 
    IF RECCOUNT()>1
       MNOVI=ALLTRIM(STR(mzadnjibr+1,6,0))
       MLEN=LEN(MNOVI)
       MN2=REPLICATE('0',6-MLEN)+MNOVI  
       MN2BRKAL=MN2
    ELSE
       MN2BRKAL='000001'
    ENDIF   
    MREC=RECCOUNT()+1
    USE   
    MIME=REPLI('0',5-LEN(ALLTRIM(STR(MREC,5,0))))+ALLTRIM(STR(MREC,5,0))
    *-------formiran je naziv datoteke
    SELECT KASA
    GO TOP
    MAMAL=0
    MMIME=MIME+'.BON'
    *----------FORMIRAMO PRVI RED DATOTEKE
    MDANAS=SUBSTR(DTOC(DATE()),1,2)+SUBSTR(DTOC(DATE()),4,2)+SUBSTR(DTOC(DATE()),7,4)
    MVREME=SUBSTR(TIME(),1,2)+SUBSTR(TIME(),4,2)+SUBSTR(TIME(),7,2)
    MM='100'+MDANAS+MVREME+MIME+'01'
    *---KREIRAMO DATOTEKU------------
    bobi=FCREATE(MMIME)
    FPUTS(bobi,MM)
    DO WHILE.NOT.EOF()
      MRSIF=RSIF
      M2KOLI=ABS(KOLI)
      MKOLI=TRAN(ABS(KOLI),'99999.999')
      MMKOLI=SUBSTR(MKOLI,1,5)+SUBSTR(MKOLI,7,3)
      M1LEN=LEN(ALLTRIM(MMKOLI))
      IF M1LEN<8
         MMKOLI=REPLI('0',8-M1LEN)+ALLTRIM(MMKOLI)
      ENDIF
      MMALCENA=TRAN(MALCENA,'9999999.99')
      MMMALCENA=SUBSTR(MMALCENA,1,7)+SUBSTR(MMALCENA,9,2)
      M1LEN=LEN(ALLTRIM(MMMALCENA))
      IF M1LEN<9
         MMMALCENA=REPLI('0',9-M1LEN)+ALLTRIM(MMMALCENA)
      ENDIF
      MSTORN=STORNIRAN
      IF KOLI>0
         MSTORN='00'
      ELSE
         MSTORN='01'   
      ENDIF
      MNAZ=SUBSTR(NAZ,1,30)
      MRSIF=ALLTRIM(RSIF)
      MLENRSIF=LEN(MRSIF)
      MBARKOD=REPLI('0',13-MLENRSIF)+MRSIF
      IF aobveznik=1
      DO CASE TARIFA
      CASE TARIFA='      '
         MPG='01'
      CASE ALLTRIM(TARIFA)=TOSTOPA
         MPG='03'
      OTHERWISE
         MPG='04'
      ENDCASE
      ELSE
         MPG='00'
      endif         
*      IF STORNO<>'S'
            MM='200'+MNAZ+MMMALCENA+MMKOLI+MSTORN+MBARKOD+MPG
            FPUTS(bobi,MM)
            IF MSTORN='00'
            MAMAL=MAMAL+MALVRED
            ELSE
            MAMAL=MAMAL-ABS(MALVRED)
            ENDIF
*      ENDIF
      SKIP
   ENDDO 
   GO TOP
      MGOTOVINA=TRAN(GOTOVINA,'999999999.99')
      MKARTICA =TRAN(KARTICA ,'999999999.99')
      MCEK     =TRAN(CEK     ,'999999999.99')
      IF KARTICA<>0
         MGOT=TRAN(KARTICA,'999999999.99')
         MMGOT=SUBSTR(MGOT,1,9)+SUBSTR(MGOT,11,2)
         M1LEN=LEN(ALLTRIM(MMGOT))
         IF M1LEN<10
            MMGOT=REPLI('0',11-M1LEN)+ALLTRIM(MMGOT)
         ENDIF
         MM='300'+MMGOT+'02'
         FPUTS(bobi,MM)
      ENDIF
      IF CEK    <>0
         MGOT=TRAN(CEK,'999999999.99')
         MMGOT=SUBSTR(MGOT,1,9)+SUBSTR(MGOT,11,2)
         M1LEN=LEN(ALLTRIM(MMGOT))
         IF M1LEN<10
           MMGOT=REPLI('0',11-M1LEN)+ALLTRIM(MMGOT)
         ENDIF
         MM='300'+MMGOT+'01'
         FPUTS(bobi,MM)
      ENDIF
      IF GOTOVINA<>0
         MGOT=TRAN(GOTOVINA,'999999999.99')
         MMGOT=SUBSTR(MGOT,1,9)+SUBSTR(MGOT,11,2)
         M1LEN=LEN(ALLTRIM(MMGOT))
         IF M1LEN<10
            MMGOT=REPLI('0',11-M1LEN)+ALLTRIM(MMGOT)
         ENDIF
         MM='300'+MMGOT+'00'
         FPUTS(bobi,MM)
      ENDIF
   FCLOSE(bobi)
   *------PRENOS PODATAKA U ODGOVARAJUCU PUTANJU
   MPUTANJA='C:\IPOS\BON'
*   MPUTANJA2='C:'   
*   SET PATH TO &MPUTANJA
*   SET DEFAULT TO &MPUTANJA
   COPY FILE &MMIME TO &MPUTANJA
*   COPY FILE &MMIME TO &MPUTANJA2   
   DELETE FILE (MMIME)
 *  DO eifioka
   SELECT KASA
   M3MALVRED=TRANSFORM(MAMAL,'999 999.99')
   IF MaDATO>MAMAL
      MKUSUR=MaDATO-MAMAL
   ELSE
      MKUSUR=0
   ENDIF
  * dO METADISP WITH 'IZNOS ' +M3MALVRED,'KUSUR '+TRANSFORM(MKUSUR,'999 999.99')
   SELECT KASA
   GO TOP   
   DO KASASNIMAJ 
   SELECT KASA
   ZAP
   SELECT ROB
  
   POP KEY
