PUSH KEY CLEAR
SELECT KLPRO
SET ORDER TO 
GO BOTTOM
IF RECCOUNT()>0
   MRBR  =RBR
   MBRNAL=BRNAL
   MGRUPA=GRUPA
   APPEND BLANK
   REPLACE RBR WITH MRBR
   REPLACE GRUPA WITH MGRUPA
   REPLACE BRNAL WITH MBRNAL
ELSE
APPEND BLANK
ENDIF
KLPRO.GRD0.COLUMN1.SETFOCUS
POP KEY