PUSH KEY CLEAR
SELECT KLPRO
IF ARHIVA=' '
USE PROPAR IN 0 
SELECT PROPAR
MMAGPOLU=MAGPOLU
MFPPOLU=STR(VAL(FPPOLU),3,0)
USE

SELECT KLPRO
   MRBR=RBR
   SET ORDER TO 1
   SEEK MRBR
   MMIMA=0
   MDATDOK=DATDOK
   MRSIF=PSIF
   MBRNAL=BRNAL
   MRNAZ=ROB.NAZ
   KKAL='KAL'+ALLTRIM(MMAGPOLU)+'.DBF'
   KKALG='KALG'+ALLTRIM(MMAGPOLU)+'.DBF'
   USE &KKALG IN 0 ALIAS KALG
   SELECT KALG
   SET ORDER TO 3
   SEEK MBRNAL
   IF FOUND()
      MMIMA=1
      MBRKAL=BRKAL
   ELSE
      SET ORDER TO 1
      GO BOTTOM
      IF RECCOUNT()>0
         MBRKAL=BRKAL
      ELSE
         MBRKAL='000000'
      ENDIF
   ENDIF
   SET ORDER TO 
   BROJAC=1
   IF MMIMA=1
      MNBRKAL=MBRKAL
   ELSE
      MNBRKAL= REPLI('0',6-LEN(ALLTRIM((STR(VAL(MBRKAL)+BROJAC,6,0)))))+ALLTRIM((STR(VAL(MBRKAL)+BROJAC,6,0)))
   ENDIF
   *-------NASLI SMO RACUN SAD DODAJEMO STAVKE
   SELECT KALG
   IF MMIMA=0
      APPEND BLANK
      REPLACE BRKAL WITH MNBRKAL
      REPLACE BRRAC WITH MNBRKAL
      REPLACE FVRSTA WITH MFPPOLU
      REPLACE DOKUM WITH MNBRKAL
      REPLACE DATDOK WITH MDATDOK
      REPLACE VALUTA WITH MDATDOK
      REPLACE BRNAL WITH MBRNAL
      REPLACE RNAL WITH MBRNAL
      REPLACE SIFRA WITH '    1'
      REPLACE DATUM WITH DATE()
      REPLACE VREME WITH TIME()
   ELSE
      REPLACE BRKAL WITH MNBRKAL
      REPLACE BRRAC WITH MNBRKAL
      REPLACE FVRSTA WITH MFPPOLU
      REPLACE DATDOK WITH MDATDOK
      REPLACE VALUTA WITH MDATDOK
      REPLACE BRNAL WITH MBRNAL
      REPLACE RNAL WITH MBRNAL
      REPLACE SIFRA WITH '    1'
      REPLACE DATUM WITH DATE()
      REPLACE VREME WITH TIME()
   ENDIF
   USE
   USE &KKAL IN 0 ALIAS KAL
   SELECT KAL
   SET ORDER TO 1
   IF MMIMA=1
      LOCATE FOR BRKAL=MBRKAL

      IF FOUND()
         DO WHILE.NOT.EOF()
            IF BRKAL<>MBRKAL
               EXIT
            ENDIF
            REPLACE KOL WITH 0
            REPLACE CENA WITH 0
            REPLACE IZNOS WITH 0
            REPLACE VELCENA WITH 0
            REPLACE VELVRED WITH 0
            REPLACE BRKAL WITH ''
LOCATE FOR BRKAL=MBRKAL

            IF FOUND()
               LOOP
            ELSE
               EXIT
            ENDIF
            SKIP
         ENDDO
      ENDIF
   ENDIF
   SET ORDER TO 
   SELECT KLPRO
   SEEK MRBR
   DO WHILE.NOT.EOF()
      IF RBR<>MRBR
         EXIT
      ENDIF   
      MRSIF=PSIF
      MRKOL=KOL
      MRCENA=CENA
      MTARIFA=ROB.TARIFA
      MPROCPOR=ROB.PROCPOR
      REPLACE ARHIVA WITH '*'
      IF MRKOL<>0
         SELECT KAL
         APPEND BLANK
         REPLACE BRKAL WITH MNBRKAL
         REPLACE RSIF WITH MRSIF
         REPLACE KOL WITH MRKOL
         REPLACE CENA WITH MRCENA
         REPLACE VELCENA WITH MRCENA
         REPLACE IZNOS WITH ROUND(KOL*CENA,2)
         REPLACE VELVRED WITH ROUND(KOL*CENA,2)
         REPLACE TARIFA WITH MTARIFA
         REPLACE PROCPOR WITH MPROCPOR
         REPLACE POREZ WITH 0
         REPLACE MALVRED WITH VELVRED
         REPLACE MALCENA WITH CENA
         REPLACE DATDOK WITH MDATDOK
      ENDIF
      SELECT KLPRO
      SKIP
   ENDDO
   SELECT KAL
   USE
SELECT KLPRO
ELSE
   DO PORUKAU WITH 'NALOG JE PROKNJIŽEN '
ENDIF
KLPRO.GRD0.SETFOCUS
POP KEY