PUSH KEY CLEAR
SELECT KLZAP
SET ORDER TO 
IF RECCOUNT()>0
   MREDNI=REDNI
   MDATDOK=DATDOK
ELSE
   MREDNI='0001'
   MDATDOK=DATE()
ENDIF      
APPEND BLANK
REPLACE REDNI WITH MREDNI
REPLACE DATDOK WITH MDATDOK
KLZAP.GRD0.COLUMN1.SETFOCUS
POP KEY