PARAMETERS MKVREDNOST,MKKONTO,MBRNAL,MDATDOK,MOPIS,MDA,MMTR,MDEV,MDEVKURS
PUSH KEY CLEAR

IF MKVREDNOST<>0
   IF MKKONTO<>SPACE(10)
      APPEND BLANK
      IF MDA='D'
         REPLACE DUG WITH MKVREDNOST
         IF MDEVKURS<>0
            REPLACE DEVDUG WITH ROUND(MKVREDNOST/MDEVKURS,4)
         ENDIF
      ELSE
         REPLACE POT WITH MKVREDNOST
         IF MDEVKURS<>0
            REPLACE devPOT WITH ROUND(MKVREDNOST/MDEVKURS,4)
         ENDIF
      ENDIF
      REPLACE KONTO WITH MKKONTO
      REPLACE BRNAL WITH MBRNAL
      REPLACE DATDOK WITH MDATDOK
      REPLACE DATPDV WITH MDATDOK
      REPLACE OPIS WITH MOPIS
      REPLACE MTR WITH MMTR
      REPLACE DEV WITH MDEV
      REPLACE DEVKURS WITH MDEVKURS
   ENDIF
ENDIF   
POP KEY