PUSH KEY CLEAR
MISPRAVNO=0
FAK.CMDKNJIZIFAK0.SETFOCUS

*FAK.GRD0.COLUMN1.SETFOCUS
*FAK.VISIBLE=.F.
SELECT FAK
MBRKAL=BRKAL
MAKNJI=0
MVRSTAOBJ=FAKPRN.VRSTAOBJ
MISPRAVNOV=0
MBRRAC=ALLTRIM(FAKG.BRRAC)
MLENRAC=LEN(MBRRAC)
IF MVRSTAOBJ<>' '
   IF TOBJEKAT='V'
      IF MVRSTAOBJ='V'
         MISPRAVNOV=1
      ELSE
         MISPRAVNOV=0
      ENDIF
   ELSE
      IF MVRSTAOBJ='M'
         MISPRAVNOV=1
      ELSE
         MISPRAVNOV=0
      ENDIF
   ENDIF         
ELSE
   MISPRAVNOV=1
ENDIF         

IF FAKG.BRNAL<>SPACE(6).AND.MISPRAVNOV=1.AND.MLENRAC>0

IF EOF()
   WAIT windows ' sada smo na kraju '
   GO bottom
endif   
MBRKAL=BRKAL
IF FAKG.ARHIVA=' '
   MVNAL=FAKG.BRNAL
   REPLACE FAKG.DATUM WITH DATE()
   REPLACE FAKG.VREME WITH TIME()
   REPLACE FAKG.OPER WITH OPERATER

   DO IDEL WITH (KKOCKAX)
   DO IDEL WITH (KKOCKAX1)
   SELECT FAKG
   COPY STRUCTURE TO &KKOCKA1
   SELECT FAK
   COPY STRUCTURE TO &KKOCKA
   USE &KKOCKA IN 0 ALIAS KOCKA EXCLUSIVE
   USE &KKOCKA1 IN 0 ALIAS KOCKA1 EXCLUSIVE
   SELECT FAKG
   SCATTER NAME POLJA
   SELECT KOCKA1
   APPEND BLANK
   GATHER NAME POLJA
   SELECT FAK
   SET ORDER TO 1
   SEEK MBRKAL
   MVALDANA=AN0.VALDAN
   MVALDAN='   '
   SEEK MBRKAL
   IF FOUND()
      DO WHILE.NOT.EOF()
         IF BRKAL<>MBRKAL
            EXIT
         ENDIF
         IF koli<>0.or.vtxt<>' '
            DO CASE MVALDANA
            CASE MVALDANA=1
               MVALDAN=ROB.VALDAN1
            CASE MVALDANA=2
               MVALDAN=ROB.VALDAN2
            CASE MVALDANA=3
               MVALDAN=ROB.VALDAN3
            CASE MVALDANA=4
               MVALDAN=ROB.VALDAN4
            CASE MVALDANA=5
               MVALDAN=ROB.VALDAN5
            OTHERWISE
               MVALDAN='0'
            ENDCASE             
            REPLACE VALDAN WITH MVALDAN     
         ENDIF   
         SCATTER NAME POLJA
         SELECT KOCKA
         APPEND BLANK
         GATHER NAME POLJA
         SELECT KOCKA
         SELECT FAK
         SKIP
      ENDDO
   ENDIF       
   *-------------OVDE SE KOPIRA U SNIMAK-----------
*   SET STEP ON 
   MIME='0'+MVNAL
   MIME1='0'+MVNAL+'G'
   MMIME=MIME+'.DBF'
   MMIME1=MIME1+'.DBF'
   AGDE2=MSNIMAK+'\'+MSSNIMAK 
   SELECT KOCKA
   COPY TO &MIME
   COPY FILE &MMIME TO &AGDE2   
   ERASE &MMIME
   SELECT KOCKA
   USE
   SELECT KOCKA1
   COPY TO &MIME1
   COPY FILE &MMIME1 TO &AGDE2   
   ERASE &MMIME1
   SELECT KOCKA1
   USE
   *-------KRAJ KOPIRANJA U SNIMAK-----------------
   SELECT FAK
   SEEK MBRKAL
   IF FOUND()
      DO while.not.eof()
         IF BRKAL<>MBRKAL
            EXIT
         ENDIF
         IF KOLI=0.AND.CENA=0.AND.VELCENA=0.AND.MALCENA=0.AND.VTXT=' '
            REPLACE RSIF WITH SPACE(5)
         ENDIF   
         IF RSIF<>SPACE(5)
            IF DATDOK=CTOD('').OR.CENA=0.AND.VTXT=' '
               MISPRAVNO=1
            ENDIF
            IF TOBJEKAT='V'.AND.VTXT=' '
               IF VELCENA=0
                  MISPRAVNO=1
               ENDIF  
            ELSE
               IF VTXT=' '
                  IF MALCENA=0
                     MISPRAVNO=1
                  ENDIF 
               ELSE
                  MISPRAVNO=0
               ENDIF      
            ENDIF 
         ELSE
         ENDIF   
         SKIP
      ENDDO   
      SEEK MBRKAL         
      IF MISPRAVNO=0
         DO KNJIZIFAK WITH MBRKAL
         IF tnet=2
            SELECT FAK
            GO top
            DO while.not.eof()
               SCATTER NAME polja
               SELECT FAKS
               APPEND BLANK
               GATHER NAME polja
               SELECT FAK
               skip
            enddo   
         ENDIF
         MAKNJI=0
     ELSE
        DO PORUKAU WITH ' RACUN JE NEISPRAVAN JER NEMA CENU ILI DATUM '
      ENDIF   
   ENDIF
ELSE
   PUBLIC PPORUKA
   PPORUKA=' RAÈUN '+mBRKAL+' JE PROKNJIŽEN '
   DO PORUKA
   MAKNJI=1
ENDIF
IF tnet=1
   SELECT FAK
   IF EOF()
      GO BOTTOM
   ENDIF   
   FAK.GRD0.SETFOCUS
   FAK.REFRESH
ELSE
   IF MISPRAVNO=0
      SELECT FAK
      IF MAKNJI=0
         DELETE ALL
         PACK
      ENDIF
      FAK.release
   ENDIF   
endif

ELSE
   PUBLIC PPORUKA
   PPORUKA=' RAÈUN '+mBRKAL+' NEMA BROJA RACUNA,NALOGA, ILI JE NEISPR.VRSTA NALOGA '
   DO PORUKA
   SELECT FAK
ENDIF
*FAK.VISIBLE=.T.
POP KEY