PUSH KEY CLEAR

SET EXACT OFF

DO CASE TKOJI

CASE TKOJI='KAL'
SELECT KNJIZS
GO TOP
MBRNAL=BRNAL


USE NALAP IN 0 ORDER 2 ALIAS NALAP
SELECT NALAP
SEEK MBRNAL
IF FOUND()
   DO WHILE.NOT.EOF()
      IF BRNAL<>MBRNAL
         EXIT
      ENDIF
         REPLACE DUG WITH 0
         REPLACE POT WITH 0
         REPLACE KONTO WITH ''
         REPLACE OPIS WITH 'B'
      SKIP
   ENDDO   
ENDIF



USE NAL IN 0 ORDER 2 ALIAS NAL
SELECT NAL
SEEK MBRNAL
IF FOUND()
   DO WHILE.NOT.EOF()
      IF BRNAL<>MBRNAL
         EXIT
      ENDIF
         REPLACE DUG WITH 0
         REPLACE POT WITH 0
         REPLACE KONTO WITH ''
         REPLACE OPIS WITH 'B'
      SKIP
   ENDDO   
ENDIF
USE
*---------KNJIZENJE SINTETIKE------------

SELECT KNJIZS
GO TOP
DO WHILE.NOT.EOF()
   MKONTO=KONTO
   MDUG=DUG
   MPOT=POT
   MOPIS=OPIS
   MDATDOK=DATDOK
   MDOK=DOK
   IF SUBSTR(KONTO,1,4)<>'NEMA'
   SELECT NALAP
   APPEND BLANK
   REPLACE KONTO WITH MKONTO
   REPLACE DUG WITH MDUG
   REPLACE POT WITH MPOT
   REPLACE OPIS WITH MOPIS
   REPLACE DATDOK WITH MDATDOK
   REPLACE DOK WITH MDOK
   REPLACE BRNAL WITH MBRNAL   
   SELECT KNJIZS
   ENDIF
   SKIP
ENDDO   

SELECT NALAP
USE

*-----------KNJIZENJE ANALITIKE-------------


USE AAAN IN 0 ALIAS AAAN 

SELECT KNJIZA
GO TOP
KK=0
DO WHILE.NOT.EOF()
   MKONTO=KONTO
   MSIFRA=SIFRA
   MDATDOK=DATDOK
   MVALUTA=VALUTA
   MBRRAC=BRRAC
   MDUG=DUG
   MPOT=POT
   MDOK=DOK
   MOPIS=BRKAL
   SELECT AAAN
   LOCATE FOR KONTO=MKONTO
   IF FOUND()
      MREDNI=ALLTRIM(SIFPROD)
      KANAL='ANAL'+MREDNI
      USE &KANAL IN 0 ORDER 4 ALIAS ANAL
      
      SELECT ANAL
      IF KK=0
         SEEK MBRNAL
         IF FOUND()
            IF KK=0
               DO WHILE.NOT.EOF()
                  IF BRNAL<>MBRNAL
                     EXIT
                  ENDIF
                  REPLACE DUG WITH 0
                  REPLACE POT WITH 0
                  REPLACE BRRAC WITH ''
                  SKIP
               ENDDO   
            ENDIF   
         ENDIF
         KK=1
      ENDIF
      APPEND BLANK
      REPLACE KONTO WITH MKONTO
      REPLACE SIFRA WITH MSIFRA
      REPLACE DATDOK WITH MDATDOK
      REPLACE VALUTA WITH MVALUTA
      REPLACE BRRAC WITH MBRRAC
      REPLACE DUG WITH MDUG
      REPLACE POT WITH MPOT
      REPLACE BRNAL WITH MBRNAL
      REPLACE DOK WITH MDOK
      SELECT ANAL
      USE
   ENDIF
   SELECT KNJIZA
   SKIP
   IF KONTO<>MKONTO
      KK=0
      MKONTO=KONTO
   ENDIF      
ENDDO   




*-----------KNJIZENJE TRGOVACKE KNJIGE ILI KEPU-------------


IF TOBJEKAT='V'
   MTM='TVTM'+TREDNI
ELSE
   MTM='TM'+TREDNI
ENDIF

USE &KTM IN 0 ORDER 2 ALIAS TM

SELECT KNJIZT
GO TOP
KK=0
DO WHILE.NOT.EOF()
   MDATDOK=DATDOK
   MOPIS='KAL-'+BRKAL+'-'+DTOC(DATDOK)
   MUKNAB=UKNAB
   *MDOK=DOK
   MBRKAL=BRKAL
   SELECT TM
   SET ORDER TO 2
   LOCATE FOR BRKAL=MBRKAL

   IF .NOT.FOUND()
      APPEND BLANK
   ENDIF 
   REPLACE DATDOK WITH MDATDOK
   REPLACE OPIS WITH MOPIS
   REPLACE UKNAB WITH MUKNAB
*   REPLACE DOK WITH MDOK
   REPLACE BRNAL WITH MBRNAL   
   REPLACE BRKAL WITH MBRKAL
   SELECT KNJIZT
   SKIP
ENDDO   
USE
*--------KRAJ KNJIZENJA KEPU


*-----------KNJIZENJE KNJIGE PRIHODA---------


IF TOBJEKAT='M'
   MTM='TMP'+TREDNI
   USE &MTM IN 0 ORDER 2 ALIAS TMP
   
   SELECT KNJIZR
   GO TOP
   KK=0
   DO WHILE.NOT.EOF()
      MDATDOK=DATDOK
      MOPIS='KAL-'+BRKAL+'-'+DTOC(DATDOK)
      MPLACPOR=PLACPOR
      MNABVRED=NABVRED
      MMARZA=MARZA
      MPOREZ=POREZ
      MMALVRED=MALVRED
      MBRKAL=BRKAL
      MBRNAL=BRNAL
      SELECT TMP
      SET ORDER TO 2
LOCATE FOR BRKAL=MBRKAL

      IF .NOT.FOUND()
         APPEND BLANK
      ENDIF 
      REPLACE DATDOK WITH MDATDOK
      REPLACE OPIS WITH MOPIS
      REPLACE PLACPOR WITH MPLACPOR
      REPLACE NABVRED WITH MNABVRED
      REPLACE MARZA WITH MMARZA
      REPLACE POREZ WITH MPOREZ
      REPLACE MALVRED WITH MMALVRED
      REPLACE BRNAL WITH MBRNAL   
      REPLACE BRKAL WITH MBRKAL
      SELECT KNJIZR
      SKIP
   ENDDO   
   
SELECT TMP
USE
ENDIF
*--------KRAJ KNJIZENJA KNJIGE PRIHODA


*-----------KNJIZENJE KNJIGE PLACENOG POREZA-------------

USE PLACPOR IN 0 ORDER 3 ALIAS PLACPOR


*---------PRVI PROLAZ BRISE KALKULACIJE
SEEK MBRNAL
DO WHILE.NOT.EOF()
   IF BRNAL<>MBRNAL
      EXIT
   ENDIF   
   REPLACE POREZ WITH 0
   SKIP
ENDDO      

*-----DRUGI PROLAZ KNJIZI--------------

MMESTA=MBAZNI+'\'+'MESTA.DBF'
USE &MMESTA IN 0 ORDER 1 ALIAS MESTA
SET ORDER TO 1

SELECT KPLAC
SET RELATION TO TARIFA INTO TARIFA ADDITIVE
SET RELATION TO MP INTO MESTA ADDITIVE

DO WHILE.NOT.EOF()
   MDATDOK=DATDOK
   MDOK=DOK
   MTARIFA=TARIFA
   MPROCPOR=PROCPOR
   MPOREZ=POREZ
   MPOREZ1=POREZ1
   MPOREZ2=POREZ2
   MBRNAL=BRNAL
   MMP=MP

   MZIRO1=ALLTRIM(MESTA.ZIRO1)+'-'+ALLTRIM(TARIFA.ZIR1)+'-'+ALLTRIM(MESTA.ZIRO2)+'-'+ALLTRIM(TARIFA.ZIR1Z) 
   IF TARIFA.VOJ1=SPACE(5)
      MZIRO2=ALLTRIM(MESTA.ZIRO1)+'-'+ALLTRIM(TARIFA.ZIR2)+'-'+ALLTRIM(MESTA.ZIRO2)+'-'+ALLTRIM(TARIFA.ZIR2Z)    
   ELSE   
      MZIRO2=ALLTRIM(TARIFA.VOJ1)+'-'+ALLTRIM(TARIFA.ZIR2)+'-'+ALLTRIM(TARIFA.VOJ2)+'-'+ALLTRIM(TARIFA.ZIR2Z)       
   ENDIF
   if mporez1<>0
      sELECT PLACPOR
      APPEND BLANK
      REPLACE DATDOK WITH MDATDOK
      REPLACE TARIFA WITH MTARIFA
      REPLACE POREZ WITH MPOREZ1  
      REPLACE PROCPOR WITH MPROCPOR
      REPLACE BRNAL WITH MBRNAL
      REPLACE DOK WITH MDOK
      REPLACE MP WITH MMP
      replace zir with mziro1
   endif
   
   if mporez2<>0
      sELECT PLACPOR
      APPEND BLANK
      REPLACE DATDOK WITH MDATDOK
      REPLACE TARIFA WITH MTARIFA
      REPLACE POREZ WITH MPOREZ2  
      REPLACE PROCPOR WITH MPROCPOR
      REPLACE BRNAL WITH MBRNAL
      REPLACE DOK WITH MDOK
      REPLACE MP WITH MMP
      replace zir with mziro2
   endif

   SELECT KPLAC

   SKIP
ENDDO   
SELECT PLACPOR
USE
*--------KRAJ KNJIZENJA KNJIGE PLACENOG POREZA

*--------ARHIVIRANJE KALKULACIJE---------------------------------

USE &KKALG IN 0 ORDER 1 ALIAS KALG
SELECT KALG

SEEK ABRKAL
IF FOUND()
   REPLACE ARHIVA WITH '*'
ENDIF
USE   

*---------------PRENOS CENA IZ KALKULACIJA U SIFARNIK-----------

USE &KKAL IN 0 ORDER 1 ALIAS KAL

USE ROB IN 0 ORDER 1 ALIAS ROB

SELECT KAL
SEEK ABRKAL
IF FOUND()
   MDATNAB=DATDOK
   DO WHILE.NOT.EOF()
      IF BRKAL<>ABRKAL
         EXIT
      ENDIF   
      MRSIF=RSIF
      MNABCENA=NABCENA
      MZADNAB=CENA
      MVELCENA=VELCENA
      MMALCENA=MALCENA
      MKOL=KOL
      SELECT ROB
      SEEK MRSIF
      IF FOUND()
         IF TOBJEKAT='V'
            REPLACE VELCENA WITH MVELCENA
            REPLACE ZADNAB WITH MZADNAB
            REPLACE NABCENA WITH MNABCENA
            REPLACE ULAZ WITH ULAZ+KOL
         ELSE
            REPLACE MALCENA WITH MMALCENA
            REPLACE ZADNABM WITH MZADNAB
            REPLACE NABCENAM WITH MNABCENA
            REPLACE ULAZM WITH ULAZM+KOL
         ENDIF          
         REPLACE DATNAB WITH MDATNAB
      ENDIF   
      SELECT KAL
      SKIP
   ENDDO   
ENDIF
SELECT KAL
USE
SELECT ROB
USE


SELECT KNJIZA
GO TOP
SELECT KNJIZS
GO TOP

KNJIZI.RELEASE
*THISFORM.REFRESH


*----------------------KNJIZENJE RACUNA---------------------
*----------------------KNJIZENJE RACUNA---------------------
*----------------------KNJIZENJE RACUNA---------------------


CASE TKOJI='RAC'

SELECT KNJIZS
GO TOP
MBRNAL=BRNAL


USE NALAP IN 0 ORDER 2 ALIAS NALAP
SELECT NALAP
SEEK MBRNAL
IF FOUND()
   DO WHILE.NOT.EOF()
      IF BRNAL<>MBRNAL
         EXIT
      ENDIF
         REPLACE DUG WITH 0
         REPLACE POT WITH 0
         REPLACE KONTO WITH ''
         REPLACE OPIS WITH 'B'
      SKIP
   ENDDO   
ENDIF



USE NAL IN 0 ORDER 2 ALIAS NAL
SELECT NAL
SEEK MBRNAL
IF FOUND()
   DO WHILE.NOT.EOF()
      IF BRNAL<>MBRNAL
         EXIT
      ENDIF
         REPLACE DUG WITH 0
         REPLACE POT WITH 0
         REPLACE KONTO WITH ''
         REPLACE OPIS WITH 'B'
      SKIP
   ENDDO   
ENDIF
USE
*---------KNJIZENJE SINTETIKE------------

SELECT KNJIZS
GO TOP
DO WHILE.NOT.EOF()
   MKONTO=KONTO
   MDUG=DUG
   MPOT=POT
   MOPIS=OPIS
   MDATDOK=DATDOK
   MDOK=DOK
   IF SUBSTR(KONTO,1,4)<>'NEMA'
   SELECT NALAP
   APPEND BLANK
   REPLACE KONTO WITH MKONTO
   REPLACE DUG WITH MDUG
   REPLACE POT WITH MPOT
   REPLACE OPIS WITH MOPIS
   REPLACE DATDOK WITH MDATDOK
   REPLACE DOK WITH MDOK
   REPLACE BRNAL WITH MBRNAL   
   SELECT KNJIZS
   ENDIF
   SKIP
ENDDO   

SELECT NALAP
USE

*-----------KNJIZENJE ANALITIKE-------------


USE AAAN IN 0 ALIAS AAAN
SELECT KNJIZA
GO TOP
KK=0
DO WHILE.NOT.EOF()
   MKONTO=KONTO
   MSIFRA=SIFRA
   MDATDOK=DATDOK
   MVALUTA=VALUTA
   MBRRAC=BRRAC
   MDUG=DUG
   MPOT=POT
   MDOK=DOK
   MOPIS=BRKAL
   SELECT AAAN
   LOCATE FOR KONTO=MKONTO
   IF FOUND()
      MREDNI=ALLTRIM(SIFPROD)
      KANAL='ANAL'+MREDNI+'.DBF'
      
      USE &KANAL IN 0 ORDER 4 ALIAS ANAL
      SELECT ANAL      
      IF KK=0
         SEEK MBRNAL
         IF FOUND()
            IF KK=0
               DO WHILE.NOT.EOF()
                  IF BRNAL<>MBRNAL
                     EXIT
                  ENDIF
                  REPLACE DUG WITH 0
                  REPLACE POT WITH 0
                  REPLACE BRRAC WITH ''
                  SKIP
               ENDDO   
            ENDIF   
         ENDIF
         KK=1
      ENDIF
      APPEND BLANK
      REPLACE KONTO WITH MKONTO
      REPLACE SIFRA WITH MSIFRA
      REPLACE DATDOK WITH MDATDOK
      REPLACE VALUTA WITH MVALUTA
      REPLACE BRRAC WITH MBRRAC
      REPLACE DUG WITH MDUG
      REPLACE POT WITH MPOT
      REPLACE BRNAL WITH MBRNAL
      REPLACE DOK WITH MDOK
      SELECT ANAL
      USE
   ENDIF
   SELECT KNJIZA
   SKIP
   IF KONTO<>MKONTO
      KK=0
      MKONTO=KONTO
   ENDIF      
ENDDO   
SELECT AAAN
USE


*-----------KNJIZENJE TRGOVACKE KNJIGE ILI KEPU-------------


IF TOBJEKAT='V'
   MTM='TVTM'+TREDNI
ELSE
   MTM='TM'+TREDNI
ENDIF
USE &KTM IN 0 ORDER 2 ALIAS TM

SELECT KNJIZT
GO TOP
KK=0
DO WHILE.NOT.EOF()
   MDATDOK=DATDOK
   MOPIS='FAK-'+BRKAL+'-'+DTOC(DATDOK)
   MVREDPROD=VREDPROD
   *MDOK=DOK
LOCATE FOR BRKAL=MBRKAL

   SELECT TM
   SET ORDER TO 4
      LOCATE FOR BRKAL=MBRKAL

   IF .NOT.FOUND()
      APPEND BLANK
   ENDIF 
   REPLACE DATDOK WITH MDATDOK
   REPLACE OPIS WITH MOPIS
   REPLACE VREDPROD WITH MVREDPROD
*   REPLACE DOK WITH MDOK
   REPLACE BRNAL WITH MBRNAL   
   REPLACE BRFAK WITH MBRKAL
   SELECT KNJIZT
   SKIP
ENDDO   
USE
*--------KRAJ KNJIZENJA KEPU


*-----------KNJIZENJE KNJIGE PLACENOG POREZA-------------

USE PLACPOR IN 0 ORDER 3
SELECT PLACPOR

*---------PRVI PROLAZ BRISE KALKULACIJE
SEEK MBRNAL
DO WHILE.NOT.EOF()
   IF BRNAL<>MBRNAL
      EXIT
   ENDIF   
   REPLACE POREZ WITH 0
   SKIP
ENDDO      

*-----DRUGI PROLAZ KNJIZI--------------

MMESTA=MBAZNI+'\'+'MESTA.DBF'
USE &MMESTA IN 0 ORDER 1 ALIAS MESTA


SELECT KPLAC

SET RELATION TO TARIFA INTO TARIFA ADDITIVE
SET RELATION TO MP INTO MESTA ADDITIVE
GO TOP
DO WHILE.NOT.EOF()
   MDATDOK=DATDOK
   MDOK=DOK
   MTARIFA=TARIFA
   MPROCPOR=PROCPOR
   MPOREZ=POREZ
   MPOREZ1=POREZ1
   MPOREZ2=POREZ2
   MBRNAL=BRNAL
   MMP=MP
   MZIRO1=ALLTRIM(MESTA.ZIRO1)+'-'+ALLTRIM(TARIFA.ZIR1)+'-'+ALLTRIM(MESTA.ZIRO2)+'-'+ALLTRIM(TARIFA.ZIR1Z) 
   IF TARIFA.VOJ1=SPACE(5)
      MZIRO2=ALLTRIM(MESTA.ZIRO1)+'-'+ALLTRIM(TARIFA.ZIR2)+'-'+ALLTRIM(MESTA.ZIRO2)+'-'+ALLTRIM(TARIFA.ZIR2Z)    
   ELSE   
      MZIRO2=ALLTRIM(TARIFA.VOJ1)+'-'+ALLTRIM(TARIFA.ZIR2)+'-'+ALLTRIM(TARIFA.VOJ2)+'-'+ALLTRIM(TARIFA.ZIR2Z)       
   ENDIF
   if mporez1<>0
      sELECT PLACPOR
      APPEND BLANK
      REPLACE DATDOK WITH MDATDOK
      REPLACE TARIFA WITH MTARIFA
      REPLACE POREZ WITH -MPOREZ1  
      REPLACE PROCPOR WITH MPROCPOR
      REPLACE BRNAL WITH MBRNAL
      REPLACE DOK WITH MDOK
      REPLACE MP WITH MMP
      replace zir with mziro1
   endif
   
   if mporez2<>0
      sELECT PLACPOR
      APPEND BLANK
      REPLACE DATDOK WITH MDATDOK
      REPLACE TARIFA WITH MTARIFA
      REPLACE POREZ WITH -MPOREZ2  
      REPLACE PROCPOR WITH MPROCPOR
      REPLACE BRNAL WITH MBRNAL
      REPLACE DOK WITH MDOK
      REPLACE MP WITH MMP
      replace zir with mziro2
   endif

   SELECT KPLAC
   SKIP
ENDDO   
SELECT PLACPOR
USE
Select MESTA
use
*--------KRAJ KNJIZENJA KNJIGE PLACENOG POREZA

*-----------KNJIZENJE KNJIGE PRIHODA---------


IF TOBJEKAT='M'
   MTM='TMP'+TREDNI
   USE &MTM IN 0 ORDER 2 ALIAS TMP
   
   SELECT KNJIZR
   GO TOP
   KK=0
   DO WHILE.NOT.EOF()
      MDATDOK=DATDOK
      MOPIS='FAK-'+BRKAL+'-'+DTOC(DATDOK)
      MPROO=PROO
      MBRKAL=BRKAL
      MBRNAL=BRNAL
      SELECT TMP
      SET ORDER TO 4
LOCATE FOR BRKAL=MBRKAL

      IF .NOT.FOUND()
         APPEND BLANK
      ENDIF 
      REPLACE DATDOK WITH MDATDOK
      REPLACE OPIS WITH MOPIS
      REPLACE PROO WITH MPROO
      REPLACE BRNAL WITH MBRNAL   
      REPLACE BRFAK WITH MBRKAL
      SELECT KNJIZR
      SKIP
   ENDDO   
   SELECT TMP
   USE

ENDIF   
*--------KRAJ KNJIZENJA KNJIGE PRIHODA---------


*--------ARHIVIRANJE RACUNA---------------------------------


USE &KFAKG IN 0 ORDER 1 ALIAS FAKG
SELECT FAKG

SEEK ABRKAL

IF FOUND()
   
   REPLACE ARHIVA WITH '*'
ENDIF
USE   


*--------PRENOS CENA U SIFARNIK----------------




USE &KFAK IN 0 ORDER 1 ALIAS FAK


USE ROB IN 0 ORDER 1

SELECT FAK

SEEK ABRKAL
IF FOUND()
   DO WHILE.NOT.EOF()
      IF BRKAL<>ABRKAL
         EXIT
      ENDIF   
      MRSIF=RSIF
      MKOL=KOLI
      SELECT ROB
      SEEK MRSIF
      IF FOUND()
         IF TOBJEKAT='V'
            REPLACE IZLAZ WITH IZLAZ+MKOL
         ELSE
            REPLACE IZLAZM WITH IZLAZM+MKOL         
         ENDIF 
      ENDIF   
      SELECT FAK
      SKIP
   ENDDO   
ENDIF
SELECT FAK
USE
SELECT ROB
USE



SELECT KNJIZA
GO TOP
SELECT KNJIZS
GO TOP

KNJIZI.RELEASE
*THISFORM.REFRESH


*---------------------KNJIZENJE NIVELACIJA
*---------------------KNJIZENJE NIVELACIJA

CASE TKOJI='NIV'
SELECT KNJIZS
GO TOP
MBRNAL=BRNAL


USE NALAP IN 0 ORDER 2 ALIAS NALAP
SELECT NALAP
SEEK MBRNAL
IF FOUND()
   DO WHILE.NOT.EOF()
      IF BRNAL<>MBRNAL
         EXIT
      ENDIF
         REPLACE DUG WITH 0
         REPLACE POT WITH 0
         REPLACE KONTO WITH ''
         REPLACE OPIS WITH 'B'
      SKIP
   ENDDO   
ENDIF



USE NAL IN 0 ORDER 2 ALIAS NAL
SELECT NAL
SEEK MBRNAL
IF FOUND()
   DO WHILE.NOT.EOF()
      IF BRNAL<>MBRNAL
         EXIT
      ENDIF
         REPLACE DUG WITH 0
         REPLACE POT WITH 0
         REPLACE KONTO WITH ''
         REPLACE OPIS WITH 'B'
      SKIP
   ENDDO   
ENDIF
USE
*---------KNJIZENJE SINTETIKE------------

SELECT KNJIZS
GO TOP
DO WHILE.NOT.EOF()
   MKONTO=KONTO
   MDUG=DUG
   MPOT=POT
   MOPIS=OPIS
   MDATDOK=DATDOK
   MDOK=DOK
   IF SUBSTR(KONTO,1,4)<>'NEMA'
   SELECT NALAP
   APPEND BLANK
   REPLACE KONTO WITH MKONTO
   REPLACE DUG WITH MDUG
   REPLACE POT WITH MPOT
   REPLACE OPIS WITH MOPIS
   REPLACE DATDOK WITH MDATDOK
   REPLACE DOK WITH MDOK
   REPLACE BRNAL WITH MBRNAL   
   SELECT KNJIZS
   ENDIF
   SKIP
ENDDO   

SELECT NALAP
USE


*-----------KNJIZENJE TRGOVACKE KNJIGE ILI KEPU-------------


IF TOBJEKAT='V'
   MTM='TVTM'+TREDNI
ELSE
   MTM='TM'+TREDNI
ENDIF

USE &KTM IN 0 ORDER 2 ALIAS TM

SELECT KNJIZT
GO TOP
KK=0
DO WHILE.NOT.EOF()
   MDATDOK=DATDOK
   MOPIS='NIV-'+BRKAL+'-'+DTOC(DATDOK)
   MUKNAB=UKNAB
   *MDOK=DOK
   MBRKAL=BRKAL
   SELECT TM
   SET ORDER TO 2
      LOCATE FOR BRKAL=MBRKAL

   IF .NOT.FOUND()
      APPEND BLANK
   ENDIF 
   REPLACE DATDOK WITH MDATDOK
   REPLACE OPIS WITH MOPIS
   REPLACE UKNAB WITH MUKNAB
   REPLACE BRNAL WITH MBRNAL   
   REPLACE BRKAL WITH MBRKAL
   SELECT KNJIZT
   SKIP
ENDDO   
USE
*--------KRAJ KNJIZENJA KEPU


*-----------KNJIZENJE KNJIGE PRIHODA---------

IF TOBJEKAT='M'
   MTM='TMP'+TREDNI
   USE &MTM IN 0 ORDER 1 ALIAS TMP
   
   SELECT KNJIZR
   GO TOP
   KK=0
   DO WHILE.NOT.EOF()
      MDATDOK=DATDOK
      MOPIS='KAL-'+BRKAL+'-'+DTOC(DATDOK)
      MMARZA=MARZA
      MPOREZ=POREZ
      MMALVRED=MALVRED
      MBRKAL=BRKAL
      MBRNAL=BRNAL
      SELECT TMP
      SET ORDER TO 2
         LOCATE FOR BRKAL=MBRKAL

      IF .NOT.FOUND()
         APPEND BLANK
      ENDIF 
      REPLACE DATDOK WITH MDATDOK
      REPLACE OPIS WITH MOPIS
      REPLACE MARZA WITH MMARZA
      REPLACE POREZ WITH MPOREZ
      REPLACE MALVRED WITH MMALVRED
      REPLACE BRNAL WITH MBRNAL   
      REPLACE BRKAL WITH MBRKAL
      SELECT KNJIZR
      SKIP
   ENDDO   
ENDIF   
SELECT TMP
USE
*--------KRAJ KNJIZENJA KNJIGE PRIHODA


*--------ARHIVIRANJE KALKULACIJE---------------------------------
*---------------PRENOS CENA IZ NIVELACIJA U SIFARNIK-----------

USE &KTVNIV IN 0 ORDER 1 ALIAS NIV


USE ROB IN 0 ORDER 1

SELECT NIV
SEEK ABRKAL
IF FOUND()
   DO WHILE.NOT.EOF()
      IF BRKAL<>ABRKAL
         EXIT
      ENDIF   
      MRSIF=RSIF
      MVELCENA=VELCENA
      MMALCENA=MALCENA
      MKOL=KOL
      REPLACE ARHIVA WITH '*'
      SELECT ROB
      SEEK MRSIF
      IF FOUND()
         IF TOBJEKAT='V'
            REPLACE VELCENA WITH MVELCENA
         ELSE
            REPLACE MALCENA WITH MMALCENA
         ENDIF          
      ENDIF   
      SELECT NIV
      SKIP
   ENDDO   
ENDIF
SELECT NIV
USE
SELECT ROB
USE


SELECT KNJIZA
GO TOP
SELECT KNJIZS
GO TOP


KNJIZI.RELEASE
*THISFORM.REFRESH


*----------------------KNJIZENJE USLUGA---------------------
*----------------------KNJIZENJE USLUGA---------------------
*----------------------KNJIZENJE USLUGA---------------------


CASE TKOJI='U'

use &KuslG IN 0 ALIAS USLG ORDER 1
SELECT USLG
SEEK ABRKAL

IF FOUND()
   REPLACE ARHIVA WITH '*'
ENDIF

USE   

SELECT KNJIZS
GO TOP
MBRNAL=BRNAL


USE NALAP IN 0 ORDER 2 ALIAS NALAP
SELECT NALAP
SEEK MBRNAL
IF FOUND()
   DO WHILE.NOT.EOF()
      IF BRNAL<>MBRNAL
         EXIT
      ENDIF
         REPLACE DUG WITH 0
         REPLACE POT WITH 0
         REPLACE KONTO WITH ''
         REPLACE OPIS WITH 'B'
      SKIP
   ENDDO   
ENDIF



USE NAL IN 0 ORDER 2 ALIAS NAL
SELECT NAL
SEEK MBRNAL
IF FOUND()
   DO WHILE.NOT.EOF()
      IF BRNAL<>MBRNAL
         EXIT
      ENDIF
         REPLACE DUG WITH 0
         REPLACE POT WITH 0
         REPLACE KONTO WITH ''
         REPLACE OPIS WITH 'B'
      SKIP
   ENDDO   
ENDIF
USE
*---------KNJIZENJE SINTETIKE------------

SELECT KNJIZS
GO TOP
DO WHILE.NOT.EOF()
   MKONTO=KONTO
   MDUG=DUG
   MPOT=POT
   MOPIS=OPIS
   MDATDOK=DATDOK
   MDOK=DOK
   IF SUBSTR(KONTO,1,4)<>'NEMA'
   SELECT NALAP
   APPEND BLANK
   REPLACE KONTO WITH MKONTO
   REPLACE DUG WITH MDUG
   REPLACE POT WITH MPOT
   REPLACE OPIS WITH MOPIS
   REPLACE DATDOK WITH MDATDOK
   REPLACE DOK WITH MDOK
   REPLACE BRNAL WITH MBRNAL   
   SELECT KNJIZS
   ENDIF
   SKIP
ENDDO   

SELECT NALAP
USE

*-----------KNJIZENJE ANALITIKE-------------


USE AAAN IN 0 ALIAS AAAN
SELECT KNJIZA
GO TOP
KK=0
DO WHILE.NOT.EOF()
   MKONTO=KONTO
   MSIFRA=SIFRA
   MDATDOK=DATDOK
   MVALUTA=VALUTA
   MBRRAC=BRRAC
   MDUG=DUG
   MPOT=POT
   MDOK=DOK
   MOPIS=BRKAL
   SELECT AAAN
   LOCATE FOR KONTO=MKONTO
   IF FOUND()
      MREDNI=ALLTRIM(SIFPROD)
      KANAL='ANAL'+MREDNI+'.DBF'
      
      USE &KANAL IN 0 ORDER 4 ALIAS ANAL
      SELECT ANAL      
      IF KK=0
         SEEK MBRNAL
         IF FOUND()
            IF KK=0
               DO WHILE.NOT.EOF()
                  IF BRNAL<>MBRNAL
                     EXIT
                  ENDIF
                  REPLACE DUG WITH 0
                  REPLACE POT WITH 0
                  REPLACE BRRAC WITH ''
                  SKIP
               ENDDO   
            ENDIF   
         ENDIF
         KK=1
      ENDIF
      APPEND BLANK
      REPLACE KONTO WITH MKONTO
      REPLACE SIFRA WITH MSIFRA
      REPLACE DATDOK WITH MDATDOK
      REPLACE VALUTA WITH MVALUTA
      REPLACE BRRAC WITH MBRRAC
      REPLACE DUG WITH MDUG
      REPLACE POT WITH MPOT
      REPLACE BRNAL WITH MBRNAL
      REPLACE DOK WITH MDOK
      SELECT ANAL
      USE
   ENDIF
   SELECT KNJIZA
   SKIP
   IF KONTO<>MKONTO
      KK=0
      MKONTO=KONTO
   ENDIF      
ENDDO   
SELECT AAAN
USE



SELECT KNJIZA
GO TOP
SELECT KNJIZS
GO TOP
KNJIZI.RELEASE
*THISFORM.REFRESH

ENDCASE
POP KEY