PARAMETERS MKVREDNOST,MKKONTO,MBRNAL,MDATDOK,MOPIS,MDA,MEDATPRI,MEDATPDV
PUSH KEY CLEAR
IF MKVREDNOST<>0
   IF MKKONTO<>SPACE(10)
      APPEND BLANK
      IF MDA=UPPER('D')
         REPLACE DUG WITH MKVREDNOST
      ELSE
         REPLACE POT WITH MKVREDNOST
      ENDIF
      REPLACE KONTO WITH MKKONTO
      REPLACE BRNAL WITH MBRNAL
      REPLACE DATDOK WITH MDATDOK
      REPLACE DATPRI WITH MEDATPRI
      REPLACE DATPDV WITH MEDATPDV
      REPLACE OPIS WITH MOPIS
   ENDIF
ENDIF   
POP KEY