SELECT KOMANDE
mred=red
KOMANDE.GRD0.SETFOCUS
GO TOP
MBROJ=0
DO WHILE.NOT.EOF()
   IF red=mred
   IF ZNAK<>' '
      MBROJ=MBROJ+1
   ENDIF      
   endif
   SKIP
ENDDO   
GO TOP
DIMENSION JOZA[MBROJ] 
BROJAC=0
DO WHILE.NOT.EOF()
   IF red=mred
      IF ZNAK<>' '
         BROJAC=BROJAC+1
         MCMD=ALLTRIM(KOMANDA)
         JOZA[BROJAC]=MCMD
      ENDIF
   endif
   SELECT KOMANDE
   SKIP
ENDDO   
FOR I=1 TO BROJAC
   MCMD=JOZA[I]
   EXECSCRIPT(MCMD)
NEXT
KOMANDE.RELEASE
KEYBOARD '{ENTER}'
