SELECT KOMANDLE
MIME=ALLTRIM(IME)
SELECT KOMANDER
*SET STEP ON 
DO CASE 
CASE SUBSTR(MIME,1,2)='..'
*   SET STEP ON 
   CD..
   MNDIR=ADDBS(SYS(5)+SYS(2003))
   SELECT KOMANDER
   REPLACE FILTERLE WITH '*.*'
   REPLACE AKTDIRLE WITH ALLTRIM(MNDIR)   
   mfilterle=ALLTRIM(filterle)
   mfilterde=ALLTRIM(filterde)
   maktdirle=ALLTRIM(aktdirle)
   maktdirde=ALLTRIM(aktdirde)
   DO KOMANDERPROCITAJLE WITH MAKTDIRLE
CASE SUBSTR(MIME,1,2)='=>'
*   SET STEP ON 
   MNDIR=ALLTRIM(SUBSTR(MIME,3,60))
   SELECT KOMANDER
   REPLACE FILTERLE WITH '*.*'
   IF LEN(ALLTRIM(aktdirle))=3
      REPLACE AKTDIRLE WITH IMEDISKALE+':\'+MNDIR+'\'
   ELSE
      REPLACE AKTDIRLE WITH ALLTRIM(aktdirle)+MNDIR+'\'   
   endif   
   mfilterle=ALLTRIM(filterle)
   mfilterde=ALLTRIM(filterde)
   maktdirle=ALLTRIM(aktdirle)
   maktdirde=ALLTRIM(aktdirde)
   DO KOMANDERPROCITAJLE WITH MAKTDIRLE
OTHERWISE
   DO CASE
   CASE LOWER(RIGHT(MIME,4))=LOWER('.DBF')
      USE &MIME IN 0 ALIAS MIME
      SELECT MIME
      BROWSE
      USE
   CASE LOWER(RIGHT(MIME,4))=LOWER('.EXE')
      ! &MIME
   OTHERWISE
      MODIFY COMMAND &MIME
   ENDCASE
ENDCASE
KOMANDER.GRD1.BACKCOLOR=RGB(238,254,233)
KOMANDER.GRD0.BACKCOLOR=RGB(255,255,255)
KOMANDER.SHAPELEVO.backCOLOR=RGB(231,153,143)
KOMANDER.SHAPEDESNO.backCOLOR=RGB(242,242,242)
KOMANDER.GRD0.RECORDSOURCE='KOMANDLE'
KOMANDER.GRD1.RECORDSOURCE='KOMANDDE'
SELECT KOMANDLE
KOMANDER.REFRESH
KOMANDER.GRD0.SETFOCUS
