SELECT KOMANDDE
MIME=ALLTRIM(IME)
SELECT KOMANDER
DO CASE 
CASE SUBSTR(MIME,1,2)='..'
*   SET STEP ON 
   CD..
   MNDIR=ADDBS(SYS(5)+SYS(2003))
   SELECT KOMANDER
   REPLACE FILTERDE WITH '*.*'
   REPLACE AKTDIRDE WITH ALLTRIM(MNDIR)   
   mfilterDe=ALLTRIM(filterDe)
   mfilterLe=ALLTRIM(filterLe)
   maktdirDe=ALLTRIM(aktdirDe)
   maktdirLe=ALLTRIM(aktdirLe)
   DO KOMANDERPROCITAJDE WITH MAKTDIRDE
CASE SUBSTR(MIME,1,2)='=>'
*   SET STEP ON 
   MNDIR=ALLTRIM(SUBSTR(MIME,3,60))
   IF LEN(MNDIR)>0
      SELECT KOMANDER
      REPLACE FILTERDE WITH '*.*'
      IF LEN(ALLTRIM(aktdirDe))=3
         REPLACE AKTDIRDE WITH IMEDISKADE+':\'+MNDIR+'\'
      ELSE
         REPLACE AKTDIRDE WITH ALLTRIM(aktdirDe)+MNDIR+'\'   
      endif   
      mfilterDe=ALLTRIM(filterDe)
      mfilterLe=ALLTRIM(filterLe)
      maktdirDe=ALLTRIM(aktdirDe)
      maktdirLe=ALLTRIM(aktdirLe)
      DO KOMANDERPROCITAJDE WITH MAKTDIRDE
   ENDIF   
OTHERWISE
   DO CASE
   CASE LOWER(RIGHT(MIME,4))=LOWER('.DBF')
      USE &MIME IN 0 ALIAS MIME
      SELECT MIME
      BROWSE
      USE
   CASE LOWER(RIGHT(MIME,4))=LOWER('.EXE')
      ! &MIME
   OTHERWISE
      MODIFY COMMAND &MIME
   ENDCASE
ENDCASE
KOMANDER.GRD0.BACKCOLOR=RGB(238,254,233)
KOMANDER.GRD1.BACKCOLOR=RGB(255,255,255)
KOMANDER.SHAPEDESNO.BackCOLOR=RGB(231,153,143)
KOMANDER.SHAPELEVO.backCOLOR=RGB(242,242,242)
KOMANDER.GRD1.RECORDSOURCE='KOMANDDE'
KOMANDER.GRD0.RECORDSOURCE='KOMANDLE'
SELECT KOMANDDE
KOMANDER.REFRESH
KOMANDER.GRD1.SETFOCUS
