PARAMETERS MAKTDIRDE
SET DEFAULT TO &maktdirDe
SELECT komandDe
ZAP
APPEND BLANK
REPLACE IME WITH '..'
*-----CITANJE STABLA DIREKTORIJUMA
   local AKTDIR, SUBDIR, i
   local array NIZDIR[1]
   AKTDIR=ADDBS(MAKTDIRDE)   
   SUBDIR=adir(NIZDIR,MAKTDIRDE+"*.*","DHS")
   for i = 1 to SUBDIR
       if NIZDIR[i,1]#"." AND "D"$NIZDIR[i,5]
          MNIZDIR=NIZDIR[i,1]
          IF MNIZDIR<>'..'
             SELECT KOMANDDE
             APPEND BLANK
             REPLACE IME WITH '=> '+MNIZDIR         
          ENDIF
       ENDIF   
   NEXT
*------------------------------------   
GTABELE = ADIR(ETABELE, mfilterDe) 
FOR I = 1 TO GTABELE
   MPOLJE=ETABELE(I,1)
   MPOLJE2=ETABELE(I,2)
   MPOLJE3=ETABELE(I,3)
   MPOLJE4=ETABELE(I,4)   
   MPOLJE5=ETABELE(I,5)      
   SELECT KOMANDDE
   APPEND BLANK
   REPLACE IME WITH LOWER(MPOLJE)
*   MIME=IME
*   MAT=AT('.',MIME)
*   REPLACE IME WITH LOWER(SUBSTR(MIME,1,MAT-1))
*   REPLACE EXST WITH LOWER(SUBSTR(MIME,MAT+1,4))
   REPLACE DUZINA WITH MPOLJE2
   REPLACE DATUM WITH MPOLJE3
   REPLACE VREME WITH MPOLJE4
   REPLACE ATRIBUT WITH MPOLJE5 
endfor   
GO TOP
SELECT KOMANDLE
GO TOP   
SELECT KOMANDDE
GO TOP   
*KOMANDER.GRD1.column1.SETFOCUS
*KOMANDER.GRD1.refresh


