PARAMETERS AKONTO,ADAT0,ADAT1
PUSH KEY CLEAR
MKONTO=AKONTO
MDAT0=ADAT0
MDAT1=ADAT1
SET EXACT ON
MKLEN=LEN(ALLTRIM(MKONTO))
SELECT DATUMI
REPLACE DAT0 WITH MDAT0
REPLACE DAT1 WITH MDAT1
SELECT NALP
KKNALIZV=MDATA01+'\NALIZV'+OPERATER+'.DBF'
KKNALIZVX=MDATA01+'\NALIZV'+OPERATER+'.CDX'
KNALIZV=MDATA01+'\NALIZV'+OPERATER
KNALIZVX=MDATA01+'\NALIZV'+OPERATER


DO IDEL WITH (KKNALIZV)
DO IDEL WITH (KKNALIZVX)
DO IBAZE WITH KNALIZV,'NALIZV'
DO IIND WITH KNALIZV,'KONTO10+DTOS(DATDOK)','BRNAL','DTOS(DATDOK)',;
             'KONTO10+SIFRA+DTOS(DATDOK)','SIFRA+DTOS(DATDOK)','SIFRA+BRRAC+DTOS(DATDOK)'

USE &KNALIZV IN 0 ALIAS NALIZV EXCLUSIVE 

SELECT NALP
SET ORDER TO 1
SET EXACT OFF 
MK4NAZIV=KONTO.NAZIV
SEEK ALLTRIM(MKONTO)
IF FOUND()
   MPDUG=0
   MPPOT=0
   DO WHILE.NOT.EOF()
      IF SUBSTR(KONTO,1,MKLEN)<>ALLTRIM(MKONTO)
         EXIT
      ENDIF
      IF DATDOK<MDAT0
         MPDUG=MPDUG+DUG
         MPPOT=MPPOT+POT
      ENDIF
      SKIP
   ENDDO
   SELECT NALIZV
   IF MPDUG<>0.OR.MPPOT<>0
      APPEND BLANK
      REPLACE PDUG WITH MPDUG
      REPLACE PPOT WITH MPPOT
      REPLACE PSALDO WITH PDUG-PPOT    
      REPLACE K4NAZIV WITH MK4NAZIV
      REPLACE KONTO WITH MKONTO 
   ENDIF
   SELECT NALP
   SEEK ALLTRIM(MKONTO)
   DO WHILE.NOT.EOF()
      IF SUBSTR(KONTO,1,MKLEN)<>ALLTRIM(MKONTO)
         EXIT
      ENDIF
      IF DATDOK>=MDAT0.AND.DATDOK<=MDAT1
         MAKONTO=KONTO
         MBRNAL=BRNAL
         MDUG=DUG
         MPOT=POT
         MDATDOK=DATDOK
         MOPIS=OPIS
         SELECT NALIZV
         APPEND BLANK
         REPLACE KONTO10 WITH MAKONTO
         REPLACE BRNAL WITH MBRNAL
         REPLACE DUG WITH MDUG
         REPLACE POT WITH MPOT
         REPLACE DATDOK WITH MDATDOK
         REPLACE K4NAZIV WITH MK4NAZIV
         REPLACE OPIS WITH MOPIS
         SELECT NALP
      ENDIF 
      SKIP
   ENDDO
   SELECT NALIZV
   GO TOP
   MDUG=0
   MPOT=0
   MSALDO=0
   DO WHILE.NOT.EOF()
      MSALDO=MSALDO+DUG-POT+PSALDO
      REPLACE SALDO WITH MSALDO
      SKIP
   ENDDO   
   GO TOP
ENDIF   
SELECT NALIZV
GO TOP
*REPORT FORM KONTO10  PREVIEW 
   mfile='KONTO10'
   uslov=""
   DO printer_bullzip WITH mdata02,mfile,uslov

SELECT NALIZV 
USE
SELECT NALP
SET EXACT ON                                        
POP KEY