   PARAMETERS MDAT0,MDAT1,MBRNAL,mkonto
   PUSH KEY CLEAR
   USE AAAN IN 0 
   
   SELECT AAAN
   LLAST=RECCOUNT()
   USE ANAL1 IN 0
   SELECT ANAL1
   COPY STRUCTURE TO &KKOCKA 
   USE    
   DO IDEL WITH (KKOCKAX)
   DO IDEL WITH (KKOCKAX2)
   USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
   SELECT KOCKA
   INDEX ON 'KONTO+SIFRA+DEV+STR(DEVKURS,18,6)' TAG KONTO
   SET ORDER TO 1
   SELECT AAAN
   GO TOP
   DO WHILE.NOT.EOF()
      KKANAL ='ANAL'+ALLTRIM(SIFPROD)
      KK2ANAL ='ANAL'+ALLTRIM(SIFPROD)+'.DBF'
      M2KONTO=KONTO
      MANVRSTA=DP
      IF m2konto=mkonto.or.mkonto=SPACE(10)
         IF FILE(KK2ANAL)
            USE &KKANAL IN 0 ALIAS ANAL
            SELECT ANAL
            SET ORDER TO 3
            GO TOP
            DO WHILE.NOT.EOF()
               IF DATDOK>=MDAT0.AND.DATDOK<=MDAT1
                  MSIFRA=SIFRA
                  MDEVDUG=DEVDUG
                  MDEVPOT=DEVPOT
                  MDEV=DEV
                  MDEVKURS=DEVKURS
                  IF MDEVDUG<>0.OR.MDEVPOT<>0
                     SELECT KOCKA
                     APPEND BLANK
                     REPLACE SIFRA WITH MSIFRA
                     REPLACE DEV WITH MDEV
                     REPLACE DEVKURS WITH MDEVKURS
                     IF MANVRSTA='D'
                        REPLACE DEVDUG WITH MDEVDUG-MDEVPOT
                     ELSE
                        REPLACE DEVPOT WITH MDEVPOT-MDEVDUG
                     ENDIF
                     REPLACE KONTO WITH M2KONTO
                     REPLACE BRNAL WITH MBRNAL
                     SELECT ANAL
                  ENDIF
               ENDIF
               SKIP
             ENDDO
             SELECT ANAL
             USE
         endif 
      ENDIF   
      SELECT AAAN
      SKIP
   ENDDO


   SELECT KOCKA
   TOTAL ON KONTO+SIFRA+DEV+STR(DEVKURS,18,6) TO &KKOCKA2 FIELDS DEVDUG,DEVPOT
   USE
   SELECT AAAN
   USE
   SELECT ANKURSR
   DELETE ALL
   PACK
   APPEND FROM &KKOCKA2
   GO TOP
   REPLACE ALL DATOD WITH MDAT0
   REPLACE ALL DATDO WITH MDAT1
   GO TOP
   DO WHILE.NOT.EOF()
      MDEV=DEV+DTOS(MDAT1)
      SELECT DEV
      SET ORDER TO 1
      SEEK MDEV
      IF FOUND()
         MNDEVKURS=KURS
      ELSE
         MNDEVKURS=0
      ENDIF
      SELECT ANKURSR
      REPLACE NDEVKURS WITH MNDEVKURS
      SKIP
   ENDDO
   SELECT ANKURSR
   GO TOP
POP KEY

