PUSH KEY CLEAR
GO TOP
IF ARHIVA='*'
   MARHIVA=1
   LD.GRD0.READONLY=.F.
   LD.GRD0.BACKCOLOR=RGB(255,255,255)
ELSE
   MARHIVA=0
   LD.GRD0.READONLY=.T.
ENDIF      
DO WHILE.NOT.EOF()
   IF MARHIVA=0
      REPLACE ARHIVA WITH '*'
   ELSE
      REPLACE ARHIVA WITH ' '
   ENDIF
   SKIP
ENDDO   
GO TOP
POP KEY