PUSH KEY CLEAR
   select LDPARAM
   MCZAKON=CZAKON
   MPROCPOR=PROCPOR
   MMINIMAL=MINIMAL
   Adoppio=ROUND(doppr1/100,6)
   Adopzdr=ROUND(dopzr1/100,6)
   Adopnez=ROUND(dopnr1/100,6)
   ADOPSOC=ADOPPIO+ADOPZDR+ADOPNEZ 
   select LD
   MCASUK=CASUK
   MSTART=LDRAD.STARTBOD
   MMINIMAL2=MSTART*(MCASUK*100/MCZAKON/100)
   MDOTNETO=NETO
   IF MDOTNETO<MMINIMAL2
      REPLACE DOTACIJA WITH MMINIMAL2-MDOTNETO
   ELSE
      REPLACE DOTACIJA WITH 0
   ENDIF
POP KEY
