PUSH KEY CLEAR
   select LDPARAM
   MCZAKON=CZAKON
   MPROCPOR=PROCPOR
   MMINIMAL=MINIMAL
   Adoppio=ROUND(doppr1/100,6)
   Adopzdr=ROUND(dopzr1/100,6)
   Adopnez=ROUND(dopnr1/100,6)
   ADOPSOC=ADOPPIO+ADOPZDR+ADOPNEZ 
   select LD
   MCASUK=CASUK
   MMINIMAL2=MMINIMAL*(MCASUK*100/MCZAKON/100)
   MDOTBRUTO=DINUK+STIM1+STIM2+STIM3+TERENSKI+FIKSNA+DINSUS
   IF MDOTBRUTO<MMINIMAL2
      REPLACE DOTACIJA WITH MMINIMAL2-MDOTBRUTO
   ELSE
      REPLACE DOTACIJA WITH 0
   ENDIF
POP KEY
