PUBLIC KOMORE,aredispl,adatispl
PUSH KEY CLEAR

SELECT LDPARAM
KOMORE=KOMORAJ+KOMORAS+KOMORAR
mredispl=redispl
DO case
CASE mredispl=1
   mdatispl=dat1
CASE mredispl=2
   mdatispl=dat2
CASE mredispl=3
   mdatispl=dat3
OTHERWISE
   mredispl=4
   mdatispl=dat4
ENDCASE
aredispl=mredispl
adatispl=mdatispl
DO IDEL WITH (KKOCKAX)
DO IDEL WITH (KKOCKAX2)
SELECT LD
COPY TO &KKOCKA
USE &KKOCKA IN 0 ALIAS KOCKA EXCLUSIVE
SELECT KOCKA
INDEX ON DOK TAG DOK
SET ORDER TO 1
TOTAL ON DOK TO &KKOCKA2
ZAP
APPEND FROM &KKOCKA2
GO TOP
REPORT FORM LDGRUPE0DOK  PREVIEW 
SELECT KOCKA
USE
 SELECT LD
 SET ORDER TO  
 POP KEY