PUBLIC KOMORE,aredispl,adatispl
PUSH KEY CLEAR

SELECT LDPARAM
KOMORE=KOMORAJ+KOMORAS+KOMORAR
mredispl=redispl
DO case
CASE mredispl=1
   mdatispl=dat1
CASE mredispl=2
   mdatispl=dat2
CASE mredispl=3
   mdatispl=dat3
OTHERWISE
   mredispl=4
   mdatispl=dat4
ENDCASE
aredispl=mredispl
adatispl=mdatispl
SELECT LD
SET ORDER TO 5
DO IDEL WITH (KKOCKAX)
SORT ON GRUPA,GRUPA1 TO &KKOCKA
USE &KKOCKA IN 0 ALIAS KOCKA EXCLUSIVE
SELECT KOCKA
*SELECT * FROM LD WHERE (GRUPA=MGRUPA.OR.MGRUPA=0).AND.(MTR=MMTR.OR.MMTR=0)
REPORT FORM LDGRUPE10  PREVIEW 
SELECT KOCKA
USE

 SELECT LD
 SET ORDER TO  
 POP KEY