PUBLIC KOMORE,aredispl,adatispl
PUSH KEY CLEAR

SELECT LDPARAM
KOMORE=KOMORAJ+KOMORAS+KOMORAR
mredispl=redispl
DO case
CASE mredispl=1
   mdatispl=dat1
CASE mredispl=2
   mdatispl=dat2
CASE mredispl=3
   mdatispl=dat3
OTHERWISE
   mredispl=4
   mdatispl=dat4
ENDCASE
aredispl=mredispl
adatispl=mdatispl
DO IDEL WITH (KKOCKAX)
SELECT LD
SET ORDER TO 5
*SELECT * FROM LD WHERE (GRUPA=MGRUPA.OR.MGRUPA=0).AND.(MTR=MMTR.OR.MMTR=0)
TOTAL ON GRUPA TO &KKOCKA
USE &KKOCKA IN 0 ALIAS KOCKA EXCLUSIVE
SELECT KOCKA
REPORT FORM LDGRUPE0Z  PREVIEW 
SELECT KOCKA
USE
 SELECT LD
 SET ORDER TO  
 POP KEY