PUSH KEY CLEAR
SELECT LD
GO TOP
DO WHILE.NOT.EOF()
   IF umanjenje='30'
      MIME_PREZ=LDRAD.IME_PREZ
      Mmaticnibr=LDRAD.maticnibr
      MBRUTO=ROUND(bruto,0)
      MDOPPF=ROUND(DOPPF,0)
      MDOPZF=ROUND(DOPZF,0)
      MDOPNF=ROUND(DOPNF,0)
      MDOPPFS=ROUND(DOPPFS,0)
      MDOPZFS=ROUND(DOPZFS,0)
      MDOPNFS=ROUND(DOPNFS,0)
      MDOPPFU=ROUND(DOPPFU,0)
      MDOPZFU=ROUND(DOPZFU,0)
      MDOPNFU=ROUND(DOPNFU,0)
      MDOPPFR=ROUND(DOPPFU-DOPPF,0)
      MDOPZFR=ROUND(DOPZFU-DOPZF,0)
      MDOPNFR=ROUND(DOPNFU-DOPNF,0)
      SELECT LDINZS
      APPEND BLANK
      REPLACE REDNI WITH RECNO()
      REPLACE IME_PREZ WITH MIME_PREZ
      replace maticnibr WITH mmaticnibr
      REPLACE BRUTO WITH MBRUTO
      REPLACE DOPPF WITH MDOPPFS
      REPLACE DOPZF WITH MDOPZFS
      REPLACE DOPNF WITH MDOPNFS
      REPLACE DOPPFU WITH MDOPPFR
      REPLACE DOPZFU WITH MDOPZFR
      REPLACE DOPNFU WITH MDOPNFR
      REPLACE DOPPFR WITH MDOPPF
      REPLACE DOPZFR WITH MDOPZF
      REPLACE DOPNFR WITH MDOPNF
   ENDIF   
   SELECT LD
   SKIP
ENDDO   
SELECT LDINZS
GO TOP
POP KEY