PUSH KEY CLEAR
SELECT LDPARAM
MCMES=CMES
SELECT LD
GO TOP
DO WHILE.NOT.EOF()
   MIME_PREZ=LDRAD.IME_PREZ
   MMATICNIBR=LDRAD.MATICNIBR
   MBRUTO=BRUTO
   MNETO=NETO
   MPOREZ=POREZ
   MDOPZF=DOPZF
   MSVEGA=NETO+POREZ+DOPZF
   SELECT LDINV
   APPEND BLANK
   REPLACE IME_PREZ WITH MIME_PREZ
   REPLACE MATICNIBR WITH MMATICNIBR
   REPLACE NETO WITH MNETO
   REPLACE POREZ WITH MPOREZ
   REPLACE DOPZDR WITH MDOPZF
   REPLACE SVEGA WITH MSVEGA 
   REPLACE CASOVI WITH MCMES
   REPLACE OSTVARCAS WITH MCMES
   
   SELECT LD
   SKIP
ENDDO   
SELECT LDINV
GO TOP
POP KEY