PUSH KEY CLEAR
SELECT LDIZRVRE
SET RELATION TO
DO FORM LDRADKR
SELECT LDRAD
SET ORDER TO 1
MBROJ=BROJ
SELECT LDIZRVRE
IF BROJ<1
   REPLACE BROJ WITH MBROJ
ENDIF   
SET RELATION TO BROJ INTO LDRAD ADDITIVE
POP KEY
