PUSH KEY CLEAR
SELECT LDKRED
SET RELATION TO
DO FORM LDRADKR
SELECT LDRAD
SET ORDER TO 1
MBROJ=BROJ
SELECT LDKRED
IF BROJ<1
   REPLACE BROJ WITH MBROJ
ENDIF   
SET RELATION TO BROJ INTO LDRAD ADDITIVE
SET RELATION TO SIFRA INTO AN0 ADDITIVE
SET RELATION TO KREDIT INTO LDKREDR ADDITIVE
POP KEY
