PUSH KEY CLEAR
SELECT LDKRED
SET RELATION TO
TKOJI='PLATA'
DO FORM FAN0
SELECT AN0
SET ORDER TO 1
MSIFRA=SIFRA
SELECT LDKRED
IF SIFRA=SPACE(5).OR.SIFRA='    0'
   REPLACE SIFRA WITH MSIFRA
ENDIF
SET RELATION TO BROJ INTO LDRAD ADDITIVE
SET RELATION TO SIFRA INTO AN0 ADDITIVE
SET RELATION TO KREDIT INTO LDKREDR ADDITIVE
POP KEY

