PROCEDURE NZ1UZMI
PUSH KEY CLEAR
SELECT LD
GO TOP
DO WHILE.NOT.EOF()
   MIME_PREZ=LDRAD.IME_PREZ
   MBRUTO=BRUTO
   MPDETE=BRUTO
   MOSNOVP=BRUTO-POROSLOB
   MPOREZ=POREZ
   MZAISPLAT=NETO
   MDOP=DOPSOCF+DOPSOCR
   MOBAVEZA=NETO+POREZ+DOPSOCF+DOPSOCR
   SELECT LDNZ1
   APPEND BLANK
   REPLACE BR WITH STR(RECNO(),2,0)
   REPLACE IME_PREZ WITH MIME_PREZ
   REPLACE BRUTO WITH MBRUTO
   REPLACE PDETE WITH MPDETE
   REPLACE OSNOVP WITH MOSNOVP
   REPLACE POREZ WITH MPOREZ
   REPLACE ZAISPLAT WITH MZAISPLAT
   REPLACE DOP WITH MDOP
   REPLACE OBAVEZE WITH MOBAVEZA
   SELECT LD
   SKIP
ENDDO   
SELECT LDNZ1
GO TOP
POP KEY
ENDPROC