SELECT LDPARAM
ASOLOSN1=SOLOSN1
ASOLOSN2=SOLOSN2
ASOLOSN3=SOLOSN3
ASOLPROC1=SOLPROC1
ASOLPROC2=SOLPROC2
ASOLPROC3=SOLPROC3
MCZAKON=CZAKON
SELECT LD
GO TOP
DO WHILE.NOT.EOF()
   MNETO=NETO   
   MSOLPOR1=0
   MSOLPOR2=0
   MSOLPOR3=0
   IF CASUK<>0   
      MKOEFCAS=MCZAKON/CASUK
      IF MKOEFCAS<1
         MKOEFCAS=1
      ENDIF   
   ELSE
      MKOEFCAS=1
   ENDIF

   MSOLOSN1=ASOLOSN1/MKOEFCAS
   MSOLOSN2=ASOLOSN2/MKOEFCAS
   MSOLOSN3=ASOLOSN3/MKOEFCAS

   MSOLPROC1=ASOLPROC1
   MSOLPROC2=ASOLPROC2
   MSOLPROC3=ASOLPROC3

   IF MNETO>MSOLOSN1.AND.MNETO<=MSOLOSN2
      MSOLPOR1=ROUND(((MNETO)-MSOLOSN1)*MSOLPROC1/100,2)
   ENDIF
   IF MNETO>MSOLOSN2.AND.MNETO<=MSOLOSN3
      MSOLPOR1=ROUND((MSOLOSN2-MSOLOSN1)*MSOLPROC1/100,2)
      MSOLPOR2=ROUND((MNETO-MSOLOSN2)*MSOLPROC2/100,2)
   ENDIF
   IF MNETO>MSOLOSN3
      MSOLPOR1=ROUND((MSOLOSN2-MSOLOSN1)*MSOLPROC1/100,2)
      MSOLPOR2=ROUND((MSOLOSN3-MSOLOSN2)*MSOLPROC2/100,2)
      MSOLPOR3=ROUND((MNETO-MSOLOSN3)*MSOLPROC3/100,2)
   ENDIF
   
   REPLACE SOLIDARN WITH MSOLPOR1+MSOLPOR2+MSOLPOR3
   
   IF MSOLPOR1<>0
      REPLACE SOLOSN1 WITH MSOLOSN1
      REPLACE SOLPROC1 WITH MSOLPROC1
      REPLACE SOLPOR1 WITH MSOLPOR1
   ELSE
      REPLACE SOLOSN1 WITH 0
      REPLACE SOLPROC1 WITH 0
      REPLACE SOLPOR1 WITH  0  
   ENDIF   
      
   IF MSOLPOR2<>0
      REPLACE SOLOSN2 WITH MSOLOSN2
      REPLACE SOLPROC2 WITH MSOLPROC2
      REPLACE SOLPOR2 WITH MSOLPOR2
   ELSE
      REPLACE SOLOSN2 WITH 0
      REPLACE SOLPROC2 WITH 0
      REPLACE SOLPOR2 WITH  0  
   ENDIF   

   IF MSOLPOR3<>0
      REPLACE SOLOSN3 WITH MSOLOSN3
      REPLACE SOLPROC3 WITH MSOLPROC3
      REPLACE SOLPOR3 WITH MSOLPOR3
   ELSE
      REPLACE SOLOSN3 WITH 0
      REPLACE SOLPROC3 WITH 0
      REPLACE SOLPOR3 WITH  0  
   ENDIF   
  
   SKIP
ENDDO   
GO TOP