PROCEDURE LDOBRACUNA 
parameters aa,MGRUPA,ASABOL,ASAKOR,ASAPREBAC,ASAOBUSTAVE,anaknade
*MC = CENA RADA
SELECT LDPARAM
MPROCNOC=PROCNOC
MNOC=PROCNOC
MPROCPROD=PROCPROD
MPROD=PROCPROD
MPROCNED=PROCNED
MNED=MPROCNED
MPROCBOL=PROCBOL
MPROCPRAZ=PROCPRAZ
MPROCSUS=PROCSUS
mnaknade=anaknade
MDEZ=MPROCPRAZ
MPROCPLAC=PROCPLAC
MPROCMIN=PROCMIN
MCZAKON=CZAKON
MMESEC=MESEC
MISPLATA=ISPLATA
MPROSBRUTO=PROSBRUTO
MSRAZPOR=SRAZPOR
MMINNAC=MINNAC
MSTARTKOEF=EKOEFS
   PUBLIC MDECIMALE,MNEOPOREZ,MDEC,MNEOPOREZP
   MDECIMALE=DECIMALE
   MNEOPOREZ=NEOPOREZ
   MNEOPOREZP=NEOPOREZP
   IF MDECIMALE=' '
      MDEC=0
   ELSE
      MDEC=2
   ENDIF      

SELECT LD
IF LDRAD.GRUPA=MGRUPA.OR.MGRUPA=0
*------------PROMENLJIVE
mc=aa
MSABOL=ASABOL
MSAKOR=ASAKOR
MMPREBAC=ASAPREBAC
MSAOBUSTAVE=ASAOBUSTAVE
*-----------PROMENLJIVE--------


SB=ROUND(LDRAD.STARTBOD/MCZAKON,8)
SBMIN=ROUND(LDRAD.STARTBOD,8)

MMPROCMIN=LDRAD.STAZ*MPROCMIN
MPROSTIM=KOLSTIM+INDSTIM
MA1=MMPROCMIN
MA2=(100+MA1)/100

MMM=LDRAD.STARTBOD*MSTARTKOEF/MCZAKON

MSTARTCAS=MCZAKON
MBODVR=ROUND(CASVR*MMM,3)
MBODSLPUT=ROUND(CSLPUT*MMM,3)
MBODSUSP=ROUND(CSUSP*MMM*MPROCSUS/100,3)
MBODZASTOJ=ROUND(CZASTOJ*MMM,3)
MBODUC=ROUND(MBODVR*MMPREBAC,3)
IF MBODVR<>0
   MPREBAC=MBODUC/MBODVR
ELSE
   MPREBAC=1
ENDIF



MBODMIN=ROUND(MPREBAC*(MBODUC+MBODSLPUT)*MMPROCMIN/100,3)
MBODPRAZ=ROUND(MPREBAC*CASPRAZ*MMM*(100+MMPROCMIN)*(100+MPROSTIM)/100/100,3)
MBODDOR=ROUND(MPREBAC*CASDOR*MMM*(100+MMPROCMIN)*(100+MPROSTIM)/100/100,3)
MBODGOD=ROUND(MPREBAC*CASGOD*MMM*(100+MMPROCMIN)*(100+MPROSTIM)/100/100,3)
MBOD2PLAC=ROUND(MPREBAC*CASPLAC2*MMM*(100+MMPROCMIN)*(100+MPROSTIM)/100/100,3)
MBODNED=ROUND(MPREBAC*CASNED*MMM*MNED*(100+MMPROCMIN)*(100+MPROSTIM)/100/100/100,3)
MBODRADNAP=ROUND(MPREBAC*CASRADNAP*MMM*MDEZ*(100+MMPROCMIN)*(100+MPROSTIM)/100/100/100,3)
MBODNOC=ROUND(MPREBAC*CASNOC*MMM*MNOC/100,3)
MBODPROD=ROUND(MPREBAC*CASPROD*MMM*MPROD/100,3)
MBODPLAC=ROUND(MPREBAC*CASPLAC*MMM*MPROCPLAC*(100+MMPROCMIN)/100/100,3)
MBODVV=ROUND(MPREBAC*CASVV*MMM,3)
MBODOST1=ROUND(MPREBAC*CAS1*MMM,3)
MBODOST2=ROUND(MPREBAC*CAS2*MMM,3)
MBODLIC=ROUND((MBODUC+MBODSLPUT)*INDSTIM/100,3)
MBODKOL=ROUND((MBODUC+MBODSLPUT)*KOLSTIM/100,3)
MBODSZ=ROUND(MBODUC*STIMSZ/100,3)

mevidbroj=ldrad.evidbroj
replace evidbroj WITH mevidbroj

REPLACE DINMIN WITH ROUND(MBODMIN*MC,1)
REPLACE DINVR WITH ROUND(MBODVR*MC,2)
REPLACE DINUC WITH ROUND(MBODUC*MC,2)
REPLACE DINSL WITH ROUND(MBODSLPUT*MC,2)
REPLACE DINSUSP WITH ROUND(MBODSUSP*MC,2)
REPLACE DINZASTOJ WITH ROUND(MBODZASTOJ*MC,2)
REPLACE DINNOC WITH ROUND(MBODNOC*MC,2)
REPLACE DINPROD WITH ROUND(MBODPROD*MC,2)

REPLACE DINRADNAP WITH ROUND(MBODRADNAP*MC,2)
REPLACE DINDOR WITH ROUND(MBODDOR*MC,2)
REPLACE DIN2 WITH ROUND(MBODOST2*MC,2)
REPLACE DINPAUSAL WITH ROUND((DINUC+DINSL)*PAUSAL/100,2)
MSTARTBOD=LDRAD.STARTBOD
*SET STEP ON 
IF mnaknade<>'D'

   REPLACE DINPRAZ WITH ROUND(MBODPRAZ*MC,2)
   REPLACE DINPLAC WITH ROUND(MBODPLAC*MC,2)
   REPLACE DINPLAC2 WITH ROUND(MBOD2PLAC*MC,2)
   REPLACE DINVV WITH ROUND(MBODVV*MC,2)
   REPLACE DINGOD WITH ROUND(MBODGOD*MC,2)
   REPLACE DINNED WITH ROUND(MBODNED*MC,2)
   IF CASBOL<>0
      IF MSABOL='S'
         mbol=ROUND(MSTARTBOD*((100+(MMPROCMIN))/100)*MSTARTKOEF*MPROCBOL*MC*CASBOL/MSTARTCAS/100,2)
         if dinbol>mbol
            REPLACE DINBOL WITH mbol
         endif
         IF DINBOL=0
            REPLACE DINBOL WITH MBOL
         ENDIF
      ENDIF
      IF MSABOL='D'
         mnbol=ROUND(MSTARTBOD*((100+(MMPROCMIN))/100)*MSTARTKOEF*MPROCBOL*MC*CASBOL/MSTARTCAS/100,2)
         REPLACE DINBOL WITH mnbol
      ENDIF
   ELSE
      REPLACE DINBOL WITH 0
   ENDIF
   IF CAS3BOL<>0
      IF MSABOL='S'
         mbol=ROUND(MSTARTBOD*((100+(mmPROCMIN))/100)*MSTARTKOEF*MPROCBOL*MC*CAS3BOL/MSTARTCAS/100,2)
         if din3bol>mbol
            REPLACE DIN3BOL WITH mbol
         endif
         IF DIN3BOL=0
            REPLACE DIN3BOL WITH MBOL
         ENDIF
      ENDIF   
      IF MSABOL='D'
         mnbol=ROUND(MSTARTBOD*((100+(MMPROCMIN))/100)*MSTARTKOEF*MPROCBOL*MC*CAS3BOL/MSTARTCAS/100,2)
         REPLACE DIN3BOL WITH mnbol
      ENDIF
   ELSE
      REPLACE DIN3BOL WITH 0
   ENDIF
   ma1=mMPROCMIN*LDRAD.staz
   ma2=(100+ma1)/100
   
   IF CAS2BOL<>0
      IF MSABOL='D'
         mn2bol=ROUND(MSTARTBOD*((100+(MMPROCMIN))/100)*MSTARTKOEF*100*MC*CAS2BOL/MSTARTCAS/100,2)
         REPLACE DIN2BOL WITH mn2bol
      ENDIF
      IF MSABOL='S'
         M2BOL=ROUND(MSTARTBOD*((100+(mmPROCMIn)/100))/100*MSTARTKOEF*100*MC*CAS2BOL/MSTARTCAS/100,2)
   *      if din2bol>m2bol
         REPLACE DIN2BOL WITH m2bol
   *      endif
   *      IF DIN2BOL=0
   *         REPLACE DIN2BOL WITH M2BOL
   *      ENDIF
      ENDIF
   ELSE
      REPLACE DIN2BOL WITH 0
   ENDIF
   IF CAS4BOL<>0
      IF MSABOL='D'
         mn4bol=ROUND(MSTARTBOD*((100+(mmPROCMIN))/100)*MSTARTKOEF*100*MC*CAS4BOL/MSTARTCAS/100,2)
         REPLACE DIN4BOL WITH mn4bol
      ENDIF
      IF MSABOL='S'
         M4BOL=ROUND(MSTARTBOD*((100+(MMPROCMIN)/100))/100*MSTARTKOEF*100*MVRBOD*CAS4BOL/MSTARTCAS/100,2)
         if din4bol>m4bol
            REPLACE DIN4BOL WITH m4bol
         endif
         IF DIN4BOL=0
            REPLACE DIN4BOL WITH M4BOL
         ENDIF
      ENDIF
   ELSE
      REPLACE DIN4BOL WITH 0
   ENDIF
ENDIF


REPLACE DINLIC WITH ROUND(MBODLIC*MC,2)
REPLACE DINKOL WITH ROUND(MBODKOL*MC,2)
REPLACE DINSZ WITH ROUND(MBODSZ*MC,2)

DO SABERICASA
DO SABERIDINA

MBRUTO2=DINUK-DTOP-REGRES-dinbol-dinpraz-dingod-dinplac-din2bol-din3bol-din4bol-dinplac2-dinbol2
IF MSAKOR='D'
   REPLACE DINKOR WITH ROUND(MBRUTO2*ldrad.KOLKOR/100,2)
ELSE
   REPLACE DINKOR WITH 0
ENDIF
REPLACE BRUTOLD WITH MBRUTO2+DINKOR+DTOP+REGRES+FIKSNA+DOTACIJA

REPLACE BENPROC WITH LDRAD.BENPROC
REPLACE GRUPA WITH LDRAD.GRUPA
REPLACE GRUPA1 WITH LDRAD.GRUPA1
REPLACE MTR WITH LDRAD.MTR
REPLACE CENARADA WITH MC
REPLACE MESEC WITH MMESEC

DO SABERICASA
DO SABERIDINA
DO OBRACSTIMA
DO SABERIDODA
DO SABERINAKA
DO SABERIBRUTOA

*----------OBRACUN DOTACIJE-------------------


SET PROCEDURE TO LDOBRACUN
   do obracsoc
   do obracsocU

SET PROCEDURE TO 

IF MSAOBUSTAVE='D'
   DO OBRACOBA
ENDIF


DO SABERIOBA



ENDIF

DO OBRACKOMa

ENDPROC
                   



                   
                   
PROCEDURE SABERICASA
REPLACE CASUK WITH CASUC+CASPRAZ+CASBOL+casbol2+CAS2BOL+CAS3BOL+CAS4BOL+CASPLAC+CASPLAC2+CASGOD+CASDOR;
                   +CASVV+CASNEPLAC+CASNED+CSLPUT+CSUSP+CZASTOJ
                   ENDPROC



PROCEDURE SABERIDINA
REPLACE DINUK WITH DINUC;
                  +DINSL;
                  +DINLIC;
                  +DINKOL;
                  +DINSZ;
                  +DINPROD;
                  +DINRADNAP;
                  +DINNOC;
                  +DINPAUSAL;
                  +DINGOD;
                  +DINMIN;
                  +DINDOR;
                  +DINPRAZ;
                  +DINPLAC;
                  +DINPLAC2;
                  +DINBOL;
                  +DIN2BOL;
                  +DINBOL2;                  
                  +DINZASTOJ;
                  +DTOP;
                  +REGRES;
                  +DINNED;
                  +DINSUSP
                  
                  
                  
                  
                  
                  
                  


                   
ENDPROC


PROCEDURE OBRACSTIMA
   REPLACE STIM1 WITH ROUND(DINUK*STIM1PROC/100,MDEC)
   REPLACE STIM2 WITH ROUND(DINUK*STIM2PROC/100,MDEC)
   REPLACE STIM3 WITH ROUND(DINUK*STIM3PROC/100,MDEC)
ENDPROC

PROCEDURE SABERIDODA
*   REPLACE LDODACI WITH DINNOC+DINPROD+DINRADNAP+DINNED+dinmin+TOPLI+REGRES+TERENSKI
ENDPROC

   
PROCEDURE SABERINAKA
*   REPLACE NAKNADE WITH DINPRAZ+DINBOL+DINBOL2+DINPLAC+DINPLAC2+DINGOD
ENDPROC



PROCEDURE SABERIBRUTOA
   REPLACE BRUTO WITH DINUK+DOTACIJA+FIKSNA+DINKOR
   SELECT LDPARAM
   MISPLATA=ISPLATA
   SELECT LD
*   IF MISPLATA=1
*      REPLACE PORFONDZ WITH ROUND(BRUTO*LDRAD->FONDZ/100,MDEC)
*   ELSE
*      REPLACE PORFONDZ WITH 0
*   ENDIF
ENDPROC




PROCEDURE OBRACOBA

REPLACE KASA WITH LDRAD->KASA
REPLACE KASARATA WITH LDRAD->KASARATA
REPLACE SAMODOPR WITH ROUND(NETO*LDSAMOD->SAMOPROC/100,MDEC)
REPLACE SINDIKAT1 WITH ROUND(NETO*LDRAD->SIND1PROC/100,MDEC)
REPLACE SINDIKAT2 WITH ROUND(NETO*LDRAD->SIND2PROC/100,MDEC)
REPLACE SOLIDARN WITH ROUND(NETO*LDRAD->SOLPROC/100,MDEC)
REPLACE ALIMENT WITH ROUND(NETO*LDRAD->ALIMPROC/100,MDEC)


ENDPROC


PROCEDURE SABERIOBA

   REPLACE UKOBUST WITH KREDITI+AKONTAC+PREVOZ+ALIMENT+KASA+KASARATA+SAMODOPR+SINDIKAT1+SINDIKAT2+SOLIDARN+OBUST1+OBUST2+OBUST3+OBUSTTO
   REPLACE ZAISPLATU WITH NETO-UKOBUST

ENDPROC

PROCEDURE OBRACKOMa
SELECT LDPARAM
AKOMORAJ=KOMORAJ
AKOMORAS=KOMORAS
AKOMORAR=KOMORAR
SELECT LD
REPLACE KOMORAJD WITH ROUND(BRUTO*AKOMORAJ/100,2)
REPLACE KOMORASD WITH ROUND(BRUTO*AKOMORAS/100,2)
REPLACE KOMORARD WITH ROUND(BRUTO*AKOMORAR/100,2)
ENDPROC


