PUSH KEY CLEAR
DO  FORM LDOBRACUNa 
close all tables
USE FIRMA IN 0
USE LD00 ALIAS LD IN 0
USE LDRAD IN 0 ORDER BROJ
use ldparam IN 0
use MTR IN 0
USE LDGRUPA IN 0 ORDER 1
USE LDSAMOD IN 0 ORDER SAMSIF
SELECT LDRAD
SET RELATION TO SAMSIF INTO LDSAMOD ADDITIVE 
SELECT LD
GO TOP
SET RELATION TO BROJ INTO LDRAD ADDITIVE

LDa.GRD0.RECORDSOURCE='LD'

SET PROCEDURE TO ldpodaci
   DO PUNIPOD01
SET PROCEDURE TO

SELECT LD
POP KEY
LDA.RELEASE

DO LDREKAP2 WITH 0

KEYBOARD '{ENTER}'

