   parameters aa,MGRUPA,ADINSAT,AMINULI
   PUSH KEY CLEAR
   PUBLIC MDECIMALE,MNEOPOREZ,MDEC,MNEOPOREZP
   SELECT LDPARAM
   MPROCNOC=PROCNOC
   MPROCPROD=PROCPROD
   MPROCNED=PROCNED
   MPROCBOL=PROCBOL
   MPROCPRAZ=PROCPRAZ
   MPROCPLAC=PROCPLAC
   MPROCSUS=PROCSUS
   MPROCMIN=PROCMIN
   MCZAKON=CZAKON
   MMESEC=MESEC
   MISPLATA=ISPLATA
   MPROSBRUTO=PROSBRUTO
   MSRAZPOR=SRAZPOR
   MMINNAC=MINNAC
   MSTARTKOEF=EKOEFS
   MSDIN1=SDIN1
   MPROCPOR=PROCPOR
   MNEOPOREZP=NEOPOREZP
   MREDISPL=REDISPL
   MSDIN1=SDIN1
   MGODINA=GODINA
   IF MSTARTKOEF=0
      MSTARTKOEF=1
   ENDIF   
   MDECIMALE=DECIMALE
   MNEOPOREZ=NEOPOREZ
   IF MDECIMALE=' '
      MDEC=0
   ELSE
      MDEC=2
   ENDIF      
   SELECT LD
   REPLACE GODINA WITH MGODINA
   IF LDRAD.GRUPA=MGRUPA.OR.MGRUPA=0
      mevidbroj=ldrad.evidbroj
      replace evidbroj WITH mevidbroj
      IF ADINSAT=0
         mc=aa
         SB=ROUND(LDRAD.STARTBOD*MSTARTKOEF/MCZAKON,8)
      ELSE
         MC=ADINSAT
         SB=1
      ENDIF
      SBMIN=ROUND(LDRAD.STARTBOD,8)
      replace dinVR with ROUND(casuc*SB*MC,MDEC)
      replace dinuc with ROUND(casuc*SB*MC,MDEC)
      replace dinNOC with ROUND(casNOC*SB*MC*MPROCNOC/100,MDEC)
      replace dinPROD with ROUND(casPROD*SB*MC*MPROCPROD/100,MDEC)
      replace dinRADNAP with ROUND(casRADNAP*SB*MC*MPROCPRAZ/100,MDEC)
      replace dinPRAZ with ROUND(casPRAZ*SB*MC,MDEC)
      replace dinNED with ROUND(casNED*SB*MC*MPROCNED/100,MDEC)
      replace dinBOL with ROUND(casBOL*SB*MC*MPROCBOL/100,MDEC)
      replace dinBOL2 with ROUND(casBOL2*SB*MC,MDEC)
      replace dinPLAC with ROUND(casPLAC*SB*MC*MPROCPLAC/100,MDEC)
      replace dinPLAC2 with ROUND(casPLAC2*SB*MC,MDEC)
      replace dinGOD with ROUND(casGOD*SB*MC,MDEC)
      replace dinVV with ROUND(casVV*SB*MC,MDEC)
      replace dinDOR with ROUND(casDOR*SB*MC,MDEC)
      replace dinSL with ROUND(cSLPUT*SB*MC,MDEC)
      REPLACE DIN1 WITH ROUND(CAS1*SB*MC,MDEC)
      REPLACE DIN2 WITH ROUND(CAS2*SB*MC,MDEC)
      REPLACE DIN3 WITH ROUND(CAS3*SB*MC,MDEC)
      REPLACE DINSUS WITH ROUND(CASSUS*SB*MC*MPROCSUS/100,MDEC) 
      MMIN=DINUC+DINNOC+DINPROD+DINRADNAP+DINPRAZ+DINNED+DINBOL+DINBOL2+DINPLAC+DINPLAC2+DINGOD+DINVV+DINDOR+DIN1+DIN2+DIN3+DINSUS+DINSL
      IF MMINNAC=1
         replace dinMIN with ROUND(MMIN*MPROCMIN*LDRAD.STAZ/100,MDEC)
      ELSE
         replace dinMIN with ROUND(DINUC*MPROCMIN*LDRAD.STAZ/100,MDEC)
      ENDIF
   
      REPLACE CASUK WITH CASUC+CASPRAZ+CASBOL+CASBOL2+CASPLAC+CASPLAC2+CASGOD+CASDOR+CSLPUT;
                   +CAS1+CAS2+CAS3+CAS4+CAS5+CASRADNAP+CASNEPLAC
      REPLACE DINUK WITH DINUC+DINNOC+DINPROD+DINRADNAP+DINNED+DINPRAZ+DINBOL+DINBOL2+DINPLAC+DINPLAC2+DINGOD+DINDOR+DINSL;
                   +DIN1+DIN2+DIN3+DINMIN

      REPLACE BENPROC WITH LDRAD.BENPROC
      REPLACE GRUPA WITH LDRAD.GRUPA
      REPLACE MTR WITH LDRAD.MTR
      REPLACE CENARADA WITH MC
      REPLACE MESEC WITH MMESEC
      if Misplata=1
         doppio=ROUND(doppr1/100,6)
         dopzdr=ROUND(dopzr1/100,6)
         dopnez=ROUND(dopnr1/100,6)
      endif
      if Misplata=2
         doppio=ROUND(doppr2/100,6)
         dopzdr=ROUND(dopzr2/100,6)
         dopnez=ROUND(dopnr2/100,6)
      endif
      if Misplata=3
         doppio=ROUND(doppr3/100,6)
         dopzdr=ROUND(dopzr3/100,6)
         dopnez=ROUND(dopnr3/100,6)
      endif
      if Misplata=4
         doppio=ROUND(doppr4/100,6)
         dopzdr=ROUND(dopzr4/100,6)
         dopnez=ROUND(dopnr4/100,6)
      ENDIF
      mdopproc=ROUND((doppio+dopzdr+dopnez)*100,2)
      SELECT LD
      IF MCZAKON<>0
         M3MNEOPOREZP=ROUND(MNEOPOREZP*CASUK/MCZAKON,2)
         IF M3MNEOPOREZP>MNEOPOREZP
            M3MNEOPOREZP=MNEOPOREZP
         ENDIF
         IF MSRAZPOR<>'D'
            M3MNEOPOREZP=MNEOPOREZP
         ENDIF
      ELSE
         M3MNEOPOREZP=0
      ENDIF

      MNETO=DINUK+STIM1+STIM2+STIM3+TOPLI+REGRES+TERENSKI+FIKSNA+DOTACIJA+DINSUS

      REPLACE NETO WITH MNETO
      SELECT LDPARAM
      MISPLATA=ISPLATA
      SELECT LD
   ENDIF
   POP KEY
