PUSH KEY CLEAR
SELECT LDOPJ1N
SET RELATION TO 
SELECT LDOPJ1N0
DO FORM LDOPJ1N0
SELECT LDOPJ1N
MSIFOPIS=SIFOPIS
SELECT LDOPJ1N
IF SIFOPIS=SPACE(2)
   REPLACE SIFOPIS WITH MSIFOPIS
ENDIF   
SET RELATION TO BROJ INTO LDRAD0 ADDITIVE
SET RELATION TO SIFOPIS INTO LDOPJ1N0 ADDITIVE
LDOPJ1N.GRD0.SetFocus 
LDOPJ1N.Refresh 
POP KEY