PUSH KEY CLEAR
SELECT LDOPJ1N
SET RELATION TO 
SELECT LDRAD0
SET ORDER TO 2
DO FORM LDRAD0
SELECT LDRAD0
MBROJ=BROJ
SET ORDER TO 1
SELECT LDOPJ1N
IF BROJ=0
   REPLACE BROJ WITH MBROJ
ENDIF   
SET RELATION TO BROJ INTO LDRAD0 ADDITIVE
SET RELATION TO SIFOPIS INTO LDOPJ1N0 ADDITIVE
LDOPJ1N.GRD0.SetFocus 
LDOPJ1N.Refresh 
POP KEY