
PUSH KEY CLEAR
DO IDEL WITH (KKOCKAX)
DO IDEL WITH (KKOCKAX2)
DO IDEL WITH (KKOCKAX3)
SELECT LDOPJ1N
MREDBR=REDBR
MNAZMES=NAZMES
MDATISPL=DATISPL
MDATDOK=DATDOK
SET RELATION TO
COPY TO &KKOCKA2 FOR REDBR=MREDBR
SELECT LDOPJ1N0
COPY TO &KKOCKA
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
SELECT KOCKA
USE &KKOCKA2 IN 0 ALIAS KOCKA2 EXCLU
SELECT KOCKA2
INDEX ON SIFOPIS TAG SIFOPIS
SET ORDER TO 1
TOTAL ON SIFOPIS TO &KKOCKA3
DELETE ALL
PACK

APPEND FROM &KKOCKA3
GO TOP
SELECT KOCKA
SET RELATION TO SIFOPIS INTO KOCKA2 ADDITIVE
GO TOP
DO WHILE.NOT.EOF()
   REPLACE RADNIKA WITH KOCKA2.RADNIKA
   REPLACE SVENEOPOR WITH KOCKA2.SVENEOPOR
   REPLACE ISPLACENO WITH KOCKA2.ISPLACENO
   REPLACE ZAISPLATU WITH KOCKA2.ZAISPLATU
   REPLACE SVEGA WITH KOCKA2.SVEGA
   REPLACE NETOOPOR WITH KOCKA2.NETOOPOR
   REPLACE BRUTOOPOR WITH KOCKA2.BRUTOOPOR
   REPLACE POREZ WITH KOCKA2.POREZ
   REPLACE DATISPL WITH MDATISPL
   REPLACE DATDOK WITH MDATDOK
   REPLACE NAZMES WITH MNAZMES
   SKIP
ENDDO   
SET CENTURY ON
REPORT FORM LDOPJ01N PREVIEW 
SELECT KOCKA
USE
SELECT KOCKA2
USE
SELECT LDOPJ1N
SET RELATION TO BROJ INTO LDRAD0 ADDITIVE
SET RELATION TO SIFOPIS INTO LDOPJ1N0 ADDITIVE
LDOPJ1N.REFRESH
POP KEY