PROCEDURE LDOPJNUNESI
   PARAMETERS MREDNI,MKOD,MOPIS,MRLINI
   PUSH KEY CLEAR
   GOTO MREDNI
   REPLACE KOD WITH MKOD
   REPLACE OPIS WITH MOPIS
   REPLACE RLINI WITH MRLINI
   POP KEY
ENDPROC


PROCEDURE LDOPJNPOP
PUSH KEY CLEAR

 SELECT LDPARAM
  MNEOPOREZP=NEOPOREZP
  MREDISPL=REDISPL
  MMESEC=MESEC
  MISPLATA=ISPLATA
  USE LD00 ALIAS LD IN 0
  
  SELECT LD 
  MREC=RECCOUNT()
  GO TOP
  M61=0
  M62=0
  M63=0
  MZ61=0
  MZ62=0
  MZ63=0
  MPOROSLOB=0
  MPOROSLOB1=0
  MPOROSLOB2=0
  MPOROSLOB3=0
    
  DO WHILE.NOT.EOF()
     IF UMANJENJE='30'
        IF PORUMANJ<>0
           M61=M61+POREZU
           MZ61=MZ61+1
        ENDIF
     ENDIF   
     IF UMANJENJE='IN'
        IF PORUMANJ<>0
           M62=M62+POREZU
           MZ62=MZ62+1
        ENDIF
     ENDIF   
     IF UMANJENJE='45'.OR.UMANJENJE='50'
        IF PORUMANJ<>0
           M63=M63+POREZU
           MZ63=MZ63+1
        ENDIF
     ENDIF   
     MPOROSLOB=MPOROSLOB+POROSLOB
     MPOROSLOB1=MPOROSLOB1+POROSLOB1
     MPOROSLOB2=MPOROSLOB2+POROSLOB2
     MPOROSLOB3=MPOROSLOB3+POROSLOB3
     SKIP
  ENDDO   
  USE
  DO CASE MREDISPL
  CASE MREDISPL=1 
     MPOROSLOB=MPOROSLOB1
  CASE MREDISPL=2
     MPOROSLOB=MPOROSLOB2
  CASE MREDISPL=3
     MPOROSLOB=MPOROSLOB3
  ENDCASE   
        
  SELECT LDREK
  LOCATE FOR KOD='24. '
  mrazlika=razlika
  select LDOPJN
  LOCATE FOR KOD='1.   '
  REPLACE ZAPOSL WITH ROUND(MREC,0)
  REPLACE IZNOS WITH MRAZLIKA

  LOCATE FOR KOD='2.1. '
  REPLACE ZAPOSL WITH ROUND(MREC,0)
*  REPLACE IZNOS WITH ZAPOSL*MNEOPOREZP
  REPLACE IZNOS WITH MPOROSLOB
  LOCATE FOR KOD='6.1. '
  REPLACE ZAPOSL WITH MZ61
  REPLACE IZNOS WITH M61
 
  LOCATE FOR KOD='6.2. '
  REPLACE ZAPOSL WITH MZ62
  REPLACE IZNOS WITH M62
  LOCATE FOR KOD='6.3. '
  REPLACE ZAPOSL WITH MZ63
  REPLACE IZNOS WITH M63

  LOCATE FOR KOD='6.   '
  REPLACE ZAPOSL WITH MZ61+MZ62+MZ63
  REPLACE IZNOS WITH M61+M62+M63

  LOCATE FOR KOD='3.   '
  REPLACE ZAPOSL WITH ROUND(MREC,0)

  LOCATE FOR KOD='5.   '
  REPLACE ZAPOSL WITH ROUND(MREC,0)
  POP KEY
ENDPROC 



PROCEDURE LDOPJNPOP2
PUSH KEY CLEAR

 SELECT LDPARAM
  USE LD00 ALIAS LD IN 0
  SELECT LD 
  MREC=RECCOUNT()
  USE 
  SELECT LDREK
  LOCATE FOR KOD='24. '
  mrazlika=razlika
  select LDOPJN
  LOCATE FOR KOD='9.   '
  REPLACE ZAPOSL WITH MREC
  REPLACE IZNOS WITH MRAZLIKA
  SELECT LDREK
  LOCATE FOR KOD='22. '
  mrazlika=razlika
  select LDOPJN
  LOCATE FOR KOD='10.  '
  REPLACE ZAPOSL WITH MREC
  REPLACE IZNOS WITH MRAZLIKA
  POP KEY
ENDPROC 


PROCEDURE LDOPJNPOP3
PUSH KEY CLEAR
 SELECT LDPARAM
 MNEOPOREZP=NEOPOREZP
 MREDISPL=REDISPL
 MMESEC=MESEC
 MISPLATA=ISPLATA
  USE LD00 ALIAS LD IN 0
  SELECT LD 
  MREC=RECCOUNT()
  GO TOP
  MPOROSLOB=0
  MPOROSLOB1=0
  MPOROSLOB2=0
  MPOROSLOB3=0
  DO WHILE.NOT.EOF()
     MPOROSLOB=MPOROSLOB+POROSLOB
     MPOROSLOB1=MPOROSLOB1+POROSLOB1
     MPOROSLOB2=MPOROSLOB2+POROSLOB2
     MPOROSLOB3=MPOROSLOB3+POROSLOB3
     SKIP
  ENDDO   
  USE
    DO CASE MREDISPL
  CASE MREDISPL=1 
     MPOROSLOB=MPOROSLOB1
  CASE MREDISPL=2
     MPOROSLOB=MPOROSLOB2
  CASE MREDISPL=3
     MPOROSLOB=MPOROSLOB3
  ENDCASE   
  SELECT LDREK
  LOCATE FOR KOD='24. '
  mrazlika=razlika
  select LDOPJN
  LOCATE FOR KOD='11.  '
  REPLACE ZAPOSL WITH MREC
  REPLACE IZNOS WITH MRAZLIKA
  SELECT LDREK
  LOCATE FOR KOD='22. '
  mrazlika=razlika
  select LDOPJN
  LOCATE FOR KOD='14.  '
  REPLACE ZAPOSL WITH MREC
  REPLACE IZNOS WITH MRAZLIKA
  LOCATE FOR KOD='12.1.'
  REPLACE ZAPOSL WITH ROUND(MREC,0)
  REPLACE IZNOS WITH MPOROSLOB
  POP KEY
ENDPROC 


