PARAMETERS MSIFOPIS,MOPIS1,MOPIS2,MNEOPOREZ,MPRAVO
      APPEND BLANK
      REPLACE SIFOPIS WITH MSIFOPIS
      REPLACE OPIS1 WITH MOPIS1
      REPLACE OPIS2 WITH MOPIS2
      REPLACE PRAVO WITH MPRAVO
      REPLACE NEOPOREZ WITH MNEOPOREZ
