PUSH KEY CLEAR
SELECT LD
GO TOP
DO WHILE.NOT.EOF()
   MIME_PREZ=LDRAD.IME_PREZ
   MPOREZ=POREZ
   MZAISPLAT=NETO
   MDOPSOCF=DOPSOCF
   MDOPSOCR=DOPSOCR
   MBRUTO=NETO+POREZ+DOPSOCR
   MSVEGA=NETO+POREZ+DOPSOCF+DOPSOCR
   SELECT LDOZ10
   APPEND BLANK
   REPLACE BR WITH STR(RECNO(),3,0)
   REPLACE IME_PREZ WITH MIME_PREZ
   REPLACE BRUTO WITH MBRUTO
   REPLACE POREZ WITH MPOREZ
   REPLACE DOPR WITH MDOPSOCR
   REPLACE DOPF WITH MDOPSOCF
   REPLACE SVEGA WITH MSVEGA 
   REPLACE ZAISPLAT WITH MZAISPLAT
   SELECT LD
   SKIP
ENDDO   
SELECT LDOZ10
GO TOP
POP KEY