PUSH KEY CLEAR
SELECT LDPARAM
MMESEC=NAZMES
MDATISPL=DAT1
SELECT LD
GO TOP
DO WHILE.NOT.EOF()
   MIME_PREZ=LDRAD.IME_PREZ
   MMATICNIBR=LDRAD.MATICNIBR
   MBRUTO=BRUTO
   IF PROCBOL<>100
      MBRUTO2=ROUND(BRUTO/0.65,2)
   ELSE
      MBRUTO2=BRUTO
   ENDIF
   SELECT LDPOTVR
   APPEND BLANK
   REPLACE BR WITH STR(RECNO(),2,0)
   REPLACE IME_PREZ WITH MIME_PREZ
   REPLACE MATICNIBR WITH MMATICNIBR
   REPLACE BRUTO WITH MBRUTO
   REPLACE BRUTO2 WITH MBRUTO2
   REPLACE DATISPL WITH MDATISPL
   REPLACE MESEC WITH MMESEC
   SELECT LD
   SKIP
ENDDO   
SELECT LDPOTVR
GO TOP
POP KEY