PUSH KEY CLEAR
SELECT ldprev
GO top
mmesec=mesec
USE
USE LDPREV00 EXCLU ALIAS LDPREV IN 0
SELECT LDPREV
PUBLIC DA_ne
da_ne='N'
DO porukadane WITH ' BRISANJE MESECA '
IF da_ne='D'
   ZAP
   use
*   USE LDPREV EXCLU ALIAS LDPREV IN 0
*   SELECT LDPREV
*   DELETE ALL FOR MESEC=MMESEC
*   PACK
*   USE
ENDIF
CLOSE ALL TABLES
POP KEY
LDPREV.RELEASE
KEYBOARD '{ENTER}'
