PUSH KEY CLEAR
SELECT LD
GO TOP
DO WHILE.NOT.EOF()
   IF LDRAD.PRIPRAV<>' '
      MBROJ=BROJ
      MIME_PREZ=LDRAD.IME_PREZ
      MPOREZ=POREZ
      MNETO=NETO
      MDOPSOCR=DOPSOCR
      MUKUPNO=NETO+DOPSOCF+DOPSOCR
      MCASUK=CASUK
      MCASBOL=CASBOL
      SELECT LDPRIP
      APPEND BLANK
      REPLACE BROJ WITH MBROJ
      REPLACE IME_PREZ WITH MIME_PREZ
      REPLACE POREZ WITH MPOREZ
      REPLACE NETO WITH MNETO
      REPLACE DOPSOCR WITH MDOPSOCR
      REPLACE UKUPNO WITH MUKUPNO
      REPLACE CASRAD WITH MCASUK-MCASBOL
      REPLACE CASBOL WITH MCASBOL
      REPLACE NIVO WITH 'PRIPRAVNICI SA VIŠIM ILI VISOKIM TROGODIŠNJIM OBRAZOVANJEM '
   ENDIF
   SELECT LD
   SKIP
ENDDO   
SELECT LDPRIP
GO TOP
POP KEY
ENDPROC