ON ERROR
SELECT LD
FOR I=1 TO 99
   MLD='LD'+alltrim(str(I,2,0))+'.DBF'
   MLDPOD='LDPOD'+alltrim(str(I,2,0))+'.DBF'
   MLDP='LDP'+alltrim(str(I,2,0))+'.DBF'
   MLDPODP='LDPODP'+alltrim(str(I,2,0))+'.DBF'
   MLDB='LDB'+alltrim(str(I,2,0))+'.DBF'
   MLDPODB='LDPODB'+alltrim(str(I,2,0))+'.DBF'
   MLDI='LDI'+alltrim(str(I,2,0))+'.DBF'
   MLDPODI='LDPODI'+alltrim(str(I,2,0))+'.DBF'
   MLDR='LDR'+alltrim(str(I,2,0))+'.DBF'
   MLDPODR='LDPODR'+alltrim(str(I,2,0))+'.DBF'
   MLmes ='Lmes'+alltrim(str(i,2,0))+'.DBF'
   MLmesp='Lmesp'+alltrim(str(i,2,0))+'.DBF'
   MLmesb='Lmesb'+alltrim(str(i,2,0))+'.DBF'
   MLmesi='Lmesi'+alltrim(str(i,2,0))+'.DBF'
   MLmesR='LmesR'+alltrim(str(i,2,0))+'.DBF'
   MLDDD='LDDD'+alltrim(str(I,2,0))+'.DBF'
   MLDPREV='LDPREV'+alltrim(str(I,2,0))+'.DBF'
   DO IDEL WITH (KKOCKAX)
   IF FILE(MLD)
      SELECT LD
      COPY STRUCTURE TO &KKOCKA
      USE &KKOCKA IN 0 ALIAS KOCKA EXCLUSIVE
      SELECT KOCKA
      APPEND FROM &MLD
      REPLACE ALL ISPLATA WITH 1
      REPLACE ALL VRSTA WITH 'A'
      USE
      SELECT LD
      APPEND FROM &KKOCKA
   ENDIF
   
   IF FILE(MLDP)
      COPY STRUCTURE TO &KKOCKA
      USE &KKOCKA IN 0 ALIAS KOCKA EXCLUSIVE
      SELECT KOCKA
      APPEND FROM &MLDP
      REPLACE ALL ISPLATA WITH 2
      REPLACE ALL VRSTA WITH 'P'
      USE
      SELECT LD
      APPEND FROM &KKOCKA
   ENDIF
   
   IF FILE(MLDB)
      COPY STRUCTURE TO &KKOCKA
      USE &KKOCKA IN 0 ALIAS KOCKA EXCLUSIVE
      SELECT KOCKA
      APPEND FROM &MLDB
      REPLACE ALL ISPLATA WITH 3
      REPLACE ALL VRSTA WITH 'B'
      USE
      SELECT LD
      APPEND FROM &KKOCKA
   ENDIF
   
   IF FILE(MLDI)
      COPY STRUCTURE TO &KKOCKA
      USE &KKOCKA IN 0 ALIAS KOCKA EXCLUSIVE
      SELECT KOCKA
      APPEND FROM &MLDI
      REPLACE ALL ISPLATA WITH 3
      REPLACE ALL VRSTA WITH 'B'
      USE
      SELECT LD
      APPEND FROM &KKOCKA
   ENDIF
   IF FILE(MLDR)
      COPY STRUCTURE TO &KKOCKA
      USE &KKOCKA IN 0 ALIAS KOCKA EXCLUSIVE
      SELECT KOCKA
      APPEND FROM &MLDR
      REPLACE ALL ISPLATA WITH 3
      REPLACE ALL VRSTA WITH 'B'
      USE
      SELECT LD
      APPEND FROM &KKOCKA
   ENDIF


*-----------PODACI----------------
   USE LDPOD IN 0 
   SELECT LDPOD   
   IF FILE(MLDPOD)
      COPY STRUCTURE TO &KKOCKA
      USE &KKOCKA IN 0 ALIAS KOCKA EXCLUSIVE
      SELECT KOCKA
      APPEND FROM &MLDPOD
      REPLACE ALL MESEC WITH I
      REPLACE ALL ISPLATA WITH 1
      REPLACE ALL VRSTA WITH 'A'
      USE
      SELECT LDPOD
      APPEND FROM &KKOCKA
   ENDIF
   
   IF FILE(MLDPODP)
      COPY STRUCTURE TO &KKOCKA
      USE &KKOCKA IN 0 ALIAS KOCKA EXCLUSIVE
      SELECT KOCKA
      APPEND FROM &MLDPODP
      REPLACE ALL MESEC WITH I
      REPLACE ALL ISPLATA WITH 2
      REPLACE ALL VRSTA WITH 'P'
      USE
      SELECT LDPOD
      APPEND FROM &KKOCKA
   ENDIF
   
   IF FILE(MLDPODB)
      COPY STRUCTURE TO &KKOCKA
      USE &KKOCKA IN 0 ALIAS KOCKA EXCLUSIVE
      SELECT KOCKA
      APPEND FROM &MLDPODB
      REPLACE ALL MESEC WITH I
      REPLACE ALL ISPLATA WITH 3
      REPLACE ALL VRSTA WITH 'B'
      USE
      SELECT LDPOD
      APPEND FROM &KKOCKA
   ENDIF
   
   IF FILE(MLDPODI)
      COPY STRUCTURE TO &KKOCKA
      USE &KKOCKA IN 0 ALIAS KOCKA EXCLUSIVE
      SELECT KOCKA
      APPEND FROM &MLDPODI
      REPLACE ALL MESEC WITH I
      REPLACE ALL ISPLATA WITH 3
      REPLACE ALL VRSTA WITH 'B'
      USE
      SELECT LDPOD
      APPEND FROM &KKOCKA
   ENDIF
   IF FILE(MLDPODR)
      COPY STRUCTURE TO &KKOCKA
      USE &KKOCKA IN 0 ALIAS KOCKA EXCLUSIVE
      SELECT KOCKA
      APPEND FROM &MLDPODR
      REPLACE ALL MESEC WITH I
      REPLACE ALL ISPLATA WITH 3
      REPLACE ALL VRSTA WITH 'B'
      USE
      SELECT LDPOD
      APPEND FROM &KKOCKA
   ENDIF
   SELECT LDPOD
   USE   


*----------LDDD-PODACI----------------
   USE LDDD IN 0 
   SELECT LDDD
   
   IF FILE(MLDDD)
      COPY STRUCTURE TO &KKOCKA
      USE &KKOCKA IN 0 ALIAS KOCKA EXCLUSIVE
      SELECT KOCKA
      APPEND FROM &MLDDD
      REPLACE ALL MESEC WITH I
      REPLACE ALL ISPLATA WITH 1
      REPLACE ALL VRSTA WITH 'A'
      USE
      SELECT LDDD
      APPEND FROM &KKOCKA
   ENDIF
   SELECT LDDD
   USE   


*-----------MESTA----------------
   USE LMES IN 0 
   
   IF FILE(MLMES)
      COPY STRUCTURE TO &KKOCKA
      USE &KKOCKA IN 0 ALIAS KOCKA EXCLUSIVE
      SELECT KOCKA
      APPEND FROM &MLMES
      REPLACE ALL MESEC WITH I
      REPLACE ALL ISPLATA WITH 1
      REPLACE ALL VRSTA WITH 'A'
      USE
      SELECT LMES
      APPEND FROM &KKOCKA
   ENDIF
   
   IF FILE(MLMESP)
      COPY STRUCTURE TO &KKOCKA
      USE &KKOCKA IN 0 ALIAS KOCKA EXCLUSIVE
      SELECT KOCKA
      APPEND FROM &MLMESP
      REPLACE ALL MESEC WITH I
      REPLACE ALL ISPLATA WITH 2
      REPLACE ALL VRSTA WITH 'P'
      USE
      SELECT LMES
      APPEND FROM &KKOCKA
   ENDIF
   
   IF FILE(MLMESB)
      COPY STRUCTURE TO &KKOCKA
      USE &KKOCKA IN 0 ALIAS KOCKA EXCLUSIVE
      SELECT KOCKA
      APPEND FROM &MLMESB
      REPLACE ALL MESEC WITH I
      REPLACE ALL ISPLATA WITH 3
      REPLACE ALL VRSTA WITH 'B'
      USE
      SELECT LMES
      APPEND FROM &KKOCKA
   ENDIF
   
   IF FILE(MLMESI)
      COPY STRUCTURE TO &KKOCKA
      USE &KKOCKA IN 0 ALIAS KOCKA EXCLUSIVE
      SELECT KOCKA
      APPEND FROM &MLMESI
      REPLACE ALL MESEC WITH I
      REPLACE ALL ISPLATA WITH 3
      REPLACE ALL VRSTA WITH 'B'
      USE
      SELECT LMES
      APPEND FROM &KKOCKA
   ENDIF
   IF FILE(MLMESR)
      COPY STRUCTURE TO &KKOCKA
      USE &KKOCKA IN 0 ALIAS KOCKA EXCLUSIVE
      SELECT KOCKA
      APPEND FROM &MLMESR
      REPLACE ALL MESEC WITH I
      REPLACE ALL ISPLATA WITH 3
      REPLACE ALL VRSTA WITH 'B'
      USE
      SELECT LMES
      APPEND FROM &KKOCKA
   ENDIF
   SELECT LMES
   USE   
*----------LDPREV PODACI----------------
   USE LDPREV IN 0 
   SELECT LDPREV
   IF FILE(MLDPREV)
      COPY STRUCTURE TO &KKOCKA
      USE &KKOCKA IN 0 ALIAS KOCKA EXCLUSIVE
      SELECT KOCKA
      APPEND FROM &MLDPREV
      REPLACE ALL MESEC WITH I
      REPLACE ALL ISPLATA WITH 1
      REPLACE ALL VRSTA WITH 'A'
      USE
      SELECT LDPREV
      APPEND FROM &KKOCKA
   ENDIF
   SELECT LDPREV
   USE   
   SELECT LD
NEXT
SELECT LD

