PUSH KEY CLEAR
CLOSE ALL TABLES
USE LDPREV EXCLU ALIAS LDPREV IN 0
SELECT LDPREV

PUBLIC DA_ne
da_ne='N'
DO porukadane WITH ' BRISANJE ARHIVE '
IF da_ne='D'
   ZAP
   use
ENDIF
CLOSE ALL TABLES
POP KEY
LDPREVARHIVA.RELEASE
KEYBOARD '{ENTER}'
