
PUSH KEY CLEAR

SELECT LDPARAM
MREDISPL=REDISPL
MMESEC=MESEC
MISPLATA=ISPLATA

DO CASE MISPLATA
CASE MISPLATA=1
   LVRSTA=''
CASE MISPLATA=2
   LVRSTA='P'
CASE MISPLATA=3
   LVRSTA='B'
CASE MISPLATA=4
   LVRSTA='I'
CASE MISPLATA=5
   LVRSTA='R'
OTHERWISE
   LVRSTA='U'
ENDCASE

USE LMES00 IN 0 ORDER 1 ALIAS LMES EXCLUSIVE
SELECT LMES

MMESTA=MDATA00+'\'+'MESTA.DBF'
IF MREDISPL=1
SELECT LMES
   DELETE ALL
PACK

   APPEND FROM &MMESTA
   GO TOP

   DO WHILE.NOT.EOF()
      REPLACE POR WITH 0
      REPLACE PORF WITH 0
      REPLACE ZDR WITH 0
      REPLACE ZDRF WITH 0 
      REPLACE PIO WITH 0
      REPLACE PIOF WITH 0   
      REPLACE NEZ WITH 0
      REPLACE NEZF WITH 0
      REPLACE PIOVL WITH 0
      REPLACE BEN WITH 0
      SKIP
   ENDDO   
ENDIF


SELECT FIRMA
MFPOR=FPOR
SELECT LMES
GO TOP
DO WHILE.NOT.EOF()
   IF LVRSTA<>'B'
      M1=VAL(ZIRO2+MFPOR)
      M2=(M1*100/97)-int(M1*100/97)
      M3=ROUND(97*M2,0)
      M4=98-M3
      MM4=REPLICATE('0',2-LEN(ALLTRIM(STR(M4,2,0))))+ALLTRIM(STR(M4,2,0))
      REPLACE PORBROJ WITH MM4+'-'+SUBSTR(ZIRO2,1,3)+'-'+ALLTRIM(MFPOR)
      REPLACE PORBROJP WITH MM4+'-'+SUBSTR(ZIRO2,1,3)+'-'+ALLTRIM(MFPOR)
   ELSE
      M1=VAL('601'+MFPOR)
      M2=(M1*100/97)-int(M1*100/97)
      M3=ROUND(97*M2,0)
      M4=98-M3
      MM4=REPLICATE('0',2-LEN(ALLTRIM(STR(M4,2,0))))+ALLTRIM(STR(M4,2,0))
      REPLACE PORBROJ WITH MM4+'-'+'601'+'-'+ALLTRIM(MFPOR)
      M1=VAL(ZIRO2+MFPOR)
      M2=(M1*100/97)-int(M1*100/97)
      M3=ROUND(97*M2,0)
      M4=98-M3
      MM4=REPLICATE('0',2-LEN(ALLTRIM(STR(M4,2,0))))+ALLTRIM(STR(M4,2,0))
      REPLACE PORBROJP WITH MM4+'-'+SUBSTR(ZIRO2,1,3)+'-'+ALLTRIM(MFPOR)
   ENDIF   
   REPLACE MESEC WITH MMESEC
   REPLACE ISPLATA WITH MISPLATA   
   SKIP
ENDDO   

GO TOP
*---------------UNOS PODATAKA U TABELU
DO WHILE.NOT.EOF()
   MMP=MP
   SELECT LD
   GO TOP
   APOR=0
   APORU=0
   AZDR=0
   AZDRF=0
   APIO=0
   APIOF=0
   APIOU=0
   APIOFU=0
   ANEZ=0
   ANEZF=0
   APIOVL=0
   ABEN=0
   DO WHILE.NOT.EOF()
      IF LDRAD.MP=MMP
         IF UMANJENJE='Z1'
            APOR=APOR+POREZS-POREZU
         ELSE
            APOR=APOR+POREZ
         ENDIF
         IF UMANJENJE<>'Z1'
            APORU=0
         ENDIF   
         IF LDRAD.GRUPA<>9999
                    
            APIO=APIO+DOPPR
            APIOF=APIOF+DOPPF
      *-------DODATO 21.09.2011---
            IF UMANJENJE='Z1'
               APIOU=APIOU+DOPPRU
               APIOFU=APIOFU+DOPPFU
            ENDIF
         
         ELSE
            APIOVL=APIOVL+DOPPR+DOPPF            
         ENDIF
         ANEZ=ANEZ+DOPNR
         ANEZF=ANEZF+DOPNF
         ABEN=ABEN+BENDIN
      ENDIF
      SKIP
   ENDDO
   SELECT LMES
   MRREC=RECNO()
   IF mredispl=1
      REPLACE POR1 WITH APOR
      REPLACE POR1U WITH APORU
      REPLACE PIO1 WITH APIO 
      REPLACE PIOF1 WITH APIOF
      REPLACE PIO1U WITH APIOU
      REPLACE PIOF1U WITH APIOFU      
      REPLACE PIOVL1 WITH APIOVL    
      REPLACE NEZ1 WITH ANEZ
      REPLACE NEZF1 WITH ANEZF
      REPLACE BEN1 WITH ABEN
      
      REPLACE POR WITH APOR
      REPLACE PORU WITH APORU
      REPLACE PIO WITH APIO 
      REPLACE PIOF WITH APIOF
      REPLACE PIOU WITH APIOU
      REPLACE PIOFU WITH APIOFU      
      REPLACE PIOVL WITH APIOVL    
      REPLACE NEZ WITH ANEZ
      REPLACE NEZF WITH ANEZF
      REPLACE BEN WITH ABEN
   ENDIF   
 
   IF MREDISPL=2
      REPLACE POR2 WITH APOR
      REPLACE POR2U WITH APORU
      REPLACE PIO2 WITH APIO 
      REPLACE PIOF2 WITH APIOF
      REPLACE PIO2U WITH APIOU
      REPLACE PIOF2U WITH APIOFU      
      
      REPLACE PIOVL2 WITH APIOVL    
      REPLACE NEZ2 WITH ANEZ
      REPLACE NEZF2 WITH ANEZF
      REPLACE BEN2 WITH ABEN
      
      REPLACE POR WITH APOR-POR1
      REPLACE PORU WITH APORU-POR1U
      REPLACE PIO WITH APIO-PIO1
      REPLACE PIOF WITH APIOF-PIOF1
      REPLACE PIOU WITH APIOU-PIO1U
      REPLACE PIOFU WITH APIOFU-PIOF1U  
      REPLACE PIOVL WITH APIOVL-PIOVL1
      REPLACE NEZ WITH ANEZ-NEZ1
      REPLACE NEZF WITH ANEZF-NEZF1
      REPLACE BEN WITH ABEN-BEN1
   ENDIF   
 
   IF MREDISPL=3
      REPLACE POR3 WITH APOR
      REPLACE POR3U WITH APORU
      REPLACE PIO3 WITH APIO 
      REPLACE PIOF3 WITH APIOF
      REPLACE PIO3U WITH APIOU 
      REPLACE PIOF3U WITH APIOFU
      REPLACE PIOVL3 WITH APIOVL    
      REPLACE NEZ3 WITH ANEZ
      REPLACE NEZF3 WITH ANEZF
      REPLACE BEN3 WITH ABEN
      
      REPLACE POR WITH APOR-POR2
      REPLACE PORU WITH APORU-POR2U
      REPLACE PIO WITH APIO-PIO2
      REPLACE PIOF WITH APIOF-PIOF2
      REPLACE PIOU WITH APIOU-PIO2U
      REPLACE PIOFU WITH APIOFU-PIOF2U
      REPLACE PIOVL WITH APIOVL-PIOVL2
      REPLACE NEZ WITH ANEZ-NEZ2
      REPLACE NEZF WITH ANEZF-NEZF2
      REPLACE BEN WITH ABEN-BEN2
   ENDIF   
 
   IF MREDISPL=4
      REPLACE POR4 WITH APOR
      REPLACE POR4U WITH APORU
      REPLACE PIO4 WITH APIO 
      REPLACE PIOF4 WITH APIOF
      REPLACE PIO4U WITH APIOU 
      REPLACE PIOF4U WITH APIOFU
      REPLACE PIOVL4 WITH APIOVL    
      REPLACE NEZ4 WITH ANEZ
      REPLACE NEZF4 WITH ANEZF
      REPLACE BEN4 WITH ABEN
      
      REPLACE POR WITH APOR-POR3
      REPLACE PORU WITH APORU-POR3U
      REPLACE PIO WITH APIO-PIO3
      REPLACE PIOF WITH APIOF-PIOF3
      REPLACE PIOU WITH APIOU-PIO3U
      REPLACE PIOFU WITH APIOFU-PIOF3U
      REPLACE PIOVL WITH APIOVL-PIOVL3
      REPLACE NEZ WITH ANEZ-NEZ3
      REPLACE NEZF WITH ANEZF-NEZF3
      REPLACE BEN WITH ABEN-BEN3
   ENDIF   

  SKIP
ENDDO   

SELECT LMES 
*--------------UNOS ZDRAVSTVO PO POSLOVNIM JEDINICAMA--------
GO TOP
DO WHILE.NOT.EOF()
   MMP=MP
   SELECT LD
   GO TOP
   AZDR=0
   AZDRF=0
   AZDRV=0
   AZDRFV=0
   DO WHILE.NOT.EOF()
      IF LDRAD.PJ=MMP
         IF LDRAD.GRUPA<>9999
            AZDR=AZDR+DOPZR
            AZDRF=AZDRF+DOPZF 
         ELSE
            AZDRV=AZDRV+DOPZR
            AZDRFV=AZDRFV+DOPZF 
         ENDIF            
      ENDIF
      SKIP
   ENDDO

   SELECT LMES
   MRREC=RECNO()
   IF MREDISPL=1
      REPLACE ZDR1 WITH AZDR 
      REPLACE ZDRF1 WITH AZDRF
      REPLACE ZDR WITH AZDR 
      REPLACE ZDRF WITH AZDRF
      
      REPLACE ZDR1V WITH AZDRV 
      REPLACE ZDRF1V WITH AZDRFV
      REPLACE ZDRV WITH AZDRV 
      REPLACE ZDRFV WITH AZDRFV

   ENDIF   
   IF MREDISPL=2
      REPLACE ZDR2 WITH AZDR
      REPLACE ZDRF2 WITH AZDRF
      REPLACE ZDR WITH AZDR-ZDR1
      REPLACE ZDRF WITH AZDRF-ZDRF1

      REPLACE ZDR2V WITH AZDRV
      REPLACE ZDRF2V WITH AZDRFV
      REPLACE ZDRV WITH AZDRV-ZDR1V
      REPLACE ZDRFV WITH AZDRFV-ZDRF1V

   ENDIF   
   IF MREDISPL=3
      REPLACE ZDR3 WITH AZDR
      REPLACE ZDRF3 WITH AZDRF

      REPLACE ZDR WITH AZDR-ZDR2
      REPLACE ZDRF WITH AZDRF-ZDRF2

      REPLACE ZDR3V WITH AZDRV
      REPLACE ZDRF3V WITH AZDRFV

      REPLACE ZDRV WITH AZDRV-ZDR2V
      REPLACE ZDRFV WITH AZDRFV-ZDRF2V

   ENDIF   
   IF MREDISPL=4
      REPLACE ZDR4 WITH AZDR
      REPLACE ZDRF4 WITH AZDRF
      REPLACE ZDR WITH AZDR-ZDR3
      REPLACE ZDRF WITH AZDRF-ZDRF3

      REPLACE ZDR4V WITH AZDRV
      REPLACE ZDRF4V WITH AZDRFV
      REPLACE ZDRV WITH AZDRV-ZDR3V
      REPLACE ZDRFV WITH AZDRFV-ZDRF3V

   ENDIF   

  SELECT LMES  
  SKIP
ENDDO   

SELECT LMES

USE
SELECT LD
GO TOP

SELECT LDPARAM
MREDISPL=REDISPL
MSAM='SAM'+ALLTRIM(STR(MREDISPL,1,0))
SELECT LDSAMOD
REPLACE ALL &MSAM WITH 0
SELECT LD
GO TOP
DO WHILE.NOT.EOF()
  MSAMODOP=LD.SAMODOPR
  MSAMSIF=LDRAD.SAMSIF
  SELECT LDSAMOD
  SET ORDER TO 1
  SEEK MSAMSIF
  IF FOUND()
      REPLACE &MSAM WITH &MSAM+MSAMODOP
  ENDIF
  SELECT LD
  SKIP
ENDDO 
SELECT LDSAMOD  
GO TOP
DO WHILE.NOT.EOF()
   IF MREDISPL=1
      REPLACE SAMODOP WITH SAM1
   ENDIF
   IF MREDISPL=2
      REPLACE SAMODOP WITH SAM2-SAM1
   ENDIF
   IF MREDISPL=3
      REPLACE SAMODOP WITH SAM3-SAM2
   ENDIF
   IF MREDISPL=4
      REPLACE SAMODOP WITH SAM4-SAM3
   ENDIF
   SKIP
ENDDO
SELECT LD
GO TOP
POP KEY
