PUSH KEY CLEAR
   DO PUNIPOD WITH   1,'1.     ',' OBRACUNATE ZARADE '
   DO PUNIPOD WITH   2,'2.     ',' Broj zaposlenih(2.1 - 2.3)'
   DO PUNIPOD WITH   3,'2.1.   ',' nepuno vreme              '
   DO PUNIPOD WITH   4,'2.2.   ',' zaposleni za oslobadj     '
   DO PUNIPOD WITH   5,'2.2.1. ',' clan 45 stav 1            '
   DO PUNIPOD WITH   6,'2.2.2. ',' clan 45 stav 2            '
   DO PUNIPOD WITH   7,'2.2.3. ',' clan 45a stav 1           '
   DO PUNIPOD WITH   8,'2.2.4. ',' clan 45a stav 2           '
   DO PUNIPOD WITH   9,'2.2.5. ',' clan 45b stav 1           '
   DO PUNIPOD WITH  10,'3.     ',' OSNOVICA ZA OBRACUN DOPRI-'
   DO PUNIPOD WITH  11,'4.     ',' ukupni doprinosi          '
   DO PUNIPOD WITH  12,'4.1.   ',' Iz zarada zaposlenih      '
   DO PUNIPOD WITH  13,'4.1.1. ',' Za PIO                    '
   DO PUNIPOD WITH  14,'4.1.2. ',' Za zdravstvo              '
   DO PUNIPOD WITH  15,'4.1.3. ',' Za zaposljavanje          '
   DO PUNIPOD WITH  16,'4.2.   ',' Na teret poslodavca       '
   DO PUNIPOD WITH  17,'4.2.1. ',' Za PIO                    '
   DO PUNIPOD WITH  18,'4.2.2. ',' Za zdravstvo              '
   DO PUNIPOD WITH  19,'4.2.3. ',' Za zaposljavanje          '
   DO PUNIPOD WITH  20,'5.     ',' placa doprinos za staz os.'
   DO PUNIPOD WITH  21,'6.     ',' dopr.za pio za benef.staz '
   DO PUNIPOD WITH  22,'7.     ',' ISPLACENI DEO ZARADE      '
   DO PUNIPOD WITH  23,'8.     ',' ISPLACENI DEO ZARADE      '
   DO PUNIPOD WITH  24,'8.1.   ','                           '
   DO PUNIPOD WITH  25,'8.1.1. ','                           '
   DO PUNIPOD WITH  26,'8.1.2. ','                           '
   DO PUNIPOD WITH  27,'8.1.3. ','                           '
   DO PUNIPOD WITH  28,'8.2.   ','                           '
   DO PUNIPOD WITH  29,'8.2.1. ','                           '
   DO PUNIPOD WITH  30,'8.2.2. ','                           '
   DO PUNIPOD WITH  31,'8.2.3. ','                           '
   DO PUNIPOD WITH  32,'9.     ','                           '
   DO PUNIPOD WITH  33,'10.    ',' Zarada za isplatu (1 - 8) '
   DO PUNIPOD WITH  34,'11.    ',' Doprinos za uplatu(5-9> 0)'
   DO PUNIPOD WITH  35,'11.1.  ',' Iz zarada zaposlenih      '
   DO PUNIPOD WITH  36,'11.1.1.',' PIO (5.1.1.-9.1.1)        '
   DO PUNIPOD WITH  37,'11.1.2.',' zdravstvo (5.1.2.-9.1.2)  '
   DO PUNIPOD WITH  38,'11.1.3.',' zaposljavanje(5.1.3-9.1.3)'
   DO PUNIPOD WITH  39,'11.2.  ',' Na teret poslodavca       '
   DO PUNIPOD WITH  40,'11.2.1.',' PIO (5.2.1.-9.2.1)        '
   DO PUNIPOD WITH  41,'11.2.2.',' zdravstvo (5.2.2.-9.2.2)  '
   DO PUNIPOD WITH  42,'11.2.3.',' zaposljavanje(5.2.3-9.2.3)'
   DO PUNIPOD WITH  43,'12.    ',' dopr.za upl.pio za b.staz '
   DO PUNIPOD WITH  44,'13.    ',' Vise placeni doprinosi    '
   DO PUNIPOD WITH  45,'13.1.  ',' Iz sredst poslodavca      '
   DO PUNIPOD WITH  46,'13.1.1.',' PIO (9.1.1.-5.1.1)        '
   DO PUNIPOD WITH  47,'13.1.2.',' zdravstvo (9.1.2.-5.1.2)  '
   DO PUNIPOD WITH  48,'13.1.3.',' zaposljavanje(9.1.3-5.1.3)'
   DO PUNIPOD WITH  49,'13.2.  ',' Iz zadara zaposlenih      '
   DO PUNIPOD WITH  50,'13.2.1.',' PIO (9.1.1.-5.1.1)        '
   DO PUNIPOD WITH  51,'13.2.2.',' zdravstvo (9.1.2.-5.1.2)  '
   DO PUNIPOD WITH  52,'13.2.3.',' zaposljavanje(9.1.3-5.1.3)'
   DO PUNIPOD WITH  53,'14.    ','                           '
   DO PUNIPOD WITH  54,'14.1.  ',' poslodavac                '
   DO PUNIPOD WITH  55,'14.1.1.',' pio                       '
   DO PUNIPOD WITH  56,'14.1.2.',' zdravstvo (9.2.2.-5.2.2)  '
   DO PUNIPOD WITH  57,'14.1.3.',' zaposljavanje(9.2.3-5.2.3)'
   DO PUNIPOD WITH  58,'14.2.  ',' Iz zarada zaposlenih      '
   DO PUNIPOD WITH  59,'14.2.1.',' PIO (12.1.1.-14.1.1)      '
   DO PUNIPOD WITH  60,'14.2.2.',' zdravstvo (12.1.2-14.1.2) '
   DO PUNIPOD WITH  61,'14.2.3.',' zaposljav.(12.1.3-14.1.3) '
   DO PUNIPOD WITH  62,'20.    ',' BROJ RADNIKA              '
   DO PUNIPOD WITH  63,'21.    ',' NETO ZA ISPLATU           '
   DO PUNIPOD WITH  64,'22.    ',' POREZ NA DOHODAK          '
   DO PUNIPOD WITH  65,'23.    ',' DOPRINOSI RADNIKA UKUPNO  '
   DO PUNIPOD WITH  66,'24.    ',' BRUTO PRIMANJA            '
   DO PUNIPOD WITH  67,'25.    ',' porez na fond zarada      '
   DO PUNIPOD WITH  68,'26.    ',' DOPRINOSI RADNIKA UKUP.   '
   DO PUNIPOD WITH  69,'27.    ',' doprinosi radnika p i o   '
   DO PUNIPOD WITH  70,'28.    ',' doprinosi radnika zdravst.'
   DO PUNIPOD WITH  71,'29.    ',' doprinosi radnika nezap.  '
   DO PUNIPOD WITH  72,'30.    ',' DOPRINOSI FIRMA   UKUPNO  '
   DO PUNIPOD WITH  73,'31.    ',' doprinosi firma  p i o    '
   DO PUNIPOD WITH  74,'32.    ',' DOPRINOSI FIRMA zdravstvo '
   DO PUNIPOD WITH  75,'33.    ',' DOPRINOSI FIRMA nezaposl. '
   DO PUNIPOD WITH  76,'34.    ',' doprinos komori Jugoslav  '
   DO PUNIPOD WITH  77,'35.    ',' doprinos komori Republike '
   DO PUNIPOD WITH  78,'36.    ',' doprinos komori regiona   '
   DO PUNIPOD WITH  79,'37.    ',' CASOVI UKUPNO             '
   DO PUNIPOD WITH  80,'38.    ',' KREDITI                   '   
   DO PUNIPOD WITH  81,'39.    ',' AKONTACIJA                '
   DO PUNIPOD WITH  82,'40.    ',' SOLIDARNOST               '
   DO PUNIPOD WITH  83,'41.    ',' SAMODOPRINOS              '
   DO PUNIPOD WITH  84,'42.    ',' SINDIKAT 1                 '
   DO PUNIPOD WITH  85,'43.    ',' SINDIKAT 2                 '   
   DO PUNIPOD WITH  86,'44.    ',' ALIMENTACIJA              '
   DO PUNIPOD WITH  87,'45.    ',' KASA                      '
   DO PUNIPOD WITH  88,'46.    ',' KASA RATA                     '
   DO PUNIPOD WITH  89,'47.    ',' OBUSTAVA 1                '
   DO PUNIPOD WITH  90,'48.    ',' OBUSTAVA 2                '
   DO PUNIPOD WITH  91,'49.    ',' OBUSTAVA 3                '
   DO PUNIPOD WITH  92,'50.    ',' UKUPNE OBUSTAVE           '
   DO PUNIPOD WITH  93,'51.    ',' ZA ISPLATU                '
   DO PUNIPOD WITH  94,'52.    ',' BENEFICIRANI STAZ         '
   DO PUNIPOD WITH  95,'53.    ',' CAS PO UCINKU             '
   DO PUNIPOD WITH  96,'54.    ',' CAS PO VREMENU            '
   DO PUNIPOD WITH  97,'55.    ',' CAS NOCNI RAD             '
   DO PUNIPOD WITH  98,'56.    ',' CAS PRODUZ.RAD            '
   DO PUNIPOD WITH  99,'57.    ',' CAS PRAZNIK               '
   DO PUNIPOD WITH 100,'58.    ',' CAS PLACENO ODS           '
   DO PUNIPOD WITH 101,'59.    ',' CAS PLAC.ODS 100 %        '
   DO PUNIPOD WITH 102,'60.    ',' CAS RAD NA PRAZNIK        '
   DO PUNIPOD WITH 103,'61.    ',' CAS RAD NEDELJOM          '
   DO PUNIPOD WITH 104,'62.    ',' CAS DORUCAK               '
   DO PUNIPOD WITH 105,'63.    ',' CAS VOJNA VEZBA           '
   DO PUNIPOD WITH 106,'64.    ',' CAS GODISNJI ODM.         '
   DO PUNIPOD WITH 107,'65.    ',' CAS BOLOVANJE             '
   DO PUNIPOD WITH 108,'66.    ',' CAS BOLOVANJE 100 %       '
   DO PUNIPOD WITH 109,'67.    ',' CAS OSTALO 1              '
   DO PUNIPOD WITH 110,'68.    ',' CAS OSTALO 2              '
   DO PUNIPOD WITH 111,'69.    ',' CAS OSTALO 3              '
   DO PUNIPOD WITH 112,'70.    ',' CAS OSTALO 4              '
   DO PUNIPOD WITH 113,'71.    ',' CAS OSTALO 5              '
   DO PUNIPOD WITH 114,'72.    ',' din po vremenu            '
   DO PUNIPOD WITH 115,'73.    ',' din po ucinku             '
   DO PUNIPOD WITH 116,'74.    ',' din munuli rad            '
   DO PUNIPOD WITH 117,'75.    ',' DIN NOCNI RAD             '
   DO PUNIPOD WITH 118,'76.    ',' DIN PRODUZ.RAD            '
   DO PUNIPOD WITH 119,'77.    ',' DIN PRAZNIK               '
   DO PUNIPOD WITH 120,'78.    ',' DIN RAD NEDELJOM          '
   DO PUNIPOD WITH 121,'79.    ',' DIN BOLOVANJE             '
   DO PUNIPOD WITH 122,'80.    ',' DIN BOLOVANJE 100 %       '
   DO PUNIPOD WITH 123,'81.    ',' DIN PLACENO ODS           '
   DO PUNIPOD WITH 124,'82.    ',' DIN PLAC.ODS 100 %        '
   DO PUNIPOD WITH 125,'83.    ',' DIN GODISNJI ODM.         '
   DO PUNIPOD WITH 126,'84.    ',' DIN VOJNA VEZBA           '
   DO PUNIPOD WITH 127,'85.    ',' DIN DORUCAK               '
   DO PUNIPOD WITH 128,'86.    ',' DIN RAD NA PRAZNIK        '
   DO PUNIPOD WITH 129,'87.    ',' DIN OSTALO 1              '
   DO PUNIPOD WITH 130,'88.    ',' DIN OSTALO 2              '
   DO PUNIPOD WITH 131,'89.    ',' DIN OSTALO 3              '
   DO PUNIPOD WITH 132,'90.    ',' DIN OSTALO 4              '
   DO PUNIPOD WITH 133,'91.    ',' DIN OSTALO 5              '
   DO PUNIPOD WITH 134,'92.    ',' FIKSNA PLATA              '
   DO PUNIPOD WITH 135,'93.    ',' TOPLI OBROK               '
   DO PUNIPOD WITH 136,'94.    ',' REGRES ZA GOD ODMOR       '
   DO PUNIPOD WITH 137,'95.    ',' TERENSKI DODATAK          '
   DO PUNIPOD WITH 138,'96.    ',' STIMULACIJA 1             '
   DO PUNIPOD WITH 139,'97.    ',' STIMULACIJA 2             '
   DO PUNIPOD WITH 140,'98.    ',' STIMULACIJA 3             '
   DO PUNIPOD WITH 141,'99.    ',' UKUPNI DODACI             '
   DO PUNIPOD WITH 142,'100.   ',' UKUPNE NAKNADE            '
   DO PUNIPOD WITH 143,'152.   ',' DOPRINOSI PIO VLASNIKA    '   
   DO PUNIPOD WITH 144,'153.   ',' NAKNADA PREVOZA           '   
   DO PUNIPOD WITH 145,'154.   ',' OBUSTAVA PREVOZA          '   
   
POP KEY