PUSH KEY CLEAR
SELECT LD
SET ORDER TO 6
GO TOP
DO WHILE.NOT.EOF()
   REPLACE SAMSIF WITH LDRAD.SAMSIF
   SKIP
ENDDO   
GO TOP
REPORT FORM LDSAMOD PREVIEW  FOR SAMODopr<>0

 SELECT LD
 SET ORDER TO  
 POP KEY