*------------------LD PLATA------------------

PROCEDURE LDPODtast
ON KEY LABEL F1    DO HELPN WITH 'LDPOD'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDPOD.RELEASE
ENDPROC

PROCEDURE LDPOD00tast
ON KEY LABEL F1    DO HELPN WITH 'LDPOD00'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDPOD00.RELEASE
ENDPROC


PROCEDURE LDPARTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDPAR'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDPAR.RELEASE
ENDPROC

PROCEDURE LDPAR2TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDPAR2'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDPAR2.RELEASE
ENDPROC

PROCEDURE LDRADTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDRAD'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL +     DO LDRADDOD
   on key label INS   DO LDRADDOD
   on key label F4   DO LDTRIMER  
   on key label F5   DO LDTREVIDBROJR
   on key label F6   DO LDTRSIFR  
   on key label F7   DO LDRADKART
   on key label F8   DO LDRADMESTATR
   on key label F9   DO LDRADGRUPE
   ON KEY LABEL ESC   LDRAD.RELEASE
ENDPROC

PROCEDURE LDRADCLTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDRADCL'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL +     DO LDRADCLDOD
   on key label INS   DO LDRADCLDOD
   ON KEY LABEL ESC   LDRADCL.RELEASE
ENDPROC

PROCEDURE LDRADCL0TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDRADCL0'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   *ON KEY LABEL +     DO LDRADDOD
   *on key label INS   DO LDRADDOD
   ON KEY LABEL ESC   LDRADCL0.RELEASE
ENDPROC

PROCEDURE LDRADCL0KTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDRADCL0K'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   *ON KEY LABEL +     DO LDRADDOD
   *on key label INS   DO LDRADDOD
   ON KEY LABEL ESC   LDRADCL0K.RELEASE
ENDPROC


PROCEDURE LDRADKTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDRADK'
   ON KEY LABEL F2   ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDRADK.RELEASE
ENDPROC

PROCEDURE LDTAST
   ON KEY LABEL F1    DO HELPN WITH 'LD'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LD.RELEASE
   ON KEY LABEL F4    DO LDTRIME
   ON KEY LABEL F5    DO LDTREVIDBROJ
   ON KEY LABEL F6    DO LDTRSIF
   ON KEY LABEL F7    DO LDKARTF8
   ON KEY LABEL F8    DO LDPOPUNIKOL
   ON KEY LABEL F10   DO LDOBRACF10
   ON KEY LABEL Shift+F3 DO LDLISTIC
   ON KEY LABEL Shift+F4 DO LDLISTICI
   ON KEY LABEL Shift+F10 DO LDBRISI
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE LDPRENOSITAST
   ON KEY LABEL F1    DO HELPN WITH 'LDPRENOSI'
   ON KEY LABEL F2   ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDPRENOSI.RELEASE
ENDPROC

PROCEDURE LDOBRACUNNSTARITAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOBRACUNNSTARI'
   ON KEY LABEL F2   ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDOBRACUNNSTARI.RELEASE
ENDPROC


PROCEDURE LDARHTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDARH'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDARH.RELEASE
   ON KEY LABEL F4    LDARH.TXTIME.GOTFOCUS
   ON KEY LABEL F5    LDARH.TXTKOLONA.GOTFOCUS
   ON KEY LABEL F6    LDARH.TXTBROJ.GOTFOCUS
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC



PROCEDURE LDUNOSCASTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDUNOSCAS'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDUNOSCAS.RELEASE
ENDPROC


PROCEDURE LDRADNIKKARTTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDRADNIKKART'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDRADNIKKART.RELEASE
ENDPROC

PROCEDURE LDRADNIKKARTATAST
   ON KEY LABEL F1    DO HELPN WITH 'LDRADNIKKARTA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDRADNIKKARTA.RELEASE
ENDPROC


PROCEDURE LDPODTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDPOD'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDPOD.RELEASE
ENDPROC

PROCEDURE LDUNOSRADTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDUNOSRAD'
   ON KEY LABEL ESC   LDUNOSRAD.RELEASE
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
ENDPROC

PROCEDURE LDPREBRUTOTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDPRENBRUTO'
   ON KEY LABEL ESC   LDPREBRUTO.RELEASE
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
ENDPROC



PROCEDURE LDODTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOD'
   ON KEY LABEL F2        ! /N CALC.EXE;ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F7    DO LDODF7
   ON KEY LABEL F8    DO LDODF8
   ON KEY LABEL F9    DO LDODF9
   ON KEY LABEL F10   DO LDODF10
   ON KEY LABEL ESC   LDOD.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC 
ENDPROC
   
PROCEDURE LDODATAST
   ON KEY LABEL F1    DO HELPN WITH 'LDODA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F7    DO LDODF7
   ON KEY LABEL F8    DO LDODF8
   ON KEY LABEL F9    DO LDODF9
   ON KEY LABEL F10   DO LDODF10
   ON KEY LABEL ESC   LDODA.RELEASE
ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC
PROCEDURE LDODBTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDODB'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F7    DO LDODF7
   ON KEY LABEL F8    DO LDODF8
   ON KEY LABEL F9    DO LDODF9
   ON KEY LABEL F10   DO LDODF10
   ON KEY LABEL ESC   LDODB.RELEASE
ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC


ENDPROC

PROCEDURE LDOPJTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOPJ'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F7    DO LDOPJF7
   ON KEY LABEL F10   DO LDOPJF10
   ON KEY LABEL ESC   LDOPJ.RELEASE
ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC

ENDPROC


PROCEDURE LDOPJNTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOPJN'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F7    DO LDOPJNF7
   ON KEY LABEL F10   DO LDOPJNF10
   ON KEY LABEL ESC   LDOPJN.RELEASE
ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC

ENDPROC


PROCEDURE L2VIRMTAST
   ON KEY LABEL F1    DO HELPN WITH 'L2VIRM'
    ON KEY LABEL F2        ! /N CALC.EXE
    ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   L2VIRM.RELEASE
ENDPROC

PROCEDURE L2VIRM0TAST
   ON KEY LABEL F1    DO HELPN WITH 'L2VIRM0'
    ON KEY LABEL F2        ! /N CALC.EXE
    ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   L2VIRM0.RELEASE
ENDPROC

PROCEDURE LDVIRMTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDVIRM'
   ON KEY LABEL F3    DO LDVIRMF2
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
  ON KEY LABEL F8    DO LDVIRMF8
   ON KEY LABEL F9    DO LDVIRMF9
   ON KEY LABEL F10   DO LDVIRMF10

   ON KEY LABEL ESC   LDVIRM.RELEASE
ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC

ENDPROC

PROCEDURE LDVIRM1TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDVIRM1'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDVIRM1.RELEASE
ENDPROC


PROCEDURE LDMESTATAST
   ON KEY LABEL F1    DO HELPN WITH 'LDMESTA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDMESTA.RELEASE
ENDPROC

PROCEDURE LDREKTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDREK'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F7    DO LDREKF7
   ON KEY LABEL F10   DO LDREKF10
   ON KEY LABEL ESC   LDREK.RELEASE
ENDPROC

PROCEDURE LDOD1TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOD1'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDOD1.RELEASE
ENDPROC

PROCEDURE LDOPJ1TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOPJ1'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDOPJ1.RELEASE
ENDPROC

PROCEDURE LDOPJ1NTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOPJ1N'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL F4    DO LDOPJ1NF4
   ON KEY LABEL F5    DO LDOPJ1NF5
   ON KEY LABEL F10   DO LDOPJ1NF10
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDOPJ1N.RELEASE
ENDPROC

PROCEDURE LDOPJ1N0TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOPJ1N0'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDOPJ1N0.RELEASE
ENDPROC

PROCEDURE LDNZ1TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDNZ1'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDNZ1.RELEASE
ENDPROC

PROCEDURE LDBOLNTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDBOLN'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDBOLN.RELEASE
ENDPROC

PROCEDURE LDINVTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDINV'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDINV.RELEASE
ENDPROC

PROCEDURE LDINV2TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDINV2'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDINV2.RELEASE
ENDPROC

PROCEDURE LDINV3TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDINV3'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDINV3.RELEASE
ENDPROC



PROCEDURE LDOPNRTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOPNR'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDOPNR.RELEASE
ENDPROC

PROCEDURE LDZ1TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDZ1'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDZ1.RELEASE
ENDPROC

PROCEDURE LDKREDTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDKRED'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL +     DO LDKREDDOD
   ON KEY LABEL F4    DO LDTRSIFRAK
   ON KEY LABEL F5    DO LDTREVIDBROJK
   ON KEY LABEL F6    DO LDTRSIFK
   ON KEY LABEL F7    DO LDKRRAD
   ON KEY LABEL F8    DO LDKRAN0
   ON KEY LABEL ESC   LDKRED.RELEASE
ENDPROC

PROCEDURE LDRADKRTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDRADKR'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDRADKR.RELEASE
ENDPROC

PROCEDURE LDRADCLTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDRADCL'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDRADCL.RELEASE
ENDPROC

PROCEDURE LDKREDRTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDKREDR'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL +     DO LDKREDRDOD
   ON KEY LABEL INS   DO LDKREDRDOD
   ON KEY LABEL ESC   LDKREDR.RELEASE
ENDPROC

PROCEDURE LDKREDRKARTTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDKREDRKART'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDKREDRKART.RELEASE
ENDPROC


PROCEDURE LDKRASTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDKRAS'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDKRAS.RELEASE
ENDPROC

PROCEDURE LDKREDKTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDKREDK'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDKREDK.RELEASE
ENDPROC

PROCEDURE LDSPISTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDSPIS'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDSPIS.RELEASE
ENDPROC

PROCEDURE LDAKONTTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDAKONT'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDAKONT.RELEASE
ENDPROC

PROCEDURE LDPRENKREDTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDPRENKRED'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDPRENKRED.RELEASE
ENDPROC

PROCEDURE LDPOPUNIKOLTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDPOPUNIKOL'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDPOPUNIKOL.RELEASE
ENDPROC

PROCEDURE LDSAMODTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDSAMOD'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDSAMOD.RELEASE
ENDPROC


PROCEDURE LDSIFRATAST
   ON KEY LABEL F1    DO HELPN WITH 'LDSIFRA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDSIFRA.RELEASE
ENDPROC

PROCEDURE LDOPJ2TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOPJ2'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDOPJ2.RELEASE
ENDPROC

PROCEDURE LDOPJ3TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOPJ3'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDOPJ3.RELEASE
ENDPROC

PROCEDURE LDOPJ4TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOPJ4'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDOPJ4.RELEASE
ENDPROC

PROCEDURE LDOPJ5TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOPJ5'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDOPJ5.RELEASE
ENDPROC

PROCEDURE LDOPJ6TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOPJ6'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDOPJ6.RELEASE
ENDPROC

PROCEDURE LDOPJ7TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOPJ7'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDOPJ7.RELEASE
ENDPROC

PROCEDURE LDOPJ8TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOPJ8'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDOPJ8.RELEASE
ENDPROC

PROCEDURE LDMESTAKTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDMESTAK'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDMESTAK.RELEASE
ENDPROC

PROCEDURE LD0TAST
   ON KEY LABEL F1    DO HELPN WITH 'LD0'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LD0.RELEASE
ENDPROC


PROCEDURE LDAKONTATAST
   ON KEY LABEL F1    DO HELPN WITH 'LDAKONTA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDAKONTA.RELEASE
ENDPROC

PROCEDURE LDARHBRISITAST
   ON KEY LABEL F1    DO HELPN WITH 'LDARHBRISI'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDARHBRISI.RELEASE
ENDPROC

PROCEDURE LDARHDODAJTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDARHDODAJ'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDARHDODAJ.RELEASE
ENDPROC

PROCEDURE LDARHIVATAST
   ON KEY LABEL F1    DO HELPN WITH 'LDARHIVA'
   ON KEY LABEL F2        ! /N CALC.EXE
  ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDARHIVA.RELEASE
ENDPROC


PROCEDURE LDARHIVA2TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDARHIVA2'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDARHIVA2.RELEASE
ENDPROC

PROCEDURE LDBOLTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDBOL'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDBOL.RELEASE
ENDPROC

PROCEDURE LDDUNKTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDDUNK'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDDUNK.RELEASE
ENDPROC

PROCEDURE LDDUNKUTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDDUNKU'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDDUNKU.RELEASE
ENDPROC

PROCEDURE LDGRUPATAST
   ON KEY LABEL F1    DO HELPN WITH 'LDGRUPA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDGRUPA.RELEASE
ENDPROC

PROCEDURE LDINZSTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDINZS'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDINZS.RELEASE
ENDPROC

PROCEDURE LDKATEGTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDKATEG'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDKATEG.RELEASE
ENDPROC

PROCEDURE LDKRASATAST
   ON KEY LABEL F1    DO HELPN WITH 'LDKRASA'
   ON KEY LABEL F2        ! /N CALC.EXE
   
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDKRASA.RELEASE
ENDPROC

PROCEDURE LDM4TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDM4'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDM4.RELEASE
ENDPROC

PROCEDURE LDM4BRISITAST
   ON KEY LABEL F1    DO HELPN WITH 'LDM4BRISI'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDM4BRISI.RELEASE
ENDPROC

PROCEDURE LDM4DODAJTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDM4DODAJ'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDM4DODAJ.RELEASE
ENDPROC

PROCEDURE LDM4OSNTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDM4OSN'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDM4OSN.RELEASE
ENDPROC

PROCEDURE LDM4PODTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDM4POD'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDM4POD.RELEASE
ENDPROC

PROCEDURE LDOBRACUNTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOBRACUN'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDOBRACUN.RELEASE
ENDPROC

PROCEDURE LDOBRACUNATAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOBRACUNA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDOBRACUNA.RELEASE
ENDPROC

PROCEDURE LDOBRACUNNTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOBRACUNN'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDOBRACUNN.RELEASE
ENDPROC

PROCEDURE LDOD1NTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOD1N'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDOD1N.RELEASE
ENDPROC

PROCEDURE LDODN2TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDODN2'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDODN2.RELEASE
ENDPROC

PROCEDURE LDOPJ2TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOPJ2'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDOPJ2.RELEASE
ENDPROC

PROCEDURE LDOPJ2P1TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOPJ2P1'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDOPJ2P1.RELEASE
ENDPROC

PROCEDURE LDOPJ2P2TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOPJ2P2'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDOPJ2P2.RELEASE
ENDPROC

PROCEDURE LDOPJ3TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOPJ3'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDOPJ3.RELEASE
ENDPROC

PROCEDURE LDOPJ4TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOPJ4'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDOPJ4.RELEASE
ENDPROC

PROCEDURE LDOPJ4P1TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOPJ4P1'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDOPJ4P1.RELEASE
ENDPROC

PROCEDURE LDOPJ4P2TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOPJ4P2'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDOPJ4P2.RELEASE
ENDPROC


PROCEDURE LDOPJ5TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOPJ5'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDOPJ5.RELEASE
ENDPROC

PROCEDURE LDOPJ6TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOPJ6'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDOPJ6.RELEASE
ENDPROC

PROCEDURE LDOPJ6P1TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOPJ6P1'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDOPJ6P1.RELEASE
ENDPROC

PROCEDURE LDOPJ7TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOPJ7'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDOPJ7.RELEASE
ENDPROC

PROCEDURE LDOPJ8TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOPJ8'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDOPJ8.RELEASE
ENDPROC

PROCEDURE LDOSNOVTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOSNOV'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDOSNOV.RELEASE
ENDPROC

PROCEDURE LDPOTVRTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDPOTVR'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDPOTVR.RELEASE
ENDPROC


PROCEDURE LDPOTVR2TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDPOTVR2'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDPOTVR2.RELEASE
ENDPROC


PROCEDURE LDPPPTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDPPP'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDPPP.RELEASE
ENDPROC

PROCEDURE LDPPP0TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDPPP0'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDPPP0.RELEASE
ENDPROC

PROCEDURE LDPRENBRUTOTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDPRENBRUTO'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDPRENBRUTO.RELEASE
ENDPROC

PROCEDURE LDRAD0TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDRAD0'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDRAD0.RELEASE
ENDPROC

PROCEDURE LDRAD0KARTTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDRAD0KART'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDRAD0KART.RELEASE
ENDPROC

PROCEDURE LDRADVRTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDRADVR'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDRADVR.RELEASE
ENDPROC

PROCEDURE LDRADVR1TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDRADVR1'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDRADVR1.RELEASE
ENDPROC

PROCEDURE LDRADVR2TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDRADVR2'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDRADVR2.RELEASE
ENDPROC

PROCEDURE LDRADVR3TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDRADVR3'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDRADVR3.RELEASE
ENDPROC

PROCEDURE LDRADVR4TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDRADVR4'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDRADVR4.RELEASE
ENDPROC

PROCEDURE LDSP01TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDSP01'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDSP01.RELEASE
ENDPROC

PROCEDURE LDTOPTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDTOP'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDTOP.RELEASE
ENDPROC

PROCEDURE LDVIRM6TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDVIRM6'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDVIRM6.RELEASE
ENDPROC

PROCEDURE LDDOTACTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDDOTAC'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDDOTAC.RELEASE
ENDPROC

PROCEDURE LDPUTNALTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDPUTNAL'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDPUTNAL.RELEASE
ENDPROC

PROCEDURE LDPUTNAL1TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDPUTNAL1'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDPUTNAL1.RELEASE
ENDPROC

PROCEDURE LD01TAST
   ON KEY LABEL F1    DO HELPN WITH 'LD01'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LD01.RELEASE
ENDPROC

PROCEDURE LD01pTAST
   ON KEY LABEL F1    DO HELPN WITH 'LD01p'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LD01p.RELEASE
ENDPROC

PROCEDURE LD01pbrisiTAST
   ON KEY LABEL F1    DO HELPN WITH 'LD01pbrisi'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LD01pbrisi.RELEASE
ENDPROC

PROCEDURE LDSLOBSTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDSLOBS'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDSLOBS.RELEASE
ENDPROC

PROCEDURE LDKON00TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDKON00'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDKON00.RELEASE
ENDPROC

PROCEDURE LDKON000TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDKON000'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDKON000.RELEASE
ENDPROC

PROCEDURE LDKONtAST
   ON KEY LABEL F1    DO HELPN WITH 'LDKON'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDKON.RELEASE
ENDPROC

PROCEDURE LDRADVRETAST
ON KEY LABEL F1    DO HELPN WITH 'LDRADVRE'
ON KEY LABEL ESC       LDRADVRE.RELEASE
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ENDPROC

PROCEDURE LDRADVRERTAST
ON KEY LABEL F1    DO HELPN WITH 'LDRADVRER'
ON KEY LABEL ESC       LDRADVRER.RELEASE
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ENDPROC

PROCEDURE LDRADVREDODTAST
ON KEY LABEL F1    DO HELPN WITH 'LDRADVREDOD'
ON KEY LABEL ESC       LDRADVREDOD.RELEASE
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ENDPROC

PROCEDURE LDPROSZTAST
ON KEY LABEL F1    DO HELPN WITH 'LDPROSZ'
ON KEY LABEL ESC       LDPROSZ.RELEASE
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ENDPROC

PROCEDURE LDTRAZITAST
   ON KEY LABEL F1    DO HELPN WITH 'LDTRAZI'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDTRAZI.RELEASE
ENDPROC

PROCEDURE LDTRSIFTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDTRSIF'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDTRSIF.RELEASE
ENDPROC

PROCEDURE LDPREVTRSIFTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDPREVTRSIF'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDPREVTRSIF.RELEASE
ENDPROC

PROCEDURE LDTRIMETAST
   ON KEY LABEL F1    DO HELPN WITH 'LDTRIME'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDTRIME.RELEASE
ENDPROC

PROCEDURE LDPREVTRIMETAST
   ON KEY LABEL F1    DO HELPN WITH 'LDPREVTRIME'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDPREVTRIME.RELEASE
ENDPROC

PROCEDURE LDTREVIDBROJTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDTREVIDBROJ'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDTREVIDBROJ.RELEASE
ENDPROC

PROCEDURE LDPREVTREVIDBROJTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDPREVTREVIDBROJ'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDPREVTREVIDBROJ.RELEASE
ENDPROC


PROCEDURE LDTRSIFKTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDTRSIFK'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDTRSIFK.RELEASE
ENDPROC


PROCEDURE LDTRSIFRAKTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDTRSIFRAK'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDTRSIFRAK.RELEASE
ENDPROC

PROCEDURE LDTREVIDBROJKTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDTREVIDBROJK'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDTREVIDBROJK.RELEASE
ENDPROC


PROCEDURE LDTRSIFrTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDTRSIFr'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDTRSIFr.RELEASE
ENDPROC


PROCEDURE LDtrimertAST
   ON KEY LABEL F1    DO HELPN WITH 'LDTRimeR'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDTRimer.RELEASE
ENDPROC

PROCEDURE LDTREVIDBROJRTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDTREVIDBROJR'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDTREVIDBROJR.RELEASE
ENDPROC

PROCEDURE LDRADVREPREGTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDRADVREPREG'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDRADVREPREG.RELEASE
ENDPROC

PROCEDURE LDTOPLITAST
   ON KEY LABEL F1    DO HELPN WITH 'LDTOPLI'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDTOPLI.RELEASE
ENDPROC


PROCEDURE ldoz07TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOZ07'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDOZ07.RELEASE
ENDPROC

PROCEDURE ldoz08TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOZ08'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDOZ08.RELEASE
ENDPROC



PROCEDURE ldoz09TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOZ09'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDOZ09.RELEASE
ENDPROC

PROCEDURE ldoz10TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOZ10'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDOZ10.RELEASE
ENDPROC


PROCEDURE LDTOREGTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDTOREG'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDTOREG.RELEASE
ENDPROC


PROCEDURE LDRADP0TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDRADP0'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDRADP0.RELEASE
ENDPROC



PROCEDURE LDDD0TAST
ON KEY LABEL F1        DO HELPN WITH 'LDDD0'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       LDDD0.RELEASE
ON KEY LABEL F10       DO LDDD0BIRAM
ENDPROC

PROCEDURE LDDDTAST
ON KEY LABEL F1        DO HELPN WITH 'LDDD'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL F4        DO LDTRIMEDD
ON KEY LABEL F6        DO LDTRSIFDD
ON KEY LABEL ESC       LDDD.RELEASE
ENDPROC

PROCEDURE LDSIFRADDTAST
ON KEY LABEL F1        DO HELPN WITH 'LDSIFRADD'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       LDSIFRADD.RELEASE
ENDPROC


PROCEDURE LDTRSIFDDTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDTRSIFDD'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDTRSIFDD.RELEASE
ENDPROC


PROCEDURE LDTRIMEDDTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDTRIMEDD'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDTRIMEDD.RELEASE
ENDPROC

PROCEDURE LDTREVIDBROJDDTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDTREVIDBROJDD'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDTREVIDBROJDD.RELEASE
ENDPROC

PROCEDURE LDDDPOPUNIKOLTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDDDPOPUNIKOL'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDDDPOPUNIKOL.RELEASE
ENDPROC

PROCEDURE LDIZJDOPTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDIZJDOP'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDIZJDOP.RELEASE
ENDPROC



PROCEDURE LDPORPOTTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDPORPOT'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDPORPOT.RELEASE
ENDPROC

PROCEDURE LDPORPOT12TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDPORPOT12'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDPORPOT12.RELEASE
ENDPROC


PROCEDURE LDPORSTATAST
   ON KEY LABEL F1    DO HELPN WITH 'LDPORSTA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDPORSTA.RELEASE
ENDPROC

PROCEDURE LDOZ07KTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOZ07K'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDOZ07K.RELEASE
ENDPROC

PROCEDURE LDOZ08KTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOZ08K'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDOZ08K.RELEASE
ENDPROC

PROCEDURE LDPREVTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDPREV'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDPREV.RELEASE
   ON KEY LABEL F4    DO LDPREVTRIME
   ON KEY LABEL F5    DO LDPREVTREVIDBROJ
   ON KEY LABEL F6    DO LDPREVTRSIF
   ON KEY LABEL Shift+F10 DO LDPREVBRISIsve
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE LDPREVSIFRATAST
   ON KEY LABEL F1    DO HELPN WITH 'LDPREVSIFRA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDPREVSIFRA.RELEASE
ENDPROC

PROCEDURE LDPREVPOPUNIKOLTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDPREVPOPUNIKOL'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDPREVPOPUNIKOL.RELEASE
ENDPROC

PROCEDURE LDPREVPOPUNIKOLNEOTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDPREVPOPUNIKOLNEO'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDPREVPOPUNIKOLNEO.RELEASE
ENDPROC

PROCEDURE LDZZO010TAST
ON KEY LABEL F1    DO HELPN WITH 'LDZZO010'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       LDZZO010.RELEASE
ENDPROC


PROCEDURE LDZZO01TAST
ON KEY LABEL F1    DO HELPN WITH 'LDZZO01'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       LDZZO01.RELEASE
ENDPROC

PROCEDURE LDZZO020TAST
ON KEY LABEL F1    DO HELPN WITH 'LDZZO020'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       LDZZO020.RELEASE
ENDPROC


PROCEDURE LDZZO02TAST
ON KEY LABEL F1    DO HELPN WITH 'LDZZO02'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       LDZZO02.RELEASE
ENDPROC

PROCEDURE LDPRIPKTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDPRIPK'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDPRIPK.RELEASE
ENDPROC

PROCEDURE LDPRIPTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDPRIP'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDPRIP.RELEASE
ENDPROC

PROCEDURE LDIZRVRETAST
   ON KEY LABEL F1    DO HELPN WITH 'LDIZRVRE'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL F4    DO LDIZRVRERAD
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDIZRVRE.RELEASE
ENDPROC

PROCEDURE LDDOPUNITAST
   ON KEY LABEL F1    DO HELPN WITH 'LDDOPUNI'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDDOPUNI.RELEASE
ENDPROC

PROCEDURE LD000TAST
   ON KEY LABEL F1    DO HELPN WITH 'LD000'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LD000.RELEASE
ENDPROC



PROCEDURE LDREK00TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDREK00'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDREK00.RELEASE
ENDPROC

PROCEDURE LDOBrOPJ18TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOBRopj18'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDOBRopj18.RELEASE
ENDPROC

PROCEDURE LDOBRBOLOVANJETAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOBRBOLOVANJE'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDOBRBOLOVANJE.RELEASE
ENDPROC


PROCEDURE LDobrporodTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOBRPOROD'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDOBRPOROD.RELEASE
ENDPROC

PROCEDURE LDOBRRACUNITAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOBRRACUNI'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDOBRRACUNI.RELEASE
ENDPROC

PROCEDURE LDOBRKNJIZENJETAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOBRKNJIZENJE'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDOBRKNJIZENJE.RELEASE
ENDPROC

PROCEDURE LDOBRKNJIZICETAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOBRKNJIZICE'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDOBRKNJIZICE.RELEASE
ENDPROC

PROCEDURE LDOBRINVALIDITAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOBRINVALIDI'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDOBRINVALIDI.RELEASE
ENDPROC

PROCEDURE LDOBRPODACITAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOBRPODACI'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDOBRPODACI.RELEASE
ENDPROC

PROCEDURE LDOBRPOTVRDETAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOBRPOTVRDE'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDOBRPOTVRDE.RELEASE
ENDPROC

PROCEDURE LDOBRIOSITAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOBRIOSI'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDOBRIOSI.RELEASE
ENDPROC

PROCEDURE LDOBRIOSI1TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOBRIOSI1'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDOBRIOSI1.RELEASE
ENDPROC

PROCEDURE LDzahtevTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDzahtev'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDzahtev.RELEASE
ENDPROC

PROCEDURE LDPPPBRISITAST
   ON KEY LABEL F1    DO HELPN WITH 'LDPPPBRISI'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDPPPBRISI.RELEASE
ENDPROC

PROCEDURE LDKOPIRAJMESTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDKOPIRAJMES'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDKOPIRAJMES.RELEASE
ENDPROC

PROCEDURE LDZSPTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDZSP'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDZSP.RELEASE
ENDPROC

PROCEDURE LDZSDTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDZSD'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDZSD.RELEASE
ENDPROC



PROCEDURE PREGLEDTAST
   ON KEY LABEL F1    DO HELPN WITH 'PREGLED'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PREGLED.RELEASE
ENDPROC

PROCEDURE MESTAKTAST
   ON KEY LABEL F1    DO HELPN WITH 'MESTAK'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   MESTAK.RELEASE
ENDPROC

PROCEDURE FMESTATRTAST

ON KEY LABEL F1    DO HELPN WITH 'FMESTATR'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 

ON KEY LABEL +         DO FMESTATRDOD
on key label INS       DO FMESTATRDOD
ON KEY LABEL ESC       FMESTATR.RELEASE
ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC

ENDPROC


PROCEDURE HELPNTAST
   ON KEY LABEL ESC       HELPN.RELEASE
   ON KEY LABEL F1    ON KEY
   ON KEY LABEL CTRL+F12  HELPN.GRD0.READONLY=.F.
ENDPROC

PROCEDURE NCALCTAST
ON KEY LABEL F1    DO HELPN WITH 'NCALC'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL INS       DO NCALCDOD
ON KEY LABEL F7        DO NCALCF7
ON KEY LABEL F8        DO NCALCF8
ON KEY LABEL ESC       NCALC.RELEASE
ENDPROC

PROCEDURE fan0dEONAZTAST
   ON KEY LABEL F1    DO HELPN WITH 'FAN0DEONAZ'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       fan0DEONAZ.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE VIRM1TAST
   ON KEY LABEL F1    DO HELPN WITH 'VIRM1'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   VIRM1.RELEASE
ENDPROC

PROCEDURE PREGLEDTXTTAST
   ON KEY LABEL F1    DO HELPN WITH 'PREGLEDTXT'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PREGLEDTXT.RELEASE
ENDPROC

PROCEDURE PREGFTAST
   ON KEY LABEL F1    DO HELPN WITH 'PREGF'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PREGF.RELEASE
ENDPROC

PROCEDURE PORUKATAST
   ON KEY LABEL F1    DO HELPN WITH 'PORUKA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PORUKA.RELEASE
ENDPROC

PROCEDURE AN0K2TAST
ON KEY LABEL F1    DO HELPN WITH 'AN0K2'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       AN0K2.RELEASE
ENDPROC

PROCEDURE FAN0TAST

ON KEY LABEL F1    DO HELPN WITH 'FAN0'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       FAN0.RELEASE
ON KEY LABEL +         DO FAN0DOD
on key label INS       DO FAN0DOD
ON KEY LABEL F3        DO FAN0DEONAZ
ON KEY LABEL ALT+F3        DO FAN0TEKRAC
ON KEY LABEL F4        DO FAN0TRAZI
ON KEY LABEL F5        DO FAN0GR5TRAZI
ON KEY LABEL F6        DO FAN0TRAZIF6
ON KEY LABEL F7        DO FAN0KARTF7
ON KEY LABEL F8        DO FAN0ZIROTRAZI
ON KEY LABEL CTRL+F12  DO OTVFAN0
ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC

ENDPROC

PROCEDURE fan0TEKRACTAST
   ON KEY LABEL F1    DO HELPN WITH 'FAN0TEKRAC'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       fan0TEKRAC.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE TMPREGLEDKOLONETAST
   ON KEY LABEL F1    DO HELPN WITH 'TMPREGLEDKOLONE'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       TMPREGLEDKOLONE.RELEASE
ENDPROC

PROCEDURE PUTARTAST
   ON KEY LABEL F1    DO HELPN WITH 'PUTAR'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL +         DO PUTARDOD
   on key label INS       DO PUTARDOD  
   ON KEY LABEL F4        DO PUTAR0 WITH 1
   ON KEY LABEL F7        DO PUTARK   
   ON KEY LABEL F10        DO PUTAR1
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PUTAR.RELEASE
ENDPROC

PROCEDURE PUTAR0TAST
   ON KEY LABEL F1    DO HELPN WITH 'PUTAR0'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL +         DO PUTAR0DOD
   on key label INS       DO PUTAR0DOD  
   ON KEY LABEL F7        DO PUTAR0K   
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PUTAR0.RELEASE
ENDPROC

PROCEDURE PUTAR0kTAST
   ON KEY LABEL F1    DO HELPN WITH 'PUTAR0k'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PUTAR0k.RELEASE
ENDPROC

PROCEDURE PUTARkTAST
   ON KEY LABEL F1    DO HELPN WITH 'PUTARk'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PUTARk.RELEASE
ENDPROC

PROCEDURE PUTAR1TAST
   ON KEY LABEL F1    DO HELPN WITH 'PUTAR1'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PUTAR1.RELEASE
ENDPROC

PROCEDURE LDATAST
   ON KEY LABEL F1    DO HELPN WITH 'LDA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDA.RELEASE
   ON KEY LABEL F4    DO LDTRIMEA
   ON KEY LABEL F5    DO LDTREVIDBROJA
   ON KEY LABEL F6    DO LDTRSIFA
   ON KEY LABEL F7    DO LDKARTF8
   ON KEY LABEL F8    DO LDPOPUNIKOL
   ON KEY LABEL F10   DO LDOBRACF10
   ON KEY LABEL Shift+F3 DO LDLISTIC
   ON KEY LABEL Shift+F4 DO LDLISTICI
   ON KEY LABEL Shift+F10 DO LDBRISIA
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC


PROCEDURE LDOSTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOS'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDOS.RELEASE
ENDPROC


PROCEDURE LDOS1TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOS1'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDOS1.RELEASE
ENDPROC


PROCEDURE LDizvjpTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDizvjp'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LDizvjp.RELEASE
ENDPROC

PROCEDURE LDOPJ7prenosTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDOPJ7prenos'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDOPJ7prenos.releaSE
ENDPROC

PROCEDURE LDPPODPOTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDPPODPO'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDPPODPO.releaSE
ENDPROC

PROCEDURE LDPPODPTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDPPODP'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDPPODP.releaSE
ENDPROC

PROCEDURE LDPPODOTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDPPODO'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDPPODO.releaSE
ENDPROC

PROCEDURE LDPPODSOTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDPPODSO'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDPPODSO.releaSE
ENDPROC


PROCEDURE LDPORODILJE00TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDPORODILJE00'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDPORODILJE00.releaSE
ENDPROC


PROCEDURE LDBOLOVANJE00TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDBOLOVANJE00'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDBOLOVANJE00.releaSE
ENDPROC


PROCEDURE LDprevparamTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDPREVPARAM'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDPREVPARAM.releaSE
ENDPROC


PROCEDURE LDPrEVARHIVATAST
   ON KEY LABEL F1    DO HELPN WITH 'LDPREVARHIVA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDPREVARHIVA.releaSE
ENDPROC


PROCEDURE ldprevsifraprihTAST
   ON KEY LABEL F1    DO HELPN WITH 'ldprevsifraprih'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       ldprevisfraprih.RELEASE
ENDPROC

PROCEDURE XM2LDPPPPARTAST
   ON KEY LABEL F1    DO HELPN WITH 'XM2LDPPPPAR'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   XM2LDPPPPAR.releaSE
ENDPROC


PROCEDURE ldopj7slaganjeTAST
   ON KEY LABEL F1    DO HELPN WITH 'ldopj7slaganje'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   ldopj7slaganje.releaSE
ENDPROC

PROCEDURE ldopj7PRENOSpTAST
   ON KEY LABEL F1    DO HELPN WITH 'ldopj7PRENOSp'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   ldopj7PRENOSp.releaSE
ENDPROC

PROCEDURE ldopj7brisiperiodTAST
   ON KEY LABEL F1    DO HELPN WITH 'ldopj7brisiperiod'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   ldopj7brisiperiod.releaSE
ENDPROC


PROCEDURE LDAKONT0TAST
   ON KEY LABEL F1    DO HELPN WITH 'LDAKONT0'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDAKONT0.releaSE
ENDPROC

PROCEDURE LDNOVIRTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDNOVIR'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDNOVIR.releaSE
ENDPROC

PROCEDURE LDNOVIRZTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDNOVIRZ'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDNOVIRZ.releaSE
ENDPROC

PROCEDURE LDNOVIRZpreuzmiTAST
   ON KEY LABEL F1    DO HELPN WITH 'LDNOVIRZpreuzmi'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDNOVIRZpreuzmi.releaSE
ENDPROC

PROCEDURE LDNAKNADETAST
   ON KEY LABEL F1    DO HELPN WITH 'LDNAKNADE'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LDNAKNADE.releaSE
ENDPROC
