PUSH KEY CLEAR
*---------POPUNJAVAN JE VIRMANA---------------------
SELECT LDPARAM
MREDISPL=ISPLATA
MSVRHA=' ZARADA ZA '+NAZMES+' '+GODINA+' '+STR(MREDISPL,1,0)
MSTAMPA='*'
MNAZMES=NAZMES
MAKTIVRAC=AKTIVRAC
MISPLATA=ISPLATA
MKONACNA=KONACNA
MMESEC=MESEC
DO CASE MREDISPL
CASE MREDISPL=1
   MDATDOK=DAT1
CASE MREDISPL=2
   MDATDOK=DAT2
CASE MREDISPL=3
   MDATDOK=DAT3
OTHERWISE
   MDATDOK=DAT4
ENDCASE   
MKOMJ=0
MKOMS=0
MKOMR=0
USE LDREK IN 0 ALIAS LDREK
SELECT LDREK
LOCATE FOR KOD='34.    '
IF FOUND()
MKOMJ=RAZLIKA
ENDIF
LOCATE FOR KOD='35.    '
IF FOUND()
MKOMS=RAZLIKA
ENDIF
LOCATE FOR KOD='36.    '
IF FOUND()
MKOMR=RAZLIKA
ENDIF
USE
SELECT FIRMA
MZIRORACZ=FZIRO
MFDOP=FDOP
MFREP=FPORREP
MRAZ='1'
IF MAKTIVRAC=1
   MZIRORACZ=FZIRO
   MRAZ='1'
ENDIF   
IF MAKTIVRAC=2
   MZIRORACZ=FZIRO2
   MRAZ='2'
ENDIF   
IF MAKTIVRAC=3
   MZIRORACZ=FZIRO3
   MRAZ='3'
ENDIF   
IF MAKTIVRAC=4
   MZIRORACZ=FZIRO4
   MRAZ='4'
ENDIF   
IF MAKTIVRAC=5
   MZIRORACZ=FZIRO5
   MRAZ='5'
ENDIF   
IF MAKTIVRAC=6
   MZIRORACZ=FZIRO6
   MRAZ='6'
ENDIF   

IF MISPLATA=3
   MZIRORACZ=FZIROBOL
   MRAZ='B'
ENDIF


SELECT MESTA
GO TOP
MPIO=0
MPIOF=0
MPIOVL=0
MNEZ=0
MNEZF=0
MBEN=0
DO WHILE.NOT.EOF()
   MPIO=MPIO+PIO-PIOU
   MPIOF=MPIOF+PIOF-PIOFU
   MPIOVL=MPIOVL+PIOVL
   MNEZ=MNEZ+NEZ
   MNEZF=MNEZF+NEZF
   MBEN=MBEN+BEN
   SKIP
ENDDO
 

SELECT L2VIRM
GO TOP
DO WHILE.NOT.EOF()
   MKOD=KOD
   MVRSTA=VRSTA
   MMODELO=MODELO
   MSIF1=SIF1
   MZIRORAC=ZIRORAC
   MNAZRAC=NAZRAC
   IF MKOD='27.    ';
      .OR.MKOD='29.    ';
      .OR.MKOD='31.    ';
      .OR.MKOD='33.    ';
      .OR.MKOD='52.    ';
      .OR.MKOD='34.    ';
      .OR.MKOD='35.    ';
      .OR.MKOD='36.    ';
      .OR.MKOD='102.   '
	   SELECT VIRM
       APPEND BLANK
          
       REPLACE VRSTA WITH MVRSTA
       REPLACE MODELO WITH MMODELO
       IF MKOD='27.    '.OR.MKOD='31.    '
          REPLACE POZIVO WITH MFDOP
       ENDIF
       IF MKOD='29.    '.OR.MKOD='33.    '
          IF MISPLATA<>3
             REPLACE POZIVO WITH MFDOP
          ELSE
             REPLACE POZIVO WITH MFREP
          ENDIF
       ENDIF
       IF MKOD='102.   '
          IF MISPLATA<>3
             REPLACE POZIVO WITH MFDOP
          ELSE
             REPLACE POZIVO WITH MFREP
          ENDIF
       ENDIF
       REPLACE SIF1 WITH MSIF1
       REPLACE ZIRORAC WITH MZIRORAC
       REPLACE ZIRORACZ WITH MZIRORACZ
       REPLACE NAZRAC WITH MNAZRAC
       REPLACE SVRHA WITH MSVRHA
       REPLACE STAMPA WITH MSTAMPA
       REPLACE DATDOK WITH MDATDOK
       REPLACE RAZ WITH MRAZ
       DO CASE MKOD   
       CASE MKOD='27.    ' 
          MDUG=MPIO
       CASE MKOD='29.    '
          MDUG=MNEZ
       CASE MKOD='31.    '
          MDUG=MPIOF
       CASE MKOD='33.    '
          MDUG=MNEZF
       CASE MKOD='52.    '
          MDUG=MBEN
       CASE MKOD='102.   '
          MDUG=MPIOVL
       CASE MKOD='34.    '
          MDUG=MKOMJ
       CASE MKOD='35.    '
          MDUG=MKOMS
       CASE MKOD='36.    '
          MDUG=MKOMR
       OTHERWISE
          MDUG=0
       ENDCASE               
       REPLACE DUG WITH MDUG
       SELECT L2VIRM  
   ELSE
      SELECT MESTA
      GO TOP
*      SET STEP ON 
      DO WHILE.NOT.EOF()
        
         MPORBROJ=PORBROJ
         MPORBROJP=PORBROJP
         IF MKOD='22.    '
            MPOR=POR-PORU
            IF MPOR<>0
               SELECT VIRM
               APPEND BLANK
               REPLACE VRSTA WITH MVRSTA
               REPLACE MODELO WITH MMODELO
               REPLACE SIF1 WITH MSIF1
               REPLACE ZIRORAC WITH MZIRORAC
               REPLACE ZIRORACZ WITH MZIRORACZ
               REPLACE NAZRAC WITH MNAZRAC
               REPLACE DUG WITH MPOR           
               IF MISPLATA<>3    
                  REPLACE POZIVO WITH MPORBROJ
               ELSE
                  REPLACE POZIVO WITH MPORBROJP
               ENDIF
               REPLACE SVRHA WITH MSVRHA
               REPLACE STAMPA WITH MSTAMPA
               REPLACE DATDOK WITH MDATDOK
               REPLACE RAZ WITH MRAZ
               SELECT MESTA
            ENDIF
         ENDIF   
         IF MKOD='28.    '
            MZDR=ZDR
            MZDRV=ZDRV
            IF MZDR<>0.OR.MZDRV<>0
               SELECT VIRM
               APPEND BLANK
               REPLACE VRSTA WITH MVRSTA
               REPLACE MODELO WITH MMODELO
               REPLACE SIF1 WITH MSIF1
               REPLACE ZIRORAC WITH MZIRORAC
               REPLACE ZIRORACZ WITH MZIRORACZ
               REPLACE NAZRAC WITH MNAZRAC
               REPLACE DUG WITH MZDR+MZDRV               
               IF MISPLATA<>3
                  REPLACE POZIVO WITH MPORBROJ
               ELSE
                  REPLACE POZIVO WITH MFREP
               ENDIF       
               REPLACE SVRHA WITH MSVRHA
               REPLACE STAMPA WITH MSTAMPA
               REPLACE DATDOK WITH MDATDOK
               REPLACE RAZ WITH MRAZ
               SELECT MESTA
            ENDIF
         ENDIF   
         IF MKOD='32.    '
            MZDRF=ZDRF
            MZDRFV=ZDRFV
            IF MZDRF<>0.OR.MZDRFV<>0
               SELECT VIRM
               APPEND BLANK
               REPLACE VRSTA WITH MVRSTA
               REPLACE MODELO WITH MMODELO
               REPLACE SIF1 WITH MSIF1
               REPLACE ZIRORAC WITH MZIRORAC
               REPLACE ZIRORACZ WITH MZIRORACZ
               REPLACE NAZRAC WITH MNAZRAC
               REPLACE DUG WITH MZDRF+MZDRFV
               IF MISPLATA<>3
                  REPLACE POZIVO WITH MPORBROJ
               ELSE
                  REPLACE POZIVO WITH MFREP
               ENDIF       
               REPLACE SVRHA WITH MSVRHA
               REPLACE STAMPA WITH MSTAMPA
               REPLACE DATDOK WITH MDATDOK
               REPLACE RAZ WITH MRAZ
               SELECT MESTA
            ENDIF
         ENDIF   
         IF MKOD='25.    '
            MPORF=PORF
            IF MPORF<>0
               SELECT VIRM
               APPEND BLANK
               REPLACE VRSTA WITH MVRSTA
               REPLACE MODELO WITH MMODELO
               REPLACE SIF1 WITH MSIF1
               REPLACE ZIRORAC WITH MZIRORAC
               REPLACE ZIRORACZ WITH MZIRORACZ
               REPLACE NAZRAC WITH MNAZRAC
               REPLACE DUG WITH MPORF               
               REPLACE POZIVO WITH MPORBROJ
               REPLACE SVRHA WITH MSVRHA
               REPLACE STAMPA WITH MSTAMPA
               REPLACE DATDOK WITH MDATDOK
               REPLACE RAZ WITH MRAZ
               SELECT MESTA
            ENDIF
         ENDIF   
         SKIP

      ENDDO   
   ENDIF

   SELECT L2VIRM
   SKIP
ENDDO
*--------POPUNJAVA JE VIRMANA ZA SAMODOPRINOS-------
USE LDSAMOD IN 0
SELECT LDSAMOD

GO TOP
DO WHILE.NOT.EOF()
   IF ISPLATA=MISPLATA.AND.MESEC=MMESEC

   MSTAMPA='*'
   MZIRORAC=ZIRORAC
   MNAZRAC='MESNI SAMODOPRINOS - '+SAMONAZ
   mdug=SAMODOP
   
   SELECT VIRM
   APPEND BLANK
   REPLACE STAMPA WITH MSTAMPA
   REPLACE DATDOK WITH MDATDOK
   REPLACE NAZRAC WITH MNAZRAC
   *--------POPUNJAVANJE SVRHE DOZNAKE---------
   MNAZMES2=MNAZMES+SPACE(10-LEN(ALLTRIM(MNAZMES)))
   MSVRHA='SAMOD. ZA '+MNAZMES2+' '+SUBSTR(DTOC(FIRMA.FDAT1),7,4)+' godine '+STR(MREDISPL,2,0)+' ISPLATA '
   REPLACE SVRHA WITH MSVRHA
   replace dug with mdug
   REPLACE ZIRORAC WITH MZIRORAC
       REPLACE ZIRORACZ WITH MZIRORACZ
   REPLACE VRSTA WITH '6'
   select LDSAMOD
   ENDIF
   skip
ENDDO   
select LDSAMOD
use
select VIRM
*----------popunjavanje podataka za spiskove isplate--------

use an0 IN 0 ORDER 1
SELECT AN0



USE LDSPIS IN 0  
SELECT LDSPIS  
GO TOP
SET ORDER TO 2

SELECT AN0
GO TOP
DO WHILE.NOT.EOF()
    REPLACE IZNOS1 WITH 0
    REPLACE IZNOS2 WITH 0    
    SKIP
ENDDO

GO TOP

DO WHILE.NOT.EOF()
   MSIFRA=SIFRA
   SELECT LDSPIS
   SEEK MSIFRA
   IF FOUND()
      MIZNOS=0
      DO WHILE.NOT.EOF()
         IF SIFRA<>MSIFRA
            EXIT
         ENDIF
         MIZNOS=MIZNOS+IZNOS
         SKIP
      ENDDO
      SELECT AN0
      REPLACE IZNOS1 WITH MIZNOS
   ENDIF
   SELECT AN0    
   SKIP
ENDDO

go top
do while.not.eof()
   IF IZNOS1<>0
      MDUG=IZNOS1
      MNAZIV=ALLTRIM(NAZIV)+' '+ALLTRIM(MESTO)+' - ZARADA '
      MZIRORAC=ZIRORAC
      SELECT VIRM
      APPEND BLANK
      REPLACE STAMPA WITH MSTAMPA
      REPLACE DATDOK WITH MDATDOK
      REPLACE NAZRAC WITH MNAZIV
      *--------POPUNJAVANJE SVRHE DOZNAKE---------
      MNAZMES2=MNAZMES+SPACE(9-LEN(ALLTRIM(MNAZMES)))
      MSVRHA='ISPLATA ZA '+MNAZMES2+' '+SUBSTR(DTOC(FIRMA.FDAT1),7,4)+' godine '+STR(MREDISPL,2,0)+' ISPLATA '
      REPLACE SVRHA WITH MSVRHA
      replace dug with mdug
      REPLACE ZIRORAC WITH MZIRORAC
      REPLACE ZIRORACZ WITH MZIRORACZ
      REPLACE RAZ WITH MRAZ
      REPLACE VRSTA WITH '7'
      REPLACE SIF1 WITH '240'

   ENDIF
   SELECT AN0
   skip
enddo      
SELECT AN0
USE
SELECT LDSPIS
USE
SELECT VIRM
*-------------POPUNJAVANJE KREDITA---------------------


use an0 IN 0 order  1
SELECT AN0
USE LDKRED IN 0
SELECT LDKRED
SET ORDER TO 3
MPOZIVO=''
MMODELO=''
SELECT AN0
GO TOP
DO WHILE.NOT.EOF()
   MSIFRA=SIFRA
   SELECT LDKRED
   SEEK MSIFRA
   IF FOUND()
      MMODELO=MODELO
      MPOZIVO=PARTIJA
      MIZNOS=0
      DO WHILE.NOT.EOF()
         IF SIFRA<>MSIFRA
            EXIT
         ENDIF
         IF MKONACNA='D'
         MIZNOS=MIZNOS+AKTIVRATA
         ELSE
         MIZNOS=MIZNOS+AKONTRATA
         ENDIF
         SKIP
      ENDDO
      SELECT AN0
      REPLACE IZNOS2 WITH MIZNOS
      REPLACE MODELO WITH MMODELO
      REPLACE POZIVO WITH MPOZIVO
   ENDIF
   SELECT AN0    
   SKIP
ENDDO
SELECT AN0
go top
do while.not.eof()
   IF IZNOS2<>0
      MDUG=IZNOS2
      MNAZIV=ALLTRIM(NAZIV)+' '+ALLTRIM(MESTO)+' - KREDIT'
      MZIRORAC=ZIRORAC
      MPOZIVO=POZIVO
      MMODELO=MODELO
      SELECT VIRM
      APPEND BLANK
      REPLACE STAMPA WITH MSTAMPA
      REPLACE DATDOK WITH MDATDOK
      REPLACE NAZRAC WITH MNAZIV
      *--------POPUNJAVANJE SVRHE DOZNAKE---------
      MNAZMES2=MNAZMES+SPACE(10-LEN(ALLTRIM(MNAZMES)))
      MSVRHA='KREDIT ZA '+MNAZMES2+' '+SUBSTR(DTOC(FIRMA.FDAT1),7,4)+' godine '+STR(MREDISPL,2,0)+' ISPLATA '
      REPLACE SVRHA WITH MSVRHA
      replace dug with mdug
      REPLACE ZIRORAC WITH MZIRORAC
      REPLACE ZIRORACZ WITH MZIRORACZ
      REPLACE RAZ WITH MRAZ
      REPLACE VRSTA WITH '8'
      REPLACE MODELO WITH MMODELO
      REPLACE POZIVO WITH MPOZIVO
      REPLACE SIF1 WITH '241'
   ENDIF
   SELECT AN0
   skip
enddo      
SELECT AN0
USE
SELECT LDKRED
USE
SELECT VIRM
DELETE ALL FOR DUG=0
PACK
replace ALL valuta WITH '941'
LOCATE FOR vrsta='99'
IF FOUND()
   mmodelo=modelo
   mpozivo=pozivo
   mdatdok=datdok
   mdatval=datval
   GO top
   DO while.not.eof()
      IF sif1='240'
         replace modelo WITH mmodelo
         replace pozivo WITH mpozivo
         replace datdok WITH mdatdok
         replace datval WITH mdatval
      endif
      SKIP
   enddo   
ENDIF
replace ALL modelo WITH '99' FOR modelo=SPACE(2)
GO top

POP KEY
LDVIRM.RELEASE
KEYBOARD '{ENTER}'

