PROCEDURE LECO00TAST
ON KEY LABEL F1    DO HELPN WITH 'LECO00'
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL ESC       LECO00.RELEASE
ENDPROC

PROCEDURE LECotipproTAST
ON KEY LABEL F1    DO HELPN WITH 'LECOtippro'
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL ESC       LECOtippro.RELEASE
ENDPROC

PROCEDURE LECoTARPORTAST
ON KEY LABEL F1    DO HELPN WITH 'LECOtARPOR'
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL ESC       LECOTARPOR.RELEASE
ENDPROC

PROCEDURE LECorobaTAST
ON KEY LABEL F1    DO HELPN WITH 'LECOroba'
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL ESC       LECOroba.RELEASE
ENDPROC

PROCEDURE LECogrupaTAST
ON KEY LABEL F1    DO HELPN WITH 'LECOgrupa'
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL ESC       LECOgrupa.RELEASE
ENDPROC

PROCEDURE LECoprogruTAST
ON KEY LABEL F1    DO HELPN WITH 'LECOprogru'
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL ESC       LECOprogru.RELEASE
ENDPROC

PROCEDURE LECozaliheTAST
ON KEY LABEL F1    DO HELPN WITH 'LECOzalihe'
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL ESC       LECOzalihe.RELEASE
ENDPROC

PROCEDURE LECoCENETAST
ON KEY LABEL F1    DO HELPN WITH 'LECOCENE'
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL ESC       LECOCENE.RELEASE
ENDPROC

PROCEDURE LECOPOPUSTITAST
ON KEY LABEL F1    DO HELPN WITH 'LECOPOPUSTI'
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL ESC       LECOPOPUSTI.RELEASE
ENDPROC

PROCEDURE LECORACUNITAST
ON KEY LABEL F1    DO HELPN WITH 'LECORACUNI'
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL ESC       LECORACUNI.RELEASE
ENDPROC

PROCEDURE LECODUGvezTAST
ON KEY LABEL F1    DO HELPN WITH 'LECODUGVEZ'
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL ESC       LECODUGVEZ.RELEASE
ENDPROC

PROCEDURE LECOKUPCITAST
ON KEY LABEL F1    DO HELPN WITH 'LECOKUPCI'
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL ESC       LECOKUPCI.RELEASE
ENDPROC

PROCEDURE LECOPORTAST
ON KEY LABEL F1    DO HELPN WITH 'LECOPOR'
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL ESC       LECOPOR.RELEASE
ENDPROC

PROCEDURE LECOPUTTAST
ON KEY LABEL F1    DO HELPN WITH 'LECOPUT'
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL ESC       LECOPUT.RELEASE
ENDPROC


PROCEDURE LECOPRIJEMTAST
ON KEY LABEL F1    DO HELPN WITH 'LECOPRIJEM'
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL F5        DO lecoprijembiram
ON KEY LABEL ESC       LECOPRIJEM.RELEASE
ENDPROC


PROCEDURE LECOakcproTAST
ON KEY LABEL F1    DO HELPN WITH 'LECOAKCPRO'
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL F2        ! /N CALC.EXE
oN KEY LABEL ESC       LECOAKCPRO.RELEASE
ENDPROC


PROCEDURE LECO002TAST
ON KEY LABEL F1    DO HELPN WITH 'LECO002'
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL ESC       LECO002.RELEASE
ENDPROC

PROCEDURE L2KOMERCTAST
	ON KEY LABEL F1    DO HELPN WITH 'L2KOMERC'
	ON KEY LABEL CTRL+ENTER DO NCALC 
	ON KEY LABEL F2        ! /N CALC.EXE
	ON KEY LABEL ESC       L2KOMERC.RELEASE
ENDPROC

PROCEDURE L2KUPCITAST
	ON KEY LABEL F1    DO HELPN WITH 'L2KUPCI'
	ON KEY LABEL CTRL+ENTER DO NCALC 
	ON KEY LABEL F2        ! /N CALC.EXE
	ON KEY LABEL ESC       L2KUPCI.RELEASE
ENDPROC

PROCEDURE L2KODOBTAST
	ON KEY LABEL F1    DO HELPN WITH 'L2KODOB'
	ON KEY LABEL CTRL+ENTER DO NCALC 
	ON KEY LABEL F2        ! /N CALC.EXE
	ON KEY LABEL ESC       L2KODOB.RELEASE
ENDPROC

PROCEDURE L2MESTAITAST
	ON KEY LABEL F1    DO HELPN WITH 'L2MESTAI'
	ON KEY LABEL CTRL+ENTER DO NCALC 
	ON KEY LABEL F2        ! /N CALC.EXE
	ON KEY LABEL ESC       L2MESTAI.RELEASE
ENDPROC

PROCEDURE L2ARTIKTAST
	ON KEY LABEL F1    DO HELPN WITH 'L2ARTIK'
	ON KEY LABEL CTRL+ENTER DO NCALC 
	ON KEY LABEL F2        ! /N CALC.EXE
	ON KEY LABEL ESC       L2ARTIK.RELEASE
ENDPROC


PROCEDURE L2UPLATAST
	ON KEY LABEL F1    DO HELPN WITH 'L2UPLA'
	ON KEY LABEL CTRL+ENTER DO NCALC 
	ON KEY LABEL F2        ! /N CALC.EXE
	ON KEY LABEL ESC       L2UPLA.RELEASE
ENDPROC

PROCEDURE L2DUGOVTAST
	ON KEY LABEL F1    DO HELPN WITH 'L2DUGOV'
	ON KEY LABEL CTRL+ENTER DO NCALC 
	ON KEY LABEL F2        ! /N CALC.EXE
	ON KEY LABEL ESC       L2DUGOV.RELEASE
ENDPROC

PROCEDURE L2DUGOVTAST
	ON KEY LABEL F1    DO HELPN WITH 'L2DUGOV'
	ON KEY LABEL CTRL+ENTER DO NCALC 
	ON KEY LABEL F2        ! /N CALC.EXE
	ON KEY LABEL ESC       L2DUGOV.RELEASE
ENDPROC

PROCEDURE L2MENICETAST
	ON KEY LABEL F1    DO HELPN WITH 'L2MENICE'
	ON KEY LABEL CTRL+ENTER DO NCALC 
	ON KEY LABEL F2        ! /N CALC.EXE
	ON KEY LABEL ESC       L2MENICE.RELEASE
ENDPROC

PROCEDURE L2SALDOTAST
	ON KEY LABEL F1    DO HELPN WITH 'L2SALDO'
	ON KEY LABEL CTRL+ENTER DO NCALC 
	ON KEY LABEL F2        ! /N CALC.EXE
	ON KEY LABEL ESC       L2SALDO.RELEASE
ENDPROC


