PARAMETERS MMIME,MMIME0
   COPY FILE &MMIME TO &MFSALJI
*   MBON='C:\KASABON'
*   COPY FILE &MMIME TO &MBON

   *MMIMEOK=MFPRIMI+'\'+MMIME0+'.OK'
   *MMIMEERR=MFPRIMI+'\'+MMIME0+'.ERR'
   
   
   *SET PATH TO &MFPRIMI
   *SET DEFAULT TO &MFPRIMI
   *BROJAC=0
   *DO WHILE.T.
   *   IF BROJAC=5000
   *      EXIT
   *   ENDIF
   *   IF FILE (MMIMEOK)
   *      ERASE &MMIMEOK
   *      EXIT
   *   ENDIF
   *   IF FILE (MMIMEERR)
   *      ERASE &MMIMEERR
   *      EXIT
   *   ELSE
   *      BROJAC=BROJAC+1
   *      LOOP
   *   ENDIF
   *ENDDO   
   *SET path TO &MDATAPOD
   *SET DEFAULT TO &MDATAPOD
