PUSH KEY CLEAR
SET ORDER TO 
IF RECCOUNT()>0
GO bottom
mdatdok=datdok
MMLM=MLM
MPROCPOR=PROCPOR
MDINPREM=DINPREM
MCENAMLM=CENAMLM
ELSE
mdatdok=DATE()
MMLM=0
MPROCPOR=0
MDINPREM=0
MCENAMLM=0
ENDIF
IF sifra<>SPACE(5).OR.RECCOUNT()<1
   APPEND BLANK
   replace datdok WITH mdatdok
   REPLACE MLM WITH MMLM
   REPLACE PROCPOR  WITH MPROCPOR
   REPLACE DINPREM WITH MDINPREM
   REPLACE CENAMLM WITH MCENAMLM
ENDIF
GO BOTTOM
MLEKO.GRD0.REFRESH
MLEKO.GRD0.COLUMN1.SETFOCUS
POP KEY
MLEKO.REFRESH