PUSH KEY CLEAR
SELECT MTR
SET ORDER TO 
GO BOTTOM
APPEND BLANK
GO BOTTOM
MTR.GRD0.SetFocus
MTR.GRD0.REFRESH
REPLACE MTR WITH RECNO()
DO FORM MTRKART
GO BOTTOM
MTR.GRD0.SetFocus
MTR.GRD0.REFRESH
MTR.REFRESH  
POP KEY