PUSH KEY clear
nalGK10.CMD0.setfocus
SELECT NALP
mbrnal=brnal
   DO idel WITH (kkockax)   
   DO idel WITH (kkockax2)   
SELECT NALP
COPY STRU TO &KKOCKA
USE &KKOCKA IN 0 ALIAS KOCKA exclu   
KKNALIZV=MDATA01+'\NALIZV'+OPERATER+'.DBF'
KKNALIZVX=MDATA01+'\NALIZV'+OPERATER+'.CDX'
KNALIZV=MDATA01+'\NALIZV'+OPERATER
KNALIZVX=MDATA01+'\NALIZV'+OPERATER


DO IDEL WITH (KKNALIZV)
DO IDEL WITH (KKNALIZVX)
DO IBAZE WITH KNALIZV,'NALIZV'
DO IIND WITH KNALIZV,'KONTO10+DTOS(DATDOK)','BRNAL','DTOS(DATDOK)',;
             'KONTO10+SIFRA+DTOS(DATDOK)','SIFRA+DTOS(DATDOK)','SIFRA+BRRAC+DTOS(DATDOK)'
USE &KNALIZV IN 0 ALIAS NALIZV EXCLUSIVE 
SELECT NALP
SET ORDER TO 2
SEEK MBRNAL
IF FOUND()
   DO WHILE.NOT.EOF()
      IF BRNAL<>MBRNAL
         EXIT
      ENDIF   
      MKONTO=KONTO
      MDUG=DUG
      MPOT=POT
      MOPIS=OPIS
      MDATDOK=DATDOK
      MBRNAL=BRNAL
      IF MDUG<>0.OR.MPOT<>0
         SELECT NALIZV
         APPEND BLANK
         REPLACE KONTO10 WITH MKONTO
         REPLACE DUG WITH MDUG
         REPLACE POT WITH MPOT
         REPLACE OPIS WITH MOPIS
         REPLACE BRNAL WITH MBRNAL
         replace datdok WITH mdatdok
         SELECT KOCKA
         APPEND BLANK
         REPLACE KONTO WITH MKONTO
      ENDIF
      SELECT NALP
      SKIP
   ENDDO    
ENDIF
SELECT KOCKA
USE
SELECT NALIZV
SET ORDER TO 
GO TOP
SET CENTURY off

*REPORT FORM NALOG610 PREVIEW
   mfile='NALOG610'
   uslov=""
   DO printer_bullzip WITH mdata02,mfile,uslov

SET CENTURY on
SELECT NALIZV
USE
SELECT NALP
SET ORDER TO 2
SEEK mbrnal
SET ORDER TO 
nalGK10.grd0.COLUMN2.setfocus
POP key