MBRNAL=BRNAL
SET ORDER TO 2
SEEK MBRNAL
IF FOUND()
   DO WHILE.NOT.EOF()
      IF BRNAL<>MBRNAL
         EXIT
      ENDIF   
      IF ARHIVA=' '
         REPLACE ARHIVA WITH '*'
      ELSE
         REPLACE ARHIVA WITH ' '
      ENDIF           
      SKIP
   ENDDO   
ENDIF  
SEEK MBRNAL
SET ORDER TO 
NALGK10.GRD0.SETFOCUS
NALGK10.Refresh 
