PUSH KEY CLEAR
   SELECT NALP
   SET ORDER TO 
   GO BOTTOM
   IF RECCOUNT()>0
      MOPIS=OPIS
      MBRNAL=BRNAL
      MDATDOK=DATDOK
      MKONTO=KONTO
      APPEND BLANK
      REPLACE KONTO WITH MKONTO
      REPLACE OPIS WITH MOPIS
      REPLACE BRNAL WITH MBRNAL
      REPLACE DATDOK WITH MDATDOK
      REPLACE DATUM WITH DATE()
      REPLACE VREME WITH TIME()
      NALGK10.GRD0.SETFOCUS
      NALGK10.REFRESH
   ELSE
      APPEND BLANK
      GO BOTTOM
   ENDIF
   NALGK10.GRD0.COLUMN1.SETFOCUS
   NALGK10.REFRESH  
POP KEY