PUSH KEY CLEAR
MBRNAL=BRNAL
SET ORDER TO 2
SEEK MBRNAL
IF FOUND()
   IF ARHIVA=' '
      DO WHILE.NOT.EOF()
         IF BRNAL<>MBRNAL
            EXIT
         ENDIF
         REPLACE DUG WITH 0
         REPLACE POT WITH 0
         SKIP
      ENDDO   
   ENDIF
ENDIF   
SEEK MBRNAL
NALGK10.GRD0.SetFocus
POP KEY
NALGK10.REFRESH