PUSH KEY CLEAR
SELECT NALMTR
USE
USE NALMTR IN 0 EXCLUSIVE
SELECT NALMTR
   PUBLIC DA_NE
   DA_NE='D'
   DO PORUKADANE WITH ' BRISANJE TABELE '
   IF DA_NE='D'   
      DELETE ALL
PACK

   ENDIF   
NALMTR.RELEASE
KEYBOARD '{ENTER}'
POP KEY