PUSH KEY CLEAR
SELECT NALMTR
MBRNAL=BRNAL
USE
USE NAlmtr IN 0 EXCLUSIVE
SELECT NALMTR
   PUBLIC DA_NE
   DA_NE='D'
   DO PORUKADANE WITH ' BRISANJE NALOGA '+MBRNAL
   IF DA_NE='D'   
      DELETE ALL FOR BRNAL=MBRNAL
      PACK
   ENDIF   
NALMTR.RELEASE
KEYBOARD '{ENTER}'
POP KEY