PUSH KEY CLEAR
SELECT NALMTRK
   PUBLIC DA_NE
   DA_NE='D'
   DO PORUKADANE WITH ' BRISANJE TABELE '
   IF DA_NE='D'   
      DELETE ALL
PACK

   ENDIF   
NALMTRK.RELEASE
NALMTR.RELEASE
KEYBOARD '{ENTER}'
POP KEY