PUSH KEY CLEAR
IF RECCOUNT()>0
   GO BOTTOM
   MDATDOK=DATDOK
   MDEV=DEV
   MKURS=KURS
ELSE
   MDATDOK=DATE()
   MDEV=''   
   MKURS=1
ENDIF
APPEND BLANK
REPLACE DATDOK WITH MDATDOK+1
REPLACE DEV WITH MDEV
REPLACE KURS WITH MKURS
POP KEY
NALPSIFDEV.REFRESH