PUSH KEY CLEAR
IF TNACINK<>'D'
   NALP.GRD0.COLUMN2.SETFOCUS
ELSE
   NALP2.GRD0.COLUMN2.SETFOCUS
ENDIF      
IF PPASGK=1
   TBRISI=1
   CLOSE ALL TABLES
   IF TANAL=='NALP'
      USE &KNALPA IN 0 ALIAS NALP EXCLU
   ELSE
      USE NALAP IN 0 ALIAS NALP EXCLU
   ENDIF
   SELECT NALP
   DELETE ALL FOR DUG=0.AND.POT=0
   PACK
   USE
   IF TNACINK<>'D'
      NALP.RELEASE
   ELSE
      NALP2.RELEASE
   ENDIF      
ENDIF
POP KEY