PUSH KEY CLEAR
NALP.CMD0.SETFOCUS
IF PPASGK=1
   IF DUG<>0
      PUBLIC APRIH
      APRIH='D'
   ENDIF
   IF POT<>0
      PUBLIC APRIH
      APRIH='P'
   ENDIF
   IF DUG<>0.OR.POT<>0
      DO FORM NALPDODPRIH
   ENDIF
ENDIF
NALP.GRD0.SETFOCUS
POP KEY