PUSH KEY CLEAR

MRREC=RECNO()
SET ORDER TO 2
MBRNAL=BRNAL
SEEK MBRNAL
MDUG=0
MPOT=0
DO WHILE.NOT.EOF()
   IF BRNAL<>MBRNAL
      EXIT
   ENDIF
   MDUG=MDUG+DUG
   MPOT=MPOT+POT
   SKIP
ENDDO
   NALP.LBLDUG.CAPTION=  ' DUGUJE    '
   NALP.LBLPOT.CAPTION=  ' POTRAŽUJE '            
   IF MDUG-MPOT<>0
      NALP.TXTSALDO.BACKCOLOR=RGB(168,255,168)
   ELSE
      NALP.TXTSALDO.BACKCOLOR=RGB(255,0,0)
   ENDIF      
   NALP.LBLSALDO.CAPTION=' SALDO     '
   NALP.TXTSALDO.VALUE=TRAN(MDUG-MPOT,'999 999 999 999.99')               
   NALP.TXTDUG.VALUE=TRAN(MDUG,'999 999 999 999.99')      
   NALP.TXTPOT.VALUE=TRAN(MPOT,'999 999 999 999.99')  
   POP KEY