PUSH KEY CLEAR
SELECT AATM
IF EOF()
   GO BOTTOM
ENDIF
mrec=RECNO()
         
      PUBLIC TREDNI,TKOJI,TMESTO,TVRSTA,TNAZIV,TGRAD,TSIFARNIK,TNET,TFVRSTA,TDANVAL
      TREDNI=ALLTRIM(SIFPROD)
      TNAZIV=ALLTRIM(PNAZIV)
      TMESTO=ALLTRIM(PMESTO)
      TSIFARNIK=SIFARNIK
      TKOJI=' '
      KTM='TM'+TREDNI+'.DBF'
      KTMX='TM'+TREDNI+'.CDX'
      TKOJI='M'
      TOBJEKAT='M'
      DO FORM TMNAL
      SELECT aatm
      GOTO mrec
      NALPTK.GRD0.REFRESH
POP KEY
