PUSH KEY CLEAR
   IF TNACINK<>'D'
      NALP.CMDKON.SETFOCUS
   ELSE
      NALP2.CMDKON.SETFOCUS
   ENDIF   
   DO FORM KONTO
   SELECT NALP
   IF TNACINK<>'D'   
      NALP.GRD0.SETFOCUS   
   ELSE
      NALP2.GRD0.SETFOCUS   
   ENDIF      
POP KEY