PUSH KEY CLEAR
SET EXACT OFF
MKONTO=KONTO
DO IDEL WITH (KKOCKAX)
SELECT NAL
COPY STRUCTURE TO &KKOCKA
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
SET ORDER TO 1
SEEK MKONTO
IF FOUND()
   DO WHILE.NOT.EOF()
      IF KONTO<>MKONTO
         EXIT
      ENDIF   
      SCATTER NAME POLJA
      SELECT KOCKA
      APPEND BLANK
      GATHER NAME POLJA
      SELECT NAL
      SKIP
   ENDDO   
ENDIF
SELECT KOCKA
GO TOP
MSTANJE=0
MSALDO=0
DO WHILE.NOT.EOF()
   MSTANJE=MSTANJE+ULAZ-IZLAZ
   MSALDO=MSALDO+DUG-POT
   REPLACE STANJE WITH MSTANJE
   REPLACE SALDO WITH MSALDO
   SKIP
ENDDO   
GO TOP
SET RELATION TO KONTO INTO KONTO ADDITIVE
*REPORT FORM NALPREGMAT PREVIEW
   mfile='NALPREGMAT'
   uslov=""
   DO printer_bullzip WITH mdata02,mfile,uslov

SELECT KOCKA
SET RELATION TO
USE
SELECT NAL
SET ORDER TO 1
SEEK MKONTO
SET ORDER TO 3
NAL.GRD0.SETFOCUS
NAL.REFRESH
POP KEY