PUSH KEY CLEAR
IF RECCOUNT()>0
GO top
MBRNAL=BRNAL
MOPIS=OPIS
MDATDOK=DATDOK
MDEV=''
MDEVKURS=0
SELECT AAAN
GO TOP
DO WHILE.NOT.EOF()
   MKONTO=KONTO
   MDP=DP
   MSIFPROD=ALLTRIM(SIFPROD)
   MDUG=0
   MPOT=0
   MDEVDUG=0
   MDEVPOT=0
   MKANAL='ANAL'+MSIFPROD+'.DBF'
   IF FILE(MKANAL)
      USE &MKANAL ALIAS ANAL IN 0 ORDER 4
      SELECT ANAL
      SEEK MBRNAL
      IF FOUND()
         DO WHILE.NOT.EOF()
            IF BRNAL<>MBRNAL
               EXIT
            ENDIF 
            MDUG=MDUG+DUG
            MPOT=MPOT+POT
            MDEVDUG=MDEVDUG+DEVDUG
            MDEVPOT=MDEVPOT+DEVPOT  
            IF MDEVDUG<>0.OR.MDEVPOT<>0
            MDEV=DEV
            MDEVKURS=DEVKURS
            ENDIF
            SKIP
         ENDDO   
      ENDIF
      USE
   ENDIF
   SELECT NALP
   IF MDUG<>0.OR.MDEVDUG<>0
      APPEND BLANK
      REPLACE DUG WITH MDUG
      REPLACE DEVDUG WITH MDEVDUG
      REPLACE BRNAL WITH MBRNAL
      REPLACE OPIS WITH MOPIS
      REPLACE DATDOK WITH MDATDOK
      REPLACE KONTO WITH MKONTO
      IF DEVDUG<>0
         REPLACE DEV WITH MDEV
         REPLACE DEVKURS WITH MDEVKURS
      ENDIF   
   ENDIF
   IF MPOT<>0.OR.MDEVPOT<>0
      APPEND BLANK
      REPLACE POT WITH MPOT
      REPLACE DEVPOT WITH MDEVPOT
      REPLACE BRNAL WITH MBRNAL
      REPLACE OPIS WITH MOPIS
      REPLACE DATDOK WITH MDATDOK
      REPLACE KONTO WITH MKONTO
      IF DEVPOT<>0
         REPLACE DEV WITH MDEV
         REPLACE DEVKURS WITH MDEVKURS
      ENDIF   
   ENDIF
      
   SELECT AAAN    
   SKIP
ENDDO   
SELECT NALP
NALP.GRD0.SETFOCUS
GO BOTTOM
NALP.GRD0.REFRESH
ENDIF
POP KEY