PUSH KEY CLEAR
IF RECCOUNT()>0
   MREC=RECNO()
      DO idel WITH (kkockax)

   COPY TO &KKOCKA FOR RECNO()=MREC      
   APPEND FROM &KKOCKA
   SELECT NALP
   IF tnacink<>'D'
      NALP.GRD0.SETFOCUS
      GO BOTTOM
      NALP.GRD0.REFRESH
   ELSE
      NALP2.GRD0.SETFOCUS
      GO BOTTOM
      NALP2.GRD0.REFRESH
   endif
ENDIF
POP KEY