PUSH KEY CLEAR
MBRNAL=BRNAL
SET ORDER TO 2
SEEK MBRNAL
IF FOUND()
   DO WHILE.NOT.EOF()
      IF BRNAL<>MBRNAL
         EXIT
      ENDIF
      REPLACE DUG WITH 0
      REPLACE POT WITH 0
      REPLACE DEVDUG WITH 0
      REPLACE DEVPOT WITH 0    
      SKIP
   ENDDO   
ENDIF   
SEEK MBRNAL
NALPN.GRD0.SetFocus
POP KEY
NALPN.REFRESH