   PROCEDURE PVRNAL 
      parameters N1,N2,N3,N4,N5,N6,N7,N8,N9,N10,N11
      PUSH KEY CLEAR
      APPEND BLANK
        REPLACE VRNAL WITH N1
         REPLACE NAZIV WITH N2
         REPLACE PERIOD WITH N3
         REPLACE OBL WITH N4
         REPLACE DOK WITH N5
         REPLACE Mp WITH N6
         REPLACE NALDOK WITH N7
         REPLACE ZNAKOVI WITH N8
         REPLACE POCSIF WITH N9
         REPLACE NAUTO WITH N10
         REPLACE KONTO WITH N11
         POP KEY
   ENDPROC
