PUSH KEY CLEAR
SELECT NALP
MTMDATDOK=DATDOK
MTMBRNAL=BRNAL
NALP.CMD0.SETFOCUS
USE AATM IN 0
SELECT AATM
MREC=RECCOUNT()
GO TOP
DO WHILE.NOT.EOF()
   MREDNI=ALLTRIM(SIFPROD)
   MDOK='M'+MREDNI
   MKONTO=KONTO
   MKONTOPAZ=KONTOPAZ
   KTM='TM'+MREDNI+'.DBF'
   IF FILE(KTM)
      USE &KTM IN 0 ALIAS TM
      SELECT TM
      SET ORDER TO 1
      SEEK MTMDATDOK
      IF FOUND()
         MUPLACENO=0
         DO WHILE.NOT.EOF()
            IF DATDOK<>MTMDATDOK
               EXIT
            ENDIF
            MUPLACENO=MUPLACENO+UPLACENO   
            REPLACE BRNAL WITH MTMBRNAL
            SKIP
         ENDDO   
      ELSE
         MUPLACENO=0   
      ENDIF 
      SELECT NALP
      GO BOTTOM
      IF DUG<>0.OR.POT<>0
         APPEND BLANK
      ENDIF
      REPLACE KONTO WITH MKONTOPAZ
      REPLACE OPIS WITH 'PAZAR PRODAVNICE '+MREDNI
      REPLACE BRNAL WITH MTMBRNAL
      REPLACE DATDOK WITH MTMDATDOK
      REPLACE POT WITH MUPLACENO
      REPLACE DOK WITH MDOK
      SELECT TM
      USE
   ENDIF
   SELECT AATM
   SKIP
ENDDO   
CLOSE ALL
   PUBLIC TKOJI,TANAL
   TKOJI='NALGK'
   TANAL='NALP'
POP KEY
   nalp.release

KEYBOARD '{ENTER}'

