PUSH KEY CLEAR
   MBRNAL=BRNAL
   NALP.COMMAND28.SETFOCUS
   USE PDVU IN 0 ORDER 5
   SELECT PDVU
   DO IDEL WITH (KKOCKAX)
   COPY STRU TO &KKOCKA
   USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
   SELECT PDVU
   SEEK MBRNAL
   IF FOUND()
      DO WHILE.NOT.EOF()
         IF BRNAL<>MBRNAL
            EXIT
         ENDIF
         SCATTER NAME POLJA
         IF VPDV<>SPACE(3)
            SELECT KOCKA
            APPEND BLANK
            GATHER NAME POLJA   
         ENDIF
         SELECT PDVU
         SKIP
      ENDDO
   ENDIF
   SELECT PDVU
   USE
   SELECT KOCKA
   INDEX ON SIFRA TAG SIFRA
   SET ORDER TO 1
   SELECT KOCKA
   SET RELATION TO SIFRA INTO AN0
   GO TOP
   DO WHILE.NOT.EOF()
      MNAZ=AN0.NAZIV
      MDUG=UKNAB-PDV18-PDV8-PDV5
      MKONTO=KONTO
      
      SELECT NALP
      GO BOTTOM
      MBRNAL=BRNAL
      MDATDOK=DATDOK
      IF MDUG<>0
         APPEND BLANK
         REPLACE BRNAL WITH MBRNAL
         REPLACE DUG WITH MDUG
         REPLACE KONTO WITH MKONTO
         REPLACE OPIS WITH MNAZ
         REPLACE DATDOK WITH MDATDOK
      ENDIF
      SELECT KOCKA
      SKIP
   ENDDO    
   SELECT KOCKA
   SET RELATION TO
   USE
   USE
   SELECT NALP
   NALP.GRD0.SETFOCUS
   NALP.Refresh   
 


   USE PDVI IN 0 ORDER 5
   SELECT PDVI
   DO IDEL WITH (KKOCKAX)
   COPY STRU TO &KKOCKA
   USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
   SELECT PDVI
*   BROW
   SEEK MBRNAL
   IF FOUND()
      DO WHILE.NOT.EOF()
         IF BRNAL<>MBRNAL
            EXIT
         ENDIF
         SCATTER NAME POLJA
         IF VPDV<>SPACE(3)
            SELECT KOCKA
            APPEND BLANK
            GATHER NAME POLJA   
         ENDIF
         SELECT PDVI
         SKIP
      ENDDO
   ENDIF
   SELECT PDVI
   USE
   SELECT KOCKA
   INDEX ON SIFRA TAG SIFRA
   SET ORDER TO 1
   SELECT KOCKA
   SET RELATION TO SIFRA INTO AN0
   GO TOP
   DO WHILE.NOT.EOF()
      MNAZ=AN0.NAZIV
      MDUG=UKPROD-PDV18-PDV8
      MKONTO=KONTO
      MDEVDUG=DEVDUG
      MDEVPOT=DEVPOT
      MDEVKURS=DEVKURS
      MDEV=DEV
      SELECT NALP
      GO BOTTOM
      MBRNAL=BRNAL
      MDATDOK=DATDOK
      IF MDUG<>0
      APPEND BLANK
      REPLACE BRNAL WITH MBRNAL
      REPLACE POT WITH MDUG
      REPLACE KONTO WITH MKONTO
      REPLACE OPIS WITH MNAZ
      REPLACE DATDOK WITH MDATDOK
      REPLACE DEVPOT WITH  MDEVDUG
      REPLACE DEVKURS WITH MDEVKURS
      REPLACE DEV WITH MDEV
      ENDIF
      SELECT KOCKA
      SKIP
   ENDDO    
   SELECT KOCKA
   SET RELATION TO
   USE
   USE
   SELECT NALP
   NALP.GRD0.SETFOCUS
   POP KEY

