PUSH KEY clear
SELECT NALPRNAL
mbrnal=brnal
MMREC=RECNO()

   DO idel WITH (kkockax)
   DO idel WITH (kkockax2)




KKNALIZV=MDATA01+'\NALIZV'+OPERATER+'.DBF'
KKNALIZVX=MDATA01+'\NALIZV'+OPERATER+'.CDX'
KNALIZV=MDATA01+'\NALIZV'+OPERATER
KNALIZVX=MDATA01+'\NALIZV'+OPERATER


DO IDEL WITH (KKNALIZV)
DO IDEL WITH (KKNALIZVX)
DO IBAZE WITH KNALIZV,'NALIZV'
DO IIND WITH KNALIZV,'KONTO+DTOS(DATDOK)','BRNAL','DTOS(DATDOK)',;
             'KONTO+SIFRA+DTOS(DATDOK)','SIFRA+DTOS(DATDOK)','SIFRA+BRRAC+DTOS(DATDOK)'


USE &KNALIZV IN 0 ALIAS NALIZV EXCLUSIVE 

USE NAL IN 0 ORDER 2
SELECT NAL
SEEK MBRNAL
IF FOUND()
   DO WHILE.NOT.EOF()
      IF BRNAL<>MBRNAL
         EXIT
      ENDIF   
      MKONTO=KONTO
      MDUG=DUG
      MPOT=POT
      MOPIS=OPIS
      MDEV=DEV
      MDEVKURS=DEVKURS
      MDEVDUG=DEVDUG
      MDEVPOT=DEVPOT
      MDATDOK=DATDOK
      MBRNAL=BRNAL
      MDOK=DOK
      MMP=MP
      MMTR=MTR 
      SELECT NALIZV
      IF MDUG<>0.OR.MPOT<>0
      APPEND BLANK
      REPLACE KONTO WITH MKONTO
      REPLACE DUG WITH MDUG
      REPLACE POT WITH MPOT
      REPLACE OPIS WITH MOPIS
      REPLACE DEV WITH MDEV
      REPLACE DEVKURS WITH MDEVKURS
      REPLACE DEVDUG WITH MDEVDUG
      REPLACE DEVPOT WITH MDEVPOT
      REPLACE BRNAL WITH MBRNAL
      REPLACE MP WITH MMP
      REPLACE MTR WITH MMTR
      REPLACE DOK WITH MDOK  
      REPLACE GRUPA WITH '00'
      replace datdok WITH mdatdok
      ENDIF
      SELECT NAL
      SKIP
   ENDDO    
ENDIF
SELECT NAL
USE

SELECT NALIZV
SET ORDER TO 
GO TOP
SET CENTURY off
*REPORT FORM NALOG6 PREVIEW
   mfile='NALOG6'
   uslov=""
   DO printer_bullzip WITH mdata02,mfile,uslov

SET CENTURY on
SELECT NALIZV
USE


SELECT NALPRNAL
SET ORDER TO 
GOTO MMREC
POP key
NALPRNAL.GRD0.setfocus