PUSH KEY CLEAR
NALPRKON.CMDF10.SETFOCUS
DO IDEL WITH (KKOCKAX)
SELECT NALPRKON
MKONTO=KONTO
MMREC=RECNO()
USE nal IN 0 ORDER 4
SELECT nal
SELECT KONTO,OPIS,DUG,POT,SALDO,MP,MTR,DOK,BRNAL,DATDOK FROM NAL WHERE KONTO=MKONTO;
                         INTO cursor KOCKA readwrite ORDER BY DATDOK
                        * USE
*SELECT nal
*use
USE &KKONTO IN 0 ALIAS KONTO ORDER 1                         
SELECT KOCKA
   SELECT KOCKA
   GO TOP
   MSALDO=0
   MDUG=0
   MPOT=0
   DO WHILE.NOT.EOF()
      MSALDO=MSALDO+DUG-POT
      REPLACE SALDO WITH MSALDO
      MDUG=MDUG+DUG
      MPOT=MPOT+POT
      SKIP
   ENDDO   
   ADUG=MDUG
   APOT=MPOT
   SET ORDER TO 
   GO TOP
   SET RELATION TO KONTO INTO KONTO ADDITIVE
   PUBLIC ANAZIV
   ANAZIV=KONTO.NAZIV
   *REPORT FORM NALPRKON0  PREVIEW 
   mfile='NALPRKON0'
   uslov=""
   DO printer_bullzip WITH mdata02,mfile,uslov
   
   SELECT KOCKA
   USE
   SELECT KONTO
   USE
   SELECT NAL
   USE
SELECT NALPRKON
SET ORDER TO 
GOTO MMREC
POP key
NALPRKON.GRD0.setfocus