PUSH KEY CLEAR
SELECT NALP
MBRNAL=BRNAL
SELECT NALBROJ
SEEK MBRNAL
IF FOUND()
   MVRNAL=VRNAL
ELSE
   MVRNAL=SPACE(3)
ENDIF
SELECT NALVRSTA
SEEK MVRNAL
IF FOUND()
   MKONTOI=KONTO
ELSE
   MKONTOI=SPACE(8) 
ENDIF           

SELECT NALP
IF MKONTOI<>SPACE(8)
   SET ORDER TO 2
   MDUG=0
   MPOT=0
   MMKONTO=KONTO
   BB=1
   GO TOP
   DO WHILE.NOT.EOF()
      IF BRNAL<>MBRNAL
         EXIT
      ENDIF
      MDUG=MDUG+DUG
      MPOT=MPOT+POT
      MOPIS=OPIS
      MDATDOK=DATDOK
      IF KONTO=MKONTOI
         BB=0
      ENDIF
      SKIP
   ENDDO

   IF BB=1
      IF MPOT<>0
         APPEND BLANK
         REPLACE KONTO WITH MKONTOI
         REPLACE OPIS WITH MOPIS
         REPLACE DATDOK WITH MDATDOK
         REPLACE DUG WITH MPOT
         REPLACE BRNAL WITH MBRNAL
         REPLACE DATUM WITH DATE()
         REPLACE VREME WITH TIME()
         
      ENDIF

      IF MDUG<>0
         APPEND BLANK
         REPLACE KONTO WITH MKONTOI
         REPLACE OPIS WITH MOPIS
         REPLACE DATDOK WITH MDATDOK
         REPLACE POT WITH MDUG
         REPLACE BRNAL WITH MBRNAL
         REPLACE DATUM WITH DATE()
         REPLACE VREME WITH TIME()
      ENDIF
   ENDIF     
ENDIF   
SET ORDER TO
GO BOTTOM

IF TNACINK<>'D'
   NALP.GRD0.SETFOCUS
   POP KEY
   NALP.REFRESH
ELSE
   NALP2.GRD0.SETFOCUS
   POP KEY
   NALP2.REFRESH
ENDIF