PUSH KEY CLEAR
*   SET STEP ON 
   *------PROVERA POSTOJANJA KONTA U ANALITICI-------
   SELECT NALP
   ttanal=tanal 
*   SET STEP ON 
   IF PKNJAN='D'
         DO NALPANAL1
   ELSE
         DO NALPANAL2
   ENDIF        
   SELECT NALP
   TANAL=ttanal
   KEYBOARD '{RIGHTARROW}'
   KEYBOARD '{LEFTARROW}'
*   NALP.GRD0.REFRESH
*   NALP.REFRESH
POP KEY
