PUSH KEY CLEAR
IF PPASGK=1
   IF RECCOUNT()>0
      MOPIS=OPIS
      MBRNAL=BRNAL
      MDATDOK=DATDOK
      MKONTO=KONTO
      MMP=MP
      MMTR=MTR
      MDOK=DOK
      APPEND BLANK
      REPLACE KONTO WITH MKONTO
      REPLACE OPIS WITH MOPIS
      REPLACE BRNAL WITH MBRNAL
      REPLACE DATDOK WITH MDATDOK
      REPLACE OPER WITH OPERATER
      REPLACE DATUM WITH DATE()
      REPLACE VREME WITH TIME()
      REPLACE DOK WITH MDOK
      REPLACE MTR WITH MMTR
      REPLACE MP WITH MMP
      NALP.GRD0.SETFOCUS
      NALP.REFRESH
   ELSE
      DO FORM NALBROJ
   ENDIF
   NALP2.GRD0.COLUMN1.SETFOCUS
   NALP2.REFRESH  
ENDIF
POP KEY