PUSH KEY CLEAR
   GO TOP
   DO WHILE.NOT.EOF()
      REPLACE DUG WITH 0
      REPLACE POT WITH 0
      REPLACE DEVDUG WITH 0
      REPLACE DEVPOT WITH 0    
      SKIP
   ENDDO   
NALP.GRD0.SetFocus
POP KEY
NALP.REFRESH