PUSH KEY CLEAR
SELECT NALP
MBRNAL=BRNAL
MOPIS=OPIS
MMTR=MTR
MDOK=DOK
MDATDOK=DATDOK
NALP.COMMAND29.SETFOCUS
SELECT AAAN
GO TOP
DO WHILE.NOT.EOF()
   MANSIF=SIFPROD
   MANKON=KONTO
   KANAL ='ANAL'+ALLTRIM(MANSIF)+'.DBF'
   USE &KANAL IN 0 ALIAS ANAL ORDER 4
   SELECT ANAL
   SEEK MBRNAL
   IF FOUND()
      MDUG=0
      MPOT=0
      DO WHILE.NOT.EOF()
         IF BRNAL<>MBRNAL
            EXIT
         ENDIF
         MDUG=MDUG+DUG
         MPOT=MPOT+POT
         SKIP
      ENDDO
      SELECT NALP
      IF DUG<>0.OR.POT<>0
         APPEND BLANK
      ENDIF
         REPLACE BRNAL WITH MBRNAL
         REPLACE OPIS WITH MOPIS
         REPLACE MTR WITH MMTR
         REPLACE DOK WITH MDOK
         REPLACE DATDOK WITH MDATDOK
         REPLACE KONTO WITH MANKON
         REPLACE DUG WITH MDUG
         REPLACE POT WITH MPOT
   ENDIF
   SELECT ANAL
   USE
   SELECT AAAN
   SKIP
ENDDO
SELECT NALP
GO BOTTOM
*------------TRGOVACKA KNJIGA--------------
USE AATM IN 0 
SELECT AATM 
GO TOP
DO WHILE.NOT.EOF()
   MANKON=KONTO
   KTM ='TM'+ALLTRIM(SIFPROD)+'.DBF'
   MDOK='M'+ALLTRIM(SIFPROD)
   USE &KTM IN 0 ORDER 1 ALIAS TM
   SELECT TM
   SEEK MDATDOK

   IF FOUND()
      MPOT=0
      DO WHILE.NOT.EOF()
         IF DATUP<>MDATDOK
            EXIT
         ENDIF
         MPOT=MPOT+UPLACENO
         SKIP
      ENDDO
      SELECT NALP
      IF DUG<>0.OR.POT<>0
         APPEND BLANK
      ENDIF
         REPLACE BRNAL WITH MBRNAL
         REPLACE OPIS WITH MOPIS
         REPLACE DOK WITH MDOK
         REPLACE DATDOK WITH MDATDOK
         REPLACE KONTO WITH MANKON
         REPLACE POT WITH MPOT
   ENDIF
   SELECT TM
   USE
   SELECT AATM
   SKIP
ENDDO
SELECT AATM
USE
SELECT NALP
GO BOTTOM
NALP.GRD0.SETFOCUS
NALP.GRD0.REFRESH
POP KEY
