PUSH KEY CLEAR
   IF RECCOUNT()>0
      MOPIS=OPIS
      MBRNAL=BRNAL
      MDATDOK=DATDOK
      MKONTO=KONTO
      APPEND BLANK
      REPLACE KONTO WITH MKONTO
      REPLACE OPIS WITH MOPIS
      REPLACE BRNAL WITH MBRNAL
      REPLACE DATDOK WITH MDATDOK
      NALP.GRD0.SETFOCUS
      NALP.REFRESH
   ELSE
      APPEND BLANK
   ENDIF   
   NALRASP.GRD0.COLUMN1.SETFOCUS
   NALRASP.REFRESH  
POP KEY