
*------------------UTVRDJIVANJE REZULTATA-------------------------
PROCEDURE NALREZUL
PARAMETERS KONP,KONR,MDAT0,MDAT1,MBRNAL,MOPIS
PUSH KEY CLEAR

KKNALIZV=MDATA01+'\NALIZV'+OPERATER+'.DBF'
KKNALIZVX=MDATA01+'\NALIZV'+OPERATER+'.CDX'
KNALIZV=MDATA01+'\NALIZV'+OPERATER
KNALIZVX=MDATA01+'\NALIZV'+OPERATER

DO IDEL WITH (KKNALIZV)
DO IDEL WITH (KKNALIZVX)
DO IBAZE WITH KNALIZV,'NALIZV'
DO IIND WITH KNALIZV,'KONTO+DTOS(DATDOK)','BRNAL','DTOS(DATDOK)',;
             'KONTO+SIFRA+DTOS(DATDOK)','SIFRA+DTOS(DATDOK)','SIFRA+BRRAC+DTOS(DATDOK)'

DO idel WITH (kkockax)   

SELECT NAL
SET RELATION TO
USE &KNALIZV EXCLU IN 0 ALIAS NALIZV

SELECT NAL
GO TOP
DO WHILE.NOT.EOF()
   IF DATDOK>=MDAT0.AND.DATDOK<=MDAT1
      IF (SUBSTR(KONTO,1,1)=KONR.OR.SUBSTR(KONTO,1,1)=KONP.OR.SUBSTR(KONTO,1,3)='721')
         NMKONTO=KONTO
         NMDUG=DUG
         NMPOT=POT
         NMDATDOK=DATDOK
         SELECT NALIZV
         APPEND BLANK
         REPLACE KONTO WITH NMKONTO
         REPLACE DUG WITH NMDUG
         REPLACE POT WITH NMPOT
         REPLACE DATDOK WITH NMDATDOK
         SELECT NAL
      ENDIF
   ENDIF      
   SKIP
ENDDO
SELECT NALIZV      
INDEX ON KONTO TAG KONTO
SET ORDER TO 1
TOTAL ON KONTO TO &KKOCKA FIELDS DUG,POT
ZAP
USE

USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
SELECT KOCKA
*---------POSLOVNI PRIHODI I RASHODI-------------
GO TOP
MDUG710=0
MDUG711=0
MDUG712=0
MDUG713=0
MPOT710=0
MPOT711=0
MPOT712=0
MPOT713=0
MDUG721=0
MPOT630=0
MPOT631=0
DO WHILE.NOT.EOF()
   *---------710-------------
   IF SUBSTR(KONTO,1,3)='501'
      MDUG710=MDUG710+DUG-POT
   ENDIF
   IF SUBSTR(KONTO,1,3)='511'
       MDUG710=MDUG710+DUG-POT
   ENDIF
   IF SUBSTR(KONTO,1,3)='512'
       MDUG710=MDUG710+DUG-POT
   ENDIF
   IF SUBSTR(KONTO,1,3)='513'
       MDUG710=MDUG710+DUG-POT
   ENDIF
   IF SUBSTR(KONTO,1,2)='52'
       MDUG710=MDUG710+DUG-POT
   ENDIF
   IF SUBSTR(KONTO,1,2)='53'
       MDUG710=MDUG710+DUG-POT
   ENDIF
   IF SUBSTR(KONTO,1,3)='540'
       MDUG710=MDUG710+DUG-POT
   ENDIF
   IF SUBSTR(KONTO,1,3)='541'
       MDUG710=MDUG710+DUG-POT
   ENDIF
   IF SUBSTR(KONTO,1,2)='55'
       MDUG710=MDUG710+DUG-POT
   ENDIF
   IF SUBSTR(KONTO,1,3)='600'
       MPOT710=MPOT710+POT-DUG
   ENDIF
   IF SUBSTR(KONTO,1,3)='601'
       MPOT710=MPOT710+POT-DUG
   ENDIF
   IF SUBSTR(KONTO,1,3)='602'
       MPOT710=MPOT710+POT-DUG
   ENDIF
   IF SUBSTR(KONTO,1,3)='610'
       MPOT710=MPOT710+POT-DUG
   ENDIF
   IF SUBSTR(KONTO,1,3)='611'
       MPOT710=MPOT710+POT-DUG
   ENDIF
   IF SUBSTR(KONTO,1,3)='612'
       MPOT710=MPOT710+POT-DUG
   ENDIF
   IF SUBSTR(KONTO,1,3)='613'
       MPOT710=MPOT710+POT-DUG
   ENDIF

   IF SUBSTR(KONTO,1,2)='62'
       MPOT710=MPOT710+POT-DUG
   ENDIF
   IF SUBSTR(KONTO,1,2)='64'
       MPOT710=MPOT710+POT-DUG
   ENDIF
   IF SUBSTR(KONTO,1,2)='65'
       MPOT710=MPOT710+POT-DUG
   ENDIF
   IF SUBSTR(KONTO,1,3)='630'
       MPOT630=MPOT630+pOT-DUG
   ENDIF
   IF SUBSTR(KONTO,1,3)='631'
       MPOT631=MPOT631-POT+DUG
   ENDIF
   *---------711---------------
   IF SUBSTR(KONTO,1,3)='560'
      MDUG711=MDUG711+DUG-POT
   ENDIF
   IF SUBSTR(KONTO,1,3)='561'
      MDUG711=MDUG711+DUG-POT
   ENDIF
   IF SUBSTR(KONTO,1,3)='562'
      MDUG711=MDUG711+DUG-POT
   ENDIF
   IF SUBSTR(KONTO,1,3)='563'
      MDUG711=MDUG711+DUG-POT
   ENDIF
   IF SUBSTR(KONTO,1,3)='569'
      MDUG711=MDUG711+DUG-POT
   ENDIF

   IF SUBSTR(KONTO,1,3)='660'
      MPOT711=MPOT711+POT-DUG
   ENDIF

   IF SUBSTR(KONTO,1,3)='661'
      MPOT711=MPOT711+POT-DUG
   ENDIF
   IF SUBSTR(KONTO,1,3)='662'
      MPOT711=MPOT711+POT-DUG
   ENDIF
   IF SUBSTR(KONTO,1,3)='663'
      MPOT711=MPOT711+POT-DUG
   ENDIF
   IF SUBSTR(KONTO,1,3)='669'
      MPOT711=MPOT711+POT-DUG
   ENDIF
   *---------712---------------
   IF SUBSTR(KONTO,1,3)='570'
      MDUG712=MDUG712+DUG-POT
   ENDIF
   IF SUBSTR(KONTO,1,3)='571'
      MDUG712=MDUG712+DUG-POT
   ENDIF
   IF SUBSTR(KONTO,1,3)='572'
      MDUG712=MDUG712+DUG-POT
   ENDIF
   IF SUBSTR(KONTO,1,3)='573'
      MDUG712=MDUG712+DUG-POT
   ENDIF
   IF SUBSTR(KONTO,1,3)='574'
      MDUG712=MDUG712+DUG-POT
   ENDIF
   IF SUBSTR(KONTO,1,3)='575'
      MDUG712=MDUG712+DUG-POT
   ENDIF
   IF SUBSTR(KONTO,1,3)='576'
      MDUG712=MDUG712+DUG-POT
   ENDIF
   IF SUBSTR(KONTO,1,3)='577'
      MDUG712=MDUG712+DUG-POT
   ENDIF
   IF SUBSTR(KONTO,1,3)='578'
      MDUG712=MDUG712+DUG-POT
   ENDIF
   IF SUBSTR(KONTO,1,3)='579'
      MDUG712=MDUG712+DUG-POT
   ENDIF

   IF SUBSTR(KONTO,1,3)='670'
      MPOT712=MPOT712+POT-DUG
   ENDIF
   IF SUBSTR(KONTO,1,3)='671'
      MPOT712=MPOT712+POT-DUG
   ENDIF
   IF SUBSTR(KONTO,1,3)='672'
      MPOT712=MPOT712+POT-DUG
   ENDIF
   IF SUBSTR(KONTO,1,3)='673'
      MPOT712=MPOT712+POT-DUG
   ENDIF
   IF SUBSTR(KONTO,1,3)='674'
      MPOT712=MPOT712+POT-DUG
   ENDIF
   IF SUBSTR(KONTO,1,3)='675'
      MPOT712=MPOT712+POT-DUG
   ENDIF
   IF SUBSTR(KONTO,1,3)='676'
      MPOT712=MPOT712+POT-DUG
   ENDIF
   IF SUBSTR(KONTO,1,3)='676'
      MPOT712=MPOT712+POT-DUG
   ENDIF
   IF SUBSTR(KONTO,1,3)='677'
      MPOT712=MPOT712+POT-DUG
   ENDIF
   IF SUBSTR(KONTO,1,3)='678'
      MPOT712=MPOT712+POT-DUG
   ENDIF
   IF SUBSTR(KONTO,1,3)='679'
      MPOT712=MPOT712+POT-DUG
   ENDIF
   *---------713---------------
   IF SUBSTR(KONTO,1,3)='680'
      MPOT713=MPOT713+POT-DUG
   ENDIF
   IF SUBSTR(KONTO,1,3)='681'
      MPOT713=MPOT713+POT-DUG
   ENDIF
   IF SUBSTR(KONTO,1,3)='682'
      MPOT713=MPOT713+POT-DUG
   ENDIF
   IF SUBSTR(KONTO,1,3)='580'
      MDUG713=MDUG713+DUG-POT
   ENDIF
   IF SUBSTR(KONTO,1,3)='581'
      MDUG713=MDUG713+DUG-POT
   ENDIF
   IF SUBSTR(KONTO,1,3)='582'
      MDUG713=MDUG713+DUG-POT
   ENDIF
   IF SUBSTR(KONTO,1,3)='584'
      MDUG713=MDUG713+DUG-POT
   ENDIF
   *----------721------------
   IF SUBSTR(KONTO,1,3)='721'
      MDUG721=MDUG721+DUG-POT
   ENDIF
   SKIP
ENDDO
SELECT KOCKA
USE


USE NALAP IN 0 ALIAS NALAP
SELECT NALAP
M599=MDUG710+MDUG711+MDUG712+MDUG713
M699=MPOT710+MPOT711+MPOT712+MPOT713+MPOT630-MPOT631

MDUG714=0
IF M699>M599
   MDUG714=M699-M599
ELSE
   MDUG714=M599-M699
ENDIF


MDUG720=MDUG714
MDUG723=MDUG720


DO NALREZUL2 WITH '7100',MDUG710,0,MDAT1,MBRNAL,MOPIS
DO NALREZUL2 WITH '7110',MDUG711,0,MDAT1,MBRNAL,MOPIS
DO NALREZUL2 WITH '7120',MDUG712,0,MDAT1,MBRNAL,MOPIS
DO NALREZUL2 WITH '7130',MDUG713,0,MDAT1,MBRNAL,MOPIS
DO NALREZUL2 WITH '5990',0      ,M599,MDAT1,MBRNAL,MOPIS    
DO NALREZUL2 WITH '7100',0      ,MPOT710,MDAT1,MBRNAL,MOPIS 
DO NALREZUL2 WITH '7110',0      ,MPOT711,MDAT1,MBRNAL,MOPIS 
DO NALREZUL2 WITH '7120',0      ,MPOT712,MDAT1,MBRNAL,MOPIS
DO NALREZUL2 WITH '7130',0      ,MPOT713,MDAT1,MBRNAL,MOPIS
DO NALREZUL2 WITH '6990',M699    ,0,MDAT1,MBRNAL,MOPIS

SELECT NALAP 
APPEND BLANK
   REPLACE KONTO WITH '7100'
   IF MDUG710>MPOT710
      REPLACE POT WITH MDUG710-MPOT710
   ELSE
      REPLACE DUG WITH MPOT710-MDUG710
   ENDIF
   DO NALREZUL3 WITH MDAT1,MBRNAL,MOPIS
APPEND BLANK
   REPLACE KONTO WITH '7110'
   IF MDUG711>MPOT711
      REPLACE POT WITH MDUG711-MPOT711
   ELSE
      REPLACE DUG WITH MPOT711-MDUG711
   ENDIF
   DO NALREZUL3 WITH MDAT1,MBRNAL,MOPIS   
APPEND BLANK

   REPLACE KONTO WITH '7120'
   IF MDUG712>MPOT712
      REPLACE POT WITH MDUG712-MPOT712
   ELSE
      REPLACE DUG WITH MPOT712-MDUG712
   ENDIF
   DO NALREZUL3 WITH MDAT1,MBRNAL,MOPIS   
APPEND BLANK

   REPLACE KONTO WITH '7130'
   IF MDUG713>MPOT713
      REPLACE POT WITH MDUG713-MPOT713
   ELSE
      REPLACE DUG WITH MPOT713-MDUG713
   ENDIF
   DO NALREZUL3 WITH MDAT1,MBRNAL,MOPIS   
APPEND BLANK

   REPLACE KONTO WITH '7140'
   IF MDUG714>0
      REPLACE DUG WITH MDUG714
   ELSE
      REPLACE POT WITH -MDUG714
   ENDIF
   DO NALREZUL3 WITH MDAT1,MBRNAL,MOPIS   
APPEND BLANK

   REPLACE KONTO WITH '7140'
   IF MDUG714>0
      REPLACE POT WITH MDUG714
   ELSE
      REPLACE DUG WITH -MDUG714
   ENDIF
   DO NALREZUL3 WITH MDAT1,MBRNAL,MOPIS   
APPEND BLANK

   REPLACE KONTO WITH '7200'
   IF MDUG714>0
      REPLACE DUG WITH MDUG714
   ELSE
      REPLACE POT WITH -MDUG714
   ENDIF
   DO NALREZUL3 WITH MDAT1,MBRNAL,MOPIS   
APPEND BLANK

   REPLACE KONTO WITH '7200'
   IF MDUG714>0
      REPLACE POT WITH MDUG714
   ELSE
      REPLACE DUG WITH -MDUG714
   ENDIF
   DO NALREZUL3 WITH MDAT1,MBRNAL,MOPIS   
APPEND BLANK

   REPLACE KONTO WITH '7230'
   IF MDUG714>0
      REPLACE DUG WITH MDUG714
   ELSE
      REPLACE POT WITH -MDUG714
   ENDIF
   DO NALREZUL3 WITH MDAT1,MBRNAL,MOPIS   
APPEND BLANK

   REPLACE KONTO WITH '7230'
   IF MDUG714>0
      REPLACE POT WITH MDUG714
   ELSE
      REPLACE DUG WITH -MDUG714
   ENDIF
   DO NALREZUL3 WITH MDAT1,MBRNAL,MOPIS   
APPEND BLANK

   REPLACE KONTO WITH '7210'
   REPLACE POT WITH MDUG721
   DO NALREZUL3 WITH MDAT1,MBRNAL,MOPIS   



IF MDUG714-MDUG721>0.AND.M699>M599

   APPEND BLANK
   
   REPLACE KONTO WITH '3410'
   REPLACE POT WITH MDUG714-MDUG721
   DO NALREZUL3 WITH MDAT1,MBRNAL,MOPIS   
ELSE

   IF M699>M599

      APPEND BLANK
   
      REPLACE KONTO WITH '3510'
      REPLACE DUG WITH MDUG721-MDUG714
   DO NALREZUL3 WITH MDAT1,MBRNAL,MOPIS   
   ELSE

      APPEND BLANK

      REPLACE KONTO WITH '2910'
      REPLACE DUG WITH MDUG714+MDUG721
   DO NALREZUL3 WITH MDAT1,MBRNAL,MOPIS         
   ENDIF

ENDIF


SELECT NALAP
USE
SELECT NAL
SET ORDER TO 3
SET RELATION TO BRNAL INTO NALBROJ ADDITIVE
SET RELATION TO KONTO INTO KONTo ADDITIVE
SET RELATION TO MP INTO MESTA ADDITIVE
SET RELATION TO MTR INTO MTR ADDITIVE

GO TOP
POP KEY
ENDPROC





PROCEDURE NALREZUL2
   PARAMETERS MKONTO,MDUG,MPOT,MDAT1,MBRNAL,MOPIS
   PUSH KEY CLEAR

   APPEND BLANK
   REPLACE KONTO WITH MKONTO
   REPLACE DUG WITH MDUG
   REPLACE POT WITH MPOT
   DO NALREZUL3 WITH MDAT1,MBRNAL,MOPIS
   POP KEY
ENDPROC   


PROCEDURE NALREZUL3
   PARAMETERS MDAT1,MBRNAL,MOPIS
PUSH KEY CLEAR
   replace brnal with MBRNAL
   REPLAC DATDOK WITH MDAT1
   REPLACE OPIS WITH MOPIS
POP KEY
ENDPROC   

*------------------ZATVARANJE KLASA------------------------
PROCEDURE NALZAT

PARAMETERS MKONP,MKONR,MDAT0,MDAT1,MBRNAL,MOPIS
PUSH KEY CLEAR


DO idel WITH (kkockax)
DO idel WITH (kkockax2)
DO idel WITH (kkockax3)
DO idel WITH (kkockax4)

SELECT NAL
SET RELATION TO

KKNALIZV=MDATA01+'\NALIZV'+OPERATER+'.DBF'
KKNALIZVX=MDATA01+'\NALIZV'+OPERATER+'.CDX'
KNALIZV=MDATA01+'\NALIZV'+OPERATER
KNALIZVX=MDATA01+'\NALIZV'+OPERATER


DO IDEL WITH (KKNALIZV)
DO IDEL WITH (KKNALIZVX)
DO IBAZE WITH KNALIZV,'NALIZV'
DO IIND WITH KNALIZV,'KONTO+DTOS(DATDOK)','BRNAL','DTOS(DATDOK)',;
             'KONTO+SIFRA+DTOS(DATDOK)','SIFRA+DTOS(DATDOK)','SIFRA+BRRAC+DTOS(DATDOK)'

USE &KNALIZV IN 0 EXCLU ALIAS NALIZV

SELECT NAL
COPY TO &KKOCKA FOR (SUBSTR(KONTO,1,1))=mkonr.AND.(SUBSTR(KONTO,1,3)<>'599').and.DATDOK>=MDAT0.AND.DATDOK<=MDAT1
COPY TO &KKOCKA2 FOR (SUBSTR(KONTO,1,1))=MKONP.AND.(SUBSTR(KONTO,1,3)<>'699').and.DATDOK>=MDAT0.AND.DATDOK<=MDAT1

USE &kkocka IN 0 ALIAS kocka EXCLUSIVE
SELECT kocka
INDEX on konto TAG konto
SET ORDER TO 1
TOTAL ON KONTO TO &KKOCKA3 FIELDS DUG,POT
ZAP
APPEND FROM &kkocka3
replace ALL dug WITH dug-pot
replACE ALL pot WITH 0
USE

USE &kkocka2 IN 0 ALIAS kocka2 EXCLUSIVE
SELECT kocka2
INDEX on konto TAG konto
SET ORDER TO 1
TOTAL ON KONTO TO &KKOCKA4 FIELDS DUG,POT
ZAP
APPEND FROM &kkocka4
replace ALL pot WITH pot-dug
replACE ALL dug WITH 0
USE
SELECT nalizv
APPEND FROM &kkocka
APPEND FROM &kkocka2
REPLACE all DATDOK WITH mdat1
replace all brnal with mbrnal
replace ALL opis with mopis
*---------POSLOVNI PRIHODI I RASHODI-------------
GO TOP
DO WHILE.NOT.EOF()
    IF DUG<>0
       REPLACE POT WITH DUG
       REPLACE DUG WITH 0
    ELSE
       REPLACE DUG WITH POT
       REPLACE POT WITH 0
    ENDIF
    SKIP
ENDDO

SUM ALL DUG TO MDUG
SUM ALL POT TO MPOT
USE

USE NALaP IN 0 EXCLU ALIAS NALAP
SELECT NALAP
APPEND FROM &KNALIZV
   APPEND BLANK
   REPLACE KONTO WITH '6990'
   REPLACE POT WITH MDUG
   REPLACE DATDOK WITH mdat1
   replace brnal with mbrnal
   replace opis with mopis
   
   APPEND BLANK
   REPLACE KONTO WITH '5990'
   REPLACE DUG WITH MPOT
   REPLACE DATDOK WITH mdat1
   replace brnal with mbrnal
   replace opis with mopis
 
use
SELECT NAL
SET ORDER TO 3
POP KEY
endproc


*------------------ZATVARANJE AKTIVE I PASIVE-----------------------
PROCEDURE NALZATA

PARAMETERS MDAT0,MDAT1,MBRNAL,MOPIS
PUSH KEY CLEAR

DO idel WITH (kkockax)

SELECT NAL
SET RELATION TO

KKNALIZV=MDATA01+'\NALIZV'+OPERATER+'.DBF'
KKNALIZVX=MDATA01+'\NALIZV'+OPERATER+'.CDX'
KNALIZV=MDATA01+'\NALIZV'+OPERATER
KNALIZVX=MDATA01+'\NALIZV'+OPERATER

DO IDEL WITH (KKNALIZV)
DO IDEL WITH (KKNALIZVX)
DO IBAZE WITH KNALIZV,'NALIZV'
DO IIND WITH KNALIZV,'KONTO+DTOS(DATDOK)','BRNAL','DTOS(DATDOK)',;
             'KONTO+SIFRA+DTOS(DATDOK)','SIFRA+DTOS(DATDOK)','SIFRA+BRRAC+DTOS(DATDOK)'

USE &KNALIZV IN 0 EXCLU ALIAS NALIZV

SELECT NAL
GO TOP
DO WHILE.NOT.EOF()
   IF DATDOK>=MDAT0.AND.DATDOK<=MDAT1
         NMKONTO=KONTO
         NMDUG=DUG
         NMPOT=POT
         NMDATDOK=DATDOK
         SELECT NALIZV
         APPEND BLANK
         REPLACE KONTO WITH NMKONTO
         REPLACE DUG WITH NMDUG
         REPLACE POT WITH NMPOT
         REPLACE DATDOK WITH mdat1
         replace brnal with mbrnal
         replace opis with mopis
         SELECT NAL
   ENDIF      
   SKIP
ENDDO
SELECT NALIZV      
INDEX ON KONTO TAG KONTO
SET ORDER TO 1
TOTAL ON KONTO TO &KKOCKA FIELDS DUG,POT
ZAP
USE

USE &KKOCKA IN 0 EXCLU ALIAS KOCKA
SELECT KOCKA
*---------POSLOVNI PRIHODI I RASHODI-------------
REPLACE ALL DUG WITH DUG-POT
REPLACE ALL POT WITH 0
GO TOP
DO WHILE.NOT.EOF()
    IF DUG>0
       REPLACE POT WITH DUG
       REPLACE DUG WITH 0
    ELSE
       REPLACE DUG WITH ABS(DUG)
       REPLACE POT WITH 0
    ENDIF
    SKIP
ENDDO

SUM ALL DUG TO MDUG
SUM ALL POT TO MPOT
USE

USE NALaP IN 0 EXCLU ALIAS NALAP
SELECT NALAP
APPEND FROM &KKOCKA
   APPEND BLANK
   REPLACE KONTO WITH '7300'
   REPLACE POT WITH MDUG
   REPLACE DATDOK WITH mdat1
   replace brnal with mbrnal
   replace opis with mopis
   
   APPEND BLANK
   REPLACE KONTO WITH '7300'
   REPLACE DUG WITH MPOT
   REPLACE DATDOK WITH mdat1
   replace brnal with mbrnal
   replace opis with mopis
 
use
SELECT NAL
SET ORDER TO 3
POP KEY
endproc