USE NALAP IN 0 
SELECT NALRASP
GO TOP
DO WHILE.NOT.EOF()
   MKONTO=K9
   MDATDOK=DATDOK
   MDUG=DUG
   MPOT=POT
   MBRNAL=BRNAL
   SELECT NALAP
   APPEND BLANK
   REPLACE KONTO WITH MKONTO
   REPLACE DATDOK WITH MDATDOK
   REPLACE DUG WITH MDUG
   REPLACE POT WITH MPOT
   REPLACE BRNAL WITH MBRNAL
   SELECT NALRASP
   SKIP
ENDDO
SELECT NALAP
USE
SELECT NALRASP
GO TOP