PARAMETERS SVE
PUSH KEY CLEAR
SET EXACT ON

KKNALIZV=MDATA01+'\NALIZV'+OPERATER+'.DBF'
KKNALIZVX=MDATA01+'\NALIZV'+OPERATER+'.CDX'
KNALIZV=MDATA01+'\NALIZV'+OPERATER
KNALIZVX=MDATA01+'\NALIZV'+OPERATER


DO IDEL WITH (KKNALIZV)
DO IDEL WITH (KKNALIZVX)
DO IBAZE WITH KNALIZV,'NALIZV'
DO IIND WITH KNALIZV,'KONTO+DTOS(DATDOK)','BRNAL','DTOS(DATDOK)',;
             'KONTO+SIFRA+DTOS(DATDOK)','SIFRA+DTOS(DATDOK)','SIFRA+BRRAC+DTOS(DATDOK)'

USE &KNALIZV IN 0 ALIAS NALIZV EXCLUSIVE 

   DO idel WITH (kkockax)   
   DO idel WITH (kkockax2)   
   DO idel WITH (kkockax3)   
   DO idel WITH (kkockax4)   
   DO idel WITH (kkockax5)   
   
SELECT NALIZV   
COPY STRUCTURE TO &KKOCKA   
COPY STRUCTURE TO &KKOCKA3   
USE
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
*USE TMP0 IN 0
SELECT TMP
COPY TO &KKOCKA2 FOR MALVRED<>0
*USE   

*----------------KNJIGA PRIHODA-------------------
USE &KKOCKA2 IN 0 ALIAS KOCKA2 EXCLU
SELECT KOCKA2
INDEX ON BRNAL  TAG BRNAL
TOTAL ON BRNAL FIELDS MALVRED TO &KKOCKA3
ZAP
APPEND FROM &KKOCKA3
SET ORDER TO 1
GO TOP
DO WHILE.NOT.EOF()
   MBRNAL=BRNAL
   MDUG=MALVRED
   MKONTO=KONTO
   MBRNAL=BRNAL
   MDATDOK=DATDOK
   SELECT KOCKA
   APPEND BLANK
   REPLACE BRNAL WITH MBRNAL
   REPLACE DUG WITH MDUG
   REPLACE KONTO WITH MKONTO
   REPLACE DATDOK WITH MDATDOK
   SELECT KOCKA2
   SKIP
ENDDO   
SELECT KOCKA2
USE
*----------------GLAVNA KNJIGA--------------------
USE NAL IN 0
SELECT NAL
COPY TO &KKOCKA4 FOR (SUBSTR(konto,1,5)='13400'.OR.SUBSTR(konto,1,5)='13200';
                  .OR.SUBSTR(konto,1,5)='10100'.OR.SUBSTR(konto,1,5)='12000').AND.DUG<>0
USE
USE &KKOCKA4 IN 0 ALIAS KOCKA4 EXCLU
SELECT KOCKA4
INDEX ON BRNAL  TAG BRNAL
SET ORDER TO 1
SELECT KOCKA
GO TOP
DO WHILE.NOT.EOF()
   MBRNAL=BRNAL
   mdatdok=datdok
   SELECT KOCKA4
   SEEK MBRNAL
   IF FOUND()
      MDUG=0
      MPOT=0
      DO WHILE.NOT.EOF()
         IF BRNAL<>MBRNAL 
            EXIT
         ENDIF   
         MDUG=MDUG+DUG
         REPLACE KONTO WITH '9999999999'
         SKIP
      ENDDO      
      SELECT KOCKA
      REPLACE UDUG WITH MDUG
   ENDIF 
   SELECT KOCKA
   SKIP
ENDDO
SELECT KOCKA4
DELETE ALL FOR KONTO='9999999999'
PACK
IF RECCOUNT()>0
   GO TOP
   DO WHILE.NOT.EOF()
      MKONTO=KONTO
      MBRNAL=BRNAL
      MUDUG=DUG-POT
      MDATDOK=DATDOK
      SELECT KOCKA
      APPEND BLANK
      REPLACE BRNAL WITH MBRNAL
      REPLACE UDUG WITH MUDUG
      REPLACE DATDOK WITH MDATDOK
      REPLACE KONTO WITH MKONTO
      SELECT KOCKA4
      SKIP
   ENDDO   
ENDIF      
SELECT KOCKA4
USE
SELECT KOCKA
GO TOP
DO WHILE.NOT.EOF()
   REPLACE SALDO WITH DUG-POT
   REPLACE USALDO WITH UDUG-UPOT
   REPLACE DSALDO WITH SALDO-USALDO
   SKIP
ENDDO   
GO TOP
TNAZIV=' KNJIGA PRIHODA I RASHODA SLAGANJE ZADUZENJA '
TOBJEKAT='0'
TTVREDNI='0'
*REPORT FORM TVGKSLAG PREVIEW FOR ABS(DSALDO)>1
   mfile='TVGKSLAG'
   uslov="ABS(DSALDO)>1"
   DO printer_bullzip WITH mdata02,mfile,uslov

SELECT kocka
USE
SELECT TMP
SET EXACT OFF
POP KEY