PUSH KEY CLEAR
IF NALB='100'
   SELECT NALVRSTA
   MREC=RECNO()
   USE
   USE &KNALVRSTA ALIAS NALVRSTA EXCLU IN 0
   SELECT NALVRSTA
   GOTO MREC
   IF MREC>0.AND.MREC=RECCOUNT()
      DELETE 
      PACK
   ENDIF
   NALVRSTA.RELEASE
   KEYBOARD '{ENTER}'
ENDIF   
POP KEY
