PUSH KEY CLEAR
   SELECT CALC
   GO BOTTOM
   IF RECCOUNT()<1
      MBROJ=1
   ELSE
      MBROJ=BROJ
   ENDIF      
   APPEND BLANK
   REPLACE BROJ WITH MBROJ
   REPLACE ZNAK WITH '+'
   NCALC.GRD0.SetFocus
   NCALC.GRD0.column2.SetFocus
   NCALC.GRD0.REFRESH
   NCALC.grd0.setfocus   
POP KEY