PUSH KEY CLEAR
   SELECT NIV
   MBRKAL=BRKAL
   MBRNAL=BRNAL
IF MBRNAL<>SPACE(6)

IF ARHIVA=' '
   SELECT NIV
   MBRKAL=BRKAL
   MBRNAL=BRNAL
   NIV.GRD0.COLUMN1.SETFOCUS
   SELECT NIV
   MBRKAL=BRKAL
   SET RELATION TO
   USE
   USE &KTVNIV EXCLU IN 0 ALIAS NIV 
   SELECT NIV
   DELETE ALL FOR BRKAL=MBRKAL
   PACK
   USE
   *----------BRISANJE IZ GOTOVIH NALOGA---------
   USE NALAP IN 0 ORDER 2
   SELECT NALAP
   SEEK MBRNAL
   IF FOUND()
      DO WHILE.NOT.EOF()
         IF BRNAL<>MBRNAL
            EXIT
         ENDIF
         REPLACE KONTO WITH 'B'
         REPLACE DUG WITH 0
         REPLACE POT WITH 0
         REPLACE DEVDUG WITH 0
         REPLACE DEVPOT WITH 0   
         SKIP
      ENDDO   
   ENDIF  
   SELECT NALAP
   USE
   *----------BRISANJE IZ GLAVNE KNJIGE--------
   USE NAL IN 0 ORDER 2
   SELECT NAL
   SEEK MBRNAL
   IF FOUND()
      DO WHILE.NOT.EOF()
         IF BRNAL<>MBRNAL
            EXIT
         ENDIF
         REPLACE KONTO WITH 'B'
         REPLACE DUG WITH 0
         REPLACE POT WITH 0
         REPLACE DEVDUG WITH 0
         REPLACE DEVPOT WITH 0   
         SKIP
      ENDDO   
   ENDIF  
   SELECT NAL
   USE
   *----------BRISANJE IZ KEPU I TRGOVACKE---------
   IF TOBJEKAT='V'
      KTM='TVTM'+TTVREDNI+'.DBF'
   ELSE
      KTM='TM'+TTVREDNI+'.DBF'
   ENDIF   
   USE &KTM IN 0 ORDER 3 ALIAS TM
   SELECT TM
   SEEK MBRNAL
   IF FOUND()
      DO WHILE.NOT.EOF()
         IF BRNAL<>MBRNAL
            EXIT
         ENDIF
         REPLACE OPIS WITH 'BRISANO'
         REPLACE UKNAB WITH 0
         REPLACE VREDPROD WITH 0
         SKIP
      ENDDO   
   ENDIF  
   SELECT TM
   USE
   *----------BRISANJE IZ KNJIGE PRIHODA--------
   USE TMP0 IN 0 ORDER 3 ALIAS TMP
   SELECT TMP
   SEEK MBRNAL
   IF FOUND()
      DO WHILE.NOT.EOF()
         IF BRNAL<>MBRNAL
            EXIT
         ENDIF
         REPLACE OPIS WITH 'BRISANO'
         REPLACE NABVRED WITH 0
         REPLACE SOPVRED WITH 0
         REPLACE MARZA WITH 0
         REPLACE POREZ WITH 0
         REPLACE PLACPOR WITH 0
         REPLACE MALVRED WITH 0
         SKIP
      ENDDO   
   ENDIF  
   SELECT TMP
   USE
ENDIF
ENDIF
NIVSERV.RELEASE
NIV.RELEASE
POP KEY
KEYBOARD '{ENTER}'
