PUSH KEY clear
NIV.GRD0.COLUMN1.SETFOCUS

SELECT NIV
SET ORDER TO 
IF RECCOUNT()>0
   *---AKO KALKULACIJA POSTOJI
   IF ARHIVA=' '
      *---AKO NIJE ARHIVIRANA-----
      MBRKAL=BRKAL
      MDATDOK=DATDOK
      MBRNAL=BRNAL
      MSEMA=SEMA
      MKONTO=KONTO
      MKONTOS=KONTOS
      MKONTOK=KONTOK
      
      APPEND BLANK
      REPLACE BRKAL WITH MBRKAL 
      REPLACE DATDOK WITH MDATDOK
      REPLACE BRNAL WITH MBRNAL
      REPLACE SEMA WITH MSEMA
      REPLACE KONTO WITH KONTO
      REPLACE KONTOS WITH KONTOS
      REPLACE KONTOK WITH KONTOK            
      NIV.GRD0.SETFOCUS
      NIV.REFRESH
   ELSE
      *------AKO JE KALKULACIJA  ARHIVIRANA
      SELECT NIV
      GO BOTTOM
      MBRKAL=BRKAL
      MNLEN=LEN(ALLTRIM(STR(VAL(ALLTRIM(SUBSTR(MBRKAL,2,5)))+1,5,0)))
      MNBRKAL='N'+REPLI('0',5-MNLEN)+ALLTRIM(STR(VAL(ALLTRIM(SUBSTR(MBRKAL,2,5)))+1,5,0))
      SET ORDER TO 1
            LOCATE FOR BRKAL=MNBRKAL

      IF.NOT.FOUND()
         SET ORDER TO
         APPEND BLANK
         GO BOTTOM
         REPLACE BRKAL WITH MNBRKAL 
         REPLACE DATDOK WITH DATE()
         niv.refresh
      ENDIF
      IF ARHIVA=' '
      DO  FORM NIVZAG
      ENDIF   
   ENDIF 
   SELECT NIV
   SET ORDER TO 
   GO BOTTOM
ELSE
   *--------AKO PRVA STAVKA NE POSTOJI---------
   SET ORDER TO 
   APPEND BLANK
   GO BOTTOM
   niv.grd0.refresh
   MNBRKAL='N00001'
   REPLACE BRKAL WITH MNBRKAL 
   REPLACE DATDOK WITH DATE()
   *------IDEMO U ZAGLAVLJE
   IF .NOT.FOUND()
      DO  FORM NIVZAG
   ENDIF   
ENDIF    


SELECT NIV
SET ORDER TO 
GO bottom
IF EOF()
   SKIP -1
endif   
POP key
NIV.GRD0.COLUMN3.SETFOCUS
*NIV.REFRESH  
