PUSH KEY CLEAR
SELECT NIV
mnbrkal=brkal
IF ARHIVA=' '
   IF ALLTRIM(OPER)=AAOPER
   SELECT NIV
   SET RELATION TO
   SELECT NIV
         LOCATE FOR BRKAL=MNBRKAL
   IF.NOT.FOUND()
      APPEND BLANK
      REPLACE BRKAL WITH MNBRKAL
      REPLACE OPER WITH AAOPER
   ENDIF      
   DO FORM NIVZAG
   SELECT KAL
   APPEND BLANK
   REPLACE BRKAL WITH MNBRKAL
   SET ORDER TO 1
   LOCATE FOR BRKAL=MNBRKAL

   SET RELATION TO RSIF INTO ROB ADDITIVE
*   REPLACE DATDOK WITH KALG.DATDOK    
   SET ORDER TO 
   GO BOTTOM
   NIVNOVA.RELEASE
   NIV.grd0.setfocus
   NIV.refresh
   ELSE
      PUBLIC PPORUKA
      PPORUKA=' NIVELACIJU '+MNBRKAL+' JE OTVORIO DRUGI OPERATER-OTVORITE NOVU '
      DO PORUKA
   ENDIF   
ELSE
   PUBLIC PPORUKA
   PPORUKA=' NIVELACIJA '+MNBRKAL+' JE PROKNJIZENA  OTVORITE NOVU '
   DO PORUKA
ENDIF
POP KEY