PUSH KEY CLEAR
*SET STEP ON
NIVNOVA.GRD0.RECORDSOURCE=''
SELECT magg
GO BOTTOM
MBRKAL=SUBSTR(BRKAL,2,5)
MMREC=RECCOUNT()
*use
MNLEN=LEN(ALLTRIM(STR(VAL(ALLTRIM(MBRKAL))+1,5,0)))
MNBRKAL='N'+REPLI('0',5-MNLEN)+ALLTRIM(STR(VAL(ALLTRIM(MBRKAL))+1,5,0))
SELECT MAGg
LOCATE FOR BRKAL=MNBRKAL
IF.NOT.FOUND()
   APPEND BLANK
   REPLACE BRKAL WITH MNBRKAL
   REPLACE OPER WITH AAOPER
ENDIF
SELECT MAGG
SCATTER NAME POLJA
SELECT NIV
APPEND BLANK
GATHER NAME POLJA
SELECT MAGG
NIVNOVA.GRD0.RECORDSOURCE='MAGG'
NIVNOVA.GRD0.COLUMN1.CONTROLSOURCE='BRKAL'
NIVNOVA.GRD0.SETFOCUS
NIVNOVA.REFRESH
POP KEY
