PUSH KEY CLEAR
SELECT NIV
GO BOTTOM
MBRKAL=BRKAL
MNLEN='N'+LEN(ALLTRIM(STR(VAL(ALLTRIM(MBRKAL))+1,5,0)))
MNBRKAL='N'+REPLI('0',5-MNLEN)+ALLTRIM(STR(VAL(ALLTRIM(MBRKAL))+1,5,0))
APPEND BLANK
REPLACE BRKAL WITH MNBRKAL
REPLACE OPER WITH AAOPER
NIVNOVA.GRD0.SETFOCUS
POP KEY
NIVNOVA.REFRESH