PUSH KEY CLEAR
   REPLACE SIZNOS WITH KOL*SCENA
   REPLACE VELVRED WITH KOL*VELCENA
   REPLACE MALVRED WITH KOL*MALCENA
     IF TOBJEKAT='V'
         REPLACE POREZ WITH ROUND(VELVRED*PROCPOR/(100),2)
         REPLACE SPOREZ WITH ROUND(SIZNOS*SPROCPOR/(100),2)      
         REPLACE RAZLPOR WITH POREZ-SPOREZ
      ELSE
         REPLACE POREZ WITH ROUND(MALVRED*PROCPOR/(100+PROCPOR),2)
         REPLACE SPOREZ WITH ROUND(SIZNOS*SPROCPOR/(100+SPROCPOR),2)      
         REPLACE RAZLPOR WITH POREZ-SPOREZ
         REPLACE VELVRED WITH 0
         REPLACE VELCENA WITH 0
      ENDIF       
     IF TFPDV='N'
         REPLACE POREZ WITH 0
         REPLACE SPOREZ WITH 0      
         REPLACE RAZLPOR WITH 0
     ENDIF     
       
   IF TOBJEKAT='M'
      REPLACE MARZA WITH MALVRED-SIZNOS-RAZLPOR
   ELSE
      REPLACE MARZA WITH VELVRED-SIZNOS
   ENDIF
   IF SIZNOS<>0
      REPLACE MARPROC WITH ROUND(MARZA*100/SIZNOS,5)
   ELSE
      REPLACE MARZA WITH 0
      REPLACE MARPROC WITH 0
   ENDIF
POP KEY   
