PUSH KEY CLEAR
   DO idel WITH (kkockax)
CLOSE ALL
USE &KTVNIV IN 0 ALIAS NIV EXCLUSIVE
SELECT NIV
SORT ON BRKAL TO &KKOCKA
DELETE ALL
PACK

APPEND FROM &KKOCKA
NIVSERV.RELEASE
NIV.RELEASE
POP KEY
KEYBOARD '{ENTER}'
