PUSH KEY CLEAR
NIV.GRD0.COLUMN1.SETFOCUS
MBRKAL=BRKAL
*REPORT FORM NIV0podnaz  FOR BRKAL=MBRKAL PREVIEW 
   mfile='NIV0podnaz'
   uslov="BRKAL=MBRKAL"
   DO printer_bullzip WITH mdata02,mfile,uslov

POP KEY
