PUSH KEY CLEAR
SET century on
NIV.GRD0.COLUMN1.SETFOCUS
MBRKAL=BRKAL
*REPORT FORM NIV0ODLUKA  FOR BRKAL=MBRKAL PREVIEW 
   mfile='NIV0ODLUKA'
   uslov="BRKAL=MBRKAL"
   DO printer_bullzip WITH mdata02,mfile,uslov

SET CENTURY off
POP KEY
