PUSH KEY CLEAR
IF PPASAN=1
   SET ORDER TO 
   IF RECCOUNT()>0
      APPEND BLANK
      OBRKONS.GRD0.SETFOCUS
      OBRKONS.REFRESH
   ELSE
      APPEND BLANK
   ENDIF
   OBRKONS.GRD0.COLUMN1.SETFOCUS
   OBRKONS.REFRESH  
ELSE
   PUBLIC PPORUKA
   PPORUKA=' NEMATE PRAVO DODAVANJA POLJA '
   DO PORUKA 
ENDIF
POP KEY