PUSH KEY CLEAR
SELECT OS0
SET ORDER TO 
IF RECCOUNT()<1
APPEND BLANK
REPLACE OSIFRA WITH STR(RECNO(),4,0)
ELSE
GO BOTTOM
MOSIFRA=VAL(OSIFRA)+1
APPEND BLANK
REPLACE OSIFRA WITH STR(MOSIFRA,4,0)
ENDIF
OS0.GRD0.SETFOCUS
OS0.GRD0.REFRESH
POP KEY
OS0.REFRESH
