PUSH KEY CLEAR
      GO TOP
      DO WHILE.NOT.EOF()
         REPLACE SAD0 WITH NAB0-ISP0
         REPLACE SAD02 WITH NAB02-ISP02
         *----------PREMA PORESKIM PROPISIMA
         IF NAB02<>0
            REPLACE SAD02 WITH NAB02-ISP02
            IF AG='1' 
               MAMORT=ROUND(NAB02*STOPAOT2*BRMES/(12*100),2)
            ELSE
               MAMORT=ROUND(SAD02*STOPAOT2*BRMES/(12*100),2)
            ENDIF
            IF ABS(MAMORT)>ABS(NAB02)-ABS(ISP02)
               MMAMORT=SAD02
            ELSE
               MMAMORT=MAMORT
            ENDIF
            REPLACE AMORT2 WITH MMAMORT
         ELSE
            REPLACE AMORT2 WITH 0
         ENDIF


         IF ABS(ISP02)+ABS(AMORT2)>ABS(NAB02)
            REPLACE AMORT2 WITH NAB02-ISP02
         ENDIF

         REPLACE NAB2 WITH NAB02
         REPLACE ISP2 WITH ISP02+AMORT2
         REPLACE SAD2 WITH NAB2-ISP2

         *----------PREMA M R STANDARDIMA

         IF NAB0<>0
            IF PROCGOD<>0
               MAMORT=ROUND((SAD0)*STOPAOT*BRMES/(12*PROCGOD*100),2)
            ELSE
               MAMORT=ROUND((NAB0)*STOPAOT*BRMES/(12*100),2)
            ENDIF
            IF ABS(MAMORT)>ABS(NAB0)-ABS(ISP0)
               MMAMORT=SAD0
            ELSE
               MMAMORT=MAMORT
            ENDIF
            REPLACE AMORT WITH MMAMORT
         ELSE
            REPLACE AMORT WITH 0
         ENDIF


         IF ABS(ISP0)+ABS(AMORT)>ABS(NAB0)
            REPLACE AMORT WITH NAB0-ISP0
         ENDIF

         REPLACE NAB WITH NAB0
         REPLACE ISP WITH ISP0+AMORT
         REPLACE SAD WITH NAB-ISP
      SKIP
   ENDDO
POP KEY