PUSH KEY CLEAR
SELECT OSPOPIS
   DO idel WITH (kkockax)

USE FIRMA IN 0
SELECT OS
SET ORDER TO 3
TOTAL ON KONTO FIELDS NAB0,ISP0,SAD0,NAB02,ISP02,SAD02,NAB,ISP,SAD,NAB2,ISP2,SAD2,AMORT,AMORT2 TO &KKOCKA
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
SELECT KOCKA

*REPORT FORM OSPOPIS30 PREVIEW 

   mfile='OSPOPIS30' 
   uslov=""
   DO printer_bullzip WITH mdata02,mfile,uslov



SELECT KOCKA
USE
SELECT FIRMA
USE
SELECT OS
SET ORDER TO 
SELECT OSPOPIS
POP KEY