PUSH KEY CLEAR
SELECT OSPOPIS
   DO idel WITH (kkockax)
   DO idel WITH (kkockax2)
USE FIRMA IN 0
SELECT OS
SET ORDER TO 3
COPY TO &kkocka
USE &kkocka IN 0 ALIAS kocka EXCLUSIVE
SELECT kocka
INDEX on SUBSTR(konto,1,3) TAG kocka
TOTAL ON SUBSTR(konto,1,3) FIELDS NAB0,ISP0,SAD0,NAB02,ISP02,SAD02,NAB,ISP,SAD,NAB2,ISP2,SAD2,AMORT,AMORT2 TO &KKOCKA2
use
USE &KKOCKA2 IN 0 ALIAS KOCKA EXCLU
SELECT KOCKA
*REPORT FORM OSPOPIS30sin PREVIEW 

   mfile='OSPOPIS30SIN' 
   uslov=""
   DO printer_bullzip WITH mdata02,mfile,uslov


SELECT KOCKA
USE
SELECT FIRMA
USE
SELECT OS
SET ORDER TO 
SELECT OSPOPIS
POP KEY