PARAMETERS MKONTO
PUSH KEY CLEAR

SELECT OSPOPIS
   DO idel WITH (kkockax)

USE FIRMA IN 0
SELECT OS
SET ORDER TO 5
TOTAL ON MESTO FIELDS NAB0,ISP0,SAD0,NAB02,ISP02,SAD02,NAB,ISP,SAD,NAB2,ISP2,SAD2,AMORT,AMORT2 TO &KKOCKA FOR KONTO=MKONTO.OR.MKONTO=SPACE(8)
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
PUBLIC AKONTO
AKONTO=MKONTO
SELECT KOCKA

*REPORT FORM OSPOPIS310 PREVIEW 

   mfile='OSPOPIS310' 
   uslov=""
   DO printer_bullzip WITH mdata02,mfile,uslov


SELECT KOCKA
USE
SELECT FIRMA
USE
SELECT OS
SET ORDER TO 
SELECT OSPOPIS
POP KEY