PUSH KEY CLEAR
SELECT OSPODACI
MEDAT0=EDAT0
SELECT OSPOPIS
   DO idel WITH (kkockax)

USE FIRMA IN 0
SELECT OS
SET ORDER TO 3
TOTAL ON KONTO FIELDS NAB0,ISP0,SAD0 TO &KKOCKA FOR DATNAB<MEDAT0
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
SELECT KOCKA

*REPORT FORM OSPOPIS40 PREVIEW 
   mfile='OSPOPIS40' 
   uslov=""
   DO printer_bullzip WITH mdata02,mfile,uslov


SELECT KOCKA
USE
SELECT FIRMA
USE
SELECT OS
SET ORDER TO 
SELECT OSPOPIS
POP KEY
