PUSH KEY CLEAR
IF PPASAN<>1
   PUBLIC PPORUKA
   PPORUKA=' NEMATE PRAVO NA OVU OPERACIJU '
   DO PORUKA 
ELSE
   AN.GRD0.SetAll("DynamicBackColor", "IIF(ANALP.ZATVAR=' ', RGB(255,255,255), RGB(255,255,255))", "Column")  
   AN.GRD0.ReadOnly=.F.
*   AN.GRD0.BACKCOLOR=RGB(255,255,255)
   AN.GRD0.SetFocus
   AN.Refresh 
ENDIF   
POP KEY