PUSH KEY CLEAR
*IF PPASMP<>1
*   PUBLIC PPORUKA
*   PPORUKA=' NEMATE PRAVO NA OVU OPERACIJU '
*   DO PORUKA 
*ELSE
   IF TM.GRD0.READONLY=.T.
      TM.GRD0.READONLY=.F.
      TM.GRD0.BACKCOLOR=RGB(255,255,255)
      TM.GRD0.SETFOCUS
   ELSE
      TM.GRD0.READONLY=.T.
      TM.GRD0.SETFOCUS
   ENDIF
*ENDIF   
POP KEY