PUSH KEY CLEAR
*IF PPASMP<>1
*   PUBLIC PPORUKA
*   PPORUKA=' NEMATE PRAVO NA OVU OPERACIJU '
*   DO PORUKA 
*ELSE
   IF TMPAZARS.GRD0.READONLY=.T.
      TMPAZARS.GRD0.READONLY=.F.
      TMPAZARS.GRD0.BACKCOLOR=RGB(255,255,255)
      TMPAZARS.GRD0.SETFOCUS
   ELSE
      TMPAZARS.GRD0.READONLY=.T.
      TMPAZARS.GRD0.SETFOCUS
   ENDIF
*ENDIF   
POP KEY