PUSH KEY CLEAR
   SELECT PCEV
   SET RELATION TO
   USE
   DO CASE MAMENI
   CASE MAMENI=1
      USE PCEV IN 0 EXCLU ALIAS PCEV
   CASE MAMENI=2
      USE PCEVO IN 0 EXCLU ALIAS PCEV
   CASE MAMENI=3
      USE PCEVME IN 0 EXCLU ALIAS PCEV
   CASE MAMENI=4
      USE PCEVOD IN 0 EXCLU ALIAS PCEV
   CASE MAMENI=5
      USE PCEVTR IN 0 EXCLU ALIAS PCEV
   CASE MAMENI=6
      USE PCEVRD IN 0 EXCLU ALIAS PCEV
   CASE MAMENI=7
      USE PCEVTZ IN 0 EXCLU ALIAS PCEV
   ENDCASE
   SELECT PCEV
   DELETE ALL FOR KOL=0
   PACK
   USE
PCEVSERV.RELEASE
POP KEY