PUSH KEY CLEAR
PUBLIC MREDREC,MREDZAD
SELECT PCEV
SET ORDER TO
SET RELATION TO
MREDREC=RECNO()
MREDZAD=RECCOUNT()
MBRKAL=BRKAL
DO FORM ROBA
SELECT PCEV
SET ORDER TO 1
LOCATE FOR BRKAL=MBRKAL

SET ORDER TO 
GOTO MREDREC
SELECT PCEV
SET RELATION TO BRKAL INTO PCEVG  ADDITIVE
SET RELATION TO RSIF INTO ROB ADDITIVE
PCEV.GRD0.COLUMN1.SETFOCUS
POP KEY
