PUSH KEY CLEAR
CLOSE ALL
DO CASE MAMENI 
CASE MAMENI=1
   USE PCEV IN 0 ORDER 1 ALIAS PCEV EXCLU
   USE PCEVG IN 0 ORDER 1 ALIAS PCEVG EXCLU
CASE MAMENI=2
   USE PCEVO IN 0 ORDER 1 ALIAS PCEV EXCLU
   USE PCEVOG IN 0 ORDER 1 ALIAS PCEVG EXCLU
CASE MAMENI=3
   USE PCEVME IN 0 ORDER 1 ALIAS PCEV EXCLU
   USE PCEVMEG IN 0 ORDER 1 ALIAS PCEVG EXCLU
CASE MAMENI=4
   USE PCEVOD IN 0 ORDER 1 ALIAS PCEV EXCLU
   USE PCEVODG IN 0 ORDER 1 ALIAS PCEVG EXCLU
CASE MAMENI=5
   USE PCEVTR IN 0 ORDER 1 ALIAS PCEV EXCLU
   USE PCEVTRG IN 0 ORDER 1 ALIAS PCEVG EXCLU
CASE MAMENI=6
   USE PCEVRD IN 0 ORDER 1 ALIAS PCEV EXCLU
   USE PCEVRDG IN 0 ORDER 1 ALIAS PCEVG EXCLU
CASE MAMENI=7
   USE PCEVTZ IN 0 ORDER 1 ALIAS PCEV EXCLU
   USE PCEVTZG IN 0 ORDER 1 ALIAS PCEVG EXCLU
ENDCASE
   SELECT PCEVG
   GO TOP
   DO WHILE.NOT.EOF()
      MBRKAL=BRKAL
      IF DATDOK=CTOD('').OR.SIFRA=SPACE(5)
         DELETE 
      ENDIF
      SKIP
   ENDDO
   PACK
   GO TOP
   DO WHILE.NOT.EOF()
      MBRKAL=BRKAL
      SELECT PCEV
      LOCATE FOR BRKAL=MBRKAL

      IF FOUND()
         LL=1
      ELSE
         LL=0
      ENDIF
      SELECT PCEVG
      IF LL=0
         DELETE 
      ENDIF
      SKIP
   ENDDO
   SELECT PCEVG
   PACK
   CLOSE ALL
PCEVSERV.RELEASE
POP KEY
