PUSH KEY CLEAR
PCEV.COMMAND7.SETFOCUS
DO IDEL WITH (KkALIZVX)
KPCEVIZV=MDATA01+'\'+'PCEVIZV'+OPERATER
KPCEVIZVD=MDATA01+'\'+'PCEVIZV'+OPERATER+'.DBF'
KPCEVIZVX=MDATA01+'\'+'PCEVIZV'+OPERATER+'.CDX'

DO IDEL WITH (KPCEVIZVD)
DO IDEL WITH (KPCEVIZVX)
DO IDEL WITH (Kkockax)
DO IDEL WITH (Kkockax2)
SET DEFAULT TO &MDATA01
DO IBAZE WITH KPCEVIZV,'PCEVIZV'
DO IIND WITH KPCEVIZV,'DTOS(DATDOK)'
SET DEFAULT TO &MDATA02
USE  &KPCEVIZV IN 0 ALIAS PCEVIZV EXCLU ORDER 1
SELECT PCEVIZV
DELETE ALL
PACK

SELECT PCEV
MRSIF=RSIF
MMREC=RECNO()
SET ORDER TO 2
SEEK MRSIF
IF FOUND()
   DO WHILE.NOT.EOF()
      IF RSIF<>MRSIF
         EXIT
      ENDIF   
      MBRKAL=BRKAL
      MPC1PR=PCEVG.PC1PR
      MPC2PR=PCEVG.PC2PR
      MAdatdok=DATDOK
      MASIFRA=PCEVG.sifra
      MAIDBROJ=PCEVG.IDBROJ
      MAIDBROJI=PCEVG.IDBROJI
      MANAZIV=an0.naziv
      MAKOL=KOL
      MAVELCENA=PROSCENA
      MAVELVRED=PROSVRED
      MAULIZ=PCEVG.ULIZ
      MAIE=PCEVG.IE
      select PCEVIZV
      APPEND BLANK
      REPLACE BRKAL WITH MBRKAL
      REPLACE RSIF WITH MRSIF
      REPLACE DATDOK WITH MADATDOK
      REPLACE SIFRA WITH MASIFRA
      REPLACE IDBROJ WITH MAIDBROJ
      REPLACE IDBROJI WITH MAIDBROJI
      REPLACE NAZIV WITH MAnaziv
      REPLACE KOL WITH MAKOL
      REPLACE VELCENA WITH MAVELCENA
      REPLACE VELVRED WITH MAVELVRED
      REPLACE ULIZ WITH MAULIZ
      REPLACE IE WITH MAIE
      REPLACE PC1PR WITH MPC1PR
      REPLACE PC2PR WITH MPC2PR
      SELECT PCEV
      SKIP
   ENDDO   
   select PCEVIZV
   go top
   MKOLST=0
   MVREDST=0
   DO WHILE.NOT.EOF()
      IF ULIZ='U'
         REPLACE KOLU WITH KOL
         REPLACE VREDU WITH VELVRED
      ELSE
         REPLACE KOLI WITH KOL
         REPLACE VREDI WITH VELVRED
      ENDIF
      MKOLST=MKOLST+KOLU-KOLI
      REPLACE KOLST WITH MKOLST
      MVREDST=MVREDST+VREDU-VREDI
      REPLACE VREDST WITH MVREDST
      SKIP
   ENDDO   
   GO TOP
   SET RELATION TO SIFRA INTO AN0 ADDITIVE
   SET RELATION TO IDBROJ INTO PCDEF0 ADDITIVE
   SET RELATION TO RSIF INTO ROB ADDITIVE

   REPORT FORM PCEVKROBPROS PREVIEW
ENDIF   
   SELECT PCEVIZV
   USE
   SELECT PCEV
   SET ORDER TO
   GOTO MMREC
POP KEY
