     MNEPROFITU=PCEVG.NEPROFITU
     MNEPROFITI=PCEVG.NEPROFITI
     motr=PCEVG.otr
     MBRKAL=BRKAL
     MPC1PR=PCEVG.PC1PR
     MPC2PR=PCEVG.PC2PR
     MARSIF=rsif
     MAdatdok=DATDOK
     MAFVRSTA=PCEVG.fvrsta
     MASIFRA=PCEVG.sifra
     MAVSIFRA=PCEVG.VSIFRA
     MAVOZSIFRA=PCEVG.VOZSIFRA
     MAIDBROJ=PCEVG.IDBROJ
     MAIDBROJI=PCEVG.IDBROJI
     MAIDPROFC=PCEVG.IDPROFC
     MAIDSEKTOR=PCEVG.IDSEKTOR
     MAIDPODSEK=PCEVG.IDPODSEK
     MAIDLOKAC=PCEVG.IDLOKAC
     MAIDPROFCI=PCEVG.IDPROFCI
     MAIDSEKTORI=PCEVG.IDSEKTORI
     MAIDPODSEKI=PCEVG.IDPODSEKI
     MAIDLOKACI=PCEVG.IDLOKACI
     MBRRAC=PCEVG.BRRAC
     MDOKUM=PCEVG.DOKUM
     MANAZIV=an0.naziv
     MAPROTOKOL=PCEVG.PROTOKOL
     MBRPREVOZ=PCEVG.BRPREVOZ
     MTURA=TURA
     MKILOMETR=KILOMETR
     MKILOMETRP=KILOMETRP
     MAKOL=KOL
     MAVELCENA=VELCENA
     MAKOEF=KOEF
     MAKOL2=KOL2
     MAVELVRED=VELVRED-RABAT
     MADEVCENA=DEVCENA
     MADEVVRED=DEVVRED
     MAULIZ=PCEVG.ULIZ
     MAIE=PCEVG.IE
     MATARIFA=TARIFA
     MAPROCPOR=PROCPOR
     MAPOREZ=POREZ
     MARABPROC=RABPROC
     MARABAT=RABAT
     MAFAKVRED=FAKVRED
     MOPSTI=OPSTI
     MRELACOD=PCEVG.RELACOD
     MRELACDO=PCEVG.RELACDO
     MPOCSAT=POCSAT
     MZADSAT=ZADSAT
     MSATI=SATI 
     MVKONTO=PCEVG.VKONTO
     MAPROSCENA=PROSCENA
     MAPROSVRED=PROSVRED
     select PCEVIZV
     APPEND BLANK
     REPLACE BRKAL WITH MBRKAL
     REPLACE RSIF WITH MARSIF
     REPLACE DATDOK WITH MADATDOK
     REPLACE FVRSTA WITH MAFVRSTA
     REPLACE SIFRA WITH MASIFRA
     REPLACE VSIFRA WITH MAVSIFRA
     REPLACE VOZSIFRA WITH MAVOZSIFRA
     REPLACE IDBROJ WITH MAIDBROJ
     REPLACE IDBROJI WITH MAIDBROJI
     REPLACE IDPROFC WITH MAIDPROFC
     REPLACE IDSEKTOR WITH MAIDSEKTOR
     REPLACE IDPODSEK WITH MAIDPODSEK
     REPLACE IDLOKAC WITH MAIDLOKAC
     REPLACE IDPROFCI WITH MAIDPROFCI
     REPLACE IDSEKTORI WITH MAIDSEKTORI
     REPLACE IDPODSEKI WITH MAIDPODSEKI
     REPLACE IDLOKACI WITH MAIDLOKACI
     REPLACE NAZIV WITH MAnaziv
     REPLACE PROTOKOL WITH MAPROTOKOL
     REPLACE KOL WITH MAKOL
     IF MAMENI=6
        IF MAPROSCENA=0
           REPLACE VELCENA WITH MAVELCENA
        ELSE
           REPLACE VELCENA WITH MAPROSCENA
        ENDIF
     ELSE
        REPLACE VELCENA WITH MAVELCENA
     ENDIF   
     
     REPLACE KOEF WITH MAKOEF
     REPLACE KOL2 WITH MAKOL2
     
     IF MAMENI=6
        IF MAPROSVRED=0
           REPLACE VELVRED WITH MAVELVRED
   *       REPLACE VELVRED WITH 0   
        ELSE
           REPLACE VELVRED WITH MAPROSVRED
        ENDIF
     ELSE
        REPLACE VELVRED WITH MAVELVRED
     ENDIF   
     

     REPLACE DEVCENA WITH MADEVCENA
     REPLACE DEVVRED WITH MADEVVRED
     REPLACE ULIZ WITH MAULIZ
     REPLACE IE WITH MAIE
     REPLACE TARIFA WITH MATARIFA
     REPLACE PROCPOR WITH MAPROCPOR
     REPLACE POREZ WITH MAPOREZ
     REPLACE RABPROC WITH MARABPROC
     REPLACE RABAT WITH MARABAT
     REPLACE FAKVRED WITH MAFAKVRED
     REPLACE PC1PR WITH MPC1PR
     REPLACE PC2PR WITH MPC2PR
     REPLACE BRPREVOZ WITH MBRPREVOZ
     REPLACE KILOMETR WITH MKILOMETR
     REPLACE KILOMETRP WITH MKILOMETRP
     REPLACE TURA WITH MTURA
     REPLACE OPSTI WITH MOPSTI
     REPLACE BRRAC WITH MBRRAC
     REPLACE DOKUM WITH MDOKUM
     REPLACE RELACOD WITH MRELACOD
     REPLACE RELACDO WITH MRELACDO
     REPLACE POCSAT WITH MPOCSAT
     REPLACE ZADSAT WITH MZADSAT
     REPLACE SATI WITH MSATI
     REPLACE NEPROFITU WITH MNEPROFITU
     REPLACE NEPROFITI WITH MNEPROFITI
     REPLACE OTR WITH MOTR
     REPLACE VKONTO WITH MVKONTO
