PUSH KEY CLEAR
SELECT PCEV
IF KOL=0
   REPLACE VELVRED WITH 0
   REPLACE KOL2 WITH 0
   REPLACE VELCENA WITH 0
   REPLACE RABPROC WITH 0
   REPLACE RABAT WITH 0
   REPLACE POREZ WITH 0
   REPLACE FAKVRED WITH 0
ELSE
   IF VELCENA=0 
      IF PCEVG.ULIZ='U'
         REPLACE VELCENA WITH ROB.DCENA
      ELSE
         REPLACE VELCENA WITH ROB.VELCENA
      ENDIF   
   ENDIF   
   IF KOEF=0
      REPLACE KOEF WITH 1
   ENDIF
   REPLACE KOL2 WITH ROUND(KOL*KOEF,3)
   REPLACE VELVRED WITH KOL2*VELCENA
   REPLACE RABAT WITH ROUND(VELVRED*RABPROC/100,2)
   IF PCEVG.ULIZ='U'
      IF PCEVG.PPDV<>' '
         REPLACE POREZ WITH ROUND((VELVRED-RABAT)*PROCPOR/100,2)
      ELSE
         REPLACE POREZ WITH 0
      ENDIF
   ELSE
      IF PCEVG.OPDV<>' '
         REPLACE POREZ WITH ROUND((VELVRED-RABAT)*PROCPOR/100,2)
      ELSE
         REPLACE POREZ WITH 0
      ENDIF
   ENDIF   
   REPLACE FAKVRED WITH VELVRED-RABAT+POREZ
   REPLACE SATI WITH ZADSAT-POCSAT
   REPLACE KILOMETRP WITH TURA*KILOMETR
ENDIF
POP KEY
