PUSH KEY CLEAR
SELECT PCEV

IF RECCOUNT()>0
   *---AKO KALKULACIJA POSTOJI
   IF PCEVG.ARHIVA=' '
     *---AKO NIJE ARHIVIRANA-----
      MBRKAL=BRKAL
       
      MDATDOK=DATDOK
      APPEND BLANK
      REPLACE BRKAL WITH MBRKAL 
      REPLACE DATDOK WITH MDATDOK
      PCEV.GRD0.SETFOCUS
      PCEV.REFRESH
   ELSE
      *------AKO JE KALKULACIJA  ARHIVIRANA
      SELECT PCEV
      SET ORDER TO 1
      GO BOTTOM
      MBRKAL=BRKAL
      
      MNLEN=LEN(ALLTRIM(STR(VAL(ALLTRIM(MBRKAL))+1,6,0)))
      MNBRKAL=REPLI('0',6-MNLEN)+ALLTRIM(STR(VAL(ALLTRIM(MBRKAL))+1,6,0))
      SET ORDER TO 1
            LOCATE FOR BRKAL=MNBRKAL

      IF.NOT.FOUND()
         APPEND BLANK
         REPLACE BRKAL WITH MNBRKAL 
         PCEV.GRD0.SETFOCUS
         PCEV.GRD0.REFRESH
         PCEV.REFRESH
      ENDIF
         SELECT PCEVG
               LOCATE FOR BRKAL=MNBRKAL

         IF.NOT.FOUND()
            APPEND BLANK
            REPLACE BRKAL WITH MNBRKAL
         ENDIF      
  
         DO FORM PCEVZAG
         SELECT PCEV
         SET RELATION TO 
         SET RELATION TO BRKAL INTO PCEVG ADDITIVE
         SET RELATION TO RSIF INTO ROB ADDITIVE
         
               LOCATE FOR BRKAL=MNBRKAL

         IF FOUND()
            DO WHILE.NOT.EOF()
               IF BRKAL<>MNBRKAL
                  EXIT
               ENDIF   
               REPLACE DATDOK WITH PCEVG.DATDOK     
               DO PCEVRAC
               SKIP
            ENDDO
         ENDIF      
         SET ORDER TO 
         GO BOTTOM
   ENDIF 
ELSE
   *--------AKO PRVA STAVKA NE POSTOJI---------
   APPEND BLANK
   MNBRKAL='000001'
   REPLACE BRKAL WITH MNBRKAL 
   *------IDEMO U ZAGLAVLJE
   IF .NOT.FOUND()
      SELECT PCEV
      SET RELATION TO
      SELECT PCEVG
            LOCATE FOR BRKAL=MNBRKAL

      IF.NOT.FOUND()
         APPEND BLANK
         REPLACE BRKAL WITH MNBRKAL
      ENDIF      
      DO FORM PCEVZAG
      SELECT PCEV
      SET ORDER TO 1
      SET RELATION TO 
      SET RELATION TO BRKAL INTO PCEVG ADDITIVE
      SET RELATION TO RSIF INTO ROB ADDITIVE
            LOCATE FOR BRKAL=MNBRKAL

      IF FOUND()
         DO WHILE.NOT.EOF()
            IF BRKAL<>MNBRKAL
               EXIT
            ENDIF   
            REPLACE DATDOK WITH PCEVG.DATDOK     
            DO PCEVRAC
            SKIP
         ENDDO
      ENDIF      
      SET ORDER TO 
      GO BOTTOM
   ENDIF   
ENDIF    

SELECT PCEV
SET ORDER TO
GO BOTTOM
TZADKAL=BRKAL
PCEV.GRD0.SetAll("DynamicBackColor", "IIF(MOD(VAL(BRKAL),2)<>0, RGB(255,255,128), RGB(152,254,231))", "Column")  
PCEV.GRD0.COLUMN3.SETFOCUS
POP KEY
PCEV.REFRESH  
