PUSH KEY CLEAR
SELECT PCVOZILA
SET ORDER TO 
GO BOTTOM
APPEND BLANK
GO BOTTOM
PCVOZILA.GRD0.SetFocus
PCVOZILA.GRD0.REFRESH
REPLACE VSIFRA WITH STR(RECNO(),4,0)
DO FORM PCVOZILAKART
GO BOTTOM
PCVOZILA.GRD0.SetFocus
PCVOZILA.GRD0.REFRESH
PCVOZILA.REFRESH  
POP KEY