PUSH KEY CLEAR
SELECT PCVOZACI
SET ORDER TO 
GO BOTTOM
APPEND BLANK
GO BOTTOM
PCVOZACI.GRD0.SetFocus
PCVOZACI.GRD0.REFRESH
REPLACE VOZSIFRA WITH STR(RECNO(),4,0)
DO FORM PCVOZACIKART
GO BOTTOM
PCVOZACI.GRD0.SetFocus
PCVOZACI.GRD0.REFRESH
PCVOZACI.REFRESH  
POP KEY