PUSH KEY CLEAR
IF UKPROD<>0
   IF proc18=0
      REPLACE PDV18 WITH ROUND(UKPROD*VAL(TOSTOPA)/(100+VAL(TOSTOPA)),2) 
   ELSE
      REPLACE PDV18 WITH ROUND(UKPROD*proc18/(100+proc18),2) 
   endif   
   REPLACE OSN18 WITH UKPROD-PDV18
   DO RACPDVI
   PDVIK.TXTUKPROD.SETFOCUS
   PDVIK.REFRESH
ENDIF
POP KEY