PUSH KEY CLEAR
IF UKPROD<>0
   IF proc8=0
      REPLACE PDV8 WITH ROUND(UKPROD*VAL(TNSTOPA)/(100+VAL(TNSTOPA)),2) 
   ELSE
      REPLACE PDV8 WITH ROUND(UKPROD*proc8/(100+proc8),2) 
   endif   
   REPLACE OSN8 WITH UKPROD-PDV8
   DO RACPDVI
   PDVIK.TXTUKPROD.SETFOCUS
   PDVIK.REFRESH
ENDIF
POP KEY