PARAMETERS PRINTAJ
PUSH KEY CLEAR
SELECT DATUMI
REPLACE DAT0 WITH PDVIIZV03.TXTFDAT0.VALUE
REPLACE DAT1 WITH PDVIIZV03.TXTFDAT1.VALUE

MDAT0=PDVIIZV03.TXTFDAT0.VALUE
MDAT1=PDVIIZV03.TXTFDAT1.VALUE

DO IDEL WITH  (KKOCKAX)
DO IDEL WITH  (KKOCKAX2)
DO IDEL WITH  (KKOCKAX3)
DO IDEL WITH  (KKOCKAX4)
DO IDEL WITH  (KKOCKAX5)      
      
   USE &KPDVUS EXCLU IN 0 ALIAS PDVUS
   SELECT PDVUS
  * brow
   DELETE ALL
   PACK
   COPY STRU TO &KKOCKA
   COPY STRU TO &KKOCKA2
   COPY STRU TO &KKOCKA3
   USE &KKOCKA IN 0 ALIAS KOCKA exclu
   SELECT KOCKA
   INDEX ON BRNAL+KONTO TAG KONTO
   SELECT PDV
   GO TOP
   DO WHILE.NOT.EOF()
      IF DATDOK>=MDAT0.AND.DATDOK<=MDAT1
         MPDV18=PDV18
         MPDV8=PDV8
         MKON18=pdvkon.kONP1
         MKON8=pdvkon.KONP2
         MBRNAL=BRNAL
         SELECT KOCKA
         IF MPDV18<>0
            APPEND BLANK
            REPLACE PDV WITH MPDV18
            REPLACE KONTO WITH MKON18
            REPLACE BRNAL WITH MBRNAL
         ENDIF
         IF MPDV8<>0
            APPEND BLANK
            REPLACE PDV WITH MPDV8
            REPLACE KONTO WITH MKON8
            REPLACE BRNAL WITH MBRNAL
         ENDIF
      ENDIF
      SELECT PDV
      SKIP
   ENDDO
   
   SELECT KOCKA
   SET ORDER TO 1
   TOTAL ON BRNAL+KONTO TO &KKOCKA2 FIELDS PDV
   DELETE ALL
   PACK
   APPEND FROM &KKOCKA2
   USE NAL IN 0 ORDER 1
   SELECT NAL
   COPY TO &KKOCKA4 FOR SUBSTR(KONTO,1,2)='47'.and.(datDOK>=mdat0.and.datDOK<=mdat1)
   USE
   USE &kkocka4 IN 0 ALIAS kocka4 exclu
   SELECT kocka4
   DELETE ALL FOR SUBSTR(konto,1,3)='479'
   PACK
   INDEX on BRNAL+KONTO TAG KONTO
   SET ORDER TO 1
   TOTAL ON BRNAL+KONTO TO &KKOCKA5
   ZAP
   APPEND FROM &KKOCKA5
   USE &KKOCKA2 EXCLU IN 0 ALIAS kocka2
   SELECT KOCKA2
   ZAP
   SELECT KOCKA4
   GO TOP
   DO WHILE.NOT.EOF()
      IF DATDOK>=MDAT0.AND.DATDOK<=MDAT1
         MPDVGK=POT
         MBRNAL=BRNAL
         MKONTO=KONTO
         REPLACE DUG WITH 9999999
         SELECT KOCKA2
         APPEND blank
         REPLACE PDVGK WITH MPDVGK
         REPLACE BRNAL WITH MBRNAL
         REPLACE KONTO WITH MKONTO
      ENDIF   
      SELECT KOCKA4
      SKIP
   ENDDO
   SELECT KOCKA4
   USE
   SELECT KOCKA2
   USE
   DO IDEL WITH  (KKOCKAX2)
   SELECT KOCKA
   APPEND FROM &KKOCKA2
   TOTAL ON BRNAL+KONTO TO &KKOCKA2
   ZAP
   APPEND FROM &KKOCKA2
   USE
   SELECT PDVUS
   USE
   USE &KPDVUS EXCLU IN 0 ALIAS PDVUS
   SELECT PDVUS
   DELETE ALL
   PACK
   APPEND FROM &KKOCKA
   DELETE ALL FOR PDV=PDVGK
   DELETE ALL FOR ABS(PDV-PDVGK)<=1
   PACK
   REPLACE ALL DAT0 WITH MDAT0
   REPLACE ALL DAT1 WITH MDAT1
   *REPORT FORM PDVIGKSLAG PREVIEW 
   mfile='PDVIGKSLAG' 
   uslov=""
   DO printer_bullzip WITH mdata02,mfile,uslov
   
   SELECT PDVUS
   USE
   SELECT PDV
   GO TOP 
   POP KEY
   PDVIIZV03.release
   
