PARAMETERS PRINTAJ
PUSH KEY CLEAR
SELECT DATUMI
REPLACE DAT0 WITH PDVIIZV03.TXTFDAT0.VALUE
REPLACE DAT1 WITH PDVIIZV03.TXTFDAT1.VALUE

MDAT0=PDVIIZV03.TXTFDAT0.VALUE
MDAT1=PDVIIZV03.TXTFDAT1.VALUE

DO IDEL WITH  (KKOCKAX)
DO IDEL WITH  (KKOCKAX2)
DO IDEL WITH  (KKOCKAX3)
DO IDEL WITH  (KKOCKAX4)
DO IDEL WITH  (KKOCKAX5)      
DO IDEL WITH  (KKOCKAX6)            
   USE &KPDVUS EXCLU IN 0 ALIAS PDVUS
   SELECT PDVUS
  * brow
   DELETE ALL
   PACK
   COPY STRU TO &KKOCKA
   COPY STRU TO &KKOCKA2
   COPY STRU TO &KKOCKA3
   USE &KKOCKA IN 0 ALIAS KOCKA exclu
   SELECT KOCKA

   INDEX ON BRNAL+KONTO TAG KONTO
   SELECT PDV
   GO TOP
   DO WHILE.NOT.EOF()
      IF DATDOK>=MDAT0.AND.DATDOK<=MDAT1
         MOSN18=OSN18
         MOSN8=OSN8
         MOSN0=OSN0
         MKONTO=KONTO
         MBRNAL=BRNAL
         MDATDOK=DATDOK
         SELECT KOCKA
         APPEND BLANK
         REPLACE PDV WITH MOSN18+MOSN8+MOSN0
         REPLACE KONTO WITH SUBSTR(MKONTO,1,4)         
         REPLACE BRNAL WITH MBRNAL
         REPLACE DATDOK WITH MDATDOK
      ENDIF
      SELECT PDV
      SKIP
   ENDDO
   
   SELECT KOCKA
   SET ORDER TO 1
   TOTAL ON BRNAL+KONTO TO &KKOCKA2 FIELDS PDV
   DELETE ALL
   PACK
   APPEND FROM &KKOCKA2
   USE NAL IN 0 ORDER 1
   SELECT NAL
   COPY TO &KKOCKA4 FOR (SUBSTR(KONTO,1,1)='6').and.(datDOK>=mdat0.and.datDOK<=mdat1)
   USE
   USE &kkocka4 IN 0 ALIAS kocka4 exclu
   SELECT kocka4
   REPLACE ALL KONTO WITH SUBSTR(KONTO,1,4)
   DELETE ALL FOR SUBSTR(KONTO,1,2)='62'
   DELETE ALL FOR SUBSTR(KONTO,1,3)='699'   
   PACK
   INDEX on BRNAL+KONTO TAG KONTO
   SET ORDER TO 1
   TOTAL ON BRNAL+KONTO TO &KKOCKA5
   ZAP
   APPEND FROM &KKOCKA5
   USE &KKOCKA2 EXCLU IN 0 ALIAS kocka2
   SELECT KOCKA2
   ZAP
   SELECT KOCKA4
   GO TOP
   DO WHILE.NOT.EOF()
      IF DATDOK>=MDAT0.AND.DATDOK<=MDAT1
         MPDVGK=POT-dug
         MBRNAL=BRNAL
         MKONTO=KONTO
         MDATDOK=DATDOK
         REPLACE DUG WITH 9999999
         SELECT KOCKA2
         APPEND blank
         REPLACE PDVGK WITH MPDVGK
         REPLACE BRNAL WITH MBRNAL
         REPLACE KONTO WITH MKONTO
         REPLACE DATDOK WITH MDATDOK
      ENDIF   
      SELECT KOCKA4
      SKIP
   ENDDO
   SELECT KOCKA4
   USE
   SELECT KOCKA2
   USE
   DO IDEL WITH  (KKOCKAX2)
   SELECT KOCKA
   APPEND FROM &KKOCKA2
   TOTAL ON BRNAL+KONTO TO &KKOCKA2
   ZAP
   APPEND FROM &KKOCKA2
   USE
   SELECT PDVUS
   USE
   USE &KPDVUS EXCLU IN 0 ALIAS PDVUS
   SELECT PDVUS
   DELETE ALL
   PACK
   APPEND FROM &KKOCKA
   DELETE ALL FOR PDV=PDVGK
   DELETE ALL FOR ABS(PDV-PDVGK)<=1
   PACK
   REPLACE ALL DAT0 WITH MDAT0
   REPLACE ALL DAT1 WITH MDAT1
   SORT ON DATDOK TO &KKOCKA2
   ZAP
   APPEND FROM &KKOCKA2
   GO TOP
   IF PRINTAJ=1
      *REPORT FORM PDVIGKSLAG PREVIEW 
      
   mfile='PDVIGKSLAG' 
   uslov=""
   DO printer_bullzip WITH mdata02,mfile,uslov
      
      
   ELSE
      COPY TO &KKOCKA2
      USE &KKOCKA2 IN 0 EXCLUSIVE ALIAS KOCKA2
      SELECT KOCKA2
      IF PRINTAJ=2
         INDEX ON KONTO+SUBSTR(BRNAL,1,1) TAG BRNAL
         SET ORDER TO 1
         TOTAL ON KONTO+SUBSTR(BRNAL,1,1) TO &KKOCKA6
      ENDIF
      IF PRINTAJ=3
         INDEX ON KONTO+SUBSTR(BRNAL,1,2) TAG BRNAL
         SET ORDER TO 1
         TOTAL ON KONTO+SUBSTR(BRNAL,1,2) TO &KKOCKA6
      ENDIF
      IF PRINTAJ=4
         INDEX ON KONTO TAG BRNAL
         SET ORDER TO 1
         TOTAL ON KONTO TO &KKOCKA6
      ENDIF
      USE
      SELECT PDVUS
      ZAP
      APPEND FROM &KKOCKA6
      GO TOP
      *REPORT FORM PDVIGKSLAG PREVIEW   
   mfile='PDVIGKSLAG' 
   uslov=""
   DO printer_bullzip WITH mdata02,mfile,uslov
      
   ENDIF 
   SELECT PDVUS
   USE
   SELECT PDV
   GO TOP 
   POP KEY
   PDVIIZV03.release
   
