PUSH KEY CLEAR
SELECT PDV
SET RELATION TO 
DO FORM FAN0
SELECT AN0
SET ORDER TO 1
SELECT PDV
SET RELATION TO VPDV INTO PDVKON ADDITIVE
SET RELATION TO SIFRA INTO AN0 ADDITIVE
PDVI.GRD0.SETFOCUS
POP KEY
PDVI.Refresh 