PUSH KEY CLEAR
IF UKNAB<>0
   MOSTOPA=VAL(TOSTOPA)
   IF proc18=0
      REPLACE PDV18 WITH ROUND(UKNAB*MOSTOPA/(100+MOSTOPA),2)
   else
      REPLACE PDV18 WITH ROUND(UKNAB*proc18/(100+proc18),2)   
   endif
   REPLACE OSN18 WITH UKNAB-PDV18
   DO RACPDV
   PDVUK.TXTUKNAB.SETFOCUS
   PDVUK.REFRESH
ENDIF
POP KEY