PUSH KEY CLEAR
SET ORDER TO 
GO BOTTOM
IF RECCOUNT()>0
   MVPDV=VPDV
   MDATPDV=DATPDV
   MDATPRI=DATPRI
   MDATDOK=DATDOK
   MVALUTA=VALUTA
   MBRNAL=BRNAL
   MDOK=DOK
ELSE
   MVPDV='UN0'
   MDATPDV=CTOD('')
   MDATPRI=CTOD('')
   MDATDOK=CTOD('')
   MVALUTA=CTOD('')
   MBRNAL=SPACE(6)
   MDOK=SPACE(3)      
ENDIF   
IF VPDV<>SPACE(3).OR.RECCOUNT()<1
   APPEND BLANK
   GO BOTTOM
   REPLACE VPDV WITH MVPDV
   REPLACE DATPRI WITH MDATPRI
   REPLACE DATPDV WITH MDATPDV
   REPLACE DATDOK WITH MDATDOK
   REPLACE VALUTA WITH MVALUTA
   REPLACE BRNAL WITH MBRNAL
   REPLACE DOK WITH MDOK
   REPLACE DATUM WITH DATE()
   REPLACE VREME WITH TIME()   
   PDVU.GRD0.SETFOCUS
   PDVU.REFRESH 
   DO  FORM PDVUK 
ENDIF
PDVU.GRD0.SetFocus 
POP KEY
PDVU.Refresh 