PUSH KEY CLEAR
SET ORDER TO 
GO BOTTOM
IF RECCOUNT()>0
   MVPDV=VPDV
   MDATPRI=DATPRI
   MDATPDV=DATPDV
   MDATDOK=DATDOK
   MVALUTA=VALUTA
   MBRNAL=BRNAL
   MDOK=DOK
ELSE
   MVPDV='UN0'
   MDATPRI=CTOD('')
   MDATPDV=CTOD('')
   MDATDOK=CTOD('')
   MVALUTA=CTOD('')
   MBRNAL=SPACE(6)
   MDOK=SPACE(3)      
ENDIF   
IF VPDV<>SPACE(3).OR.RECCOUNT()<1
   APPEND BLANK
   GO BOTTOM
   REPLACE VPDV WITH MVPDV
   REPLACE DATPRI WITH MDATPRI
   REPLACE DATPDV WITH MDATPDV
   REPLACE DATDOK WITH MDATDOK
   REPLACE VALUTA WITH MVALUTA
   REPLACE BRNAL WITH MBRNAL
   REPLACE DOK WITH MDOK
   REPLACE DATUM WITH DATE()
   REPLACE VREME WITH TIME()   
   PDVU0.GRD0.SETFOCUS
   PDVU0.REFRESH 
   DO FORM PDVUK
ENDIF
PDVU0.GRD0.SetFocus 
POP KEY
PDVU0.Refresh 