PUSH KEY CLEAR
IF UKNAB<>0
   IF proc8=0
      REPLACE PDV8 WITH ROUND(UKNAB*VAL(TNSTOPA)/(100+VAL(TNSTOPA)),2)
   ELSE
      REPLACE PDV8 WITH ROUND(UKNAB*proc8/(100+proc8),2)   
   endif
   REPLACE OSN8 WITH UKNAB-PDV8
   DO RACPDV
   PDVUK.TXTUKNAB.SETFOCUS
   PDVUK.REFRESH
ENDIF
POP KEY