   PARAMETERS mesec,MKONTO,MDUGPOT,MESN
PUSH KEY CLEAR
   
   MMESN=MESN
   SELECT NAL
   SEEK MKONTO
   MDUG=0
   IF FOUND()
      DO WHILE.NOT.EOF()
         IF KONTO<>MKONTO
            EXIT
         ENDIF
         IF MONTH(DATDOK)=MESEC
            IF MDUGPOT='D'
               MDUG=MDUG+KURSDUG-KURSPOT
            ELSE
               MDUG=MDUG+KURSPOT-KURSDUG
            ENDIF   
         ENDIF
         SKIP
      ENDDO   
   ENDIF
   SELECT PLANME 
   REPLACE &MMESN WITH ROUND(MDUG,0)
POP KEY