PUSH KEY CLEAR
POMAT.GRD0.COLUMN1.SETFOCUS
SELECT FAK

MMFF=FAKG.ARHIVA
IF FAKG.ARHIVA<>'*' 

   MBRKAL=BRKAL
   SET RELATION TO
   SELECT FAKG
   LOCATE FOR BRKAL=MBRKAL

   IF.NOT.FOUND()
      APPEND BLANK
      REPLACE BRKAL WITH MBRKAL
   ENDIF      
   DO FORM POMATZAG
   SELECT FAK
   REPLACE DATDOK WITH FAKG.DATDOK    
   SET RELATION TO BRKAL INTO FAKG ADDITIVE
   SET RELATION TO RSIF INTO ROB ADDITIVE
   SELECT FAK
   SET ORDER TO 1
   LOCATE FOR BRKAL=MBRKAL

   IF FOUND()
      DO WHILE.NOT.EOF()
         IF BRKAL<>MBRKAL
            EXIT
         ENDIF
         REPLACE DATDOK WITH FAKG.DATDOK
*         DO FAKRAC
         SKIP
      ENDDO
      LOCATE FOR BRKAL=MBRKAL

   ENDIF         
   SET ORDER TO 
ENDIF

POMAT.GRD0.COLUMN3.SETFOCUS
POP KEY
POMAT.REFRESH  
