PUSH KEY CLEAR
SELECT FAK
USE 

DO CASE MMAVRSTA
CASE MMAVRSTA=1
   USE POPOL IN 0 ALIAS FAK EXCLU
CASE MMAVRSTA=2
   USE POMAT IN 0 ALIAS FAK EXCLU
CASE MMAVRSTA=3
   USE POPMA IN 0 ALIAS FAK EXCLU
OTHERWISE
   USE POAMB IN 0 ALIAS FAK EXCLU
ENDCASE
SELECT FAK
DELETE ALL FOR KOLI=0
PACK
USE
POMAT.RELEASE
KEYBOARD '{ENTER}'

POP KEY
