PUSH KEY CLEAR
PUBLIC MREDREC,MREDZAD
SELECT FAK
MREDREC=RECNO()
MREDZAD=RECCOUNT()
POMAT.GRD0.COLUMN1.SETFOCUS
MBRKAL=BRKAL
DO FORM ROBA
SELECT FAK
SET ORDER TO 
GOTO MREDREC
POMAT.GRD0.COLUMN1.SETFOCUS
POP KEY
