PUSH KEY CLEAR
MBRKAL=BRKAL
IF FAKG->ARHIVA=' '
   SELECT FAK
   SET RELATION TO
   USE
   SELECT FAKG
   USE    
   DO CASE MMAVRSTA

   CASE MMAVRSTA=1
      USE POPOL IN 0 ALIAS FAK EXCLU
      USE POPOLG IN 0 ORDER 1 ALIAS FAKG EXCLU
   CASE MMAVRSTA=2
      USE POMAT IN 0 ALIAS FAK EXCLU
      USE POMATG IN 0 ORDER 1 ALIAS FAKG EXCLU 
   CASE MMAVRSTA=3
      USE POPMA IN 0 ALIAS FAK EXCLU
      USE POPMAG IN 0 ORDER 1 ALIAS FAKG EXCLU
   OTHERWISE
      USE POAMB IN 0 ALIAS FAK EXCLU
      USE POAMBG IN 0 ORDER 1 ALIAS FAKG EXCLU
   ENDCASE   
   SELECT FAK
   DELETE ALL FOR BRKAL=MBRKAL
   PACK
   USE    
   SELECT FAKG
   DELETE ALL FOR BRKAL=MBRKAL
   PACK
   USE
ENDIF
POMAT.RELEASE
KEYBOARD '{ENTER}'
POP KEY