PUSH KEY CLEAR
POMAT.GRD0.COLUMN1.SETFOCUS
   *---AKO KALKULACIJA POSTOJI
   IF FAKG.ARHIVA=' '.AND.RECCOUNT()>0
      *---AKO NIJE ARHIVIRANA-----
      MBRKAL=BRKAL
      MDATDOK=DATDOK
      APPEND BLANK
      REPLACE BRKAL WITH MBRKAL 
      REPLACE DATDOK WITH MDATDOK
      POMAT.GRD0.SETFOCUS
      POMAT.REFRESH
   ELSE
      *------AKO JE KALKULACIJA  ARHIVIRANA
      USE PROPAR IN 0 
      SELECT PROPAR
      go top
      MMAGMAT=ALLTRIM(MAGMAT)
      MFPMAT=FPMAT
      USE
      KNKALG='FAKG'+MMAGMAT+'.DBF'
      IF FILE(KNKALG)
         USE &KNKALG IN 0 ORDER 1 ALIAS KNKALG
         SELECT KNKALG
         GO BOTTOM
         MBRKAL=BRKAL
         USE
         MNLEN=LEN(ALLTRIM(STR(VAL(ALLTRIM(MBRKAL))+1,6,0)))
         MNBRKAL=REPLI('0',6-MNLEN)+ALLTRIM(STR(VAL(ALLTRIM(MBRKAL))+1,6,0))
         SELECT FAK
         SET RELATION TO
         SET ORDER TO 1 
         GO BOTTOM
         APPEND BLANK
         GO BOTTOM
         REPLACE BRKAL WITH MNBRKAL 
         POMAT.GRD0.SETFOCUS
         POMAT.GRD0.REFRESH
         POMAT.REFRESH
         SELECT FAKG
         GO BOTTOM
         APPEND BLANK
         GO BOTTOM
         REPLACE BRKAL WITH MNBRKAL
         DO FORM POMATZAG
      ENDIF
      SELECT FAK
            LOCATE FOR BRKAL=MNBRKAL

      SET RELATION TO BRKAL INTO FAKG ADDITIVE
      SET RELATION TO RSIF INTO ROB ADDITIVE
      REPLACE DATDOK WITH FAKG.DATDOK    
      SET ORDER TO 
   ENDIF 

SELECT FAK
SET ORDER TO
POMAT.GRD0.COLUMN3.SETFOCUS
POP KEY
POMAT.REFRESH  
