PUSH KEY CLEAR
   MPRIH=0
   MRASH=0
   GO TOP
   DO WHILE.NOT.EOF()
      MREC=RECNO()
      IF MREC=3.OR.MREC=4.OR.MREC=5.OR.MREC=6
         MPRIH=MPRIH+IZNOS
      ENDIF
      IF MREC>=9.AND.MREC<=14
         MRASH=MRASH+IZNOS
      ENDIF
      SKIP
   ENDDO
   GOTO 7
      REPLACE IZNOS WITH MPRIH
   GOTO 15
      REPLACE IZNOS WITH MRASH
   GOTO 16
      REPLACE IZNOS WITH MPRIH-MRASH
   GO TOP
POP KEY