PROCEDURE ROUZMI
   PARAMETERS AA,BB
PUSH KEY CLEAR
   msel=BB
   SELECT PREGLED
   APPEND BLANK
   REPLACE PPOLJE WITH SUBSTR(AA,1,103)
   REPLACE PPOLJE2 WITH SUBSTR(AA,104,103)
   REPLACE PPOLJE3 WITH SUBSTR(AA,207,103)
   REPLACE PPOLJE4 WITH SUBSTR(AA,310,103)
   REPLACE PPOLJE5 WITH SUBSTR(AA,413,103)
   REPLACE PPOLJE6 WITH SUBSTR(AA,516,103)
   SELECT &BB
POP KEY
ENDPROC


*PROCEDURE ROPOC
*   PARAMETERS AA
*   MSEL=SELECT()
*   SELECT 25
*   USE &TPREGLE EXCLU ALIAS PREGLED
*   ZAP
*   select (msel)
*ENDPROC   


PROCEDURE ROPOC
   PARAMETERS AA
   PUSH KEY CLEAR
   MSEL=AA
   USE &TPREGLE IN 0 EXCLU ALIAS PREGLED
   SELECT PREGLED
   ZAP
   select &AA
POP KEY
ENDPROC   
