IF TFPOSSIF<>'D' 

PUSH KEY CLEAR

SELECT PROAMB
APPEND BLANK
REPLACE Asif WITH STR(RECNO(),5,0)
REPLACE RSIF WITH ASIF
PROAMBP.GRD0.REFRESH
      DO FORM PROAMBK

PROAMBP.GRD0.SETFOCUS
POP KEY
PROAMBP.REFRESH
ENDIF