PUSH KEY CLEAR
*MUZIKA=MBAZNI+'\WAV\S009.WAV'
*SET BELL TO MUZIKA
*??CHR(7)
*SET BELL TO


   SELECT PROAMB
   MASIF=ASIF
   MCENA=PLCENA
   SELECT PRONORMA
   IF PSIF=SPACE(5).AND.MSIF=SPACE(5).AND.PMSIF=SPACE(5).AND.ASIF=SPACE(5).AND.LDSIF=SPACE(5).AND.DIRSIF=SPACE(5).AND.OPSSIF=SPACE(5)
      REPLACE ASIF WITH MASIF
      REPLACE CENA WITH MCENA
   ENDIF
   
PROAMB.VISIBLE=.F.
IF MNOR=1
   PRONORMA.REFRESH
ELSE
   PRONORMAL.REFRESH
ENDIF
PROAMB.VISIBLE=.T. 
   
SELECT PROAMB
PROAMB.GRD0.COLUMN2.SETFOCUS
PROAMB.REFRESH
POP KEY