IF TFPOSSIF<>'D'
PUSH KEY CLEAR
SELECT PROAMB
APPEND BLANK
REPLACE Asif WITH STR(RECNO(),5,0)
REPLACE RSIF WITH ASIF
PROAMB.GRD0.REFRESH
      DO FORM PROAMBK
PROAMB.GRD0.SETFOCUS
POP KEY
PROAMB.REFRESH
ENDIF