PUSH KEY CLEAR
SELECT PROCKNAL
SET ORDER TO 
GO BOTTOM
IF RECCOUNT()>0
   SCATTER NAME POLJA
ENDIF
APPEND BLANK
IF RECCOUNT()>1
   GATHER NAME POLJA
ENDIF
GO BOTTOM
PROCKNAL.GRD0.REFRESH
PROCKNAL.GRD0.COLUMN2.SetFocus
PROCKNAL.REFRESH
POP KEY