PUSH KEY CLEAR

   SELECT PRODIR
   MDIRSIF=DIRSIF

   MCENA=CENA
   SELECT PRONORMA
   IF MSIF=SPACE(5).AND.PMSIF=SPACE(5).AND.ASIF=SPACE(5).AND.LDSIF=SPACE(5).AND.DIRSIF=SPACE(5).AND.OPSSIF=SPACE(5)
      REPLACE DIRSIF WITH MDIRSIF
      REPLACE CENA WITH MCENA
   ENDIF
PRODIRP.VISIBLE=.F.
PRONORMAP.REFRESH
PRODIRP.VISIBLE=.T. 
   
SELECT PRODIR
PRODIRP.GRD0.COLUMN2.SETFOCUS
PRODIRP.REFRESH
POP KEY