PUSH KEY CLEAR
   SELECT PROMAT
   MMSIF=MSIF
   MCENA=PLCENA
   SELECT PRONORMA
   MRSIF=RSIF
   MNORMATIV=NORMATIV
   IF PSIF=SPACE(5).AND.MSIF=SPACE(5).AND.PMSIF=SPACE(5).AND.ASIF=SPACE(5).AND.LDSIF=SPACE(5).AND.DIRSIF=SPACE(5).AND.OPSSIF=SPACE(5)
      REPLACE MSIF WITH MMSIF
      REPLACE CENA WITH MCENA
   ELSE
      APPEND BLANK
      REPLACE RSIF WITH MRSIF
      REPLACE NORMATIV WITH MNORMATIV
      REPLACE MSIF WITH MMSIF
      REPLACE CENA WITH MCENA   
   ENDIF
PROMAT.VISIBLE=.F.
IF MNOR=1
   PRONORMA.REFRESH
ELSE
   PRONORMAL.REFRESH
ENDIF
PROMAT.VISIBLE=.T. 
   
SELECT PROMAT
PROMAT.GRD0.COLUMN2.SETFOCUS
POP KEY
PROMAT.REFRESH