IF TFPOSSIF<>'D' 
PUSH KEY CLEAR
SELECT PROMAT
APPEND BLANK
REPLACE Msif WITH STR(RECNO(),5,0)
REPLACE RSIF WITH MSIF
PROMATP.GRD0.REFRESH
DO FORM PROMATK
PROMATP.GRD0.SETFOCUS
POP KEY
PROMATP.REFRESH
ENDIF