PUSH KEY CLEAR

   SELECT PROMAT
   MMSIF=MSIF
   MCENA=PLCENA
   SELECT PRONORMA
   IF MSIF=SPACE(5).AND.PMSIF=SPACE(5).AND.ASIF=SPACE(5).AND.LDSIF=SPACE(5).AND.DIRSIF=SPACE(5).AND.OPSSIF=SPACE(5)
      REPLACE MSIF WITH MMSIF
      REPLACE CENA WITH MCENA
   ENDIF
PROMATP.VISIBLE=.F.
PRONORMAP.REFRESH
PROMATP.VISIBLE=.T. 
   
SELECT PROMAT
PROMATP.GRD0.COLUMN2.SETFOCUS
POP KEY
PROMATP.REFRESH