IF TFPOSSIF<>'D'
PUSH KEY CLEAR
SELECT PROMAT
APPEND BLANK
REPLACE Msif WITH STR(RECNO(),5,0)
REPLACE RSIF WITH MSIF
PROMAT.GRD0.REFRESH
DO FORM PROMATK

PROMAT.GRD0.SETFOCUS
POP KEY
PROMAT.REFRESH
ENDIF