PUSH KEY CLEAR
SET ORDER TO 
if reccount()>0
   MRNAL=RNAL
   MNORMATIV=NORMATIV
   mrsif=rsif
   MDAT0=DAT0
   MDAT1=DAT1
   MDOK=DOK
   MFAKTURA=FAKTURA
   MMATDOK=MATDOK
ELSE
   MNORMATIV=SPACE(5)
   mrsif=space(5)
   MDAT0=DATE()
   MDAT1=DATE()
   MRNAL='000001'
   MDOK=' '
   MFAKTURA=' '
   MMATDOK=''
endif      
*IF KOL<>0
   append blank
   GO bottom
   REPLACE DAT0 WITH MDAT0
   REPLACE DAT1 WITH MDAT1
   REPLACE RNAL WITH MRNAL
   REPLACE DOK WITH MDOK
   REPLACE FAKTURA WITH MFAKTURA
   REPLACE MATDOK WITH MMATDOK
*ENDIF
IF MPNAL=1
   PRONAL.grd0.column1.setfocus
   PRONAL.REFRESH  
ELSE
   PRONALL.grd0.column1.setfocus
   PRONALL.REFRESH  
ENDIF
POP KEY