PARAMETERS MDAT0,MDAT1,MSVE
DO IDEL WITH (KKOCKAX)
DO IDEL WITH (KKOCKAX2)
SELECT PRONAL
SET ORDER TO 
COPY STRUCTURE TO &KKOCKA
USE &KKOCKA IN 0 EXCLUSIVE ALIAS KOCKA
SELECT PRONAL
GO TOP
DO WHILE.NOT.EOF()
   IF DAT0>=MDAT0.AND.DAT0<=MDAT1
      MNAZ=ROB.NAZ      
      SCATTER NAME POLJA
      SELECT KOCKA
      APPEND BLANK
      GATHER NAME POLJA   
      REPLACE SVENORMA WITH KOL*RCENA
      REPLACE MSIFNAZ WITH MNAZ
      SELECT PRONAL
   ENDIF      
   SKIP
ENDDO   
SELECT KOCKA
*-------------PREUZIMAMO IZ KALKULACIJA
USE PROPAR IN 0 
SELECT PROPAR
MMAGGOT=ALLTRIM(MAGGOT)
USE
SELECT PRONAL
SET RELATION TO
*----------UNOSIMO POLUPROIZVODE----------
KKAL='KAL'+MMAGGOT
KKALG='KALG'+MMAGGOT
KKKAL='KAL'+MMAGGOT+'.DBF'
KKKALG='KALG'+MMAGGOT+'.DBF'

IF FILE(KKKAL)
   USE &KKAL IN 0 ORDER 1 ALIAS KAL
   SELECT KAL
   USE &KKALG IN 0 ORDER 1 ALIAS KALG
   SELECT KALG
   SELECT KAL
   SET RELATION TO BRKAL INTO KALG ADDITIVE
   SET RELATION TO RSIF INTO ROB ADDITIVE
   GO TOP
   DO WHILE.NOT.EOF()
      SELECT KAL
      IF KALG.DATDOK>=MDAT0.AND.KALG.DATDOK<=MDAT1
      IF KALG.RNAL<>SPACE(12)
         MTVKOL=KOL
         MTVCENA=CENA
         MRSIF=RSIF
         MRNAL=KALG.RNAL
         MNAZ=ROB.NAZ
         SELECT KOCKA
         APPEND BLANK
         REPLACE RNAL WITH MRNAL
         REPLACE RSIF WITH MRSIF
         REPLACE MSIFNAZ WITH MNAZ
         REPLACE TVKOL WITH MTVKOL
         REPLACE TVCENA WITH MTVCENA
         REPLACE TVIZNOS WITH MTVKOL*MTVCENA
      ENDIF
      ENDIF
      SELECT KAL
      SKIP
   ENDDO   
ENDIF
SELECT KAL
USE
SELECT KALG
USE
SELECT KOCKA
INDEX ON RNAL+RSIF TAG RRNAL
SET ORDER TO 1
TOTAL ON RNAL+RSIF TO &KKOCKA2 FIELDS KOL,SVENORMA,TVKOL,TVIZNOS
DELETE ALL
PACK

APPEND FROM &KKOCKA2
GO TOP
PUBLIC ADAT0,ADAT1
ADAT0=MDAT0
ADAT1=MDAT1
IF MSVE=1
   *REPORT FORM PRONALSLAG0GOT PREVIEW
   mfile='PRONALSLAG0GOT' 
   uslov=""
   DO printer_bullzip WITH mdata02,mfile,uslov
   
ELSE
   *REPORT FORM PRONALSLAG0GOT PREVIEW FOR (KOL<>TVKOL).OR.(SVENORMA<>TVIZNOS)
   mfile='PRONALSLAG0GOT' 
   uslov="(KOL<>TVKOL).OR.(SVENORMA<>TVIZNOS)"
   DO printer_bullzip WITH mdata02,mfile,uslov
   
ENDIF
SELECT KOCKA
USE
SELECT PRONAL
SET RELATION TO RSIF INTO rob additive
SET RELATION TO NORMATIV INTO PRONORMA ADDITIVE
SET RELATION TO RNAL INTO PRONLOP ADDITIVE
GO TOP

