PUSH KEY CLEAR
DO IDEL WITH (KKOCKAX)
DO IDEL WITH (KKOCKAX2)
SELECT PRONAL
SET ORDER TO 1
MNORMATIV=NORMATIV
MRNAL=RNAL
MRKOL=KOL
MRSIF=RSIF
SET RELATION TO

SELECT PRONORMA
COPY STRUCTURE TO &KKOCKA
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU

SELECT KOCKA
SET RELATION TO LDSIF INTO PRORAD ADDITIVE
SET RELATION TO RSIF INTO ROB ADDITIVE

*---------PRENOSIMO RADNI NALOG
SELECT PRONAL
SET ORDER TO 1
SEEK MRNAL
IF FOUND()
   DO WHILE.NOT.EOF()
      IF RNAL<>MRNAL
         EXIT
      ENDIF      
      MKOL=KOL
      MDAT0=DAT0
      MDAT1=DAT1
      MRCENA=RCENA
      SELECT KOCKA
      APPEND BLANK
      replace rnal WITH mrnal
      REPLACE NORMATIV WITH MNORMATIV
      REPLACE RSIF WITH MRSIF
      REPLACE SSIF WITH MRSIF
      REPLACE DAT0 WITH MDAT0
      REPLACE DAT1 WITH MDAT1
      REPLACE OPIS WITH '            '
      REPLACE DCENA WITH MRCENA
      REPLACE KOLR WITH MKOL
      REPLACE DIZNOS WITH ROUND(KOLR*DCENA,3)
      REPLACE MSIFNAZ WITH ROB.NAZ
      REPLACE RMESTO WITH '      '
      REPLACE GRUPA WITH '0'
      SELECT PRONAL
      SKIP
   ENDDO   
ENDIF
SELECT KOCKA

*--------PRENOSIMO OPIS RADNOG NALOGA
SELECT PRONLOP
SEEK MRNAL
IF FOUND()
   DO WHILE.NOT.EOF()
      IF RNAL<>MRNAL
         EXIT
      ENDIF      
      MOPIS=OPIS
      SELECT KOCKA
      APPEND BLANK
      replace rnal WITH mrnal
      REPLACE RSIF WITH MRSIF
      REPLACE NORMATIV WITH MNORMATIV
      REPLACE POMOPIS WITH MOPIS
      REPLACE RMESTO WITH '      '
      REPLACE GRUPA WITH ' '
      SELECT PRONLOP
      SKIP
   ENDDO   
ENDIF
SELECT KOCKA

*----------PRENOS OPISA NORMATIVA----------
SELECT PRONROP
SEEK MNORMATIV
DO WHILE.NOT.EOF()
   IF NORMATIV<>MNORMATIV
      EXIT
   ENDIF
   MOPIS=OPIS
   SELECT KOCKA
   APPEND BLANK
   REPLACE RSIF WITH MRSIF
   REPLACE NORMATIV WITH MNORMATIV
   REPLACE POMOPIS WITH MOPIS
   REPLACE GRUPA WITH '0'
   REPLACE RSIF WITH MRSIF
   REPLACE RMESTO WITH '000000'
   SELECT PRONROP
   SKIP
ENDDO      
SELECT KOCKA 

*--------PRENOSIMO NORMATIV RADA
SELECT PRONORMA
SEEK MNORMATIV
IF FOUND()
   DO WHILE.NOT.EOF()
      IF NORMATIV<>MNORMATIV
         EXIT
      ENDIF
      IF LDSIF<>SPACE(5)
         SCATTER NAME POLJA   
         SELECT KOCKA
         APPEND BLANK
         GATHER NAME POLJA
         REPLACE RMESTO WITH PRORAD.RMESTO
         REPLACE SRRADA WITH PRORAD.SRRADA
         REPLACE KOEFIC WITH PRORAD.KOEFIC
         REPLACE KOL WITH KOL*MRKOL
         REPLACE IZNOS WITH KOL*CENA
         SELECT PRONORMA   
      ENDIF    
      SKIP
   ENDDO   
ENDIF
SELECT KOCKA
INDEX on RMESTO+GRUPA+LDSIF TAG RMESTO
INDEX ON OPIS TAG OPIS
INDEX ON GRUPA TAG GRUPA
SET ORDER TO 1
GO TOP

MRSIF=RSIF
SELECT PRONORMA
SET RELATION TO
SELECT PRORAD
SET RELATION TO
*--------PRENOS OPISA RADNIH OPERACIJA
SELECT PRONORMA
SEEK MNORMATIV
IF FOUND()
   DO WHILE.NOT.EOF()
      IF NORMATIV<>MNORMATIV
         EXIT
      ENDIF
      IF LDSIF<>SPACE(5)
         MLDSIF=LDSIF
         SELECT PRORAD
         SEEK MLDSIF
         IF FOUND()
            MLDSIF=LDSIF
            MRMESTO=RMESTO
            MKOEFIC=KOEFIC
            MSRRADA=SRRADA
            SELECT PRORADOP
            SEEK MLDSIF
            IF FOUND()
               DO WHILE.NOT.EOF()
                  IF LDSIF<>MLDSIF
                     EXIT
                  ENDIF   
                  MOPIS=OPIS
                  IF OPIS<>SPACE(60)
                     SELECT KOCKA
                     APPEND BLANK
                     REPLACE LDSIF WITH MLDSIF
                     REPLACE RSIF WITH MRSIF
                     REPLACE NORMATIV WITH MNORMATIV
                     REPLACE POMOPIS WITH MOPIS
                     REPLACE GRUPA WITH 'E'
                     REPLACE RSIF WITH MRSIF
                     REPLACE RMESTO WITH MRMESTO
                     SELECT PRORADOP
                  ENDIF
                  SKIP
               ENDDO      
            ENDIF
         ENDIF 
      ENDIF
      SELECT PRONORMA
      SKIP
   ENDDO
ENDIF      
*------------------------------------
SELECT KOCKA
SET ORDER TO 1
GO TOP
*REPORT FORM PRONAL0RAD PREVIEW
   mfile='PRONAL0RAD' 
   uslov=""
   DO printer_bullzip WITH mdata02,mfile,uslov

USE
SELECT PRONAL
SET RELATION TO RSIF INTO rob additive
SET RELATION TO NORMATIV INTO PRONORMA ADDITIVE
SET RELATION TO RNAL INTO PRONLOP ADDITIVE
SET ORDER TO 
PRONAL.GRD0.SETFOCUS
PRONAL.REFRESH
POP KEY
