SELECT PRONALVC
SET ORDER TO 
GO BOTTOM
IF RECCOUNT()>0
   MDAT0=DAT0
   MDAT1=DAT1
ELSE
   MDAT0=DATE()
   MDAT1=DATE()
ENDIF      
APPEND BLANK
PRONALVC.GRD0.REFRESH
REPLACE DAT0 WITH MDAT0
REPLACE DAT1 WITH MDAT1
PRONALVC.GRD0.COLUMN1.SETFOCUS
