PUSH KEY CLEAR
SELECT PRONLOP
MREC=RECNO()
USE
USE PRONLOPP IN 0 EXCLUSIVE ORDER 1 ALIAS PRONLOP
SELECT PRONLOP
DELETE ALL FOR RECNO()=MREC
PACK
USE
USE PRONLOPP IN 0 ORDER 1 ALIAS PRONLOP
SELECT PRONLOP
PRONLOPP.RELEASE
POP KEY
KEYBOARD '{ENTER}'

