USE PRONALVC IN 0
SELECT PRONALV
GO TOP
DO WHILE.NOT.EOF()
   MDATDOK=DATDOK
   MCENARADA=0
   MKOEFNS=0
   SELECT PRONALVC
   DO WHILE.NOT.EOF()
      IF MDATDOK>=DAT0.AND.MDATDOK<=DAT1
         MCENARADA=CENARADA
         MKOEFNS=KOEFNS
         EXIT
      ENDIF   
      SKIP
   ENDDO
   SELECT PRONALV   
   REPLACE STARTBOD WITH LDRAD.STARTBOD
   REPLACE CENARADA WITH MCENARADA
   REPLACE KOEFNS WITH MKOEFNS
   REPLACE CASUK WITH CASEFE+CASREZ
   REPLACE DINEFE WITH CASEFE*STARTBOD*CENARADA
   REPLACE DINREZ WITH CASREZ*STARTBOD*CENARADA
   REPLACE DINUK WITH DINEFE+DINREZ
   REPLACE BRUTONS WITH DINUK*KOEFNS
   SKIP
ENDDO
SELECT PRONALVC
USE
SELECT PRONALV
GO TOP   
