PARAMETERS MDAT0,MDAT1,MSVE
DO IDEL WITH (KKOCKAX)
DO IDEL WITH (KKOCKAX2)
SELECT PRONAL
SET RELATION TO
SET ORDER TO 
SELECT PRONORMA 
SET ORDER TO 3
COPY STRUCTURE TO &KKOCKA
USE &KKOCKA IN 0 EXCLUSIVE ALIAS KOCKA
SELECT PRONAL
GO TOP
DO WHILE.NOT.EOF()
   IF DAT0>=MDAT0.AND.DAT0<=MDAT1
      MNORMATIV=NORMATIV
      MRNAL=RNAL
      MKOL=KOL
      SELECT PRONORMA
      SEEK MNORMATIV
      IF FOUND()
         DO WHILE.NOT.EOF()
            IF NORMATIV<>MNORMATIV
               EXIT
            ENDIF
            IF PSIF<>SPACE(5).OR.MSIF<>SPACE(5).OR.PMSIF<>SPACE(5).OR.ASIF<>SPACE(5)
               SCATTER NAME POLJA
               SELECT KOCKA
               APPEND BLANK
               GATHER NAME POLJA   
               REPLACE KOL WITH KOL*MKOL
               REPLACE IZNOS WITH KOL*CENA
               REPLACE RNAL WITH MRNAL
               SELECT PRONORMA
            ENDIF      
            SKIP
         ENDDO   
      ENDIF
   ENDIF
   SELECT PRONAL
   SKIP
ENDDO   
SELECT KOCKA
*--------------------ZAVRSENO JE PREUZIMANJE IZ NORMATIVA-------


*-------------PREUZIMAMO IZ FAKTURA

USE PROPAR IN 0 
SELECT PROPAR


SELECT PROPAR
MMAGGOT=ALLTRIM(MAGGOT)
MMAGPOLU=ALLTRIM(MAGPOLU)
MMAGMAT=ALLTRIM(MAGMAT)
MMAGPMAT=ALLTRIM(MAGPMAT)
MMAGAMB=ALLTRIM(MAGAMB)
USE
*----------UNOSIMO POLUPROIZVODE----------
KKFAK='FAK'+MMAGPOLU+'.DBF'
KKFAKG='FAKG'+MMAGPOLU+'.DBF'
KFAK='FAK'+MMAGPOLU
KFAKG='FAKG'+MMAGPOLU

IF FILE(KKFAK)
   USE &KFAK IN 0 ORDER 1 ALIAS FAK
   SELECT FAK

   USE &KFAKG IN 0 ORDER 1 ALIAS FAKG
   SELECT FAKG
    
   USE AATV IN 0
   SELECT AATV
   LOCATE FOR ALLTRIM(SIFPROD)=ALLTRIM(mMAGPOLU)
   IF FOUND()
      IF SIFARNIK<>'  '
         PROMAT='ROB'+ALLTRIM(SIFARNIK)
      ELSE
         PROMAT='ROB'
      ENDIF    
      IF TFPOSSIF='D'
         PROMAT='ROBV'+ALLTRIM(SIFPROD)
      ENDIF
   ENDIF
   USE
   
   
   USE &PROMAT IN 0 ALIAS AROB ORDER 1
   SELECT FAK
   SET RELATION TO BRKAL INTO FAKG ADDITIVE
   SET RELATION TO RSIF INTO AROB ADDITIVE
   GO TOP
   DO WHILE.NOT.EOF()
      SELECT FAK
      IF FAKG.DATDOK>=MDAT0.AND.FAKG.DATDOK<=MDAT1
      IF FAKG.RNAL<>SPACE(12)
         MTVKOL=KOLI
         MTVCENA=CENA
         MPSIF=RSIF
         MRNAL=FAKG.RNAL
         MNAZ=AROB.NAZ
         SELECT KOCKA
         APPEND BLANK
         REPLACE RNAL WITH MRNAL
         REPLACE PSIF WITH MPSIF
         REPLACE SSIF WITH MPSIF
         REPLACE MSIFNAZ WITH MNAZ
         REPLACE TVKOL WITH MTVKOL
         REPLACE TVCENA WITH MTVCENA
         REPLACE TVIZNOS WITH MTVKOL*MTVCENA
         REPLACE GRUPA WITH 'A'
      ENDIF
      ENDIF
      SELECT FAK
      SKIP
   ENDDO   
ENDIF
SELECT FAK
USE
SELECT FAKG
USE
SELECT AROB
USE
*----------UNOSIMO OSNOVNI MATERIJAL----------
KFAK='FAK'+MMAGMAT
KFAKG='FAKG'+MMAGMAT
KKFAK='FAK'+MMAGMAT+'.DBF'
KKFAKG='FAKG'+MMAGMAT+'.DBF'

IF FILE(KKFAK)
   USE AATV IN 0
   SELECT AATV
   LOCATE FOR ALLTRIM(SIFPROD)=ALLTRIM(mMAGMAT)
   IF FOUND()
      IF SIFARNIK<>'  '
         PROMAT='ROB'+ALLTRIM(SIFARNIK)
      ELSE
         PROMAT='ROB'
      ENDIF    
      IF TFPOSSIF='D'
        PROMAT='ROBV'+ALLTRIM(SIFPROD)
      ENDIF
   ENDIF
   
   USE
   USE &PROMAT IN 0 ALIAS AROB ORDER 1
   USE &KFAK IN 0 ORDER 1 ALIAS FAK
   SELECT FAK
   
   USE &KFAKG IN 0 ORDER 1 ALIAS FAKG
   SELECT FAKG

   SELECT FAK
   SET RELATION TO BRKAL INTO FAKG ADDITIVE
   SET RELATION TO RSIF INTO AROB ADDITIVE
   GO TOP
   DO WHILE.NOT.EOF()
      SELECT FAK
      IF FAKG.DATDOK>=MDAT0.AND.FAKG.DATDOK<=MDAT1
      IF FAKG.RNAL<>SPACE(12)
         MTVKOL=KOLI
         MTVCENA=CENA
         MMSIF=RSIF
         MRNAL=FAKG.RNAL
         MNAZ=AROB.NAZ
         SELECT KOCKA
         APPEND BLANK
         REPLACE RNAL WITH MRNAL
         REPLACE MSIF WITH MMSIF
         REPLACE SSIF WITH MMSIF
         REPLACE MSIFNAZ WITH MNAZ
         REPLACE TVKOL WITH MTVKOL
         REPLACE TVCENA WITH MTVCENA
         REPLACE TVIZNOS WITH MTVKOL*MTVCENA
         REPLACE GRUPA WITH 'B'
      ENDIF
      ENDIF
      SELECT FAK
      SKIP
   ENDDO   
ENDIF
SELECT FAK
USE
SELECT FAKG
USE
SELECT AROB
USE
*----------UNOSIMO POMOCNI MATERIJAL---------
KFAK='FAK'+MMAGPMAT
KFAKG='FAKG'+MMAGPMAT
KKFAK='FAK'+MMAGPMAT+'.DBF'
KKFAKG='FAKG'+MMAGPMAT+'.DBF'
IF FILE(KKFAK)
   USE AATV IN 0
   SELECT AATV
   LOCATE FOR ALLTRIM(SIFPROD)=ALLTRIM(mMAGPMAT)
   IF FOUND()
      IF SIFARNIK<>'  '
         PROMAT='ROB'+ALLTRIM(SIFARNIK)
      ELSE
         PROMAT='ROB'
      ENDIF    
      IF TFPOSSIF='D'
         PROMAT='ROBV'+ALLTRIM(SIFPROD)
      ENDIF
   ENDIF
   USE

   USE &PROMAT IN 0 ALIAS AROB ORDER 1
   USE &KFAK IN 0 ORDER 1 ALIAS FAK
   SELECT FAK
   USE &KFAKG IN 0 ORDER 1 ALIAS FAKG
   SELECT FAKG
   SELECT FAK
   SET RELATION TO BRKAL INTO FAKG ADDITIVE
   SET RELATION TO RSIF INTO AROB ADDITIVE
   GO TOP
   DO WHILE.NOT.EOF()
      SELECT FAK
      IF FAKG.DATDOK>=MDAT0.AND.FAKG.DATDOK<=MDAT1
      IF FAKG.RNAL<>SPACE(12)
         MTVKOL=KOLI
         MTVCENA=CENA
         MPMSIF=RSIF
         MRNAL=FAKG.RNAL
         MNAZ=AROB.NAZ
         SELECT KOCKA
         APPEND BLANK
         REPLACE RNAL WITH MRNAL
         REPLACE PMSIF WITH MPMSIF
         REPLACE SSIF WITH MPMSIF
         REPLace msifnaz WITH mnaz
         REPLACE TVKOL WITH MTVKOL
         REPLACE TVCENA WITH MTVCENA
         REPLACE TVIZNOS WITH MTVKOL*MTVCENA
         REPLACE GRUPA WITH 'C'
      ENDIF
      ENDIF
      SELECT FAK
      SKIP
   ENDDO   
ENDIF
SELECT FAK
USE
SELECT FAKG
USE
SELECT AROB
USE

*----------UNOSIMO AMBALAZU---------
KFAK='FAK'+MMAGAMB
KFAKG='FAKG'+MMAGAMB
KKFAK='FAK'+MMAGAMB+'.DBF'
KKFAKG='FAKG'+MMAGAMB+'.DBF'
IF FILE(KKFAK)
   USE AATV IN 0
   SELECT AATV
   LOCATE FOR ALLTRIM(SIFPROD)=ALLTRIM(mMAGAMB)
   IF FOUND()
      IF SIFARNIK<>'  '
         PROMAT='ROB'+ALLTRIM(SIFARNIK)
      ELSE
         PROMAT='ROB'
      ENDIF    
      IF TFPOSSIF='D'
         PROMAT='ROBV'+ALLTRIM(SIFPROD)
      ENDIF
   ENDIF
   USE
   USE &PROMAT IN 0 ALIAS AROB ORDER 1
   USE &KFAK IN 0 ORDER 1 ALIAS FAK
   SELECT FAK
   USE &KFAKG IN 0 ORDER 1 ALIAS FAKG
   SELECT FAKG

   SELECT FAK
   SET RELATION TO BRKAL INTO FAKG ADDITIVE
   SET RELATION TO rsif INTO AROB ADDITIVE
   GO TOP
   DO WHILE.NOT.EOF()
      SELECT FAK
      IF FAKG.RNAL<>SPACE(12)
      IF FAKG.DATDOK>=MDAT0.AND.FAKG.DATDOK<=MDAT1
         MTVKOL=KOLI
         MTVCENA=CENA
         MASIF=RSIF
         MRNAL=FAKG.RNAL
         MNAZ=AROB.NAZ
         SELECT KOCKA
         APPEND BLANK
         REPLACE RNAL WITH MRNAL
         REPLACE ASIF WITH MASIF
         REPLACE SSIF WITH MASIF
         REPLACE MSIFNAZ WITH MNAZ
         REPLACE TVKOL WITH MTVKOL
         REPLACE TVCENA WITH MTVCENA
         REPLACE TVIZNOS WITH MTVKOL*MTVCENA
         REPLACE GRUPA WITH 'D'
      ENDIF
      ENDIF 
      SELECT FAK
      SKIP
   ENDDO   
ENDIF
SELECT FAK
USE
SELECT FAKG
USE
SELECT AROB
USE
SELECT KOCKA
INDEX ON RNAL+GRUPA+PSIF+MSIF+PMSIF+ASIF TAG RRNAL
SET ORDER TO 1
TOTAL ON RNAL+GRUPA+PSIF+MSIF+PMSIF+ASIF TO &KKOCKA2 FIELDS KOL,IZNOS,TVKOL,TVIZNOS
DELETE ALL
PACK

APPEND FROM &KKOCKA2
GO TOP
PUBLIC ADAT0,ADAT1
ADAT0=MDAT0
ADAT1=MDAT1
IF MSVE=1
   *REPORT FORM PRONALSLAG0 PREVIEW
   mfile='PRONALSLAG0' 
   uslov=""
   DO printer_bullzip WITH mdata02,mfile,uslov
   
ELSE
   *REPORT FORM PRONALSLAG0 PREVIEW FOR (KOL<>TVKOL).OR.(IZNOS<>TVIZNOS)
   mfile='PRONALSLAG0' 
   uslov="(KOL<>TVKOL).OR.(IZNOS<>TVIZNOS)"
   DO printer_bullzip WITH mdata02,mfile,uslov
   
ENDIF
SELECT KOCKA
USE
SELECT PRONAL
SET RELATION TO RSIF INTO rob additive
SET RELATION TO NORMATIV INTO PRONORMA ADDITIVE
SET RELATION TO RNAL INTO PRONLOP ADDITIVE
GO TOP
