PUSH KEY CLEAR
SELECT PRONALBR
GO BOTTOM
MRNAL=RNAL
MNLEN=LEN(ALLTRIM(STR(VAL(ALLTRIM(MRNAL))+1,6,0)))
MNRNAL=REPLI('0',6-MNLEN)+ALLTRIM(STR(VAL(ALLTRIM(MRNAL))+1,6,0))
APPEND BLANK
REPLACE RNAL WITH MNRNAL
REPLACE OPER WITH AAOPER
PRONALBR.GRD0.SETFOCUS
POP KEY
