PUSH KEY CLEAR
MRNAL=RNAL
SET ORDER TO 1
SEEK MRNAL
IF FOUND()
   DO WHILE.NOT.EOF()
      IF RNAL<>MRNAL
         EXIT
      ENDIF
      REPLACE ARHIVA WITH ' '   
      SKIP
   ENDDO   
ENDIF
SEEK MRNAL
SET ORDER TO 
POP KEY