PUSH KEY CLEAR
SET EXACT ON
SELECT PRONORMA
MPSIF=PSIF
MNORMATIV=NORMATIV
SET ORDER TO 3
SEEK MNORMATIV
DO WHILE.NOT.EOF()
   IF NORMATIV<>MNORMATIV
      EXIT
   ENDIF   
IF MSIF<>SPACE(5)
REPLACE MSIFNAZ WITH PROMAT.NAZ
REPLACE SSIF WITH PROMAT.MSIF
replace OPIS WITH 'OSNOVNI MATERIJAL'
REPLACE GRUPA WITH 'B'
ENDIF
IF PMSIF<>SPACE(5)
REPLACE MSIFNAZ WITH PROPMAT.NAZ
REPLACE SSIF WITH PROPMAT.PMSIF
replace OPIS WITH 'POMOÆNI MATERIJAL'
REPLACE GRUPA WITH 'C'
ENDIF
IF ASIF<>SPACE(5)
REPLACE MSIFNAZ WITH PROAMB.NAZ
REPLACE SSIF WITH PROAMB.ASIF
replace OPIS WITH 'AMBALAŽA'
REPLACE GRUPA WITH 'D'
ENDIF

IF LDSIF<>SPACE(5)
REPLACE MSIFNAZ WITH PRORAD.NAZ
REPLACE SSIF WITH PRORAD.LDSIF
replace OPIS WITH 'RAD'
REPLACE GRUPA WITH 'E'
ENDIF
IF DIRSIF<>SPACE(5)
REPLACE MSIFNAZ WITH PRODIR.NAZ
REPLACE SSIF WITH PRODIR.DIRSIF
replace OPIS WITH 'DIREKTNI TROŠKOVI'
REPLACE GRUPA WITH 'F'
ENDIF

IF OPSSIF<>SPACE(5)
REPLACE MSIFNAZ WITH PROOPS.NAZ
REPLACE SSIF WITH PROOPS.OPSSIF
replace OPIS WITH 'OPŠTI TROŠKOVI'
REPLACE GRUPA WITH 'G'
ENDIF
SKIP

ENDDO
SELECT PRONORMA
GO TOP
SEEK MNORMATIV
SET ORDER TO 4
*REPORT FORM PRONORMA0P  FOR NORMATIV=MNORMATIV PREVIEW
   mfile='PRONORMA0P'    
   uslov="NORMATIV=MNORMATIV"
   DO printer_bullzip WITH mdata02,mfile,uslov

SET ORDER TO 3
SEEK MNORMATIV
SET ORDER TO 
PRONORMAP.GRD0.SetFocus 
POP KEY
PRONORMAP.Refresh

