PUSH KEY CLEAR
IF RECCOUNT()<1
SELECT PRONAl
SET RELATION TO
DO FORM PRONALBR
SELECT PRONAL
SET RELATION TO RSIF INTO rob additive
SET RELATION TO NORMATIV INTO PRONORMA ADDITIVE
PRONALL.GRD0.SETFOCUS
PRONALL.REFRESH
endif
POP KEY