PUSH KEY CLEAR
SET EXACT ON
SELECT PRONORMA
MRSIF=RSIF
MNORMATIV=NORMATIV
SET ORDER TO 3
SEEK MNORMATIV
DO WHILE.NOT.EOF()
   IF NORMATIV<>MNORMATIV
      EXIT
   ENDIF   
IF PSIF<>SPACE(5)
REPLACE MSIFNAZ2 WITH PROPOLU.NAZ2
REPLACE SSIF2 WITH PROPOLU.PODNAZIV
replace OPIS WITH 'POLUPROIZVODI'
REPLACE GRUPA WITH 'A'
ENDIF
IF MSIF<>SPACE(5)
REPLACE MSIFNAZ2 WITH PROMAT.NAZ2
REPLACE SSIF2 WITH PROMAT.PODNAZIV
replace OPIS WITH 'OSNOVNI MATERIJAL'
REPLACE GRUPA WITH 'B'
ENDIF
IF PMSIF<>SPACE(5)
REPLACE MSIFNAZ2 WITH PROPMAT.NAZ2
REPLACE SSIF2 WITH PROPMAT.PODNAZIV
replace OPIS WITH 'POMOÆNI MATERIJAL'
REPLACE GRUPA WITH 'C'
ENDIF
IF ASIF<>SPACE(5)
REPLACE MSIFNAZ2 WITH PROAMB.NAZ2
REPLACE SSIF2 WITH PROAMB.PODNAZIV
replace OPIS WITH 'AMBALAŽA'
REPLACE GRUPA WITH 'D'
ENDIF

IF LDSIF<>SPACE(5)
REPLACE MSIFNAZ2 WITH PRORAD.NAZ
REPLACE SSIF2 WITH PRORAD.LDSIF
replace OPIS WITH 'RAD'
REPLACE GRUPA WITH 'E'
ENDIF
IF DIRSIF<>SPACE(5)
REPLACE MSIFNAZ2 WITH PRODIR.NAZ
REPLACE SSIF2 WITH PRODIR.DIRSIF
replace OPIS WITH 'DIREKTNI TROŠKOVI'
REPLACE GRUPA WITH 'F'
ENDIF

IF OPSSIF<>SPACE(5)
REPLACE MSIFNAZ2 WITH PROOPS.NAZ
REPLACE SSIF2 WITH PROOPS.OPSSIF
replace OPIS WITH 'OPŠTI TROŠKOVI'
REPLACE GRUPA WITH 'G'
ENDIF
SKIP

ENDDO
GO TOP
SEEK MNORMATIV
SET ORDER TO 4
*REPORT FORM PRONORMA0DN FOR NORMATIV=MNORMATIV PREVIEW
   mfile='PRONORMA0DN' 
   uslov="NORMATIV=MNORMATIV"
   DO printer_bullzip WITH mdata02,mfile,uslov

SET ORDER TO 3
SEEK MNORMATIV
SET ORDER TO 
IF MNOR=1
   PRONORMA.GRD0.SetFocus 
   PRONORMA.Refresh
ELSE
   PRONORMAL.GRD0.SetFocus 
   PRONORMAL.Refresh
ENDIF
POP KEY

