PUSH KEY CLEAR
MRNAL=RNAL
SELECT PRONORMA
DO IDEL WITH (KKOCKAX)
DO IDEL WITH (KKOCKAX2)
USE prorad IN 0 ORDER 1
COPY STRUCTURE TO &KKOCKA
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
SELECT PRONAL
MPSIF=PSIF
SET ORDER TO 1
SEEK MRNAL

PUBLIC ANAZ,ABARKOD,AJED,AKOL
ANAZ=''
ABARKOD=''
AJED=''
AKOL=0
SELECT PROPOLU
SEEK MPSIF
IF FOUND()
   ANAZ=NAZ
   ABARKOD=BARKOD
   AJED=JED
ENDIF
SELECT PRONAL
SET ORDER TO 1
SEEK MRNAL
IF FOUND()
   AKOL=KOL
ENDIF
SEEK MRNAL
IF FOUND()
   DO WHILE.NOT.EOF()
     IF RNAL<>MRNAL
        EXIT
     ENDIF      
     MPSIF=PSIF
     MKOL=KOL
     MNORMATIV=NORMATIV
     SELECT PRONORMA
     SET ORDER TO 3
     SEEK MNORMATIV
     IF FOUND()
        DO WHILE.NOT.EOF()
           IF NORMATIV<>MNORMATIV
              EXIT
           ENDIF
           MKOL=KOL
           MDAT0=DAT0
           MDAT1=DAT1
           MRCENA=RCENA
           SCATTER NAME POLJA
           IF ldsif<>SPACE(5)
              M2KOL=KOL
              MLDSIF=LDSIF
              SELECT KOCKA
              APPEND BLANK
              GATHER NAME POLJA 
              SELECT PRORAD
              SEEK MLDSIF
              IF FOUND()
                 MIZNOS=M2KOL*CENA
                 MMSIFNAZ=PRORAD.NAZ
                 MBARKOD=BARKOD
                 SELECT KOCKA
                 REPLACE KOL WITH M2KOL*AKOL
                 REPLACE MSIFNAZ WITH MMSIFNAZ
                 REPLACE IZNOS WITH MIZNOS
                 REPLACE BARKOD WITH MBARKOD
              ENDIF
           ENDIF
           SELECT PRONORMA
           SKIP
        ENDDO   
     ENDIF
     SELECT PRONAL
     SKIP
   ENDDO   
ENDIF   

SELECT PRORAD
USE
SELECT PRONAL
SET ORDER TO 1
SEEK MRNAL
SELECT KOCKA
GO TOP
*REPORT FORM PRONAL03P PREVIEW
   mfile='PRONAL03P' 
   uslov=""
   DO printer_bullzip WITH mdata02,mfile,uslov

USE
SELECT PRONAL
SET ORDER TO 
PRONALP.GRD0.SETFOCUS
POP KEY
PRONALP.REFRESH
