PUSH KEY CLEAR
SELECT PRONROP
MREC=RECNO()
USE
USE PRONROPp IN 0 EXCLUSIVE ORDER 1 ALIAS PRONROP
SELECT PRONROP
DELETE ALL FOR RECNO()=MREC
PACK
USE
USE PRONROPP IN 0 ORDER 1 ALIAS PRONROP
SELECT PRONROP
PRONROPP.RELEASE
POP KEY
KEYBOARD '{ENTER}'

