PUSH KEY CLEAR
SET EXACT ON
DO IDEL WITH (KKOCKAX)
SELECT PRONORMA
MRSIF=RSIF
MNORMATIV=NORMATIV
SET ORDER TO 3
SEEK MNORMATIV
DO WHILE.NOT.EOF()
   IF NORMATIV<>MNORMATIV
      EXIT
   ENDIF   
   IF LDSIF<>SPACE(5)
      REPLACE MSIFNAZ WITH PRORAD.NAZ
      REPLACE SSIF WITH PRORAD.LDSIF
      replace OPIS WITH 'RAD'
      REPLACE GRUPA WITH 'E'
      REPLACE RMESTO WITH '000001'
   ENDIF
   SKIP
ENDDO

SELECT PRONORMA
COPY STRUCTURE TO &KKOCKA
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
SELECT PRONORMA
SEEK MNORMATIV
IF FOUND()
   DO WHILE.NOT.EOF()
      IF NORMATIV<>MNORMATIV
         EXIT
      ENDIF
      IF LDSIF<>SPACE(5)
         SCATTER NAME POLJA   
         SELECT KOCKA
         APPEND BLANK
         GATHER NAME POLJA
         REPLACE RMESTO WITH PRORAD.RMESTO
         REPLACE SRRADA WITH PRORAD.SRRADA
         REPLACE KOEFIC WITH PRORAD.KOEFIC
         SELECT PRONORMA   
      ENDIF    
      SKIP
   ENDDO   
ENDIF
SELECT KOCKA
INDEX on RMESTO+GRUPA+LDSIF TAG GRUPA
SET ORDER TO 1
GO TOP
MRSIF=RSIF
SELECT PRONORMA
SET RELATION TO
SELECT PRORAD
SET RELATION TO
*----------PRENOS OPISA NORMATIVA----------
SELECT PRONROP
SEEK MNORMATIV
DO WHILE.NOT.EOF()
   IF NORMATIV<>MNORMATIV
      EXIT
   ENDIF
   MOPIS=OPIS
   SELECT KOCKA
   APPEND BLANK
   REPLACE NORMATIV WITH MNORMATIV
   REPLACE POMOPIS WITH MOPIS
   REPLACE GRUPA WITH '0'
   REPLACE RSIF WITH MRSIF
   REPLACE RMESTO WITH '000000'
   SELECT PRONROP
   SKIP
ENDDO      
*--------PRENOS OPISA RADNIH OPERACIJA
SELECT PRONORMA
SEEK MNORMATIV
IF FOUND()
   DO WHILE.NOT.EOF()
      IF NORMATIV<>MNORMATIV
         EXIT
      ENDIF
      IF LDSIF<>SPACE(5)
         MLDSIF=LDSIF
         SELECT PRORAD
         SEEK MLDSIF
         IF FOUND()
            MLDSIF=LDSIF
            MRMESTO=RMESTO
            MKOEFIC=KOEFIC
            MSRRADA=SRRADA
            SELECT PRORADOP
            SEEK MLDSIF
            IF FOUND()
               DO WHILE.NOT.EOF()
                  IF LDSIF<>MLDSIF
                     EXIT
                  ENDIF   
                  MOPIS=OPIS
                  IF OPIS<>SPACE(60)
                     SELECT KOCKA
                     APPEND BLANK
                     REPLACE LDSIF WITH MLDSIF
                     REPLACE NORMATIV WITH MNORMATIV
                     REPLACE POMOPIS WITH MOPIS
                     REPLACE GRUPA WITH 'E'
                     REPLACE RSIF WITH MRSIF
                     REPLACE RMESTO WITH MRMESTO
                     SELECT PRORADOP
                  ENDIF
                  SKIP
               ENDDO      
            ENDIF
         ENDIF 
      ENDIF
      SELECT PRONORMA
      SKIP
   ENDDO
ENDIF      

SELECT KOCKA
GO TOP
SET RELATION TO RSIF INTO ROB
SET RELATION TO LDSIF INTO PRORAD
GO TOP

*REPORT FORM PRONORMA0PROS PREVIEW
   mfile='PRONORMA0PROS' 
   uslov=""
   DO printer_bullzip WITH mdata02,mfile,uslov

SELECT KOCKA
USE
SELECT PRONORMA
SET ORDER TO 3
SEEK MNORMATIV
SET ORDER TO 
SELECT PRORAD
SET RELATION TO LDSIF INTO PRORADOP ADDITIVE
SELECT PRONORMA
SET RELATION TO RSIF INTO rob additive
sET RELATION TO psif INTO PROpolu additive
SET RELATION TO msif INTO PROmat additive
SET RELATION TO ldsif INTO prorad additive
SET RELATION TO dirsif INTO proDIR additive
SET RELATION TO opssif INTO proOPS additive
SET RELATION TO PMSIF INTO proPMAT additive
SET RELATION TO ASIF INTO proAMB additive
SET RELATION TO NORMATIV INTO PRONROP ADDITIVE
PRONORMA.GRD0.SetFocus 
POP KEY
PRONORMA.Refresh

