PUSH KEY CLEAR
PUBLIC ARNAL,ADAT0,ADAT1
MRNAL=RNAL
ARNAL=RNAL
ADAT0=DAT0
ADAT1=DAT1
PUBLIC ARSIF,ARNAZ
ARSIF=''
ARNAZ=''
SELECT PRONORMA
DO IDEL WITH (KKOCKAX)
DO IDEL WITH (KKOCKAX2)

COPY STRUCTURE TO &KKOCKA
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
SELECT PRONAL
SET ORDER TO 1
SEEK MRNAL
IF FOUND()
   ARSIF=PSIF
   ARNAZ=PROPOLU.NAZ
   DO WHILE.NOT.EOF()
     IF RNAL<>MRNAL
        EXIT
     ENDIF      
     MPSIF=PSIF
     MKOL=KOL
     MNORMATIV=NORMATIV
     SELECT PRONORMA
     SET ORDER TO 3
     SEEK MNORMATIV
     IF FOUND()
        DO WHILE.NOT.EOF()
           IF NORMATIV<>MNORMATIV
              EXIT
           ENDIF
           IF msif<>SPACE(5).or.pmsif<>SPACE(5).or.asif<>SPACE(5)
              SCATTER NAME POLJA
              SELECT KOCKA
              APPEND BLANK
              GATHER NAME POLJA 
              REPLACE KOL WITH KOL*MKOL
           endif     
           SELECT PRONORMA
           SKIP
        ENDDO   
     ENDIF
     SELECT PRONAL
     SKIP
   ENDDO   
ENDIF   
SELECT KOCKA
INDEX ON PSIF+MSIF+PMSIF+ASIF TAG OPIS
INDEX ON GRUPA TAG GRUPA
SET ORDER TO 1
TOTAL ON PSIF+MSIF+PMSIF+ASIF FIELDS KOL,IZNOS TO &KKOCKA2
DELETE ALL
PACK

SELECT KOCKA
APPEND FROM &KKOCKA2
SET ORDER TO 2
GO TOP
*REPORT FORM PRONAL02P PREVIEW
   mfile='PRONAL02P' 
   uslov=""
   DO printer_bullzip WITH mdata02,mfile,uslov

SELECT KOCKA
SET RELATION TO
USE
SELECT PRONAL
SET ORDER TO 
PRONALP.GRD0.SETFOCUS
POP KEY
PRONALP.REFRESH
