PUSH KEY CLEAR
SELECT PRONALBR
mnRNAL=RNAL
IF ARHIVA=' '
   IF ALLTRIM(OPER)=AAOPER
      LOCATE FOR rnal=MNrnal
      IF.NOT.FOUND()
         APPEND BLANK
         REPLACE rnal WITH MNrnal
         REPLACE OPER WITH AAOPER
      ENDIF      
      pronalbr.grd0.setfocus
      pronalbr.refresh
      SELECT PRONAL
      APPEND BLANK
      REPLACE RNAL WITH MNRNAL
      REPLACE DAT0 WITH DATE()
      REPLACE DAT1 WITH DATE()
      REPLACE DATZAVR WITH DATE()
      PRONALBR.RELEASE
      PRONALL.GRD0.SETFOCUS
      PRONALL.GRD0.refresh
   ELSE
      PUBLIC PPORUKA
      PPORUKA=' RADNI NALOG '+MNRNAL+' JE OTVORIO DRUGI OPERATER-OTVORITE NOVI '
      DO FORM PORUKA
      PRONALBR.GRD0.RECORDSOURCE='PRONALBR'
      PRONALBR.GRD0.COLUMN1.CONTROLSOURCE='RNAL'
      PRONALBR.GRD0.COLUMN1.SETFOCUS
      PRONALBR.GRD0.REFRESH
      PRONALBR.REFRESH
   ENDIF
ELSE
   PUBLIC PPORUKA
   PPORUKA=' RADNI NALOG '+MNRNAL+' JE PROKNJIZEN  OTVORITE NOVI '
   DO FORM PORUKA
   SELECT PRONALBR
   PRONALBR.GRD0.RECORDSOURCE='PRONALBR'
   PRONALBR.GRD0.COLUMN1.CONTROLSOURCE='RNAL'
   PRONALBR.GRD0.COLUMN1.SETFOCUS
   PRONALBR.GRD0.REFRESH
   PRONALBR.REFRESH
ENDIF
POP KEY
