SELECT PRONALV
SET ORDER TO 
GO BOTTOM
IF RECCOUNT()>0
   MRNAL=RNAL
   MDATDOK=DATDOK
ELSE
   MRNAL='000000000000'
   MDATDOK=DATE()
ENDIF      
APPEND BLANK
PRONALV.GRD0.REFRESH
REPLACE RNAL WITH MRNAL
REPLACE DATDOK WITH MDATDOK
PRONALV.GRD0.COLUMN3.SETFOCUS
