PUSH KEY CLEAR

   SELECT PROOPS
   MOPSSIF=OPSSIF

   MCENA=CENA
   SELECT PRONORMA
   IF PSIF=SPACE(5).AND.MSIF=SPACE(5).AND.PMSIF=SPACE(5).AND.ASIF=SPACE(5).AND.LDSIF=SPACE(5).AND.DIRSIF=SPACE(5).AND.OPSSIF=SPACE(5)
      REPLACE OPSSIF WITH MOPSSIF
      REPLACE CENA WITH MCENA
   ENDIF
PROOPS.VISIBLE=.F.
IF MNOR=1
   PRONORMA.REFRESH
ELSE
   PRONORMAL.REFRESH
ENDIF
PROOPS.VISIBLE=.T. 
   
SELECT PROOPS
PROOPS.GRD0.COLUMN2.SETFOCUS
POP KEY
PROOPS.REFRESH