PUSH KEY CLEAR

   SELECT PROOPS
   MOPSSIF=OPSSIF

   MCENA=CENA
   SELECT PRONORMA
   IF MSIF=SPACE(5).AND.PMSIF=SPACE(5).AND.ASIF=SPACE(5).AND.LDSIF=SPACE(5).AND.DIRSIF=SPACE(5).AND.OPSSIF=SPACE(5)
      REPLACE OPSSIF WITH MOPSSIF
      REPLACE CENA WITH MCENA
   ENDIF
PROOPSP.VISIBLE=.F.
PRONORMAP.REFRESH
PROOPSP.VISIBLE=.T. 
   
SELECT PROOPS
PROOPSP.GRD0.COLUMN2.SETFOCUS
POP KEY
PROOPSP.REFRESH