PUSH KEY CLEAR

   SELECT PROPMAT
   MMSIF=PMSIF
   MCENA=PLCENA
   SELECT PRONORMA
   IF PSIF=SPACE(5).AND.MSIF=SPACE(5).AND.PMSIF=SPACE(5).AND.ASIF=SPACE(5).AND.LDSIF=SPACE(5).AND.DIRSIF=SPACE(5).AND.OPSSIF=SPACE(5)
      REPLACE PMSIF WITH MMSIF
      REPLACE CENA WITH MCENA
   ENDIF
PROPMAT.VISIBLE=.F.
IF MNOR=1
   PRONORMA.REFRESH
ELSE
   PRONORMAL.REFRESH
ENDIF
PROPMAT.VISIBLE=.T. 
   
SELECT PROPMAT
PROPMAT.GRD0.COLUMN2.SETFOCUS
POP KEY
PROPMAT.REFRESH