PUSH KEY CLEAR
SELECT PRONORMA
DO IDEL WITH (KKOCKAX)
DO IDEL WITH (KKOCKAX2)
COPY STRUCTURE TO &KKOCKA
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
SELECT PROPLAN
GO TOP
   DO WHILE.NOT.EOF()
     IF ARHIVA=' '
        MNORMATIV=NORMATIV
        MKOL=KOL
        MRNAL=RNAL
        SELECT PRONORMA
        SET ORDER TO 3
        SEEK MNORMATIV
        IF FOUND()
           DO WHILE.NOT.EOF()
              IF NORMATIV<>MNORMATIV
                 EXIT
              ENDIF
              SCATTER NAME POLJA
              IF ZADCENA<>0
                 MCENA=ZADCENA
              ELSE
                 MCENA=CENA
              ENDIF
              SELECT KOCKA
              APPEND BLANK
              GATHER NAME POLJA 
              REPLACE CENA WITH MCENA
              REPLACE KOL WITH KOL*MKOL
              REPLACE IZNOS WITH KOL*CENA  
              REPLACE RNAL WITH MRNAL
              SELECT PRONORMA
              SKIP
           ENDDO   
        ENDIF
     ENDIF
     SELECT PROPLAN
     SKIP
   ENDDO   
SELECT KOCKA
INDEX ON RNAL+OPIS TAG OPIS
INDEX ON RNAL+GRUPA+MSIFNAZ TAG GRUPA
INDEX ON RNAL+PSIF+MSIF+PMSIF+ASIF+LDSIF+DIRSIF+OPSSIF TAG SSIF
SET ORDER TO 3
TOTAL ON RNAL+PSIF+MSIF+PMSIF+ASIF+LDSIF+DIRSIF+OPSSIF  FIELDS KOL,IZNOS TO &KKOCKA2
DELETE ALL
PACK

APPEND FROM &KKOCKA2
*----------SADA PROVERAVAMO MATERIJAL NA STANJU----------------
USE PROPAR IN 0 
SELECT PROPAR

MMAGGOT=MAGGOT
MFPGOT=FPGOT

MMAGPOLU=MAGPOLU
MFPPOLU=FPPOLU

MMAGMAT=MAGMAT
MFPMAT=FPMAT

MMAGPMAT=MAGPMAT
MFPPMAT=FPPMAT

MMAGAMB=MAGAMB
MFPAMB=FPAMB
USE
*------PROVERAVAMO ROBU NA STANJU---------------
*------POLUPROIZVODI---------------------------
KFAK='FAK'+ALLTRIM(MMAGPOLU)
KFAKG='FAKG'+ALLTRIM(MMAGPOLU)

USE &KFAK IN 0 ORDER 2 ALIAS FAK
SELECT FAK

USE &KFAKG IN 0 ORDER 1 ALIAS FAKG
SELECT FAKG

SELECT FAK
SET RELATION TO BRKAL INTO FAKG

SELECT KOCKA
GO TOP
DO WHILE.NOT.EOF()
   MRNAL=RNAL
   IF PSIF<>SPACE(5)
      MPSIF=PSIF
      MNASTANJU=0
      SELECT FAK
      SEEK MPSIF
      IF FOUND()
         DO WHILE.NOT.EOF()
            IF RSIF<>MPSIF
               EXIT
            ENDIF   
            IF FAKG.RNAL=MRNAL
               MNASTANJU=MNASTANJU+KOLI
            ENDIF
            SKIP
         ENDDO   
      ENDIF
      SELECT KOCKA
      REPLACE NASTANJU WITH MNASTANJU
   ENDIF
   SKIP
ENDDO
SELECT FAK
USE
SELECT FAKG
USE
SELECT KOCKA
GO TOP

*------MATERIJAL---------------------------
KFAK='FAK'+ALLTRIM(MMAGMAT)
KFAKG='FAKG'+ALLTRIM(MMAGMAT)

USE &KFAK IN 0 ORDER 2 ALIAS FAK
SELECT FAK

USE &KFAKG IN 0 ORDER 1 ALIAS FAKG
SELECT FAKG
SELECT FAK
SET RELATION TO BRKAL INTO FAKG

SELECT KOCKA
GO TOP
DO WHILE.NOT.EOF()
   MRNAL=RNAL
   IF MSIF<>SPACE(5)
      MMSIF=MSIF
      MNASTANJU=0
      SELECT FAK
      SEEK MMSIF
      IF FOUND()
         DO WHILE.NOT.EOF()
            IF RSIF<>MMSIF
               EXIT
            ENDIF   
            IF FAKG.RNAL=MRNAL
               MNASTANJU=MNASTANJU+KOLI
            ENDIF   
            SKIP
         ENDDO   
      ENDIF
      SELECT KOCKA
      REPLACE NASTANJU WITH MNASTANJU
   ENDIF
   SKIP
ENDDO
SELECT FAK
USE
SELECT FAKG
USE
SELECT KOCKA
GO TOP

*-----POMOCNI-MATERIJAL---------------------------
KFAK='FAK'+ALLTRIM(MMAGPMAT)
KFAKG='FAKG'+ALLTRIM(MMAGPMAT)

USE &KFAK IN 0 ORDER 2 ALIAS FAK
SELECT FAK

USE &KFAKG IN 0 ORDER 1 ALIAS FAKG
SELECT FAKG
SELECT FAK
SET RELATION TO BRKAL INTO FAKG

SELECT KOCKA
GO TOP
DO WHILE.NOT.EOF()
   MRNAL=RNAL
   IF PMSIF<>SPACE(5)
      MPMSIF=PMSIF
      MNASTANJU=0
      SELECT FAK
      SEEK MPMSIF
      IF FOUND()
         DO WHILE.NOT.EOF()
            IF RSIF<>MPMSIF
               EXIT
            ENDIF   
            IF FAKG.RNAL=MRNAL
               MNASTANJU=MNASTANJU+KOLI
            ENDIF
            SKIP
         ENDDO   
      ENDIF
      SELECT KOCKA
      REPLACE NASTANJU WITH MNASTANJU
   ENDIF
   SKIP
ENDDO
SELECT FAK
USE
SELECT FAKG
USE
SELECT KOCKA
GO TOP


*-----AMBALAZA--------------------------
KFAK='FAK'+ALLTRIM(MMAGAMB)
KFAKG='FAKG'+ALLTRIM(MMAGAMB)

USE &KFAK IN 0 ORDER 2 ALIAS FAK
SELECT FAK

USE &KFAKG IN 0 ORDER 1 ALIAS FAKG
SELECT FAKG
SELECT FAK
SET RELATION TO BRKAL INTO FAKG

SELECT KOCKA
GO TOP
DO WHILE.NOT.EOF()
   MRNAL=RNAL
   IF ASIF<>SPACE(5)
      MASIF=ASIF
      MNASTANJU=0
      SELECT FAK
      SEEK MASIF
      IF FOUND()
         DO WHILE.NOT.EOF()
            IF RSIF<>MASIF
               EXIT
            ENDIF   
            IF FAKG.RNAL=MRNAL
               MNASTANJU=MNASTANJU+KOLI
            ENDIF
            SKIP
         ENDDO   
      ENDIF
      SELECT KOCKA
      REPLACE NASTANJU WITH MNASTANJU
   ENDIF
   SKIP
ENDDO
SELECT FAK
USE
SELECT FAKG
USE
SELECT KOCKA
SET ORDER TO 2
GO TOP
DO WHILE.NOT.EOF()
   REPLACE POTREBNO WITH KOL
   REPLACE RAZLIKA WITH NASTANJU-POTREBNO
   replace pnastanju WITH nastanju*cena
   replace ppotrebno WITH POTREBNO*CENA
   REPLACE PRAZLIKA WITH PNASTANJU-PPOTREBNO
   SKIP
ENDDO   
*REPORT FORM PROPLAN03 PREVIEW
   mfile='PROPLAN03'    
   uslov=""
   DO printer_bullzip WITH mdata02,mfile,uslov

USE
SELECT PROPLAN
SET ORDER TO 
PROPLAN.GRD0.SETFOCUS
PROPLAN.REFRESH
POP KEY
