PUSH KEY CLEAR

   SELECT PROPMAT
   MMSIF=PMSIF
   MCENA=PLCENA
   SELECT PRONORMA
   IF MSIF=SPACE(5).AND.PMSIF=SPACE(5).AND.ASIF=SPACE(5).AND.LDSIF=SPACE(5).AND.DIRSIF=SPACE(5).AND.OPSSIF=SPACE(5)
      REPLACE PMSIF WITH MMSIF
      REPLACE CENA WITH MCENA
   ENDIF
PROPMATP.VISIBLE=.F.
PRONORMAP.REFRESH
PROPMATP.VISIBLE=.T. 
   
SELECT PROPMAT
PROPMATP.GRD0.COLUMN2.SETFOCUS
POP KEY
PROPMATP.REFRESH