IF TFPOSSIF<>'D' 
PUSH KEY CLEAR
SELECT PROPOLU
APPEND BLANK
REPLACE Psif WITH STR(RECNO(),5,0)
REPLACE RSIF WITH PSIF
PROPOLUP.GRD0.REFRESH
DO FORM PROPOLUK
PROPOLUP.GRD0.SETFOCUS
POP KEY
PROPOLUP.REFRESH
ENDIF