PUSH KEY CLEAR
SELECT PRONORMA
DO IDEL WITH (KKOCKAX)
DO IDEL WITH (KKOCKAX2)
COPY STRUCTURE TO &KKOCKA
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
SELECT PROPLAN
GO TOP
   DO WHILE.NOT.EOF()
     MNORMATIV=NORMATIV
     MKOL=KOL
     SELECT PRONORMA
     SET ORDER TO 3
     SEEK MNORMATIV
     IF FOUND()
        DO WHILE.NOT.EOF()
           IF NORMATIV<>MNORMATIV
              EXIT
           ENDIF
           SCATTER NAME POLJA
           IF ZADCENA<>0
              MCENA=ZADCENA
           ELSE
              MCENA=CENA
           ENDIF
           SELECT KOCKA
           APPEND BLANK
           GATHER NAME POLJA 
           REPLACE CENA WITH MCENA
           REPLACE KOL WITH KOL*MKOL
           REPLACE IZNOS WITH KOL*CENA  
           SELECT PRONORMA
           SKIP
        ENDDO   
     ENDIF
     SELECT PROPLAN
     SKIP
   ENDDO   
SELECT KOCKA
INDEX ON OPIS TAG OPIS
INDEX ON GRUPA+MSIFNAZ TAG GRUPA
INDEX ON PSIF+MSIF+PMSIF+ASIF+LDSIF+DIRSIF+OPSSIF TAG SSIF
SET ORDER TO 3
TOTAL ON PSIF+MSIF+PMSIF+ASIF+LDSIF+DIRSIF+OPSSIF  FIELDS KOL,IZNOS TO &KKOCKA2
DELETE ALL
PACK

APPEND FROM &KKOCKA2
*----------SADA PROVERAVAMO MATERIJAL NA STANJU----------------
USE PROPAR IN 0 
SELECT PROPAR

MMAGGOT=MAGGOT
MFPGOT=FPGOT

MMAGPOLU=MAGPOLU
MFPPOLU=FPPOLU

MMAGMAT=MAGMAT
MFPMAT=FPMAT

MMAGPMAT=MAGPMAT
MFPPMAT=FPPMAT

MMAGAMB=MAGAMB
MFPAMB=FPAMB
USE
*------PROVERAVAMO ROBU NA STANJU---------------
*------POLUPROIZVODI---------------------------
KKAL='KAL'+ALLTRIM(MMAGPOLU)
KKALG='KALG'+ALLTRIM(MMAGPOLU)
KFAK='FAK'+ALLTRIM(MMAGPOLU)
KFAKG='FAKG'+ALLTRIM(MMAGPOLU)

USE &KKAL IN 0 ORDER 2 ALIAS KAL
SELECT KAL
USE &KFAK IN 0 ORDER 2 ALIAS FAK
SELECT FAK

SELECT KOCKA
GO TOP
DO WHILE.NOT.EOF()
   IF PSIF<>SPACE(5)
      MPSIF=PSIF
      MNASTANJU=0
      SELECT KAL
      SEEK MPSIF
      IF FOUND()
         DO WHILE.NOT.EOF()
            IF RSIF<>MPSIF
               EXIT
            ENDIF   
            MNASTANJU=MNASTANJU+KOL
            SKIP
         ENDDO   
      ENDIF
      SELECT FAK
      SEEK MPSIF
      IF FOUND()
         DO WHILE.NOT.EOF()
            IF RSIF<>MPSIF
               EXIT
            ENDIF   
            MNASTANJU=MNASTANJU-KOLI
            SKIP
         ENDDO   
      ENDIF
      SELECT KOCKA
      REPLACE NASTANJU WITH MNASTANJU
   ENDIF
   SKIP
ENDDO
SELECT KAL
USE
SELECT FAK
USE
SELECT KOCKA
GO TOP

*------MATERIJAL---------------------------
KKAL='KAL'+ALLTRIM(MMAGMAT)
KKALG='KALG'+ALLTRIM(MMAGMAT)
KFAK='FAK'+ALLTRIM(MMAGMAT)
KFAKG='FAKG'+ALLTRIM(MMAGMAT)

USE &KKAL IN 0 ORDER 2 ALIAS KAL
SELECT KAL
USE &KFAK IN 0 ORDER 2 ALIAS FAK
SELECT Fak

SELECT KOCKA
GO TOP
DO WHILE.NOT.EOF()
   IF MSIF<>SPACE(5)
      MMSIF=MSIF
      MNASTANJU=0
      SELECT KAL
      SEEK MMSIF
      IF FOUND()
         DO WHILE.NOT.EOF()
            IF RSIF<>MMSIF
               EXIT
            ENDIF   
            MNASTANJU=MNASTANJU+KOL
            SKIP
         ENDDO   
      ENDIF
      SELECT FAK
      SEEK MMSIF
      IF FOUND()
         DO WHILE.NOT.EOF()
            IF RSIF<>MMSIF
               EXIT
            ENDIF   
            MNASTANJU=MNASTANJU-KOLI
            SKIP
         ENDDO   
      ENDIF
      SELECT KOCKA
      REPLACE NASTANJU WITH MNASTANJU
   ENDIF
   SKIP
ENDDO
SELECT KAL
USE
SELECT FAK
USE
SELECT KOCKA
GO TOP

*-----POMOCNI-MATERIJAL---------------------------
KKAL='KAL'+ALLTRIM(MMAGPMAT)
KKALG='KALG'+ALLTRIM(MMAGPMAT)
KFAK='FAK'+ALLTRIM(MMAGPMAT)
KFAKG='FAKG'+ALLTRIM(MMAGPMAT)

USE &KKAL IN 0 ORDER 2 ALIAS KAL
SELECT KAL

USE &KFAK IN 0 ORDER 2 ALIAS FAK
SELECT FAK

SELECT KOCKA
GO TOP
DO WHILE.NOT.EOF()
   IF PMSIF<>SPACE(5)
      MPMSIF=PMSIF
      MNASTANJU=0
      SELECT KAL
      SEEK MPMSIF
      IF FOUND()
         DO WHILE.NOT.EOF()
            IF RSIF<>MPMSIF
               EXIT
            ENDIF   
            MNASTANJU=MNASTANJU+KOL
            SKIP
         ENDDO   
      ENDIF
      SELECT FAK
      SEEK MPMSIF
      IF FOUND()
         DO WHILE.NOT.EOF()
            IF RSIF<>MPMSIF
               EXIT
            ENDIF   
            MNASTANJU=MNASTANJU-KOLI
            SKIP
         ENDDO   
      ENDIF
      SELECT KOCKA
      REPLACE NASTANJU WITH MNASTANJU
   ENDIF
   SKIP
ENDDO
SELECT KAL
USE
SELECT FAK
USE
SELECT KOCKA
GO TOP


*-----AMBALAZA--------------------------
KKAL='KAL'+ALLTRIM(MMAGAMB)
KKALG='KALG'+ALLTRIM(MMAGAMB)
KFAK='FAK'+ALLTRIM(MMAGAMB)
KFAKG='FAKG'+ALLTRIM(MMAGAMB)

USE &KKAL IN 0 ORDER 2 ALIAS KAL
SELECT KAL

USE &KFAK IN 0 ORDER 2 ALIAS FAK
SELECT FAK

SELECT KOCKA
GO TOP
DO WHILE.NOT.EOF()
   IF ASIF<>SPACE(5)
      MASIF=ASIF
      MNASTANJU=0
      SELECT KAL
      SEEK MASIF
      IF FOUND()
         DO WHILE.NOT.EOF()
            IF RSIF<>MASIF
               EXIT
            ENDIF   
            MNASTANJU=MNASTANJU+KOL
            SKIP
         ENDDO   
      ENDIF
      SELECT FAK
      SEEK MASIF
      IF FOUND()
         DO WHILE.NOT.EOF()
            IF RSIF<>MASIF
               EXIT
            ENDIF   
            MNASTANJU=MNASTANJU-KOLI
            SKIP
         ENDDO   
      ENDIF
      SELECT KOCKA
      REPLACE NASTANJU WITH MNASTANJU
   ENDIF
   SKIP
ENDDO
SELECT KAL
USE
SELECT FAK
USE
SELECT KOCKA
SET ORDER TO 2
GO TOP
DO WHILE.NOT.EOF()
   REPLACE POTREBNO WITH KOL
   REPLACE RAZLIKA WITH NASTANJU-POTREBNO
   replace pnastanju WITH nastanju*cena
   replace ppotrebno WITH POTREBNO*CENA
   REPLACE PRAZLIKA WITH PNASTANJU-PPOTREBNO
   SKIP
ENDDO   
*REPORT FORM PROPLAN02 PREVIEW
   mfile='PROPLAN02'    
   uslov=""
   DO printer_bullzip WITH mdata02,mfile,uslov

USE
SELECT PROPLAN
SET ORDER TO 
PROPLAN.GRD0.SETFOCUS
PROPLAN.REFRESH
POP KEY
