PUSH KEY CLEAR
   SELECT PROPOLU
   MMSIF=PSIF
   MCENA=PLCENA
   SELECT PRONORMA
   REPLACE PSIF WITH MMSIF
   REPLACE CENA WITH MCENA
PROPOLUP.VISIBLE=.F.
PRONORMAP.REFRESH
PROPOLUP.VISIBLE=.T. 
   
SELECT PROPOLU
PROPOLUP.GRD0.COLUMN2.SETFOCUS
POP KEY
PROPOLUP.REFRESH