IF TFPOSSIF<>'D'
PUSH KEY CLEAR
SELECT PROPMAT
APPEND BLANK
REPLACE PMsif WITH STR(RECNO(),5,0)
REPLACE RSIF WITH PMSIF
PROPMAT.GRD0.REFRESH

DO FORM PROPMATK

PROPMAT.GRD0.SETFOCUS
POP KEY
PROPMAT.REFRESH
ENDIF