PUSH KEY CLEAR

   SELECT PROPOLU
   MMSIF=PSIF
   MCENA=PLCENA
   SELECT PRONORMA
   IF PSIF=SPACE(5).AND.MSIF=SPACE(5).AND.PMSIF=SPACE(5).AND.ASIF=SPACE(5).AND.LDSIF=SPACE(5).AND.DIRSIF=SPACE(5).AND.OPSSIF=SPACE(5)
      REPLACE PSIF WITH MMSIF
      REPLACE CENA WITH MCENA
   ENDIF
PROPOLU.VISIBLE=.F.
IF MNOR=1
   PRONORMA.REFRESH
ELSE
   PRONORMAL.REFRESH
ENDIF
PROPOLU.VISIBLE=.T. 
   
SELECT PROPOLU
PROPOLU.GRD0.COLUMN2.SETFOCUS
POP KEY
PROPOLU.REFRESH