IF TFPOSSIF<>'D'
PUSH KEY CLEAR
SELECT PROPOLU
APPEND BLANK
REPLACE Psif WITH STR(RECNO(),5,0)
REPLACE RSIF WITH PSIF
PROPOLU.GRD0.REFRESH
DO FORM PROPOLUK

PROPOLU.GRD0.SETFOCUS
POP KEY
PROPOLU.REFRESH
ENDIF