IF TFPOSSIF<>'D' 

PUSH KEY CLEAR
SELECT PROPMAT
APPEND BLANK
REPLACE PMsif WITH STR(RECNO(),5,0)
REPLACE RSIF WITH PMSIF
PROPMATP.GRD0.REFRESH

DO FORM PROPMATK

PROPMATP.GRD0.SETFOCUS
POP KEY
PROPMATP.REFRESH
ENDIF