PUSH KEY CLEAR
SELECT PRONORMA
DO IDEL WITH (KKOCKAX)
DO IDEL WITH (KKOCKAX2)
COPY STRUCTURE TO &KKOCKA
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
SELECT PROPLAN
GO TOP
   DO WHILE.NOT.EOF()
     IF ARHIVA=' ' 
     MNORMATIV=NORMATIV
     MKOL=KOL
     SELECT PRONORMA
     SET ORDER TO 3
     SEEK MNORMATIV
     IF FOUND()
        DO WHILE.NOT.EOF()
           IF NORMATIV<>MNORMATIV
              EXIT
           ENDIF
           SCATTER NAME POLJA
           IF ZADCENA<>0
              MCENA=ZADCENA
           ELSE
              MCENA=CENA
           ENDIF
           SELECT KOCKA
           APPEND BLANK
           GATHER NAME POLJA 
           REPLACE CENA WITH MCENA
           REPLACE KOL WITH KOL*MKOL
           REPLACE IZNOS WITH KOL*CENA  
           SELECT PRONORMA
           SKIP
        ENDDO   
     ENDIF
     ENDIF
     SELECT PROPLAN
     SKIP
   ENDDO   
SELECT KOCKA

INDEX ON OPIS TAG OPIS
INDEX ON GRUPA+MSIFNAZ TAG GRUPA
INDEX ON PSIF+MSIF+PMSIF+ASIF+LDSIF+DIRSIF+OPSSIF TAG SSIF
SET ORDER TO 3
TOTAL ON PSIF+MSIF+PMSIF+ASIF+LDSIF+DIRSIF+OPSSIF  FIELDS KOL,IZNOS TO &KKOCKA2
DELETE ALL
PACK

APPEND FROM &KKOCKA2
SET ORDER TO 1
COPY TO &KKOCKA2
DELETE ALL
PACK

SELECT PROPLAN
GO TOP
   DO WHILE.NOT.EOF()
      IF ARHIVA=' '
      MRSIF=RSIF
      MKOL=KOL
      MRCENA=RCENA
      SELECT KOCKA
      APPEND BLANK
      REPLACE RSIF WITH MRSIF
      REPLACE SSIF WITH MRSIF
      REPLACE KOL WITH MKOL
      REPLACE OPIS WITH '            '
      REPLACE CENA WITH MRCENA
      REPLACE MSIFNAZ WITH ROB.NAZ
      REPLACE IZNOS WITH KOL*CENA
      SELECT PROPLAN
      ENDIF
      SKIP
   ENDDO   
SELECT KOCKA
APPEND FROM &KKOCKA2
GO TOP
PUBLIC AIZNPRO,AIZNMAT
AIZNPRO=0
AIZNMAT=0
DO WHILE.NOT.EOF()
   IF OPIS=SPACE(20)
      AIZNPRO=AIZNPRO+(KOL*CENA)
   ELSE
      AIZNMAT=AIZNMAT+(KOL*CENA)
   ENDIF      
   SKIP
ENDDO   
SET ORDER TO 2
GO TOP
*REPORT FORM PROPLAN0 PREVIEW
   mfile='PROPLAN0'    
   uslov=""
   DO printer_bullzip WITH mdata02,mfile,uslov

USE
SELECT PROPLAN
SET ORDER TO 
PROPLAN.GRD0.SETFOCUS
PROPLAN.REFRESH
POP KEY
