PUSH KEY CLEAR


   SELECT PRORAD
   MLDSIF=LDSIF
   MCENA=CENA
   SELECT PRONORMA
   IF MSIF=SPACE(5).AND.PMSIF=SPACE(5).AND.ASIF=SPACE(5).AND.LDSIF=SPACE(5).AND.DIRSIF=SPACE(5).AND.OPSSIF=SPACE(5)
      REPLACE LDSIF WITH MLDSIF
      REPLACE CENA WITH MCENA
   ENDIF
PRORADP.VISIBLE=.F.
PRONORMAP.REFRESH
PRORADP.VISIBLE=.T. 
   
SELECT PRORAD
PRORADP.GRD0.COLUMN2.SETFOCUS
POP KEY
PRORADP.REFRESH