REPLACE VELVRED WITH ROUND(KOL*VELCENA,2)
REPLACE POREZ WITH ROUND(VELVRED*PROCPOR/100,2)
REPLACE FAKVRED WITH VELVRED+POREZ
IF PROCAV1<>0
REPLACE OSNAV1 WITH ROUND(VELVRED*PROCAV1/100,2)
ENDIF
IF PROCAV1<>0
REPLACE OSNAV2 WITH ROUND(VELVRED*PROCAV2/100,2)
ENDIF
IF PROCAV1<>0
REPLACE OSNAV3 WITH ROUND(VELVRED*PROCAV3/100,2)
ENDIF
IF PROCAV1<>0
REPLACE OSNAV4 WITH ROUND(VELVRED*PROCAV4/100,2)
ENDIF
IF PROCAV1<>0
REPLACE OSNAV5 WITH ROUND(VELVRED*PROCAV5/100,2)
ENDIF

REPLACE PORAV1 WITH ROUND(OSNAV1*PROCPOR/100,2)
REPLACE PORAV2 WITH ROUND(OSNAV2*PROCPOR/100,2)
REPLACE PORAV3 WITH ROUND(OSNAV3*PROCPOR/100,2)
REPLACE PORAV4 WITH ROUND(OSNAV4*PROCPOR/100,2)
REPLACE PORAV5 WITH ROUND(OSNAV5*PROCPOR/100,2)

REPLACE DINAV1 WITH OSNAV1+PORAV1
REPLACE DINAV2 WITH OSNAV2+PORAV2
REPLACE DINAV3 WITH OSNAV3+PORAV3
REPLACE DINAV4 WITH OSNAV4+PORAV4
REPLACE DINAV5 WITH OSNAV5+PORAV5

REPLACE PROCAV WITH PROCAV1+PROCAV2+PROCAV3+PROCAV4+PROCAV5
REPLACE OSNAV WITH OSNAV1+OSNAV2+OSNAV3+OSNAV4+OSNAV5
REPLACE PORAV WITH PORAV1+PORAV2+PORAV3+PORAV4+PORAV5
REPLACE DINAV WITH DINAV1+DINAV2+DINAV3+DINAV4+DINAV5
replace naziv WITH an0.naziv
replace fpsifra WITH '  1'
IF VPMP=' '
   REPLACE VPMP WITH 'V'
ENDIF   
