PUSH KEY CLEAR
if reccount()>0
   MBRKAL=BRKAL
   MRNAL=RNAL
   MDATZAH=DATZAH
   MDATUGOVOR=DATUGOVOR
   MDATISPOR=DATISPOR
   MDATPONUDE=DATPONUDE
   MSIFRA=SIFRA
ELSE
   MBRKAL='000001'
   MRNAL='000001'   
   MDATZAH=CTOD('')
   MDATUGOVOR=CTOD('')
   MDATISPOR=CTOD('')      
   MDATPONUDE=CTOD('')   
   MSIFRA=''
endif      
IF KOL<>0.OR.RECCOUNT()<1
   append blank
   REPLACE BRKAL WITH MBRKAL
   REPLACE RNAL WITH MRNAL   
   REPLACE DATZAH WITH MDATZAH
   REPLACE DATUGOVOR WITH MDATUGOVOR
   REPLACE DATISPOR WITH MDATISPOR
   REPLACE DATPONUDE WITH MDATPONUDE        
   REPLACE SIFRA WITH MSIFRA
ENDIF
PROZAH.grd0.column1.setfocus
PROZAH.REFRESH  
POP KEY