PUSH KEY CLEAR
   SET ORDER TO 
   IF RECCOUNT()>0
      MOPIS=OPIS
      MBRNAL=BRNAL
      MDATDOK=DATDOK
      MVALUTA=VALUTA
      APPEND BLANK
      REPLACE OPIS WITH MOPIS
      REPLACE BRNAL WITH MBRNAL
      REPLACE DATDOK WITH MDATDOK
      REPLACE VALUTA WITH MVALUTA
      REPLACE OPER WITH OPERATER
      REPLACE DATUM WITH DATE()
      REPLACE VREME WITH TIME()   
      PUANAL.GRD0.SETFOCUS
      PUANAL.REFRESH
   ELSE
      APPEND BLANK
      REPLACE DATDOK WITH DATE()
   ENDIF
   PUANAL.GRD0.COLUMN1.SETFOCUS
   PUANAL.REFRESH  
POP KEY