PUSH KEY CLEAR
  MMESEC=MESEC
  PU.CMDBRISIMES.SETFOCUS
  CLOSE ALL TABLES
  USE PU EXCLU IN 0 ALIAS PU
  SELECT PU
  GO TOP
  DO WHILE.NOT.EOF()
     IF MESEC=MMESEC
        IF ARHIVA=' '
           DELETE NEXT 1
        ENDIF
     ENDIF
     SKIP
  ENDDO         
  PACK
  GO TOP
  PU.RELEASE
  KEYBOARD '{ENTER}'
  POP KEY