PUSH KEY CLEAR
   SET ORDER TO 
   IF RECCOUNT()>0
      MDATDOK=DATDOK
      MVALUTA=VALUTA
      MMESEC=MESEC
      MDANA=DANA
      APPEND BLANK
      REPLACE DATDOK WITH MDATDOK
      REPLACE VALUTA WITH MVALUTA
      REPLACE MESEC WITH MMESEC
      REPLACE DANA WITH MDANA
      PU.GRD0.SETFOCUS
      PU.REFRESH
   ELSE
      APPEND BLANK
      REPLACE DATDOK WITH DATE()
   ENDIF
   PU.GRD0.COLUMN1.SETFOCUS
   PU.REFRESH  
POP KEY