SELECT KASA
GO TOP
IF RECCOUNT()>0
   USE KASAPAR IN 0
   SELECT KASAPAR
   MSIFRA=SIFRA
   MFVRSTA=FVRSTA
   MPOCNAL=POCNAL
   MSEMA=SEMA
   USE
   SELECT KASA
   MOPER=OPER
   M2MALVRED=0
   MGOTOVINA=GOTOVINA
   MKES=GOTOVINA
   MCEK=CEK
   MKARTICA=KARTICA
   MIDKARTICE=IDKARTICE
   DO WHILE.NOT.EOF()
      M2MALVRED=M2MALVRED+MALVRED
      SKIP
   ENDDO
   MKARTICA=0
   MCEK=M2MALVRED
   MGOTOVINA=0

   GO TOP
      MOPER=OPER
      MDATUM=DATE()
      MVREME=TIME()
      MSTO=STO
      USE KASABROJ IN 0 
      SELECT KASABROJ
      GO BOTTOM
      IF RECCOUNT()>0
         MZADNJIbr=VAL(BRKAl)
      ELSE
         mzadnjibr=0
      endif
      APPEND BLANK
      IF RECCOUNT()>1
         MNOVI=ALLTRIM(STR(mzadnjibr+1,6,0))
         MLEN=LEN(MNOVI)
         MN2=REPLICATE('0',6-MLEN)+MNOVI  
         MN2BRKAL=MN2
      ELSE
         MN2BRKAL='000001'
      ENDIF   
      REPLACE BRKAL WITH MN2BRKAL
      REPLACE OPER WITH MOPER
      REPLACE DATUM WITH MDATUM
      REPLACE VREME WITH MVREME
      REPLACE STO WITH MSTO
      USE

   SELECT KASA
   GO TOP
   MBRKAL=MN2BRKAL
   MSIFRA=SIFRA
   USE KASAREVG IN 0 ORDER 1 ALIAS FAKG
   SELECT FAKG
   SET ORDER TO 1
   LOCATE FOR BRKAL=MBRKAL


   IF.NOT.FOUND()
      APPEND BLANK
      REPLACE BRKAL WITH MBRKAL
      REPLACE FVRSTA WITH MFVRSTA
      REPLACE SIFRA WITH MSIFRA
      REPLACE VPDV WITH 'IN0'
      REPLACE OPDV WITH '*'
      REPLACE DATDOK WITH DATE()
      REPLACE DATUM WITH DATE()
      REPLACE VALUTA WITH DATE()
      REPLACE VREME WITH TIME()
      REPLACE BRRAC WITH MBRKAL
      REPLACE BRNAL WITH SUBSTR(MPOCNAL,1,1)+SUBSTR(BRKAL,2,5)
      REPLACE KES WITH MGOTOVINA
      REPLACE CEK WITH MCEK
      REPLACE KARTICA WITH MKARTICA
      REPLACE KASA WITH '*'
      REPLACE ARHIVA WITH '*'
      REPLACE OPER WITH MOPER
      REPLACE IDKARTICE WITH MIDKARTICE
   ENDIF
   USE
   USE KASAREV IN 0 ORDER 1 ALIAS FAK
   SELECT FAK
   SELECT KASA
   DO WHILE.NOT.EOF()
      MRSIF=RSIF
      MKOLI=KOLI
      MMALCENA=MALCENA
      MMALVRED=MALVRED
      MDATDOK=DATE()
      MTARIFA=TARIFA
      MPROCPOR=PROCPOR
      mrabproc=rabproc
      mrabat=rabat
      SELECT FAK
      APPEND BLANK
      REPLACE BRKAL WITH MBRKAL
      REPLACE RSIF WITH MRSIF
      REPLACE KOLI WITH MKOLI
      REPLACE MALCENA WITH MMALCENA
      REPLACE MALVRED WITH MMALVRED
      replace rabproc WITH mrabproc
      replace rabat WITH mrabat
      REPLACE DATDOK WITH MDATDOK
      REPLACE TARIFA WITH MTARIFA
      REPLACE PROCPOR WITH MPROCPOR
      REPLACE DATDOK WITH MDATDOK
      SELECT KASA
      SKIP
   ENDDO   
   SELECT FAK
   USE
   SELECT KASA
   GO TOP
ENDIF