PUSH KEY CLEAR
PUTAR.GRD0.RECORDSOURCE=''
SELECT PUTAR
SET ORDER TO 
IF RECCOUNT()>0
   GO BOTTOM
   MDATDOK=DATDOK
   MGRUPA=GRUPA
ELSE
   MDATDOK=DATE()
   MGRUPA=''
ENDIF
APPEND BLANK
REPLACE REDBR WITH STR(RECNO(),6,0)
REPLACE DATDOK WITH MDATDOK
REPLACE GRUPA WITH MGRUPA
DO PUTARK
SET ORDER TO 
PUTAR.GRD0.RECORDSOURCE='PUTAR'
putar.GRD0.SetFocus 
POP KEY