PARAMETERS AODAKLE
IF AODAKLE=1
SELECT PUTAR
SET RELATION TO
DO FORM PUTAR0
SELECT PUTAR0
SET ORDER TO 1
SELECT PUTAR
SET RELATION TO SIFREL INTO PUTAR0 ADDITIVE
SET RELATION TO PUTNAL INTO PUTNAL ADDITIVE
ENDIF