PUSH KEY CLEAR
PUTAR0.GRD0.RECORDSOURCE=''
SELECT PUTAR0
SET ORDER TO 
APPEND BLANK
REPLACE SIFREL WITH STR(RECNO(),6,0)
DO PUTAR0K
SET ORDER TO 1
PUTAR0.GRD0.RECORDSOURCE='PUTAR0'
putar0.GRD0.SetFocus 
POP KEY