PROCEDURE PUTWEB00TAST
ON KEY LABEL F1    DO HELPN WITH 'PUTWEB00'
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL ESC       PUTWEB00.RELEASE
ENDPROC

PROCEDURE PUTWEBAN0TAST
ON KEY LABEL F1    DO HELPN WITH 'PUTWEBAN0'
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL ESC       PUTWEBAN0.RELEASE
ENDPROC


PROCEDURE PUTWEBROBTAST
ON KEY LABEL F1    DO HELPN WITH 'PUTWEBROB'
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL ESC       PUTWEBROB.RELEASE
ENDPROC

PROCEDURE PUTWEBFAKTAST
ON KEY LABEL F1    DO HELPN WITH 'PUTWEBFAK'
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL ESC       PUTWEBFAK.RELEASE
ENDPROC

PROCEDURE PUTWEBKONEKCIJATAST
ON KEY LABEL F1    DO HELPN WITH 'PUTWEBKONEKCIJA'
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL ESC       PUTWEBKONEKCIJA.RELEASE
ENDPROC

PROCEDURE PUTWEBKORTAST
ON KEY LABEL F1    DO HELPN WITH 'PUTWEBKOR'
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL ESC       PUTWEBKOR.RELEASE
ENDPROC

PROCEDURE PUTWEBAN0MITAST
ON KEY LABEL F1    DO HELPN WITH 'PUTWEBAN0MI'
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL ESC       PUTWEBAN0MI.RELEASE
ENDPROC


