PARAMETERS MRED,M21AN,M21AP
PUSH KEY CLEAR
   SEEK MRED
   IF FOUND()
      M21N=NETO
      M21P=PRETH
      IF M21AN<>0
         MNP=ROUND(M21N*100/M21AN,0)
      ELSE
         MNP=0
      ENDIF
      IF M21AP<>0
         MPP=ROUND(M21P*100/M21AP,0)
      ELSE
         MPP=0
      ENDIF
      REPLACE PRNETO WITH MNP
      REPLACE PRPRETH WITH MPP
POP KEY
   ENDIF
