PUSH KEY CLEAR
SELECT CALC
IF RECCOUNT()>0
   MREDNI=RECNO()
ELSE
   MREDNI=0
ENDIF
mbroj=broj
SEEK mbroj
IF FOUND()
   MMRED=0
   DO WHILE.NOT.EOF()
      IF BROJ<>MBROJ
         EXIT
      ENDIF   
      MMRED=MMRED+1
      SKIP
   ENDDO 
ELSE
   MMRED=1   
ENDIF
MSALDO=0
SEEK MBROJ   
DO WHILE.NOT.EOF()
   IF BROJ<>MBROJ
      EXIT
   ENDIF   
   IF MMRED=1
      MSALDO=IZNOS
   ELSE
      SKIP-1
      MPOC=SALDO
      SKIP
      MIZNOS=IZNOS
      DO CASE znak
      CASE ZNAK='+'
            MSALDO=MPOC+IZNOS
      CASE ZNAK='-'
            MSALDO=MPOC-IZNOS
      CASE ZNAK='*'
            MSALDO=MPOC*IZNOS
      CASE ZNAK='/'
         IF IZNOS<>0
            MSALDO=MPOC/IZNOS
         ELSE
            MSALDO=MPOC
         ENDIF
      CASE ZNAK='P'
            MSALDO=MPOC*IZNOS/100
      CASE ZNAK='K'
            MSALDO=SQRT(MPOC)
      CASE ZNAK='S'
            MSALDO=MPOC^IZNOS
      ENDCASE
   ENDIF
   SELECT CALC
   IF MSALDO<9999999999999.9999
      REPLACE SALDO WITH MSALDO
   ELSE
      REPLACE SALDO WITH 0
   ENDIF
   SKIP
ENDDO
SELECT CALC
IF MREDNI>0
GOTO MREDNI
ENDIF
NCALC.GRD0.SETFOCUS
POP KEY