   PUSH KEY CLEAR
   SELECT PDV
   IF proc18=0
      IF DTOS(DATDOK)>=TVAZIOD
         REPLACE PROC18 WITH VAL(TOSTOPA)
      ENDIF
   endif
   IF proc8=0
      IF DTOS(DATDOK)>=TVAZIOD
         REPLACE PROC8 WITH VAL(TNSTOPA)
      ENDIF
   endif
   IF procpolj=0
      IF DTOS(DATDOK)>=TVAZIOD
         REPLACE PROCpOLJ WITH TpSTOPA
      ENDIF
   endif
   IF OPS=' '
      REPLACE PDV18 WITH ROUND(OSN18*PROC18/100,2)
      REPLACE PDV8 WITH ROUND(OSN8*PROC8/100,2)
      REPLACE PDV5 WITH ROUND(OSN5*procpolj/100,2)
   ELSE
      IF OPS='O'
         REPLACE PDV18 WITH 0
         REPLACE PDV8 WITH 0
         REPLACE PDV5 WITH 0                  
      ENDIF
      IF OPS='P'
         REPLACE OSN18 WITH 0
         REPLACE OSN8 WITH 0
         REPLACE osn5 WITH 0                  
      ENDIF
   ENDIF
   IF VPDV='BPO'
       MPDVNE18=0
       MPDVNE8=0
       IF OSN18<>0
          MPDVNE18=ROUND(OSN18*PROC18/100,2)
       ENDIF
       IF OSN8<>0
          MPDVNE8=ROUND(OSN8*PROC8/100,2)
       ENDIF
       REPLACE PDVNE WITH MPDVNE18+MPDVNE8
   ENDIF
   IF SUBSTR(vpdv,1,2)='UN'
      REPLACE NEOPOREZ WITH UKNAB-OSN18-OSN8-OSN5-PDV18-PDV8-PDV5
   ENDIF  
   IF SUBSTR(vpdv,1,2)='UB'
      REPLACE NEOPOREZ WITH UKNAB
   ENDIF      
   REPLACE UKUPNO WITH OSN18+OSN8+OSN5+neoporez
   REPLACE PDV WITH PDV18+PDV8+PDV5
 *  REPLACE DATUM WITH DATE()
 *  REPLACE VREME WITH TIME()
   POP KEY