  PUSH KEY CLEAR
  SELECT PDV

  IF proc18=0
      IF DTOS(DATDOK)>=TVAZIOD
         REPLACE PROC18 WITH VAL(TOSTOPA)
      ENDIF  
   endif
  IF proc8=0
      IF DTOS(DATDOK)>=TVAZIOD
         REPLACE PROC8 WITH VAL(TNSTOPA)
      ENDIF  
   endif
   IF OPS=' '   
      REPLACE PDV18 WITH ROUND(OSN18*PROC18/100,2)
      REPLACE PDV8 WITH ROUND(OSN8*PROC8/100,2)
   ELSE
      IF OPS='O'
         REPLACE PDV18 WITH 0
         REPLACE PDV8 WITH 0
      ENDIF
      IF OPS='P'
         REPLACE OSN18 WITH 0
         REPLACE OSN8 WITH 0
      ENDIF   
   ENDIF
   REPLACE UKUPNO WITH OSN18+OSN8+osn0
   REPLACE PDV WITH PDV18+PDV8
 *  REPLACE DATUM WITH DATE()
 *  REPLACE VREME WITH TIME()
 POP KEY