MPROVERAF=KASAPROVERAF()
IF MPROVERAF=1

   SELECT KASA
   GO TOP
   IF RECCOUNT()>0
      IF FILE(KKOCKAX)
         DELETE FILE &KKOCKAX
      ENDIF
      SET ORDER TO 2
      TOTAL ON RSIF TO &KKOCKA FIELDS KOLI,MALVRED
      USE &KKOCKA IN 0 ALIAS KOCKA EXCLUSIVE
      SELECT KOCKA
      DO KASARADTREB2
      SELECT KOCKA 
      USE
   ENDIF            
   SELECT KASA
   GO TOP
ELSE
   DO PORUKAU WITH 'ŠTAMPAÈ NIJE FISKALIZOVAN '
ENDIF
