SELECT ROB
*SET STEP ON 
*BROW
MRSIF=RSIF
MRCENA=PLCENA
SELECT PRONAL
*IF LEN(allTRIM(RSIF))=0
   SELECT PRONAL
   MARH=ARHIVA
   MRNAL=RNAL
   MDAT0=DAT0
   MDAT1=DAT1
   MDOK=DOK
   MFAKTURA=FAKTURA
   APPEND BLANK
   GO bottom
   REPLACE RNAL WITH MRNAL
   REPLACE RSIF WITH MRSIF
   REPLACE RCENA WITH MRCENA    
   REPLACE DAT0 WITH MDAT0
   REPLACE DAT1 WITH MDAT1
   REPLACE DOK WITH MDOK
   REPLACE FAKTURA WITH MFAKTURA
   replace rcena WITH mrcena
   SELECT PRONORMA
   SEEK MRSIF
   IF FOUND()
      MNORMATIV=NORMATIV
   ELSE
      MNORMATIV=' '
   ENDIF
   SELECT PRONAL
   REPLACE NORMATIV WITH MNORMATIV      
*ENDIF   

