PUSH KEY CLEAR
SELECT ROB0
IF RECCOUNT()>0
   SET ORDER TO 
   *GO BOTTOM
   *IF NAZ=SPACE(30)
   *   SKIP -1
      SCATTER NAME POLJA
   *  SKIP
      APPEND BLANK
      GATHER NAME POLJA
      REPLACE RSIF WITH STR(RECNO(),5,0)
*   ENDIF
      ROBA00.GRD0.SETFOCUS
      ROBA00.GRD0.REFRESH
      DO ROBA0KARTF7
ENDIF

ROBA00.GRD0.SETFOCUS
POP KEY