SET PROCEDURE TO PREGLED
PUSH KEY CLEAR
  DO ROPOC WITH 'ROB'
  SET ORDER TO
  GO TOP
  MM='PLU;NAME;VAT;BAR;PRiCe;PRCTYPE;STN;GRP'
  DO ROUZMI WITH MM,'ROB'
  SELECT ROB
  DO WHILE.NOT.EOF()
     IF VAZI<>' '
        IF MALCENA<>0.AND.NAZ<>SPACE(30)
           MPLU=SUBSTR(ALLTRIM(RSIF),1,4)
           MNAME=SUBSTR(NAZSKR,1,22)
           MBAR=SUBSTR(BARKOD,1,14)
           MPRICE=ALLTRIM(STR(MALCENA,12,2))
           MPRCTYPE='0'
           MSTN='1'
           MGRP='0'
           DO CASE TARIFA
           CASE TARIFA=SPACE(6).OR.TOBVEZNIK='N'
              MVAT='1'
           CASE ALLTRIM(TARIFA)=TOSTOPA
              MVAT='4'
           CASE ALLTRIM(TARIFA)=TNSTOPA
              MVAT='5'
           OTHERWISE
              MVAT='1'   
           ENDCASE
           MM=ALLTRIM(MPLU)+';'+ALLTRIM(MNAME)+';'+ALLTRIM(MVAT)+';'+ALLTRIM(MBAR)+';'+ALLTRIM(MPRICE)+';'+ALLTRIM(MPRCTYPE)+';'+ALLTRIM(MSTN)+';'+ALLTRIM(MGRP)
           DO ROUZMI WITH MM,'ROB'
           SELECT ROB
        ENDIF
     ENDIF   
     SELECT ROB
     SKIP
  ENDDO
SET PROCEDURE TO 
SELECT PREGLED
DO  FORM PREGLED 
SELECT PREGLED
USE
SELECT ROB
POP KEY