IF Maodakle=1
*   SET STEP ON 
   SCATTER NAME polja
   mrsif=rsif
   DO CASE ODAKLEIDE
   CASE ODAKLEIDE='ROBA'
      SELECT rob
   CASE ODAKLEIDE='POLU'
      SELECT PROPOLU
   CASE ODAKLEIDE='OMAT'
      SELECT PROMAT
   CASE ODAKLEIDE='PMAT'
      SELECT PROPMAT
   CASE ODAKLEIDE='AMBA'
      SELECT PROAMB
   CASE ODAKLEIDE='PPOLU'
      SELECT PROPOLU
   CASE ODAKLEIDE='POMAT'
      SELECT PROMAT
   CASE ODAKLEIDE='PPMAT'
      SELECT PROPMAT
   CASE ODAKLEIDE='PAMBA'
      SELECT PROAMB
   ENDCASE      
   
   SET ORDER to
   LOCATE FOR rsif=mrsif
   IF.not.found()
      APPEND BLANK
      GO bottom
      GATHER NAME polja
      DO CASE ODAKLEIDE
      CASE ODAKLEIDE='ROBA'
         SELECT rob
      CASE ODAKLEIDE='POLU'
         SELECT PROPOLU
      CASE ODAKLEIDE='OMAT'
         SELECT PROMAT
      CASE ODAKLEIDE='PMAT'
         SELECT PROPMAT
      CASE ODAKLEIDE='AMBA'
         SELECT PROAMB
      CASE ODAKLEIDE='PPOLU'
         SELECT PROPOLU
      CASE ODAKLEIDE='POMAT'
         SELECT PROMAT
      CASE ODAKLEIDE='PPMAT'
         SELECT PROPMAT
      CASE ODAKLEIDE='PAMBA'
         SELECT PROAMB
      ENDCASE      
   ENDIF
   SET ORDER TO 2
   SELECT rob0
   ROBA00.GRD0.SetFocus
   ROBA00.GRD0.REFRESH
endif
