*SELECT ROB
*MRSIF=RSIF
*USE ROBMEMO IN 0 
*SELECT ROBMEMO
*LOCATE FOR RSIF=MRSIF
*IF.NOT.FOUND()
*   APPEND BLANK
*   REPLACE RSIF WITH MRSIF
*ENDIF
*GO BOTTOM
*DO FORM ROBA0MEMO   
*SELECT robmemo
*USE
*SELECT rob