 USE GENEKO IN 0 EXCLU
 SELECT GENEKO
 DELETE ALL
PACK

  SELECT ROB
  SET ORDER TO 2
  GO TOP
  BROJAC=1
  DO WHILE.NOT.EOF()
     IF VAZI<>' '
     ENDIF   
     IF NAZ<>SPACE(30)
        IF MALCENA<>0
           MREDBR=RECNO()
           MBARKOD=BARKOD
           MMALCENA=MALCENA
           MNAZIV=NAZ 
           IF PROCPOR=VAL(TOSTOPA)
              MPORGRID=3
           ELSE
              MPORGRID=4
           ENDIF
           SELECT GENEKO
           IF RECCOUNT()<=2099
           APPEND BLANK
           REPLACE REDBR WITH RECNO()
           REPLACE BARKOD WITH MBARKOD
           REPLACE NAZIV WITH MNAZIV
           REPLACE CENA WITH MMALCENA
           REPLACE PORGRID WITH MPORGRID
           ENDIF
        ENDIF
     ENDIF
     SELECT ROB
     SKIP
  ENDDO
SELECT GENEKO

COPY TO ARTIKLI1 TYPE CSV
USE
COPY FILE ARTIKLI1.CSV TO ARTIKLI0.TXT
SELECT ROB
SET ORDER TO 2
POP KEY