PUSH KEY CLEAR
if tfpossif='D'.AND.TNEZAJEDNO<>'D'
roba00.cmddodaj.setfocus
SELECT ROB0
SET ORDER TO
APPEND BLANK
REPLACE rsif WITH STR(RECNO(),5,0)
REPLACE PSIF WITH RSIF
REPLACE MSIF WITH RSIF
REPLACE PMSIF WITH RSIF
REPLACE ASIF WITH RSIF

REPLACE JED WITH 'KOM'
REPLACE TARIFA WITH '20'
REPLACE PROCPOR WITH 20
REPLACE VRSTA WITH 'N'
ROBA00.GRD0.REFRESH

DO FORM ROBAK2

SELECT ROB0
SET ORDER TO 2
ROBA00.GRD0.SETFOCUS
ROBA00.REFRESH
ENDIF
POP KEY
