PUSH KEY CLEAR
SELECT FAK
MREDREC=RECNO()
MREDZAD=RECCOUNT()
MBRKAL=BRKAL
MDATDOK=DATDOK
SELECT ROB
MKOL=KOL
MRSIF=RSIF
MNAZ=NAZ
SELECT FAK
IF MREDREC=MREDZAD
   IF FAKG.ARHIVA=' '
      SELECT IROB
      APPEND BLANK
      REPLACE REDBR WITH RECNO()
      REPLACE RSIF WITH MRSIF
      REPLACE NAZ WITH MNAZ
      REPLACE BRKAL WITH MBRKAL
      REPLACE DATDOK WITH MDATDOK
   ENDIF
ELSE
   DO PORUKAU WITH ' NISTE NA ZADNJEM POLJU TREBOVANJA'
endif   
SELECT ROB
POP KEY
