PARAMETERS mrsif,MDAT0,MDAT1,MFVRSTA,MSIFRA,MINTERNE,MPRENOSNE,MREC
PUSH KEY CLEAR


DO IDEL WITH  (KTVKARTX)

ON ERROR
USE  &KTVKART ALIAS TVKART EXCLU IN 0
SELECT TVKART
DELETE ALL
PACK

ON ERROR DO GRESKE WITH ;
   ERROR( ), MESSAGE( ), MESSAGE(1), PROGRAM( ), LINENO( )

INDEX ON DTOS(DATDOK) TAG DATDOK
SET ORDER TO 1


SET EXACT OFF
 
*---------UZIMAMO ROBU IZ KALKULACIJA------------

IF TNET=1
   SELECT KAL
ELSE
   SELECT KALs
ENDIF
SET ORDER TO 2
SEEK MRSIF
DO WHILE.NOT.EOF()
   IF RSIF<>MRSIF
      EXIT
   ENDIF
   IF DATDOK>=MDAT0.AND.DATDOK<=MDAT1
      IF KALG.FVRSTA=MFVRSTA.OR.MFVRSTA=SPACE(3)
         IF KALG.SIFRA=MSIFRA.OR.MSIFRA=SPACE(5)
            IF KALG.INTERNA=MINTERNE.OR.MINTERNE=' '
               IF KALG.PRENOS=MPRENOSNE.OR.MPRENOSNE=' '
                  ADATDOK=DATDOK
                  Abrkal=brkal
                  AKOL=KOL
                  AKOLI=0
                  AKOLST=0
                  ADATROK=DATROK
                  IF TOBJEKAT='V'
                     ACENA=VELCENA
                     ADUG=VELVRED
                     APOT=0
                     ASALDO=0
                  ELSE
                     Acena=malcena
                     ADUG=MALVRED
                     APOT=0
                     ASALDO=0
                  endif
                  ANCENA=NABCENA
                  ANDUG=NABVRED
                  ANPOT=0
                  ANSALDO=0
                  ASIFRA=KALG.SIFRA                       
                  MSERIJA=SERIJA
                  MSERTIFIK=SERTIFIK
                  MDATPRO=DATPRO
                  SELECT TVKART
                  APPEND BLANK 
                  REPLACE RSIF WITH MRSIF
                  REPLACE DATDOK WITH ADATDOK
                  REPLACE BRKAL WITH ABRKAL  
                  REPLACE KOL WITH AKOL
                  REPLACE KOLI WITH AKOLI
                  REPLACE KOLST WITH AKOLST
                  REPLACE CENA WITH ACENA
                  REPLACE DUG WITH ADUG
                  REPLACE POT WITH APOT
                  REPLACE SALDO WITH ASALDO
                  REPLACE NCENA WITH ANCENA
                  REPLACE NDUG WITH ANDUG
                  REPLACE NPOT WITH ANPOT
                  REPLACE NSALDO WITH ANSALDO
                  REPLACE SIFRA WITH ASIFRA
                  REPLACE DATROK WITH ADATROK
                  REPLACE DATpro WITH mdatpro
                  REPLACE serija WITH mserija
                  REPLACE sertifik WITH msertifik
                  
                  IF TNET=1  
                     SELECT KAL
                  ELSE
                     SELECT KALs
                  ENDIF
               endif
            ENDIF
         ENDIF
      ENDIF
   ENDIF
   SKIP
ENDDO   

*---------UZIMAMO ROBU IZ RACUNA------------
IF TNET=1
   SELECT FAK
ELSE
   SELECT FAKS
ENDIF

SET ORDER TO 2
SEEK MRSIF
DO WHILE.NOT.EOF()
   IF RSIF<>MRSIF
      EXIT
   ENDIF
   IF DATDOK>=MDAT0.AND.DATDOK<=MDAT1
      IF FAKG.FVRSTA=MFVRSTA.OR.MFVRSTA=SPACE(3)
         IF FAKG.SIFRA=MSIFRA.OR.MSIFRA=SPACE(5)
            IF FAKG.INTERNA=MINTERNE.OR.MINTERNE=' '
               IF FAKG.PRENOS=MPRENOSNE.OR.MPRENOSNE=' '
                  ADATDOK=DATDOK
                  Abrkal=brkal
                  AKOLI=KOLI
                  ADATROK=DATROK
                  IF TOBJEKAT='V'
                     ACENA=VELCENA
                     APOT=VELVRED
                  ELSE
                     Acena=malcena
                     APOT=MALVRED
                  endif
                  ASIFRA=FAKG.SIFRA                       
                  MSERIJA=SERIJA
                  MSERTIFIK=SERTIFIK
                  MDATPRO=DATPRO
                  
                  SELECT TVKART
                  APPEND BLANK 
                  REPLACE RSIF WITH MRSIF
                  REPLACE DATDOK WITH ADATDOK
                  REPLACE BRKAL WITH ABRKAL  
                  REPLACE KOLI WITH AKOLI
                  REPLACE CENA WITH ACENA
                  REPLACE POT WITH APOT
                  REPLACE SIFRA WITH ASIFRA
                  REPLACE DATROK WITH ADATROK
                  REPLACE DATpro WITH mdatpro
                  REPLACE serija WITH mserija
                  REPLACE sertifik WITH msertifik
                  IF TNET=1
                     SELECT FAK
                  ELSE
                     SELECT FAKS
                  ENDIF
               endif
            ENDIF
         ENDIF
      ENDIF
   ENDIF
   SKIP
ENDDO   

DO CASE TKOJI
CASE TKOJI='KAL'
   SELECT KALG
   SET RELATION TO

CASE TKOJI='RAC'
   SELECT FAKG
   SET RELATION TO
ENDCASE


IF TNET=1
   SELECT KAL
ELSE
   SELECT KALs
ENDIF
SET ORDER TO 1
SET RELATION TO
IF TNET=1
   SELECT FAK
ELSE
   SELECT FAKS
ENDIF
SET ORDER TO 1
SET RELATION TO
SELECT NIV
SET ORDER TO 1
SET RELATION TO

*-----------UZELI SMO SVE PODATKE PRAVIMO PROSECNE CENE------
SELECT AN0
SET ORDER TO 1
select TVKART
go top
MKOL=0
MKOLI=0
MDUG=0
MPOT=0
MNDUG=0
MNPOT=0
DO WHILE.NOT.EOF()
   MKOL=MKOL+KOL
   MKOLI=MKOLI+KOLI
   REPLACE KOLST WITH MKOL-MKOLI
   MDUG=MDUG+DUG
   MPOT=MPOT+POT
   REPLACE SALDO WITH MDUG-MPOT
 
   MNDUG=MNDUG+NDUG
   REPLACE NSALDO WITH MNDUG-MNPOT
   
   IF KOLI<>0 
      IF (KOLST+KOLI)<>0
         MNCENA=NSALDO/(KOLST+KOLI)
      ELSE
         MNCENA=0
      ENDIF
      REPLACE NCENA WITH MNCENA
      REPLACE NPOT WITH MNCENA*KOLI
      MNPOT=MNPOT+NPOT
      REPLACE NSALDO WITH MNDUG-MNPOT
   ENDIF
   SKIP
ENDDO   


GO TOP
SET EXACT ON
SET RELATION TO SIFRA INTO AN0 ADDITIVE
SET RELATION TO RSIF INTO ROB ADDITIVE


DO TVKART2F10ROK


select TVKART
GO TOP
MRSIF=RSIF
SET RELATION TO
use
DO CASE TKOJI
CASE TKOJI='KAL'
   SELECT FAKG
   SET RELATION TO
   SET RELATION TO SIFRA INTO AN0 ADDITIVE
 *  SET RELATION TO FVRSTA INTO FAKPRN ADDITIVE
   
   SELECT KALG
   SET RELATION TO
   SET RELATION TO SIFRA INTO AN0 ADDITIVE
   SET RELATION TO FVRSTA INTO KALPRN ADDITIVE
   
   IF TNET=1
      select FAK
   ELSE
      SELECT FAKS
   ENDIF
   SET RELATION TO BRKAL INTO FAKG  ADDITIVE
   SET RELATION TO RSIF INTO ROB ADDITIVE
   IF TNET=1
      select KAL
   ELSE
      SELECT KALs
   ENDIF
   SET RELATION TO BRKAL INTO KALG  ADDITIVE
   SET RELATION TO RSIF INTO ROB ADDITIVE
CASE TKOJI='RAC'
   SELECT KALG
   SET RELATION TO
   SET RELATION TO SIFRA INTO AN0 ADDITIVE
 
   SELECT FAKG
   SET RELATION TO
   SET RELATION TO SIFRA INTO AN0 ADDITIVE
   SET RELATION TO FVRSTA INTO FAKPRN ADDITIVE
 
   
   IF TNET=1
      select KAL
   ELSE
      SELECT KALs
   ENDIF
   SET RELATION TO BRKAL INTO KALG  ADDITIVE
   SET RELATION TO RSIF INTO ROB ADDITIVE
   SELECT FAKG
*   SET RELATION TO SIFRA INTO AN0 ADDITIVE
   IF TNET=1
      select FAK
   ELSE
      SELECT FAKS
   ENDIF
   SET RELATION TO BRKAL INTO FAKG  ADDITIVE
   SET RELATION TO RSIF INTO ROB ADDITIVE
CASE TKOJI='NIV'
   SELECT KALG
   SET RELATION TO
   SET RELATION TO SIFRA INTO AN0 ADDITIVE
*   SET RELATION TO FVRSTA INTO KALPRN ADDITIVE

   IF TNET=1
      select KAL
   ELSE
      SELECT KALs
   ENDIF
   SET RELATION TO BRKAL INTO KALG  ADDITIVE
   SET RELATION TO RSIF INTO ROB ADDITIVE
   SELECT FAKG
   SET RELATION TO
   SET RELATION TO SIFRA INTO AN0 ADDITIVE
   IF TNET=1
      select FAK
   ELSE
      SELECT FAKS
   ENDIF
   SET RELATION TO BRKAL INTO FAKG  ADDITIVE
   SET RELATION TO RSIF INTO ROB ADDITIVE
   select NIV
   SET RELATION TO RSIF INTO ROB ADDITIVE

CASE TKOJI='AROB'
   SELECT KALG
   SET ORDER TO 1
   SELECT FAKG
   SET ORDER TO 1
   SELECT KAL
   SET RELATION TO BRKAL INTO KALG  ADDITIVE
   SELECT FAK
   SET RELATION TO BRKAL INTO FAKG  ADDITIVE
   SELECT ROB
   SET ORDER TO 1
   SEEK MRSIF
   SET ORDER TO 2
   SET RELATION TO TARIFA INTO TARIFA ADDITIVE
   ROBA0.GRD0.SETFOCUS
   ROBA0.GRD0.REFRESH
   SET EXACT OFF
ENDCASE
POP KEY