PUSH KEY CLEAR
DO CASE TKOJI
  CASE TKOJI='KAL'
     DO ROBABIRAMKAL
  CASE TKOJI='KOM'
     DO ROBABIRAMKOM
  CASE TKOJI='RAC'
     DO ROBABIRAMFAK
  CASE TKOJI='NIV'
     DO ROBABIRAMNIV
  CASE TKOJI='MG'
     DO ROBABIRAMMG
  CASE TKOJI='PRONOR'
     DO ROBABIRAMPRONOR
  CASE TKOJI='PRONAL'
     DO ROBABIRAMPRONAL
  CASE TKOJI='PROPLAN'
     DO ROBABIRAMPROPLAN
  CASE TKOJI='SE'
     DO ROBABIRAMSE
  CASE TKOJI='SA'
     DO ROBABIRAMSA
  CASE TKOJI='POMAT'
     DO ROBABIRAMPOMAT
ENDCASE
POP KEY

