      SELECT ROB
      MRSIF=RSIF
      MMALCENA=MALCENA
      MTARIFA=TARIFA
      MPROCPOR=PROCPOR
      SELECT MG
      SET ORDER TO 
      GO BOTTOM 
      MBRKAL=BRKAL
      MBRFAK=BRFAK
      MSIFRA=SIFRA
      MDATDOK=DATDOK
      MBRRAC=BRRAC
      MOPIS=OPIS
      IF RSIF<>SPACE(5)
         APPEND BLANK
      ENDIF   
      REPLACE BRKAL WITH MBRKAL
      REPLACE BRFAK WITH MBRFAK
      REPLACE RSIF WITH MRSIF    
      REPLACE MALCENA WITH MMALCENA
      REPLACE TARIFA WITH MTARIFA
      REPLACE PROCPOR WITH MPROCPOR
      REPLACE SIFRA WITH MSIFRA
      REPLACE BRRAC WITH MBRRAC
      REPLACE OPIS WITH MOPIS
      REPLACE DATDOK WITH MDATDOK
      ROBA.VISIBLE=.F.
*      MG.GRD0.SETFOCUS
      MG.GRD0.REFRESH
      *MG.REFRESH
      ROBA.VISIBLE=.T. 
