PARAMETERS mPODROB,MDAT0,MDAT1,MFVRSTA,MSIFRA,MINTERNE,MPRENOSNE,MREC
PUSH KEY CLEAR
DO IDEL WITH  (KTVKARTX)
ON ERROR
USE  &KTVKART ALIAS TVKART EXCLU IN 0
SELECT TVKART
DELETE ALL
PACK

ON ERROR DO GRESKE WITH ;
   ERROR( ), MESSAGE( ), MESSAGE(1), PROGRAM( ), LINENO( )

INDEX ON DTOS(DATDOK) TAG DATDOK
SET ORDER TO 1


SET EXACT OFF
 
DO CASE TKOJI

CASE TKOJI='KAL'
   SELECT KALG
   SET RELATION TO

CASE TKOJI='RAC'
   SELECT FAKG
  SET RELATION TO

ENDCASE
   DO idel WITH (kkockax)   

SELECT ROB
COPY STRUCTURE TO &KKOCKA
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
SELECT ROB
SET ORDER TO 9
SEEK MPODROB
IF FOUND()
   DO WHILE.NOT.EOF()
      IF PODROB<>MPODROB
         EXIT
      ENDIF
      SCATTER NAME POLJA
      SELECT KOCKA
      APPEND BLANK
      GATHER NAME POLJA
      SELECT ROB   
      SKIP
   ENDDO   
ENDIF 
SELECT KOCKA
GO TOP
DO WHILE.NOT.EOF()
   MRSIF=RSIF
   MNAZ=NAZ
   MDUZINA=DUZINA
   MSIRINA=SIRINA
   MVELICINA=VELICINA
   MBOJA=BOJA
   *---------UZIMAMO ROBU IZ KALKULACIJA------------
   SELECT KAL
   SET ORDER TO 2
   SEEK MRSIF
   DO WHILE.NOT.EOF()
   IF RSIF<>MRSIF
      EXIT
   ENDIF
   IF DATDOK>=MDAT0.AND.DATDOK<=MDAT1
      IF KALG.FVRSTA=MFVRSTA.OR.MFVRSTA=SPACE(3)
         IF KALG.SIFRA=MSIFRA.OR.MSIFRA=SPACE(5)
            IF KALG.INTERNA=MINTERNE.OR.MINTERNE=' '
               IF KALG.PRENOS=MPRENOSNE.OR.MPRENOSNE=' '
                  ADATDOK=DATDOK
                  Abrkal=brkal
                  AKOL=KOL
                  AKOLI=0
                  AKOLST=0
                  IF TOBJEKAT='V'
                     ACENA=VELCENA
                     ADUG=VELVRED
                     APOT=0
                     ASALDO=0
                  ELSE
                     Acena=malcena
                     ADUG=MALVRED
                     APOT=0
                     ASALDO=0
                  endif
                  ANCENA=NABCENA
                  ANDUG=NABVRED
                  ANPOT=0
                  ANSALDO=0
                  ASIFRA=KALG.SIFRA                       
                  
                  SELECT TVKART
                  APPEND BLANK 
                  REPLACE RSIF WITH MRSIF
                  REPLACE DATDOK WITH ADATDOK
                  REPLACE BRKAL WITH ABRKAL  
                  REPLACE KOL WITH AKOL
                  REPLACE KOLI WITH AKOLI
                  REPLACE KOLST WITH AKOLST
                  REPLACE CENA WITH ACENA
                  REPLACE DUG WITH ADUG
                  REPLACE POT WITH APOT
                  REPLACE SALDO WITH ASALDO
                  REPLACE NCENA WITH ANCENA
                  REPLACE NDUG WITH ANDUG
                  REPLACE NPOT WITH ANPOT
                  REPLACE NSALDO WITH ANSALDO
                  REPLACE SIFRA WITH ASIFRA
                  REPLACE BOJA WITH MBOJA
                  REPLACE DUZINA WITH MDUZINA
                  REPLACE SIRINA WITH MSIRINA
                  REPLACE VELICINA WITH MVELICINA
                  REPLACE NAZ WITH MNAZ
                  IF TNET=1  
                     SELECT KAL
                  ELSE
                     SELECT KALs
                  ENDIF
               endif
            ENDIF
         ENDIF
      ENDIF
   ENDIF
   SKIP
ENDDO   

*---------UZIMAMO ROBU IZ NIVELACIJA------------
SELECT NIV
SET ORDER TO 2
SEEK MRSIF
DO WHILE.NOT.EOF()
   IF RSIF<>MRSIF
      EXIT
   ENDIF
   IF DATDOK>=MDAT0.AND.DATDOK<=MDAT1
      ADATDOK=DATDOK
      Ambrkal=brkal
      IF TOBJEKAT='V'
         ACENA=VELCENA
         ADUG=VELVRED
         ASCENA=SCENA
         ASDUG=-SIZNOS
         AKOL=KOL
         
         
      ELSE
         Acena=malcena
         ADUG=MALVRED
         ASDUG=-SIZNOS         
         ASCENA=SCENA
         AKOL=KOL
      endif
      SELECT TVKART
      APPEND BLANK 
      REPLACE BRKAL WITH AMBRKAL
      REPLACE RSIF WITH MRSIF
      REPLACE DATDOK WITH ADATDOK
      REPLACE DUG WITH ASDUG
      REPLACE CENA WITH ASCENA
      REPLACE KOL WITH -AKOL
      REPLACE BOJA WITH MBOJA
      REPLACE DUZINA WITH MDUZINA
      REPLACE SIRINA WITH MSIRINA
      REPLACE VELICINA WITH MVELICINA
      REPLACE NAZ WITH MNAZ
      APPEND BLANK 
      REPLACE BRKAL WITH AMBRKAL
      REPLACE RSIF WITH MRSIF
      REPLACE DATDOK WITH ADATDOK
      REPLACE DUG WITH ADUG
      REPLACE CENA WITH ACENA
      REPLACE KOL WITH AKOL
      REPLACE BOJA WITH MBOJA
      REPLACE DUZINA WITH MDUZINA
      REPLACE SIRINA WITH MSIRINA
      REPLACE VELICINA WITH MVELICINA
      REPLACE NAZ WITH MNAZ
      
      SELECT NIV
   endif
   SKIP
ENDDO   


*---------UZIMAMO ROBU IZ RACUNA------------
SELECT FAK

SET ORDER TO 2
SEEK MRSIF
DO WHILE.NOT.EOF()
   IF RSIF<>MRSIF
      EXIT
   ENDIF
   IF DATDOK>=MDAT0.AND.DATDOK<=MDAT1
      IF FAKG.FVRSTA=MFVRSTA.OR.MFVRSTA=SPACE(3)
         IF FAKG.SIFRA=MSIFRA.OR.MSIFRA=SPACE(5)
            IF FAKG.INTERNA=MINTERNE.OR.MINTERNE=' '
               IF FAKG.PRENOS=MPRENOSNE.OR.MPRENOSNE=' '
                  ADATDOK=DATDOK
                  Abrkal=brkal
                  AKOLI=KOLI
                  IF TOBJEKAT='V'
                     ACENA=VELCENA
                     APOT=VELVRED
                  ELSE
                     Acena=malcena
                     APOT=MALVRED
                  endif
                  ASIFRA=FAKG.SIFRA                       
                  
                  SELECT TVKART
                  APPEND BLANK 
                  REPLACE RSIF WITH MRSIF
                  REPLACE DATDOK WITH ADATDOK
                  REPLACE BRKAL WITH ABRKAL  
                  REPLACE KOLI WITH AKOLI
                  REPLACE CENA WITH ACENA
                  REPLACE POT WITH APOT
                  REPLACE SIFRA WITH ASIFRA
                  REPLACE BOJA WITH MBOJA
                  REPLACE DUZINA WITH MDUZINA
                  REPLACE SIRINA WITH MSIRINA
                  REPLACE VELICINA WITH MVELICINA
                  REPLACE NAZ WITH MNAZ
                  SELECT FAK
               endif
            ENDIF
         ENDIF
      ENDIF
   ENDIF
   SELECT FAK
   SKIP
ENDDO   
SELECT KOCKA
SKIP
ENDDO
SELECT KOCKA
USE

   SELECT KAL

SET ORDER TO 1
SET RELATION TO
SELECT FAK
SET ORDER TO 1
SET RELATION TO
SELECT NIV
SET ORDER TO 1
SET RELATION TO


SELECT TVKART
GO TOP
SET EXACT ON
SET RELATION TO SIFRA INTO AN0 ADDITIVE
SET RELATION TO RSIF INTO ROB ADDITIVE

*-----------UZELI SMO SVE PODATKE PRAVIMO PROSECNE CENE------
select TVKART
go top
MKOL=0
MKOLI=0
MDUG=0
MPOT=0
DO WHILE.NOT.EOF()
   MKOL=MKOL+KOL
   MKOLI=MKOLI+KOLI
   REPLACE KOLST WITH MKOL-MKOLI
   MDUG=MDUG+DUG
   MPOT=MPOT+POT
   REPLACE SALDO WITH MDUG-MPOT
   SKIP
ENDDO   
GO TOP

DO TVKART2F10G

select TVKART
GO TOP
MRSIF=RSIF
SET RELATION TO
use
DO CASE TKOJI
CASE TKOJI='KAL'
   SELECT KALG
   SET RELATION TO SIFRA INTO AN0 ADDITIVE
      select KAL
   SET RELATION TO BRKAL INTO KALG  ADDITIVE
   SET RELATION TO RSIF INTO ROB ADDITIVE
CASE TKOJI='RAC'
   SELECT FAKG
   SET RELATION TO SIFRA INTO AN0 ADDITIVE
select FAK
   SET RELATION TO BRKAL INTO FAKG  ADDITIVE
   SET RELATION TO RSIF INTO ROB ADDITIVE
CASE TKOJI='NIV'
   select NIV
   SET RELATION TO RSIF INTO ROB ADDITIVE
CASE TKOJI='AROB'
   SELECT KALG
   SET ORDER TO 1
   SELECT FAKG
   SET ORDER TO 1
   SELECT KAL
   SET RELATION TO BRKAL INTO KALG  ADDITIVE
   SELECT FAK
   SET RELATION TO BRKAL INTO FAKG  ADDITIVE
   SELECT ROB
   SET ORDER TO 1
   SEEK MRSIF
   SET ORDER TO 2
   SET RELATION TO TARIFA INTO TARIFA ADDITIVE
   ROBA0.GRD0.SETFOCUS
   ROBA0.GRD0.REFRESH
   SET EXACT OFF
ENDCASE
POP KEY