PUSH KEY CLEAR
SELECT ROB
USE
IF TOBJEKAT='V'
   IF TSIFARNIK<>'  '
      KROB='ROB'+ALLTRIM(TSIFARNIK)
   ELSE
      KROB='ROB'
   ENDIF
ELSE
   IF TSIFARNIK<>'  '
      KROB='MROB'+ALLTRIM(TSIFARNIK)
   ELSE
      KROB='ROB'
   ENDIF
ENDIF
if tfpossif='D'.AND.TNEZAJEDNO<>'D'
   KROB='rob'+tobjekat+TTVREDNI
ENDIF     
USE &KROB ALIAS ROB IN 0 ORDER 1 EXCLUSIVE
SELECT ROB
DO FORM ROBADUPSIF2BK
ROBAPROVERE00.RELEASE
ROBA0.RELEASE
POP KEY