PUSH KEY CLEAR
SELECT ROB
SET FILTER TO 
IF RECCOUNT()>0
   SET ORDER TO 
   *GO BOTTOM
   *IF NAZ=SPACE(30)
   *   SKIP -1
      SCATTER NAME POLJA
   *  SKIP
      APPEND BLANK
      GATHER NAME POLJA
      REPLACE RSIF WITH STR(RECNO(),5,0)
*   ENDIF
      ROBA.GRD0.SETFOCUS
      ROBA.GRD0.REFRESH
      DO ROBAKARTF7
ENDIF

ROBA.GRD0.SETFOCUS
POP KEY