SELECT ROB
MRSIF=RSIF
MRCENA=PLCENA
SELECT PROPLAN 
IF RSIF<>SPACE(5)
   APPEND BLANK
   REPLACE RSIF WITH MRSIF
   REPLACE RCENA WITH MRCENA    
   SELECT PRONORMA
   SEEK MRSIF
   IF FOUND()
      MNORMATIV=NORMATIV
   ELSE
      MNORMATIV=' '
   ENDIF
   SELECT PROPLAN
   REPLACE NORMATIV WITH MNORMATIV      
ENDIF   
