PUSH KEY CLEAR
CLOSE ALL
*SET STEP ON 
USE &KFAK IN 0 ALIAS FAK EXCLU
SELECT FAK
ROBA0PROSCEN.LBLROBA.CAPTION=' SORTIRAMO FAKTURE '

SORT TO REZ ON DATDOK,BRKAL
DELETE ALL
PACK

APPEND FROM REZ
USE

USE &KKAL IN 0 ALIAS kal EXCLUSIVE
SELECT kal 
ROBA0PROSCEN.LBLROBA.CAPTION='SORTIRAMO KALKULACIJE '

SORT TO REZ2 ON DATDOK,BRKAL
DELETE ALL
PACK

APPEND FROM REZ2
USE


USE PROSCEN IN 0 EXCLU
SELECT PROSCEN
INDEX ON DTOS(DATDOK) TAG DATOK
SET ORDER TO 1

   if tfpossif='D'.AND.TNEZAJEDNO<>'D'

      KROB='rob'+tobjekat+TTVREDNI
   ENDIF     

USE &KROB IN 0 ALIAS ROB ORDER 1
SELECT ROB   
MLASTREC=RECCOUNT()
SET ORDER TO 1
USE &KFAK IN 0 ORDER 2 ALIAS FAK
USE &KFAKG IN 0 ORDER 1 ALIAS FAKG

SELECT FAK
SET RELATION TO BRKAL INTO FAKG ADDITIVE

USE &KKAL IN 0 ORDER 2 ALIAS KAL
USE &KKALG IN 0 ORDER 1 ALIAS KALG
SELECT KAL
SET RELATION TO BRKAL INTO KALG ADDITIVE


SELECT ROB
GO TOP
DO WHILE.NOT.EOF()
   MRSIF=RSIF
   SELECT KAL
   SEEK MRSIF
   IF FOUND()
      SELECT PROSCEN
DELETE ALL
PACK

      SELECT KAL
      DO WHILE.NOT.EOF()
         IF RSIF<>MRSIF
            EXIT
         ENDIF   
         MKOL=KOL
         MNABVRED= IZNOS-RABAT+ZAVISNI+zavisnin+ZAVISNIC+ZAVISC2+ZAVISC3+cardin+trdob+trdobn+zaokruz
         MDATDOK=DATDOK
         SELECT PROSCEN
         APPEND BLANK
         REPLACE RSIF WITH MRSIF
         REPLACE KOL WITH MKOL
         REPLACE NABVRED WITH MNABVRED
         IF KOL<>0
            REPLACE NABCENA WITH ROUND(NABVRED/KOL,4)
         ENDIF   
         REPLACE DATDOK WITH MDATDOK
         SELECT KAL
         SKIP
      ENDDO   
      SELECT FAK
      SEEK MRSIF
      IF FOUND()
         DO WHILE.NOT.EOF()
            IF RSIF<>MRSIF
               EXIT
            ENDIF   
            MKOLI=KOLI
            MREC=RECNO()
            MDATDOK=DATDOK
            SELECT PROSCEN
            APPEND BLANK
            REPLACE RREC WITH MREC
            REPLACE RSIF WITH MRSIF
            REPLACE KOLI WITH MKOLI
            REPLACE DATDOK WITH MDATDOK
            SELECT FAK
            SKIP
         ENDDO   
      ENDIF
      SELECT PROSCEN
 *     SET STEP ON 
      GO TOP
      MKOLST=0
      MNABVRED=0
      MIZNI=0
      MNABVREDST=0
      MMCENA=0
      DO WHILE.NOT.EOF()
*         BROWSE
         MRREC=RREC
         MKOLST=MKOLST+KOL-KOLI
         MNABVRED=MNABVRED+NABVRED
         MNABVREDST=MNABVRED-MIZNI
         IF MRREC<>0.AND.CENA<>0
            MMCENA=CENA
         ENDIF   
         IF MKOLST+KOLI<>0
            MMIZNI=ROUND(MNABVREDST*KOLI/(MKOLST+KOLI),4) 
         ELSE
            MMIZNI=0
         ENDIF   
         IF KOLI<>0
            MCENA=ROUND(MMIZNI/KOLI,4)
            IF MRREC<>0
               REPLACE CENA WITH MCENA
               IF MRREC<>0.AND.CENA<>0
                  MMCENA=CENA
               ENDIF   
               IF CENA=0
                  REPLACE CENA WITH MMCENA
               ENDIF
               MCENA=CENA
               MMIZNI=ROUND(KOLI*CENA,4) 
               SELECT FAK
               GOTO MRREC
               REPLACE CENA WITH MCENA
               SELECT PROSCEN
            ENDIF   
         ENDIF
         MIZNI=MIZNI+MMIZNI
         SKIP
      ENDDO
   ENDIF
   SELECT ROB
   ROBA0PROSCEN.LBLROBA.CAPTION=TRANSFORM(RECCOUNT(),'9999999')+' '+TRANSFORM(RECNO(),'9999999')+' '+TRANSFORM(RECCOUNT()-RECNO(),'9999999')+' '+ROB.NAZ
   SKIP
ENDDO

CLOSE ALL
POP KEY
