PUSH KEY CLEAR
SELECT NIV
MREDREC=RECNO()
MREDZAD=RECCOUNT()
MBRKAL=BRKAL
MDATDOK=DATDOK
MBRNAL=BRNAL
SELECT ROB
MKOL=KOL
MNAZ=NAZ
MRSIF=RSIF
MTARIFA=TARIFA
MVELCENA=VELCENA
MMALCENA=MALCENA
MPROCPOR=PROCPOR
IF TUNKOL='D'
   IF MREDREC=MREDZAD
      SELECT ROB
      DO FORM TVUNKOL
      SELECT ROB
      ROBA.GRD0.SETFOCUS
      ROBA.GRD0.REFRESH
   ELSE
      DO PORUKAU WITH ' NISTE NA ZADNJEM POLJU NIVELACIJE '
   ENDIF
ELSE
   MKOL=0
ENDIF

SELECT NIV
IF MREDREC=MREDZAD
   IF ARHIVA=' '
      SELECT IROB
      APPEND BLANK
      REPLACE REDBR WITH RECNO()
      REPLACE RSIF WITH MRSIF
      REPLACE NAZ WITH MNAZ
      REPLACE KOL WITH MKOL
      REPLACE BRKAL WITH MBRKAL
      REPLACE DATDOK WITH MDATDOK
      REPLACE TARIFA WITH MTARIFA
      REPLACE PROCPOR WITH MPROCPOR
      REPLACE VELCENA WITH MVELCENA
      REPLACE MALCENA WITH MMALCENA
      REPLACE BRNAL WITH MBRNAL
   ENDIF
ELSE
   DO PORUKAU WITH ' NISTE NA ZADNJEM POLJU NIVELACIJE '
endif   
SELECT ROB
POP KEY


