PUSH KEY CLEAR
IF TFPOSSIF<>'D'
SELECT ROB
SET ORDER TO
APPEND BLANK
REPLACE rsif WITH STR(RECNO(),5,0)
REPLACE PSIF WITH RSIF
REPLACE MSIF WITH RSIF
REPLACE PMSIF WITH RSIF
REPLACE ASIF WITH RSIF

REPLACE JED WITH 'KOM'
REPLACE TARIFA WITH '20'
REPLACE PROCPOR WITH 20
REPLACE VRSTA WITH 'N'
ROBA0.GRD0.REFRESH

DO FORM ROBAK2

SELECT ROB
SET ORDER TO 2
ROBA0.GRD0.SETFOCUS
ROBA0.REFRESH
ENDIF
POP KEY
