PUSH KEY CLEAR
SELECT ROB
SET FILTER TO 
GO BOTTOM
IF TFSIFARNIK<>SPACE(8)
   IF TZSIFARNIK='D'
      SELECT ROB
      SET RELATION TO
      MZSIFARNIK=TFSIFARNIK
      USE &MZSIFARNIK IN 0 ALIAS ROBA
      SELECT ROBA
      SET RELATION TO TARIFA INTO TARIFA ADDITIVE
      GO BOTTOM
      SELECT ROBA
      GO BOTTOM
      M2REC=RECCOUNT()
      SELECT ROB
      SET RELATION TO TARIFA INTO TARIFA ADDITIVE
      SELECT ROB
      GO BOTTOM
      M3REC=RECCOUNT()
      IF M3REC<M2REC
         SELECT ROBA
         GOTO M3REC+1
         DO WHILE.NOT.EOF()
            SCATTER NAME POLJA
            SELECT ROB
            APPEND BLANK
            GATHER NAME POLJA
            SELECT ROBA
            SKIP
         ENDDO   
      ENDIF
      SELECT ROBA
      USE
      SELECT ROB
   ENDIF
ENDIF
ROBA.GRD0.SETFOCUS
POP KEY
ROBA.REFRESH
