PARAMETERS MRSIF0,MRSIF1
PUSH KEY CLEAR
MNAZ=ROB.NAZ
   DO idel WITH (kkockax)   
   DO idel WITH (kkockax2)   
   DO idel WITH (kkockax3)   
   DO idel WITH (kkockax4)   

USE &KTVKART IN 0  ALIAS TVKART  EXCLU
SELECT TVKART
INDEX ON DATDOK TAG DATDOK
SET ORDER TO TAG DATDOK

SELECT KAL
COPY STRUCTURE TO &KKOCKA2
USE &KKOCKA2 IN 0 ALIAS KOCKA2 EXCLU
SELECT kocka2
INDEX on rsif TAG kol
SET ORDER TO 1

SELECT FAK
SET ORDER TO 2
SELECT ROB
SET ORDER TO 1
GO TOP
BROJAC=0
BBROJAC=0
KKOJA=0
DO WHILE.NOT.EOF()
   IF VAL(RSIF)>=MRSIF0.AND.VAL(RSIF)<MRSIF1 
   IF VRSTA<>'U'
   MRSIF=RSIF
   BBROJAC=BBROJAC+1
   ROBAMINUS.LBLROBA.CAPTION=RSIF+' '+NAZ+' '+TRAN(RECCOUNT()-BBROJAC,'9999999')
   MENAZ=NAZ
   IF NAZ<>SPACE(30)
   SELECT TVKART
   DELETE ALL
   PACK

   SELECT KAL
   SET ORDER TO 2
   SEEK MRSIF
   IF FOUND()
      DO WHILE.NOT.EOF()
         IF RSIF<>MRSIF
            EXIT
         ENDIF   
         MDATDOK=KALG.DATDOK
         MRSIF=RSIF
         MKOL=KOL
         MVELCENA=VELCENA
         SELECT TVKART
         APPEND BLANK
         REPLACE DATDOK WITH MDATDOK
         REPLACE RSIF WITH MRSIF
         REPLACE KOL WITH MKOL
         REPLACE VELCENA WITH MVELCENA
         SELECT KAL
         SKIP
      ENDDO
   ENDIF
   *----------------RACUN VELOPRODAJE
   SELECT FAK
   SEEK MRSIF
   IF FOUND()
      DO WHILE.NOT.EOF()
         IF RSIF<>MRSIF
            EXIT
         ENDIF   
         MDATDOK=FAKG.DATDOK
         MRSIF=RSIF
         MKOLI=KOLI
         MVELCENA=VELCENA
         SELECT TVKART
         APPEND BLANK
         REPLACE DATDOK WITH MDATDOK
         REPLACE RSIF WITH MRSIF
         REPLACE KOLI WITH MKOLI
         REPLACE VELCENA WITH MVELCENA
         SELECT FAK
         SKIP
      ENDDO
   ENDIF
   *-------------------PRIKAZ KARTICE -------------------
   SELECT TVKART
   IF RECCOUNT()>0
      GO TOP
      mkolul=0
      mkoliz=0
      mulaz=0
      mizlaz=0
      MEKOL=0
      BROJAC=0
      *@ 0,0 CLEAR
      DO WHILE.NOT.EOF()
         MKOLUL=MKOLUL+KOL
         mkoliz=mkoliz+koli
         MKOLST=MKOLUL-MKOLIZ
         REPLACE KOLST WITH MKOLST
         IF KOLST<0
            ROBAMINUS.LBLROBA2.CAPTION=RSIF+' '+BRKAL+' '+DTOC(DATDOK)+' '+str(MKOLUL-MKOLIZ,11,3)
            SELECT KOCKA2
            MKKAL='MANJAK'
            MDATDOK=CTOD('')
            MCENA=VELCENA
            APPEND BLANK
               REPLACE BRKAL WITH MKKAL
               REPLACE RSIF WITH MRSIF
               REPLACE DATDOK WITH MDATDOK
               REPLACE KOL WITH MKOLST
               REPLACE CENA WITH MCENA
               REPLACE VELCENA WITH MCENA
            SELECT TVKART
         ENDIF
         BROJAC=BROJAC+1
         skip
      ENDDO
      ENDIF
   ENDIF
   ENDIF
   ENDIF
   SELECT ROB
   SKIP
ENDDO

SELECT kocka2
SORT ON RSIF,kol TO &kkocka3 
DELETE ALL
PACK

APPEND FROM &KKOCKA3

SELECT rob
GO top
DO while.not.eof()
   mrsif=rsif
   MCENA=VELCENA
   SELECT kocka2
   SEEK mrsif
   IF FOUND()
*      IF RSIF='    5'
*        BROWSE
*      ENDIF  
      BROJAC=0
      DO while.not.eof()
         IF RSIF<>MRSIF
            EXIT
         ENDIF
         IF BROJAC>0
            REPLACE KOL WITH 0
         ELSE   
            REPLACE CENA WITH MCENA
         ENDIF      
         SKIP
         BROJAC=BROJAC+1
      ENDDO   
   ENDIF
   SELECT ROB
   SKIP
enddo   

SELECT KOCKA2
DELETE ALL FOR KOL=0
PACK

GO TOP
DO WHILE.NOT.EOF()
   MKKAL='MANJAK'
   MDATDOK=CTOD('')
   MKOL=kol
   MRSIF=RSIF
   MCENA=CENA
   SELECT kal
   APPEND BLANK
   REPLACE BRKAL WITH MKKAL
   REPLACE RSIF WITH MRSIF
   REPLACE DATDOK WITH MDATDOK
   REPLACE KOL WITH -MKOL
   REPLACE CENA WITH MCENA
   REPLACE VELCENA WITH MCENA
   SELECT kocka2
   SKIP
ENDDO   
SELECT KOCKA2
USE
SELECT ROB
POP KEY