PUSH KEY CLEAR
ROBA.CMDDODAJ.SETFOCUS
   if tfpossif<>'D'.OR.TNEZAJEDNO='D'

   SELECT ROB
   SET FILTER TO 
   SET ORDER TO 
   GO BOTTOM
   APPEND BLANK
   REPLACE rsif WITH STR(RECNO(),5,0)
   REPLACE PSIF WITH RSIF
   REPLACE MSIF WITH RSIF
   REPLACE PMSIF WITH RSIF
   REPLACE ASIF WITH RSIF
   MMRECC=RECCOUNT()
   REPLACE JED WITH 'KOM'
   REPLACE TARIFA WITH tostopa
   REPLACE PROCPOR WITH VAL(toStopa)
   REPLACE VRSTA WITH 'N'
   ROBA.GRD0.REFRESH
   DO FORM ROBAK2   
   ROBA.GRD0.REFRESH
   ROBA.GRD0.SETFOCUS
   ROBA.REFRESH
ENDIF
POP KEY
