PUSH KEY CLEAR
ROBA.COMMAND2.SETFOCUS
SELECT ROB
MRSIF=RSIF
SET EXACT OFF
DO IDEL WITH (KKOCKAX)
DO IDEL WITH (KKOCKAX2)
DO IDEL WITH (KKOCKAX3)
DO IDEL WITH (KKOCKAX4)

IF TNET=1
SELECT KAL 
ELSE
SELECT KALS
ENDIF
SET ORDER TO 2
IF RECCOUNT()>0
   MRKAL=RECNO()
ELSE
   MRKAL=0
ENDIF
COPY STRUCTURE TO &KKOCKA
IF TNET=1
SELECT FAK
ELSE
SELECT FAKS
ENDIF
SET ORDER TO 2
IF RECCOUNT()>0
   MRFAK=RECNO()
ELSE
   MRFAK=0
ENDIF

COPY STRUCTURE TO &KKOCKA2
USE AATV IN 0
SELECT AATV
MREC=RECCOUNT()
USE
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
USE &KKOCKA2 IN 0 ALIAS KOCKA2 EXCLU
IF TNET=1
SELECT KAL
ELSE
SELECT KALS
ENDIF
SEEK MRSIF
IF FOUND()
   DO WHILE.NOT.EOF()
      IF RSIF<>MRSIF
        EXIT
      ENDIF  
      SCATTER NAME POLJA
      SELECT KOCKA
      APPEND BLANK
      GATHER NAME POLJA
      IF TNET=1
      SELECT KAL         
      ELSE
      SELECT KALS
      ENDIF
      SKIP
   ENDDO   
ENDIF
IF TNET=1   
   SELECT FAK
ELSE
   SELECT FAKS
ENDIF
SEEK MRSIF
IF FOUND()
   DO WHILE.NOT.EOF()
      IF RSIF<>MRSIF
         EXIT
      ENDIF   
      SCATTER NAME POLJA
      SELECT KOCKA2
      APPEND BLANK
      GATHER NAME POLJA
      IF TNET=1
      SELECT FAK      
      ELSE
      SELECT FAKS
      ENDIF
      SKIP
   ENDDO   
ENDIF

*------------NAPUNJENJE BAZE---------------------------
DO IDEL WITH  (KTVKARTX)
ON ERROR
USE  &KTVKART ALIAS TVKART EXCLU IN 0
SELECT TVKART
DELETE ALL
PACK

ON ERROR DO GRESKE WITH ;
   ERROR( ), MESSAGE( ), MESSAGE(1), PROGRAM( ), LINENO( )
INDEX ON DTOS(DATDOK) TAG DATDOK
SET ORDER TO 1

*---------UZIMAMO ROBU IZ KALKULACIJA------------
SELECT KOCKA
GO TOP
DO WHILE.NOT.EOF()
   ADATDOK=DATDOK
   Abrkal=brkal
   AKOL=KOL
   MNCENA=NABCENA
   mdok=sbrkal
   MMARZA=MARZA
   IF TOBJEKAT='V'
      ACENA=VELCENA
   ELSE
      Acena=malcena-ROUND(MALCENA*PROCPOR/100,2)
   ENDIF
   SELECT TVKART
   APPEND BLANK 
   REPLACE RSIF WITH MRSIF
   REPLACE DATDOK WITH ADATDOK
   REPLACE BRKAL WITH ABRKAL  
   REPLACE KOL WITH AKOL
   REPLACE NCENA WITH MNCENA
   REPLACE SALDO WITH MMARZA
   replace dok WITH mdok
   REPLACE CENA WITH ACENA
   SELECT KOCKA
   SKIP
ENDDO   
*---------UZIMAMO ROBU IZ RACUNA------------
SELECT KOCKA2
GO TOP
DO WHILE.NOT.EOF()
   ADATDOK=DATDOK
   Abrkal=brkal
   AKOLI=KOLI
   AMARZA=MARZA-RABAT-RABAT2
   mdok=sbrkal
   MNCENA=CENA
   MMARZA=AMARZA
   IF TOBJEKAT='V'
      ACENA=VELCENA
   ELSE
      Acena=malcena-ROUND(MALCENA*PROCPOR/100,2)
   endif
   SELECT TVKART
   APPEND BLANK 
   REPLACE RSIF WITH MRSIF
   REPLACE DATDOK WITH ADATDOK
   REPLACE BRKAL WITH ABRKAL  
   REPLACE KOLI WITH AKOLI
   REPLACE NCENA WITH MNCENA
   REPLACE CENA WITH ACENA
   REPLACE SALDO WITH -MMARZA
   replace dok WITH mdok
   SELECT KOCKA2
   SKIP
ENDDO   
SELECT kocka
USE
SELECT kocka2
USE
SELECT ROB 
SET ORDER TO 1
SELECT TVKART
GO TOP
MKOLST=0
DO WHILE.NOT.EOF()
   MKOLST=MKOLST+KOL-KOLI
   REPLACE KOLST WITH MKOLST    
   SKIP
ENDDO   
SET EXACT ON
SET RELATION TO SIFRA INTO AN0 ADDITIVE
SET RELATION TO RSIF INTO ROB ADDITIVE
SELECT TVKART
*REPORT FORM ROBAF4KARTICA PREVIEW
   mfile='ROBAF4KARTICA'   
   uslov=""
   DO printer_bullzip WITH mdata02,mfile,uslov


SELECT TVKART
SET RELATION TO
USE
IF TNET=1
SELECT KAL
ELSE
SELECT KALS
ENDIF
SET ORDER TO 
IF TNET<>1
IF MRKAL>0
GOTO MRKAL
ENDIF
ENDIF

IF TNET=1
SELECT FAK
ELSE
SELECT FAKS
ENDIF
SET ORDER TO 
IF TNET=1
IF MRFAK>0
GOTO MRFAK
ENDIF
ENDIF
SELECT ROB
SET ORDER TO 1
SEEK MRSIF
SET ORDER TO 2
ROBA.GRD0.SETFOCUS
POP KEY