PUSH KEY CLEAR
SELECT KAL
MREDREC=RECNO()
MREDZAD=RECCOUNT()
MBRKAL=BRKAL
MDATDOK=DATDOK
SELECT ROB
MKOL=KOL
MRSIF=RSIF
MTARIFA=TARIFA
MVELCENA=VELCENA
MMALCENA=MALCENA
MRCENA=PLCENA
MPROCPOR=PROCPOR
MNAZ=NAZ
IF TOBJEKAT='V'
   MZADNAB=ZADNAB
   MAPROSCEN=PROSCENV
ELSE
   MZADNAB=ZADNABM
   MAPROSCEN=PROSCENM
ENDIF   
IF TUNKOL='D'
   IF MREDREC=MREDZAD
      SELECT ROB
      DO FORM TVUNKOL
      SELECT ROB
      ROBA.GRD0.SETFOCUS
      ROBA.GRD0.REFRESH
      MKOL=T2UNKOL
      REPLACE KOL WITH KOL+MKOL
   ELSE
      DO PORUKAU WITH ' NISTE NA ZADNJEM POLJU KALKULACIJE '
   ENDIF
ELSE
   MKOL=0
ENDIF
SELECT KAL
IF MREDREC=MREDZAD
   IF KALG.ARHIVA=' '
      SELECT IROB
      APPEND BLANK
      REPLACE REDBR WITH RECNO()
      REPLACE RSIF WITH MRSIF
      REPLACE NAZ WITH MNAZ
      REPLACE KOL WITH MKOL
      REPLACE BRKAL WITH MBRKAL
      REPLACE DATDOK WITH MDATDOK
      REPLACE TARIFA WITH MTARIFA
      REPLACE PROCPOR WITH MPROCPOR
      REPLACE VELCENA WITH MVELCENA
      REPLACE MALCENA WITH MMALCENA
      REPLACE ZADNAB WITH MZADNAB
   ENDIF
ELSE
   DO PORUKAU WITH ' NISTE NA ZADNJEM POLJU KALKULACIJE '
endif   
SELECT ROB
POP KEY
