PUSH KEY CLEAR
SELECT ROBHEM0
SET ORDER TO 
GO BOTTOM
APPEND BLANK
GO BOTTOM
ROBHEM0.GRD0.SetFocus
ROBHEM0.GRD0.REFRESH
*REPLACE MISIFRA WITH STR(RECNO(),5,0)
*DO FORM AN0MIKART
GO BOTTOM
SET ORDER TO 1
ROBHEM0.GRD0.SetFocus
ROBHEM0.GRD0.REFRESH
ROBHEM0.REFRESH  
POP KEY