PUSH KEY CLEAR
SELECT ROBHEM
SET ORDER TO 
GO BOTTOM
APPEND BLANK
GO BOTTOM
ROBHEM.GRD0.SetFocus
ROBHEM.GRD0.REFRESH
*REPLACE MISIFRA WITH STR(RECNO(),5,0)
*DO FORM AN0MIKART
GO BOTTOM
ROBHEM.GRD0.SetFocus
ROBHEM.GRD0.REFRESH
ROBHEM.REFRESH  
POP KEY