PUSH KEY CLEAR
SELECT AN0

DO FORM FAN0

MSIFRA=SIFRA
SELECT ROB
ROBA0IZVMI.GOTFOCUS
MMSIFRA=ROBA0IZVMI.TXTSIFRA.VALUE

IF MMSIFRA=SPACE(5)
   ROBA0IZV.TXTSIFRA.VALUE=MSIFRA
ENDIF   
ROBA0IZVMI.COMMAND1.SETFOCUS
ROBA0IZVMI.REFRESH
POP KEY
