PUSH KEY CLEAR
*robmasine.grd0.recordsource=''
SELECT ROB
SET ORDER TO 
GO BOTTOM
IF RECCOUNT()>0
MDATDOK=DATDOK
ENDIF
SET ORDER TO
APPEND BLANK
GO BOTTOM
IF RECCOUNT()>1
   REPLACE DATDOK WITH MDATDOK
ENDIF   
SET ORDER TO 
*robmasine.grd0.recordsource='rob'
robmasine.refresh
GO bottom
ROBMASINE.GRD0.COLUMN2.SETFOCUS
POP KEY
*ROBMASINE.REFRESH
