PARAMETERS ASVAROBA,APODRSIF
PUSH KEY CLEAR
MMPODRSIF=APODRSIF
DO IDEL WITH (KKOCKAX)
DO IDEL WITH (KKOCKAX2)
DO IDEL WITH (KKOCKAX3)
DO IDEL WITH (KKOCKAX4)
DO IDEL WITH (KKOCKAX6)
DO IDEL WITH (KKOCKAX7)
DO IDEL WITH (KKOCKAX8)

SELECT KAL 
COPY STRUCTURE TO &KKOCKA
COPY STRUCTURE TO &KKOCKA6
SELECT FAK
COPY STRUCTURE TO &KKOCKA2
COPY STRUCTURE TO &KKOCKA7
SELECT ROB
COPY STRUCTURE TO &KKOCKA3
COPY STRUCTURE TO &KKOCKA8

USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
USE &KKOCKA2 IN 0 ALIAS KOCKA2 EXCLU
USE &KKOCKA3 IN 0 ALIAS KOCKA3 EXCLU


USE &KKOCKA6 IN 0 ALIAS KOCKA6 EXCLU
USE &KKOCKA7 IN 0 ALIAS KOCKA7 EXCLU
USE &KKOCKA8 IN 0 ALIAS KOCKA8 EXCLU

SELECT KAL
USE
SELECT KALG
USE
SELECT FAK
USE
SELECT FAKG
USE
   USE AATV IN 0
   SELECT AATV
   GO top
   mrec=RECNO()
   DO while.not.eof()
      i=RECNO()
      IF flager='D'
         AKAL='KAL'+ALLTRIM(STR(I,2,0))+'.DBF'
         AKALG='KALG'+ALLTRIM(STR(I,2,0))+'.DBF'
         AFAK='FAK'+ALLTRIM(STR(I,2,0))+'.DBF'
         AFAKG='FAKG'+ALLTRIM(STR(I,2,0))+'.DBF'
         USE &AKAL IN 0 ALIAS KAL ORDER 1
         USE &AKALG IN 0 ALIAS KALG ORDER 1
         SELECT KAL
         SET RELATION TO BRKAL INTO KALG
   
         USE &AFAK IN 0 ALIAS FAK ORDER 1
         USE &AFAKG IN 0 ALIAS FAKG ORDER 1
         SELECT FAK
         SET RELATION TO BRKAL INTO FAKG
         SELECT KAL
         GO TOP
         DO WHILE.NOT.EOF()
            MSIFRA=KALG.SIFRA
            SCATTER NAME POLJA
            IF kol>0
               SELECT KOCKA
               APPEND BLANK
               GATHER NAME POLJA
            endif               
            REPLACE SIFRA WITH MSIFRA
            SELECT KAL         
            MRSIF=RSIF
            MKOL=KOL
            SELECT KOCKA3
            APPEND BLANK
            IF mkol>0
               REPLACE ULAZ WITH MKOL
            ELSE
               replace izlaz WITH -mkol
            endif
            REPLACE RSIF WITH MRSIF
            SELECT KAL
            SKIP
         ENDDO   
         SELECT FAK
         GO TOP
         DO WHILE.NOT.EOF()
            SCATTER NAME POLJA
            SELECT KOCKA2
            APPEND BLANK
            GATHER NAME POLJA
            SELECT FAK      
            MRSIF=RSIF
            MKOLI=KOLI
            SELECT KOCKA3
            APPEND BLANK
            REPLACE IZLAZ WITH MKOLI
            REPLACE RSIF WITH MRSIF
            SELECT FAK
            SKIP
         ENDDO   
         SELECT KAL
         USE
         SELECT FAK
         USE
         SELECT KALG
         USE
        SELECT FAKG
        USE
     endif   
     SELECT aatv
     SKIP
enddo        
SELECT AATV
USE   
*---------------POKUPILI SMO SVE PODATKE---------------
SELECT KOCKA
INDEX ON RSIF+DTOS(DATDOK) TAG RSIF
SELECT KOCKA2
INDEX ON RSIF+DTOS(DATDOK) TAG RSIF
SELECT KOCKA3
INDEX ON RSIF TAG RSIF
DO IDEL WITH (KKOCKAX4)
SELECT KOCKA3
TOTAL ON RSIF TO &KKOCKA4 FIELDS ULAZ,IZLAZ
DELETE ALL
PACK
APPEND FROM &KKOCKA4
SELECT ROB
SET ORDER TO 2
GO TOP
DO WHILE.NOT.EOF()
   IF NAZ<>SPACE(30)
   IF SUBSTR(NAZ,1,1)<>'*'
      MRSIF=RSIF
      MNAZ=NAZ
      MGRUPA=GRUPA
      MBARKOD=BARKOD
      MPODRSIF=PODRSIF
      MVPKOL=ULAZ-IZLAZ
      IF ASVAROBA=1.OR.ASVAROBA=0
         SELECT ROBNARR
         APPEND BLANK
         REPLACE RSIF WITH MRSIF
         REPLACE NAZ WITH MNAZ
         REPLACE GRUPA WITH MGRUPA
         REPLACE VPKOL WITH MVPKOL
         REPLACE BARKOD WITH MBARKOD
         REPLACE PODRSIF WITH MPODRSIF
      ELSE
         IF PODRSIF=MMPODRSIF
            SELECT ROBNARR
            APPEND BLANK
            REPLACE RSIF WITH MRSIF
            REPLACE NAZ WITH MNAZ
            REPLACE GRUPA WITH MGRUPA
            REPLACE VPKOL WITH MVPKOL
            REPLACE BARKOD WITH MBARKOD
            REPLACE PODRSIF WITH MPODRSIF
         ENDIF
      ENDIF   

   SELECT KOCKA
   SET ORDER TO 1
   SEEK MRSIF
   MPRVIUL=DATE()    
   MZADUL=DATE()
   MZADIZ=DATE()
   MZADKOL=0
   MSIFRA=SPACE(5)
   IF FOUND()
      MPRVIUL=DATDOK
      MKOL=0
      DO WHILE.NOT.EOF()
         IF RSIF<>MRSIF
            EXIT
         ENDIF   
         MKOL=MKOL+KOL 
         MZADUL=DATDOK
         MZADKOL=KOL
         MSIFRA=SIFRA
         SKIP
      ENDDO   
      SELECT ROBNARR
      REPLACE ULAZ WITH MKOL     
      REPLACE SIFRA WITH MSIFRA
   ENDIF
   SELECT KOCKA2
   SET ORDER TO 1
   SEEK MRSIF
   IF FOUND()
      MKOL01=0
      MKOL02=0
      MKOL03=0
      MKOL04=0
      MKOL05=0
      MKOL06=0
      MKOL07=0
      MKOL08=0
      MKOL09=0
      MKOL10=0
      MKOL11=0
      MKOL12=0
      DO WHILE.NOT.EOF()
         IF RSIF<>MRSIF
            EXIT
         ENDIF   
         IF MONTH(DATDOK)=1
            MKOL01=MKOL01+KOLI
         ENDIF   
         IF MONTH(DATDOK)=2
            MKOL02=MKOL02+KOLI
         ENDIF   
         IF MONTH(DATDOK)=3
            MKOL03=MKOL03+KOLI
         ENDIF   
         IF MONTH(DATDOK)=4
           MKOL04=MKOL04+KOLI
         ENDIF   
         IF MONTH(DATDOK)=5
            MKOL05=MKOL05+KOLI
         ENDIF   
         IF MONTH(DATDOK)=6
            MKOL06=MKOL06+KOLI
         ENDIF   
         IF MONTH(DATDOK)=7
            MKOL07=MKOL07+KOLI
         ENDIF   
         IF MONTH(DATDOK)=8
            MKOL08=MKOL08+KOLI
         ENDIF   
         IF MONTH(DATDOK)=9
            MKOL09=MKOL09+KOLI
         ENDIF   
         IF MONTH(DATDOK)=10
            MKOL10=MKOL10+KOLI
         ENDIF   
         IF MONTH(DATDOK)=11
            MKOL11=MKOL11+KOLI
         ENDIF   
         IF MONTH(DATDOK)=12
            MKOL12=MKOL12+KOLI
         ENDIF   
         MZADIZ=DATDOK
         SELECT KOCKA2
         SKIP
      ENDDO
      SELECT ROBNARR
      REPLACE KOL01 WITH ROUND(MKOL01,0)
      REPLACE KOL02 WITH ROUND(MKOL02,0)
      REPLACE KOL03 WITH ROUND(MKOL03,0)
      REPLACE KOL04 WITH ROUND(MKOL04,0)
      REPLACE KOL05 WITH ROUND(MKOL05,0)
      REPLACE KOL06 WITH ROUND(MKOL06,0)
      REPLACE KOL07 WITH ROUND(MKOL07,0)
      REPLACE KOL08 WITH ROUND(MKOL08,0)
      REPLACE KOL09 WITH ROUND(MKOL09,0)
      REPLACE KOL10 WITH ROUND(MKOL10,0)
      REPLACE KOL11 WITH ROUND(MKOL11,0)
      REPLACE KOL12 WITH ROUND(MKOL12,0)
      REPLACE IZLAZ WITH KOL01+KOL02+KOL03+KOL04+KOL05+KOL06+KOL07+KOL08+KOL09+KOL10+KOL11+KOL12
   ENDIF
   SELECT ROBNARR
   REPLACE STANJE WITH ULAZ-IZLAZ
   REPLACE ZADUL WITH MZADUL
   REPLACE ZADIZ WITH MZADIZ
   REPLACE PRVIUL WITH MPRVIUL
   REPLACE ZADKOL WITH MZADKOL
   IF ZADIZ<>CTOD('').AND.ZADUL<>CTOD('')
      REPLACE DANAPROD WITH MZADIZ-MPRVIUL+1
   ENDIF
   IF DANAPROD<>0
      REPLACE MESECNO WITH ROUND((IZLAZ+STANJE)*30/DANAPROD,2)
   ENDIF   
   ENDIF
ENDIF
   SELECT ROB
   SKIP
ENDDO   

SELECT KOCKA
USE
SELECT KOCKA2
USE
SELECT KOCKA3
USE

USE &KKAL IN 0 ALIAS KAL
USE &KFAK IN 0 ALIAS FAK
USE &KKALG IN 0 ALIAS KALG ORDER 1
USE &KFAKG IN 0 ORDER 1 ALIAS FAKG
SELECT KAL
SET RELATION TO BRKAL INTO KALG  ADDITIVE
SELECT FAK
SET RELATION TO BRKAL INTO FAKG  ADDITIVE
SELECT ROBNARR
replace ALL stanje WITH ulaz-izlaz-vpkol
IF ASVAROBA=0
   DELETE ALL FOR ULAZ=0.AND.IZLAZ=0.AND.VPKOL=0
   PACK
ENDIF
SET ORDER TO 2
GO TOP
POP KEY
ROBNARP.Release
*KEYBOARD '{ENTER}'
