PARAMETERS AACENIME
PUSH KEY CLEAR

MCENIME=AACENIME
MDAT0=ROBNIV.TXTDAT0.VALUE
MDAT1=ROBNIV.TXTDAT1.VALUE
MSEMA=ROBNIV.TEXT2.VALUE
MNAL=ALLTRIM(ROBNIV.TEXT3.VALUE)

*SELECT DATUMI
*REPLACE DAT0 WITH MDAT0
*REPLACE DAT1 WITH MDAT1

TDAT0=MDAT0
TDAT1=MDAT1


   DO idel WITH (kkockax)   
   DO idel WITH (kkockax1)   
   DO idel WITH (kkockax2)   


SELECT NIV 
USE
USE &KTVNIV EXCLU IN 0 ALIAS NIV

SELECT NIV
DELETE ALL FOR DATDOK>=MDAT0.AND.DATDOK<=MDAT1
PACK

SET ORDER TO 2
IF RECCOUNT()>0
   GO BOTTOM
   MSBRNIV=BRKAL
   MLEN=LEN(ALLTRIM(STR(VAL( SUBSTR(MSBRNIV,2,5))+1,5,0)))
   MNOVI=ALLTRIM( STR( VAL( SUBSTR(MSBRNIV,2,5) )+1,5,0 ) )
   MNBRNIV='N'+REPLI('0',5-MLEN)+MNOVI
ELSE
   MNBRNIV='N00001'   
ENDIF   

COPY STRU TO &KKOCKA


USE &KKOCKA IN 0 ALIAS KOCKA EXCLUSIVE 
SELECT KOCKA

INDEX ON DTOS(DATDOK) TAG DATDOK


DO IDEL WITH  (KTVKARTX)

ON ERROR

USE  &KTVKART ALIAS TVKART EXCLU IN 0
SELECT TVKART
DELETE ALL
PACK

ON ERROR DO GRESKE WITH ;
   ERROR( ), MESSAGE( ), MESSAGE(1), PROGRAM( ), LINENO( )
INDEX ON RSIF+DTOS(DATDOK) TAG RDAT
SET ORDER TO 1
IF MCENIME<>''
   MMCENIME=ALLTRIM(MCENIME)+'.DBF'
   USE &MMCENIME IN 0 ALIAS CENEIME ORDER 1
ENDIF
SELECT ROB
SET ORDER TO 1
GO TOP

DO WHILE.NOT.EOF()
   MRSIF=RSIF
   IF vrsta<>'U'

   IF TOBJEKAT='V'
      MVELCENA=VELCENA
   ELSE
      MVELCENA=MALCENA
   ENDIF
   MTARIFA=TARIFA
   MPROCPOR=PROCPOR
   robniv.lblnaz.caption=rsif+' '+naz
   IF MCENIME<>''
      SELECT CENEIME
      SEEK MRSIF
      IF FOUND()

         M0KOL=KOL
         M2DATDOK=CENDAT
         IF TOBJEKAT='V'
            M2VELCENA=VELCENA
         ELSE
            M2VELCENA=MALCENA
         ENDIF
         SELECT TVKART      
         APPEND BLANK
         REPLACE RSIF WITH MRSIF
         REPLACE BRKAL WITH 'XXXXXX'
         REPLACE KOL WITH M0KOL
         REPLACE CENA WITH M2VELCENA
         REPLACE DATDOK WITH M2DATDOK
      ELSE
         SELECT TVKART
      ENDIF
   ENDIF
   *-----TRAZIMO ROBU U KALKULACIJAMA----   
   SELECT KAL
   SET ORDER TO 2
   SEEK MRSIF
   IF FOUND()
      DO WHILE.NOT.EOF()
         IF RSIF<>MRSIF
            EXIT
         ENDIF
         IF DATDOK>=MDAT0.AND.DATDOK<=MDAT1
            MDATDOK=DATDOK
            MBRKAL=BRKAL
            MKOL=KOL
            IF TOBJEKAT='V' 
               MCENA=VELCENA
            ELSE
               MCENA=MALCENA
            ENDIF
      
            SELECT TVKART
            APPEND BLANK
            REPLACE RSIF WITH MRSIF
            REPLACE BRKAL WITH MBRKAL
            REPLACE KOL WITH MKOL
            REPLACE CENA WITH MCENA
            REPLACE DATDOK WITH MDATDOK
            SELECT KAL
         ENDIF   
         SKIP
      ENDDO   
   ENDIF
   *-------KRAJ KALKULACIJA--------
    
   *-----TRAZIMO ROBU U RACUNIMA----   
   SELECT FAK
   SET ORDER TO 2
   SEEK MRSIF
   IF FOUND()
      DO WHILE.NOT.EOF()
         IF RSIF<>MRSIF
            EXIT
         ENDIF
         IF DATDOK>=MDAT0.AND.DATDOK<=MDAT1
            MDATDOK=DATDOK
            MBRKAL=BRKAL
            MKOLI=KOLI
            IF TOBJEKAT='V'
               MCENA=VELCENA
            ELSE
               MCENA=MALCENA
            ENDIF
      
            SELECT TVKART
            APPEND BLANK
            REPLACE RSIF WITH MRSIF
            REPLACE BRKAL WITH MBRKAL
            REPLACE KOLI WITH MKOLI
            REPLACE CENA WITH MCENA
            REPLACE DATDOK WITH MDATDOK
            SELECT FAK
         ENDIF   
         SKIP
      ENDDO   
   ENDIF

   *-------KRAJ KALKULACIJA--------
   *------POCINJEMO NIVELACIJE-----
   SELECT TVKART
   GO TOP
   MKOL=0
   DO WHILE.NOT.EOF()
      MKOL=MKOL+KOL-KOLI
      REPLACE KOLST WITH MKOL
      SKIP
   ENDDO   
   
   SELECT TVKART
   GO TOP
   DO WHILE.NOT.EOF()
      MKOL=KOLST
      MCENA=CENA
      SKIP
      MNCENA=CENA
      MDATNAB=DATDOK
      SKIP -1
      IF MCENA<>MNCENA.AND.MNCENA<>0
         REPLACE NIVKOL WITH MKOL
         REPLACE NIVCENA WITH MNCENA
         REPLACE DATNAB WITH MDATNAB
      ENDIF   
      SKIP
   ENDDO   
   GO BOTTOM
   MCENA=CENA
   MKOL=KOLST
   
*   MKOL=NIVKOL
   IF MCENA<>MVELCENA
      APPEND BLANK
      REPLACE RSIF WITH MRSIF
      REPLACE NIVKOL WITH MKOL
      REPLACE DATDOK WITH MDAT1
      REPLACE DATNAB WITH MDAT1
      REPLACE NIVCENA WITH MVELCENA
      REPLACE CENA WITH MCENA
   ENDIF   
   SELECT TVKART
   GO TOP
   DO WHILE.NOT.EOF()
      IF NIVCENA<>0.AND.NIVKOL<>0
         MSCENA=CENA
         MDATDOK=DATNAB
         MKOL=NIVKOL
         MVELCENA=NIVCENA
         MBRKAL=BRKAL
            SELECT KOCKA
            APPEND BLANK
            IF TOBJEKAT='V'
               REPLACE VELCENA WITH MVELCENA
            ELSE   
               REPLACE MALCENA WITH MVELCENA
            ENDIF
            REPLACE RSIF WITH MRSIF
            REPLACE SCENA WITH MSCENA
            REPLACE KOL WITH MKOL
            REPLACE DATDOK WITH MDATDOK
            REPLACE TARIFA WITH MTARIFA
            REPLACE PROCPOR WITH MPROCPOR
            REPLACE STARIFA WITH MTARIFA
            REPLACE SPROCPOR WITH MPROCPOR
            REPLACE BRKAL WITH MBRKAL
      SELECT TVKART
      ENDIF
      SKIP
   ENDDO   
   SELECT TVKART
   DELETE ALL
   PACK
   *------KRAJ NIVELACIJA-----------
   ENDIF
   SELECT ROB
   SKIP
ENDDO   

   IF MCENIME<>''
      SELECT CENEIME
      USE
   ENDIF   

SELECT TVKART
USE
robniv.lblnaz.caption='ZAVRSILI SMO PRIKUPLJANJE NIVELACIJA--RADIMO SALDO '
********'ZAVRSILI SMO PRIKUPLJANJE NIVELACIJA--RADIMO SALDO '
SELECT KOCKA
TOTAL ON DTOS(DATDOK) TO &KKOCKA1 

USE &KKOCKA1 IN 0 ALIAS KOCKA1 EXCLU
SELECT KOCKA1
GO TOP
*------UPISUJEMO BROJEVE NIVELACIJA--------
DO WHILE.NOT.EOF()
   MDATDOK=DATDOK
   MNBRKAL=MNBRNIV
   REPLACE BRKAL WITH MNBRKAL
   MLEN=LEN(ALLTRIM(STR(VAL( SUBSTR(BRKAL,2,5))+1,5,0)))
   MNOVI=ALLTRIM( STR( VAL( SUBSTR(BRKAL,2,5) )+1,5,0 ) )
   MNBRNIV='N'+REPLI('0',5-MLEN)+MNOVI
   SELECT KOCKA
   SEEK DTOS(MDATDOK)
   IF FOUND()
      DO WHILE.NOT.EOF()       
         IF DTOS(DATDOK)<>DTOS(MDATDOK)
            EXIT
         ENDIF
         REPLACE BRKAL WITH MNBRKAL
         REPLACE SEMA WITH MSEMA
         IF LEN(ALLTRIM(mnal))=2
            REPLACE BRNAL WITH MNAL+SUBSTR(BRKAL,3,4)
         ELSE
            REPLACE BRNAL WITH MNAL+SUBSTR(BRKAL,4,3)
         endif   
         DO NIVRAC
         SKIP   
      ENDDO      
   ENDIF
   SELECT KOCKA1
   SKIP
ENDDO    

SELECT KOCKA
SORT ON BRKAL,DATDOK TO &KKOCKA2
DELETE ALL
PACK

APPEND FROM &KKOCKA2
USE
SELECT KOCKA1
USE
SELECT NIV
APPEND FROM &KKOCKA
SELECT NIV 
USE
USE &KTVNIV IN 0 ALIAS NIV
SELECT NIV
SET ORDER TO
SELECT ROB
SET ORDER TO 2
GO TOP
ROBNIV.RELEASE
POP KEY