PUSH KEY CLEAR
DO IDEL WITH (KKOCKAX)
DO IDEL WITH (KKOCKAX2)
DO IDEL WITH (KKOCKAX3)
DO IDEL WITH (KKOCKAX4)

SELECT KAL 
COPY STRUCTURE TO &KKOCKA
SELECT FAK
COPY STRUCTURE TO &KKOCKA2
SELECT ROB
COPY STRUCTURE TO &KKOCKA3
USE AATV IN 0
SELECT AATV
MREC=RECCOUNT()
USE
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
USE &KKOCKA2 IN 0 ALIAS KOCKA2 EXCLU
USE &KKOCKA3 IN 0 ALIAS KOCKA3 EXCLU
SELECT KAL
USE
SELECT KALG
USE
SELECT FAK
USE
SELECT FAKG
USE

FOR I=1 TO MREC
   AKAL='KAL'+ALLTRIM(STR(I,2,0))+'.DBF'
   AKALG='KALG'+ALLTRIM(STR(I,2,0))+'.DBF'
   AFAK='FAK'+ALLTRIM(STR(I,2,0))+'.DBF'
   AFAKG='FAKG'+ALLTRIM(STR(I,2,0))+'.DBF'
   USE &AKAL IN 0 ALIAS KAL ORDER 1
   USE &AKALG IN 0 ALIAS KALG ORDER 1
   SELECT KAL
   SET RELATION TO BRKAL INTO KALG
   
   USE &AFAK IN 0 ALIAS FAK ORDER 1
   USE &AFAKG IN 0 ALIAS FAKG ORDER 1
   SELECT FAK
   SET RELATION TO BRKAL INTO FAKG
   SELECT KAL
   GO TOP
   DO WHILE.NOT.EOF()
         MSIFRA=KALG.SIFRA
         SCATTER NAME POLJA
         SELECT KOCKA
         APPEND BLANK
         GATHER NAME POLJA
         REPLACE SIFRA WITH MSIFRA
         SELECT KAL         
      MRSIF=RSIF
      MKOL=KOL
      SELECT KOCKA3
      APPEND BLANK
      REPLACE ULAZ WITH MKOL
      REPLACE RSIF WITH MRSIF
      SELECT KAL
      SKIP
   ENDDO   
   SELECT FAK
   GO TOP
   DO WHILE.NOT.EOF()
         SCATTER NAME POLJA
         SELECT KOCKA2
         APPEND BLANK
         GATHER NAME POLJA
         SELECT FAK      
      MRSIF=RSIF
      MKOLI=KOLI
      SELECT KOCKA3
      APPEND BLANK
      REPLACE IZLAZ WITH MKOLI
      REPLACE RSIF WITH MRSIF
      SELECT FAK
      SKIP
   ENDDO   
   SELECT KAL
   USE
   SELECT FAK
   USE
   SELECT KALG
   USE
   SELECT FAKG
   USE
NEXT

USE AATM IN 0
SELECT AATM
MREC=RECCOUNT()
USE

FOR I=1 TO MREC
   AKAL='TMKAL'+ALLTRIM(STR(I,2,0))+'.DBF'
   AKALG='TMKALG'+ALLTRIM(STR(I,2,0))+'.DBF'
   AFAK='TMFAK'+ALLTRIM(STR(I,2,0))+'.DBF'
   AFAKG='TMFAKG'+ALLTRIM(STR(I,2,0))+'.DBF'
   USE &AKAL IN 0 ALIAS KAL ORDER 1
   USE &AKALG IN 0 ALIAS KALG ORDER 1
   SELECT KAL
   SET RELATION TO BRKAL INTO KALG
   
   USE &AFAK IN 0 ALIAS FAK ORDER 1
   USE &AFAKG IN 0 ALIAS FAKG ORDER 1
   SELECT FAK
   SET RELATION TO BRKAL INTO FAKG
   SELECT KAL
   GO TOP
   DO WHILE.NOT.EOF()
      IF DATDOK=TDAT0
         SCATTER NAME POLJA
         SELECT KOCKA
         APPEND BLANK
         GATHER NAME POLJA
         SELECT KAL         
      ENDIF
      SKIP
   ENDDO   
   SELECT FAK
   GO TOP
   DO WHILE.NOT.EOF()
      IF DATDOK=TDAT0
         SCATTER NAME POLJA
         SELECT KOCKA2
         APPEND BLANK
         GATHER NAME POLJA
         SELECT FAK      
      ENDIF
      SKIP
   ENDDO   
   SELECT KAL
   USE
   SELECT FAK
   USE
   SELECT KALG
   USE
   SELECT FAKG
   USE
NEXT

*---------------POKUPILI SMO SVE PODATKE---------------
SELECT KOCKA
INDEX ON RSIF+DTOS(DATDOK) TAG RSIF
SELECT KOCKA2
INDEX ON RSIF+DTOS(DATDOK) TAG RSIF
SELECT KOCKA3
INDEX ON RSIF TAG RSIF
DO IDEL WITH (KKOCKAX4)
SELECT KOCKA3
TOTAL ON RSIF TO &KKOCKA4 FIELDS ULAZ,IZLAZ
DELETE ALL
PACK

APPEND FROM &KKOCKA4

SELECT ROB
SET ORDER TO 2
GO TOP
DO WHILE.NOT.EOF()
   MRSIF=RSIF
   MNAZ=NAZ
   MGRUPA=GRUPA
   MPODNAZIV=PODNAZIV
   MPODRSIF=PODRSIF
   SELECT KOCKA3
   SEEK MRSIF
   IF FOUND()
      MVPKOL=ULAZ-IZLAZ
   ELSE
      MVPKOL=0
   ENDIF      
   SELECT ROBNARR
   APPEND BLANK
   REPLACE RSIF WITH MRSIF
   REPLACE NAZ WITH MNAZ
   REPLACE GRUPA WITH MGRUPA
   REPLACE VPKOL WITH MVPKOL
   REPLACE PODNAZIV WITH MPODNAZIV
   REPLACE PODRSIF WITH MPODRSIF
   SELECT KOCKA
   SET ORDER TO 1
   SEEK MRSIF
   MPRVIUL=DATE()    
   MZADUL=DATE()
   MZADIZ=DATE()
   MZADKOL=0
   MSIFRA=SPACE(5)
   IF FOUND()
      MPRVIUL=DATDOK
      MKOL=0
      DO WHILE.NOT.EOF()
         IF RSIF<>MRSIF
            EXIT
         ENDIF   
         MKOL=MKOL+KOL 
         MZADUL=DATDOK
         MZADKOL=KOL
         MZADCENA=NABCENA
         MSIFRA=SIFRA
         SKIP
      ENDDO   
      SELECT ROBNARR
      REPLACE ULAZ WITH MKOL     
      REPLACE SIFRA WITH MSIFRA
      REPLACE ZADCENA WITH MZADCENA
   ENDIF
   SELECT KOCKA2
   SET ORDER TO 1
   SEEK MRSIF
   IF FOUND()
      MIZLAZ=0
      MZADIZ=CTOD('')
      DO WHILE.NOT.EOF()
         IF RSIF<>MRSIF
            EXIT
         ENDIF   
         MIZLAZ=MIZLAZ+KOLI
         MZADIZ=DATDOK
         SELECT KOCKA2
         SKIP
      ENDDO
      SELECT ROBNARR
      REPLACE IZLAZ WITH MIZLAZ
   ENDIF
   SELECT ROBNARR
   REPLACE STANJE WITH ULAZ-IZLAZ
   REPLACE ZADUL WITH MZADUL
   REPLACE ZADIZ WITH MZADIZ
   REPLACE PRVIUL WITH MPRVIUL
   REPLACE ZADKOL WITH MZADKOL
   IF ZADIZ<>CTOD('').AND.ZADUL<>CTOD('')
      REPLACE DANAPROD WITH MZADIZ-MPRVIUL+1
   ENDIF
   IF DANAPROD<>0
      REPLACE MESECNO WITH ROUND(IZLAZ*30/DANAPROD,2)
   ENDIF   
   SELECT ROB
   SKIP
ENDDO   
SELECT KOCKA
USE
SELECT KOCKA2
USE
SELECT KOCKA3
USE
USE &KKAL IN 0 ALIAS KAL
USE &KFAK IN 0 ALIAS FAK
USE &KKALG IN 0 ALIAS KALG ORDER 1
USE &KFAKG IN 0 ORDER 1 ALIAS FAKG
SELECT KAL
SET RELATION TO BRKAL INTO KALG  ADDITIVE
SELECT FAK
SET RELATION TO BRKAL INTO FAKG  ADDITIVE
SELECT ROBNARR
DELETE ALL FOR NAZ=SPACE(30)
PACK
SET ORDER TO 4
GO TOP
POP KEY
ROBNARP.Release
KEYBOARD '{ENTER}'
