PARAMETERS AGDE
PUSH KEY CLEAR
SELECT RONARI
SET ORDER TO 1
MGRUPA=GRUPA
IF AGDE=0
   *REPORT FORM RONARI02 PREVIEW FOR GRUPA=MGRUPA
   mfile='RONARI02'   
   USLOV="GRUPA=MGRUPA"
   DO printer_bullzip WITH mdata02,mfiLE,USLOV
   
ELSE
   *REPORT FORM RONARI02 PREVIEW 
   mfile='RONARI02'   
   USLOV=""
   DO printer_bullzip WITH mdata02,mfiLE,USLOV
ENDIF
POP KEY
