PUSH KEY CLEAR
SELECT ROB
SET ORDER TO 1
SELECT ROBNARR
SET ORDER TO 2
GO TOP
DO IDEL WITH (KKOCKAX)
DO IDEL WITH (KKOCKAX2)
COPY TO &kkocka FOR NARUCITI<>0.AND.VPKOL>0
USE &kkocka IN 0 ALIAS kocka EXCLUSIVE
SELECT kocka
VPFAK='FAK1'
VPFAKG='FAKG1'
USE &VPFAK IN 0 ALIAS VFAK ORDER 1
USE &VPFAKG IN 0 ALIAS VFAKG ORDER 1
USE ROB IN 0 ALIAS ROBA ORDER 1
   MSIFRA='    1'
   SELECT VFAKG
   GO BOTTOM
   MNKAL=BRKAL
   IF RECCOUNT()>0
      GO BOTTOM
      MNOVI=VAL(BRKAL)+1
      MLEN=LEN(ALLTRIM(STR(MNOVI,6,0)))
      MNBRKAL=REPLICATE('0',6-MLEN)+ALLTRIM(STR(MNOVI,6,0))
   ELSE
      MNBRKAL='000001'
   ENDIF      
   SELECT VFAKG
   APPEND BLANK
   REPLACE BRKAL WITH MNBRKAL
   REPLACE DATDOK WITH DATE()
   REPLACE PORDAT WITH DATE()
   REPLACE OTPDAT WITH DATE()
   REPLACE VALUTA WITH DATE()
   REPLACE SIFRA WITH MSIFRA
   REPLACE FVRSTA WITH '  6'
   USE
SELECT KOCKA
GO TOP
DO WHILE.NOT.EOF()
   MRSIF=RSIF
   MKOLI=NARUCITI
   IF NARUCITI<=VPKOL
      MKOLI=NARUCITI
   ELSE
      MKOLI=VPKOL
   ENDIF   
   SELECT ROBA
   SEEK MRSIF
   IF FOUND()
      MPROSCENV=PROSCENV
      MVELCENA=VELCENA
      REPLACE KOL WITH KOL-MKOLI
      REPLACE IZLAZ WITH IZLAZ+MKOLI  
      SELECT ROBA
   ELSE
      MPROSCENV=1
      MVELCENA=1
   ENDIF      
   
   SELECT VFAK
   APPEND BLANK
   REPLACE BRKAL WITH MNBRKAL
   REPLACE RSIF WITH MRSIF
   REPLACE KOLI WITH MKOLI
   REPLACE VELCENA WITH MVELCENA
   REPLACE CENA WITH MPROSCENV
   SELECT KOCKA
   SKIP
ENDDO   
SELECT KOCKA
USE
SELECT VFAK
USE
SELECT ROBA
USE
SELECT ROBNARR
GO TOP
POP KEY
ROBNARR.Release
KEYBOARD '{ENTER}'
