PUSH KEY CLEAR
SELECT ROB
SET ORDER TO 2
GO TOP
DO WHILE.NOT.EOF()
   MRSIF=RSIF
   MNAZ=NAZ
   MGRUPA=GRUPA
   MSIFRA=SIFRA
   SELECT ROBNARR
   APPEND BLANK
   REPLACE RSIF WITH MRSIF
   REPLACE NAZ WITH MNAZ
   REPLACE GRUPA WITH MGRUPA
   REPLACE SIFRA WITH MSIFRA
   SELECT KAL
   SET ORDER TO 2
   SEEK MRSIF
   MPRVIUL=DATE()    
   MZADUL=DATE()
   MZADIZ=DATE()
   MZADKOL=0
   IF FOUND()
      MPRVIUL=DATDOK
      MKOL=0
      DO WHILE.NOT.EOF()
         IF RSIF<>MRSIF
            EXIT
         ENDIF   
         MKOL=MKOL+KOL 
         MZADUL=DATDOK
         MZADKOL=KOL
         SKIP
      ENDDO   
      SELECT ROBNARR
      REPLACE ULAZ WITH MKOL     
   ENDIF
   SELECT FAK
   SET ORDER TO 2
   SEEK MRSIF
   IF FOUND()
      MKOL01=0
      MKOL02=0
      MKOL03=0
      MKOL04=0
      MKOL05=0
      MKOL06=0
      MKOL07=0
      MKOL08=0
      MKOL09=0
      MKOL10=0
      MKOL11=0
      MKOL12=0
      DO WHILE.NOT.EOF()
         IF RSIF<>MRSIF
            EXIT
         ENDIF   
         IF MONTH(DATDOK)=1
            MKOL01=MKOL01+KOLI
         ENDIF   
         IF MONTH(DATDOK)=2
            MKOL02=MKOL02+KOLI
         ENDIF   
         IF MONTH(DATDOK)=3
            MKOL03=MKOL03+KOLI
         ENDIF   
         IF MONTH(DATDOK)=4
           MKOL04=MKOL04+KOLI
         ENDIF   
         IF MONTH(DATDOK)=5
            MKOL05=MKOL05+KOLI
         ENDIF   
         IF MONTH(DATDOK)=6
            MKOL06=MKOL06+KOLI
         ENDIF   
         IF MONTH(DATDOK)=7
            MKOL07=MKOL07+KOLI
         ENDIF   
         IF MONTH(DATDOK)=8
            MKOL08=MKOL08+KOLI
         ENDIF   
         IF MONTH(DATDOK)=9
            MKOL09=MKOL09+KOLI
         ENDIF   
         IF MONTH(DATDOK)=10
            MKOL10=MKOL10+KOLI
         ENDIF   
         IF MONTH(DATDOK)=11
            MKOL11=MKOL11+KOLI
         ENDIF   
         IF MONTH(DATDOK)=12
            MKOL12=MKOL12+KOLI
         ENDIF   
         MZADIZ=DATDOK
         SELECT FAK
         SKIP
      ENDDO
      SELECT ROBNARR
      REPLACE KOL01 WITH ROUND(MKOL01,0)
      REPLACE KOL02 WITH ROUND(MKOL02,0)
      REPLACE KOL03 WITH ROUND(MKOL03,0)
      REPLACE KOL04 WITH ROUND(MKOL04,0)
      REPLACE KOL05 WITH ROUND(MKOL05,0)
      REPLACE KOL06 WITH ROUND(MKOL06,0)
      REPLACE KOL07 WITH ROUND(MKOL07,0)
      REPLACE KOL08 WITH ROUND(MKOL08,0)
      REPLACE KOL09 WITH ROUND(MKOL09,0)
      REPLACE KOL10 WITH ROUND(MKOL10,0)
      REPLACE KOL11 WITH ROUND(MKOL11,0)
      REPLACE KOL12 WITH ROUND(MKOL12,0)
      REPLACE IZLAZ WITH KOL01+KOL02+KOL03+KOL04+KOL05+KOL06+KOL07+KOL08+KOL09+KOL10+KOL11+KOL12
   ENDIF
   SELECT ROBNARR
   REPLACE STANJE WITH ULAZ-IZLAZ
   REPLACE ZADUL WITH MZADUL
   REPLACE ZADIZ WITH MZADIZ
   REPLACE PRVIUL WITH MPRVIUL
   REPLACE ZADKOL WITH MZADKOL
   IF ZADIZ<>CTOD('').AND.ZADUL<>CTOD('')
      REPLACE DANAPROD WITH MZADIZ-MPRVIUL+1
   ENDIF
   IF DANAPROD<>0
      REPLACE MESECNO WITH ROUND(IZLAZ*30/DANAPROD,2)
   ENDIF   
   SELECT ROB
   SKIP
ENDDO   
SELECT ROBNARR
GO TOP
DELETE ALL FOR ULAZ=0.AND.IZLAZ=0
PACK
SET ORDER TO 2
GO TOP
POP KEY
ROBNARR.Release
KEYBOARD '{ENTER}'
