MGRUPA=GRUPA
SET ORDER TO 3
GO TOP
SEEK MGRUPA
DO WHILE.NOT.EOF()
   IF GRUPA<>MGRUPA
      EXIT
   ENDIF   
   MNARUCITI=IZLAZ
   REPLACE NARUCITI WITH MNARUCITI 
   SKIP
ENDDO   
SET ORDER TO 2
ROBNARR.GRD0.SETFOCUS