GO TOP
DO WHILE.NOT.EOF()
   IF VPKOL<>0
      IF IZLAZ>VPKOL
         MNARUCITI=VPKOL
      ELSE
         MNARUCITI=IZLAZ
      ENDIF
      REPLACE NARUCITI WITH MNARUCITI 
   ENDIF
   SKIP
ENDDO   