MGRUPA=GRUPA
SET ORDER TO 4
SEEK MGRUPA
IF FOUND()
DO WHILE.NOT.EOF()
   IF GRUPA<>MGRUPA
      EXIT
   ENDIF  
   IF IZLAZ<>0
      MNARUCITI=IZLAZ
      REPLACE NARUCITI WITH MNARUCITI 
   ENDIF
   SKIP
ENDDO   
ENDIF
SET ORDER TO 2
robnarpnarucivanje.release