PUSH KEY CLEAR
SELECT ROBNARR
MRSIF=RSIF
ROBNARP.COMMAND9.SETFOCUS
DO IDEL WITH  (KTVKARTX)
ON ERROR
USE  &KTVKART ALIAS TVKART EXCLU IN 0
SELECT TVKART
DELETE ALL
PACK

ON ERROR DO GRESKE WITH ;
   ERROR( ), MESSAGE( ), MESSAGE(1), PROGRAM( ), LINENO( )
INDEX ON DTOS(DATDOK) TAG DATDOK
SET ORDER TO 1
SET EXACT OFF
*---------UZIMAMO ROBU IZ KALKULACIJA------------
SELECT KAL
SET ORDER TO 2
SEEK MRSIF
DO WHILE.NOT.EOF()
   IF RSIF<>MRSIF
      EXIT
   ENDIF
   ADATDOK=DATDOK
   Abrkal=brkal
   AKOL=KOL
   AKOLI=0
   AKOLST=0
   ACENA=VELCENA
   ADUG=VELVRED
   APOT=0
   ASALDO=0
   ANCENA=NABCENA
   ANDUG=NABVRED
   ANPOT=0
   ANSALDO=0
   ASIFRA=KALG.SIFRA                       
   SELECT TVKART
   APPEND BLANK 
   REPLACE RSIF WITH MRSIF
   REPLACE DATDOK WITH ADATDOK
   REPLACE BRKAL WITH ABRKAL  
   REPLACE KOL WITH AKOL
   REPLACE KOLI WITH AKOLI
   REPLACE KOLST WITH AKOLST
   REPLACE CENA WITH ACENA
   REPLACE DUG WITH ADUG
   REPLACE POT WITH APOT
   REPLACE SALDO WITH ASALDO
   REPLACE NCENA WITH ANCENA
   REPLACE NDUG WITH ANDUG
   REPLACE NPOT WITH ANPOT
   REPLACE NSALDO WITH ANSALDO
   REPLACE SIFRA WITH ASIFRA
   SELECT KAL
   SKIP
ENDDO   
*---------UZIMAMO ROBU IZ NIVELACIJA------------
SELECT NIV
SET ORDER TO 2
SEEK MRSIF
DO WHILE.NOT.EOF()
   IF RSIF<>MRSIF
      EXIT
   ENDIF
   ADATDOK=DATDOK
   Ambrkal=brkal
   ACENA=VELCENA
   ADUG=VELVRED
   ASCENA=SCENA
   ASDUG=-SIZNOS
   AKOL=KOL
   SELECT TVKART
   APPEND BLANK 
   REPLACE BRKAL WITH AMBRKAL
   REPLACE RSIF WITH MRSIF
   REPLACE DATDOK WITH ADATDOK
   REPLACE DUG WITH ASDUG
   REPLACE CENA WITH ASCENA
   REPLACE KOL WITH -AKOL
   REPLACE GLAVNA WITH 'N'
   APPEND BLANK 
   REPLACE BRKAL WITH AMBRKAL
   REPLACE RSIF WITH MRSIF
   REPLACE DATDOK WITH ADATDOK
   REPLACE DUG WITH ADUG
   REPLACE CENA WITH ACENA
   REPLACE KOL WITH AKOL
   REPLACE GLAVNA WITH 'N'
   SELECT NIV
   SKIP
ENDDO   
SELECT FAK
SET ORDER TO 2
SEEK MRSIF
DO WHILE.NOT.EOF()
   IF RSIF<>MRSIF
      EXIT
   ENDIF
   ADATDOK=DATDOK
   Abrkal=brkal
   AKOLI=KOLI
   ACENA=VELCENA
   APOT=VELVRED
   ASIFRA=FAKG.SIFRA                       
   SELECT TVKART
   APPEND BLANK 
   REPLACE RSIF WITH MRSIF
   REPLACE DATDOK WITH ADATDOK
   REPLACE BRKAL WITH ABRKAL  
   REPLACE KOLI WITH AKOLI
   REPLACE CENA WITH ACENA
   REPLACE POT WITH APOT
   REPLACE SIFRA WITH ASIFRA
   SELECT FAK
   SKIP
ENDDO   
SELECT KALG
SET RELATION TO
SELECT FAKG
SET RELATION TO
SELECT KAL
SET ORDER TO 1
SET RELATION TO
SELECT FAK
SET ORDER TO 1
SET RELATION TO
SELECT NIV
SET ORDER TO 1
SET RELATION TO
*-----------UZELI SMO SVE PODATKE PRAVIMO PROSECNE CENE------
SELECT AN0
SET ORDER TO 1
SELECT ROB
SET ORDER TO 1
select TVKART
go top
MKOL=0
MKOLI=0
MDUG=0
MPOT=0
MNDUG=0
MNPOT=0
DO WHILE.NOT.EOF()
   MKOL=MKOL+KOL
   MKOLI=MKOLI+KOLI
   REPLACE KOLST WITH MKOL-MKOLI
   MDUG=MDUG+DUG
   MPOT=MPOT+POT
   REPLACE SALDO WITH MDUG-MPOT
 
   MNDUG=MNDUG+NDUG
   REPLACE NSALDO WITH MNDUG-MNPOT
   
   IF KOLI<>0 
      IF (KOLST+KOLI)<>0
         MNCENA=NSALDO/(KOLST+KOLI)
      ELSE
         MNCENA=0
      ENDIF
      REPLACE NCENA WITH MNCENA
      REPLACE NPOT WITH MNCENA*KOLI
      MNPOT=MNPOT+NPOT
      REPLACE NSALDO WITH MNDUG-MNPOT
   ENDIF
   SKIP
ENDDO   
GO TOP
SET EXACT ON
SET RELATION TO SIFRA INTO AN0 ADDITIVE
SET RELATION TO RSIF INTO ROB ADDITIVE
*REPORT FORM TVKARTPRN PREVIEW
   mfile='TVKARTPRN'   
   USLOV=""
   DO printer_bullzip WITH mdata02,mfiLE,USLOV


select TVKART
use
select KAL
SET RELATION TO BRKAL INTO KALG  ADDITIVE
*SET RELATION TO RSIF INTO ROB ADDITIVE
SELECT KALG
SET RELATION TO
*SET RELATION TO SIFRA INTO AN0 ADDITIVE
select FAK
SET RELATION TO BRKAL INTO FAKG  ADDITIVE
*SET RELATION TO RSIF INTO ROB ADDITIVE
SELECT FAKG
SET RELATION TO
*SET RELATION TO SIFRA INTO AN0 ADDITIVE
SELECT ROBNARR
SET ORDER TO 1
SEEK MRSIF
SET ORDER TO 2
ROBNARP.GRD0.SETFOCUS
POP KEY