PUSH KEY CLEAR
ROBNARI.LBLNAPREDAK.VISIBLE=.T.
DO IDEL WITH (KKOCKAX)
DO IDEL WITH (KKOCKAX2)
DO IDEL WITH (KKOCKAX3)
DO IDEL WITH (KKOCKAX4)

SELECT KAL 
COPY STRUCTURE TO &KKOCKA
SELECT FAK
COPY STRUCTURE TO &KKOCKA2
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
USE &KKOCKA2 IN 0 ALIAS KOCKA2 EXCLU

   SELECT KAL
   MREC=RECCOUNT()
   SET ORDER TO 
   GO TOP
   DO WHILE.NOT.EOF()
      IF KALG.PRENOS=' '
         MSIFRA=KALG.SIFRA
      ELSE
         MSIFRA=' '
      ENDIF
      SCATTER NAME POLJA
      SELECT KOCKA
      APPEND BLANK
      GATHER NAME POLJA
      REPLACE SIFRA WITH MSIFRA
      SELECT KAL         
      ROBNARI.LBLNAPREDAK.CAPTION='KALKULACIJE '+TRANSFORM(MREC,'999999')+'-'+TRANSFORM(RECNO(),'999999')+'-'+TRANSFORM(MREC-RECNO(),'999999')
      SKIP
   ENDDO   
   SELECT FAK
   MREC=RECCOUNT()
   SET ORDER TO 
   GO TOP
   DO WHILE.NOT.EOF()
      SCATTER NAME POLJA
      SELECT KOCKA2
      APPEND BLANK
      GATHER NAME POLJA
      SELECT FAK
      ROBNARI.LBLNAPREDAK.CAPTION='FAKTURE '+TRANSFORM(MREC,'999999')+'-'+TRANSFORM(RECNO(),'999999')+'-'+TRANSFORM(MREC-RECNO(),'999999')
      SKIP
   ENDDO   

*---------------POKUPILI SMO SVE PODATKE---------------
ROBNARI.LBLNAPREDAK.CAPTION='INDEKSIRAMO'
SELECT KOCKA
INDEX ON RSIF+DTOS(DATDOK) TAG RSIF
SET ORDER TO 1
SELECT KOCKA2
INDEX ON RSIF+DTOS(DATDOK) TAG RSIF
SET ORDER TO 1
SELECT ROB
MREC=RECCOUNT()
SET ORDER TO 1
GO TOP
DO WHILE.NOT.EOF()
   MRSIF=RSIF
   MNAZ=NAZ
   MGRUPA=GRUPA
   MPODNAZIV=PODNAZIV
   SELECT RONARI
   APPEND BLANK
   REPLACE RSIF WITH MRSIF
   REPLACE NAZ WITH MNAZ
   REPLACE GRUPA WITH MGRUPA
   REPLACE PODNAZIV WITH MPODNAZIV 
   MZADIZ=CTOD('')
   mnabvredI=0
   mvelvred=0
   MFAKTURNA=0
   MNABVRED=0
   SELECT KOCKA2
   SEEK MRSIF
   IF FOUND()
      DO WHILE.NOT.EOF()
         IF RSIF<>MRSIF
            EXIT
         ENDIF
         MZADIZ=DATDOK
         mFAKTURNA=mFAKTURNA+velvred-rabat-rabat2
         mvelvred=mvelvred+velvred
         MNABVREDI=MNABVREDI+IZNI
         SKIP
      ENDDO      
   ENDIF
   SELECT RONARI
   REPLACE ZADIZ WITH MZADIZ
   replace vrediz with mNABVREDI
   REPLACE FAKTURNA WITH MFAKTURNA
   REPLACE VREDIZP WITH MVELVRED
   SELECT KOCKA
   SEEK MRSIF
   MPRVIUL=DATE()    
   MZADUL=CTOD('')
   MZADKOL=0
   MSIFRA=SPACE(5)
   MZADCENA=0
   MVREDULP=0
   IF FOUND()
      MPRVIUL=DATDOK
      MKOL=0
      DO WHILE.NOT.EOF()
         IF RSIF<>MRSIF
            EXIT
         ENDIF   
         MKOL=MKOL+KOL 
         mnabvred=mnabvred+nabvred 
         MVREDULP=MVREDULP+VELVRED
         IF KOL>0          
            MZADUL=DATDOK
            MZADKOL=KOL
            MSIFRA=SIFRA
            MZADCENA=NABCENA
         ENDIF
         SKIP
      ENDDO   
      SELECT RONARI
      REPLACE ULAZ WITH MKOL     
      REPLACE SIFRA WITH MSIFRA
      REPLACE ZADCENA WITH MZADCENA
      replace vredul WITH mnabvred
      REPLACE VREDULP WITH MVREDULP
   ENDIF
   MIZLAZ=0
   SELECT KOCKA2
   SEEK MRSIF
   IF FOUND()
      DO WHILE.NOT.EOF()
         IF RSIF<>MRSIF
            EXIT
         ENDIF   
         MIZLAZ=MIZLAZ+KOLI
         SKIP
      ENDDO   
   ENDIF
   SELECT RONARI
   REPLACE IZLAZ WITH MIZLAZ
   REPLACE STANJE WITH ULAZ-IZLAZ
   REPLACE ZADUL WITH MZADUL
*   REPLACE ZADIZ WITH MZADIZ
   REPLACE PRVIUL WITH MPRVIUL
   REPLACE ZADKOL WITH MZADKOL
   IF ZADIZ<>CTOD('').AND.ZADUL<>CTOD('')
      REPLACE DANAPROD WITH MZADIZ-MPRVIUL+1
   ENDIF
   IF DANAPROD<>0
      REPLACE KOL15 WITH ROUND(IZLAZ*15/DANAPROD,2)
      REPLACE KOL30 WITH ROUND(IZLAZ*30/DANAPROD,2)
      REPLACE KOL60 WITH ROUND(IZLAZ*60/DANAPROD,2)
   ENDIF   
   SELECT ROB
   ROBNARI.LBLNAPREDAK.CAPTION='IDEMO KROZ ROBU '+TRANSFORM(MREC,'999999')+'-'+TRANSFORM(RECNO(),'999999')+'-'+TRANSFORM(MREC-RECNO(),'999999')
   SKIP
ENDDO   
SELECT KOCKA
USE
SELECT KOCKA2
USE
SELECT RONARI
ROBNARI.LBLNAPREDAK.CAPTION='BRISANJE PRAZNINA '
DELETE ALL FOR NAZ=SPACE(30)
PACK
SET ORDER TO 1
GO TOP
POP KEY
