PUSH KEY CLEAR
SELECT ROBNARR
SET ORDER TO 4
MGRUPA=GRUPA
*REPORT FORM ROBNARP01 PREVIEW FOR GRUPA=MGRUPA.And.naruciti<>0
   mfile='ROBNARP01'   
   USLOV="GRUPA=MGRUPA.And.naruciti<>0"
   DO printer_bullzip WITH mdata02,mfiLE,USLOV


SET ORDER TO 2
POP KEY