PUSH KEY CLEAR
SELECT ROBNARR
MRSIF=RSIF
DO IDEL WITH  (KTVKARTX)
ON ERROR
USE  &KTVKART ALIAS TVKART EXCLU IN 0
SELECT TVKART
DELETE ALL
PACK

ON ERROR DO GRESKE WITH ;
   ERROR( ), MESSAGE( ), MESSAGE(1), PROGRAM( ), LINENO( )

INDEX ON DTOS(DATDOK) TAG DATDOK
SET ORDER TO 1
SET EXACT OFF
*---------UZIMAMO ROBU IZ KALKULACIJA------------
SELECT KAL
SET ORDER TO 2
SEEK MRSIF
DO WHILE.NOT.EOF()
   IF RSIF<>MRSIF
      EXIT
   ENDIF
   ADATDOK=DATDOK
   Abrkal=brkal
   AKOL=KOL
   ACENA=NABCENA
   ADUG=NABVRED
   SELECT TVKART
   APPEND BLANK 
   REPLACE RSIF WITH MRSIF
   REPLACE DATDOK WITH ADATDOK
   REPLACE BRKAL WITH ABRKAL  
   REPLACE KOL WITH AKOL
   REPLACE CENA WITH ACENA
   REPLACE DUG WITH ADUG
   SELECT KAL
   SKIP
ENDDO   
*---------UZIMAMO ROBU IZ RACUNA------------
SELECT FAK
SET ORDER TO 2
SEEK MRSIF
DO WHILE.NOT.EOF()
   IF RSIF<>MRSIF
      EXIT
   ENDIF
   ADATDOK=DATDOK
   Abrkal=brkal
   AKOLI=KOLI
   AMARZA=MARZA
   IF TOBJEKAT='V'
      ACENA=VELCENA
      APOT=VELVRED
   ELSE
      Acena=malcena-ROUND(MALCENA*PROCPOR/100,2)
      APOT=ACENA*KOLI
   endif
   SELECT TVKART
   APPEND BLANK 
   REPLACE RSIF WITH MRSIF
   REPLACE DATDOK WITH ADATDOK
   REPLACE BRKAL WITH ABRKAL  
   REPLACE KOLI WITH AKOLI
   REPLACE CENA WITH ACENA
   REPLACE POT WITH APOT
   REPLACE SALDO WITH AMARZA
   SELECT FAK
   SKIP
ENDDO   
SELECT ROB
SET ORDER TO 1
SELECT TVKART
GO TOP
MKOLST=0
DO WHILE.NOT.EOF()
   MKOLST=MKOLST+KOL-KOLI
   REPLACE KOLST WITH MKOLST    
   SKIP
ENDDO   
SET EXACT ON
SET RELATION TO SIFRA INTO AN0 ADDITIVE
SET RELATION TO RSIF INTO ROB ADDITIVE
*REPORT FORM ROBNARRKART PREVIEW
   mfile='ROBNARRKART'   
   USLOV=""
   DO printer_bullzip WITH mdata02,mfiLE,USLOV


SELECT TVKART
SET RELATION TO
USE
SELECT ROB
SET ORDER TO 2
SELECT ROBNARR
SET ORDER TO 1
SEEK MRSIF
SET ORDER TO 
ROBNARR.GRD0.SETFOCUS
POP KEY