PARAMETERS AGDE
PUSH KEY CLEAR
SELECT RONARI
SET ORDER TO 1
MGRUPA=GRUPA
IF AGDE=0
   *REPORT FORM RONARI0 PREVIEW FOR GRUPA=MGRUPA.And.naruciti<>0
   mfile='RONARI0'   
   USLOV="GRUPA=MGRUPA.And.naruciti<>0"
   DO printer_bullzip WITH mdata02,mfiLE,USLOV
   
ELSE
   *REPORT FORM RONARI0 PREVIEW FOR NARUCITI<>0
   mfile='RONARI0'   
   USLOV="NARUCITI<>0"
   DO printer_bullzip WITH mdata02,mfiLE,USLOV
   
ENDIF
POP KEY
