PARAMETERS AGDE
PUSH KEY CLEAR
MGRUPA1=ROBPOPIS.TXTGRUPA1.VALUE
MGRUPA2=ROBPOPIS.TXTGRUPA2.VALUE
MGRUPA3=ROBPOPIS.TXTGRUPA3.VALUE
MGRUPA4=ROBPOPIS.TXTGRUPA4.VALUE
MGRUPA5=ROBPOPIS.TXTGRUPA5.VALUE
MGRUPA=ROBPOPIS.TXTGRUPA.VALUE
MTXTKOL=ROBPOPIS.TXTKOL.VALUE
MMAGACIN=ROBPOPIS.TXTMAGACIN.VALUE

PUBLIC CTXT1,CTXT2,CTXT3

CTXT1=ROBPOPIS.CENTXT1.VALUE
CTXT2=ROBPOPIS.CENTXT2.VALUE
CTXT3=ROBPOPIS.CENTXT3.VALUE
SELECT DATUMI
REPLACE CENTXT1 WITH CTXT1
REPLACE CENTXT2 WITH CTXT2
REPLACE CENTXT3 WITH CTXT3

SELECT ROB
DO IDEL WITH (KKOCKAX)
SELECT ROB
SORT ON GRUPA TO &KKOCKA 
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
SELECT KOCKA
INDEX ON podnaziv TAG GRNAZ
SET ORDER TO 1 


   IF mtxtKOL='N'
      IF AGDE=0
         *REPORT FORM ROBPOPISPODDN PREVIEW FOR (GRUPA=MGRUPA.OR.MGRUPA=SPACE(3));
         .AND.(GRUPA1=MGRUPA1.OR.MGRUPA1=SPACE(3));
         .AND.(GRUPA2=MGRUPA2.OR.MGRUPA2=SPACE(3));
         .AND.(GRUPA3=MGRUPA3.OR.MGRUPA3=SPACE(3));
         .AND.(GRUPA4=MGRUPA4.OR.MGRUPA4=SPACE(3));
         .AND.(GRUPA5=MGRUPA5.OR.MGRUPA5=SPACE(3));
         .AND.(MAGACIN=MMAGACIN.OR.MMAGACIN=0).and.KOL<>0
         
   mfile='ROBPOPISPODDN'   
   USLOV1="(GRUPA=MGRUPA.OR.MGRUPA=SPACE(3));
      .AND.(GRUPA1=MGRUPA1.OR.MGRUPA1=SPACE(3));
      .AND.(GRUPA2=MGRUPA2.OR.MGRUPA2=SPACE(3));
      .AND.(GRUPA3=MGRUPA3.OR.MGRUPA3=SPACE(3))"
   USLOV2=".AND.(GRUPA4=MGRUPA4.OR.MGRUPA4=SPACE(3));
      .AND.(GRUPA5=MGRUPA5.OR.MGRUPA5=SPACE(3))"
      
   USLOV3=".AND.(MAGACIN=MMAGACIN.OR.MMAGACIN=0);
      .and.kol<>0"

      
   USLOV=USLOV1+USLOV2+USLOV3
   DO printer_bullzip WITH mdata02,mfiLE,USLOV
         
         
         
      ELSE
         REPORT FORM ROBPOPISPODDN TO PRINTER PROMPT FOR (GRUPA=MGRUPA.OR.MGRUPA=SPACE(3));
         .AND.(GRUPA1=MGRUPA1.OR.MGRUPA1=SPACE(3));
         .AND.(GRUPA2=MGRUPA2.OR.MGRUPA2=SPACE(3));
         .AND.(GRUPA3=MGRUPA3.OR.MGRUPA3=SPACE(3));
         .AND.(GRUPA4=MGRUPA4.OR.MGRUPA4=SPACE(3));
         .AND.(GRUPA5=MGRUPA5.OR.MGRUPA5=SPACE(3));
         .AND.(MAGACIN=MMAGACIN.OR.MMAGACIN=0).and.KOL<>0
      ENDIF
   ELSE
      IF AGDE=0
         *REPORT FORM ROBPOPISPODKDN PREVIEW FOR (GRUPA=MGRUPA.OR.MGRUPA=SPACE(3));
         .AND.(GRUPA1=MGRUPA1.OR.MGRUPA1=SPACE(3));
         .AND.(GRUPA2=MGRUPA2.OR.MGRUPA2=SPACE(3));
         .AND.(GRUPA3=MGRUPA3.OR.MGRUPA3=SPACE(3));
         .AND.(GRUPA4=MGRUPA4.OR.MGRUPA4=SPACE(3));
         .AND.(GRUPA5=MGRUPA5.OR.MGRUPA5=SPACE(3));
         .AND.(MAGACIN=MMAGACIN.OR.MMAGACIN=0).and.KOL<>0
         
   mfile='ROBPOPISPODKDN'   
   USLOV1="(GRUPA=MGRUPA.OR.MGRUPA=SPACE(3));
      .AND.(GRUPA1=MGRUPA1.OR.MGRUPA1=SPACE(3));
      .AND.(GRUPA2=MGRUPA2.OR.MGRUPA2=SPACE(3));
      .AND.(GRUPA3=MGRUPA3.OR.MGRUPA3=SPACE(3))"
   USLOV2=".AND.(GRUPA4=MGRUPA4.OR.MGRUPA4=SPACE(3));
      .AND.(GRUPA5=MGRUPA5.OR.MGRUPA5=SPACE(3))"
      
   USLOV3=".AND.(MAGACIN=MMAGACIN.OR.MMAGACIN=0);
      .and.kol<>0"

      
   USLOV=USLOV1+USLOV2+USLOV3
   DO printer_bullzip WITH mdata02,mfiLE,USLOV
         
         
         
         
      ELSE
         REPORT FORM ROBPOPISPODKDN TO PRINTER PROMPT FOR (GRUPA=MGRUPA.OR.MGRUPA=SPACE(3));
         .AND.(GRUPA1=MGRUPA1.OR.MGRUPA1=SPACE(3));
         .AND.(GRUPA2=MGRUPA2.OR.MGRUPA2=SPACE(3));
         .AND.(GRUPA3=MGRUPA3.OR.MGRUPA3=SPACE(3));
         .AND.(GRUPA4=MGRUPA4.OR.MGRUPA4=SPACE(3));
         .AND.(GRUPA5=MGRUPA5.OR.MGRUPA5=SPACE(3));
         .AND.(MAGACIN=MMAGACIN.OR.MMAGACIN=0).and.KOL<>0
      ENDIF
   ENDIF
SELECT KOCKA
USE
SELECT ROB
*ROBPOPIS.RELEASE
POP KEY