PUSH KEY CLEAR
*MUZIKA=MBAZNI+'\WAV\S009.WAV'
*SET BELL TO MUZIKA
*??CHR(7)
*SET BELL TO
SELECT ROBPROI
MPROIZV=PROIZV
SELECT ROB
IF PROIZV=SPACE(5)
  REPLACE PROIZV WITH MPROIZV
ENDIF   
ROBPROI.RELEASE
SELECT ROB
ROBAK2.REFRESH
POP KEY