PUSH KEY CLEAR
SELECT ROBPROI
SET ORDER TO
APPEND BLANK
REPLACE PROIZV WITH STR(RECNO(),5,0)
ROBPROI.GRD0.REFRESH
DO FORM ROBPROIK
SELECT ROBPROI
SET ORDER TO 2
ROBPROI.GRD0.SETFOCUS
ROBPROI.REFRESH
POP KEY