PUSH KEY CLEAR
SELECT ROBVRST
SET ORDER TO
APPEND BLANK
REPLACE rVRSTA WITH STR(RECNO(),5,0)
ROBVRSTA.GRD0.REFRESH
DO FORM ROBVRSTK
SELECT ROBVRST
SET ORDER TO 2
ROBVRSTA.GRD0.SETFOCUS
ROBVRSTA.REFRESH
POP KEY