PUSH KEY CLEAR
*MUZIKA=MBAZNI+'\WAV\S009.WAV'
*SET BELL TO MUZIKA
*??CHR(7)
*SET BELL TO
MRVRSTA=RVRSTA
SELECT ROB
IF RVRSTA=SPACE(5)
  REPLACE RVRSTA WITH MRVRSTA
ENDIF   
ROBVRSTA.RELEASE
SELECT ROB
ROBAK2.REFRESH
POP KEY