PARAMETERS MMIME,MMIME0,MASACEKAJ
   MFSALJI='C:\sc\input'
   MFPRIMI='C:\sc\output'
   COPY FILE &MMIME TO &MFSALJI
   IF MASACEKAJ=0
      INKEY(1)
   ENDIF
   SET PATH TO &MDATA02 
   SET DEFAULT TO &MDATA02
