PUSH KEY CLEAR
IF RECCOUNT()>0
   IF SENALG.ARHIVA=' '
      *---AKO NIJE ARHIVIRANA-----
      MBRKAL=BRKAL
      MDATDOK=DATDOK
      APPEND BLANK
      REPLACE BRKAL WITH MBRKAL 
      REPLACE DATDOK WITH MDATDOK
      SENAL.GRD0.SETFOCUS
      SENAL.REFRESH
   ELSE
      *------AKO JE KALKULACIJA  ARHIVIRANA
      SELECT SENAL
      SET ORDER TO 1 
      GO BOTTOM
      MBRKAL=BRKAL
      MNLEN=LEN(ALLTRIM(STR(VAL(ALLTRIM(MBRKAL))+1,6,0)))
      MNBRKAL=REPLI('0',6-MNLEN)+ALLTRIM(STR(VAL(ALLTRIM(MBRKAL))+1,6,0))
      SET ORDER TO 1
            LOCATE FOR BRKAL=MNBRKAL

      IF.NOT.FOUND()
         APPEND BLANK
         REPLACE BRKAL WITH MNBRKAL 
         SENAL.GRD0.SETFOCUS
         SENAL.GRD0.REFRESH
         SENAL.REFRESH
      ENDIF
      SELECT SENALG
            LOCATE FOR BRKAL=MNBRKAL

      IF.NOT.FOUND()
         APPEND BLANK
         REPLACE BRKAL WITH MNBRKAL
      ENDIF      
      DO FORM SENALZAG
      SELECT SENAL
      LOCATE FOR BRKAL=MNBRKAL
      REPLACE DATDOK WITH SENALG.DATDOK    
      SET ORDER TO 
   ENDIF 
ELSE
   *--------AKO PRVA STAVKA NE POSTOJI---------
   APPEND BLANK
   MNBRKAL='000001'
   REPLACE BRKAL WITH MNBRKAL 
   *------IDEMO U ZAGLAVLJE
   IF .NOT.FOUND()
      SELECT SENAL
      SET RELATION TO
      SELECT SENALG
      LOCATE FOR BRKAL=MNBRKAL
      IF.NOT.FOUND()
         APPEND BLANK
         REPLACE BRKAL WITH MNBRKAL
      ENDIF     
      DO FORM SENALZAG
      SELECT SENAL
      SET RELATION TO BRKAL INTO SENALG ADDITIVE
      SET RELATION TO RSIF INTO ROB ADDITIVE
      REPLACE DATDOK WITH SENALG.DATDOK
   ENDIF   
ENDIF    

POP KEY
SELECT SENAL
SET ORDER TO
SENAL.GRD0.COLUMN2.SETFOCUS
SENAL.REFRESH  
