PUSH KEY CLEAR
SELECT SENAL
IF EOF()
   GO bottom
endif   
MBRKAL=BRKAL
SET ORDER TO 1
LOCATE FOR BRKAL=MBRKAL

*REPORT FORM SENAL0O FOR BRKAL=MBRKAL PREVIEW 
   mfile='SENAL0o'   
   USLOV="BRKAL=MBRKAL"
   DO printer_bullzip WITH mdata02,mfiLE,USLOv

SELECT SENAL
LOCATE FOR BRKAL=MBRKAL

SET ORDER TO 
senal.grd0.setfocus
POP KEY
