PUSH KEY CLEAR
SELECT SENAL
SET ORDER TO 1
IF EOF()
   GO bottom
endif   
MSVEGA=0
MBRKAL=BRKAL
SET ORDER TO 1
LOCATE FOR BRKAL=MBRKAL

IF FOUND()
   MSVEGA=SENALG.SVEGA+SENALG.IZNOSKILO
      DO WHILE.NOT.EOF()
      IF BRKAL<>MBRKAL
         EXIT
      ENDIF   
      MSVEGA=MSVEGA+IZNOS
      SKIP
   ENDDO   
ENDIF
PUBLIC ASVEGA
ASVEGA=MSVEGA
LOCATE FOR BRKAL=MBRKAL

*REPORT FORM SENAL0 FOR BRKAL=MBRKAL PREVIEW 
   mfile='SENAL0'   
   USLOV="BRKAL=MBRKAL"
   DO printer_bullzip WITH mdata02,mfiLE,USLOv

SELECT SENAL
LOCATE FOR BRKAL=MBRKAL

SET ORDER TO 
senal.grd0.setfocus
POP KEY
