PUSH KEY CLEAR
MBRKAL=BRKAL
SELECT SENAL
SET RELATION TO
SELECT SENALG
LOCATE FOR BRKAL=MBRKAL

IF FOUND()
   IF ARHIVA=' '
      REPLACE ARHIVA WITH '*'
   ELSE
      REPLACE ARHIVA WITH ' '  
   ENDIF       
ENDIF
SELECT SENAL
SET ORDER TO 1
LOCATE FOR BRKAL=MBRKAL

SET ORDER TO 
SET RELATION TO BRKAL INTO SENALG  ADDITIVE
SET RELATION TO RSIF INTO ROB ADDITIVE
SENAL.GRD0.Refresh
SENAL.GRD0.SETFOCUS
POP KEY
SENAL.Refresh 

