PUSH KEY CLEAR
      SELECT SENAL
      MBRKAL=BRKAL
      SET RELATION TO
      SELECT SENALG
      DO FORM SENALZAG
      SELECT SENAL
      SET RELATION TO BRKAL INTO SENALG ADDITIVE
      SET RELATION TO RSIF INTO ROB ADDITIVE
      SET ORDER TO 1
      LOCATE FOR BRKAL=MBRKAL

      IF FOUND()
         DO WHILE.NOT.EOF()
            IF BRKAL<>MBRKAL
               EXIT
            ENDIF   
            REPLACE DATDOK WITH SENALG.DATDOK
            SKIP
         ENDDO
         LOCATE FOR BRKAL=MBRKAL

      ENDIF
      SET ORDER TO 
      SENAL.GRD0.SETFOCUS
POP KEY      
      SENAL.REFRESH      