PUSH KEY CLEAR
IF SENALG.ARHIVA=' '
   MSBRKAL=BRKAL
   MSRNAL='1'+SUBSTR(BRKAL,2,11)
   SELECT SEPARAM
   MRSIFU=RSIF
   USE &KFAK ALIAS FAK IN 0 ORDER 1
   USE &KFAKG IN 0 ALIAS FAKG ORDER 1
   SELECT FAK
   GO BOTTOM
   MNBRKAL='      '
   MNOVI=VAL(BRKAL)+1
   DO WHILE.T.
      MLEN=LEN(ALLTRIM(STR(MNOVI)))
      MNBRKAL=REPLI('0',6-MLEN)+ALLTRIM(STR(MNOVI))
      LOCATE FOR BRKAL=MNBRKAL
      IF FOUND()
         MNOVI=MNOVI+1
         LOOP
      ELSE
         EXIT
      ENDIF
   ENDDO
   SELECT SENAL
   SET ORDER TO 1
   *MMODEL=SENALG.MODEL
   *MREGBR=SENALG.REGBR
   SET RELATION TO
   SELECT FAK
   SET RELATION TO BRKAL INTO FAKG ADDITIVE 
   SET RELATION  TO RSIF INTO ROB ADDITIVE
   SELECT SENAL
   SET RELATION TO BRKAL INTO SENALG ADDITIVE
   MSVEGAU=SENALG.SVEGA+SENALG.IZNOSKILO
   SEEK MSBRKAL
   IF FOUND()
      MSIFRA=SENALG.SIFRA
      MDATDOK=SENALG.DATDOK
      MUREDJAJ=SENALG.UREDJAJ
      MIDBROJ=SENALG.IDBROJ
      DO WHILE.NOT.EOF()
         IF BRKAL<>MSBRKAL
            EXIT
         ENDIF
         MBRRAC=MSBRKAL
         MRSIF=RSIF
         MKOL=KOL
         SELECT ROB
         SEEK MRSIF
         MPROCPOR=ROB.PROCPOR
         MTARIFA=ROB.TARIFA
         MVELCENA=ROB.VELCENA
         MMALCENA=ROB.MALCENA
         MVRSTA=ROB.VRSTA
         MCENA=ROB.ZADNABM
         SELECT SENAL
         MSIFRA=SENALG.SIFRA
         SELECT FAK
         IF MKOL<>0
            APPEND BLANK 
            REPLACE BRKAL WITH MNBRKAL
            REPLACE RSIF WITH MRSIF
            REPLACE KOLI WITH MKOL
            IF MCENA<>0
               REPLACE CENA WITH MCENA
            ELSE
               REPLACE CENA WITH MVELCENA
            ENDIF
            REPLACE VELCENA WITH MVELCENA
            REPLACE VELVRED WITH MKOL*VELCENA
            REPLACE TARIFA WITH MTARIFA
            REPLACE PROCPOR WITH MPROCPOR
            REPLACE POREZ WITH ROUND(VELVRED*PROCPOR/100,2)
            REPLACE IZNI WITH KOLI*CENA
            REPLACE MARZA WITH VELVRED-IZNI
            IF IZNI<>0
               REPLACE MARPROC WITH ROUND(MARZA*100/IZNI,6)
            ELSE
               REPLACE MARPROC WITH 0
            ENDIF
         ENDIF
         SELECT SENAL
         SKIP
      ENDDO
   ENDIF 
   IF MSVEGAU<>0
      SELECT FAK
      APPEND BLANK 
      REPLACE BRKAL WITH MNBRKAL
      REPLACE RSIF WITH MRSIFU
      REPLACE KOLI WITH 1
      REPLACE CENA WITH 0.01
      REPLACE VELCENA WITH MSVEGAU
      REPLACE IZNI WITH KOLI*CENA
      REPLACE VELVRED WITH VELCENA
      REPLACE TARIFA WITH '20'
      REPLACE PROCPOR WITH 20
      REPLACE POREZ WITH ROUND(VELVRED*PROCPOR/100,2)
      REPLACE MARZA WITH VELVRED-IZNI
      IF IZNI<>0
         REPLACE MARPROC WITH ROUND(MARZA*100/IZNI,6)
      ELSE
         REPLACE MARPROC WITH 0
      ENDIF
   ENDIF
     
   SELECT FAKG
         LOCATE FOR BRKAL=MNBRKAL

   IF.NOT.FOUND()
      APPEND BLANK
      REPLACE BRKAL WITH MNBRKAL
      REPLACE BRRAC WITH MSBRKAL
      REPLACE SIFRA WITH MSIFRA
      REPLACE DATDOK WITH MDATDOK
      REPLACE VALUTA WITH MDATDOK
      REPLACE BRNAL WITH 'F3'+SUBSTR(MNBRKAL,3,4)
      REPLACE OTPDAT WITH MDATDOK
      REPLACE FVRSTA WITH '  1'
      REPLACE OPDV WITH '*'
      REPLACE NAPOMENAG WITH 'RAD NA UREDJAJU '+ALLTRIM(MUREDJAJ)
      REPLACE NAPOMENAD WITH 'FAKTURISANO PO RADNOM NALOGU '+MSBRKAL+'/'+MIDBROJ
      REPLACE RNAL WITH MSRNAL
      
   ENDIF
   SELECT FAK
   USE
   SELECT FAKG
   USE
   SELECT SENAL
   SET RELATION TO
   SEEK MSBRKAL
   SET ORDER TO
   SET RELATION TO BRKAL INTO SENALG ADDITIVE
   SET RELATION TO RSIF INTO ROB ADDITIVE
ENDIF
SENAL.GRD0.SETFOCUS
POP KEY
SENAL.REFRESH