PROCEDURE SOC0TAST
   ON KEY LABEL F1    DO HELPN WITH 'SOC0'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       SOC0.RELEASE
ENDPROC


PROCEDURE SOCTAST
   ON KEY LABEL F1    DO HELPN WITH 'SOC'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL +        DO SOCDOD
   ON KEY LABEL INS      DO SOCDOD      
   ON KEY LABEL F7       DO SOCPODACI         
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       SOC.RELEASE
ENDPROC

PROCEDURE SOCITAST
   ON KEY LABEL F1    DO HELPN WITH 'SOCI'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL +        DO SOCIDOD
   ON KEY LABEL INS      DO SOCIDOD      
   ON KEY LABEL F7       DO SOCIPODACI         
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       SOCI.RELEASE
ENDPROC

PROCEDURE SOCULICETAST
   ON KEY LABEL F1    DO HELPN WITH 'SOCULICE'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       SOCULICE.RELEASE
ENDPROC

PROCEDURE SOCpodTAST
   ON KEY LABEL F1    DO HELPN WITH 'SOCPOD'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       SOCPOD.RELEASE
ENDPROC


PROCEDURE SOCIPODTAST
   ON KEY LABEL F1    DO HELPN WITH 'SOCIPOD'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       SOCIPOD.RELEASE
ENDPROC
