PROCEDURE AKTUELNOTAST
 *  ON KEY LABEL F1    DO HELPN WITH 'AKTUELNO'
   ON KEY LABEL F2        ! /N CALC.EXE
 *  ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       AKTUELNO.RELEASE
ENDPROC

PROCEDURE AKTUELNOODDOTAST
*   ON KEY LABEL F1    DO HELPN WITH 'AKTUELNOODDO'
   ON KEY LABEL F2        ! /N CALC.EXE
*   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       AKTUELNOODDO.RELEASE
ENDPROC

PROCEDURE TEKSTTAST
*   ON KEY LABEL F1    DO HELPN WITH 'TEKST'
   ON KEY LABEL F2        ! /N CALC.EXE
*   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       TEKST.RELEASE
ENDPROC

PROCEDURE OBRBUTAST
 *  ON KEY LABEL F1    DO HELPN WITH 'OBRBU'
   ON KEY LABEL F2        ! /N CALC.EXE
 *  ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   OBRBU.RELEASE
ENDPROC


PROCEDURE OBRASCITAST
*   ON KEY LABEL F1    DO HELPN WITH 'OBRASCI'
   ON KEY LABEL F2        ! /N CALC.EXE
*   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   OBRASCI.RELEASE
ENDPROC

PROCEDURE OBROPPTAST
*   ON KEY LABEL F1    DO HELPN WITH 'OBROPP'
   ON KEY LABEL F2        ! /N CALC.EXE
*   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   OBROPP.RELEASE
ENDPROC

PROCEDURE OPPSEMATAST
*   ON KEY LABEL F1    DO HELPN WITH 'OPPSEMA'
   ON KEY LABEL F2        ! /N CALC.EXE
*   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   OPPSEMA.RELEASE
ENDPROC

PROCEDURE POROBTAST
*   ON KEY LABEL F1    DO HELPN WITH 'POROB'
   ON KEY LABEL F2        ! /N CALC.EXE
*   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   POROB.RELEASE
ENDPROC

PROCEDURE OBRBTGTAST
*   ON KEY LABEL F1    DO HELPN WITH 'OBRBTG'
   ON KEY LABEL F2        ! /N CALC.EXE
*   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   OBRBTG.RELEASE
ENDPROC

PROCEDURE OBRPB1TAST
 *  ON KEY LABEL F1    DO HELPN WITH 'OBRPB1'
   ON KEY LABEL F2        ! /N CALC.EXE
 *  ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   OBRPB1.RELEASE
ENDPROC


PROCEDURE OBRPKTAST
 *  ON KEY LABEL F1    DO HELPN WITH 'OBRPK'
   ON KEY LABEL F2        ! /N CALC.EXE
 *  ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   OBRPK.RELEASE
ENDPROC


PROCEDURE OBRPB1ATAST
 *  ON KEY LABEL F1    DO HELPN WITH 'OBRPB1A'
   ON KEY LABEL F2        ! /N CALC.EXE
 *  ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   OBRPB1A.RELEASE
ENDPROC


PROCEDURE OBRPB2TAST
*   ON KEY LABEL F1    DO HELPN WITH 'OBRPB2'
   ON KEY LABEL F2        ! /N CALC.EXE
*   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   OBRPB2.RELEASE
ENDPROC

PROCEDURE OBRPB2TAST
*   ON KEY LABEL F1    DO HELPN WITH 'OBRPB2'
   ON KEY LABEL F2        ! /N CALC.EXE
*   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   OBRPB2.RELEASE
ENDPROC

PROCEDURE OBRPDPTAST
*   ON KEY LABEL F1    DO HELPN WITH 'OBRPDP'
   ON KEY LABEL F2        ! /N CALC.EXE
*   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   OBRPDP.RELEASE
ENDPROC

PROCEDURE OBRPDP2TAST
*   ON KEY LABEL F1    DO HELPN WITH 'OBRPDP2'
   ON KEY LABEL F2        ! /N CALC.EXE
*   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   OBRPDP2.RELEASE
ENDPROC
PROCEDURE OBRPDP3TAST
*   ON KEY LABEL F1    DO HELPN WITH 'OBRPDP3'
   ON KEY LABEL F2        ! /N CALC.EXE
*   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   OBRPDP3.RELEASE
ENDPROC

PROCEDURE OBRPDP2NTAST
*   ON KEY LABEL F1    DO HELPN WITH 'OBRPDP2N'
   ON KEY LABEL F2        ! /N CALC.EXE
*   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   OBRPDP2N.RELEASE
ENDPROC
PROCEDURE OBRPDP3NTAST
*   ON KEY LABEL F1    DO HELPN WITH 'OBRPDP3N'
   ON KEY LABEL F2        ! /N CALC.EXE
*   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   OBRPDP3N.RELEASE
ENDPROC

PROCEDURE OBRPDPNTAST
*   ON KEY LABEL F1    DO HELPN WITH 'OBRPDPN'
   ON KEY LABEL F2        ! /N CALC.EXE
*   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   OBRPDPN.RELEASE
ENDPROC

PROCEDURE OBRPK1TAST
*   ON KEY LABEL F1    DO HELPN WITH 'OBRPK1'
   ON KEY LABEL F2        ! /N CALC.EXE
*   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   OBRPK1.RELEASE
ENDPROC

PROCEDURE OBRPK2TAST
*   ON KEY LABEL F1    DO HELPN WITH 'OBRPK2'
   ON KEY LABEL F2        ! /N CALC.EXE
*   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   OBRPK2.RELEASE
ENDPROC

PROCEDURE OBRPK3TAST
*   ON KEY LABEL F1    DO HELPN WITH 'OBRPK3'
   ON KEY LABEL F2        ! /N CALC.EXE
*   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   OBRPK3.RELEASE
ENDPROC



PROCEDURE OBRPP4TAST
*   ON KEY LABEL F1    DO HELPN WITH 'OBRPP4'
   ON KEY LABEL F2        ! /N CALC.EXE
*   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   OBRPP4.RELEASE
ENDPROC

PROCEDURE OBRPP8TAST
*   ON KEY LABEL F1    DO HELPN WITH 'OBRPP8'
   ON KEY LABEL F2        ! /N CALC.EXE
*   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   OBRPP8.RELEASE
ENDPROC

PROCEDURE OBRSUTAST
*   ON KEY LABEL F1    DO HELPN WITH 'OBRSU'
   ON KEY LABEL F2        ! /N CALC.EXE
*   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   OBRSU.RELEASE
ENDPROC

PROCEDURE OBRSU1TAST
*   ON KEY LABEL F1    DO HELPN WITH 'OBRSU1'
   ON KEY LABEL F2        ! /N CALC.EXE
*   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   OBRSU1.RELEASE
ENDPROC

PROCEDURE OBRSU3TAST
*   ON KEY LABEL F1    DO HELPN WITH 'OBRSU1'
   ON KEY LABEL F2        ! /N CALC.EXE
*   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   OBRSU3.RELEASE
ENDPROC



PROCEDURE OBRSITAST
*   ON KEY LABEL F1    DO HELPN WITH 'OBRSI'
   ON KEY LABEL F2        ! /N CALC.EXE
*   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   OBRSI.RELEASE
ENDPROC

PROCEDURE OBRPPDG1TAST
*   ON KEY LABEL F1    DO HELPN WITH 'OBRPPDG1'
   ON KEY LABEL F2        ! /N CALC.EXE
*   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   OBRPPDG1.RELEASE
ENDPROC


PROCEDURE OBRPPDG1ATAST
 *  ON KEY LABEL F1    DO HELPN WITH 'OBRPPDG1A'
   ON KEY LABEL F2        ! /N CALC.EXE
 *  ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   OBRPPDG1A.RELEASE
ENDPROC

PROCEDURE OBRPPDG1BTAST
 *  ON KEY LABEL F1    DO HELPN WITH 'OBRPPDG1B'
   ON KEY LABEL F2        ! /N CALC.EXE
 *  ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   OBRPPDG1B.RELEASE
ENDPROC

PROCEDURE OBRPPDG1CTAST
 *  ON KEY LABEL F1    DO HELPN WITH 'OBRPPDG1C'
   ON KEY LABEL F2        ! /N CALC.EXE
 *  ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   OBRPPDG1C.RELEASE
ENDPROC

PROCEDURE OBRIPDTAST
*   ON KEY LABEL F1    DO HELPN WITH 'OBRIPD'
   ON KEY LABEL F2        ! /N CALC.EXE
*   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   OBRIPD.RELEASE
ENDPROC

PROCEDURE OBRIPD1TAST
*   ON KEY LABEL F1    DO HELPN WITH 'OBRIPD1'
   ON KEY LABEL F2        ! /N CALC.EXE
*   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   OBRIPD1.RELEASE
ENDPROC

PROCEDURE OBROBAVPDVTAST
*   ON KEY LABEL F1    DO HELPN WITH 'OBROBAVPDV'
   ON KEY LABEL F2        ! /N CALC.EXE
*   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       OBROBAVPDV.RELEASE
ENDPROC

PROCEDURE OBREPPDVTAST
*   ON KEY LABEL F1    DO HELPN WITH 'OBREPPDV'
   ON KEY LABEL F2        ! /N CALC.EXE
*   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       OBREPPDV.RELEASE
ENDPROC

PROCEDURE OBRERPTAST
*   ON KEY LABEL F1    DO HELPN WITH 'OBRERP'
   ON KEY LABEL F2        ! /N CALC.EXE
*   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       OBRERP.RELEASE
ENDPROC

PROCEDURE OBRPPDG5TAST
*   ON KEY LABEL F1    DO HELPN WITH 'OBRPPDG5'
   ON KEY LABEL F2        ! /N CALC.EXE
*   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       OBRPPDG5.RELEASE
ENDPROC

PROCEDURE OBRPPDG2RTAST
*   ON KEY LABEL F1    DO HELPN WITH 'OBRPPDG5'
   ON KEY LABEL F2        ! /N CALC.EXE
*   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       OBRPPDG2R.RELEASE
ENDPROC

PROCEDURE TMPUTTAST
*   ON KEY LABEL F1    DO HELPN WITH 'TMPUT'
   ON KEY LABEL F2        ! /N CALC.EXE
*   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       TMPUT.RELEASE
ENDPROC

PROCEDURE ZAKONItast
*   ON KEY LABEL F1    DO HELPN WITH 'ZAKONI'
   ON KEY LABEL F2        ! /N CALC.EXE
*   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       ZAKONI.RELEASE
ENDPROC

PROCEDURE ZAKONI0TAST
*   ON KEY LABEL F1    DO HELPN WITH 'ZAKONI0'
   ON KEY LABEL F2        ! /N CALC.EXE
*   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   ZAKONI0.RELEASE
ENDPROC

PROCEDURE PREGLEDTAST
*   ON KEY LABEL F1    DO HELPN WITH 'PREGLED'
   ON KEY LABEL F2        ! /N CALC.EXE
*   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PREGLED.RELEASE
ENDPROC

PROCEDURE PREGLEDTXTTAST
*   ON KEY LABEL F1    DO HELPN WITH 'PREGLEDTXT'
   ON KEY LABEL F2        ! /N CALC.EXE
*   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PREGLEDTXT.RELEASE
ENDPROC

PROCEDURE PREGFTAST
*   ON KEY LABEL F1    DO HELPN WITH 'PREGF'
   ON KEY LABEL F2        ! /N CALC.EXE
*   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PREGF.RELEASE
ENDPROC

PROCEDURE VIZITKETAST
 *  ON KEY LABEL F1    DO HELPN WITH 'VIZITKE'
   ON KEY LABEL F2        ! /N CALC.EXE
 *  ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VIZITKE.RELEASE
ENDPROC


PROCEDURE VIZITKEKTAST
 *  ON KEY LABEL F1    DO HELPN WITH 'VIZITKEK'
   ON KEY LABEL F2        ! /N CALC.EXE
 *  ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VIZITKEK.RELEASE
ENDPROC

*------------------------------------------


PROCEDURE INDEKSIRANJETAST
   ON KEY LABEL F1    DO HELPN WITH 'INDEKSIRANJE'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   INDEKSIRANJE.RELEASE
ENDPROC


PROCEDURE PUDATVALTAST
   ON KEY LABEL F1    DO HELPN WITH 'PUDATVAL'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PUDATVAL.RELEASE
ENDPROC

PROCEDURE PUANALTAST
   ON KEY LABEL F1    DO HELPN WITH 'PUANAL'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PUANAL.RELEASE
ENDPROC


PROCEDURE PUANALTRAZITAST
   ON KEY LABEL F1    DO HELPN WITH 'PUANALTRAZI'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PUANALTRAZI.RELEASE
ENDPROC

PROCEDURE PUKNJIZINALTAST
   ON KEY LABEL F1    DO HELPN WITH 'PUKNJIZINAL'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PUKNJIZINAL.RELEASE
ENDPROC


PROCEDURE PUANALIZVTAST
   ON KEY LABEL F1    DO HELPN WITH 'PUANALIZV'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PUANALZIV.RELEASE
ENDPROC

PROCEDURE DOPUNAKONTATAST
   ON KEY LABEL F1    DO HELPN WITH 'DOPUNAKONTA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       DOPUNAKONTA.RELEASE
ENDPROC

PROCEDURE ZATVPERTAST
ON KEY LABEL F1    DO HELPN WITH 'ZATVPER'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       ZATVPER.RELEASE
ENDPROC

PROCEDURE BRISILOKALNETTAST
   ON KEY LABEL F1    DO HELPN WITH 'BRISILOKALNET'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       BRISILOKALNET.RELEASE
ENDPROC

PROCEDURE SVETABELETAST
ON KEY LABEL F1        DO HELPN WITH 'SVETABELE'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       SVETABELE.RELEASE
ENDPROC

PROCEDURE BOJE0TAST
ON KEY LABEL F1        DO HELPN WITH 'BOJE0'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       BOJE0.RELEASE
ENDPROC

PROCEDURE AACARINATAST
   ON KEY LABEL F1    DO HELPN WITH 'AACARINA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   AACARINA.RELEASE
ENDPROC

PROCEDURE AAIZDVOJENOTAST
   ON KEY LABEL F1    DO HELPN WITH 'AAIZDVOJENO'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   AAIZDVOJENO.RELEASE
ENDPROC

PROCEDURE ZAMENATAST
   ON KEY LABEL F1    DO HELPN WITH 'ZAMENA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   ZAMENA.RELEASE
ENDPROC

PROCEDURE FIRMATAST
   ON KEY LABEL F1    DO HELPN WITH 'FIRMA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   FIRMA.RELEASE
ENDPROC

PROCEDURE FIRMAPARTAST
   ON KEY LABEL F1    DO HELPN WITH 'FIRMAPAR'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   FIRMAPAR.RELEASE
ENDPROC

PROCEDURE FIRMA2TAST
   ON KEY LABEL F1    DO HELPN WITH 'FIRMA2'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   FIRMA2.RELEASE
ENDPROC

PROCEDURE LOZINKETAST
   ON KEY LABEL F1    DO HELPN WITH 'LOZNIKE'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   LOZINKES.RELEASE
ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC

ENDPROC

PROCEDURE LOZINKESTAST
   ON KEY LABEL F1    DO HELPN WITH 'LOZINKES'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       LOZINKES.RELEASE
ENDPROC

PROCEDURE PRENOStast
ON KEY LABEL F1    DO HELPN WITH 'PRENOS'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PRENOS.RELEASE
ENDPROC

PROCEDURE NOVAGODTAST
   ON KEY LABEL F1    DO HELPN WITH 'NOVAGOD'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       NOVAGOD.RELEASE
ENDPROC

PROCEDURE CAREVTAST
   ON KEY LABEL F1    DO HELPN WITH 'CAREV'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       CAREV.RELEASE
ENDPROC

PROCEDURE CAREV3TAST
   ON KEY LABEL F1    DO HELPN WITH 'CAREV3'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       CAREV3.RELEASE
ENDPROC


PROCEDURE CARROBTAST
   ON KEY LABEL F1    DO HELPN WITH 'CARROB'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       CARROB.RELEASE
ENDPROC

PROCEDURE CARROBKTAST
   ON KEY LABEL F1    DO HELPN WITH 'CARROBK'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       CARROBK.RELEASE
ENDPROC

PROCEDURE APFAKTAST
   ON KEY LABEL F1    DO HELPN WITH 'APFAK'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       APFAK.RELEASE
ENDPROC

PROCEDURE APFAK0TAST
   ON KEY LABEL F1    DO HELPN WITH 'APFAK0'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       APFAK0.RELEASE
ENDPROC

PROCEDURE APFAKKTAST
   ON KEY LABEL F1    DO HELPN WITH 'APFAKK'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       APFAKK.RELEASE
ENDPROC

PROCEDURE APIZVTAST
   ON KEY LABEL F1    DO HELPN WITH 'APZIV'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       APIZV.RELEASE
ENDPROC

PROCEDURE APIZV01TAST
   ON KEY LABEL F1    DO HELPN WITH 'APIZV01'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       APIZV01.RELEASE
ENDPROC

PROCEDURE APTROTAST
   ON KEY LABEL F1    DO HELPN WITH 'APTRO'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       APTRO.RELEASE
ENDPROC

PROCEDURE PUTAST

ON KEY LABEL F1        DO HELPN WITH 'PU'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL +         DO PUDODAJ
on key label INS       DO PUDODAJ
ON KEY LABEL ESC       PU.RELEASE
on key label F4        DO PUPART
*on key label F6        DO PUTRAZI
ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC
ON KEY LABEL CTRL+F12  DO OTVPU

ENDPROC


PROCEDURE PU0TAST

ON KEY LABEL F1    DO HELPN WITH 'PU0'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       PU0.RELEASE
ON KEY LABEL +         DO PU0DOD
ON KEY LABEL F7        DO PU0KARTF7
on key label INS       DO PU0DOD
ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC

ENDPROC


PROCEDURE PU0KTAST
   ON KEY LABEL F1    DO HELPN WITH 'PU0K'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PU0K.RELEASE
ENDPROC

PROCEDURE REC0TAST
   ON KEY LABEL F1    DO HELPN WITH 'REC0'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       REC0.RELEASE
ENDPROC

PROCEDURE APTRO0TAST
   ON KEY LABEL F1    DO HELPN WITH 'APTRO0'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       APTRO0.RELEASE
ENDPROC

PROCEDURE RECSOBETAST
   ON KEY LABEL F1    DO HELPN WITH 'RECSOBE'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       RECSOBE.RELEASE
ENDPROC

PROCEDURE RECVRSTATAST
   ON KEY LABEL F1    DO HELPN WITH 'RECVRSTA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       RECVRSTA.RELEASE
ENDPROC

PROCEDURE RECCENETAST
   ON KEY LABEL F1    DO HELPN WITH 'RECCENE'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       RECCENE.RELEASE
ENDPROC

PROCEDURE RECAN0TAST
   ON KEY LABEL F1    DO HELPN WITH 'RECAN0'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       RECAN0.RELEASE
ENDPROC

PROCEDURE RECKOPIRTAST
   ON KEY LABEL F1    DO HELPN WITH 'RECKOPIR'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       RECKOPIR.RELEASE
ENDPROC

PROCEDURE RECKOPIDTAST
   ON KEY LABEL F1    DO HELPN WITH 'RECKOPID'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       RECKOPID.RELEASE
ENDPROC

PROCEDURE RECBRISIRTAST
   ON KEY LABEL F1    DO HELPN WITH 'RECBRISIR'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       RECBRISIR.RELEASE
ENDPROC

PROCEDURE RECTREBTAST
   ON KEY LABEL F1    DO HELPN WITH 'RECTREB'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       RECTREB.RELEASE
ENDPROC

PROCEDURE NCALCTAST
ON KEY LABEL F1    DO HELPN WITH 'NCALC'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL INS       DO NCALCDOD
ON KEY LABEL F7        DO NCALCF7
ON KEY LABEL F8        DO NCALCF8
ON KEY LABEL ESC       NCALC.RELEASE
ENDPROC

PROCEDURE HELPNTAST
   ON KEY LABEL ESC       HELPN.RELEASE
   ON KEY LABEL F1    ON KEY
   ON KEY LABEL CTRL+F12  HELPN.GRD0.READONLY=.F.
ENDPROC


PROCEDURE KOMANDETAST
   ON KEY LABEL F1    DO HELPN WITH 'KOMANDE'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL +         DO KOMANDEDOD
   ON KEY LABEL INS       DO KOMANDEDOD
   ON KEY LABEL F3       DO KOMANDEZNAK
   ON KEY LABEL SHIFT+F10 DO KOMANDEBRIS
   ON KEY LABEL F5 DO KOMANDEF5
   ON KEY LABEL SHIFT+F5 DO KOMANDESF5
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       KOMANDE.RELEASE
ENDPROC





PROCEDURE glavna2snimanje1TAST
   ON KEY LABEL F1    DO HELPN WITH 'glavna2snimanje1'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       glavna2snimanje1.RELEASE
ENDPROC


PROCEDURE lozinkeatast
   ON KEY LABEL F1    DO HELPN WITH 'LOZINKEA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
  ON KEY LABEL ESC    lozinkea.RELEASE
ENDPROC


PROCEDURE FAKCMRTAST
   ON KEY LABEL F1    DO HELPN WITH 'FAKCMR'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       FAKCMR.RELEASE
ENDPROC


PROCEDURE FAKCMR0TAST
   ON KEY LABEL F1    DO HELPN WITH 'FAKCMR0'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       FAKCMR0.RELEASE
ENDPROC


PROCEDURE APTROKTAST
   ON KEY LABEL F1    DO HELPN WITH 'APTROK'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       APTROK.RELEASE
ENDPROC

PROCEDURE APTR00TAST
   ON KEY LABEL F1    DO HELPN WITH 'APTR00'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       APTR00.RELEASE
ENDPROC

PROCEDURE PORUKATAST
   ON KEY LABEL F1    DO HELPN WITH 'PORUKA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PORUKA.RELEASE
ENDPROC

PROCEDURE PRENGKPONTAST
   ON KEY LABEL F1    DO HELPN WITH 'PRENGKPON'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PRENGKPON.RELEASE
ENDPROC

PROCEDURE PRENPDVPONTAST
   ON KEY LABEL F1    DO HELPN WITH 'PRENPDVPON'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PRENPDVPON.RELEASE
ENDPROC


PROCEDURE FAN0TAST

ON KEY LABEL F1    DO HELPN WITH 'FAN0'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       FAN0.RELEASE
ON KEY LABEL +         DO FAN0DOD
on key label INS       DO FAN0DOD
ON KEY LABEL F3        DO FAN0DEONAZ
ON KEY LABEL ALT+F3        DO FAN0TEKRAC
ON KEY LABEL F4        DO FAN0TRAZI
ON KEY LABEL F5        DO FAN0GR5TRAZI
ON KEY LABEL F6        DO FAN0TRAZIF6
ON KEY LABEL F7        DO FAN0KARTF7
ON KEY LABEL F8        DO FAN0ZIROTRAZI
ON KEY LABEL CTRL+F12  DO OTVFAN0
ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC

ENDPROC


PROCEDURE REC0REZTAST
   ON KEY LABEL F1    DO HELPN WITH 'REC0REZ'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       REC0REZ.RELEASE
ENDPROC

PROCEDURE RECan0REZTAST
   ON KEY LABEL F1    DO HELPN WITH 'RECAN0'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       RECAN0.RELEASE
ENDPROC

PROCEDURE RECBRISIRTAST
   ON KEY LABEL F1    DO HELPN WITH 'RECBRISIR'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       RECBRISIR.RELEASE
ENDPROC


PROCEDURE FMESTATAST
ON KEY LABEL F1    DO HELPN WITH 'FMESTA'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL +         DO FMESTADOD
on key label INS       DO FMESTADOD
ON KEY LABEL ESC       FMESTA.RELEASE
ON KEY LABEL F7        DO FMESTAK
ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC

ENDPROC

PROCEDURE FMESTATRTAST

ON KEY LABEL F1    DO HELPN WITH 'FMESTATR'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 

ON KEY LABEL +         DO FMESTATRDOD
on key label INS       DO FMESTATRDOD
ON KEY LABEL ESC       FMESTATR.RELEASE
ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC

ENDPROC



PROCEDURE AN0K2TAST
ON KEY LABEL F1    DO HELPN WITH 'AN0K2'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       AN0K2.RELEASE
ENDPROC


PROCEDURE fan0dEONAZTAST
   ON KEY LABEL F1    DO HELPN WITH 'FAN0DEONAZ'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       fan0DEONAZ.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE recniktast 
   ON KEY LABEL F1    DO HELPN WITH 'RECNIK'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       RECNIK.RELEASE
ENDPROC


PROCEDURE ANALKNALTAST
ON KEY LABEL F1    DO HELPN WITH 'ANALKNAL'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       ANALKNAL.RELEASE
   ON KEY LABEL F10       DO ANALKNALPRN
ENDPROC


PROCEDURE MESTAKTAST
   ON KEY LABEL F1    DO HELPN WITH 'MESTAK'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   MESTAK.RELEASE
ENDPROC

PROCEDURE fan0TEKRACTAST
   ON KEY LABEL F1    DO HELPN WITH 'FAN0TEKRAC'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       fan0TEKRAC.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC




PROCEDURE os0TAST
   ON KEY LABEL F1    DO HELPN WITH 'OS0'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL +     DO OS0DODAJ
   ON KEY LABEL ESC   os0.RELEASE
ENDPROC

PROCEDURE osTAST
   ON KEY LABEL F1    DO HELPN WITH 'OS'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   os.RELEASE
ENDPROC

PROCEDURE osOATAST
   ON KEY LABEL F1    DO HELPN WITH 'OSOA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   osOA.RELEASE
ENDPROC

PROCEDURE osTRAZISIFTAST
   ON KEY LABEL F1    DO HELPN WITH 'OSTRAZISIF'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   osTRAZISIF.RELEASE
ENDPROC

PROCEDURE osTRAZIINVTAST
   ON KEY LABEL F1    DO HELPN WITH 'OSTRAZIINV'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   osTRAZIINV.RELEASE
ENDPROC

PROCEDURE ospodaciTAST
   ON KEY LABEL F1    DO HELPN WITH 'OSPODACI'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   ospodaci.RELEASE
ENDPROC

PROCEDURE OSprenosTAST
   ON KEY LABEL F1    DO HELPN WITH 'OSPRENOS'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   OSprenos.RELEASE
ENDPROC



PROCEDURE PCDEF0TAST
   ON KEY LABEL F1    DO HELPN WITH 'PCDEF0'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL F3 DO PCPROFC
   ON KEY LABEL F4 DO PCSEKTOR
   ON KEY LABEL F5 DO PCPODSEK
   ON KEY LABEL F6 DO PCLOKAC
   ON KEY LABEL F7 DO PCLOKACP
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PCDEF0.RELEASE
ENDPROC

PROCEDURE PCPROFCTAST
   ON KEY LABEL F1    DO HELPN WITH 'PCPROFC'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PCPROFC.RELEASE
ENDPROC

PROCEDURE PCSEKTORTAST
   ON KEY LABEL F1    DO HELPN WITH 'PCSEKTOR'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PCSEKTOR.RELEASE
ENDPROC

PROCEDURE PCPODSEKTAST
   ON KEY LABEL F1    DO HELPN WITH 'PCPODSEK'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PCPODSEK.RELEASE
ENDPROC

PROCEDURE PCLOKACTAST
   ON KEY LABEL F1    DO HELPN WITH 'PCLOKAC'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PCLOKAC.RELEASE
ENDPROC

PROCEDURE PCLOKACPTAST
   ON KEY LABEL F1    DO HELPN WITH 'PCLOKACP'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PCLOKACP.RELEASE
ENDPROC


PROCEDURE TP001TAST
ON KEY LABEL F1    DO HELPN WITH 'TP001'
ON KEY LABEL ESC       TP001.RELEASE
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ENDPROC

PROCEDURE TP002TAST
ON KEY LABEL F1    DO HELPN WITH 'TP002'
ON KEY LABEL ESC       TP002.RELEASE
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ENDPROC
PROCEDURE TP003TAST
ON KEY LABEL F1    DO HELPN WITH 'TP003'
ON KEY LABEL ESC       TP003.RELEASE
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ENDPROC
PROCEDURE TP004TAST
ON KEY LABEL F1    DO HELPN WITH 'TP004'
ON KEY LABEL ESC       TP004.RELEASE
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ENDPROC
PROCEDURE TP005TAST
ON KEY LABEL F1    DO HELPN WITH 'TP005'
ON KEY LABEL ESC       TP005.RELEASE
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ENDPROC

PROCEDURE TP006TAST
ON KEY LABEL F1    DO HELPN WITH 'TP006'
ON KEY LABEL ESC       TP006.RELEASE
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ENDPROC


PROCEDURE TPPRENOSTAST
ON KEY LABEL F1    DO HELPN WITH 'TPPRENOS'
ON KEY LABEL ESC       TPPRENOS.RELEASE
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ENDPROC

PROCEDURE TPRAZLOGTAST
ON KEY LABEL F1    DO HELPN WITH 'TPRAZLOG'
ON KEY LABEL ESC       TPRAZLOG.RELEASE
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ENDPROC

PROCEDURE TPTIPTAST
ON KEY LABEL F1    DO HELPN WITH 'TPTIP'
ON KEY LABEL ESC       TPTIP.RELEASE
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ENDPROC

PROCEDURE TPZEMLJATAST
ON KEY LABEL F1    DO HELPN WITH 'TPZEMLJA'
ON KEY LABEL ESC       TPZEMLJA.RELEASE
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ENDPROC


PROCEDURE TPVRSTATAST
ON KEY LABEL F1    DO HELPN WITH 'TPVRSTA'
ON KEY LABEL ESC       TPVRSTA.RELEASE
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ENDPROC

PROCEDURE TPNAMENATAST
ON KEY LABEL F1    DO HELPN WITH 'TPNAMENA'
ON KEY LABEL ESC       TPNAMENA.RELEASE
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ENDPROC


PROCEDURE TPGORIVOTAST
ON KEY LABEL F1    DO HELPN WITH 'TPGORIVO'
ON KEY LABEL ESC       TPGORIVO.RELEASE
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ENDPROC


PROCEDURE TP001KTAST
ON KEY LABEL F1    DO HELPN WITH 'TP001K'
ON KEY LABEL ESC       TP001K.RELEASE
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ENDPROC

PROCEDURE TPTIPKTAST
ON KEY LABEL F1    DO HELPN WITH 'TPTIPK'
ON KEY LABEL ESC       TPTIPK.RELEASE
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ENDPROC

PROCEDURE TPOSNBOJATAST
ON KEY LABEL F1    DO HELPN WITH 'TPOSNBOJA'
ON KEY LABEL ESC       TPOSNBOJA.RELEASE
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ENDPROC

PROCEDURE TPSPOBOJATAST
ON KEY LABEL F1    DO HELPN WITH 'TPSPOBOJA'
ON KEY LABEL ESC       TPSPOBOJA.RELEASE
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ENDPROC

PROCEDURE TPTIP0TAST
ON KEY LABEL F1    DO HELPN WITH 'TPTIP0'
ON KEY LABEL ESC       TPTIP0.RELEASE
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ENDPROC


PROCEDURE TPZANIMTAST
ON KEY LABEL F1    DO HELPN WITH 'TPZANIM'
ON KEY LABEL ESC       TPZANIM.RELEASE
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ENDPROC

PROCEDURE TPOPSTINATAST
ON KEY LABEL F1    DO HELPN WITH 'TPOPSTINA'
ON KEY LABEL ESC       TPOPSTINA.RELEASE
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ENDPROC

PROCEDURE TPDRZAVATAST
ON KEY LABEL F1    DO HELPN WITH 'TPDRZAVA'
ON KEY LABEL ESC       TPDRZAVA.RELEASE
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ENDPROC


PROCEDURE TPUREDJAJTAST
ON KEY LABEL F1    DO HELPN WITH 'TPUREDJAJ'
ON KEY LABEL ESC       TPUREDJAJ.RELEASE
ON KEY LABEL F2        ! /N CALC.EXE

ON KEY LABEL CTRL+ENTER DO NCALC 
ENDPROC

PROCEDURE TPVRPREVOZTAST
ON KEY LABEL F1    DO HELPN WITH 'TPVRPREVOZ'
ON KEY LABEL ESC       TPVRPREVOZ.RELEASE
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ENDPROC

PROCEDURE TPRADIOTAST
ON KEY LABEL F1    DO HELPN WITH 'TPRADIO'
ON KEY LABEL ESC       TPRADIO.RELEASE
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ENDPROC

PROCEDURE TPOTGTAST
ON KEY LABEL F1    DO HELPN WITH 'TPOTG'
ON KEY LABEL ESC       TPOTG.RELEASE
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ENDPROC

PROCEDURE TPVIRMPREUZMITAST
ON KEY LABEL F1    DO HELPN WITH 'TPVIRMPREUZMI'
ON KEY LABEL ESC       TPVIRMPREUZMI.RELEASE
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ENDPROC

PROCEDURE TPZAPRTAST
ON KEY LABEL F1    DO HELPN WITH 'TPZAPR'
ON KEY LABEL ESC       TPZAPR.RELEASE
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ENDPROC

PROCEDURE TPVIRM0TAST
ON KEY LABEL F1    DO HELPN WITH 'TPVIRM0'
ON KEY LABEL ESC       TPVIRM0.RELEASE
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ENDPROC

PROCEDURE TPFIRMETAST
ON KEY LABEL F1    DO HELPN WITH 'TPFIRME'
ON KEY LABEL ESC       TPFIRME.RELEASE
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ENDPROC

PROCEDURE TPVIRMATAST
ON KEY LABEL F1    DO HELPN WITH 'TPVIRMA'
ON KEY LABEL ESC       TPVIRMA.RELEASE
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ENDPROC

PROCEDURE TPVIRMAPREGTAST
ON KEY LABEL F1    DO HELPN WITH 'TPVIRMAPREG'
ON KEY LABEL ESC       TPVIRMAPREG.RELEASE
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ENDPROC



PROCEDURE AAOSTAST
   ON KEY LABEL F1    DO HELPN WITH 'AAOS'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   AAOS.RELEASE
ENDPROC



PROCEDURE AATRANSPORTTAST
   ON KEY LABEL F1    DO HELPN WITH 'AATRANSPORT'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   AATRANSPORT.RELEASE
ENDPROC

PROCEDURE VOZTAST
   ON KEY LABEL F1    DO HELPN WITH 'VOZ'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   VOZ.RELEASE
ENDPROC


PROCEDURE VOZTR0TAST
   ON KEY LABEL F1    DO HELPN WITH 'VOZTR0'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   VOZTR0.RELEASE
ENDPROC

PROCEDURE VOZTR0KTAST
   ON KEY LABEL F1    DO HELPN WITH 'VOZTR0K'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   VOZTR0K.RELEASE
ENDPROC

PROCEDURE VOZNALTAST
   ON KEY LABEL F1    DO HELPN WITH 'VOZNAL'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   VOZNAL.RELEASE
ENDPROC

PROCEDURE VOZNALKTAST
   ON KEY LABEL F1    DO HELPN WITH 'VOZNALK'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   VOZNALK.RELEASE
ENDPROC

PROCEDURE VOZILATAST
   ON KEY LABEL F1    DO HELPN WITH 'VOZILA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   VOZILA.RELEASE
ENDPROC

PROCEDURE VOZILAKTAST
   ON KEY LABEL F1    DO HELPN WITH 'VOZILAK'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   VOZILAK.RELEASE
ENDPROC

PROCEDURE VOZACITAST
   ON KEY LABEL F1    DO HELPN WITH 'VOZACI'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   VOZACI.RELEASE
ENDPROC

PROCEDURE VOZACIKTAST
   ON KEY LABEL F1    DO HELPN WITH 'VOZACIK'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   VOZACIK.RELEASE
ENDPROC

PROCEDURE VOZPREG1TAST
   ON KEY LABEL F1    DO HELPN WITH 'VOZPREG1'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   VOZPREG1.RELEASE
ENDPROC

PROCEDURE VOZPREG2TAST
   ON KEY LABEL F1    DO HELPN WITH 'VOZPREG2'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   VOZPREG2.RELEASE
ENDPROC

PROCEDURE VOZPREG3TAST
   ON KEY LABEL F1    DO HELPN WITH 'VOZPREG3'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   VOZPREG3.RELEASE
ENDPROC
PROCEDURE VOZPREG4TAST
   ON KEY LABEL F1    DO HELPN WITH 'VOZPREG4'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   VOZPREG4.RELEASE
ENDPROC

PROCEDURE VOZGORTAST
   ON KEY LABEL F1    DO HELPN WITH 'VOZGOR'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   VOZGOR.RELEASE
ENDPROC


PROCEDURE VOZgor1TAST
   ON KEY LABEL F1    DO HELPN WITH 'VOZGOR1'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   VOZGOR1.RELEASE
ENDPROC


PROCEDURE AATP0TAST
ON KEY LABEL F1    DO HELPN WITH 'AATP0'
ON KEY LABEL ESC       AATP0.RELEASE
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ENDPROC


PROCEDURE PCEVTAST
   ON KEY LABEL F1    DO HELPN WITH 'PCEV'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL +     DO PCEVDOD
   ON KEY LABEL INS   DO PCEVDOD
   ON KEY LABEL F4    DO PCEVROBA
   ON KEY LABEL F5    DO KNJIZIPCEV
   ON KEY LABEL F6    DO PCEVTRAZI
   ON KEY LABEL F8    DO PCEVKARTROBA
   ON KEY LABEL F9    DO PCEVZAG
   ON KEY LABEL ALT+F3  DO PCEVSERV
   ON KEY LABEL ALT+F2  DO PCEVPREG
   ON KEY LABEL CTRL+F12  DO PCEVOTV
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PCEV.RELEASE
ENDPROC

PROCEDURE PCEVGTAST
   ON KEY LABEL F1    DO HELPN WITH 'PCEVG'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PCEVG.RELEASE
ENDPROC


PROCEDURE PCEVZAGTAST
   ON KEY LABEL F1    DO HELPN WITH 'PCEVZAG'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PCEVZAG.RELEASE
ENDPROC


PROCEDURE PCEVPREGTAST
   ON KEY LABEL F1    DO HELPN WITH 'PCEVPREG'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PCEVPREG.RELEASE
ENDPROC

PROCEDURE PCEVPREGTRTAST
   ON KEY LABEL F1    DO HELPN WITH 'PCEVPREGTR'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PCEVPREGTR.RELEASE
ENDPROC

PROCEDURE PCEVPREGPLACTAST
   ON KEY LABEL F1    DO HELPN WITH 'PCEVPREGPLAC'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PCEVPREGPLAC.RELEASE
ENDPROC

PROCEDURE PCEVSERVTAST
   ON KEY LABEL F1    DO HELPN WITH 'PCEVSERV'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PCEVSERV.RELEASE
ENDPROC

PROCEDURE PCEVBRISITAST
   ON KEY LABEL F1    DO HELPN WITH 'PCEVBRISI'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PCEVBRISI.RELEASE
ENDPROC

PROCEDURE PCEVKOPITAST
   ON KEY LABEL F1    DO HELPN WITH 'PCEVKOPI'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PCEVKOPI.RELEASE
ENDPROC


PROCEDURE PCVOZILATAST
   ON KEY LABEL F1    DO HELPN WITH 'PCVOZILA'
   ON KEY LABEL +     DO PCVOZILADOD
   ON KEY LABEL INS   DO PCVOZILADOD
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL F4    DO PCVOZILATRAZI
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PCVOZILA.RELEASE
ENDPROC

PROCEDURE PCVOZACITAST
   ON KEY LABEL F1    DO HELPN WITH 'PCVOZACI'
   ON KEY LABEL +     DO PCVOZACIDOD
   ON KEY LABEL INS   DO PCVOZACIDOD
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL F4    DO PCVOZACITRAZI
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PCVOZACI.RELEASE
ENDPROC

PROCEDURE PCDEF00TAST
   ON KEY LABEL F1    DO HELPN WITH 'PCDEF00'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PCDEF00.RELEASE
ENDPROC

PROCEDURE PCVOZACIKARTTAST
   ON KEY LABEL F1    DO HELPN WITH 'PCDVOZACIKART'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PCVOZACIKART.RELEASE
ENDPROC

PROCEDURE PCVOZILAKARTTAST
   ON KEY LABEL F1    DO HELPN WITH 'PCDVOZILAKART'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PCVOZILAKART.RELEASE
ENDPROC

PROCEDURE PCEVIZVTAST
   ON KEY LABEL F1    DO HELPN WITH 'PCEVIZV'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PCEVIZV.RELEASE
ENDPROC

PROCEDURE PCEVIZV2TAST
   ON KEY LABEL F1    DO HELPN WITH 'PCEVIZV2'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PCEVIZV2.RELEASE
ENDPROC

PROCEDURE PCEVPREUZMIPODTAST
   ON KEY LABEL F1    DO HELPN WITH 'PCEVPREUZMIPOD'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PCEVPREUZMIPOD.RELEASE
ENDPROC

PROCEDURE PCDEF000TAST
   ON KEY LABEL F1    DO HELPN WITH 'PCDEF000'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PCDEF000.RELEASE
ENDPROC

PROCEDURE PCEVTRAZITAST
   ON KEY LABEL F1    DO HELPN WITH 'PCEVTRAZI'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PCEVTRAZI.RELEASE
ENDPROC

PROCEDURE PCEVTRROBTAST
   ON KEY LABEL F1    DO HELPN WITH 'PCEVTRROB'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PCEVtrrob.RELEASE
ENDPROC

PROCEDURE PCEVTRKALTAST
   ON KEY LABEL F1    DO HELPN WITH 'PCEVTRKAL'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PCEVTRKAL.RELEASE
ENDPROC

PROCEDURE PCEVTRKTAST
   ON KEY LABEL F1    DO HELPN WITH 'PCEVTRK'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PCEVTRK.RELEASE
ENDPROC

PROCEDURE PCEVTRFIRTAST
   ON KEY LABEL F1    DO HELPN WITH 'PCEVTRFIR'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PCEVTRFIR.RELEASE
ENDPROC

PROCEDURE PCEVOPSTITRTAST
   ON KEY LABEL F1    DO HELPN WITH 'PCEVOPSTITR'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PCEVOPSTITR.RELEASE
ENDPROC

PROCEDURE PCEVPOCTAST
   ON KEY LABEL F1    DO HELPN WITH 'PCEVPOC'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PCEVPOC.RELEASE
ENDPROC


PROCEDURE OSPOPISTAST
   ON KEY LABEL F1    DO HELPN WITH 'OSPOPIS'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       OSPOPIS.RELEASE
ENDPROC


PROCEDURE OSPOPIS2TAST
   ON KEY LABEL F1    DO HELPN WITH 'OSPOPIS2'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       OSPOPIS2.RELEASE
ENDPROC


PROCEDURE OSPOPIS3TAST
   ON KEY LABEL F1    DO HELPN WITH 'OSPOPIS3'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       OSPOPIS3.RELEASE
ENDPROC


PROCEDURE OSAGTAST
   ON KEY LABEL F1    DO HELPN WITH 'OSAG'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       OSAG.RELEASE
ENDPROC


PROCEDURE OSAGPODTAST
   ON KEY LABEL F1    DO HELPN WITH 'OSAGPOD'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       OSAGPOD.RELEASE
ENDPROC


PROCEDURE KONTOTAST
   ON KEY LABEL F1    DO HELPN WITH 'KONTO'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL +         DO KONTODODAJ
   on key label INS       DO KONTODODAJ
   ON KEY LABEL ESC       KONTO.RELEASE
   ON KEY LABEL F3        DO KONDEONAZ
   ON KEY LABEL F7        DO KONTOK
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC








PROCEDURE VOZMAPATAST

ON KEY LABEL F1        DO HELPN WITH 'VOZMAPA'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL +         DO VOZMAPADODAJ
on key label INS       DO VOZMAPADODAJ
ON KEY LABEL ESC       VOZMAPA.RELEASE
on key label F4        DO VOZMAPAPART
ENDPROC

PROCEDURE VOZMAPAdnevTAST
ON KEY LABEL F1        DO HELPN WITH 'VOZMAPADNEV'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       VOZMAPADNEV.RELEASE
ENDPROC


PROCEDURE OS0KTAST
   ON KEY LABEL F1    DO HELPN WITH 'OS0K'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       OS0K.RELEASE
ENDPROC

PROCEDURE OSVRSTATAST
   ON KEY LABEL F1    DO HELPN WITH 'OSVRSTA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       OSVRSTA.RELEASE
ENDPROC

PROCEDURE OSOSNKTAST
   ON KEY LABEL F1    DO HELPN WITH 'OSOSNK'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       OSOSNK.RELEASE
ENDPROC

PROCEDURE OSIZVORFTAST
   ON KEY LABEL F1    DO HELPN WITH 'OSIZVORF'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       OSIZVORF.RELEASE
ENDPROC


PROCEDURE OSMESTATAST
   ON KEY LABEL F1    DO HELPN WITH 'OSMESTA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       OSMESTA.RELEASE
ENDPROC


PROCEDURE ROBATAST

ON KEY LABEL F1    DO HELPN WITH 'ROBA'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       ROBA.RELEASE
ON KEY LABEL +         DO ROBADOD
on key label INS       DO ROBADOD
ON KEY LABEL F3        DO ROBADEONAZ
ON KEY LABEL F4        DO ROBAF4
ON KEY LABEL F5        DO ROBApodnaz
ON KEY LABEL F6        DO ROBAF6
ON KEY LABEL F7        DO ROBAKARTF7
ON KEY LABEL F8        DO ROBAF4KARTICA
ON KEY LABEL F9        DO ROBABKOD
ON KEY LABEL F10       DO ROBABIRAM
ON KEY LABEL SHIFT+F1      DO ROBPREGCEN
ON KEY LABEL F12      DO ROBAGRID
ON KEY LABEL ALT+F9    DO ROBAAF9
ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC
ON KEY LABEL CTRL+F12  DO OTVROBA

ENDPROC



PROCEDURE ROBVRSTTAST

ON KEY LABEL F1    DO HELPN WITH 'ROBVRST'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       ROBVRSTA.RELEASE
ON KEY LABEL +         DO ROBVRSTDOD
on key label INS       DO ROBVRSTDOD
ON KEY LABEL F7        DO ROBVRSTKARTF7
ON KEY LABEL F10       DO ROBVRSTBIRAM
ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE ROBPROITAST

ON KEY LABEL F1    DO HELPN WITH 'ROBPROI'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       ROBPROI.RELEASE
ON KEY LABEL +         DO ROBPROIDOD
on key label INS       DO ROBPROIDOD
ON KEY LABEL F7        DO ROBPROIKARTF7
ON KEY LABEL F10       DO ROBPROIBIRAM
ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE ROBAPODNAZTAST
   ON KEY LABEL F1    DO HELPN WITH 'ROBAPODNAZ'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       ROBAPODNAZ.RELEASE
ENDPROC

PROCEDURE ROBA0PODNAZTAST
   ON KEY LABEL F1    DO HELPN WITH 'ROBA0PODNAZ'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       ROBA0PODNAZ.RELEASE
ENDPROC

PROCEDURE ROBAPODNAZHTMTAST
   ON KEY LABEL F1    DO HELPN WITH 'ROBAPODNAZHTM'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       ROBAPODNAZHTM.RELEASE
ENDPROC



PROCEDURE ROBA0GRUPATAST
   ON KEY LABEL F1    DO HELPN WITH 'ROBA0GRUPA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       ROBA0GRUPA.RELEASE
ENDPROC

PROCEDURE ROBAPRENTAST
   ON KEY LABEL F1    DO HELPN WITH 'ROBAPREN'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       ROBAPREN.RELEASE
ENDPROC

PROCEDURE ROBAPROTAST
   ON KEY LABEL F1    DO HELPN WITH 'ROBAPRO'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       ROBAPRO.RELEASE
ENDPROC


PROCEDURE TVUNKOLTAST
   ON KEY LABEL F1    DO HELPN WITH 'TVUNKOL'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       TVUNKOL.RELEASE
ENDPROC


PROCEDURE KALPRNKARTTAST
ON KEY LABEL F1    DO HELPN WITH 'KALPRNKART'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       KALPRNKART.RELEASE
ENDPROC


PROCEDURE KALPRNTAST
ON KEY LABEL F1    DO HELPN WITH 'KALPRN'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       KALPRN.RELEASE
ON KEY LABEL +         DO KALPRNDOD
on key label INS       DO KALPRNDOD
on key label F7        DO KALPRNKART
ON KEY LABEL SHIFT+F10 DO KALPRNBRISI
ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC
ON KEY LABEL CTRL+F12  DO KALPRNOTVORI
ENDPROC



PROCEDURE OSPRENOSZUPTAST
   ON KEY LABEL F1    DO HELPN WITH 'OSPRENOSZUP'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       OSPRENOSZUP.RELEASE
ENDPROC


PROCEDURE OSPOPIS2PTAST
   ON KEY LABEL F1    DO HELPN WITH 'OSPOPIS2P'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       OSPOPIS2P.RELEASE
ENDPROC

PROCEDURE OSPOPIS31TAST
   ON KEY LABEL F1    DO HELPN WITH 'OSPOPIS31'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       OSPOPIS31.RELEASE
ENDPROC

PROCEDURE OSPOPIS4TAST
   ON KEY LABEL F1    DO HELPN WITH 'OSPOPIS4'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       OSPOPIS4.RELEASE
ENDPROC



PROCEDURE ROBAK2TAST
   ON KEY LABEL F1    DO HELPN WITH 'ROBAK2'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       ROBAK2.RELEASE
ENDPROC


PROCEDURE ROBVRSTKTAST
ON KEY LABEL F1    DO HELPN WITH 'ROBVRSTK'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       ROBVRSTK.RELEASE
ENDPROC

PROCEDURE ROBPROIKTAST
ON KEY LABEL F1    DO HELPN WITH 'ROBPROIK'
   ON KEY LABEL F2        ! /N CALC.EXE
   
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       ROBPROIK.RELEASE
ENDPROC


PROCEDURE ROBAbkodTAST
   ON KEY LABEL F1    DO HELPN WITH 'ROBABKOD'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       ROBAbkod.RELEASE
ENDPROC

PROCEDURE ROBADEONAZTAST
   ON KEY LABEL F1    DO HELPN WITH 'ROBADEONAZ'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       ROBADEONAZ.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE KONTOKTAST
   ON KEY LABEL F1    DO HELPN WITH 'KONTOK'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   KONTOK.RELEASE
ENDPROC


PROCEDURE KKONDEONAZTAST
   ON KEY LABEL F1    DO HELPN WITH 'KONDEONAZ'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       KONDEONAZ.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE ROBPREGCENTAST
   ON KEY LABEL F1    DO HELPN WITH 'ROBPREGCEN'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       ROBPREGCEN.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE ROBVRSTATAST
   ON KEY LABEL F1    DO HELPN WITH 'ROBVRSTA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       ROBVRSTA.RELEASE
ENDPROC


PROCEDURE PORUKAUTAST
   ON KEY LABEL F1    DO HELPN WITH 'PORUKAU'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PORUKAU.RELEASE
ENDPROC


PROCEDURE TMpDATTRAZITAST
   ON KEY LABEL F1    DO HELPN WITH 'TMPDATTRAZI'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       TMpDATTRAZI.RELEASE
ENDPROC

PROCEDURE TMp0DATTRAZITAST
   ON KEY LABEL F1    DO HELPN WITH 'TMP0DATTRAZI'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       TMp0DATTRAZI.RELEASE
ENDPROC

PROCEDURE TMp0NALTRAZITAST
   ON KEY LABEL F1    DO HELPN WITH 'TMP0NALTRAZI'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       TMp0NALTRAZI.RELEASE
ENDPROC


PROCEDURE TMP0TAST
   ON KEY LABEL F1    DO HELPN WITH 'TMP0'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   TMP0.RELEASE
   ON KEY LABEL +     DO TMP0DODAJ
   on key label INS   DO TMP0DODAJ
   ON KEY LABEL F6    DO TMP0dattrazi
   ON KEY LABEL F7    DO TMP0ZBIR
   ON KEY LABEL F8    DO TMPF8 
   ON KEY LABEL F9    DO TMP0NALTRAZI   
   ON KEY LABEL SHIFT+F10 DO TMP0BRISI
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
   ON KEY LABEL CTRL+F12 DO TMP0OTVORI
ENDPROC


PROCEDURE TMPPRENTAST
   ON KEY LABEL F1    DO HELPN WITH 'TMPPREN'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   TMPPREN.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC


PROCEDURE TMP1TAST
   ON KEY LABEL F1    DO HELPN WITH 'TMP1'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   TMP1.RELEASE
ENDPROC

PROCEDURE TMP2TAST
   ON KEY LABEL F1    DO HELPN WITH 'TMP2'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   TMP2.RELEASE
ENDPROC

PROCEDURE TMP3TAST
   ON KEY LABEL F1    DO HELPN WITH 'TMP3'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   TMP3.RELEASE
ENDPROC

PROCEDURE TMP3TAST
   ON KEY LABEL F1    DO HELPN WITH 'TMP3'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   TMP3.RELEASE
ENDPROC

PROCEDURE TMP03TAST
   ON KEY LABEL F1    DO HELPN WITH 'TMP03'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   TMP03.RELEASE
ENDPROC

PROCEDURE TMP0PRENOSTAST
   ON KEY LABEL F1    DO HELPN WITH 'TMP0PRENOS'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       TMP0PRENOS.RELEASE
ENDPROC

PROCEDURE TMPKTAST
   ON KEY LABEL F1    DO HELPN WITH 'TMPK'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   TMPK.RELEASE
ENDPROC


PROCEDURE KPOTAST
ON KEY LABEL F1        DO HELPN WITH 'KPO'
ON KEY LABEL ESC       KPO.RELEASE
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL CTRL+F12  DO KPOOTV
ON KEY LABEL F10       DO KPOF10
ON KEY LABEL SHIFT+F1  DO KPOSF1
ENDPROC

PROCEDURE KPO03TAST
ON KEY LABEL F1    DO HELPN WITH 'KPO03'
ON KEY LABEL ESC       KPO03.RELEASE
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ENDPROC


PROCEDURE KPO01TAST
ON KEY LABEL F1    DO HELPN WITH 'KPO01'
ON KEY LABEL ESC       KPO01.RELEASE
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ENDPROC

PROCEDURE AAPREUZPODTAST
   ON KEY LABEL F1    DO HELPN WITH 'AAPREUZPOD'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       AAPREUZPOD.RELEASE
ENDPROC

PROCEDURE DELOVTAST
ON KEY LABEL F1    DO HELPN WITH 'DELOV'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       DELOV.RELEASE
ON KEY LABEL +         DO DELOVDOD
on key label INS       DO DELOVDOD
ON KEY LABEL F7        DO DELOVKART
ON KEY LABEL CTRL+F12  DO OTVDELOV
ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC


PROCEDURE DELOVKARTTAST
ON KEY LABEL F1    DO HELPN WITH 'DELOVKART'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       DELOVKART.RELEASE
ENDPROC

PROCEDURE DELVRSTATAST
   ON KEY LABEL F1    DO HELPN WITH 'DELVRSTA'
   ON KEY LABEL +     DO DELVRSTADOD
   ON KEY LABEL INS   DO DELVRSTADOD
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL F4    DO DELVRSTATRAZI
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       DELVRSTA.RELEASE
ENDPROC

PROCEDURE DELVRSTAKARTTAST
   ON KEY LABEL F1    DO HELPN WITH 'DELVRSTAKART'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       DELVRSTAKART.RELEASE
ENDPROC

PROCEDURE DELDOKTAST
   ON KEY LABEL F1    DO HELPN WITH 'DELDOK'
   ON KEY LABEL +     DO DELDOKDOD
   ON KEY LABEL INS   DO DELDOKDOD
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL F4    DO DELDOKTRAZI
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       DELDOK.RELEASE
ENDPROC

PROCEDURE DELDOKKARTTAST
   ON KEY LABEL F1    DO HELPN WITH 'DELDOKKART'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       DELDOKKART.RELEASE
ENDPROC

PROCEDURE DELLOKACTAST
   ON KEY LABEL F1    DO HELPN WITH 'DELLOKAC'
   ON KEY LABEL +     DO DELLOKACDOD
   ON KEY LABEL INS   DO DELLOKACDOD
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL F4    DO DELLOKACTRAZI
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       DELLOKAC.RELEASE
ENDPROC

PROCEDURE DELLOKACKARTTAST
   ON KEY LABEL F1    DO HELPN WITH 'DELLOKACKART'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       DELLOKACKART.RELEASE
ENDPROC

PROCEDURE DELSTATTAST
   ON KEY LABEL F1    DO HELPN WITH 'DELSTAT'
   ON KEY LABEL +     DO DELSTATDOD
   ON KEY LABEL INS   DO DELSTATDOD
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL F4    DO DELSTATTRAZI
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       DELSTAT.RELEASE
ENDPROC

PROCEDURE DELSTATKARTTAST
   ON KEY LABEL F1    DO HELPN WITH 'DELSTATKART'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       DELSTATKART.RELEASE
ENDPROC

PROCEDURE DELORGANTAST
   ON KEY LABEL F1    DO HELPN WITH 'DELORGAN'
   ON KEY LABEL +     DO DELORGANDOD
   ON KEY LABEL INS   DO DELORGANDOD
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL F4    DO DELORGANTRAZI
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       DELORGAN.RELEASE
ENDPROC

PROCEDURE DELORGANKARTTAST
   ON KEY LABEL F1    DO HELPN WITH 'DELORGANKART'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       DELORGANKART.RELEASE
ENDPROC

PROCEDURE DELOVPREGLEDTAST
   ON KEY LABEL F1    DO HELPN WITH 'DELOVPREGLED'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       DELOVPREGLED.RELEASE
ENDPROC


PROCEDURE DELPRIMTAST
   ON KEY LABEL F1    DO HELPN WITH 'DELPRIM'
   ON KEY LABEL +     DO DELPRIMDOD
   ON KEY LABEL INS   DO DELPRIMDOD
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL F4    DO DELPRIMTRAZI
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       DELPRIM.RELEASE
ENDPROC

PROCEDURE DELPRIMKARTTAST
   ON KEY LABEL F1    DO HELPN WITH 'DELPRIMKART'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       DELPRIMKART.RELEASE
ENDPROC

PROCEDURE VIRMTAST
   ON KEY LABEL F1    DO HELPN WITH 'VIRM'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   VIRM.RELEASE
ENDPROC

PROCEDURE VIRM0TAST
   ON KEY LABEL F1    DO HELPN WITH 'VIRM0'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   VIRM0.RELEASE
ENDPROC

PROCEDURE VIRM0ETAST
   ON KEY LABEL F1    DO HELPN WITH 'VIRM0E'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   VIRM0E.RELEASE
ENDPROC


PROCEDURE VIRMITAST
   ON KEY LABEL F1    DO HELPN WITH 'VIRMI'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   VIRMI.RELEASE
ENDPROC

PROCEDURE VSIFRAPLTAST
   ON KEY LABEL F1    DO HELPN WITH 'VSIFRAPL'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VSIFRAPL.RELEASE
ENDPROC




PROCEDURE CEKOVITAST
   ON KEY LABEL F1        DO HELPN WITH 'CEKOVI'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL +         DO CEKDOD
   on key label INS       DO CEKDOD
   ON KEY LABEL ESC       CEKOVI.RELEASE
   ON KEY LABEL F4        DO CEKPART


ENDPROC

PROCEDURE IMENIKTAST
   ON KEY LABEL F1    DO HELPN WITH 'IMENIK'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   IMENIK.RELEASE
ENDPROC
PROCEDURE IMENIKKTAST
   ON KEY LABEL F1    DO HELPN WITH 'IMENIKK'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   IMENIKK.RELEASE
ENDPROC

PROCEDURE IMENPORTAST
   ON KEY LABEL F1    DO HELPN WITH 'IMENPOR'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   IMENPOR.RELEASE
ENDPROC

PROCEDURE VIRM1TAST
   ON KEY LABEL F1    DO HELPN WITH 'VIRM1'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   VIRM1.RELEASE
ENDPROC

PROCEDURE VIRMTRSIFTAST
   ON KEY LABEL F1    DO HELPN WITH 'VIRMTRSIF'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VIRMTRSIF.RELEASE
ENDPROC

PROCEDURE VIRMTRNAZRACTAST
   ON KEY LABEL F1    DO HELPN WITH 'VIRMTRNAZRAC'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VIRMTRNAZRAC.RELEASE
ENDPROC

PROCEDURE PCEVPREUZMIEKSTTAST
   ON KEY LABEL F1    DO HELPN WITH 'PCEVPREUZMIEKST'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PCEVPREUZMIEKST.RELEASE
ENDPROC

PROCEDURE PCEVsredisifTAST
   ON KEY LABEL F1    DO HELPN WITH 'PCEVSREDISIF'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PCEVSREDISIF.RELEASE
ENDPROC

PROCEDURE PCEVsrediprenosrTAST
   ON KEY LABEL F1    DO HELPN WITH 'PCEVSREDIPRENOSR'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PCEVSREDIPRENOSR.RELEASE
ENDPROC

PROCEDURE PCEVGKTAST
   ON KEY LABEL F1    DO HELPN WITH 'PCEVGK'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PCEVGK.RELEASE
ENDPROC

PROCEDURE PCEVGKPTAST
   ON KEY LABEL F1    DO HELPN WITH 'PCEVGKP'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PCEVGKP.RELEASE
ENDPROC

PROCEDURE PCEVGKP2TAST
   ON KEY LABEL F1    DO HELPN WITH 'PCEVGKP2'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PCEVGKP2.RELEASE
ENDPROC

PROCEDURE ZAMENALOKALTAST
   ON KEY LABEL F1    DO HELPN WITH 'ZAMENALOKAL'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       ZAMENALOKAL.RELEASE
ENDPROC

PROCEDURE TABLEHEDERTAST
   ON KEY LABEL F1    DO HELPN WITH 'TABLEHEDER'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       TABLEHEDER.RELEASE
ENDPROC

PROCEDURE ZAMENASVEOTAST
   ON KEY LABEL F1    DO HELPN WITH 'ZAMENASVEO'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       ZAMENASVEO.RELEASE
ENDPROC

PROCEDURE TMP0SALDOTAST
   ON KEY LABEL F1    DO HELPN WITH 'TMP0SALDO'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   TMP0SALDO.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC


PROCEDURE TMP1SALDOTAST
   ON KEY LABEL F1    DO HELPN WITH 'TMP1SALDO'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   TMP1SALDO.RELEASE
ENDPROC


PROCEDURE rec0rezpregledtast
   ON KEY LABEL F1    DO HELPN WITH 'rec0rezpregled'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   rec0rezpregled.RELEASE
ENDPROC

PROCEDURE recrez1tast
   ON KEY LABEL F1    DO HELPN WITH 'recrez1'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   recrez1.RELEASE
ENDPROC


PROCEDURE RECBRISIR1TAST
   ON KEY LABEL F1    DO HELPN WITH 'RECBRISIR1'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       RECBRISIR1.RELEASE
ENDPROC


PROCEDURE OBROKTAST
 *  ON KEY LABEL F1    DO HELPN WITH 'OBRPB1'
   ON KEY LABEL F2        ! /N CALC.EXE
 *  ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   OBROK.RELEASE
ENDPROC

PROCEDURE OBRPB1A1TAST
 *  ON KEY LABEL F1    DO HELPN WITH 'OBRPB1A'
   ON KEY LABEL F2        ! /N CALC.EXE
 *  ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   OBRPB1A1.RELEASE
ENDPROC
PROCEDURE OBRPPDG1STAST
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   OBRPPDG1S.RELEASE
ENDPROC

PROCEDURE OBRPPDG1S2TAST
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   OBRPPDG1S2.RELEASE
ENDPROC

PROCEDURE OBRPPDG1S3TAST
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   OBRPPDG1S3.RELEASE
ENDPROC

PROCEDURE ZAMENASVEOKOMTAST
   ON KEY LABEL F1    DO HELPN WITH 'ZAMENASVEOKOM'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       ZAMENASVEOKOM.RELEASE
ENDPROC

PROCEDURE OBRPDP14TAST
   ON KEY LABEL F1    DO HELPN WITH 'OBRPDP14'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       OBRPDP14.RELEASE
ENDPROC
PROCEDURE OBRPDP14NAPTAST
   ON KEY LABEL F1    DO HELPN WITH 'OBRPDP14NAP'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       OBRPDP14NAP.RELEASE
ENDPROC