PROCEDURE KL0TAST
   ON KEY LABEL F1    DO HELPN WITH 'KL0'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       KL0.RELEASE
ENDPROC

PROCEDURE KLZAPTAST
   ON KEY LABEL F1    DO HELPN WITH 'KLZAP'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       KLZAP.RELEASE
   ON KEY LABEL +         DO KLZAPDODAJ
   ON KEY LABEL INS       DO KLZAPDODAJ
   ON KEY LABEL F4        DO KLZAPF4
   ON KEY LABEL F7        DO KLZAPF7
   ON KEY LABEL F8        DO KLZAPF8
   ON KEY LABEL F9        DO KLZAPF9
   
ENDPROC

PROCEDURE KLPROTAST
   ON KEY LABEL F1    DO HELPN WITH 'KLPRO'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       KLPRO.RELEASE
   ON KEY LABEL +         DO KLPRODODAJ
   ON KEY LABEL INS       DO KLPRODODAJ
   ON KEY LABEL F4        DO KLPROF4
ENDPROC

PROCEDURE KLPRO0TAST
   ON KEY LABEL F1    DO HELPN WITH 'KLPRO0'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       KLPRO0.RELEASE
ENDPROC

PROCEDURE KLSTOTAST
   ON KEY LABEL F1    DO HELPN WITH 'KLSTO'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL +         DO KLSTODOD
   ON KEY LABEL INS       DO KLSTODOD
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       KLSTO.RELEASE
ENDPROC

PROCEDURE KLZAPSALDOTAST
   ON KEY LABEL F1    DO HELPN WITH 'KLZAPSALDO'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       KLZAPSALDO.RELEASE
ENDPROC

PROCEDURE KLZAPSALDO2TAST
   ON KEY LABEL F1    DO HELPN WITH 'KLZAPSALDO2'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       KLZAPSALDO2.RELEASE
ENDPROC

PROCEDURE PROPOLUTAST

ON KEY LABEL F1    DO HELPN WITH 'PROPOLU'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       PROPOLU.RELEASE
ON KEY LABEL +         DO PROPOLUDOD
on key label INS       DO PROPOLUDOD
ON KEY LABEL F7        DO PROPOLUKARTF7
ON KEY LABEL F10       DO PROPOLUBIRAM
ON KEY LABEL SHIFT+F2      DO ROBA00GLAVNI WITH 'POLU'
ON KEY LABEL F4        PROPOLU.TXTTRAZI.SETFOCUS

ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC

ENDPROC
PROCEDURE PROPOLUPTAST

ON KEY LABEL F1    DO HELPN WITH 'PROPOLUP'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       PROPOLUP.RELEASE
ON KEY LABEL +         DO PROPOLUDODP
on key label INS       DO PROPOLUDODP
ON KEY LABEL F7        DO PROPOLUKARTF7
ON KEY LABEL F10       DO PROPOLUBIRAMP
ON KEY LABEL F4        DO PROPOLUF4

ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC

ENDPROC

PROCEDURE PROMATTAST

ON KEY LABEL F1    DO HELPN WITH 'PROMAT'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       PROMAT.RELEASE
ON KEY LABEL +         DO PROMATDOD
on key label INS       DO PROMATDOD
ON KEY LABEL F7        DO PROMATKARTF7
ON KEY LABEL F10       DO PROMATBIRAM
ON KEY LABEL F4        DO PROMATF4
ON KEY LABEL F3        DO PROMATDEONAZ
ON KEY LABEL SHIFT+F2      DO ROBA00GLAVNI WITH 'OMAT'
ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC

ENDPROC


PROCEDURE PROMATPTAST

ON KEY LABEL F1    DO HELPN WITH 'PROMATP'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       PROMATP.RELEASE
ON KEY LABEL +         DO PROMATDODP
on key label INS       DO PROMATDODP
ON KEY LABEL F7        DO PROMATKARTF7P
ON KEY LABEL F10       DO PROMATBIRAMP
ON KEY LABEL F4        DO PROPMATF4

ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC

ENDPROC



PROCEDURE PROAMBTAST

ON KEY LABEL F1    DO HELPN WITH 'PROAMB'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       PROAMB.RELEASE
ON KEY LABEL +         DO PROAMBDOD
on key label INS       DO PROAMBDOD
ON KEY LABEL F7        DO PROAMBF7
ON KEY LABEL F10       DO PROAMBBIRAM
ON KEY LABEL F4        DO PROAMBF4
ON KEY LABEL SHIFT+F2      DO ROBA00GLAVNI WITH 'AMBA'
ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC

ENDPROC

PROCEDURE PROAMBPTAST

ON KEY LABEL F1    DO HELPN WITH 'PROAMBP'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       PROAMBP.RELEASE
ON KEY LABEL +         DO PROAMBDODP
on key label INS       DO PROAMBDODP
ON KEY LABEL F7        DO PROAMBF7
ON KEY LABEL F10       DO PROAMBBIRAMP
ON KEY LABEL F4        PROAMBP.TXTTRAZI.SETFOCUS
ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC

ENDPROC



PROCEDURE PROPMATTAST

ON KEY LABEL F1    DO HELPN WITH 'PROPMAT'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       PROPMAT.RELEASE
ON KEY LABEL +         DO PROPMATDOD
on key label INS       DO PROPMATDOD
ON KEY LABEL F7        DO PROPMATF7
ON KEY LABEL F10       DO PROPMATBIRAM
ON KEY LABEL F4        PROPMAT.TXTTRAZI.SETFOCUS
ON KEY LABEL SHIFT+F2      DO ROBA00GLAVNI WITH 'PMAT'
ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC

ENDPROC

PROCEDURE PROPMATPTAST

ON KEY LABEL F1    DO HELPN WITH 'PROPMATP'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       PROPMATP.RELEASE
ON KEY LABEL +         DO PROPMATDODP
on key label INS       DO PROPMATDODP
ON KEY LABEL F7        DO PROPMATF7
ON KEY LABEL F10       DO PROPMATBIRAMP
ON KEY LABEL F4        PROPMATP.TXTTRAZI.SETFOCUS

ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC

ENDPROC


PROCEDURE PRORADTAST

ON KEY LABEL F1    DO HELPN WITH 'PRORAD'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       PRORAD.RELEASE
ON KEY LABEL +         DO PRORADDOD
on key label INS       DO PRORADDOD
ON KEY LABEL F7        DO PRORADF7
ON KEY LABEL F10       DO PRORADBIRAM
ON KEY LABEL F4        PRORAD.TXTTRAZI.SETFOCUS

ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC

ENDPROC

PROCEDURE PRORAD2TAST

ON KEY LABEL F1    DO HELPN WITH 'PRORAD2'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       PRORAD2.RELEASE
ON KEY LABEL +         DO PRORADDOD2
on key label INS       DO PRORADDOD2
ON KEY LABEL F7        DO PRORADF7
ON KEY LABEL F4        PRORAD2.TXTTRAZI.SETFOCUS

ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC

ENDPROC

PROCEDURE PRORAD0TAST

ON KEY LABEL F1    DO HELPN WITH 'PRORAD0'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       PRORAD0.RELEASE
ON KEY LABEL +         DO PRORADDOD0
on key label INS       DO PRORADDOD0
ON KEY LABEL F7        DO PRORADF7
ON KEY LABEL F4        PRORAD0.TXTTRAZI.SETFOCUS
ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE PRORADPTAST

ON KEY LABEL F1    DO HELPN WITH 'PRORADP'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       PRORADP.RELEASE
ON KEY LABEL +         DO PRORADDODP
on key label INS       DO PRORADDODP
ON KEY LABEL F7        DO PRORADF7
ON KEY LABEL F10       DO PRORADBIRAMP
ON KEY LABEL F4        PRORADP.TXTTRAZI.SETFOCUS

ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC

ENDPROC



PROCEDURE PRODIRTAST

ON KEY LABEL F1    DO HELPN WITH 'PRODIR'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       PRODIR.RELEASE
ON KEY LABEL +         DO PRODIRDOD
on key label INS       DO PRODIRDOD
ON KEY LABEL F7        DO PRODIRF7
ON KEY LABEL F10       DO PRODIRBIRAM
ON KEY LABEL F4        PRODIR.TXTTRAZI.SETFOCUS

ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC

ENDPROC

PROCEDURE PRODIRPTAST

ON KEY LABEL F1    DO HELPN WITH 'PRODIRP'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       PRODIRP.RELEASE
ON KEY LABEL +         DO PRODIRDODP
on key label INS       DO PRODIRDODP
ON KEY LABEL F7        DO PRODIRF7
ON KEY LABEL F10       DO PRODIRBIRAMP
ON KEY LABEL F4        PRODIRP.TXTTRAZI.SETFOCUS

ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC

ENDPROC



PROCEDURE PROOPSTAST

ON KEY LABEL F1    DO HELPN WITH 'PROOPS'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       PROOPS.RELEASE
ON KEY LABEL +         DO PROOPSDOD
on key label INS       DO PROOPSDOD
ON KEY LABEL F7        DO PROOPSKARTF7
ON KEY LABEL F10       DO PROOPSBIRAM
ON KEY LABEL F4        PROOPS.TXTTRAZI.SETFOCUS

ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC

ENDPROC

PROCEDURE PROOPSPTAST

ON KEY LABEL F1    DO HELPN WITH 'PROOPSP'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       PROOPSP.RELEASE
ON KEY LABEL +         DO PROOPSDODP
on key label INS       DO PROOPSDODP
ON KEY LABEL F7        DO PROOPSKARTF7
ON KEY LABEL F10       DO PROOPSBIRAMP
ON KEY LABEL F4        PROOPSP.TXTTRAZI.SETFOCUS

ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC

ENDPROC

PROCEDURE PROPARTAST
   ON KEY LABEL F1    DO HELPN WITH 'PROPAR'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PROPAR.RELEASE
ENDPROC

PROCEDURE PRONALITAST
   ON KEY LABEL F1    DO HELPN WITH 'PRONALI'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PRONALI.RELEASE
ENDPROC

PROCEDURE PRONORMATAST
   ON KEY LABEL F1    DO HELPN WITH 'PRONORMA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PRONORMA.RELEASE
   ON KEY LABEL +         DO PRONORMADOD
   on key label INS       DO PRONORMADOD 
   ON KEY LABEL F5   DO PRONORMAF5
   ON KEY LABEL F6   DO PRONORTRAZI
   ON KEY LABEL F10   DO PRONORMAF10
   ON KEY LABEL SHIFT+F1   DO PRONORMASF1
   ON KEY LABEL SHIFT+F2   DO PRONORMASF2
   ON KEY LABEL SHIFT+F3   DO PRONORMASF3
   ON KEY LABEL SHIFT+F4   DO PRONORMASF4
   ON KEY LABEL SHIFT+F5   DO PRONORMASF5
   ON KEY LABEL SHIFT+F6   DO PRONORMASF6
   ON KEY LABEL SHIFT+F7   DO PRONORMASF7
   ON KEY LABEL SHIFT+F8   DO PRONORMASF8
ENDPROC

PROCEDURE PRONORMAPTAST
   ON KEY LABEL F1    DO HELPN WITH 'PRONORMAP'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL +         DO PRONORMApDOdaj
   on key label INS       DO PRONORMApDODaj 
   ON KEY LABEL ESC   PRONORMAP.RELEASE
   ON KEY LABEL F10   DO PRONORMAPF10
   ON KEY LABEL SHIFT+F2   DO PRONORMAPSF2
   ON KEY LABEL SHIFT+F3   DO PRONORMAPSF3
   ON KEY LABEL SHIFT+F4   DO PRONORMAPSF4
   ON KEY LABEL SHIFT+F5   DO PRONORMAPSF5
   ON KEY LABEL SHIFT+F6   DO PRONORMAPSF6
   ON KEY LABEL SHIFT+F7   DO PRONORMAPSF7
   ON KEY LABEL SHIFT+F8   DO PRONORMAPSF8   
ENDPROC

PROCEDURE PRONORMAF5TAST
   ON KEY LABEL F1    DO HELPN WITH 'PRONORMAF5'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PRONORMAF5.RELEASE
ENDPROC

PROCEDURE PRONORATAST
   ON KEY LABEL F1    DO HELPN WITH 'PRONORA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PRONORA.RELEASE
ENDPROC

PROCEDURE PROMATKTAST
   ON KEY LABEL F1    DO HELPN WITH 'PROMATK'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PROMATK.RELEASE
ENDPROC

PROCEDURE PROMATKPTAST
   ON KEY LABEL F1    DO HELPN WITH 'PROMATKP'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PROMATKP.RELEASE
ENDPROC

PROCEDURE PROPMATKTAST
   ON KEY LABEL F1    DO HELPN WITH 'PROPMATK'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PROPMATK.RELEASE
ENDPROC

PROCEDURE PROAMBKTAST
   ON KEY LABEL F1    DO HELPN WITH 'PROAMBK'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PROAMBK.RELEASE
ENDPROC

PROCEDURE PRORADKTAST
   ON KEY LABEL F1    DO HELPN WITH 'PRORADK'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PRORADK.RELEASE
ENDPROC

PROCEDURE PRODIRKTAST
   ON KEY LABEL F1    DO HELPN WITH 'PRODIRK'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PRODIRK.RELEASE
ENDPROC

PROCEDURE PROOPSKTAST
   ON KEY LABEL F1    DO HELPN WITH 'PROOPSK'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PROOPSK.RELEASE
ENDPROC



PROCEDURE PRONALTAST
   ON KEY LABEL F1    DO HELPN WITH 'PRONAL'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL +     DO PRONALDOD
   ON KEY LABEL ESC   PRONAL.RELEASE
   ON KEY LABEL CTRL+F12 DO PRONALOTV
   ON KEY LABEL F4       DO PROROBA
   ON KEY LABEL F6       DO PRONALTRAZI
   ON KEY LABEL F10      DO PRONAL01
ENDPROC


PROCEDURE PRONALPTAST
   ON KEY LABEL F1    DO HELPN WITH 'PRONALP'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PRONALP.RELEASE
   ON KEY LABEL CTRL+F12 DO PRONALOTV
ENDPROC

PROCEDURE PRONALIPTAST
   ON KEY LABEL F1    DO HELPN WITH 'PRONALIP'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PRONALIP.RELEASE
ENDPROC

PROCEDURE PROZAHTAST
   ON KEY LABEL F1    DO HELPN WITH 'PROZAH'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL +     DO PROZAHDOD
   ON KEY LABEL INS   DO PROZAHDOD
   ON KEY LABEL ESC   PROZAH.RELEASE
ENDPROC

PROCEDURE PROZAHZAGTAST
   ON KEY LABEL F1    DO HELPN WITH 'PROZAHZAG'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PROZAHZAG.RELEASE
ENDPROC


PROCEDURE mlekoTAST

ON KEY LABEL F1        DO HELPN WITH 'MLEKO'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL +         DO mlDOD
on key label INS       DO mldOD
ON KEY LABEL ESC       mleko.RELEASE
on key label F4        DO mlpart
ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC


ENDPROC


PROCEDURE mlekorTAST

ON KEY LABEL F1        DO HELPN WITH 'MLEKOR'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL +         DO mlDODR
on key label INS       DO mldODR
ON KEY LABEL ESC       mlekoR.RELEASE
ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC

ENDPROC

PROCEDURE mlekor01TAST

ON KEY LABEL F1        DO HELPN WITH 'MLEKOR01'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       mlekoR01.RELEASE
ENDPROC

PROCEDURE mlekor02TAST

ON KEY LABEL F1        DO HELPN WITH 'MLEKOR02'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       mlekoR02.RELEASE
ENDPROC


PROCEDURE mlekoSPISKOVITAST
   ON KEY LABEL F1        DO HELPN WITH 'MLEKOSPISKOVI'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       mlekoSPISKOVI.RELEASE
ENDPROC


PROCEDURE ml0TAST

ON KEY LABEL F1    DO HELPN WITH 'ML0'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       ml0.RELEASE
ON KEY LABEL +         DO ml0DOD
on key label INS       DO ml0DOD
ON KEY LABEL F4        DO ml0TRAZI
*ON KEY LABEL F6        FAN0.TXTF6.SETFOCUS       
ON KEY LABEL F7        DO ml0KART
ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC

ENDPROC

PROCEDURE MLCENETAST
ON KEY LABEL F1        DO HELPN WITH 'MLCENE'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL +         DO mlCENEDOD
on key label INS       DO mlCENEDOD
ON KEY LABEL ESC       MLCENE.RELEASE
ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC



PROCEDURE PRONALSLAGTAST
   ON KEY LABEL F1    DO HELPN WITH 'PRONALSLAG'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PRONALSLAG.RELEASE
ENDPROC



PROCEDURE PRONALSLAGGOTTAST
   ON KEY LABEL F1    DO HELPN WITH 'PRONALSLAGGOT'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PRONALSLAGGOT.RELEASE
ENDPROC



PROCEDURE NCALCTAST
ON KEY LABEL F1    DO HELPN WITH 'NCALC'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL INS       DO NCALCDOD
ON KEY LABEL F7        DO NCALCF7
ON KEY LABEL F8        DO NCALCF8
ON KEY LABEL ESC       NCALC.RELEASE
ENDPROC


PROCEDURE PROCKTAST
ON KEY LABEL F1    DO HELPN WITH 'PROCK'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       PROCK.RELEASE
ENDPROC

PROCEDURE PROCK0TAST
ON KEY LABEL F1    DO HELPN WITH 'PROCK0'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       PROCK0.RELEASE
ENDPROC

PROCEDURE PROCKTRTAST
ON KEY LABEL F1    DO HELPN WITH 'PROCKTR'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       PROCKTR.RELEASE
ENDPROC

PROCEDURE PROPLANTAST
ON KEY LABEL F1    DO HELPN WITH 'PROPLAN'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       PROPLAN.RELEASE
ON KEY LABEL F4       DO PROPLANROBA

ENDPROC

PROCEDURE PRONALVTAST
   ON KEY LABEL F1    DO HELPN WITH 'PRONALV'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL +          DO PRONALVDOD
   ON KEY LABEL INS        DO PRONALVDOD
   ON KEY LABEL F4         DO PRONALVRAD
   ON KEY LABEL F5         DO PRONALVCCENA
   ON KEY LABEL F7         DO PRONALVPRERAC
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC        PRONALV.RELEASE
ENDPROC

PROCEDURE PRONALVCTAST
   ON KEY LABEL F1    DO HELPN WITH 'PRONALVC'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL +          DO PRONALVCDOD
   ON KEY LABEL INS        DO PRONALVCDOD
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC        PRONALVC.RELEASE
ENDPROC


PROCEDURE PRONALVRADTAST
ON KEY LABEL F1    DO HELPN WITH 'PRONALVRAD'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       PRONALVRAD.RELEASE
ENDPROC

PROCEDURE PRONALVIZVTAST
ON KEY LABEL F1    DO HELPN WITH 'PRONALVIZV'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       PRONALVIZV.RELEASE
ENDPROC


PROCEDURE PRONALMTAST
   ON KEY LABEL F1    DO HELPN WITH 'PRONALM'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL +          DO PRONALMDOD
   ON KEY LABEL INS        DO PRONALMDOD
   ON KEY LABEL F4         DO PRONALM0
   ON KEY LABEL F7         DO PRONALMPRERAC
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC        PRONALM.RELEASE
ENDPROC

PROCEDURE PRONALM0TAST
ON KEY LABEL F1    DO HELPN WITH 'PRONALM0'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL +          DO PRONALM0DOD
ON KEY LABEL INS        DO PRONALM0DOD
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       PRONALM0.RELEASE
ENDPROC

PROCEDURE PRONALMIZVTAST
ON KEY LABEL F1    DO HELPN WITH 'PRONALMIZV'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       PRONALMIZV.RELEASE
ENDPROC


PROCEDURE AAPROIZVODNJATAST
   ON KEY LABEL F1    DO HELPN WITH 'AAPROIZVODNJA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   AAPROIZVODNJA.RELEASE
ENDPROC


PROCEDURE PROKNJIZITAST
   ON KEY LABEL F1    DO HELPN WITH 'PROKNJIZI'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PROKNJIZI.RELEASE
ENDPROC

PROCEDURE PRONORKOPITAST
   ON KEY LABEL F1    DO HELPN WITH 'PRONORKOPI'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PRONORKOPI.RELEASE
ENDPROC

PROCEDURE PRONORKOPIPTAST
   ON KEY LABEL F1    DO HELPN WITH 'PRONORKOPIP'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PRONORKOPIP.RELEASE
ENDPROC

PROCEDURE PROPOLUKTAST
   ON KEY LABEL F1    DO HELPN WITH 'PROPOLUK'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PROPOLUK.RELEASE
ENDPROC

PROCEDURE PRORJTAST
   ON KEY LABEL F1    DO HELPN WITH 'PRORJ'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PRORJ.RELEASE
ENDPROC

PROCEDURE POMATTAST

ON KEY LABEL F1    DO HELPN WITH 'POMAT'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       POMAT.RELEASE
ON KEY LABEL +         DO POMATDOD
on key label INS       DO POMATDOD
ON KEY LABEL F4        DO POMATROBA  
ON KEY LABEL F5        DO KNJIZIPOMAT
ON KEY LABEL F6        DO POMATTRAZI
ON KEY LABEL F9        DO POMATZAG
ON KEY LABEL F10       DO POMATPREGLEDTREB
ON KEY LABEL ALT+F1    DO POMATPROMENABR
ON KEY LABEL ALT+F2    DO POMATZAGT
ON KEY LABEL ALT+F3    DO POMATBRISI
ON KEY LABEL ALT+F4    DO POMATPREN
ON KEY LABEL ALT+F5    DO POMATBRISIT
ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC
*ON KEY LABEL CTRL+F12  DO FAKOTV
ENDPROC


PROCEDURE POMATZAGTAST
   ON KEY LABEL F1    DO HELPN WITH 'POMATZAG'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
ENDPROC


PROCEDURE POMATTRROBTAST
   ON KEY LABEL F1    DO HELPN WITH 'POMATTRROB'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   POMATTRROB.RELEASE
ENDPROC

PROCEDURE POMATTRROB2TAST
   ON KEY LABEL F1    DO HELPN WITH 'POMATTRROB2'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   POMATTRROB2.RELEASE
ENDPROC


PROCEDURE POMATTRNALTAST
   ON KEY LABEL F1    DO HELPN WITH 'POMATTRNAL'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   POMATTRNAL.RELEASE
ENDPROC

PROCEDURE POMATTRKALTAST
   ON KEY LABEL F1    DO HELPN WITH 'POMATTRKAL'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   POMATTRKAL.RELEASE
ENDPROC

PROCEDURE POMATTRRNALTAST
   ON KEY LABEL F1    DO HELPN WITH 'POMATTRRNAL'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   POMATTRNAL.RELEASE
ENDPROC

PROCEDURE POMATTRAZITAST
   ON KEY LABEL F1    DO HELPN WITH 'POMATTRAZI'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   POMATTRAZI.RELEASE
ENDPROC

PROCEDURE POMATTRKTAST
   ON KEY LABEL F1    DO HELPN WITH 'POMATTRK'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   POMATTRK.RELEASE
ENDPROC

PROCEDURE POMATZAGTTRFAKTAST
   ON KEY LABEL F1    DO HELPN WITH 'POMATZAGTTRFAK'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       POMATZAGTTRFAK.RELEASE
ENDPROC

PROCEDURE POMATZAGTTAST
   ON KEY LABEL F1    DO HELPN WITH 'POMATZAGT'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F6    DO POMATZAGTTRfak
   ON KEY LABEL ESC       POMATZAGT.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE POMATPRENTAST
   ON KEY LABEL F1    DO HELPN WITH 'POMATPREN'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       POMATPREN.RELEASE
ENDPROC

PROCEDURE POMATPROMENABRTAST
   ON KEY LABEL F1    DO HELPN WITH 'POMATPROMENABR'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       POMATPROMENABR.RELEASE
ENDPROC


PROCEDURE PRONORTRAZITAST
   ON KEY LABEL F1        DO HELPN WITH 'PRONORTRAZI'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PRONORTRAZI.RELEASE
ENDPROC

PROCEDURE PRONORTRPROTAST
   ON KEY LABEL F1        DO HELPN WITH 'PRONORTRPRO'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PRONORTRPRO.RELEASE
ENDPROC

PROCEDURE PRONORTRNORTAST
   ON KEY LABEL F1        DO HELPN WITH 'PRONORTRNOR'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PRONORTRNOR.RELEASE
ENDPROC


PROCEDURE PRONALTRAZITAST
   ON KEY LABEL F1        DO HELPN WITH 'PRONALTRAZI'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PRONALTRAZI.RELEASE
ENDPROC

PROCEDURE PRONALTRNALTAST
   ON KEY LABEL F1        DO HELPN WITH 'PRONALTRNAL'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PRONALTRNAL.RELEASE
ENDPROC

PROCEDURE PRONALTRPROTAST
   ON KEY LABEL F1        DO HELPN WITH 'PRONALTRPRO'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PRONALTRPRO.RELEASE
ENDPROC

PROCEDURE PRONALTRNORTAST
   ON KEY LABEL F1        DO HELPN WITH 'PRONALTRNOR'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PRONALTRNOR.RELEASE
ENDPROC

PROCEDURE PRONALTRDATTAST
   ON KEY LABEL F1        DO HELPN WITH 'PRONALTRDAT'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PRONALTRDAT.RELEASE
ENDPROC


PROCEDURE PROCKNALTAST
ON KEY LABEL F1    DO HELPN WITH 'PROCKNAL'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL +     DO PROCKNALDOD
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       PROCKNAL.RELEASE
ENDPROC


PROCEDURE PROCKNRTAST
ON KEY LABEL F1    DO HELPN WITH 'PROCKNR'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       PROCKNR.RELEASE
ENDPROC

PROCEDURE PROCKNALRADTAST
ON KEY LABEL F1    DO HELPN WITH 'PROCKNALRAD'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       PROCKNALRAD.RELEASE
ENDPROC

PROCEDURE PROCKNALRAD2TAST
ON KEY LABEL F1    DO HELPN WITH 'PROCKNALRAD2'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       PROCKNALRAD2.RELEASE
ENDPROC

PROCEDURE MLOPMTAST
   ON KEY LABEL F1    DO HELPN WITH 'MLOPM'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       MLOPM.RELEASE
ENDPROC

PROCEDURE PRORADOPTAST
   ON KEY LABEL F1    DO HELPN WITH 'PRORADOP'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PRORADOP.RELEASE
ENDPROC




PROCEDURE PRONROPTAST
   ON KEY LABEL F1    DO HELPN WITH 'PRONROP'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PRONROP.RELEASE
ENDPROC


PROCEDURE PRONROPPTAST
   ON KEY LABEL F1    DO HELPN WITH 'PRONROPP'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PRONROPP.RELEASE
ENDPROC

PROCEDURE PRONLOPTAST
   ON KEY LABEL F1    DO HELPN WITH 'PRONLOP'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PRONLOP.RELEASE
ENDPROC

PROCEDURE PRONLOPPTAST
   ON KEY LABEL F1    DO HELPN WITH 'PRONLOPP'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PRONLOPP.RELEASE
ENDPROC


PROCEDURE PORUKATAST
   ON KEY LABEL F1    DO HELPN WITH 'PORUKA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PORUKA.RELEASE
ENDPROC


PROCEDURE PROCKNALGOTTAST
ON KEY LABEL F1    DO HELPN WITH 'PROCKNALGOT'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       PROCKNALGOT.RELEASE
ENDPROC


PROCEDURE PROVMATTAST
   ON KEY LABEL F1    DO HELPN WITH 'PROVMAT'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PROVMAT.RELEASE
ENDPROC

PROCEDURE PROVMATUNOSSIFTAST
   ON KEY LABEL F1    DO HELPN WITH 'PROVMATUNOSSIF'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PROVMATUNOSSIF.RELEASE
ENDPROC


PROCEDURE PROKNJIZIPTAST
   ON KEY LABEL F1    DO HELPN WITH 'PROKNJIZIP'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PROKNJIZIP.RELEASE
ENDPROC





PROCEDURE PROZAHPREGLEDITAST
   ON KEY LABEL F1    DO HELPN WITH 'PROZAHPREGLEDI'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PROZAHPREGLEDI.RELEASE
ENDPROC

PROCEDURE PROZAHNALTAST
   ON KEY LABEL F1    DO HELPN WITH 'PROZAHNAL'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PROZAHNAL.RELEASE
ENDPROC

PROCEDURE PORUKAUTAST
   ON KEY LABEL F1    DO HELPN WITH 'PORUKAU'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PORUKAU.RELEASE
ENDPROC

PROCEDURE PROAMBKTAST
   ON KEY LABEL F1    DO HELPN WITH 'PROAMBK'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PROAMBK.RELEASE
ENDPROC


PROCEDURE PROAN0TAST
   ON KEY LABEL F1    DO HELPN WITH 'PROAN0'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PROAN0.RELEASE
ENDPROC


PROCEDURE ROBATAST

ON KEY LABEL F1    DO HELPN WITH 'ROBA'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       ROBA.RELEASE
ON KEY LABEL +         DO ROBADOD
on key label INS       DO ROBADOD
ON KEY LABEL F3        DO ROBADEONAZ
ON KEY LABEL F4        DO ROBAF4
ON KEY LABEL F5        DO ROBApodnaz
ON KEY LABEL F6        DO ROBAF6
ON KEY LABEL F7        DO ROBAKARTF7
ON KEY LABEL F8        DO ROBAF4KARTICA
ON KEY LABEL F9        DO ROBABKOD
ON KEY LABEL F10       DO ROBABIRAM
ON KEY LABEL SHIFT+F1      DO ROBPREGCEN
ON KEY LABEL F12      DO ROBAGRID
ON KEY LABEL ALT+F9    DO ROBAAF9
ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC
ON KEY LABEL CTRL+F12  DO OTVROBA

ENDPROC


PROCEDURE PROPMATKTAST
   ON KEY LABEL F1    DO HELPN WITH 'PROPMATK'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PROPMATK.RELEASE
ENDPROC


PROCEDURE FAN0TAST

ON KEY LABEL F1    DO HELPN WITH 'FAN0'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       FAN0.RELEASE
ON KEY LABEL +         DO FAN0DOD
on key label INS       DO FAN0DOD
ON KEY LABEL F3        DO FAN0DEONAZ
ON KEY LABEL ALT+F3        DO FAN0TEKRAC
ON KEY LABEL F4        DO FAN0TRAZI
ON KEY LABEL F5        DO FAN0GR5TRAZI
ON KEY LABEL F6        DO FAN0TRAZIF6
ON KEY LABEL F7        DO FAN0KARTF7
ON KEY LABEL F8        DO FAN0ZIROTRAZI
ON KEY LABEL CTRL+F12  DO OTVFAN0
ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC

ENDPROC


PROCEDURE AN0K2TAST
ON KEY LABEL F1    DO HELPN WITH 'AN0K2'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       AN0K2.RELEASE
ENDPROC


PROCEDURE fan0dEONAZTAST
   ON KEY LABEL F1    DO HELPN WITH 'FAN0DEONAZ'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       fan0DEONAZ.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC


PROCEDURE FAKPROMENABRTAST
   ON KEY LABEL F1    DO HELPN WITH 'FAKPROMENABR'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       FAKPROMENABR.RELEASE
ENDPROC


PROCEDURE FAKPRNTAST
ON KEY LABEL F1    DO HELPN WITH 'FAKPRN'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       FAKPRN.RELEASE
   ON KEY LABEL +         DO FAKPRNDOD
   on key label INS       DO FAKPRNDOD
   ON KEY LABEL SHIFT+F10 DO FAKPRNBRISI
ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC
ON KEY LABEL CTRL+F12  DO FAKPRNOTVORI
ENDPROC


PROCEDURE FAKPRNKARTTAST
ON KEY LABEL F1    DO HELPN WITH 'FAKPRNKART'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       FAKPRNKART.RELEASE
ENDPROC

PROCEDURE ROBAbkodTAST
   ON KEY LABEL F1    DO HELPN WITH 'ROBABKOD'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       ROBAbkod.RELEASE
ENDPROC


PROCEDURE ROBPREGCENTAST
   ON KEY LABEL F1    DO HELPN WITH 'ROBPREGCEN'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       ROBPREGCEN.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE FAKPRNKARTTAST
   ON KEY LABEL F1    DO HELPN WITH 'FAKPRNKART'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       FAKPRNKART.RELEASE
ENDPROC

PROCEDURE ROBAPODNAZTAST
   ON KEY LABEL F1    DO HELPN WITH 'ROBAPODNAZ'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       ROBAPODNAZ.RELEASE
ENDPROC

PROCEDURE ROBVRSTKTAST
ON KEY LABEL F1    DO HELPN WITH 'ROBVRSTK'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       ROBVRSTK.RELEASE
ENDPROC

PROCEDURE ROBPROIKTAST
ON KEY LABEL F1    DO HELPN WITH 'ROBPROIK'
   ON KEY LABEL F2        ! /N CALC.EXE
   
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       ROBPROIK.RELEASE
ENDPROC

PROCEDURE ANKARTODDOTAST
   ON KEY LABEL F1    DO HELPN WITH 'ANKARTODDO'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       ANKARTODDO.RELEASE
ENDPROC


PROCEDURE HELPNTAST
   ON KEY LABEL ESC       HELPN.RELEASE
   ON KEY LABEL F1    ON KEY
   ON KEY LABEL CTRL+F12  HELPN.GRD0.READONLY=.F.
ENDPROC

PROCEDURE fan0TEKRACTAST
   ON KEY LABEL F1    DO HELPN WITH 'FAN0TEKRAC'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       fan0TEKRAC.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE ANALK2TAST
ON KEY LABEL F1    DO HELPN WITH 'ANALK2'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       ANALK2.RELEASE
   ON KEY LABEL F7        DO ANALKPRN2
   ON KEY LABEL F8        DO ANALKPRN3
   ON KEY LABEL F10       DO ANALKPRN2P
   ON KEY LABEL ALT+F7    DO ANALKPRN2N
   ON KEY LABEL ALT+F8    DO ANALKPRN3N
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC

ENDPROC

PROCEDURE ROBAK2TAST
   ON KEY LABEL F1    DO HELPN WITH 'ROBAK2'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       ROBAK2.RELEASE
ENDPROC


PROCEDURE ROBADEONAZTAST
   ON KEY LABEL F1    DO HELPN WITH 'ROBADEONAZ'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       ROBADEONAZ.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC


PROCEDURE ROBVRSTTAST

ON KEY LABEL F1    DO HELPN WITH 'ROBVRST'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       ROBVRSTA.RELEASE
ON KEY LABEL +         DO ROBVRSTDOD
on key label INS       DO ROBVRSTDOD
ON KEY LABEL F7        DO ROBVRSTKARTF7
ON KEY LABEL F10       DO ROBVRSTBIRAM
ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE ROBPROITAST

ON KEY LABEL F1    DO HELPN WITH 'ROBPROI'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       ROBPROI.RELEASE
ON KEY LABEL +         DO ROBPROIDOD
on key label INS       DO ROBPROIDOD
ON KEY LABEL F7        DO ROBPROIKARTF7
ON KEY LABEL F10       DO ROBPROIBIRAM
ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC


PROCEDURE TVUNKOLTAST
   ON KEY LABEL F1    DO HELPN WITH 'TVUNKOL'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       TVUNKOL.RELEASE
ENDPROC

PROCEDURE ROBVRSTATAST
   ON KEY LABEL F1    DO HELPN WITH 'ROBVRSTA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       ROBVRSTA.RELEASE
ENDPROC

PROCEDURE PROMATDEONAZTAST
   ON KEY LABEL F1    DO HELPN WITH 'PROMATDEONAZ'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PROMATDEONAZ.RELEASE
ENDPROC


PROCEDURE PRONORMALTAST
   ON KEY LABEL F1    DO HELPN WITH 'PRONORMAL'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PRONORMAL.RELEASE
   ON KEY LABEL +         DO PRONORMADOD
   on key label INS       DO PRONORMADOD 
   ON KEY LABEL F5   DO PRONORMAF5
   ON KEY LABEL F6   DO PRONORTRAZI
   ON KEY LABEL F10   DO PRONORMAF10
   ON KEY LABEL SHIFT+F1   DO PRONORMASF1
   ON KEY LABEL SHIFT+F2   DO PRONORMASF2
   ON KEY LABEL SHIFT+F3   DO PRONORMASF3
   ON KEY LABEL SHIFT+F4   DO PRONORMASF4
   ON KEY LABEL SHIFT+F5   DO PRONORMASF5
   ON KEY LABEL SHIFT+F6   DO PRONORMASF6
   ON KEY LABEL SHIFT+F7   DO PRONORMASF7
   ON KEY LABEL SHIFT+F8   DO PRONORMASF8
ENDPROC

PROCEDURE PRONORMALPRENOSTAST
   ON KEY LABEL F1    DO HELPN WITH 'PRONORMALPRENOS'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PRONORMALPRENOS.RELEASE
ENDPROC

PROCEDURE PRONALLTAST
   ON KEY LABEL F1    DO HELPN WITH 'PRONALL'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL +     DO PRONALDOD
   ON KEY LABEL ESC   PRONALL.RELEASE
   ON KEY LABEL F4       DO PROROBA
   ON KEY LABEL F6       DO PRONALTRAZI
   ON KEY LABEL F8       DO PRONALlDOD
   ON KEY LABEL F10      DO PRONAL01
ENDPROC

PROCEDURE PRONALLPRENOSTAST
   ON KEY LABEL F1    DO HELPN WITH 'PRONALLPRENOS'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PRONALLPRENOS.RELEASE
ENDPROC

PROCEDURE PRONALBRTAST
   ON KEY LABEL F1    DO HELPN WITH 'PRONALBR'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL +         DO PRONALBRNOVADOD
   on key label INS       DO PRONALBRNOVADOD
   on key label F5        DO PRONALBRNOVABIRAM
   ON KEY LABEL ESC       PRONALBR.RELEASE
ENDPROC

PROCEDURE PRONALprproveraTAST
   ON KEY LABEL F1    DO HELPN WITH 'PRONALPRPROVERA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PRONALPRPROVERA.RELEASE
ENDPROC

PROCEDURE PRONALbrojTAST
   ON KEY LABEL F1    DO HELPN WITH 'PRONALbroj'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PRONALbroj.RELEASE
ENDPROC

PROCEDURE PROKNJIZISVETAST
   ON KEY LABEL F1    DO HELPN WITH 'PROKNJIZISVE'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PROKNJIZISVE.RELEASE
ENDPRO


PROCEDURE CLHC00TAST
ON KEY LABEL F1        DO HELPN WITH 'CLHC00'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       CLHC00.RELEASE
ENDPROC

PROCEDURE CLHCRNALTAST
ON KEY LABEL F1        DO HELPN WITH 'CLHCRNAL'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       CLHCRNAL.RELEASE
ENDPROC

PROCEDURE CLHCidkTAST
ON KEY LABEL F1        DO HELPN WITH 'CLHCIDK'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       CLHCIDK.RELEASE
ENDPROC

PROCEDURE CLHCpakTAST
ON KEY LABEL F1        DO HELPN WITH 'CLHCPAK'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       CLHCPAK.RELEASE
ENDPROC

PROCEDURE CLHCIZVTAST
ON KEY LABEL F1        DO HELPN WITH 'CLHCIZV'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       CLHCIZV.RELEASE
ENDPROC

PROCEDURE CLHCrnalprenosTAST
ON KEY LABEL F1        DO HELPN WITH 'CLHCRNALPRENOS'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       CLHCRNALPRENOS.RELEASE
ENDPROC

PROCEDURE CLHCizvprenosTAST
ON KEY LABEL F1        DO HELPN WITH 'CLHCizvPRENOS'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       CLHCizvPRENOS.RELEASE
ENDPROC

PROCEDURE CLHCidkprenosTAST
ON KEY LABEL F1        DO HELPN WITH 'CLHCidkPRENOS'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       CLHCidkPRENOS.RELEASE
ENDPROC


PROCEDURE CLHCrnaldoppodTAST
ON KEY LABEL F1        DO HELPN WITH 'CLHCRNALdoppod'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       CLHCRNALdoppod.RELEASE
ENDPROC

PROCEDURE CLHCIZVdoppodTAST
ON KEY LABEL F1        DO HELPN WITH 'CLHCIZVdoppod'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       CLHCIZVdoppod.RELEASE
ENDPROC

PROCEDURE CLHCIZVprenosradTAST
ON KEY LABEL F1        DO HELPN WITH 'CLHCIZVPRENOSRAD'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       CLHCIZVPRENOSRAD.RELEASE
ENDPROC


PROCEDURE AAIZBORPRTAST
ON KEY LABEL F1        DO HELPN WITH 'AAIZBORPR'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       AAIZBORPR.RELEASE
ENDPROC

PROCEDURE AAIZBORPRKTAST
ON KEY LABEL F1        DO HELPN WITH 'AAIZBORPRK'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       AAIZBORPRK.RELEASE
ENDPROC

PROCEDURE AAIZBORPRKTAST
ON KEY LABEL F1        DO HELPN WITH 'AAIZBORPRK'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       AAIZBORPRK.RELEASE
ENDPROC

PROCEDURE AAIZBORPRTABTAST
ON KEY LABEL F1        DO HELPN WITH 'AAIZBORPRTAB'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       AAIZBORPRTAB.RELEASE
ENDPROC


PROCEDURE AAPRITAST
ON KEY LABEL F1        DO HELPN WITH 'AAPRI'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       AAPRI.RELEASE
ENDPROC

PROCEDURE ROBA00TAST

ON KEY LABEL F1    DO HELPN WITH 'ROBA00'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       ROBA00.RELEASE
ON KEY LABEL +         DO ROBA0DOD00
on key label INS       DO ROBA0DOD00
ON KEY LABEL F3        DO ROBtradeona0
oN KEY LABEL F4        DO ROBA00TRAZI
oN KEY LABEL F5        DO ROBA00PODNAZ
oN KEY LABEL F6        DO ROBA00GRUPA
ON KEY LABEL F7        DO ROBA0KARTF7
ON KEY LABEL F10       DO ROBA00DOPUNI
ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC
ON KEY LABEL CTRL+F12  DO OTVROB 

ENDPROC

PROCEDURE ROBA00PODNAZTAST
   ON KEY LABEL F1    DO HELPN WITH 'ROBA00PODNAZ'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       ROBA00PODNAZ.RELEASE
ENDPROC

PROCEDURE ROBA00GRUPATAST
   ON KEY LABEL F1    DO HELPN WITH 'ROBA00GRUPA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       ROBA00GRUPA.RELEASE
ENDPROC

PROCEDURE PROZAHAVANSITAST
   ON KEY LABEL F1    DO HELPN WITH 'PROZAHAVANSI'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PROZAHAVANSI.RELEASE
ENDPROC

PROCEDURE PROZAHGARTAST
   ON KEY LABEL F1    DO HELPN WITH 'PROZAHGAR'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PROZAHGAR.RELEASE
ENDPROC

PROCEDURE PROZAHRACTAST
   ON KEY LABEL F1    DO HELPN WITH 'PROZAHRAC'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PROZAHRAC.RELEASE
ENDPROC

PROCEDURE PRONalKOPITAST
   ON KEY LABEL F1    DO HELPN WITH 'PRONALKOPI'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       PRONALKOPI.RELEASE
ENDPROC
