PUSH KEY CLEAR
TEHREG.COMMAND5.SETFOCUS
PUBLIC TEHTRAZIO
TEHTRAZIO=2
DO FORM TEHREG0
PUBLIC TEHTRAZIO
TEHTRAZIO=1
PUBLIC DA_NE
DA_NE='D'
DO PORUKADANE WITH ' PRENOS U REGISTRACIJE '
IF DA_NE='D'   
   SELECT OT0
   SCATTER NAME POLJA
   SELECT OTG
   SET ORDER TO 
   GO BOTTOM
   MASIFRA=SIFRA
   MDATUM=DATUM
   MVAL=VAL(MASIFRA)+1
   MKONTROLA=KONTROLA
   APPEND BLANK
   GATHER NAME POLJA
   REPLACE SIFRA WITH STR(MVAL,6,0)
   REPLACE DATUM WITH MDATUM
   REPLACE KONTROLA WITH MKONTROLA
ENDIF   
SELECT OTG
SET ORDER TO 
TEHREG.GRD0.SETFOCUS
TEHREG.GRD0.REFRESH
POP KEY