   TEHTIP.GRD0.RECORDSOURCE=''
   SELECT OTTIP
   SET ORDER TO 
   GO BOTTOM
   APPEND BLANK
   GO BOTTOM
   DO TEHTIPKART
   SELECT OTTIP
   SET ORDER TO 1
   TEHTIP.GRD0.RECORDSOURCE='OTTIP'
   tehTIP.GRD0.REFRESH
   tehTIP.GRD0.SETFOCUS
   tehTIP.REFRESH
