   SELECT OTVIRM0
   SET ORDER TO 
   GO BOTTOM
   MVSIFRA=VSIFRA
   MVAL=VAL(MVSIFRA)+1
   APPEND BLANK
   REPLACE VSIFRA WITH STR(MVAL,4,0)
   GO BOTTOM
   DO TEHVIRM0KART
   SET ORDER TO 1
   tehVIRM0.GRD0.SETFOCUS
   tehVIRM0.REFRESH
