PUSH KEY CLEAR
   PUBLIC DA_NE
   DA_NE='D'
   DO PORUKADANE WITH ' PRENOS VIRMANA U ARHIVU '
   IF DA_NE='D'   
      SELECT OTVIRME
      USE
      USE OTVIRMA IN 0
      SELECT OTVIRMA
      APPEND FROM &KOTVIRM FOR DUG<>0
      USE
      USE &KOTVIRM IN 0 EXCLUSIVE ALIAS OTVIRME
      SELECT OTVIRME
      ZAP
   ENDIF   
TEHVIRME.Release
KEYBOARD '{ENTER}'
POP KEY
