   TEHVIRME.GRD0.RECORDSOURCE=''
   SELECT OTVIRME
   SET ORDER TO 
   GO BOTTOM
   IF RECCOUNT()>0
   MZSIFRA=ZSIFRA
   MSIF1=SIF1
   MGRUPA=GRUPA
   ELSE
   MZSIFRA=''
   MSIF1=''
   MGRUPA=''
   ENDIF
   APPEND BLANK
   GO BOTTOM
   REPLACE ZSIFRA WITH MZSIFRA
   REPLACE SIF1 WITH MSIF1
   REPLACE GRUPA WITH MGRUPA
   DO TEHVIRMEKART
   SELECT OTVIRME
   SET ORDER TO 
   TEHVIRME.GRD0.RECORDSOURCE='OTVIRME'
   tehVIRME.GRD0.REFRESH
   tehVIRME.GRD0.SETFOCUS
   tehVIRME.REFRESH
