SELECT OTVIRME
SET RELATION TO
SELECT OTVIRM0
DO FORM TEHVIRM0
SELECT OTVIRME
*SET RELATION TO VSIFRA INTO OTVIRM0 additive
*SET RELATION TO SIFRA INTO otg additive
*SET RELATION TO ZSIFRA INTO OTZAPR additive
