PUSH KEY CLEAR
SELECT OTVIRME
mrec=RECNO()
SET RELATION TO SIFRA INTO otg additive
IF GRUPA='2'
REPORT FORM TEHREG03 PREVIEW FOR RECNO()=mrec
ELSE
REPORT FORM TEHREG05 PREVIEW FOR RECNO()=mrec
ENDIF
SELECT OTVIRME
SET RELATION TO
GOTO mrec
POP KEY