PUSH KEY CLEAR
SELECT OTVIRME
SET RELATION TO SIFRA INTO otg additive
IF GRUPA='2'
REPORT FORM TEHREG03 PREVIEW
endif
IF GRUPA='1'.OR.GRUPA=' '
REPORT FORM TEHREG05 PREVIEW
endif
IF GRUPA='4'
REPORT FORM TEHREG06 PREVIEW
ENDIF
SELECT OTVIRME
SET RELATION TO
POP KEY