PUSH KEY CLEAR

IF UKNAB<>0
   REPLACE PROCMAR WITH ROUND(MARZA*100/UKNAB,6)
ELSE
   REPLACE PROCMAR WITH 0
ENDIF   
REPLACE REALMAR WITH ROUND(PROCMAR*VREDPROD/100,2)
REPLACE DANA WITH DATDO-DATOD+1
REPLACE OSTDANA WITH TDAT1-DATDO
REPLACE PROCDANA WITH DANA/365*100 
REPLACE PROCDANAO WITH OSTDANA/365*100 

REPLACE PROCENUL WITH ROUND(UKNAB/DANA*OSTDANA,2)
REPLACE PROCENIZ WITH ROUND(VREDPROD/DANA*ostDANA,2)
REPLACE PROCENMA WITH ROUND(REALMAR/DANA*OSTDANA,2)
REPLACE PROCENUS WITH ROUND(USLUGE/DANA*OSTDANA,2)
REPLACE UKUPUL WITH UKNAB+PROCENUL
REPLACE UKUPIZ WITH VREDPROD+PROCENIZ
REPLACE UKUPMA WITH REALMAR+PROCENMA
REPLACE UKUPUS WITH USLUGE+PROCENUS
REPLACE TPROCENUL WITH ROUND(UKNAB/DANA*OSTDANA*((100+TRENDPROC)/100),2)
REPLACE TPROCENIZ WITH ROUND(VREDPROD/DANA*ostDANA*((100+TRENDPROC)/100),2)
REPLACE TPROCENMA WITH ROUND(REALMAR/DANA*OSTDANA*((100+TRENDPROC)/100),2)
REPLACE TPROCENUS WITH ROUND(USLUGE/DANA*OSTDANA*((100+TRPROCUS)/100),2)
REPLACE TUKUPUL WITH UKNAB+TPROCENUL
REPLACE TUKUPIZ WITH UKNAB+TPROCENIZ
REPLACE TUKUPMA WITH REALMAR+TPROCENMA
REPLACE TUKUPUS WITH USLUGE+TPROCENUS


   DO idel WITH (kkockax)   

SELECT TM
MDATOD=DATOD
MDATDO=DATDO
MDANA=DATDO-DATOD+1
COPY STRUCTURE TO &KKOCKA


IF TOBJEKAT='V'
KTM='TM'+TTVREDNI+'.DBF'
ELSE
KTM='TM'+TTVREDNI+'.DBF'
ENDIF
USE &KTM IN 0 ALIAS TMK ORDER 1

USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
SELECT KOCKA
FOR I=1 TO MDANA
   APPEND BLANK
   REPLACE DATOD WITH MDATOD
   MDATOD=MDATOD+1
   MMDAT=DATOD
   SELECT TMK
   SEEK MMDAT 
   MSTANJE=0
   MSTANJE2=0
   MSTANJE3=0
   IF FOUND()
      DO WHILE.NOT.EOF()
         IF DATDOK<>MMDAT
            EXIT
         ENDIF   
         MSTANJE=MSTANJE+UKNAB
         MSTANJE2=MSTANJE2+VREDPROD
         MSTANJE3=MSTANJE3+UKNAB-VREDPROD
         SKIP
      ENDDO   
   ENDIF
   SELECT KOCKA
   REPLACE UKNAB WITH MSTANJE
   REPLACE VREDPROD WITH MSTANJE2
   REPLACE UPLACENO WITH MSTANJE3
NEXT
SELECT KOCKA
GO TOP
MUKNAB=0
MUPLACENO=0
MVREDPROD=0
MUSLUGE=0
DO WHILE.NOT.EOF()
   MUKNAB=MUKNAB+UKNAB
   MVREDPROD=MVREDPROD+VREDPROD
   MUPLACENO=MUPLACENO+UPLACENO
   replace usluge WITH muknab-mvredprod
   musluge=musluge+usluge
   SKIP
ENDDO   
APPEND BLANK
REPLACE UKNAB WITH MUKNAB
REPLACE VREDPROD WITH MVREDPROD
REPLACE UPLACENO WITH MUPLACENO
IF MDANA<>0
   MDNEVZAL=MUSLUGE/MDANA
ELSE
   MDNEVZAL=0
ENDIF
SELECT KOCKA
USE
SELECT TMK
USE
SELECT TM
REPLACE DNEVZAL WITH MDNEVZAL
IF MUSLUGE<>0
   REPLACE KOEFOBRTA WITH ROUND(MVREDPROD/MDNEVZAL,4)
ELSE
   REPLACE KOEFOBRTA WITH 0
ENDIF

POP KEY