PUSH KEY CLEAR
SELECT TM
SET RELATION TO
USE
IF TOBJEKAT='V'
   KTM='TVTM'+TTVREDNI+'.DBF'
ELSE
   KTM='TM'+TTVREDNI+'.DBF'
ENDIF   
   DO idel WITH (kkockax)   

USE &KTM EXCLU IN 0 ALIAS TM
SELECT TM
DELETE ALL FOR UKNAB=0.AND.VREDPROD=0.AND.UPLACENO=0.AND.USLUGE=0
PACK
SORT ON DATDOK TO &KKOCKA
DELETE ALL
PACK
APPEND FROM &KKOCKA
USE
TBRISITM=1
   TM.RELEASE
POP KEY