PUSH KEY CLEAR
SELECT TM
IF RECCOUNT()<1
   MDATDOK=DATE()
ELSE
   MDATDOK=DATDOK
   SET ORDER TO
   GO BOTTOM
*   REPLACE ARHIVA WITH '*'
ENDIF   
TM.grd0.READONLY=.F.
TM.GRD0.BACKCOLOR=RGB(255,255,255)

TM.grd0.column1.setfocus
APPEND BLANK
REPLACE DATDOK WITH MDATDOK
*GO BOTTOM
TM.grd0.column1.setfocus
TM.GRD0.REFRESH
TM.REFRESH  
POP KEY