PARAMETERS MSTAMPA
PUSH KEY CLEAR
PUBLIC ASTAMPA
ASTAMPA=MSTAMPA
SELECT TM
SET ORDER TO 1
GO TOP
BROJAC=1
DO WHILE.NOT.EOF()
   IF VRSTA='U'.AND.(USLUGE<>0.OR.UPLACENO<>0)
      REPLACE REDNI WITH BROJAC
      BROJAC=BROJAC+1
   ENDIF   
   SKIP
ENDDO   
GO TOP
DO FORM TMZBIRU WITH '1'
POP KEY