PARAMETERS SVE
PUSH KEY CLEAR

MSVE=SVE
MDOK=TOBJEKAT+TTVREDNI
MGLKONTO=TKONTO
KKNALIZV=MDATA01+'\NALIZV'+OPERATER+'.DBF'
KKNALIZVX=MDATA01+'\NALIZV'+OPERATER+'.CDX'
KNALIZV=MDATA01+'\NALIZV'+OPERATER
KNALIZVX=MDATA01+'\NALIZV'+OPERATER


DO IDEL WITH (KKNALIZV)
DO IDEL WITH (KKNALIZVX)
DO IBAZE WITH KNALIZV,'NALIZV'
DO IIND WITH KNALIZV,'KONTO+DTOS(DATDOK)','BRNAL','DTOS(DATDOK)',;
             'KONTO+SIFRA+DTOS(DATDOK)','SIFRA+DTOS(DATDOK)','SIFRA+BRRAC+DTOS(DATDOK)'

USE &KNALIZV IN 0 ALIAS NALIZV EXCLUSIVE 
USE firma IN 0

   DO idel WITH (kkockax)   
   DO idel WITH (kkockax2)   
   DO idel WITH (kkockax3)   
   DO idel WITH (kkockax4)   
   DO idel WITH (kkockax5)   

SELECT NALIZV   
COPY STRUCTURE TO &KKOCKA   
  
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
SELECT kocka

INDEX ON DTOS(DATDOK) TAG DATDOK   
*----------------GLAVNA KNJIGA--------------------
USE NAL IN 0
SELECT NAL
COPY TO &KKOCKA4 FOR DOK=MDOK.AND.KONTO=MGLKONTO
USE
KTM='TM'+TTVREDNI+'.DBF'
USE &KTM IN 0 ALIAS TM ORDER 1
SELECT TM
TOTAL ON dATDOK TO &KKOCKA2 FIELDS UKNAB,VREDPROD,UPLACENO
USE
SELECT KOCKA
APPEND FROM &KKOCKA2
REPLACE ALL KONTO WITH MGLKONTO
APPEND FROM &KKOCKA4
SET ORDER TO 1
TOTAL ON DTOS(DATDOK) TO &KKOCKA2 FIELDS DUG,POT,UKNAB,VREDPROD,UPLACENO
DELETE ALL
PACK

APPEND FROM &KKOCKA2
GO TOP
PUSH KEY CLEAR
*REPORT FORM TMGKSLAG PREVIEW
   mfile='TMgkslag'   
   USLOV=""
   DO printer_bullzip WITH mdata02,mfiLE,USLOv

POP KEY
CLOSE ALL TABLES
POP KEY