PUSH KEY CLEAR
GO TOP
MMALVRED=0
DO WHILE.NOT.EOF()
   REPLACE MALVRED WITH ROUND(KOLI*MALCENA,2)
   MMALVRED=MMALVRED+MALVRED
   SKIP
ENDDO   
GO TOP
TMKOMPOV.LBLZBIR.CAPTION=TRANSFORM(MMALVRED,'999 999 999.99')
TMKOMPOV.GRD0.SETFOCUS
TMKOMPOV.REFRESH
POP KEY