PUSH KEY CLEAR
GO TOP
MMALVRED=0
DO WHILE.NOT.EOF()
   REPLACE MALVRED WITH ROUND(KOLI*MALCENA,2)
   MMALVRED=MMALVRED+MALVRED
   SKIP
ENDDO   
GO TOP
TMKOM.LBLZBIR.CAPTION=TRANSFORM(MMALVRED,'999 999 999.99')
TMKOM.GRD0.SETFOCUS
TMKOM.REFRESH
POP KEY