PUSH KEY CLEAR
SELECT TM
IF RECCOUNT()<1
   MDATDOK=DATE()
ELSE
   MDATDOK=MGDATDOK
   SET ORDER TO
   GO BOTTOM
*   REPLACE ARHIVA WITH '*'
ENDIF   
TMnal.grd0.READONLY=.F.
TMNAL.GRD0.BACKCOLOR=RGB(255,255,255)

TMnal.grd0.column1.setfocus
APPEND BLANK
REPLACE DATDOK WITH MDATDOK
REPLACE BRNAL WITH MTMBRNAL
*GO BOTTOM
TMnal.grd0.column1.setfocus
TMnal.GRD0.REFRESH
TMnal.REFRESH  
POP KEY