MUPLACENO=0
SELECT TM
MDATDOK=DATDOK-1
SET ORDER TO 3
SEEK MTMBRNAL
IF FOUND()
   DO WHILE.NOT.EOF()
      IF BRNAL<>MTMBRNAL
         EXIT
      ENDIF   
      MUPLACENO=MUPLACENO+UPLACENO
      SKIP
   ENDDO   
ENDIF
SET ORDER TO 
   IF PKTKR='D'
      LOCATE FOR DATDOK=MDATDOK.AND.VREDPROD<>0
      IF.NOT.FOUND()
         APPEND BLANK
         REPLACE DATDOK WITH MDATDOK
         REPLACE VREDPROD WITH MUPLACENO
         REPLACE OPIS WITH 'DNEVNI PROMET '+SUBSTR(DTOC(MDATDOK),1,6)
         TMNAL.GRD0.REFRESH
         TMNAL.GRD0.COLUMN1.SETFOCUS
      ENDIF
   ENDIF

