PUSH KEY CLEAR
   IF RECCOUNT()<1
      MDATDOK=DATE()
      MOPIS=' OPIS'
   ELSE
      GO BOTTOM
      MDATDOK=DATDOK
      MOPIS=OPIS
   ENDIF   
   APPEND BLANK
   TMP0.GRD0.REFRESH
   REPLACE DATDOK WITH MDATDOK
   REPLACE OPIS WITH MOPIS
TMP0.GRD0.COLUMN1.SETFOCUS
TMP0.REFRESH  
POP KEY