PUSH KEY CLEAR
SELECT TMP
SET RELATION TO
USE
   KTMP='TMP0.DBF'

USE &KTMP EXCLU ALIAS TMP IN 0
SELECT TMP
DELETE ALL FOR UKPRIH=0.AND.MALVRED=0.AND.UPLATA=0.AND.ISPLATA=0.AND.UKRASH=0.AND.PLACPOR=0.AND.PRENPOR=0.AND.UPLACPOR=0
PACK
SORT ON DATDOK TO &KKOCKA
DELETE ALL
PACK

APPEND FROM &KKOCKA

TMP0.RELEASE
POP KEY