PUSH KEY CLEAR

   DO CASE grupa 
   CASE GRUPA='1'
         MPROVIZIJA=ROUND(DUG*1/100,2)
         MPROVINT=INT(DUG*1/100)
         MPROVRAZ=MPROVIZIJA-MPROVINT
         DO CASE MPROVRAZ
         CASE  MPROVRAZ<=0.25
            MPROVINT2=0.00
         CASE MPROVRAZ>0.25.AND.MPROVRAZ<=0.75
            MPROVINT2=0.50
         CASE MPROVRAZ>0.75
            MPROVINT2=1.00
         OTHERWISE
            MPROVINT2=0.00
         ENDCASE
         MPROVIZIJA=MPROVINT+MPROVINT2
         REPLACE PROVIZIJA WITH MPROVIZIJA
         IF PROVIZIJA<5.00
            REPLACE PROVIZIJA WITH 5
         ENDIF
         REPLACE PROCPROV WITH 1

   case GRUPA='2'
      IF DUG<=807.02
         MMP=8.33
      ELSE
         MMP=ROUND(958.33*DUG/(92000+DUG),2)
      ENDIF

      IF DUG>99600
         MMP=ROUND(DUG*0.5/100,2)
      ENDIF

      IF MMP=8.33
         REPLACE PROVIZIJA WITH 8.33
         REPLACE PROCPROV WITH 0
      ELSE
         REPLACE PROVIZIJA WITH ROUND(MMP,2)
         REPLACE PROCPROV WITH ROUND(MMP*100/DUG,2)
         REPLACE PROVIZIJA WITH ROUND(PROCPROV*DUG/100,2)
      ENDIF
   
   case GRUPA='3'

            MPROVIZIJA=ROUND(DUG*1/100,2)
            MPROVINT=INT(DUG*1/100)
            MPROVRAZ=MPROVIZIJA-MPROVINT
   
            REPLACE PROVIZIJA WITH MPROVIZIJA

            REPLACE PROCPROV WITH 1

  endcase
POP KEY