PARAMETERS NAZIV
PUSH KEY CLEAR

   MNAZIV=NAZIV+'.DBF'
   IF FILE(MNAZIV)
      USE &MNAZIV ALIAS NNAZIV IN 0
      SELECT NNAZIV
      IF RECCOUNT()<1
         MMPUTANJA=MPUTANJA+MNAZIV
         IF FILE(MMPUTANJA)  
            APPEND FROM &MMPUTANJA  
         ENDIF  
      ENDIF
      USE
      SELECT TPPRENOS
   ENDIF
   POP KEY