PARAMETERS SVE
PUSH KEY CLEAR
SET EXACT ON
MSVE=SVE
IF LEN(TTVREDNI)=1
   MDOK=ALLTRIM(TOBJEKAT+TTVREDNI)+' '
ELSE
   MDOK=ALLTRIM(TOBJEKAT+TTVREDNI)
ENDIF
MGLKONTO=TKONTO
MGLKONTOK=TKONTOK
KKNALIZV=MDATA01+'\NALIZV'+OPERATER+'.DBF'
KKNALIZVX=MDATA01+'\NALIZV'+OPERATER+'.CDX'
KNALIZV=MDATA01+'\NALIZV'+OPERATER
KNALIZVX=MDATA01+'\NALIZV'+OPERATER

DO IDEL WITH (KKNALIZV)
DO IDEL WITH (KKNALIZVX)
DO IBAZE WITH KNALIZV,'NALIZV'
DO IIND WITH KNALIZV,'KONTO+DTOS(DATDOK)','BRNAL','DTOS(DATDOK)',;
             'KONTO+SIFRA+DTOS(DATDOK)','SIFRA+DTOS(DATDOK)','SIFRA+BRRAC+DTOS(DATDOK)'

USE &KNALIZV IN 0 ALIAS NALIZV EXCLUSIVE 
USE firma IN 0

   DO idel WITH (kkockax)   
   DO idel WITH (kkockax2)   
   DO idel WITH (kkockax3)   
   DO idel WITH (kkockax4)   
   DO idel WITH (kkockax5)   

SELECT NALIZV   
COPY STRUCTURE TO &KKOCKA   
COPY STRUCTURE TO &KKOCKA3   
   
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
   
IF TOBJEKAT='V'

KFAK='FAK'+TTVREDNI
KfakG='FAKG'+TTVREDNI

IF TSIFARNIK<>'  '
  KROB='ROB'+ALLTRIM(TSIFARNIK)
ELSE
   KROB='ROB'
ENDIF

ELSE

KFAK='TMFAK'+TTVREDNI
KfakG='TMFAKG'+TTVREDNI


IF TSIFARNIK<>'  '
  KROB='MROB'+ALLTRIM(TSIFARNIK)
ELSE
   KROB='ROB'
ENDIF

ENDIF

USE &KKSEMA ALIAS KSEMA IN 0 ORDER 1
USE &KKALPRN ALIAS KALPRN IN 0 ORDER 1
*------------racuni-------------
USE &KFAKG IN 0 ALIAS FAKG 
USE &KFAK IN 0 ALIAS FAK ORDER 1
SELECT FAKG
GO TOP
DO WHILE.NOT.EOF()
   MBRKAL=BRKAL
   MFVRSTA=FVRSTA
   mdatdok=datdok
   MPRENOS=PRENOS
   MBRNAL=BRNAL
   MDATDOK=DATDOK
   IF prenos=' '
      SELECT FAK
      SEEK MBRKAL
      IF FOUND()
         MMALVRED=0
         DO WHILE.NOT.EOF()
            IF BRKAL<>MBRKAL
               EXIT
            ENDIF
            IF TOBJEKAT='V'
               MMALVRED=MMALVRED+VELVRED-RABAT
            ELSE
               MMALVRED=MMALVRED+MALVRED-RABAT
            ENDIF
            SKIP
         ENDDO   
         SELECT KOCKA
         APPEND BLANK
         REPLACE BRNAL WITH MBRNAL
         REPLACE DOK WITH MDOK
         REPLACE DUG WITH MMALVRED
         REPLACE K3 WITH 'FAK'
         replace datdok WITH mdatdok
      ENDIF     
   endif
   SELECT FAKG   
   SKIP
ENDDO   
SELECT FAK
USE
SELECT FAKG
USE
*----------------KNJIGA PRIHODA-------------------
USE TMP0 IN 0
SELECT TMP0
COPY TO &KKOCKA4 FOR DOK=MDOK.AND.(proo<>0.or.pron<>0.or.prob<>0.or.uslp<>0.or.uslb<>0)
USE
USE &KKOCKA4 IN 0 ALIAS KOCKA4 EXCLU
SELECT KOCKA4
INDEX ON BRNAL  TAG BRNAL
SET ORDER TO 1
SELECT KOCKA
GO TOP
DO WHILE.NOT.EOF()
   M2KONTO=KONTO
   MBRNAL=BRNAL
   mdatdok=datdok
   SELECT KOCKA4
   SEEK MBRNAL
   IF FOUND()
      MDUG=0
      MPOT=0
      DO WHILE.NOT.EOF()
         IF BRNAL<>MBRNAL 
            EXIT
         ENDIF   
*         IF KONTO=M2KONTO
            MDUG=MDUG+proo+pron+prob+uslp+uslb
*         ENDIF
         REPLACE KONTO WITH '9999999999'
         SKIP
      ENDDO      
      SELECT KOCKA
      REPLACE UDUG WITH MDUG
   ENDIF 
   SELECT KOCKA
   SKIP
ENDDO
SELECT KOCKA4
DELETE ALL FOR KONTO='9999999999'
PACK

IF RECCOUNT()>0
   COPY TO &KKOCKA5 
      USE &KKOCKA5 IN 0 ALIAS KOCKA5 EXCLU
      SELECT KOCKA5
      GO TOP
      DO WHILE.NOT.EOF()
         MBRNAL=BRNAL
         MUDUG=MALVRED
         MDATDOK=DATDOK
         SELECT KOCKA
         APPEND BLANK
         REPLACE BRNAL WITH MBRNAL
         REPLACE UDUG WITH MUDUG
         REPLACE DATDOK WITH MDATDOK
         SELECT KOCKA5
         SKIP
      ENDDO   
      SELECT KOCKA5
      USE
ENDIF      
SELECT KOCKA4
USE
SELECT KOCKA
GO TOP
DO WHILE.NOT.EOF()
   REPLACE SALDO WITH DUG
   REPLACE USALDO WITH UDUG
   REPLACE DSALDO WITH SALDO-USALDO
   SKIP
ENDDO   
GO TOP

IF MSVE=1
   *REPORT FORM TVGKSLAG PREVIEW
   
   mfile='TVGKSLAG'   
   USLOV=""
   DO printer_bullzip WITH mdata02,mfiLE,USLOv   
   
   
ELSE
   *REPORT FORM TVGKSLAG PREVIEW FOR ABS(DSALDO)>0.1

   mfile='TVGKSLAG'   
   USLOV="ABS(DSALDO)>0.1"
   DO printer_bullzip WITH mdata02,mfiLE,USLOv   
   
   
ENDIF

CLOSE ALL TABLES
SET EXACT OFF
POP KEY