PUSH KEY CLEAR
SET EXACT ON
IF LEN(TTVREDNI)=1
   MDOK=ALLTRIM(TOBJEKAT+TTVREDNI)+' '
ELSE
   MDOK=ALLTRIM(TOBJEKAT+TTVREDNI)
ENDIF
MGLKONTO=TKONTO
MGLKONTOK=TKONTOK
KKNALIZV=MDATA01+'\NALIZV'+OPERATER+'.DBF'
KKNALIZVX=MDATA01+'\NALIZV'+OPERATER+'.CDX'
KNALIZV=MDATA01+'\NALIZV'+OPERATER
KNALIZVX=MDATA01+'\NALIZV'+OPERATER


DO IDEL WITH (KKNALIZV)
DO IDEL WITH (KKNALIZVX)
DO IBAZE WITH KNALIZV,'NALIZV'
DO IIND WITH KNALIZV,'KONTO+DTOS(DATDOK)','BRNAL','DTOS(DATDOK)',;
             'KONTO+SIFRA+DTOS(DATDOK)','SIFRA+DTOS(DATDOK)','SIFRA+BRRAC+DTOS(DATDOK)'

USE &KNALIZV IN 0 ALIAS NALIZV EXCLUSIVE 
USE firma IN 0

   DO idel WITH (kkockax)   
   DO idel WITH (kkockax2)   
   DO idel WITH (kkockax3)   
   DO idel WITH (kkockax4)   
   DO idel WITH (kkockax5)   

SELECT NALIZV   
COPY STRUCTURE TO &KKOCKA   
COPY STRUCTURE TO &KKOCKA3   
   
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
   
IF TOBJEKAT='V'


KKAL='KAL'+TTVREDNI+'.DBF'
KKALG='KALG'+TTVREDNI+'.DBF'
KTVNIV='TVNIV'+TTVREDNI+'.DBF'
KTM='TVTM'+TTVREDNI+'.DBF'

IF TSIFARNIK<>'  '
  KROB='ROB'+ALLTRIM(TSIFARNIK)+'.DBF'
ELSE
   KROB='ROB.DBF'
ENDIF

ELSE



SKKALP='TMKAL'+TTVREDNI

KKAL='TMKAL'+TTVREDNI+'.DBF'
KKALG='TMKALG'+TTVREDNI+'.DBF'
KTVNIV='TMNIV'+TTVREDNI+'.DBF'
KTM='TM'+TTVREDNI+'.DBF'

IF TSIFARNIK<>'  '
  KROB='MROB'+ALLTRIM(TSIFARNIK)+'.DBF'
ELSE
   KROB='ROB.DBF'
ENDIF

ENDIF

USE &KKSEMA ALIAS KSEMA IN 0 ORDER 1
USE &KKALPRN ALIAS KALPRN IN 0 ORDER 1
*------------KALKULACIJE---------------
USE &KKALG IN 0 ALIAS KALG 
USE &KKAL IN 0 ALIAS KAL ORDER 1

SELECT KALG
GO TOP
DO WHILE.NOT.EOF()
   MBRNAL=BRNAL
   MBRKAL=BRKAL
   MFVRSTA=FVRSTA
   mdatdok=datdok
   SELECT KALG
   MDATDOK=DATDOK
   SELECT KAL
   SEEK MBRKAL
   IF FOUND()
      MMALVRED=0
      DO WHILE.NOT.EOF()
         IF BRKAL<>MBRKAL
            EXIT
         ENDIF
         IF TOBJEKAT='V'
            MMALVRED=MMALVRED+VELVRED
         ELSE
            MMALVRED=MMALVRED+MALVRED
         ENDIF
         SKIP
      ENDDO   
      SELECT KOCKA
      APPEND BLANK
      REPLACE BRNAL WITH MBRNAL
      REPLACE BRKAL WITH MBRKAL
      REPLACE DOK WITH MDOK
      REPLACE DUG WITH MMALVRED
      REPLACE K3 WITH 'KAL'
      replace datdok WITH mdatdok
   ENDIF     
   SELECT KALG   
   SKIP
ENDDO   
SELECT KAL
USE
SELECT KALG
USE
*--------NIVELACIJE-------------------

USE &KTVNIV IN 0 ALIAS NIV
SELECT NIV
SET ORDER TO 3
TOTAL ON BRKAL TO &KKOCKA2 FIELDS SIZNOS,VELVRED,MALVRED
USE
USE &KKOCKA2 IN 0 ALIAS KOCKA2 EXCLU
SELECT KOCKA2
GO TOP

DO WHILE.NOT.EOF()
   MBRNAL=BRNAL
   MBRKAL=BRKAL
   mdatdok=datdok
   IF TOBJEKAT='V'
      MMALVRED=VELVRED-SIZNOS
   ELSE
      MMALVRED=MALVRED-SIZNOS
   ENDIF
   
   SELECT KOCKA
   APPEND BLANK
   REPLACE BRNAL WITH MBRNAL
   REPLACE BRKAL WITH MBRKAL   
   REPLACE DOK WITH MDOK
   REPLACE DUG WITH MMALVRED
   REPLACE K3 WITH 'NIV'
   replace datdok WITH mdatdok
   SELECT KOCKA2
   SKIP
ENDDO   
SELECT KOCKA2
USE

*----------------KEPU KNJIGA--------------------
USE &KTM IN 0 ALIAS TM
SELECT TM
COPY TO &KKOCKA4 FOR UKNAB<>0
USE
USE &KKOCKA4 IN 0 ALIAS KOCKA4 EXCLU
SELECT KOCKA4
INDEX ON BRNAL TAG BRNAL
SET ORDER TO 1

SELECT KOCKA
GO TOP
DO WHILE.NOT.EOF()
   M2KONTO=KONTO
   MBRNAL=BRNAL
   mdatdok=datdok
   SELECT KOCKA4
   SEEK MBRNAL
   IF FOUND()
      MDUG=0
      MPOT=0
      DO WHILE.NOT.EOF()
         IF BRNAL<>MBRNAL 
            EXIT
         ENDIF   
         MDUG=MDUG+UKNAB
         REPLACE KONTO WITH '9999999999'
         SKIP
      ENDDO      
      SELECT KOCKA
      REPLACE UDUG WITH MDUG
   ENDIF 
   SELECT KOCKA
   SKIP
ENDDO
SELECT KOCKA4
DELETE ALL FOR KONTO='9999999999'
PACK

IF RECCOUNT()>0
      SELECT KOCKA4
      GO TOP
      DO WHILE.NOT.EOF()
         MKONTO=KONTO
         MBRNAL=BRKAL
         MBRKAL=BRKAL
         MUDUG=UKNAB
         MDATDOK=DATDOK
         SELECT KOCKA
         APPEND BLANK
         REPLACE BRNAL WITH MBRNAL
         REPLACE BRKAL WITH MBRKAL
         REPLACE UDUG WITH MUDUG
         REPLACE DATDOK WITH MDATDOK
         SELECT KOCKA4
         SKIP
      ENDDO   
ENDIF      
SELECT KOCKA4

USE
SELECT KOCKA
GO TOP

DO WHILE.NOT.EOF()
   REPLACE SALDO WITH DUG
   REPLACE USALDO WITH UDUG
   REPLACE DSALDO WITH SALDO-USALDO
   SKIP
ENDDO   
GO TOP

*REPORT FORM TVGKSLAGKEPU PREVIEW FOR dSALDO<>0

   mfile='TVGKSLAGKEPU'   
   USLOV="dSALDO<>0"
   DO printer_bullzip WITH mdata02,mfiLE,USLOv   


CLOSE ALL TABLES
SET EXACT OFF
POP KEY