PARAMETERS SVE
PUSH KEY CLEAR
SET EXACT ON
MSVE=SVE
IF LEN(TTVREDNI)=1
   MDOK=ALLTRIM(TOBJEKAT+TTVREDNI)+' '
ELSE
   MDOK=ALLTRIM(TOBJEKAT+TTVREDNI)
ENDIF
MGLKONTO=TKONTO
KKNALIZV=MDATA01+'\NALIZV'+OPERATER+'.DBF'
KKNALIZVX=MDATA01+'\NALIZV'+OPERATER+'.CDX'
KNALIZV=MDATA01+'\NALIZV'+OPERATER
KNALIZVX=MDATA01+'\NALIZV'+OPERATER

DO IDEL WITH (KKNALIZV)
DO IDEL WITH (KKNALIZVX)
DO IBAZE WITH KNALIZV,'NALIZV'
DO IIND WITH KNALIZV,'KONTO+DTOS(DATDOK)','BRNAL','DTOS(DATDOK)',;
             'KONTO+SIFRA+DTOS(DATDOK)','SIFRA+DTOS(DATDOK)','SIFRA+BRRAC+DTOS(DATDOK)'

USE &KNALIZV IN 0 ALIAS NALIZV EXCLUSIVE 
USE firma IN 0

   DO idel WITH (kkockax)   
   DO idel WITH (kkockax2)   
   DO idel WITH (kkockax3)   
   DO idel WITH (kkockax4)   
   DO idel WITH (kkockax5)   
   
SELECT NALIZV   
COPY STRUCTURE TO &KKOCKA   
COPY STRUCTURE TO &KKOCKA3   
   
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
   
IF TOBJEKAT='V'


KFAK='FAK'+TTVREDNI
KFAKG='FAKG'+TTVREDNI


ELSE

KFAK='TMFAK'+TTVREDNI
KFAKG='TMFAKG'+TTVREDNI


ENDIF

USE &KKSEMA ALIAS KSEMA IN 0 ORDER 1
USE &KFAKPRN ALIAS FAKPRN IN 0 ORDER 1
*------------------FAKTURE----------------------
USE &KFAKG IN 0 ALIAS FAKG 
USE &KFAK IN 0 ALIAS FAK ORDER 1

SELECT FAKG
GO TOP
DO WHILE.NOT.EOF()
IF INTERNA=' '.AND.PRENOS=' '
   MBRKAL=BRKAL
   MFVRSTA=FVRSTA
   mdatdok=datdok
   SELECT FAKPRN 
   SEEK MFVRSTA
   IF FOUND()
      MSEMA=SEMA
   ELSE
      MSEMA=SPACE(4) 
   ENDIF
   SELECT KSEMA 
   SEEK MSEMA
   IF FOUND()
      MKONTO=K_FAK
   ELSE
      MKONTO=SPACE(10)      
   ENDIF
   SELECT FAKG
   MBRNAL=BRNAL
   MDATDOK=DATDOK

   SELECT FAK
   SEEK MBRKAL
   IF FOUND()
      MMALVRED=0
      DO WHILE.NOT.EOF()
         IF BRKAL<>MBRKAL
            EXIT
         ENDIF
         IF TOBJEKAT='V'
            MMALVRED=MMALVRED+VELVRED+POREZ-RABAT
         ELSE
            MMALVRED=MMALVRED+MALVRED
         ENDIF
         SKIP
      ENDDO   
      SELECT KOCKA
      APPEND BLANK
      REPLACE BRNAL WITH MBRNAL
      REPLACE DOK WITH MDOK
      REPLACE POT WITH MMALVRED
      REPLACE KONTO WITH MKONTO
      REPLACE K3 WITH 'FAK'
      replace datdok WITH mdatdok
   ENDIF     
ENDIF
   SELECT FAKG   
   SKIP
ENDDO   
SELECT FAK
USE
SELECT FAKG
USE

*----------------analitika-------------------

USE ANAL1 IN 0 ALIAS ANAL
SELECT ANAL
COPY TO &KKOCKA4 FOR DOK=MDOK.AND.DUG<>0.AND.DATDOK<>TDAT0
USE
USE &KKOCKA4 IN 0 ALIAS KOCKA4 EXCLU
SELECT KOCKA4
INDEX ON BRNAL  TAG BRNAL
SET ORDER TO 1
SELECT KOCKA
GO TOP
DO WHILE.NOT.EOF()
   M2KONTO=KONTO
   MBRNAL=BRNAL
   mdatdok=datdok
   SELECT KOCKA4
   SEEK MBRNAL
   IF FOUND()
      MDUG=0
      DO WHILE.NOT.EOF()
         IF BRNAL<>MBRNAL 
            EXIT
         ENDIF   
         IF KONTO=M2KONTO
            MDUG=MDUG+DUG
         ENDIF
         REPLACE KONTO WITH '9999999999'
         SKIP
      ENDDO      
      SELECT KOCKA
      REPLACE DUG WITH MDUG
   ENDIF 
   SELECT KOCKA
   SKIP
ENDDO
SELECT KOCKA4
DELETE ALL FOR KONTO='9999999999'
PACK
IF RECCOUNT()>0
   DO IDEL WITH (KKOCKAX5)
  
   COPY TO &KKOCKA5 
  
   USE &KKOCKA5 IN 0 ALIAS KOCKA5 EXCLU
   SELECT KOCKA5
   GO TOP
   DO WHILE.NOT.EOF()
      MKONTO=KONTO
      MBRNAL=BRNAL
      MDUG=DUG
      MDATDOK=DATDOK
      SELECT KOCKA
      APPEND BLANK
      REPLACE BRNAL WITH MBRNAL
      REPLACE DUG WITH MDUG
      REPLACE DATDOK WITH MDATDOK
      REPLACE KONTO WITH MKONTO
      SELECT KOCKA5
      SKIP
   ENDDO   
   SELECT KOCKA5
   USE
ENDIF      
SELECT KOCKA4
USE
SELECT KOCKA
GO TOP
DO WHILE.NOT.EOF()
   REPLACE SALDO WITH DUG-POT
   SKIP
ENDDO   
GO TOP

*REPORT FORM TVGKSLAGA PREVIEW FOR SALDO<>0
   mfile='TVGKSLAGA'   
   USLOV="SALDO<>0"
   DO printer_bullzip WITH mdata02,mfiLE,USLOv   


CLOSE ALL TABLES
SET EXACT OFF
POP KEY