PUSH KEY CLEAR
MDAT0=TVKARTROK.TXTDAT0.VALUE
MDAT1=TVKARTROK.TXTDAT1.VALUE
MFVRSTA=STR(VAL(ALLTRIM(TVKARTROK.TXTFVRSTA.VALUE)),3,0)
IF MFVRSTA='  0'
   MFVRSTA='   '
ENDIF
MSIFRA=STR(VAL(ALLTRIM(TVKARTROK.TXTSIFRA.VALUE)),5,0)
IF MSIFRA='    0'
   MSIFRA='     '
ENDIF
MPRENOS=TVKARTROK.TXTPRENOS.VALUE
Minterna=TVKARTROK.TXTINTERNA.VALUE
SELECT DATUMI
MPAR3=PAR3
REPLACE DAT0 WITH MDAT0
REPLACE DAT1 WITH MDAT1
SELECT ROB
TVKARTROK.RELEASE

DO ROBAKARTICAROK WITH MRSIF,MDAT0,MDAT1,MFVRSTA,MSIFRA,MINTERNA,MPRENOS
POP KEY