PUSH KEY CLEAR
MDOK=TOBJEKAT+TTVREDNI
KKNALIZV=MDATA01+'\NALIZV'+OPERATER+'.DBF'
KKNALIZVX=MDATA01+'\NALIZV'+OPERATER+'.CDX'
KNALIZV=MDATA01+'\NALIZV'+OPERATER
KNALIZVX=MDATA01+'\NALIZV'+OPERATER


DO IDEL WITH (KKNALIZV)
DO IDEL WITH (KKNALIZVX)
DO IBAZE WITH KNALIZV,'NALIZV'
DO IIND WITH KNALIZV,'KONTO+DTOS(DATDOK)','BRNAL','DTOS(DATDOK)',;
             'KONTO+SIFRA+DTOS(DATDOK)','SIFRA+DTOS(DATDOK)','SIFRA+BRRAC+DTOS(DATDOK)'

USE &KNALIZV IN 0 ALIAS NALIZV EXCLUSIVE 
USE firma IN 0

   DO idel WITH (kkockax)   
   DO idel WITH (kkockax2)   
   DO idel WITH (kkockax3)   
   DO idel WITH (kkockax4)   
   DO idel WITH (kkockax5)   

SELECT NALIZV   
COPY STRUCTURE TO &KKOCKA   
COPY STRUCTURE TO &KKOCKA3   
   
USE &KKOCKA IN 0 ALIAS KOCKA EXCLU
   
IF TOBJEKAT='V'


KKAL='KAL'+TTVREDNI
KKALG='KALG'+TTVREDNI
KFAK='FAK'+TTVREDNI
KFAKG='FAKG'+TTVREDNI
KTVNIV='TVNIV'+TTVREDNI
KTM='TVTM'+TTVREDNI

IF TSIFARNIK<>'  '
  KROB='ROB'+ALLTRIM(TSIFARNIK)
ELSE
   KROB='ROB'
ENDIF

ELSE



SKKALP='TMKAL'+TTVREDNI

KKAL='TMKAL'+TTVREDNI
KKALG='TMKALG'+TTVREDNI
KFAK='TMFAK'+TTVREDNI
KFAKG='TMFAKG'+TTVREDNI
KTVNIV='TMNIV'+TTVREDNI
KTM='TM'+TTVREDNI

IF TSIFARNIK<>'  '
  KROB='MROB'+ALLTRIM(TSIFARNIK)
ELSE
   KROB='ROB'
ENDIF

ENDIF
   if tfpossif='D'.AND.TNEZAJEDNO<>'D'

  KROB='ROBV'+ALLTRIM(TTVREDNI)
ENDIF

*------------KALKULACIJE---------------
USE &KKALG IN 0 ALIAS KALG 
USE &KKAL IN 0 ALIAS KAL ORDER 1
SELECT KALG
GO TOP
DO WHILE.NOT.EOF()
   MBRKAL=BRKAL
   MFVRSTA=FVRSTA
   mdatdok=datdok
   MBRNAL=BRNAL
   MDATDOK=DATDOK
   SELECT KAL
*   LOCATE FOR BRKAL=MBRKAL
   SEEK MBRKAL
   IF FOUND()
      MMALVRED=0
      DO WHILE.NOT.EOF()
         IF BRKAL<>MBRKAL
            EXIT
         ENDIF
         IF TOBJEKAT='V'
            MMALVRED=MMALVRED+VELVRED
         ELSE
            MMALVRED=MMALVRED+MALVRED
         ENDIF
         SKIP
      ENDDO   
      SELECT KOCKA
      APPEND BLANK
      REPLACE BRNAL WITH MBRNAL
      REPLACE DUG WITH MMALVRED
      REPLACE K3 WITH 'KAL'
      replace datdok WITH mdatdok
   ENDIF     
   SELECT KALG   
   SKIP
ENDDO   
SELECT KAL
USE
SELECT KALG
USE
*--------NIVELACIJE-------------------

USE &KTVNIV IN 0 ALIAS NIV
SELECT NIV
SET ORDER TO 1
TOTAL ON BRKAL TO &KKOCKA2 FIELDS SIZNOS,VELVRED,MALVRED
USE
USE &KKOCKA2 IN 0 ALIAS KOCKA2 EXCLU
SELECT KOCKA2
GO TOP
DO WHILE.NOT.EOF()
   MBRNAL=BRNAL
   mdatdok=datdok
   IF TOBJEKAT='V'
      MMALVRED=VELVRED-SIZNOS
   ELSE
      MMALVRED=MALVRED-SIZNOS
   ENDIF
   SELECT KOCKA
   APPEND BLANK
   REPLACE BRNAL WITH MBRNAL
   REPLACE DUG WITH MMALVRED
   REPLACE K3 WITH 'NIV'
   replace datdok WITH mdatdok
   SELECT KOCKA2
   SKIP
ENDDO   
SELECT KOCKA2
USE
*------------------FAKTURE----------------------
USE &KFAKG IN 0 ALIAS FAKG 
USE &KFAK IN 0 ALIAS FAK ORDER 1
SELECT FAKG
GO TOP
DO WHILE.NOT.EOF()
   MBRKAL=BRKAL
   MFVRSTA=FVRSTA
   mdatdok=datdok
   MBRNAL=BRNAL
   MDATDOK=DATDOK
   SELECT FAK
 *  LOCATE FOR BRKAL=MBRKAL
   SEEK MBRKAL
   IF FOUND()
      MMALVRED=0
      DO WHILE.NOT.EOF()
         IF BRKAL<>MBRKAL
            EXIT
         ENDIF
         IF TOBJEKAT='V'
            MMALVRED=MMALVRED+VELVRED+POREZ-RABAT-RABAT2
         ELSE
            MMALVRED=MMALVRED+MALVRED-RABAT-RABAT2
         ENDIF
         SKIP
      ENDDO   
      SELECT KOCKA
      APPEND BLANK
      REPLACE BRNAL WITH MBRNAL
      REPLACE POT WITH MMALVRED
      REPLACE K3 WITH 'FAK'
      replace datdok WITH mdatdok
   ENDIF     
   SELECT FAKG   
   SKIP
ENDDO   
SELECT FAK
USE
SELECT FAKG
USE
*----------------KEPU--------------------
USE &KTM IN 0 ALIAS TM
SELECT TM
COPY TO &KKOCKA4
USE
USE &KKOCKA4 IN 0 EXCLUSIVE ALIAS KOCKA4
SELECT KOCKA4
INDEX ON BRNAL  TAG BRNAL
SET ORDER TO 1
SELECT KOCKA
GO TOP
DO WHILE.NOT.EOF()
   MBRNAL=BRNAL
   mdatdok=datdok
   SELECT KOCKA4
   SEEK MBRNAL
   IF FOUND()
      MDUG=0
      MPOT=0
      DO WHILE.NOT.EOF()
         IF BRNAL<>MBRNAL 
            EXIT
         ENDIF   
         IF VREDPROD<>0
            MPOT=MPOT+VREDPROD
         ELSE
            MDUG=MDUG+UKNAB
            MPOT=MPOT+VREDPROD
         ENDIF
         REPLACE BRKAL WITH '999999'
         SKIP
      ENDDO      
      SELECT KOCKA
      REPLACE UDUG WITH MDUG
      REPLACE UPOT WITH MPOT
   ENDIF 
   SELECT KOCKA
   SKIP
ENDDO
SELECT KOCKA4
DELETE ALL FOR BRKAL='999999'
PACK
IF RECCOUNT()>0
   COPY TO &KKOCKA5 
   IF FILE(KKOCKA5)
      USE &KKOCKA5 IN 0 EXCLUSIVE ALIAS KOCKA5
      SELECT KOCKA5
      GO TOP
      DO WHILE.NOT.EOF()
         MBRNAL=BRNAL
         MUDUG=UKNAB
         MUPOT=VREDPROD
         MDATDOK=DATDOK
         SELECT KOCKA
         APPEND BLANK
         REPLACE BRNAL WITH MBRNAL
         REPLACE UDUG WITH MUDUG
         REPLACE UPOT WITH MUPOT
         REPLACE DATDOK WITH MDATDOK
         SELECT KOCKA5
         SKIP
      ENDDO   
      SELECT KOCKA5
      USE
   ENDIF
ENDIF      
SELECT KOCKA4
USE
SELECT KOCKA
GO TOP
DO WHILE.NOT.EOF()
   REPLACE SALDO WITH DUG-POT
   REPLACE USALDO WITH UDUG-UPOT
   REPLACE DSALDO WITH SALDO-USALDO
   SKIP
ENDDO   
GO TOP
PUSH KEY CLEAR
*REPORT FORM TVKEPUSLAG PREVIEW FOR DSALDO<>0

   mfile='TVKEPUSLAG'   
   USLOV="DSALDO<>0"
   DO printer_bullzip WITH mdata02,mfiLE,USLOv   


POP KEY

CLOSE ALL TABLES
POP KEY