SET PROCEDURE TO PREGLED
PUSH KEY CLEAR
  DO ROPOC WITH 'ZOR'
  SET ORDER TO
  GO TOP
  SELECT ZOR
  DO WHILE.NOT.EOF()
     MM=Ppolje1
     DO ROUZMI WITH MM,'ZOR'
     SKIP
  ENDDO
SET PROCEDURE TO 
SELECT PREGLED
DO FORM PREGLED
SELECT PREGLED
USE
SELECT ZOR
POP KEY