PUSH KEY CLEAR
SET DEFAULT TO &MDATA00
IF FILE('HELPN.DBF')
   USE HELPN IN 0 EXCLUSIVE
   SELECT HELPN
   ZAP
   aHELPN=Mtxt+'HELPN.DBF'
   APPEND FROM &AHELPN
ENDIF
USE
SET DEFAULT TO &MBAZNI
GLAVNA00.Release
POP KEY