PARAMETERS VRSTAOBR  
SET STEP ON 
MVRSTA=VRSTAOBR
SELECT VP
MPIB=PIB
MGRUPA=GRUPA
*-----------TABELA OBRACUNA------------
select VPOBRAC
MCENOVNIK=CENOVNIK
MBROBRAC=BROBRAC

*------TABELA CENA

select VPCENE
SET ORDER TO 1
SEEK MCENOVNIK

mpstanje=pstanje
mzstanje=zstanje

APOC='ST'+ALLTRIM(STR(MPSTANJE,2,0))
AKRAJ='ST'+ALLTRIM(STR(MZSTANJE,2,0))

MMES=MZSTANJE-MPSTANJE

mEvaluta=valuta
mdatOD=datod
mdatDO=datdo
mEdatum=DATDO

mcvoda=cvoda
mcdvoda=cdvoda
mckanal=ckanal
mcdkanal=cdkanal
MPROCPOR=PROCPOR
mprocakont=procakont
MCTOPLANA=CTOPLANA
MCGROBLJE=CGROBLJE
MCSMECE=CSMECE

DECLARE MCS[10],MNCS[10]
FOR I=1 TO 10
   MMCS='CS'+ALLTRIM(STR(I,2,0))
   MCS[I]=&MMCS
   MMNCS='NCS'+ALLTRIM(STR(I,2,0))
   MNCS[I]=&MMNCS
NEXT
*-----------OBRACUN 1 GRADJANI----------------------
SELECT vp
MGOD=SUBSTR(STR(YEAR(MDATDO),4,0),4,1)
MBRRAC=SUBSTR(PIB,1,7)+'-'+ALLTRIM(STR(MES,2,0))+'-'+MGOD
AMODEL=SUBSTR(PIB,1,7)+ALLTRIM(STR(MES,2,0))+MGOD
 
M1=VAL(AMODEL)
M2=(M1*100/97)-INT(M1*100/97)
M3=ROUND(97*M2,0)
M4=98-M3
IF M4<=9
   M4='0'+STR(M4,1,0)
ELSE
   M4=STR(M4,2,0)
ENDIF      
REPLACE MODEL WITH M4+'-'+ALLTRIM(AMODEL)
REPLACE BRRAC WITH MBRRAC


IF MVRSTA=1

ABRNAL='O'+ALLTRIM(STR(MBROBRAC,2,0))+MGRUPA
select VPUPL
set order to 1
select VP
SET ORDER TO 1
SEEK MPIB
IF FOUND()
   REPLACE ODUG WITH 0
   REPLACE OPOT WITH 0
   REPLACE OSALDO WITH 0
   REPLACE RABAT WITH 0
   REPLACE KAMATA WITH 0
   REPLACE OSTALO WITH 0
   REPLACE SVEGA WITH 0
   select VPUPL
   seek MPIB
   if found()
      do while.not.eof()
         if PIB<>MPIB
            exit
         endif   
         *---BRISANJE NALOGA
         IF BRNAL=ABRNAL
            REPLACE DUG WITH 0
            REPLACE GRUPA WITH ' '
            REPLACE BRNAL WITH ' ' 
         ENDIF   
         skip
      enddo 
      SELECT VP
   ENDIF
ENDIF
*-----------OBRACUN KAMATE---------------
select VPUPL
set order to 
SELECT VP
USE VPKAM IN 0 EXCLU
SELECT VPKAM
ZAP
DO VPKAM WITH MPIB,MDATOD,MDATDO
SELECT VPKAM
*--------PRENOS KAMATE------------------
SET ORDER TO 1
DO VPPRENKAM WITH MPIB,MDATOD,MDATDO,MEVALUTA
SELECT VPKAM
USE
*------POPUNJAVANJE OSTALIH PODATAKA-----

SELECT VP
set procedure to
SELECT VP
REPLACE MESECI WITH MMES      
*--------OBRACUN PAUSAL------------------
IF PAUSAL=' '
   REPLACE POT WITH &AKRAJ-&APOC
ELSE
   REPLACE POT WITH MMES*MESPAUSAL
ENDIF
IF POT<0
   REPLACE POT WITH 0
ENDIF   

REPLACE POC WITH &APOC
REPLACE KRAJ WITH &AKRAJ
REPLACE UKPOT WITH KRAJ-POC
REPLACE VODA WITH 0
*------------OBRACUN ZA VODU------------------   
IF POT>0
   IF PVODA<>' '
      REPLACE VODA WITH POT*MCVODA*(100-POPPROC)/100
      REPLACE DOPV WITH POT*MCDVODA*(100-POPPROC)/100    
   ELSE
      REPLACE VODA WITH 0
      REPLACE DOPV WITH 0
   ENDIF
   *------------OBRACUN ZA KANALIZACIJU
   IF PKANAL<>' '
      REPLACE KAN WITH POT*MCKANAL*(100-POPKAN)/100
      REPLACE DOPK WITH POT*MCDKANAL*(100-POPKAN)/100    
   ELSE
      REPLACE KAN WITH 0
      REPLACE DOPK WITH 0   
   ENDIF
ELSE
   REPLACE VODA WITH 0
   REPLACE DOPV WITH 0
   REPLACE KAN WITH 0
   REPLACE DOPK WITH 0   
ENDIF

IF Psmece<>' '
   REPLACE smece WITH POV*mcsmece
ELSE
   REPLACE smece WITH 0
ENDIF

IF PTOPLANA<>' '
   REPLACE TOPLANA WITH POVTOP*MCTOPLANA
ELSE
   REPLACE TOPLANA WITH 0
ENDIF

IF PGROBLJE<>' '
   REPLACE GROBLJE WITH MCGROBLJE
ELSE
   REPLACE GROBLJE WITH 0
ENDIF

*----------UKUPNI PODACI------------------   

MVODA=VODA
MDOPV=DOPV
MKAN=KAN
MDOPK=DOPK
MSMECE=SMECE
MTOPLANA=TOPLANA
MGROBLJE=GROBLJE
MUKUPNO=VODA+DOPV+KAN+DOPK+TOPLANA+GROBLJE+SMECE
   
MSOC=ROUND(MUKUPNO*POPSOC/100,2)
   
REPLACE UKUPNO WITH MUKUPNO   
REPLACE PROCPOR WITH MPROCPOR
MPOREZ=ROUND((UKUPNO-MSOC)*PROCPOR/100,2)
REPLACE POREZ WITH MPOREZ
MOSNOV=UKUPNO-MSOC+POREZ
IF MOSNOV>0.AND.MMES>0   
   REPLACE AKONT WITH ROUND( (100+MPROCAKONT)*MOSNOV/MMES/100,0)
ELSE
   REPLACE AKONT WITH 0
ENDIF   
MUKUPNO=UKUPNO

SELECT VPUPL
SEEK MPIB

MPRDUG=0
MUPLAC=0
mispr=0
*----------PRETRAZIVANJE UPLATA ZA OSTALIM PODACIMA--------  
if found()
   do while.not.eof()
      if PIB<>mPIB
         exit
      endif
      if datum<mdatod
         mprdug=mprdug+dug-pot
      endif    
      if datum>=mdatod.and.datum<=mdatdo
         IF GRUPA='ISP'.OR.SUBSTR(GRUPA,1,2)='KO'.OR.SUBSTR(GRUPA,1,2)='SP'.OR.SUBSTR(GRUPA,1,2)='ST'
            MISPR=MISPR+DUG
         ENDIF      
      ENDIF
      if datum>=mdatod.and.datum<=mdatdo
         mUPLAC=MUPLAC+POT
         mdATUM=datum 
      endif
      skip
   enddo      
endif
*----------POPUNJAVANJE GLAVNE TABELE----------
SELECT VP
REPLACE UPLAC WITH MUPLAC
REPLACE DUG WITH MPRDUG
REPLACE OSTALO WITH MISPR
REPLACE SOC WITH -MSOC
*----------POPUNJAVANJE TABELE UPLATA----------
SELECT VPUPL   
IF MVODA<>0
   SELECT VPUPL 
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE DUG WITH MVODA  
   REPLACE DATUM WITH MEDATUM
   REPLACE VALUTA WITH MEVALUTA
   REPLACE GRUPA WITH 'VOD'
   replace opis WITH ' VODA '+GRUPA
   REPLACE BRNAL WITH ABRNAL      
ENDIF

IF MDOPV<>0
   SELECT VPUPL 
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE DUG WITH MDOPV  
   REPLACE DATUM WITH MEDATUM
   REPLACE VALUTA WITH MEVALUTA
   REPLACE GRUPA WITH 'DOV'
   replace opis WITH ' DOV '+GRUPA
   REPLACE BRNAL WITH ABRNAL      
ENDIF

IF MKAN<>0
   SELECT VPUPL 
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE DUG WITH MKAN  
   REPLACE DATUM WITH MEDATUM
   REPLACE VALUTA WITH MEVALUTA
   REPLACE GRUPA WITH 'KAN'
   replace opis WITH ' KAN '+GRUPA
   REPLACE BRNAL WITH ABRNAL      
ENDIF

IF MDOPK<>0
   SELECT VPUPL 
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE DUG WITH MDOPK  
   REPLACE DATUM WITH MEDATUM
   REPLACE VALUTA WITH MEVALUTA
   REPLACE GRUPA WITH 'DOK'
   replace opis WITH ' DOK '+GRUPA
   REPLACE BRNAL WITH ABRNAL      
ENDIF

IF MSMECE<>0
   SELECT VPUPL 
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE DUG WITH MSMECE
   REPLACE DATUM WITH MEDATUM
   REPLACE VALUTA WITH MEVALUTA
   REPLACE GRUPA WITH 'SME'
   replace opis WITH ' SME '+GRUPA
   REPLACE BRNAL WITH ABRNAL      
ENDIF

IF MTOPLANA<>0
   SELECT VPUPL 
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE DUG WITH MTOPLANA  
   REPLACE DATUM WITH MEDATUM
   REPLACE VALUTA WITH MEVALUTA
   REPLACE GRUPA WITH 'TOP'
   replace opis WITH ' TOP '+GRUPA
   REPLACE BRNAL WITH ABRNAL      
ENDIF

IF MGROBLJE<>0
   SELECT VPUPL 
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE DUG WITH MGROBLJE  
   REPLACE DATUM WITH MEDATUM
   REPLACE VALUTA WITH MEVALUTA
   REPLACE GRUPA WITH 'GRO'
   replace opis WITH ' GRO '+GRUPA
   REPLACE BRNAL WITH ABRNAL      
ENDIF

IF MSOC<>0
   SELECT VPUPL 
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE DUG WITH -MSOC
   REPLACE DATUM WITH MEDATUM
   REPLACE VALUTA WITH MEVALUTA
   REPLACE GRUPA WITH 'SOC'
   replace opis WITH ' POPUST SOC '+GRUPA
   REPLACE BRNAL WITH ABRNAL
   SELECT VP
ENDIF

IF MPOREZ<>0
   SELECT VPUPL 
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE DUG WITH MPOREZ
   REPLACE DATUM WITH MEDATUM
   REPLACE VALUTA WITH MEVALUTA
   REPLACE GRUPA WITH 'POR'
   replace opis WITH ' POREZ '+GRUPA
   REPLACE BRNAL WITH ABRNAL
   SELECT VP
ENDIF

*----------sada radimo rabat-----------
*IF TVODA=1
*   MRABPROC=0
*ELSE
*   MRABPROC=0
*ENDIF

MRABPROC=0

select VPUPL
set order to 1
select VP
SET ORDER TO 1
SEEK MPIB
IF FOUND()
   select VPUPL
   seek MPIB
   if found()
      mdug=0
      mpot=0
      MPRDUG=0
      MRUKUPNO=0
      do while.not.eof()
         if PIB<>MPIB
            exit
         endif   
         if datum<mdatOD
            mprdug=mprdug+dug-pot
         endif   
         if (datum>=mdatOD.AND.datum<=mdatDO)
            IF SUBSTR(GRUPA,1,2)<>'SP'.AND.GRUPA<>'ISP'.AND.GRUPA<>'KO' 
               mdug=mdug+dug
               mpot=mpot+pot
            ELSE
               MRUKUPNO=MRUKUPNO+DUG-POT
            ENDIF
         endif   
         skip
      enddo 
      SELECT VP
      REPLACE ODUG WITH MDUG
      REPLACE OPOT WITH MPOT
      REPLACE OSALDO WITH mprdug+MDUG-MPOT  
      IF OSALDO<=0.and.(mukupno-MRUKUPNO)>0
         MRABAT=MRABPROC*ABS(mukupno-MRUKUPNO)/100
         MRABAT=0
         REPLACE RABAT WITH MRABAT
         SELECT VPUPL
         IF MRABAT>0
            APPEND BLANK
            REPLACE PIB WITH MPIB
            REPLACE DUG WITH -MRABAT
            REPLACE BRNAL WITH ABRNAL
            REPLACE OPIS WITH 'RABAT '+DTOC(MDATDO)
            REPLACE GRUPA WITH 'RAB'
            replace datum with mdatDO
            replace valuta with mdatDO
         ENDIF
      ELSE
         MRABAT=0
      ENDIF   
      SELECT VP
      REPLACE RABAT WITH MRABAT
   endif
ENDIF
select VPUPL
set order to 
*-------kraj rabata-----------------------
SELECT VP

REPLACE SVEGA WITH UKUPNO+DUG-UPLAC+KAMATA-rabat+OSTALO+SOC
REPLACE CENOVNIK WITH MCENOVNIK
REPLACE DATUM WITH MEDATUM
REPLACE VALUTA WITH MEVALUTA
REPLACE DATOD WITH MDATOD
REPLACE DATDO WITH MDATDO
REPLACE MES WITH MZSTANJE

ENDIF

*----------OBRACUN 2 KUCNI SAVETI

IF MVRSTA=2

SELECT VP
REPLACE MESECI WITH MMES      
*--------OBRACUN PAUSAL------------------
IF PAUSAL=' '
   REPLACE POT WITH &AKRAJ-&APOC-KOREKCV
ELSE
   REPLACE POT WITH MMES*MESPAUSAL
ENDIF
REPLACE POC WITH &APOC
REPLACE KRAJ WITH &AKRAJ
REPLACE VODA WITH 0
REPLACE CENOVNIK WITH MCENOVNIK
REPLACE DATUM WITH MEDATUM
REPLACE VALUTA WITH MEVALUTA
REPLACE DATOD WITH MDATOD
REPLACE DATDO WITH MDATDO
REPLACE MES WITH MZSTANJE

ENDIF
*--------------obracun stanari--------------------------------------

IF MVRSTA=3
SELECT VP
MPIB=PIB
*------U POT UNET PODATAK O INDIVIDUALNOM VODOMERU
*------U POTS UNETA POTROSNJA ZBIRNOG VODOMERA PODELJENA PREMA BROJU STANARA



ABRNAL='O'+ALLTRIM(STR(MBROBRAC,2,0))+MGRUPA
select VPUPL
set order to 1
select VP
SET ORDER TO 1
SEEK MPIB
IF FOUND()
   REPLACE ODUG WITH 0
   REPLACE OPOT WITH 0
   REPLACE OSALDO WITH 0
   REPLACE RABAT WITH 0
   REPLACE KAMATA WITH 0
   REPLACE OSTALO WITH 0
   REPLACE SVEGA WITH 0
   select VPUPL
   seek MPIB
   if found()
      do while.not.eof()
         if PIB<>MPIB
            exit
         endif   
         *---BRISANJE NALOGA
         IF BRNAL=ABRNAL
            REPLACE DUG WITH 0
            REPLACE GRUPA WITH ' '
            REPLACE BRNAL WITH ' ' 
         ENDIF   
         skip
      enddo 
      SELECT VP
   ENDIF
ENDIF
*-----------OBRACUN KAMATE---------------
select VPUPL
set order to 
SELECT VP
USE VPKAM IN 0 EXCLU
SELECT VPKAM
ZAP
DO VPKAM WITH MPIB,MDATOD,MDATDO
SELECT VPKAM
*--------PRENOS KAMATE------------------
SET ORDER TO 1
DO VPPRENKAM WITH MPIB,MDATOD,MDATDO,MEVALUTA
SELECT VPKAM
USE
*------POPUNJAVANJE OSTALIH PODATAKA-----

SELECT VP
set procedure to
SELECT VP
REPLACE MESECI WITH MMES      
*--------OBRACUN PAUSAL------------------
IF PAUSAL=' '
   REPLACE POT WITH &AKRAJ-&APOC
ELSE
   REPLACE POT WITH MMES*MESPAUSAL*BRSTAN
ENDIF

REPLACE VODA WITH 0
*------------OBRACUN ZA VODU KOIMA VODOMER------------------   
IF POT>0.OR.POTS>0
   IF POT>0
      MPOT=POT+RASTURJ
   ELSE
      MPOT=POTS+RASTURJ
   ENDIF
   IF PVODA<>' '
      REPLACE VODA WITH MPOT*MCVODA*(100-POPPROC)/100
      REPLACE DOPV WITH MPOT*MCDVODA*(100-POPPROC)/100    
   ELSE
      REPLACE VODA WITH 0
      REPLACE DOPV WITH 0
   ENDIF
   *------------OBRACUN ZA KANALIZACIJU
   IF PKANAL<>' '
      REPLACE KAN WITH MPOT*MCKANAL*(100-POPKAN)/100
      REPLACE DOPK WITH MPOT*MCDKANAL*(100-POPKAN)/100    
   ELSE
      REPLACE KAN WITH 0
      REPLACE DOPK WITH 0   
   ENDIF
ELSE
   REPLACE VODA WITH 0
   REPLACE DOPV WITH 0
   REPLACE KAN WITH 0
   REPLACE DOPK WITH 0   
ENDIF

IF PSMECE<>' '
   REPLACE SMECE WITH POV*MCSMECE
ELSE
   REPLACE SMECE WITH 0
ENDIF

IF PTOPLANA<>' '
   REPLACE TOPLANA WITH POVTOP*mcTOPLANA
ELSE
   REPLACE TOPLANA WITH 0
ENDIF

IF PGROBLJE<>' '
   REPLACE GROBLJE WITH mcGROBLJE
ELSE
   REPLACE groblje WITH 0
ENDIF

*----------UKUPNI PODACI------------------   

MVODA=VODA
MDOPV=DOPV
MKAN=KAN
MDOPK=DOPK
MTOPLANA=TOPLANA
MGROBLJE=GROBLJE
msmece=smece

MUKUPNO=VODA+DOPV+KAN+DOPK+GROBLJE+TOPLANA+smece
   
MSOC=ROUND(MUKUPNO*POPSOC/100,2)
   
REPLACE UKUPNO WITH MUKUPNO   
REPLACE PROCPOR WITH MPROCPOR
   
MUKUPNO=UKUPNO

SELECT VPUPL
SEEK MPIB

MPRDUG=0
MUPLAC=0
mispr=0
*----------PRETRAZIVANJE UPLATA ZA OSTALIM PODACIMA--------  
if found()
   do while.not.eof()
      if PIB<>mPIB
         exit
      endif
      if datum<mdatod
         mprdug=mprdug+dug-pot
      endif    
      if datum>=mdatod.and.datum<=mdatdo
         IF GRUPA='ISP'.OR.SUBSTR(GRUPA,1,2)='KO'.OR.SUBSTR(GRUPA,1,2)='SP'.OR.SUBSTR(GRUPA,1,2)='ST'
            MISPR=MISPR+DUG
         ENDIF      
      ENDIF
      if datum>=mdatod.and.datum<=mdatdo
         mUPLAC=MUPLAC+POT
         mdATUM=datum 
      endif
      skip
   enddo      
endif
*----------POPUNJAVANJE GLAVNE TABELE----------

SELECT VP
REPLACE UPLAC WITH MUPLAC
REPLACE DUG WITH MPRDUG
REPLACE OSTALO WITH MISPR
REPLACE SOC WITH -MSOC
*----------POPUNJAVANJE TABELE UPLATA----------
SELECT VPUPL   
IF MVODA<>0
   SELECT VPUPL 
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE DUG WITH MVODA  
   REPLACE DATUM WITH MEDATUM
   REPLACE VALUTA WITH MEVALUTA
   REPLACE GRUPA WITH 'VOD'
   replace opis WITH ' VODA '+GRUPA
   REPLACE BRNAL WITH ABRNAL      
ENDIF

IF MDOPV<>0
   SELECT VPUPL 
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE DUG WITH MDOPV  
   REPLACE DATUM WITH MEDATUM
   REPLACE VALUTA WITH MEVALUTA
   REPLACE GRUPA WITH 'DOV'
   replace opis WITH ' DOV '+GRUPA
   REPLACE BRNAL WITH ABRNAL      
ENDIF

IF MKAN<>0
   SELECT VPUPL 
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE DUG WITH MKAN  
   REPLACE DATUM WITH MEDATUM
   REPLACE VALUTA WITH MEVALUTA
   REPLACE GRUPA WITH 'KAN'
   replace opis WITH ' KAN '+GRUPA
   REPLACE BRNAL WITH ABRNAL      
ENDIF

IF MDOPK<>0
   SELECT VPUPL 
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE DUG WITH MDOPK  
   REPLACE DATUM WITH MEDATUM
   REPLACE VALUTA WITH MEVALUTA
   REPLACE GRUPA WITH 'DOK'
   replace opis WITH ' DOK '+GRUPA
   REPLACE BRNAL WITH ABRNAL      
ENDIF

IF Msmece<>0
   SELECT VPUPL 
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE DUG WITH MSMECE 
   REPLACE DATUM WITH MEDATUM
   REPLACE VALUTA WITH MEVALUTA
   REPLACE GRUPA WITH 'SME'
   replace opis WITH ' SME '+GRUPA
   REPLACE BRNAL WITH ABRNAL      
ENDIF

IF MTOPLANA<>0
   SELECT VPUPL 
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE DUG WITH MTOPLANA  
   REPLACE DATUM WITH MEDATUM
   REPLACE VALUTA WITH MEVALUTA
   REPLACE GRUPA WITH 'TOP'
   replace opis WITH ' TOP '+GRUPA
   REPLACE BRNAL WITH ABRNAL      
ENDIF

IF MGROBLJE<>0
   SELECT VPUPL 
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE DUG WITH MGROBLJE  
   REPLACE DATUM WITH MEDATUM
   REPLACE VALUTA WITH MEVALUTA
   REPLACE GRUPA WITH 'GRO'
   replace opis WITH ' GRO '+GRUPA
   REPLACE BRNAL WITH ABRNAL      
ENDIF

IF MSOC<>0
   SELECT VPUPL 
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE DUG WITH -MSOC
   REPLACE DATUM WITH MEDATUM
   REPLACE VALUTA WITH MEVALUTA
   REPLACE GRUPA WITH 'SOC'
   replace opis WITH ' POPUST SOC '+GRUPA
   REPLACE BRNAL WITH ABRNAL
   SELECT VP
ENDIF

*----------sada radimo rabat-----------
MRABPROC=0
select VPUPL
set order to 1
select VP
SET ORDER TO 1
SEEK MPIB
IF FOUND()
   select VPUPL
   seek MPIB
   if found()
      mdug=0
      mpot=0
      MPRDUG=0
      MRUKUPNO=0
      do while.not.eof()
         if PIB<>MPIB
            exit
         endif   
         if datum<mdatOD
            mprdug=mprdug+dug-pot
         endif   
         if (datum>=mdatOD.AND.datum<=mdatDO)
            IF GRUPA='VOD'.OR.GRUPA='DOV'.OR.GRUPA='KAN'.OR.GRUPA='SOC'   
               mdug=mdug+dug
               mpot=mpot+pot
            ELSE
               MRUKUPNO=MRUKUPNO+DUG-POT
            ENDIF
         endif   
         skip
      enddo 
      SELECT VP
      REPLACE ODUG WITH MDUG
      REPLACE OPOT WITH MPOT
      REPLACE OSALDO WITH mprdug+MDUG-MPOT  
      IF OSALDO<=0.and.(mukupno-MRUKUPNO)>0
         MRABAT=MRABPROC*ABS(mukupno-MRUKUPNO)/100
         MRABAT=0
         REPLACE RABAT WITH -MRABAT
         SELECT VPUPL
         IF MRABAT>0
            APPEND BLANK
            REPLACE PIB WITH MPIB
            REPLACE DUG WITH -MRABAT
            REPLACE BRNAL WITH ABRNAL
            REPLACE OPIS WITH 'RABAT '+DTOC(MDATDO)
            REPLACE GRUPA WITH 'RAB'
            replace datum with mdatDO
            replace valuta with mEVALUTA
         ENDIF
      ELSE
         MRABAT=0
      ENDIF   
      SELECT VP
      REPLACE RABAT WITH MRABAT
   endif
ENDIF
select VPUPL
set order to 
SELECT VP
*-------kraj rabata-----------------------
*-------POREZ-----------------------------

MPOREZ=ROUND((UKUPNO-MSOC-RABAT)*PROCPOR/100,2)
REPLACE POREZ WITH MPOREZ
SELECT VPUPL
IF MPOREZ>0
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE DUG WITH MPOREZ
   REPLACE BRNAL WITH ABRNAL
   REPLACE OPIS WITH 'POREZ'+DTOC(MDATDO)
   REPLACE GRUPA WITH 'POR'
   replace datum with mdatDO
   replace valuta with MEVALUTA
ENDIF

SELECT VP   
REPLACE AKONT WITH (100+MPROCAKONT)*(UKUPNO-MSOC+POREZ)/MMES/100

SELECT VP
REPLACE SVEGA WITH UKUPNO+DUG-UPLAC+KAMATA-rabat+OSTALO+SOC+POREZ
REPLACE CENOVNIK WITH MCENOVNIK
REPLACE DATUM WITH MEDATUM
REPLACE VALUTA WITH MEVALUTA
REPLACE DATOD WITH MDATOD
REPLACE DATDO WITH MDATDO
REPLACE MES WITH MZSTANJE

ENDIF

*----------OBRACUN 4 FIRME

IF MVRSTA=4

ABRNAL='F'+ALLTRIM(STR(MBROBRAC,2,0))      

select VPUPL
set order to 1
select VP
SET ORDER TO 1
SEEK MPIB
IF FOUND()
   REPLACE ODUG WITH 0
   REPLACE OPOT WITH 0
   REPLACE OSALDO WITH 0
   REPLACE RABAT WITH 0
   REPLACE KAMATA WITH 0
   REPLACE OSTALO WITH 0
   REPLACE SVEGA WITH 0
   select VPUPL
   seek MPIB
   if found()
      do while.not.eof()
         if PIB<>MPIB
            exit
         endif   
         *---BRISANJE NALOGA
         IF BRNAL=ABRNAL
            REPLACE DUG WITH 0
            REPLACE GRUPA WITH ' '
            REPLACE BRNAL WITH ' ' 
         ENDIF   
         skip
      enddo 
      SELECT VP
   ENDIF
ENDIF


SELECT VP
REPLACE MESECI WITH MMES      
*--------OBRACUN PAUSAL------------------
IF PAUSAL=' '
   REPLACE POT WITH &AKRAJ-&APOC
ELSE
   REPLACE POT WITH MMES*MESPAUSAL
ENDIF
REPLACE POC WITH &APOC
REPLACE KRAJ WITH &AKRAJ
REPLACE VODA WITH 0
*------------OBRACUN ZA VODU------------------   
IF POT>0
IF PVODA<>' '
   REPLACE VODA WITH POT*MCVODA*(100-POPPROC)/100
   REPLACE DOPV WITH POT*MCDVODA*(100-POPPROC)/100    
ELSE
   REPLACE VODA WITH 0
   REPLACE DOPV WITH 0   
ENDIF
*------------OBRACUN ZA KANALIZACIJU
IF PKANAL<>' '
   REPLACE KAN WITH POT*MCKANAL*(100-POPKAN)/100
   REPLACE DOPK WITH POT*MCDKANAL*(100-POPKAN)/100    
ELSE
   REPLACE KAN WITH 0
   REPLACE DOPK WITH 0   
ENDIF
ELSE
   REPLACE VODA WITH 0
   REPLACE DOPV WITH 0   
   REPLACE KAN WITH 0
   REPLACE DOPK WITH 0   
ENDIF

IF PSMECE<>' '
   IF CENOVNIK=0
      REPLACE SMECE WITH POV*MCSMECE
   ELSE
      IF CENOVNIK>0.AND.CENOVNIK<=10
         *DECLARE MCS[10]
         MCENA=MCS[CENOVNIK]
         REPLACE SMECE WITH MCENA
         
      ELSE
         REPLACE SMECE WITH 0 
            
      ENDIF
   ENDIF
ELSE
   REPLACE SMECE WITH 0
ENDIF

IF PTOPLANA<>' '
   REPLACE TOPLANA WITH POVTOP*MCTOPLANA
ELSE
   REPLACE TOPLANA WITH 0
ENDIF
*----------UKUPNI PODACI------------------   
MVODA=VODA
MDOPV=DOPV
MKAN=KAN
MDOPK=DOPK
MTOPLANA=TOPLANA
MSMECE=SMECE
MUKUPNO=VODA+DOPV+KAN+DOPK+TOPLANA+SMECE
REPLACE UKUPNO WITH MUKUPNO
REPLACE PROCPOR WITH MPROCPOR
MPOREZ=ROUND((UKUPNO)*PROCPOR/100,2)
REPLACE POREZ WITH MPOREZ


REPLACE DATUM WITH MEDATUM
REPLACE VALUTA WITH MEVALUTA
REPLACE DATOD WITH MDATOD
REPLACE DATDO WITH MDATDO
REPLACE MES WITH MZSTANJE
  
REPLACE UKUPNO WITH MUKUPNO   
REPLACE SVEGA WITH UKUPNO+porez


SELECT VP

SELECT VPUPL   
IF MVODA<>0
   SELECT VPUPL 
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE DUG WITH MVODA  
   REPLACE DATUM WITH MEDATUM
   REPLACE VALUTA WITH MEVALUTA
   REPLACE GRUPA WITH 'VOD'
   replace opis WITH ' VODA '+GRUPA
   REPLACE BRNAL WITH ABRNAL      
ENDIF

IF MDOPV<>0
   SELECT VPUPL 
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE DUG WITH MDOPV  
   REPLACE DATUM WITH MEDATUM
   REPLACE VALUTA WITH MEVALUTA
   REPLACE GRUPA WITH 'DOV'
   replace opis WITH ' DOV '+GRUPA
   REPLACE BRNAL WITH ABRNAL      
ENDIF

IF MKAN<>0
   SELECT VPUPL 
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE DUG WITH MKAN  
   REPLACE DATUM WITH MEDATUM
   REPLACE VALUTA WITH MEVALUTA
   REPLACE GRUPA WITH 'KAN'
   replace opis WITH ' KAN '+GRUPA
   REPLACE BRNAL WITH ABRNAL      
ENDIF

IF MDOPK<>0
   SELECT VPUPL 
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE DUG WITH MDOPK  
   REPLACE DATUM WITH MEDATUM
   REPLACE VALUTA WITH MEVALUTA
   REPLACE GRUPA WITH 'DOK'
   replace opis WITH ' DOK '+GRUPA
   REPLACE BRNAL WITH ABRNAL      
ENDIF

IF MSMECE<>0
   SELECT VPUPL 
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE DUG WITH MSMECE  
   REPLACE DATUM WITH MEDATUM
   REPLACE VALUTA WITH MEVALUTA
   REPLACE GRUPA WITH 'SME'
   replace opis WITH ' SME '+GRUPA
   REPLACE BRNAL WITH ABRNAL      
ENDIF

IF MTOPLANA<>0
   SELECT VPUPL 
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE DUG WITH MTOPLANA  
   REPLACE DATUM WITH MEDATUM
   REPLACE VALUTA WITH MEVALUTA
   REPLACE GRUPA WITH 'TOP'
   replace opis WITH ' TOP '+GRUPA
   REPLACE BRNAL WITH ABRNAL      
ENDIF

IF MPOREZ<>0
   SELECT VPUPL 
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE DUG WITH MPOREZ
   REPLACE DATUM WITH MEDATUM
   REPLACE VALUTA WITH MEVALUTA
   REPLACE GRUPA WITH 'POR'
   replace opis WITH ' POREZ '+GRUPA
   REPLACE BRNAL WITH ABRNAL
   SELECT VP
ENDIF

SELECT VP
ENDIF




