SELECT VP
*SET STEP ON 
MPIB=PIB
MGRUPA=GRUPA
MIME_PREZ=IME_PREZ
*-----------TABELA OBRACUNA------------
select VPOBRAC
MCENOVNIK=CENOVNIK
MBROBRAC=BROBRAC
*------TABELA CENA
select VPCENE
SET ORDER TO 1
SEEK MCENOVNIK
mpstanje=pstanje
mzstanje=zstanje
APOC='ST'+ALLTRIM(STR(MPSTANJE,2,0))
AKRAJ='ST'+ALLTRIM(STR(MZSTANJE,2,0))
MMES=MZSTANJE-MPSTANJE
mEdatum=datum
mEvaluta=valuta
mdatOD2=DTOS(datod)
mdatDO2=DTOS(datdo)
mdatOD=datod
mdatDO=datdo
mcvoda=cvoda
mcvoda2=cvoda2
mcvoda3=cvoda3
mcdvoda=cdvoda
mckanal=ckanal
mckanal2=ckanal2
mckanal3=ckanal3
mcdkanal=cdkanal
mcdkomdin=cdkomdin
MRABPROC=RABPROC
MPROCPOR=PROCPOR
mprocakont=procakont
mcvodado=cvodado
mcvodado2=cvodado2
MBRNAL='O'+ALLTRIM(STR(MBROBRAC,2,0))+MGRUPA
MPRDUG=0
SELECT VP
*-----------OBRACUN KAMATE---------------
   select VPUPL
   set order to 
   SELECT VP
   USE VPKAM IN 0 EXCLU
   SELECT VPKAM
   ZAP
   DO VPKAM WITH MPIB,MDATOD,MDATDO
   SELECT VPKAM
*--------PRENOS KAMATE------------------
   SET ORDER TO 1
   MKAMATA=0
   SELECT VPKAM
   SET ORDER TO 1
   SEEK MPIB
   IF FOUND()
      MKAMATA=0
      DO WHILE.NOT.EOF()
         IF PIB<>MPIB
            EXIT
         ENDIF
         IF DATPOC>=MDATOD.AND.DATPOC<=MDATDO
            mKAMATA=mKAMATA+KAMATA
         ENDIF   
         SKIP
      ENDDO
   ENDIF
   *DO VPPRENKAM WITH MPIB,MDATOD,MDATDO
   SELECT VPKAM
   USE
   SELECT VP  
   REPLACE DATUM WITH MEDATUM
   REPLACE VALUTA WITH MEVALUTA
   REPLACE MES WITH MMES
   IF MKAMATA>0
      REPLACE KAMATA WITH MKAMATA
   ELSE
      REPLACE KAMATA WITH 0
   ENDIF
*--------OBRACUN PAUSAL------------------
   IF PAUSAL=' '
      REPLACE POT WITH &AKRAJ-&APOC
      MPOT=POT
   ELSE
      REPLACE POT WITH MMES*MESPAUSAL
      MPOT=POT
   ENDIF
   IF POT<0
      REPLACE POT WITH 0
      MPOT=POT
   ENDIF   
   REPLACE POC WITH &APOC
   REPLACE KRAJ WITH &AKRAJ
   *REPLACE UKPOT WITH KRAJ-POC
   REPLACE UKPOT WITH MPOT
   REPLACE VODA WITH 0
   REPLACE CENOVNIK WITH MCENOVNIK
*------------OBRACUN ZA VODU------------------   
   replace voda WITH 0
   replace voda2 WITH 0
   replace voda3 WITH 0
   replace kan WITH 0
   replace kan2 WITH 0
   replace kan3 WITH 0
   *SET STEP ON 
   IF POT>0
      IF PVODA<>' '
         *---blok tarifa 16 01 2014 
         IF pot<=mcvodado
            REPLACE VODA WITH POT*MCVODA*(100-POPPROC)/100
            replace voda2 WITH 0
            replace voda3 with 0
         endif   
         IF pot>mcvodado.and.pot<=mcvodado2
            REPLACE VODA WITH mcvodado*MCVODA*(100-POPPROC)/100
            REPLACE VODA2 WITH (POT-mcvodado)*MCVODA2*(100-POPPROC)/100            
            replace voda3 WITH 0
         endif   
         IF pot>mcvodado2
            REPLACE VODA WITH mcvodado*MCVODA*(100-POPPROC)/100
            REPLACE VODA2 WITH (mcvodado2-mcvodado)*MCVODA2*(100-POPPROC)/100            
            REPLACE VODA3 WITH (POT-mcvodado2)*MCVODA3*(100-POPPROC)/100            
         endif   
         REPLACE DOPV WITH POT*MCDVODA*(100-POPPROC)/100    
      ELSE
         REPLACE VODA WITH 0
         REPLACE DOPV WITH 0
      ENDIF
*------------OBRACUN ZA KANALIZACIJU
      IF PKANAL<>' '
         *---blok tarifa 16 01 2014 
         IF pot<=mcvodado
            REPLACE kan WITH POT*MCkanal*(100-POPPROC)/100
            replace kan2 WITH 0
            replace kan3 with 0
         endif   
         IF pot>mcvodado.and.pot<=mcvodado2
            REPLACE kan WITH mcvodado*MCkanal*(100-POPPROC)/100
            REPLACE kan2 WITH (POT-mcvodado)*MCkanal2*(100-POPPROC)/100            
            replace kan3 WITH 0
         endif   
         IF pot>mcvodado2
            REPLACE kan WITH mcvodado*MCkanal*(100-POPPROC)/100
            REPLACE kan2 WITH (mcvodado2-mcvodado)*MCkanal2*(100-POPPROC)/100            
            REPLACE kan3 WITH (POT-mcvodado2)*Mckanal3*(100-POPPROC)/100            
         endif   
         REPLACE DOPK WITH POT*MCDKANAL*(100-POPKAN)/100    
      ELSE
         REPLACE KAN WITH 0
         REPLACE DOPK WITH 0   
      ENDIF
   ELSE
      REPLACE VODA WITH 0
      REPLACE DOPV WITH 0
      REPLACE KAN WITH 0
      REPLACE DOPK WITH 0   
   ENDIF
MVODA=VODA
MDOPV=DOPV
MKAN=KAN
MDOPK=DOPK

MKOMDINAR=POT*MCdKOMDIN*(100-POPPROC)/100

MUKUPNO=VODA+voda2+voda3+DOPV+KAN+kan2+kan3+DOPK+MKOMDINAR
   
MSOC=ROUND(MUKUPNO*POPSOC/100,2)
   
REPLACE KOMDINAR WITH MKOMDINAR
   
REPLACE UKUPNO WITH MUKUPNO   
REPLACE PROCPOR WITH MPROCPOR
MPOREZ=ROUND(((VODA+KAN+voda2+kan2+voda3+kan3)-MSOC+MKOMDINAR)*PROCPOR/100,2)
REPLACE POREZ WITH MPOREZ
MOSNOV=UKUPNO-MSOC+POREZ
IF MOSNOV>0.AND.MMES>0   
   REPLACE AKONT WITH ROUND( (100+MPROCAKONT)*MOSNOV/MMES/100,0)
ELSE
   REPLACE AKONT WITH 0
ENDIF   
MUKUPNO=UKUPNO   
*----------PRETRAZIVANJE UPLATA zbog rabata--------  

   MRABATDUG=0
   SELECT VPUPL
   SET ORDER TO 1
   SEEK MPIB
   if found()
      do while.not.eof()
         if PIB<>mPIB
            exit
         ENDIF
         IF brnal<>mbrnal
*            SET STEP on
            IF datum<=mdatdo
               mrabatdug=mrabatdug+dug-pot
            endif
         endif   
        skip
     enddo      
   ELSE
      mrabatdug=0   
   endif
IF mrabatdug<=0
   imarabat=1
ELSE
   imarabat=0
endif
*-------UKUPNI PODACI------------------   
SELECT vp
   REPLACE MESECI WITH MMES      
   IF IMARABAT=1
      MRABOSNOV=VODA+DOPV+KAN+DOPK+komdinar+voda2+kan2+voda3+kan3
   ELSE
      MRABOSNOV=0
   ENDIF      
   *MMAKSPOT=MMES*15
   *IF POT<=MMAKSPOT
   IF MRABOSNOV>0
      MRABAT=ROUND(MRABOSNOV*MRABPROC/100,2)
   ELSE
      MRABAT=0
   ENDIF
   *ELSE
   *   MRABAT=0
   *ENDIF
   REPLACE RABAT WITH MRABAT
   MUKUPNO=VODA+DOPV+KAN+DOPK+komdinar+voda2+kan2+voda3+kan3
   REPLACE UKUPNO WITH MUKUPNO   
   IF POPSOC>0.AND.(MUKUPNO-mRABAT)>0
      MSOC=ROUND((MUKUPNO-RABAT)*POPSOC/100,2)
   ELSE
      MSOC=0
   ENDIF
   REPLACE SOC WITH MSOC
   REPLACE PROCPOR WITH MPROCPOR
   IF (UKUPNO-DOPV-DOPK-SOC-RABAT)>0
      MPOREZ=ROUND((UKUPNO-SOC-DOPV-DOPK-RABAT)*PROCPOR/100,2)
   ELSE
      MPOREZ=0
   ENDIF
  
   REPLACE POREZ WITH MPOREZ
   REPLACE SVEGA WITH UKUPNO-SOC-RABAT+POREZ
   MOSNOV=MUKUPNO-MSOC-mrabat+MPOREZ-DOPV-DOPK
   IF MOSNOV>0.AND.MMES>0   
      REPLACE AKONT WITH ROUND( (100+MPROCAKONT)*MOSNOV/MMES/100,0)
   ELSE
      REPLACE AKONT WITH 0
   ENDIF   
   REPLACE BRNAL WITH MBRNAL
   MPR2DUG=0
   MUPLAC=0
   mispr=0
   MSPORAZUM=0
   MOSTALO=0

   SELECT VPUPL
   SET ORDER TO 1
   SEEK MPIB
*----------PRETRAZIVANJE UPLATA ZA OSTALIM PODACIMA--------  
   if found()
      do while.not.eof()
         if PIB<>mPIB
            exit
         endif
         if DTOS(datum)<DTOS(mdatod)
            mpr2dug=mpr2dug+dug-pot
         endif    
         if DTOS(datum)>=DTOS(mdatod).and.DTOS(datum)<=DTOS(mdatdo)
            IF GRUPA='SPO'.OR.GRUPA='STA'.OR.GRUPA='STO'.OR.GRUPA='SPP'
               MSPORAZUM=MSPORAZUM+DUG
            ENDIF      
            IF GRUPA='ISP'.OR.GRUPA='KOD'
               MOSTALO=MOSTALO+DUG
            ENDIF      
         ENDIF
         if DTOS(datum)>=DTOS(mdatod).and.DTOS(datum)<=DTOS(mdatdo)
           mUPLAC=MUPLAC+POT
           mdATUM=datum 
        endif
        skip
     enddo      
  endif
*----------POPUNJAVANJE GLAVNE TABELE----------
   SELECT VP
   REPLACE DUG WITH MPR2DUG
   REPLACE UPLAC WITH MUPLAC
   REPLACE OSTALO WITH MOSTALO+msporazum
   *REPLACE SPORAZUM WITH MSPORAZUM
*   REPLACE SVEGA WITH UKUPNO+OSTALO+SPORAZUM-UPLAC+DUG+POREZ+KAMATA-MSOC
*   REPLACE ZADUZENJE WITH UKUPNO+POREZ-SOC 
*   REPLACE SOC WITH -MSOC
   SET CENTURY OFF
   MGODINA=SUBSTR(DTOC(medatum),7,2)
   mbrrac=ALLTRIM(pib)+ALLTRIM(STR(MBROBRAC,2,0))+mgodina
   REPLACE BRRAC WITH MBRRAC
   M1=VAL(mbrrac)
   M2=(M1*100/97)-INT(M1*100/97)
   M3=ROUND(97*M2,0)
   M4=98-M3
   IF M4<=9
      M4='0'+STR(M4,1,0)
   ELSE
      M4=STR(M4,2,0)
   ENDIF      
   REPLACE model WITH +M4+'-'+ALLTRIM(mbrrac)
   SET CENTURY on
   SELECT VPUPLD
   SET ORDER TO 1
   SET EXACT OFF
   GO TOP
   DO WHILE.T.
      LOCATE FOR pib=mpib.and.brnal=mbrnal
      IF FOUND()
         SET ORDER TO 
         REPLACE PIB WITH SPACE(13)
         REPLACE BRNAL WITH SPACE(6)
         REPLACE BRRAC WITH ''
         REPLACE GRUPA WITH ''
         REPLACE CENOVNIK WITH 0
         REPLACE PSTanje WITH 0
         REPLACE ZSTANJE WITH 0
         REPLACE MESEC WITH 0
         REPLACE DATUM WITH CTOD('')
         REPLACE VALUTA WITH CTOD('')
         REPLACE DATOD WITH CTOD('')
         REPLACE DATDO WITH CTOD('')
         REPLACE CVODA WITH 0
         REPLACE CDVODA WITH 0
         REPLACE CKANAL WITH 0
         REPLACE CDKANAL WITH 0
         REPLACE CVODA2 WITH 0
         REPLACE CKANAL2 WITH 0
         REPLACE CVODA3 WITH 0
         REPLACE CKANAL3 WITH 0
         REPLACE CDKomdin WITH 0
         REPLACE PROCPOR WITH 0
         REPLACE VODA WITH 0
         REPLACE KAN WITH 0
         REPLACE VODA2 WITH 0
         REPLACE KAN2 WITH 0
         REPLACE VODA3 WITH 0
         REPLACE KAN3 WITH 0
         REPLACE DOPV WITH 0
         REPLACE DOPK WITH 0
         REPLACE UKUPNO WITH 0
         REPLACE PROCPOR WITH 0
         REPLACE OSTALO WITH 0
         REPLACE SPORAZUM WITH 0
         REPLACE SOC WITH 0
         REPLACE KAMATA WITH 0
         REPLACE OSNOV WITH 0
         REPLACE POREZ WITH 0
         REPLACE POC WITH 0
         REPLACE KRAJ WITH 0
         REPLACE POT WITH 0
         REPLACE RABAT WITH 0
         REPLACE DUG WITH 0
         REPLACE SALDO WITH 0
         REPLACE SVEGA WITH 0
         replace mespausal WITH 0
         LOOP 
      ELSE
         EXIT
      ENDIF
   ENDDO   
   SET ORDER TO 
   SELECT VP
   MGRUPA=GRUPA
   MDATUM=DATUM
   MVALUTA=VALUTA
   MPAUSAL=PAUSAL
   MMESPAUSAL=MESPAUSAL
   MVODA=VODA
   MKAN=KAN
   MVODA2=VODA2
   MKAN2=KAN2
   MVODA3=VODA3
   MKAN3=KAN3
   MDOPV=DOPV
   MDOPK=DOPK
   mkomdinar=komdinar
   MUKUPNO=UKUPNO
   MOSTALO=OSTALO
   *msporazum=sPORAzum
   mdug=dug
   MSVEGA=SVEGA
   MUPLAC=UPLAC
   MPOREZ=POREZ
   MSOC=SOC
   MKAMATA=KAMATA
   MBRRAC=BRRAC
   MMODEL=MODEL
   MRABAT=RABAT
   MPROCPOR=PROCPOR
   MPOC=POC
   MKRAJ=KRAJ
   MPOT=POT
   MPVODA=PVODA
   MPKANAL=PKANAL
   MSLEP=SLEP
   MPOPPROC=POPPROC
   MPOPKAN=POPKAN
   MPOPSOC=POPSOC
   MBRSTAN=BRSTAN
   MUKSTAN=UKSTAN
   MDOMAC=DOMAC
   MKS=KS
   MKSSIFRA=KSSIFRA
   MVRSTA=VRSTA
   MSIFUL=SIFUL
   MULICA=ULICA
   MULBROJ=ULBROJ
   MBROJ=BROJ
   MIME_PREZ=IME_PREZ
   MRABAT=RABAT   
   mdatcit=datcit
   MIME_PREZc=IME_PREZc
   MULICAc=ULICAc
   SELECT VPUPLD
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE GRUPA WITH MGRUPA
   REPLACE CENOVNIK WITH MCENOVNIK
   REPLACE PSTanje WITH MPSTANJE
   REPLACE ZSTANJE WITH MZSTANJE
   REPLACE MESEC WITH MMES
   REPLACE DATUM WITH  MDATUM
   REPLACE VALUTA WITH MVALUTA
   REPLACE DATOD WITH MDATOD
   REPLACE DATDO WITH MDATDO
   REPLACE CVODA WITH MCVODA
   REPLACE CKANAL WITH MCKANAL
   REPLACE CVODA2 WITH MCVODA2
   REPLACE CKANAL2 WITH MCKANAL2
   REPLACE CVODA3 WITH MCVODA3
   REPLACE CKANAL3 WITH MCKANAL3
   REPLACE CVODADO WITH MCVODADO
   REPLACE CVODADO2 WITH MCVODADO2
   REPLACE Cdkomdin WITH MCdkomdin 
   REPLACE CDVODA WITH MCDVODA
   REPLACE CDKANAL WITH MCDKANAL
   REPLACE PROCPOR WITH MPROCPOR
   REPLACE VODA WITH MVODA
   REPLACE KAN WITH MKAN
   REPLACE VODA2 WITH MVODA2
   REPLACE KAN2 WITH MKAN2
   REPLACE VODA3 WITH MVODA3
   REPLACE KAN3 WITH MKAN3
   REPLACE DOPV WITH MDOPV
   REPLACE DOPK WITH MDOPK
   replace komdinar WITH mkomdinar
   REPLACE UKUPNO WITH MUKUPNO
   REPLACE PROCPOR WITH MPROCPOR
   REPLACE OSTALO WITH MOSTALO
   *REPLACE SPORAZUM WITH MSPORAZUM
   REPLACE DUG WITH MDUG
   REPLACE UPLAC WITH MUPLAC
   REPLACE POREZ WITH MPOREZ
   REPLACE SOC WITH MSOC
   REPLACE KAMATA WITH MKAMATA
   REPLACE SVEGA WITH MSVEGA
   REPLACE SALDO WITH SVEGA+DUG-UPLAC+KAMATA+ostalo
   REPLACE BRRAC WITH MBRRAC
   REPLACE MODEL WITH MMODEL
   REPLACE BRNAL WITH MBRNAL
   REPLACE OSNOV WITH MOSNOV
   REPLACE POC WITH MPOC
   REPLACE KRAJ WITH MKRAJ
   REPLACE POT WITH MPOT
   REPLACE UKPOT WITH MPOT
   REPLACE PVODA WITH MPVODA
   REPLACE PKANAL WITH MPKANAL
   REPLACE SLEP WITH  MSLEP
   REPLACE POPPROC WITH  MPOPPROC
   REPLACE POPKAN WITH  MPOPKAN
   REPLACE POPSOC WITH  MPOPSOC   
   REPLACE BRSTAN WITH MBRSTAN
   REPLACE UKSTAN WITH MUKSTAN
   REPLACE DOMAC WITH MDOMAC
   REPLACE KS WITH MKS
   REPLACE KSSIFRA WITH MKSSIFRA
   REPLACE VRSTA WITH MVRSTA
   REPLACE SIFUL WITH MSIFUL
   REPLACE ULICA WITH MULICA
   REPLACE ULBROJ WITH MULBROJ
   REPLACE BROJ WITH MBROJ
   REPLACE IME_PREZ WITH MIME_PREZ
   REPLACE RABAT WITH MRABAT
   replace datcit WITH mdatcit
   replace pausal WITH mpausal
   replace mespausal WITH mmespausal
   REPLACE IME_PREZc WITH MIME_PREZc
   REPLACE ULICAc WITH MULICAc
   
*   REPLACE SVEGA WITH MSVEGA
   MDDUG=VODA+DOPV+KAN+DOPK+POREZ-SOC-RABAT+KAMATA+komdinar+VODA2+VODA3+KAN2+KAN3
   SELECT VPUPL
   SET ORDER TO 1
   SEEK Mpib
   IF FOUND()
       DO WHILE.NOT.EOF()
          IF pib<>Mpib
             EXIT
          ENDIF
          IF brnal=mbrnal
          IF DUG<>0
             REPLACE DUG WITH 0
             REPLACE BRRAC WITH ''
          ENDIf    
          endif
          SKIP
       ENDDO
   ENDIF    
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE GRUPA WITH MGRUPA
   REPLACE DUG WITH MDDUG
   REPLACE DATUM WITH MDATUM
   REPLACE VALUTA WITH MVALUTA
   REPLACE BRRAC WITH MBRRAC
   REPLACE BRNAL WITH MBRNAL
   replace kamata WITH mkamata
   SET ORDER TO 
   SELECT VP
