PROCEDURE VD0TAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       VD0.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE VDATAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       VDA.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE AKOMUN00TAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   AKOMUN00.RELEASE
ENDPROC
 
PROCEDURE VDAKOEFTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL ESC       VKAKOEF.RELEASE
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL F10       DO KAKOEFKOEF 
ENDPROC
 
PROCEDURE VDUPLTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       VDUPL.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE VDUPLDTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       VDUPLD.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE VDUPLDFTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       VDUPLDF.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC


PROCEDURE VDPODTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       VDPOD.RELEASE
ENDPROC

PROCEDURE VDAFTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       VDAF.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE VDPODFTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       VDPODF.RELEASE
ENDPROC


PROCEDURE VD0TAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   VD0.RELEASE
ENDPROC


PROCEDURE VDSUD0TAST
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   VDSUD0.RELEASE
ENDPROC

PROCEDURE VDSUDTAST
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   VDSUD.RELEASE
ENDPROC

PROCEDURE VDSUD0DODRACTAST
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   VDSUD0DODRAC.RELEASE
ENDPROC

PROCEDURE VDANALIZVOTAST
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   VDANALIZVO.RELEASE
ENDPROC


PROCEDURE VT0TAST
   ON KEY LABEL F1    DO HELPN WITH 'VT0'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VT0.RELEASE
   ON KEY LABEL F2        ! /N CALC.EXE
ENDPROC


PROCEDURE VDKAKOEFTAST
   ON KEY LABEL F1    DO HELPN WITH 'VPKAKOEF'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VDKAKOEF.RELEASE
   ON KEY LABEL F2        ! /N CALC.EXE
ENDPROC

PROCEDURE VKKAKOEFTAST
   ON KEY LABEL F1    DO HELPN WITH 'VKKAKOEF'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VKKAKOEF.RELEASE
   ON KEY LABEL F2        ! /N CALC.EXE
ENDPROC

PROCEDURE VDFAN0TAST

ON KEY LABEL F1    DO HELPN WITH 'FAN0'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       FAN0.RELEASE
ON KEY LABEL +         DO FAN0DOD
on key label INS       DO FAN0DOD
ON KEY LABEL F3        DO FAN0DEONAZ
ON KEY LABEL ALT+F3        DO FAN0TEKRAC
ON KEY LABEL F4        DO FAN0TRAZI
ON KEY LABEL F5        DO FAN0GR5TRAZI
ON KEY LABEL F6        DO FAN0TRAZIF6
ON KEY LABEL F7        DO FAN0KARTF7
ON KEY LABEL F8        DO FAN0ZIROTRAZI
ON KEY LABEL CTRL+F12  DO OTVFAN0
ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC

ENDPROC


PROCEDURE HELPNTAST
   ON KEY LABEL ESC       HELPN.RELEASE
   ON KEY LABEL F1    ON KEY
   ON KEY LABEL CTRL+F12  HELPN.GRD0.READONLY=.F.
ENDPROC

PROCEDURE NCALCTAST
ON KEY LABEL F1    DO HELPN WITH 'NCALC'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL INS       DO NCALCDOD
ON KEY LABEL F7        DO NCALCF7
ON KEY LABEL F8        DO NCALCF8
ON KEY LABEL ESC       NCALC.RELEASE
ENDPROC

PROCEDURE PORUKADANETAST
   ON KEY LABEL F1    DO HELPN WITH 'PORUKADANE'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PORUKADANE.RELEASE
ENDPROC

PROCEDURE AN0K2TAST
ON KEY LABEL F1    DO HELPN WITH 'AN0K2'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       AN0K2.RELEASE
ENDPROC

PROCEDURE fan0dEONAZTAST
   ON KEY LABEL F1    DO HELPN WITH 'FAN0DEONAZ'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       fan0DEONAZ.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE PORUKATAST
   ON KEY LABEL F1    DO HELPN WITH 'PORUKA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PORUKA.RELEASE
ENDPROC


PROCEDURE VDfan0TEKRACTAST
   ON KEY LABEL F1    DO HELPN WITH 'FAN0TEKRAC'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       fan0TEKRAC.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC


PROCEDURE VDIZVESTAJITAST
   ON KEY LABEL F1    DO HELPN WITH 'VPIZVESTAJI'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VDIZVESTAJI.RELEASE
ENDPROC


PROCEDURE VDSERVISTAST
   ON KEY LABEL F1    DO HELPN WITH 'VPSERVIS'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VDSERVIS.RELEASE
ENDPROC

PROCEDURE VDDATCITTAST
   ON KEY LABEL F1    DO HELPN WITH 'VPDATCIT'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VDDATCIT.RELEASE
ENDPROC

PROCEDURE VDEKSPRIJEMPOTTAST
   ON KEY LABEL F1    DO HELPN WITH 'VPEKPRIJEMPOT'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VDEKSPRIJEMPOT.RELEASE
ENDPROC

PROCEDURE VDSTANJEAKONTTAST
   ON KEY LABEL F1    DO HELPN WITH 'VPSTANJEAKONT'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VDSTANJEAKONT.RELEASE
ENDPROC

PROCEDURE VDSTANJEAKONTFTAST
   ON KEY LABEL F1    DO HELPN WITH 'VPSTANJEAKONTF'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VDSTANJEAKONTF.RELEASE
ENDPROC

PROCEDURE VDSPORAZTAST
   ON KEY LABEL F1    DO HELPN WITH 'VPSPORAZ'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VDSPORAZ.RELEASE
ENDPROC

PROCEDURE VDSPORAZpodTAST
   ON KEY LABEL F1    DO HELPN WITH 'VPSPORAZPOD'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VDSPORAZPOD.RELEASE
ENDPROC

PROCEDURE VDSPORAZKARTTAST
   ON KEY LABEL F1    DO HELPN WITH 'VPSPORAZKART'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VDSPORAZKART.RELEASE
ENDPROC


PROCEDURE VDAPOTROSNJATAST
   ON KEY LABEL F1    DO HELPN WITH 'VPAPOTROSNJA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VDAPOTROSNJA.RELEASE
ENDPROC


PROCEDURE VCPODTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       VCPOD.RELEASE
ENDPROC

PROCEDURE VcAFTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       VcAF.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE VDULICETAST
   ON KEY LABEL F1    DO HELPN WITH 'VDULICE'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VDULICE.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC



PROCEDURE VDMESTATAST
   ON KEY LABEL F1    DO HELPN WITH 'VDMESTA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VDMESTA.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE VDGRUPATAST
   ON KEY LABEL F1    DO HELPN WITH 'VDGRUPA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VDGRUPA.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE VDZGRATAST
   ON KEY LABEL F1    DO HELPN WITH 'VDZGRA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VDZGRA.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE VDSAVETTAST
   ON KEY LABEL F1    DO HELPN WITH 'VDSAVET'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VDSAVET.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE VDVERTTAST
   ON KEY LABEL F1    DO HELPN WITH 'VDVERT'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VDVERT.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE VDSTANTAST
   ON KEY LABEL F1    DO HELPN WITH 'VDSTAN'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VDSTAN.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE VDVRSTEVTAST
   ON KEY LABEL F1    DO HELPN WITH 'VDVRSTEV'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VDVRSTEV.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE VDVODOMTAST
   ON KEY LABEL F1    DO HELPN WITH 'VDVODOM'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VDVODOM.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE VDUPLATATAST
   ON KEY LABEL F1    DO HELPN WITH 'VDUPLATA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VDUPLATA.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE VDVOPOTTAST
   ON KEY LABEL F1    DO HELPN WITH 'VDVOPOT'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VDVOPOT.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE VDAFTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       VDAF.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC
