FUNCTION vkdeft
LPARAMETERS mf
*SET STEP ON 
   SELECT VKPOSTT
   LOCATE FOR LOWER(ALLTRIM(POLJE))==lower(ALLTRIM(MF))
   IF FOUND()
      MPOLJE=ALLTRIM(POLJE)
      MVREDNOST=ALLTRIM(VREDNOST)
      *MTABELA=ALLTRIM(TABELA)
      SELECT pregled
      APPEND BLANK
      replace ppolje WITH mvrednost
      SELECT vkpostt
      MTEKST=ALLTRIM(TEKST)
      MFOLDER=ALLTRIM(FOLDER)
      SELECT VKUPLD
      IF LEN(MVREDNOST)>0
         MMVREDNOST=&mvredNost    
      ELSE
         MMVREDNOST=''
      ENDIF
      SELECT VKPOSTT
      MMRET=mtekst+mmvrednost
      RETURN MMRET
   ELSE
      SELECT VKPOSTT
      MMRET=''
      return MMRET      
   ENDIF
ENDFUNC