SELECT VP  
MPIB=PIB
MGRUPA=GRUPA
MIME_PREZ=IME_PREZ
MPREZ=AN00.PREZ
MIME=AN00.IME
*-----------TABELA OBRACUNA------------
select VPOBRAC
MCENOVNIK=CENOVNIK
MBROBRAC=BROBRAC
*------TABELA CENA
select VPCENE
SET ORDER TO 1
SEEK MCENOVNIK
mpstanje=pstanje
mzstanje=zstanje
APOC='ST'+ALLTRIM(STR(MPSTANJE,2,0))
AKRAJ='ST'+ALLTRIM(STR(MZSTANJE,2,0))
AKRAJK='ST'+ALLTRIM(STR(MZSTANJE,2,0))+'K'
MMES=MZSTANJE-MPSTANJE
mEdatum=datum
mEvaluta=valuta
mdatOD2=DTOS(datod)
mdatDO2=DTOS(datdo)
mdatOD=datod
mdatDO=datdo
mcvoda=cvoda
mcdvoda=cdvoda
mckanal=ckanal
mcdkanal=cdkanal
MRABPROC=RABPROC
MPROCPOR=PROCPOR
MMINDUG=MINDUG
mprocakont=procakont
MBRNAL='O'+ALLTRIM(STR(MBROBRAC,2,0))+MGRUPA
MPRDUG=0
SELECT VP
IF POPUST<>' '
   IMARABAT=1
ELSE
   IMARABAT=0
ENDIF   
SELECT VP
*-----------OBRACUN KAMATE---------------
   select VPUPL
   set order to 
   SELECT VP
   USE VPKAM IN 0 EXCLU ALIAS VPKAM
   SELECT VPKAM
   ZAP
   DO VPKAM WITH MPIB,MDATOD,MDATDO
   SELECT VPKAM
*--------PRENOS KAMATE------------------
   SET ORDER TO 1
   MKAMATA=0
   SELECT VPKAM
   SET ORDER TO 1
   SEEK MPIB
   IF FOUND()
      MKAMATA=0
      DO WHILE.NOT.EOF()
         IF PIB<>MPIB
            EXIT
         ENDIF
         IF DATPOC>=MDATOD.AND.DATPOC<=MDATDO
            mKAMATA=mKAMATA+KAMATA
         ENDIF   
         SKIP
      ENDDO
   ENDIF
   *DO VPPRENKAM WITH MPIB,MDATOD,MDATDO
   SELECT VPKAM
   USE
   SELECT VP  
   REPLACE DATUM WITH MEDATUM
   REPLACE VALUTA WITH MEVALUTA
   REPLACE MES WITH MMES
   IF MKAMATA>0
      REPLACE KAMATA WITH MKAMATA
   ELSE
      REPLACE KAMATA WITH 0
   ENDIF
*--------OBRACUN PAUSAL------------------
   IF PAUSAL=' '
      REPLACE POT WITH &AKRAJ-&APOC-&AKRAJK
      MPOT=POT
   ELSE
      IF MESPAUSAL<>0
         REPLACE POT WITH MMES*MESPAUSAL
      else      
         REPLACE POT WITH &AKRAJ-&APOC-&AKRAJK
      endif
      MPOT=POT
   ENDIF
   *IF POT<0
   *   REPLACE POT WITH 0
   *   MPOT=POT
   *ENDIF   
   REPLACE POC WITH &APOC
   REPLACE KRAJ WITH &AKRAJ
   *REPLACE UKPOT WITH KRAJ-POC
   REPLACE UKPOT WITH MPOT
   REPLACE VODA WITH 0
   REPLACE CENOVNIK WITH MCENOVNIK
*------------OBRACUN ZA VODU------------------   
   IF POT<>0
      IF PVODA<>' '
         REPLACE VODA WITH POT*MCVODA
         REPLACE DOPV WITH POT*MCDVODA    
         IF POPPROC<>0
            REPLACE DPVODA WITH ROUND(VODA*POPPROC/100,2)
         ELSE
            REPLACE DPVODA WITH 0   
         ENDIF   
      ELSE
         REPLACE VODA WITH 0
         REPLACE DOPV WITH 0
         REPLACE DPVODA WITH 0
      ENDIF
*------------OBRACUN ZA KANALIZACIJU
      IF PKANAL<>' '
         REPLACE KAN WITH POT*MCKANAL
         REPLACE DOPK WITH POT*MCDKANAL    
         IF POPPROC<>0
            REPLACE DPKAN WITH ROUND(VODA*POPKAN/100,2)
         ELSE
            REPLACE DPKAN WITH 0   
         ENDIF   
      ELSE
         REPLACE KAN WITH 0
         REPLACE DOPK WITH 0   
         REPLACE DPKAN WITH 0
      ENDIF
   ELSE
      REPLACE VODA WITH 0
      REPLACE DOPV WITH 0
      REPLACE KAN WITH 0
      REPLACE DOPK WITH 0   
      REPLACE DPVODA WITH 0
      REPLACE DPKAN WITH 0
   ENDIF
*-------UKUPNI PODACI------------------   
   REPLACE MESECI WITH MMES      
   MRABAT1=DPVODA+DPKAN
   MUKUPNO=VODA+DOPV+KAN+DOPK
   REPLACE UKUPNO WITH MUKUPNO   
   REPLACE PROCPOR WITH MPROCPOR
   MPR2DUG=0
   MUPLAC=0
   mispr=0
   MSPORAZUM=0
   MOSTALO=0
   MDUGPRE=0
   SELECT VPUPL
   SET ORDER TO 1
   SEEK MPIB
*----------PRETRAZIVANJE UPLATA ZA OSTALIM PODACIMA--------  
   if found()
      do while.not.eof()
         if PIB<>mPIB
            exit
         endif
         if DTOS(datum)<DTOS(mdatod)
            mpr2dug=mpr2dug+dug-pot
         endif    
         if DTOS(datum)>=DTOS(mdatod).and.DTOS(datum)<=DTOS(mdatdo)
            IF GRUPA='SPO'.OR.GRUPA='STA'.OR.GRUPA='STO'.OR.GRUPA='SPP'
               MSPORAZUM=MSPORAZUM+DUG
            ENDIF      
            IF GRUPA='ISP'.OR.GRUPA='KOD'
               MOSTALO=MOSTALO+DUG
            ENDIF      
         ENDIF
         if DTOS(datum)>=DTOS(mdatod).and.DTOS(datum)<=DTOS(mdatdo)
           mUPLAC=MUPLAC+POT
           mdATUM=datum 
        ENDIF
        *---PROVERA RABATA------------       
        if DTOS(VALUTA)<=DTOS(mdatdo)
           MDUGPRE=MDUGPRE+DUG-POT
        ENDIF
        skip
     enddo      
  ENDIF
  
   SELECT VPUPL
   DO idel WITH (kkockax)
   COPY STRUCTURE TO &kkocka
   USE &kkocka IN 0 ALIAS kocka EXCLUSIVE
   
   SET ORDER TO 1
   SEEK MPIB
*----------PRETRAZIVANJE UPLATA -------  
   md1=CTOD('')
   md2=CTOD('')
   md3=CTOD('')
   md4=CTOD('')
   md5=CTOD('')            
   mdin1=0            
   mdin2=0            
   mdin3=0            
   mdin4=0            
   mdin5=0         
   *SET STEP ON      
   if found()
      do while.not.eof()
         if PIB<>mPIB
            exit
         endif
         if DTOS(datum)>=DTOS(mdatod).and.DTOS(datum)<=DTOS(mdatdo)
         IF pot<>0
            mpot=pot
            mdatum=datum
            SELECT kocka
            APPEND BLANK
            replace pot WITH mpot
            replace datum WITH mdatum
         ENDIF
         endif 
         SELECT vpupl
        skip
     enddo      
  endif
  SELECT kocka
  GO top
  brojac=1
  DO while.not.eof()
     IF brojac=1
        md1=datum
        mdin1=pot
     ENDIF
     IF brojac=2
        md2=datum
        mdin2=pot
     ENDIF
     IF brojac=3
        md3=datum
        mdin3=pot
     ENDIF
     IF brojac=4
        md4=datum
        mdin4=pot
     ENDIF
     IF brojac=5
        md5=datum
        mdin5=pot
     ENDIF
     brojac=brojac+1
     SKIP
  enddo     
  SELECT kocka
  use
  
  SELECT VP
  IF MDUGPRE<=MMINDUG 
     *MRABAT2=ROUND(MRABPROC*(VODA+KAN-DPVODA-DPKAN)/100,2)
     mrabvoda=ROUND(MRABPROC*(VODA-DPVODA)/100,2)
     mrabkan=ROUND(MRABPROC*(KAN-DPKAN)/100,2)     
     MRABAT2=MRABVODA+MRABKAN     
  ELSE
     MRABVODA=0
     MRABKAN=0
     MRABAT2=0
  ENDIF

   MOSNOV=VODA+KAN-DPVODA-DPKAN-MRABAT2
   IF (voda-dpvoda)<>0
      Mporvoda=ROUND((voda-dpvoda-MRABVODA)*PROCPOR/100,2)      
   ELSE
      mporvoda=0   
   endif   
   IF (kan-dpkan)<>0
      Mporkan=ROUND((kan-dpkan-MRABKAN)*PROCPOR/100,2)      
   ELSE
      mporkan=0   
   endif   
   mporez=mporvoda+mporkan
   *IF MOSNOV>0
   *   MPOREZ=ROUND(MOSNOV*PROCPOR/100,2)
   *ELSE
   *   MPOREZ=0
   *ENDIF
   REPLACE OSNOV WITH MOSNOV
   REPLACE RABAT WITH MRABAT1+MRABAT2
   REPLACE RABVODA WITH MRABVODA
   REPLACE RABKAN WITH MRABKAN
   replace porvoda WITH mporvoda
   replace porkan WITH mporkan
   REPLACE POREZ WITH MPOREZ
   REPLACE SVEGA WITH MUKUPNO-RABAT+POREZ
   REPLACE BRNAL WITH MBRNAL


*----------POPUNJAVANJE GLAVNE TABELE----------
   SELECT VP
   REPLACE DUG WITH MPR2DUG
   REPLACE UPLAC WITH MUPLAC
   REPLACE OSTALO WITH MOSTALO+msporazum
   mbrrac=REPLICATE('0',2-LEN(ALLTRIM(STR(MZSTANJE,2,0))))+ALLTRIM(STR(MZSTANJE,2,0))+SUBSTR(STR(YEAR(medatum),4,0),3,2)+ALLTRIM(SUBSTR(pib,1,9))
   REPLACE BRRAC WITH MBRRAC
   M1=VAL(mbrrac)
   M2=(M1*100/97)-INT(M1*100/97)
   M3=ROUND(97*M2,0)
   M4=98-M3
   IF M4<=9
      M4='0'+STR(M4,1,0)
   ELSE
      M4=STR(M4,2,0)
   ENDIF      
   REPLACE model WITH +M4+'-'+ALLTRIM(mbrrac)
   
   SELECT VPUPLD
   SET ORDER TO 5
   SET EXACT OFF
   GO TOP
   DO WHILE.T.
      SEEK MBRRAC
      IF FOUND()
         REPLACE PIB WITH SPACE(13)
         REPLACE BRNAL WITH SPACE(6)
         REPLACE BRRAC WITH ''
         REPLACE GRUPA WITH ''
         REPLACE CENOVNIK WITH 0
         REPLACE PSTanje WITH 0
         REPLACE ZSTANJE WITH 0
         REPLACE MESEC WITH 0
         REPLACE DATUM WITH CTOD('')
         REPLACE VALUTA WITH CTOD('')
         REPLACE DATOD WITH CTOD('')
         REPLACE DATDO WITH CTOD('')
         REPLACE CVODA WITH 0
         REPLACE CDVODA WITH 0
         REPLACE CKANAL WITH 0
         REPLACE CDKANAL WITH 0
         REPLACE PROCPOR WITH 0
         REPLACE VODA WITH 0
         REPLACE DOPV WITH 0
         REPLACE KAN WITH 0
         REPLACE DOPK WITH 0
         REPLACE UKUPNO WITH 0
         REPLACE OSTALO WITH 0
         REPLACE DPVODA WITH 0
         REPLACE DPKAN WITH 0
         REPLACE KAMATA WITH 0
         REPLACE OSNOV WITH 0
         REPLACE POREZ WITH 0
         REPLACE PORVODA WITH 0
         REPLACE PORKAN WITH 0
         REPLACE POC WITH 0
         REPLACE KRAJ WITH 0
         REPLACE POT WITH 0
         REPLACE RABAT WITH 0
         REPLACE RABVODA WITH 0
         REPLACE RABKAN WITH 0                  
         REPLACE DUG WITH 0
         REPLACE SALDO WITH 0
         REPLACE SVEGA WITH 0
         REPLACE MESPAUSAL WITH 0
         REPLACE PAUSAL WITH ' '
         LOOP 
      ELSE
         EXIT
      ENDIF
   ENDDO   
  
   SELECT VP
   MGRUPA=GRUPA
   MDATUM=DATUM
   MVALUTA=VALUTA
   MPAUSAL=PAUSAL
   MMESPAUSAL=MESPAUSAL
   MVODA=VODA
   MDOPV=DOPV
   MKAN=KAN
   MDOPK=DOPK
   MDPVODA=DPVODA
   MDPKAN=DPKAN
   MUKUPNO=UKUPNO
   MOSTALO=OSTALO
   MOSNOV=OSNOV
   Mdug=dug
   MSVEGA=SVEGA
   MUPLAC=UPLAC
   MPOREZ=POREZ
   MPORVODA=PORVODA
   MPORKAN=PORKAN   
   MKAMATA=KAMATA
   MBRRAC=BRRAC
   MMODEL=MODEL
   MRABAT=RABAT
   MPROCPOR=PROCPOR
   MPOC=POC
   MKRAJ=KRAJ
   MPOT=POT
   MPVODA=PVODA
   MPKANAL=PKANAL
   MSLEP=SLEP
   MPOPPROC=POPPROC
   MPOPKAN=POPKAN
   MVRSTA=VRSTA
   MSIFUL=SIFUL
   MULICA=ULICA
   MULBROJ=ULBROJ
   MBROJ=BROJ
   MIME_PREZ=IME_PREZ
   MAPREZ=AN00.PREZ
   MAIME=AN00.IME
   MAOTAC=AN00.OTAC
   MAPOSTA0=AN00.POSTA0
   MAMESTO0=AN00.MESTO0
   MASIFUL0=AN00.SIFUL0
   MAULICA0=AN00.ULICA0
   MAULBROJ0=AN00.ULBROJ0
   MASTAN0=AN00.STAN0
   MAPIB=AN00.PIB
   MAMATICNI0=AN00.MATICNI0
   MAMATICNI1=AN00.MATICNI1
   MRABAT=RABAT   
   MRABVODA=RABVODA
   MRABKAN=RABKAN
   mdatcit=datcit
   SELECT VPUPLD
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE GRUPA WITH MGRUPA
   REPLACE CENOVNIK WITH MCENOVNIK
   REPLACE PSTanje WITH MPSTANJE
   REPLACE ZSTANJE WITH MZSTANJE
   REPLACE MESEC WITH MMES
   REPLACE DATUM WITH  MDATUM
   REPLACE VALUTA WITH MVALUTA
   REPLACE DATOD WITH MDATOD
   REPLACE DATDO WITH MDATDO
   REPLACE CVODA WITH MCVODA
   REPLACE CDVODA WITH MCDVODA
   REPLACE CKANAL WITH MCKANAL
   REPLACE CDKANAL WITH MCDKANAL
   REPLACE DPVODA WITH MDPVODA
   REPLACE DPKAN WITH MDPKAN
   REPLACE PROCPOR WITH MPROCPOR
   REPLACE VODA WITH MVODA
   REPLACE DOPV WITH MDOPV
   REPLACE KAN WITH MKAN
   REPLACE DOPK WITH MDOPK
   REPLACE UKUPNO WITH MUKUPNO
   REPLACE PROCPOR WITH MPROCPOR
   REPLACE OSTALO WITH MOSTALO
   REPLACE DUG WITH MDUG
   REPLACE UPLAC WITH MUPLAC
   REPLACE POREZ WITH MPOREZ
   REPLACE PORVODA WITH MPORVODA
   REPLACE PORKAN WITH MPORKAN
   REPLACE KAMATA WITH MKAMATA
   REPLACE SVEGA WITH MSVEGA
   REPLACE SALDO WITH SVEGA+DUG-UPLAC+KAMATA+ostalo
   REPLACE BRRAC WITH MBRRAC
   REPLACE MODEL WITH MMODEL
   REPLACE BRNAL WITH MBRNAL
   REPLACE OSNOV WITH MOSNOV
   REPLACE POC WITH MPOC
   REPLACE KRAJ WITH MKRAJ
   REPLACE POT WITH MPOT
   REPLACE UKPOT WITH MPOT
   REPLACE PVODA WITH MPVODA
   REPLACE PKANAL WITH MPKANAL
   REPLACE SLEP WITH  MSLEP
   REPLACE POPPROC WITH  MPOPPROC
   REPLACE POPKAN WITH  MPOPKAN
   REPLACE VRSTA WITH MVRSTA
   REPLACE SIFUL WITH MSIFUL
   REPLACE ULICA WITH MULICA
   REPLACE ULBROJ WITH MULBROJ
   REPLACE BROJ WITH MBROJ
   REPLACE IME_PREZ WITH MIME_PREZ
   REPLACE APREZ WITH MAPREZ
   REPLACE AIME WITH MAIME
   REPLACE AOTAC WITH MAOTAC
   REPLACE APOSTA0 WITH MAPOSTA0
   REPLACE AMESTO0 WITH MAMESTO0
   REPLACE ASIFUL0 WITH MASIFUL0
   REPLACE AULICA0 WITH MAULICA0
   REPLACE AULBROJ0 WITH MAULBROJ0
   REPLACE ASTAN0 WITH MASTAN0
   REPLACE APIB WITH MAPIB
   REPLACE AMATICNI0 WITH MAMATICNI0
   REPLACE AMATICNI1 WITH MAMATICNI1
   REPLACE RABAT WITH MRABAT
   REPLACE RABVODA WITH MRABVODA
   REPLACE RABKAN WITH MRABKAN
   replace datcit WITH mdatcit
   REPLACE PAUSAL WITH MPAUSAL
   REPLACE MESPAUSAL WITH MMESPAUSAL
   replace d1 with md1
   replace d2 with md2
   replace d3 with md3
   replace d4 with md4
   replace d5 with md5            
   replace din1 with mdin1   
   replace din2 with mdin2   
   replace din3 with mdin3   
   replace din4 with mdin4   
   replace din5 with mdin5               
   
   MDDUG=VODA+DOPV+KAN+DOPK+POREZ-RABAT+KAMATA
   SELECT VPUPL
   SET ORDER TO 6
   SEEK MBRRAC 
   IF FOUND()
       DO WHILE.NOT.EOF()
          IF BRRAC<>MBRRAC
             EXIT
          ENDIF
          IF DUG<>0
             REPLACE DUG WITH 0
             REPLACE PIB WITH ''
             REPLACE BRRAC WITH ''
          ENDIF    
          SKIP
       ENDDO
   ENDIF    
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE GRUPA WITH MGRUPA
   REPLACE DUG WITH MDDUG
   REPLACE DATUM WITH MDATUM
   REPLACE VALUTA WITH MVALUTA
   REPLACE BRRAC WITH MBRRAC
   REPLACE BRNAL WITH MBRNAL
   SELECT VP
