MPIB=VKUPL2.TXTPIB.VALUE
MDATUM=VKUPL2.TXTDATUM.VALUE
MPOT=VKUPL2.TXTPOT.VALUE
MBRNAL=VKUPL2.TXTBRNAL.VALUE
MGRUPA=VKUPL2.TXTGRUPA.VALUE
MDANAS=DATE()
MVREME=TIME()
MVALUTA=VKUPL2.TXTVALUTA.VALUE
MOPIS=VKUPL2.TXTOPIS.VALUE
IF MPOT<>0
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE DATUM WITH MDATUM
   REPLACE POT WITH MPOT
   REPLACE BRNAL WITH MBRNAL
   REPLACE GRUPA WITH MGRUPA
   REPLACE DANAS WITH MDANAS
   REPLACE VREME WITH MVREME
   REPLACE VALUTA WITH MVALUTA
   REPLACE OPIS WITH MOPIS
   SELECT VPUPL
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE DATUM WITH MDATUM
   REPLACE POT WITH MPOT
   REPLACE BRNAL WITH MBRNAL
   REPLACE GRUPA WITH MGRUPA
   REPLACE DANAS WITH MDANAS
   REPLACE VREME WITH MVREME
   REPLACE VALUTA WITH MVALUTA
   REPLACE OPIS WITH MOPIS
   SELECT VPUPL2
ENDIF
VKUPL2.TXTPIB.Value=SPACE(13)
VKUPL2.TXTPOT.Value=0
VKUPL2.TXTPIB.SETFOCUS 