PUSH KEY CLEAR
SET ORDER TO 
IF RECCOUNT()>0
      MDATDOK=DATDOK
      MMESEC=MESEC
      MDOSMESEC=DOSMESEC
      APPEND BLANK
      REPLACE DATDOK WITH MDATDOK
      REPLACE MESEC WITH MMESEC
      REPLACE OPER WITH OPERATER
      REPLACE DATUM WITH DATE()
      REPLACE VREME WITH TIME()   
      VOZMAPA.GRD0.SETFOCUS
      VOZMAPA.REFRESH
   ELSE
      APPEND BLANK
      REPLACE DATDOK WITH DATE()
   ENDIF
   VOZMAPA.GRD0.COLUMN1.SETFOCUS
   VOZMAPA.REFRESH  
POP KEY