SELECT VP
MPIB=PIB
MGRUPA=GRUPA
MIME_PREZ=IME_PREZ
MPREZ=AN00.PREZ
MIME=AN00.IME
*-----------TABELA OBRACUNA------------
select VPOBRAC
MCENOVNIK=CENOVNIK
MBROBRAC=BROBRAC
*------TABELA CENA
select VPCENE
SET ORDER TO 1
SEEK MCENOVNIK
mpstanje=pstanje
mzstanje=zstanje
APOC='ST'+ALLTRIM(STR(MPSTANJE,2,0))
AKRAJ='ST'+ALLTRIM(STR(MZSTANJE,2,0))
MMES=MZSTANJE-MPSTANJE
mEdatum=datum
mEvaluta=valuta
mdatOD2=DTOS(datod)
mdatDO2=DTOS(datdo)
mdatOD=datod
mdatDO=datdo
mcvoda=cvoda
mcdvoda=cdvoda
mckanal=ckanal
mcdkanal=cdkanal
MRABPROC=RABPROC
MPROCPOR=PROCPOR
mprocakont=procakont
MBRNAL='O'+ALLTRIM(STR(MBROBRAC,2,0))+MGRUPA
MPRDUG=0
SELECT VP
IF POPUST<>' '
   IMARABAT=1
ELSE
   IMARABAT=0
ENDIF   
SELECT VP
*-----------OBRACUN KAMATE---------------
   select VPUPL
   set order to 
   SELECT VP
   USE VPKAM IN 0 EXCLU
   SELECT VPKAM
   ZAP
   DO VPKAM WITH MPIB,MDATOD,MDATDO
   SELECT VPKAM
*--------PRENOS KAMATE------------------
   SET ORDER TO 1
   MKAMATA=0
   SELECT VPKAM
   SET ORDER TO 1
   SEEK MPIB
   IF FOUND()
      MKAMATA=0
      DO WHILE.NOT.EOF()
         IF PIB<>MPIB
            EXIT
         ENDIF
         IF DATPOC>=MDATOD.AND.DATPOC<=MDATDO
            mKAMATA=mKAMATA+KAMATA
         ENDIF   
         SKIP
      ENDDO
   ENDIF
   *DO VPPRENKAM WITH MPIB,MDATOD,MDATDO
   SELECT VPKAM
   USE
   SELECT VP  
   REPLACE DATUM WITH MEDATUM
   REPLACE VALUTA WITH MEVALUTA
   REPLACE MES WITH MMES
   IF MKAMATA>0
      REPLACE KAMATA WITH MKAMATA
   ELSE
      REPLACE KAMATA WITH 0
   ENDIF
*--------OBRACUN PAUSAL------------------
   IF PAUSAL=' '
      REPLACE POT WITH &AKRAJ-&APOC
      MPOT=POT
   ELSE
      REPLACE POT WITH MMES*MESPAUSAL
      MPOT=POT
   ENDIF
   IF POT<0
      REPLACE POT WITH 0
      MPOT=POT
   ENDIF   
   REPLACE POC WITH &APOC
   REPLACE KRAJ WITH &AKRAJ
   *REPLACE UKPOT WITH KRAJ-POC
   REPLACE UKPOT WITH MPOT
   REPLACE VODA WITH 0
   REPLACE CENOVNIK WITH MCENOVNIK
*------------OBRACUN ZA VODU------------------   
   IF POT>0
      IF PVODA<>' '
         REPLACE VODA WITH POT*MCVODA*(100-POPPROC)/100
         REPLACE DOPV WITH POT*MCDVODA*(100-POPPROC)/100    
      ELSE
         REPLACE VODA WITH 0
         REPLACE DOPV WITH 0
      ENDIF
*------------OBRACUN ZA KANALIZACIJU
      IF PKANAL<>' '
         REPLACE KAN WITH POT*MCKANAL*(100-POPKAN)/100
         REPLACE DOPK WITH POT*MCDKANAL*(100-POPKAN)/100    
      ELSE
         REPLACE KAN WITH 0
         REPLACE DOPK WITH 0   
      ENDIF
   ELSE
      REPLACE VODA WITH 0
      REPLACE DOPV WITH 0
      REPLACE KAN WITH 0
      REPLACE DOPK WITH 0   
   ENDIF
*----------PRETRAZIVANJE UPLATA zbog rabata--------  

   MRABATDUG=0
   SELECT VPUPL
   SET ORDER TO 1
   SEEK MPIB
   if found()
      do while.not.eof()
         if PIB<>mPIB
            exit
         ENDIF
         IF brnal<>mbrnal
*            SET STEP on
            IF datum<=mdatdo
               mrabatdug=mrabatdug+dug-pot
            endif
         endif   
        skip
     enddo      
   ELSE
      mrabatdug=0   
   endif
IF mrabatdug<=0
   imarabat=1
ELSE
   imarabat=0
endif
*-------UKUPNI PODACI------------------   
SELECT vp
   REPLACE MESECI WITH MMES      
   IF IMARABAT=1
      MRABOSNOV=VODA+DOPV+KAN+DOPK
   ELSE
      MRABOSNOV=0
   ENDIF      
   *MMAKSPOT=MMES*15
   *IF POT<=MMAKSPOT
   IF MRABOSNOV>0
      MRABAT=ROUND(MRABOSNOV*MRABPROC/100,2)
   ELSE
      MRABAT=0
   ENDIF
   *ELSE
   *   MRABAT=0
   *ENDIF
   REPLACE RABAT WITH MRABAT
   MUKUPNO=VODA+DOPV+KAN+DOPK
   REPLACE UKUPNO WITH MUKUPNO   
   *--------------socijala
   *   SET STEP ON 
   IF poplava=0
      mosnsoc=mmes*10*brstan
      mmosndinsoc=MUKUPNO-mRABAT
      IF pot<=mosnsoc
         mmosndinsoc=(MUKUPNO-mRABAT)
      ELSE
         mmosndinsoc=ROUND(mosnsoc/pot*(MUKUPNO-MRABAT),2)
      endif   
   ELSE
         mosnsoc=MUKUPNO-mRABAT 
         mmosndinsoc=MUKUPNO-MRABAT          
   endif      
   IF POPSOC+poplava>0.AND.(mmosndinsoc)>0
      MSOC=ROUND((MmosnDINsoc)*(POPSOC+poplava)/100,2)
   ELSE
      MSOC=0
   endif   
   IF poplava>0      
      MSOCp=ROUND((MmosnDINsoc)*(poplava)/100,2)      
   ELSE
      msocp=0
   ENDIF
   REPLACE SOC WITH MSOC
   REPLACE SOCp WITH MSOCp   
   
   *-------------kraj socijala
   REPLACE PROCPOR WITH MPROCPOR
   IF (UKUPNO-SOC-RABAT)>0
      MPOREZ=ROUND((UKUPNO-SOC-RABAT)*PROCPOR/100,2)
   ELSE
      MPOREZ=0
   ENDIF
  
   REPLACE POREZ WITH MPOREZ
   REPLACE SVEGA WITH UKUPNO-SOC-RABAT+POREZ
   MOSNOV=MUKUPNO-MSOC-mrabat+MPOREZ
   IF MOSNOV>0.AND.MMES>0   
      REPLACE AKONT WITH ROUND( (100+MPROCAKONT)*MOSNOV/MMES/100,0)
   ELSE
      REPLACE AKONT WITH 0
   ENDIF   
   REPLACE BRNAL WITH MBRNAL
   MPR2DUG=0
   MUPLAC=0
   mispr=0
   MSPORAZUM=0
   MOSTALO=0

   SELECT VPUPL
   SET ORDER TO 1
   SEEK MPIB
*----------PRETRAZIVANJE UPLATA ZA OSTALIM PODACIMA--------  
   if found()
      do while.not.eof()
         if PIB<>mPIB
            exit
         endif
         if DTOS(datum)<DTOS(mdatod)
            mpr2dug=mpr2dug+dug-pot
         endif    
         if DTOS(datum)>=DTOS(mdatod).and.DTOS(datum)<=DTOS(mdatdo)
            IF GRUPA='SPO'.OR.GRUPA='STA'.OR.GRUPA='STO'.OR.GRUPA='SPP'
               MSPORAZUM=MSPORAZUM+DUG
            ENDIF      
            IF GRUPA='ISP'.OR.GRUPA='KOD'.OR.GRUPA='SUO'.OR.GRUPA='SUV'
               MOSTALO=MOSTALO+DUG
            ENDIF      
         ENDIF
         if DTOS(datum)>=DTOS(mdatod).and.DTOS(datum)<=DTOS(mdatdo)
           mUPLAC=MUPLAC+POT
           mdATUM=datum 
        endif
        skip
     enddo      
  endif
*----------POPUNJAVANJE GLAVNE TABELE----------
   SELECT VP
   REPLACE DUG WITH MPR2DUG
   REPLACE UPLAC WITH MUPLAC
   REPLACE OSTALO WITH MOSTALO+msporazum
   *REPLACE SPORAZUM WITH MSPORAZUM
*   REPLACE SVEGA WITH UKUPNO+OSTALO+SPORAZUM-UPLAC+DUG+POREZ+KAMATA-MSOC
*   REPLACE ZADUZENJE WITH UKUPNO+POREZ-SOC 
*   REPLACE SOC WITH -MSOC
   SET CENTURY OFF
   MGODINA=SUBSTR(DTOC(medatum),7,2)
   mbrrac=ALLTRIM(pib)+ALLTRIM(STR(MBROBRAC,2,0))+mgodina
   REPLACE BRRAC WITH MBRRAC
   M1=VAL(mbrrac)
   M2=(M1*100/97)-INT(M1*100/97)
   M3=ROUND(97*M2,0)
   M4=98-M3
   IF M4<=9
      M4='0'+STR(M4,1,0)
   ELSE
      M4=STR(M4,2,0)
   ENDIF      
   REPLACE model WITH +M4+'-'+ALLTRIM(mbrrac)
   SET CENTURY on
   SELECT VPUPLD
   SET ORDER TO 1
   SET EXACT OFF
   GO TOP
   DO WHILE.T.
      LOCATE FOR pib=mpib.and.brnal=mbrnal
      IF FOUND()
         SET ORDER TO 
         REPLACE PIB WITH SPACE(13)
         REPLACE BRNAL WITH SPACE(6)
         REPLACE BRRAC WITH ''
         REPLACE GRUPA WITH ''
         REPLACE CENOVNIK WITH 0
         REPLACE PSTanje WITH 0
         REPLACE ZSTANJE WITH 0
         REPLACE MESEC WITH 0
         REPLACE DATUM WITH CTOD('')
         REPLACE VALUTA WITH CTOD('')
         REPLACE DATOD WITH CTOD('')
         REPLACE DATDO WITH CTOD('')
         REPLACE CVODA WITH 0
         REPLACE CDVODA WITH 0
         REPLACE CKANAL WITH 0
         REPLACE CDKANAL WITH 0
         REPLACE PROCPOR WITH 0
         REPLACE VODA WITH 0
         REPLACE DOPV WITH 0
         REPLACE KAN WITH 0
         REPLACE DOPK WITH 0
         REPLACE UKUPNO WITH 0
         REPLACE PROCPOR WITH 0
         REPLACE OSTALO WITH 0
         REPLACE SPORAZUM WITH 0
         REPLACE SOC WITH 0
         REPLACE SOCp WITH 0         
         REPLACE KAMATA WITH 0
         REPLACE OSNOV WITH 0
         REPLACE POREZ WITH 0
         REPLACE POC WITH 0
         REPLACE KRAJ WITH 0
         REPLACE POT WITH 0
         REPLACE RABAT WITH 0
         REPLACE DUG WITH 0
         REPLACE SALDO WITH 0
         REPLACE SVEGA WITH 0
         LOOP 
      ELSE
         EXIT
      ENDIF
   ENDDO   
   SET ORDER TO 
   SELECT VP
   MGRUPA=GRUPA
   MDATUM=DATUM
   MVALUTA=VALUTA
   MPAUSAL=PAUSAL
   MMESPAUSAL=MESPAUSAL
   MVODA=VODA
   MDOPV=DOPV
   MKAN=KAN
   MDOPK=DOPK
   MUKUPNO=UKUPNO
   MOSTALO=OSTALO
   *msporazum=sPORAzum
   mdug=dug
   MSVEGA=SVEGA
   MUPLAC=UPLAC
   MPOREZ=POREZ
   MSOC=SOC
   MSOCp=SOCp   
   MKAMATA=KAMATA
   MBRRAC=BRRAC
   MMODEL=MODEL
   MRABAT=RABAT
   MPROCPOR=PROCPOR
   MPOC=POC
   MKRAJ=KRAJ
   MPOT=POT
   MPVODA=PVODA
   MPKANAL=PKANAL
   MSLEP=SLEP
   MPOPPROC=POPPROC
   MPOPKAN=POPKAN
   MPOPSOC=POPSOC
   MPOPlava=POPlava
   MBRSTAN=BRSTAN
   MUKSTAN=UKSTAN
   MDOMAC=DOMAC
   MKS=KS
   MKSSIFRA=KSSIFRA
   MVRSTA=VRSTA
   MSIFUL=SIFUL
   MULICA=ULICA
   MULICAc=ULICAc
   MULBROJ=ULBROJ
   MBROJ=BROJ
   MIME_PREZ=IME_PREZ
   MAPREZ=AN00.PREZ
   MIME_PREZc=IME_PREZc
   MAPREZc=AN00.PREZc
   MAIME=AN00.IME
   *MAIMEc=AN00.IMEc
   MAOTAC=AN00.OTAC
   MAPOSTA0=AN00.POSTA0
   MAMESTO0=AN00.MESTO0
   MAMESTO0c=AN00.MESTO0c   
   MASIFUL0=AN00.SIFUL0
   MAULICA0=AN00.ULICA0
   MAULICA0c=AN00.ULICA0c   
   MAULBROJ0=AN00.ULBROJ0
   MASTAN0=AN00.STAN0
   MAPIB=AN00.PIB
   MAMATICNI0=AN00.MATICNI0
   MAMATICNI1=AN00.MATICNI1
   MRABAT=RABAT   
   mdatcit=datcit
   SELECT VPUPLD
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE GRUPA WITH MGRUPA
   REPLACE CENOVNIK WITH MCENOVNIK
   REPLACE PSTanje WITH MPSTANJE
   REPLACE ZSTANJE WITH MZSTANJE
   REPLACE MESEC WITH MMES
   REPLACE DATUM WITH  MDATUM
   REPLACE VALUTA WITH MVALUTA
   REPLACE DATOD WITH MDATOD
   REPLACE DATDO WITH MDATDO
   REPLACE CVODA WITH MCVODA
   REPLACE CDVODA WITH MCDVODA
   REPLACE CKANAL WITH MCKANAL
   REPLACE CDKANAL WITH MCDKANAL
   REPLACE PROCPOR WITH MPROCPOR
   REPLACE VODA WITH MVODA
   REPLACE DOPV WITH MDOPV
   REPLACE KAN WITH MKAN
   REPLACE DOPK WITH MDOPK
   REPLACE UKUPNO WITH MUKUPNO
   REPLACE PROCPOR WITH MPROCPOR
   REPLACE OSTALO WITH MOSTALO
   *REPLACE SPORAZUM WITH MSPORAZUM
   REPLACE DUG WITH MDUG
   REPLACE UPLAC WITH MUPLAC
   REPLACE POREZ WITH MPOREZ
   REPLACE SOC WITH MSOC
   REPLACE SOCp WITH MSOCp   
   REPLACE KAMATA WITH MKAMATA
   REPLACE SVEGA WITH MSVEGA
   REPLACE SALDO WITH SVEGA+DUG-UPLAC+KAMATA+ostalo
   REPLACE BRRAC WITH MBRRAC
   REPLACE MODEL WITH MMODEL
   REPLACE BRNAL WITH MBRNAL
   REPLACE OSNOV WITH MOSNOV
   REPLACE POC WITH MPOC
   REPLACE KRAJ WITH MKRAJ
   REPLACE POT WITH MPOT
   REPLACE UKPOT WITH MPOT
   REPLACE PVODA WITH MPVODA
   REPLACE PKANAL WITH MPKANAL
   REPLACE SLEP WITH  MSLEP
   REPLACE POPPROC WITH  MPOPPROC
   REPLACE POPKAN WITH  MPOPKAN
   REPLACE POPSOC WITH  MPOPSOC   
   REPLACE POPlava WITH  MPOPlava
   REPLACE BRSTAN WITH MBRSTAN
   REPLACE UKSTAN WITH MUKSTAN
   REPLACE DOMAC WITH MDOMAC
   REPLACE KS WITH MKS
   REPLACE KSSIFRA WITH MKSSIFRA
   REPLACE VRSTA WITH MVRSTA
   REPLACE SIFUL WITH MSIFUL
   REPLACE ULICA WITH MULICA
   REPLACE ULICAc WITH MULICAc
   REPLACE ULBROJ WITH MULBROJ
   REPLACE BROJ WITH MBROJ
   REPLACE IME_PREZ WITH MIME_PREZ
   REPLACE IME_PREZc WITH MIME_PREZc   
   REPLACE APREZ WITH MAPREZ
   REPLACE AIME WITH MAIME  
   REPLACE APREZc WITH MAPREZc
   *REPLACE AIMEc WITH MAIMEc
   REPLACE AOTAC WITH MAOTAC
   REPLACE APOSTA0 WITH MAPOSTA0
   REPLACE AMESTO0 WITH MAMESTO0
   REPLACE AMESTO0c WITH MAMESTO0c   
   REPLACE ASIFUL0 WITH MASIFUL0
   REPLACE AULICA0 WITH MAULICA0
   REPLACE AULICA0c WITH MAULICA0c
   REPLACE AULBROJ0 WITH MAULBROJ0
   REPLACE ASTAN0 WITH MASTAN0
   REPLACE APIB WITH MAPIB
   REPLACE AMATICNI0 WITH MAMATICNI0
   REPLACE AMATICNI1 WITH MAMATICNI1
   REPLACE RABAT WITH MRABAT
   replace datcit WITH mdatcit
*   REPLACE SVEGA WITH MSVEGA
   MDDUG=VODA+DOPV+KAN+DOPK+POREZ-SOC-RABAT+KAMATA
   SELECT VPUPL
   SET ORDER TO 1
   SEEK Mpib
   IF FOUND()
       DO WHILE.NOT.EOF()
          IF pib<>Mpib
             EXIT
          ENDIF
          IF brnal=mbrnal
          IF DUG<>0
             REPLACE DUG WITH 0
             replace kamata WITH 0
             REPLACE BRRAC WITH ''
          ENDIf    
          endif
          SKIP
       ENDDO
   ENDIF    
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE GRUPA WITH MGRUPA
   REPLACE DUG WITH MDDUG
   replace kamata WITH mkamata
   REPLACE DATUM WITH MDATUM
   REPLACE VALUTA WITH MVALUTA
   REPLACE BRRAC WITH MBRRAC
   REPLACE BRNAL WITH MBRNAL
   SET ORDER TO 
   SELECT VP
