PROCEDURE VPATAST   
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       VPA.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE AKOMUN00TAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   AKOMUN00.RELEASE
ENDPROC
 
PROCEDURE VKAKOEFTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL ESC       VKAKOEF.RELEASE
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL F10       DO KAKOEFKOEF 
ENDPROC
 
PROCEDURE VPUPLTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       VPUPL.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE VPUPLDTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       VPUPLD.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE VPUPLDFTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       VPUPLDF.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC


PROCEDURE VPPODTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       VPPOD.RELEASE
ENDPROC

PROCEDURE VPAFTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       VPAF.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE VPPODFTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       VPPODF.RELEASE
ENDPROC


PROCEDURE VP0TAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   VP0.RELEASE
ENDPROC


PROCEDURE VPSUD0TAST
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   VPSUD0.RELEASE
ENDPROC

PROCEDURE VPSUDTAST
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   VPSUD.RELEASE
ENDPROC

PROCEDURE VPSUD0DODRACTAST
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   VPSUD0DODRAC.RELEASE
ENDPROC

PROCEDURE VPANALIZVOTAST
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   VPANALIZVO.RELEASE
ENDPROC


PROCEDURE VT0TAST
   ON KEY LABEL F1    DO HELPN WITH 'VT0'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VT0.RELEASE
   ON KEY LABEL F2        ! /N CALC.EXE
ENDPROC


PROCEDURE VPKAKOEFTAST
   ON KEY LABEL F1    DO HELPN WITH 'VPKAKOEF'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VPKAKOEF.RELEASE
   ON KEY LABEL F2        ! /N CALC.EXE
ENDPROC

PROCEDURE VKKAKOEFTAST
   ON KEY LABEL F1    DO HELPN WITH 'VKKAKOEF'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VKKAKOEF.RELEASE
   ON KEY LABEL F2        ! /N CALC.EXE
ENDPROC

PROCEDURE VPFAN0TAST

ON KEY LABEL F1    DO HELPN WITH 'FAN0'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL ESC       FAN0.RELEASE
ON KEY LABEL +         DO FAN0DOD
on key label INS       DO FAN0DOD
ON KEY LABEL F3        DO FAN0DEONAZ
ON KEY LABEL ALT+F3        DO FAN0TEKRAC
ON KEY LABEL F4        DO FAN0TRAZI
ON KEY LABEL F5        DO FAN0GR5TRAZI
ON KEY LABEL F6        DO FAN0TRAZIF6
ON KEY LABEL F7        DO FAN0KARTF7
ON KEY LABEL F8        DO FAN0ZIROTRAZI
ON KEY LABEL CTRL+F12  DO OTVFAN0
ON KEY LABEL CTRL+PGDN DO IDIKRAJ
ON KEY LABEL CTRL+PGUP DO IDIPOC

ENDPROC


PROCEDURE HELPNTAST
   ON KEY LABEL ESC       HELPN.RELEASE
   ON KEY LABEL F1    ON KEY
   ON KEY LABEL CTRL+F12  HELPN.GRD0.READONLY=.F.
ENDPROC

PROCEDURE NCALCTAST
ON KEY LABEL F1    DO HELPN WITH 'NCALC'
ON KEY LABEL F2        ! /N CALC.EXE
ON KEY LABEL CTRL+ENTER DO NCALC 
ON KEY LABEL INS       DO NCALCDOD
ON KEY LABEL F7        DO NCALCF7
ON KEY LABEL F8        DO NCALCF8
ON KEY LABEL ESC       NCALC.RELEASE
ENDPROC

PROCEDURE PORUKADANETAST
   ON KEY LABEL F1    DO HELPN WITH 'PORUKADANE'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PORUKADANE.RELEASE
ENDPROC

PROCEDURE AN0K2TAST
ON KEY LABEL F1    DO HELPN WITH 'AN0K2'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       AN0K2.RELEASE
ENDPROC

PROCEDURE fan0dEONAZTAST
   ON KEY LABEL F1    DO HELPN WITH 'FAN0DEONAZ'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       fan0DEONAZ.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE PORUKATAST
   ON KEY LABEL F1    DO HELPN WITH 'PORUKA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC   PORUKA.RELEASE
ENDPROC


PROCEDURE VPfan0TEKRACTAST
   ON KEY LABEL F1    DO HELPN WITH 'FAN0TEKRAC'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       fan0TEKRAC.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC


PROCEDURE VPIZVESTAJITAST
   ON KEY LABEL F1    DO HELPN WITH 'VPIZVESTAJI'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VPIZVESTAJI.RELEASE
ENDPROC


PROCEDURE VPSERVISTAST
   ON KEY LABEL F1    DO HELPN WITH 'VPSERVIS'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VPSERVIS.RELEASE
ENDPROC

PROCEDURE VPDATCITTAST
   ON KEY LABEL F1    DO HELPN WITH 'VPDATCIT'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VPDATCIT.RELEASE
ENDPROC

PROCEDURE VPEKSPRIJEMPOTTAST
   ON KEY LABEL F1    DO HELPN WITH 'VPEKPRIJEMPOT'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VPEKSPRIJEMPOT.RELEASE
ENDPROC

PROCEDURE VPEKSPRIJEMPOTBRISTAST
   ON KEY LABEL F1    DO HELPN WITH 'VPEKPRIJEMPOTBRIS'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VPEKSPRIJEMPOTBRIS.RELEASE
ENDPROC

PROCEDURE VPSTANJEAKONTTAST
   ON KEY LABEL F1    DO HELPN WITH 'VPSTANJEAKONT'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VPSTANJEAKONT.RELEASE
ENDPROC

PROCEDURE VPSTANJEAKONTFTAST
   ON KEY LABEL F1    DO HELPN WITH 'VPSTANJEAKONTF'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VPSTANJEAKONTF.RELEASE
ENDPROC

PROCEDURE VPSPORAZTAST
   ON KEY LABEL F1    DO HELPN WITH 'VPSPORAZ'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VPSPORAZ.RELEASE
ENDPROC

PROCEDURE VPSPORAZpodTAST
   ON KEY LABEL F1    DO HELPN WITH 'VPSPORAZPOD'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VPSPORAZPOD.RELEASE
ENDPROC

PROCEDURE VPSPORAZKARTTAST
   ON KEY LABEL F1    DO HELPN WITH 'VPSPORAZKART'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VPSPORAZKART.RELEASE
ENDPROC


PROCEDURE VPAPOTROSNJATAST
   ON KEY LABEL F1    DO HELPN WITH 'VPAPOTROSNJA'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VPAPOTROSNJA.RELEASE
ENDPROC


PROCEDURE VC0TAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   VC0.RELEASE
ENDPROC



PROCEDURE VCATAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       VCA.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC


PROCEDURE VCPODTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       VCPOD.RELEASE
ENDPROC

PROCEDURE VcAFTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       VcAF.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC


PROCEDURE WWWVPPOVEZITAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       WWWVPPOVEZI.RELEASE
ENDPROC


PROCEDURE WWWVPVODOMERITAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       WWWVPVODOMERI.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC


PROCEDURE WWWVPKONEKCIJATAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       WWWVPKONEKCIJA.RELEASE
ENDPROC

PROCEDURE WWWVPVODOMERI0TAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       WWWVPVODOMERI0.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE VkUPLTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       VKUPL.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE VkUPLdtAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       VKUPLD.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC


PROCEDURE BO0TAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       BO0.RELEASE
ENDPROC

PROCEDURE VPOPOMTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       VPOPOM.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE VPOPOMDTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       VPOPOMD.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE VPOPOM01TAST
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       VPOPOM01.RELEASE
ENDPROC

PROCEDURE VPOPOM02TAST
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       VPOPOM02.RELEASE
ENDPROC

PROCEDURE VK0TAST
   ON KEY LABEL F1    DO HELPN WITH 'VK0'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VK0.RELEASE
ENDPROC

PROCEDURE VKUPLPREUZMINALTAST
   ON KEY LABEL F1    DO HELPN WITH 'VKUPLPREUZMINAL'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VKUPLPREUZMINAL.RELEASE
ENDPROC


PROCEDURE SETEKGRTAST
   ON KEY LABEL F1    DO HELPN WITH 'SETEKGR'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       SETEKGR.RELEASE
ENDPROC

PROCEDURE BOSERVISTAST
   ON KEY LABEL F1    DO HELPN WITH 'BOSERVIS'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       BOSERVIS.RELEASE
ENDPROC

PROCEDURE VKPOSTTAST
   ON KEY LABEL F1    DO HELPN WITH 'VKPOST'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VKPOST.RELEASE
ENDPROC

PROCEDURE VKPOSTDTAST
   ON KEY LABEL F1    DO HELPN WITH 'VKPOSTD'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VKPOSTD.RELEASE
ENDPROC

PROCEDURE VKPOSTTTAST
   ON KEY LABEL F1    DO HELPN WITH 'VKPOSTT'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VKPOSTT.RELEASE
ENDPROC

PROCEDURE Vb0TAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   Vb0.RELEASE
ENDPROC

PROCEDURE VBATAST   
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       VBA.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE VPREKLAMTAST
   ON KEY LABEL F1    DO HELPN WITH 'VPREKLAM'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VPREKLAM.RELEASE
ENDPROC

PROCEDURE VPREKLAMKARTTAST
   ON KEY LABEL F1    DO HELPN WITH 'VPREKLAMKART'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VPREKLAMKART.RELEASE
ENDPROC

PROCEDURE VPotpisITAST
   ON KEY LABEL F1    DO HELPN WITH 'VPOTPISI'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VPOTPISI.RELEASE
ENDPROC

PROCEDURE VPOTPISIKARTTAST
   ON KEY LABEL F1    DO HELPN WITH 'VPOTPISIKART'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VPOTPISIKART.RELEASE
ENDPROC
