SELECT VT
MPIB=PIB
MGRUPA=GRUPA
MPREZ=PREZ
MIME=IME
MKATEG=KATEG
MSIFRA=SIFRA
*-----------TABELA OBRACUNA------------
select VTOBRAC
MCENOVNIK=CENOVNIK
MBROBRAC=BROBRAC
*------TABELA CENA
select VTCENE
SET ORDER TO 1
SEEK MCENOVNIK
mEdatum=datum
mEvaluta=valuta
mdatOD2=DTOS(datod)
mdatDO2=DTOS(datdo)
mdatOD=datod
mdatDO=datdo
mcGRE=cGRE
MCKW=CKW
MBRNAL='O'+REPLICATE('0',2-LEN(ALLTRIM(STR(MBROBRAC,2,0))))+ALLTRIM(STR(MBROBRAC,2,0))
MPRDUG=0
MCOSTALO1=COSTALO1
MCOSTALO2=COSTALO2
MCOSTALO3=COSTALO3
MTOSTALO1=TOSTALO1
MTOSTALO2=TOSTALO2
MTOSTALO3=TOSTALO3

MPPOGRE=PPOGRE
MPPOOSTA1=PPOOSTA1
MPPOOSTA2=PPOOSTA2
MPPOOSTA3=PPOOSTA3
MPPOKW=PPOKW
MRABPROC=RABPROC
MDANAOBR=DANAOBR
MDANAMES=DANAMES
*SET STEP ON 
IF MDANAMES<>0
   MDANAKOEF=MDANAOBR/MDANAMES
ELSE
mdanakoef=1
endif
*SET STEP ON 
*--------------PROVERA REDOVNOSTI UPLATA----23.10.2011----------

IF MKATEG='2'
   MZARABAT=1
   USE VPK IN 0
   SELECT VPK
   MBRANAL=ALLTRIM(STR(BRANAL,5,0))
   USE
   MANAL=mdata02+'\ANAL'+MBRANAL
   USE &MANAL IN 0 ALIAS ANAL
   SELECT ANAL
   SET ORDER TO 2
   SEEK MSIFRA
   IF FOUND()
      MDUG=0
      DO WHILE.NOT.EOF()
         IF SIFRA<>MSIFRA
            EXIT
         ENDIF   
         IF ZATVAR=' '
            MDUG=MDUG+DUG-POT
            IF VALUTA<=MDATDO
               MZARABAT=0   
            ENDIF
         ENDIF
         SKIP
      ENDDO   
      IF mdug<=0
         mzarabat=1
      endif    
   ENDIF
   SELECT ANAL
   USE
ENDIF
mpdug=0
*-----------KRAJ PROVERE REDOVNOSTI UPLATA FIRMA---------------------
IF MKATEG='1'
   MZARABAT=0   
   SELECT VTUPL
   SET ORDER TO 1
   SEEK MPIB
   *----------PRETRAZIVANJE UPLATA ZA OSTALIM PODACIMA--------  
   if found()
      MPDUG=0
      do while.not.eof()
         if PIB<>mPIB
            exit
         endif
         if DTOS(datdok)<=DTOS(mdatdo)
            IF BRNAL<>mbrnal
               mpdug=mpdug+dug-pot
            endif
         endif    
        skip
     enddo      
   endif
   IF mpdug<=0
      mzarabat=1
   ELSE
      MZARABAT=0   
   endif
ENDIF
*-----------OBRACUN KAMATE---------------
   select VTUPL
   set order to 
   SELECT VT
   USE VPKAM IN 0 EXCLU
   SELECT VPKAM
   DELETE ALL
   PACK

   DO VTKAM WITH MPIB,MDATOD,MDATDO

   SELECT VPKAM
*--------PRENOS KAMATE------------------
   SET ORDER TO 1
   MKAMATA=0
   SELECT VPKAM
   SET ORDER TO 1
   SEEK MPIB
   IF FOUND()
      MKAMATA=0
      DO WHILE.NOT.EOF()
         IF PIB<>MPIB
            EXIT
         ENDIF
         IF DATPOC>=MDATOD.AND.DATPOC<=MDATDO
            mKAMATA=mKAMATA+KAMATA
         ENDIF   
         SKIP
      ENDDO
   ENDIF
   *DO VPPRENKAM WITH MPIB,MDATOD,MDATDO
   SELECT VPKAM
   USE
*---------POCETNI POODACI
   SELECT VT  
   REPLACE DATDOK WITH MEDATUM
   REPLACE VALUTA WITH MEVALUTA
   REPLACE BRNAL WITH MBRNAL
*   REPLACE MES WITH MMES
   IF MKAMATA>0
      REPLACE KAMATA WITH ROUND(MKAMATA,0)
   ELSE
      REPLACE KAMATA WITH 0
   ENDIF
*------------OBRACUN
IF PGRE<>' '
   REPLACE GRE WITH ROUND(POVOBJ*MCGRE*MDANAKOEF,2)
   REPLACE PORGRE WITH ROUND(GRE*MPPOGRE/100,2)
ELSE
   REPLACE GRE WITH 0
   REPLACE PORGRE WITH 0
ENDIF

   REPLACE DINKW WITH ROUND(POTSTAN*MCKW*MDANAKOEF,2)
   REPLACE PORKW WITH ROUND(DINKW*MPPOKW/100,2)

*------------OBRACUN ZA OSTALO
IF POSTALO1<>' '
   REPLACE OSTALO1 WITH ROUND(MCOSTALO1*MDANAKOEF,2)
   REPLACE POROSTA1 WITH ROUND(MPPOOSTA1*OSTALO1/100,2)
   REPLACE TOSTALO1 WITH MTOSTALO1
ELSE
   REPLACE OSTALO1 WITH 0
   REPLACE POROSTA1 WITH 0
   REPLACE TOSTALO1 WITH ''
ENDIF

IF POSTALO2<>' '
   REPLACE OSTALO2 WITH ROUND(MCOSTALO2*MDANAKOEF,2)
   REPLACE POROSTA2 WITH ROUND(MPPOOSTA2*OSTALO2/100,2)
   REPLACE TOSTALO2 WITH MTOSTALO2
ELSE
   REPLACE OSTALO2 WITH 0
   REPLACE POROSTA2 WITH 0
  REPLACE TOSTALO2 WITH ''
ENDIF

IF POSTALO3<>' '
   REPLACE OSTALO3 WITH ROUND(MCOSTALO3*MDANAKOEF,2)
   REPLACE POROSTA3 WITH ROUND(MPPOOSTA3*OSTALO3/100,2)
   REPLACE TOSTALO3 WITH MTOSTALO3
ELSE
   REPLACE OSTALO3 WITH 0
   REPLACE POROSTA3 WITH 0
   REPLACE TOSTALO3 WITH ''
ENDIF

*---------OBRACUN RABATA -------

MRABAT=0
MRABATPOR=0
IF MZARABAT=1
   MRABAT=ROUND(GRE*MRABPROC/100,2)
   MRABATPOR=ROUND(PORGRE*MRABPROC/100,2)
   REPLACE RABPROC WITH MRABPROC
ENDIF

REPLACE RABAT WITH MRABAT
REPLACE RABATPOR WITH MRABATPOR

*---------OBRACUN RABATA2 -------

MRABPROC2=RABPROC2
MRABAT2=0
MRABAT2=ROUND(GRE*MRABPROC2/100,2)
MRABATPOR2=ROUND(PORGRE*MRABPROC2/100,2)
REPLACE RABat2 WITH MRABat2
REPLACE RABATPOR2 WITH MRABATPOR2

*---------RASPODELA PORESKIH STOPA I OSNOVICA-----------------
MPORGRE8=0
MPORGRE18=0
MOSNGRE18=0
MOSNGRE8=0
MOSNGRE0=0
MPPOOSTA18=0
MPOROSTA18=0
MOSNOSTA18=0
MPPOOSTA118=0
MPOROSTA118=0
MOSNOSTA118=0
MOSNOSTA10=0
MPPOOSTA28=0
MPOROSTA28=0
MOSNOSTA28=0
MPPOOSTA218=0
MPOROSTA218=0
MOSNOSTA218=0
MOSNOSTA20=0
MPPOOSTA38=0
MPOROSTA38=0
MOSNOSTA38=0
MPPOOSTA318=0
MPOROSTA318=0
MOSNOSTA318=0
MOSNOSTA30=0

MPORKW8=0
MPORKW18=0
MOSNKW18=0
MOSNKW8=0
MOSNKW0=0
 
  
IF MPPOGRE<>0
   IF MPPOGRE=VAL(TNSTOPA)
      MPORGRE8=PORGRE-MRABATPOR-mrabatpor2
      MOSNGRE8=GRE-MRABAT-mrabat2
   ENDIF
   IF MPPOGRE=VAL(tostopa)
      MPORGRE18=PORGRE-MRABATPOR-mrabatpor2
      MOSNGRE18=GRE-MRABAT-mrabat2
   ENDIF      
ELSE
   MOSNGRE0=GRE-MRABAT-mrabat2
ENDIF

IF MPPOOSTA1<>0
   IF MPPOOSTA1=VAL(TNSTOPA)
      MPOROSTA18=POROSTA1
      MOSNOSTA18=OSTALO1
   ENDIF
   IF MPPOOSTA1=VAL(tostopa)
      MPOROSTA118=POROSTA1
      MOSNOSTA118=OSTALO1
   ENDIF
ELSE
   MOSNOSTA10=0
ENDIF   

IF MPPOOSTA2<>0
   IF MPPOOSTA2=VAL(TNSTOPA)
      MPOROSTA28=POROSTA2
      MOSNOSTA28=OSTALO2
   ENDIF
   IF MPPOOSTA2=VAL(tostopa)
      MPOROSTA218=POROSTA2
      MOSNOSTA218=OSTALO2
   ENDIF
ELSE
   MOSNOSTA20=0
ENDIF   

IF MPPOOSTA3<>0
   IF MPPOOSTA3=VAL(TNSTOPA)
      MPOROSTA38=POROSTA3
      MOSNOSTA38=OSTALO3
   ENDIF
   IF MPPOOSTA3=VAL(tostopa)
      MPOROSTA318=POROSTA3
      MOSNOSTA318=OSTALO3
   ENDIF
ELSE
   MOSNOSTA30=0
ENDIF   

IF MPPOKW<>0
   IF MPPOKW=8
      MPORKW8=PORKW
      MOSNKW8=DINKW
   ENDIF
   IF MPPOKW=VAL(tostopa)
      MPORKW18=PORKW
      MOSNKW18=DINKW
   ENDIF      
ELSE
   MOSNKW0=DINKW
ENDIF



MPOR8=MPORGRE8+MPOROSTA18+MPOROSTA28+MPOROSTA38+MPORKW8
MOSN8=MOSNGRE8+MOSNOSTA18+MOSNOSTA28+MOSNOSTA38+MOSNKW8
MPOR18=MPORGRE18+MPOROSTA118+MPOROSTA218+MPOROSTA318+MPORKW18
MOSN18=MOSNGRE18+MOSNOSTA118+MOSNOSTA218+MOSNOSTA318+MOSNKW18
MOSN0=MOSNGRE0+MOSNOSTA10+MOSNOSTA20+MOSNOSTA30+MOSNKW0

REPLACE OSN0 WITH MOSN0
REPLACE OSN8 WITH MOSN8
REPLACE OSN18 WITH MOSN18
REPLACE POR8 WITH MPOR8
REPLACE POR18 WITH MPOR18
REPLACE CENOVNIK WITH MCENOVNIK

*----OBRACUN UKUPNO---------------------
   MUKUPNO=GRE+OSTALO1+OSTALO2+OSTALO3+DINKW-MRABAT-mrabat2
   REPLACE POREZ WITH PORGRE+POROSTA1+POROSTA2+POROSTA3+PORKW-MRABATPOR-MRABATPOR2
   REPLACE UKUPNO WITH MUKUPNO+POREZ+KAMATA
   REPLACE SVEGA WITH UKUPNO

   MPR2DUG=0
   MUPLAC=0
   mispr=0
   MOSTALO=0
IF MKATEG='1'
   SELECT VTUPL
   SET ORDER TO 1
   SEEK MPIB
*----------PRETRAZIVANJE UPLATA ZA OSTALIM PODACIMA--------  
   if found()
      do while.not.eof()
         if PIB<>mPIB
            exit
         endif
         if DTOS(datDOK)<DTOS(mdatod)
            mpr2dug=mpr2dug+dug-pot
         endif    
         if DTOS(datDOK)>=DTOS(mdatod).and.DTOS(datDOK)<=DTOS(mdatdo)
            IF BRNAL<>MBRNAL 
               MOSTALO=MOSTALO+DUG
            ENDIF
         ENDIF
         if DTOS(DATDOK)>=DTOS(mdatod).and.DTOS(DATDOK)<=DTOS(mdatdo)
           mUPLAC=MUPLAC+POT
           mDATDOK=DATDOK 
        endif
        skip
     enddo      
  endif
ENDIF
*----------POPUNJAVANJE GLAVNE TABELE----------
   SELECT VT
   REPLACE DUG WITH MPR2DUG
   REPLACE UPLAC WITH MUPLAC
   REPLACE OSTALO WITH MOSTALO
   REPLACE RABAT  WITH MRABAT
   REPLACE RABAT2 WITH MRABAT2
   MSALDO=SVEGA+DUG-UPLAC+MOSTALO
*   SET STEP ON 
*   IF MSALDO>INT(MSALDO)
*      MZAOKRUZ=MSALDO-INT(MSALDO)
*   ELSE
*      MZAOKRUZ=-(MSALDO-INT(MSALDO))
*   ENDIF 
*   REPLACE ZAOKRUZ WITH -MZAOKRUZ
*   REPLACE SALDO WITH MSALDO-MZAOKRUZ
   REPLACE SALDO WITH MSALDO
   REPLACE ZAOKRUZ WITH 0 
   SET CENTURY OFF
   mbrrac=REPLICATE('0',2-LEN(ALLTRIM(STR(MBROBRAC,2,0))))+ALLTRIM(STR(MBROBRAC,2,0))+SUBSTR(DTOC(MDATDO),7,2)+ALLTRIM(pib)
   SET CENTURY ON
   REPLACE BRRAC WITH MBRRAC
   M1=VAL(mbrrac)
   M2=(M1*100/97)-INT(M1*100/97)
   M3=ROUND(97*M2,0)
   M4=98-M3
   IF M4<=9
      M4='0'+STR(M4,1,0)
   ELSE
      M4=STR(M4,2,0)
   ENDIF      
   REPLACE model WITH +M4+'-'+ALLTRIM(mbrrac)
   
   SELECT VTUPLD
   SET ORDER TO 5
   SET EXACT OFF
   GO TOP
   DO WHILE.T.
      SEEK MBRRAC
      IF FOUND()
         REPLACE PIB WITH SPACE(13)
         REPLACE BRNAL WITH SPACE(6)
         REPLACE BRRAC WITH ''
         REPLACE GRUPA WITH ''
         REPLACE CENOVNIK WITH 0
         REPLACE DATDOK WITH CTOD('')
         REPLACE VALUTA WITH CTOD('')
         REPLACE DATOD WITH CTOD('')
         REPLACE DATDO WITH CTOD('')
         REPLACE CGRE WITH 0
         REPLACE COSTALO1 WITH 0
         REPLACE COSTALO2 WITH 0
         REPLACE COSTALO3 WITH 0

         REPLACE PPOGRE WITH 0
         
         REPLACE PPOOSTA1 WITH 0
         REPLACE PPOOSTA2 WITH 0
         REPLACE PPOOSTA3 WITH 0
         REPLACE POROSTA1 WITH 0
         REPLACE POROSTA2 WITH 0
         REPLACE POROSTA3 WITH 0

         REPLACE PPOKW WITH 0
         
         REPLACE POREZ WITH 0
         REPLACE PORGRE WITH 0
         REPLACE OSTALO1 WITH 0
         REPLACE OSTALO2 WITH 0
         REPLACE OSTALO3 WITH 0

         REPLACE PORKW WITH 0
         
         REPLACE UKUPNO WITH 0
         REPLACE OSTALO WITH 0
         REPLACE KAMATA WITH 0
         REPLACE POREZ WITH 0
         REPLACE DUG WITH 0
         REPLACE SALDO WITH 0
         REPLACE ZAOKRUZ WITH 0
         REPLACE RABAT WITH 0
         REPLACE RABATPOR WITH 0
         REPLACE RABAT2 WITH 0
         REPLACE RABATPOR2 WITH 0
         REPLACE RABPROC WITH 0
         REPLACE RABPROC2 WITH 0
         REPLACE SVEGA WITH 0
         REPLACE OSN0 WITH 0
         REPLACE OSN8 WITH 0
         REPLACE OSN18 WITH 0
         REPLACE POR8 WITH 0
         REPLACE POR18 WITH 0
         REPLACE POCKW WITH 0
         REPLACE ZADKW WITH 0
         
         LOOP 
      ELSE
         EXIT
      ENDIF
   ENDDO   
  
   SELECT VT
   MGRUPA=GRUPA
   MDATDOK=DATDOK
   MVALUTA=VALUTA

   MGRE=GRE
   MRABAT=RABAT
   MRABAT2=RABAT2
   MRABATPOR=RABATPOR
   MRABATPOR2=RABATPOR2
   MDINKW=DINKW
   MOSTALO1=OSTALO1
   MOSTALO2=OSTALO2
   MOSTALO3=OSTALO3
      
   MPORGRE=PORGRE
   MRABATPOR=RABATPOR
   MRABATPOR2=RABATPOR2
   MPOROSTA1=POROSTA1
   MPOROSTA2=POROSTA2
   MPOROSTA3=POROSTA3
   MPORKW=PORKW

   MUKUPNO=UKUPNO
   MOSTALO=OSTALO
   MZAOKRUZ=ZAOKRUZ
   
   mdug=dug
   MSVEGA=SVEGA
   MUPLAC=UPLAC
   MPOREZ=POREZ
   MKAMATA=KAMATA
   MBRRAC=BRRAC
   MMODEL=MODEL
   MPGRE=PGRE
   MPOSTALO1=POSTALO1
   MPOSTALO2=POSTALO2
   MPOSTALO3=POSTALO3
   MPOVOBJ =POVOBJ
   MPOCKW=POCKW
   MZADKW=ZADKW
   MULICA=ULICA
   MIME_PREZ=ALLTRIM(PREZ)+' '+IME
   MRABPROC=RABPROC
   MRABPROC2=RABPROC2
   *-------CENE-----------------
   REPLACE CGRE WITH McGRE
   REPLACE COSTALO1 WITH MCOSTALO1
   REPLACE COSTALO2 WITH MCOSTALO2
   REPLACE COSTALO3 WITH MCOSTALO3
   REPLACE CKW WITH MCKW
   
   *--------STOPE POREZA-------
   REPLACE PPOGRE WITH MPPOGRE
   REPLACE PPOOSTA1 WITH MPPOOSTA1
   REPLACE PPOOSTA2 WITH MPPOOSTA2
   REPLACE PPOOSTA3 WITH MPPOOSTA3
   REPLACE PPOKW WITH MPPOKW
   *----------POREZ------------
   REPLACE PORGRE  WITH MPORGRE
*   REPLACE RABATPOR WITH MRABATPOR
*   REPLACE RABAT WITH MRABAT
   REPLACE POROSTA1 WITH MPOROSTA1
   REPLACE POROSTA2 WITH MPOROSTA2
   REPLACE POROSTA3 WITH MPOROSTA3
   REPLACE PORKW  WITH MPORKW
   
   REPLACE DATOD WITH MDATOD
   REPLACE DATDO WITH MDATDO
   
   REPLACE OSN0 WITH MOSN0
   REPLACE OSN8 WITH MOSN8
   REPLACE OSN18 WITH MOSN18
   REPLACE POR8 WITH MPOR8
   REPLACE POR18 WITH MPOR18
   replace pockw WITH mpockw
   replace zadkw WITH mzadkw
   replace ostalo1 WITH mostalo1
   replace ostalo2 WITH mostalo2
   replace ostalo3 WITH mostalo3
      
   replace tostalo1 WITH mtostalo1
   replace tostalo2 WITH mtostalo2
   replace tostalo3 WITH mtostalo3

      
   SCATTER NAME POLJA
*---------DODAVANJE POLJA-----------
   SELECT VTUPLD
   APPEND BLANK
   GATHER NAME POLJA
   *SET STEP ON 
   IF MKATEG='1'
   
   SELECT VTUPL
   SET ORDER TO 5
   SEEK MBRRAC 
   IF FOUND()
       DO WHILE.NOT.EOF()
          IF BRRAC<>MBRRAC
             EXIT
          ENDIF
          IF DUG<>0
             REPLACE DUG WITH 0
             REPLACE PIB WITH ''
             *REPLACE BRRAC WITH ''
          ENDIF    
          SKIP
       ENDDO
   ENDIF    
   mbrrack='K-'+ALLTRIM(MBRRAC)
   SEEK MBRRACk 
   IF FOUND()
       DO WHILE.NOT.EOF()
          IF ALLTRIM(BRRAC)<>ALLTRIM(MBRRACk)
             EXIT
          ENDIF
          IF DUG<>0
             REPLACE DUG WITH 0
             REPLACE PIB WITH ''
             *REPLACE BRRAC WITH ''
          ENDIF    
          SKIP
       ENDDO
   ENDIF    
*   SEEK MBRRACk    
*   brow
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE GRUPA WITH MGRUPA
   REPLACE DUG WITH MSVEGA+MZAOKRUZ-mkamata
   REPLACE DATDOK WITH MDATDOK
   REPLACE VALUTA WITH MVALUTA
   REPLACE BRRAC WITH MBRRAC
   REPLACE BRNAL WITH MBRNAL
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE GRUPA WITH MGRUPA
   REPLACE DUG WITH mkamata
   REPLACE DATDOK WITH MDATDOK
   REPLACE VALUTA WITH MVALUTA
   REPLACE BRRAC WITH 'K-'+ALLTRIM(MBRRAC)
   REPLACE BRNAL WITH MBRNAL
   
   ENDIF
   SELECT VT
