
PROCEDURE VT0TAST
   ON KEY LABEL F1    DO HELPN WITH 'VT0'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   VT0.RELEASE
ENDPROC


PROCEDURE VTATAST
   ON KEY LABEL F1    DO HELPN WITH 'VTA'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       VTA.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC

PROCEDURE VT00TAST
   ON KEY LABEL F1    DO HELPN WITH 'VT00'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   VT00.RELEASE
ENDPROC
 
PROCEDURE VTOBRAC0TAST
   ON KEY LABEL F1    DO HELPN WITH 'VTOBRAC0'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   VTOBRAC0.RELEASE
ENDPROC
 


PROCEDURE VTAKART0TAST
   ON KEY LABEL F1    DO HELPN WITH 'VTAKART0'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   VTAKART0.RELEASE
ENDPROC


PROCEDURE VTCENETAST
   ON KEY LABEL F1    DO HELPN WITH 'VTCENE'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   VTCENE.RELEASE
ENDPROC




PROCEDURE VTUPLTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL ESC       VTUPL.RELEASE
   ON KEY LABEL F2        ! /N CALC.EXE
ENDPROC

PROCEDURE VTUPLDTAST
*   ON KEY LABEL F1    DO HELP
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC       VTUPLD.RELEASE
   ON KEY LABEL CTRL+PGDN DO IDIKRAJ
   ON KEY LABEL CTRL+PGUP DO IDIPOC
ENDPROC




PROCEDURE VTRACTXTTAST
   ON KEY LABEL F1    DO HELPN WITH 'VTRACTXT'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   VTRACTXT.RELEASE
ENDPROC


PROCEDURE VTRACTX2TAST
   ON KEY LABEL F1    DO HELPN WITH 'VTRACTX2'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   VTRACTX2.RELEASE
ENDPROC

PROCEDURE VTSPISTAST
   ON KEY LABEL F1    DO HELPN WITH 'VTSPIS'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   VTSPIS.RELEASE
ENDPROC

PROCEDURE VTSPISSOCTAST
   ON KEY LABEL F1    DO HELPN WITH 'VTSPISSOC'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   VTSPISSOC.RELEASE
ENDPROC

PROCEDURE VTSPISVLATAST
   ON KEY LABEL F1    DO HELPN WITH 'VTSPISVLA'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   VTSPISVLA.RELEASE
ENDPROC


PROCEDURE VTSPISDUGTAST
   ON KEY LABEL F1    DO HELPN WITH 'VTSPISDUG'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   VTSPISDUG.RELEASE
ENDPROC

PROCEDURE VTFKART0TAST
   ON KEY LABEL F1    DO HELPN WITH 'VTFKART0'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   VTFKART0.RELEASE
ENDPROC


PROCEDURE VTSPISSALDOKSTAST
   ON KEY LABEL F1    DO HELPN WITH 'VTSPISSALDOKS'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   VTSPISSALDOKS.RELEASE
ENDPROC

PROCEDURE VTUPLPREUZMINALTAST
   ON KEY LABEL F1    DO HELPN WITH 'VTUPLPREUZMINAL'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   VTUPLPREUZMINAL.RELEASE
ENDPROC


PROCEDURE VTANALIZVOTAST
   ON KEY LABEL F1    DO HELPN WITH 'VTANALIZVO'
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL ESC       VTANALIZVO.RELEASE
ENDPROC


PROCEDURE VTZGRADETAST
   ON KEY LABEL F1    DO HELPN WITH 'VTZGRADE'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   VTZGRADE.RELEASE
ENDPROC

PROCEDURE VTSPISMERNIHMESTATAST
   ON KEY LABEL F1    DO HELPN WITH 'VTSPISMERNIHMESTA'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   VTSPISMERNIHMESTA.RELEASE
ENDPROC

PROCEDURE VPAPOTROSNJATATAST
   ON KEY LABEL F1    DO HELPN WITH 'VPAPOTROSNJA'
   ON KEY LABEL CTRL+ENTER DO NCALC 
   ON KEY LABEL F2        ! /N CALC.EXE
   ON KEY LABEL ESC   VPAPOTROSNJA.RELEASE
ENDPROC