MPIB=VTUPL2.TXTPIB.VALUE
MDATUM=VTUPL2.TXTDATUM.VALUE
MPOT=VTUPL2.TXTPOT.VALUE
MBRNAL=VTUPL2.TXTBRNAL.VALUE
MGRUPA=VTUPL2.TXTGRUPA.VALUE
MDANAS=DATE()
MVREME=TIME()
MVALUTA=VTUPL2.TXTVALUTA.VALUE
MOPIS=VTUPL2.TXTOPIS.VALUE
IF MPOT<>0
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE DATDOK WITH MDATUM
   REPLACE POT WITH MPOT
   REPLACE BRNAL WITH MBRNAL
   REPLACE GRUPA WITH MGRUPA
   REPLACE DATUM WITH MDANAS
   REPLACE VREME WITH MVREME
   REPLACE VALUTA WITH MVALUTA
   REPLACE OPIS WITH MOPIS
   SELECT VTUPL
   APPEND BLANK
   REPLACE PIB WITH MPIB
   REPLACE DATDOK WITH MDATUM
   REPLACE POT WITH MPOT
   REPLACE BRNAL WITH MBRNAL
   REPLACE GRUPA WITH MGRUPA
   REPLACE DATUM WITH MDANAS
   REPLACE VREME WITH MVREME
   REPLACE VALUTA WITH MVALUTA
   REPLACE OPIS WITH MOPIS
   SELECT VTUPL2
ENDIF
VTUPL2.TXTPIB.Value=SPACE(13)
VTUPL2.TXTPOT.Value=0
VTUPL2.TXTPIB.SETFOCUS 