PARAMETERS A1,A2,A3

PUSH KEY CLEAR

SELECT BILSEMA
MAOP=A1
SEEK MAOP
IF FOUND()
   MNETO=NETO
   MPRETH=PRETH
   SELECT BILSEMA2
   SET ORDER TO 1
   MREDNI=A2
   SEEK MREDNI
   IF FOUND()
      IF A3<>'-'
      REPLACE NETO WITH NETO+MNETO
      REPLACE PRETH WITH PRETH+MPRETH
      ELSE
      REPLACE NETO WITH NETO-MNETO
      REPLACE PRETH WITH PRETH-MPRETH
      ENDIF
      
   ENDIF
ENDIF
POP KEY