PARAMETERS MAOP
    SELECT BILSEMAS
    LOCATE FOR AOP=MAOP
    IF FOUND()
       MPRETH=NETO
       SELECT BTG
       LOCATE FOR AOP=MAOP
       IF FOUND()
          REPLACE PRETH WITH MPRETH    
       ENDIF
    ENDIF   
