procedure RACIOPUNI0
PUSH KEY CLEAR
SELECT RACIO
GO TOP
IF RECCOUNT() <1
     DO RACIOPUNI WITH '0101','LIKVIDNOST','OPŠTA LIKVIDNOST','OBRTNA SREDSTVA/KRATKOROÈNE OBAVEZE' 
     DO RACIOPUNI WITH '0102','LIKVIDNOST','UBRZANA LIKVIDNOST','OBRTNA SREDSTVA-ZALIHE/KRATKOROÈNE OBAVEZE' 
     DO RACIOPUNI WITH '0201','ZADUŽENOST','ZADUŽENOST','UKUPAN DUG/UKUPNA SREDSTVA' 
     DO RACIOPUNI WITH '0202','ZADUŽENOST','ODNOS DUGA PREMA KAPITALU','UKUPAN DUG/UKUPAN KAPITAL'      
     DO RACIOPUNI WITH '0203','ZADUŽENOST','KOEFICIJENT POKRIÆA KAMATE','EBIT RASHODI ZA KAMATE'           
     DO RACIOPUNI WITH '0204','ZADUŽENOST','KOEFICIJENT FINANSIJSKE STABILNOSTI','DUGOROÈNE OBAVEZE+KAPITAL/STALNA IMOVINA+ZALIHE'           
     DO RACIOPUNI WITH '0301','AKTIVNOSTI','PROSEÈAN PERIOD DRŽANJA ZALIHA','PROSEÈNE ZALIHE/PRIHOD OD PRODAJE*365'                
     DO RACIOPUNI WITH '0302','AKTIVNOSTI','PROSEÈAN PERIOD NAPLATE POTRAŽIVANJA','PROSEÈNI SALDO KUPACA/PRIHOD ODPRODAJE*365'                     
     DO RACIOPUNI WITH '0303','AKTIVNOSTI','PROSEÈAN PERIOD PLAÆANJA OBAVEZA','OBAVEZE PREMA DOBAVLJAÈIMA/PRIHOD ODPRODAJE*365'                          
     DO RACIOPUNI WITH '0304','AKTIVNOSTI','ISKORIŠÆENOST FIKSNIH SREDSTAVA','PRIHOD OD PRODAJE / NETO FIKSNA SREDSTVA'                               
     DO RACIOPUNI WITH '0305','AKTIVNOSTI','ISKORIŠÆENOST UKUPNIH SREDSTAVA','PRIHOD OD PRODAJE / UKUPNA SREDSTVA'                                    
     DO RACIOPUNI WITH '0401','RENTABILNOST','PROFITNA BRUTO MARGINA','UKUPNA DOBIT / PRIHOD OD PRODAJE'                                    
     DO RACIOPUNI WITH '0402','RENTABILNOST','PROFITNA NETO MARGINA','NETO DOBIT / PRIHOD OD PRODAJE'                                         
     DO RACIOPUNI WITH '0403','RENTABILNOST','EBIT MARGINA','EBIT / UKUPAN PRIHOD'                                              
     DO RACIOPUNI WITH '0404','RENTABILNOST','EBITDA MARGINA','EBITDA / UKUPAN PRIHOD'                                                   
     DO RACIOPUNI WITH '0405','RENTABILNOST','STOPA POVRAÆAJA NA UKUPNA SREDSTVA (ROA)','NETO DOBIT / UKUPNA SREDSTVA'
     DO RACIOPUNI WITH '0406','RENTABILNOST','STOPA POVRAÆAJA NA KAPITAL (ROE)','NETO DOBIT / KAPITAL'
     DO RACIOPUNI WITH '0501','EKONOMIÈNOST','EKONOMIÈNOST POSLOVANJA','POSLOVNI PRIHODI/POSLOVNI RASHODI'    
     DO RACIOPUNI WITH '0601','PRODUKTIVNOST','JEDINICNI TROSKOVI RADA','BRUTO ZARADA I LIÈNI RASHODI / UKUPAN PRIHOD'
     DO RACIOPUNI WITH '0602','PRODUKTIVNOST','PRODUKTIVNOST RADA','PRIHOD OD PRODAJE/BROJ ZAPOSLENIH'
ENDIF
POP KEY
ENDPROC

procedure RACIOPUNI
   PARAMETERS MGRUPA,MINDIKATOR,MNAZIV,MOPIS
   PUSH KEY CLEAR
   APPEND BLANK
   REPLACE GRUPA WITH mgrupa
   replace INDIKATOR with MINDIKATOR
   replace NAZIV with MNAZIV   
   replace opis with mopis
   POP KEY
endproc

